/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@link Xxx} for codepoint U+01xx (Latin Extended-A and beginning for part B).
 */
final class X01 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  Letter.UP_A, // 0x00
  Letter.LO_A, // 0x01
  Letter.UP_A, // 0x02
  Letter.LO_A, // 0x03
  Letter.UP_A, // 0x04
  Letter.LO_A, // 0x05
  Letter.UP_C, // 0x06
  Letter.LO_C, // 0x07
  Letter.UP_C, // 0x08
  Letter.LO_C, // 0x09
  Letter.UP_C, // 0x0a
  Letter.LO_C, // 0x0b
  Letter.UP_C, // 0x0c
  Letter.LO_C, // 0x0d
  Letter.UP_D, // 0x0e
  Letter.LO_D, // 0x0f
  Letter.UP_D, // 0x10
  Letter.LO_D, // 0x11
  Letter.UP_E, // 0x12
  Letter.LO_E, // 0x13
  Letter.UP_E, // 0x14
  Letter.LO_E, // 0x15
  Letter.UP_E, // 0x16
  Letter.LO_E, // 0x17
  Letter.UP_E, // 0x18
  Letter.LO_E, // 0x19
  Letter.UP_E, // 0x1a
  Letter.LO_E, // 0x1b
  Letter.UP_G, // 0x1c
  Letter.LO_G, // 0x1d
  Letter.UP_G, // 0x1e
  Letter.LO_G, // 0x1f
  Letter.UP_G, // 0x20
  Letter.LO_G, // 0x21
  Letter.UP_G, // 0x22
  Letter.LO_G, // 0x23
  Letter.UP_H, // 0x24
  Letter.LO_H, // 0x25
  Letter.UP_H, // 0x26
  Letter.LO_H, // 0x27
  Letter.UP_I, // 0x28
  Letter.LO_I, // 0x29
  Letter.UP_I, // 0x2a
  Letter.LO_I, // 0x2b
  Letter.UP_I, // 0x2c
  Letter.LO_I, // 0x2d
  Letter.UP_I, // 0x2e
  Letter.LO_I, // 0x2f
  Letter.UP_I, // 0x30
  Letter.LO_I, // 0x31
  CAP_IJ, // 0x32
  LO_IJ, // 0x33
  Letter.UP_J, // 0x34
  Letter.LO_J, // 0x35
  Letter.UP_K, // 0x36
  Letter.LO_K, // 0x37
  Letter.LO_K, // 0x38
  Letter.UP_L, // 0x39
  Letter.LO_L, // 0x3a
  Letter.UP_L, // 0x3b
  Letter.LO_L, // 0x3c
  Letter.UP_L, // 0x3d
  Letter.LO_L, // 0x3e
  Letter.UP_L, // 0x3f
  Letter.LO_L, // 0x40
  Letter.UP_L, // 0x41
  Letter.LO_L, // 0x42
  Letter.UP_N, // 0x43
  Letter.LO_N, // 0x44
  Letter.UP_N, // 0x45
  Letter.LO_N, // 0x46
  Letter.UP_N, // 0x47
  Letter.LO_N, // 0x48
  new Chars("\'n"), // 0x49
  new Chars("NG"), // 0x4a
  LO_NG, // 0x4b
  Letter.UP_O, // 0x4c
  Letter.LO_O, // 0x4d
  Letter.UP_O, // 0x4e
  Letter.LO_O, // 0x4f
  Letter.UP_O, // 0x50
  Letter.LO_O, // 0x51
  UP_OE, // 0x52
  LO_OE, // 0x53
  Letter.UP_R, // 0x54
  Letter.LO_R, // 0x55
  Letter.UP_R, // 0x56
  Letter.LO_R, // 0x57
  Letter.UP_R, // 0x58
  Letter.LO_R, // 0x59
  Letter.UP_S, // 0x5a
  Letter.LO_S, // 0x5b
  Letter.UP_S, // 0x5c
  Letter.LO_S, // 0x5d
  Letter.UP_S, // 0x5e
  Letter.LO_S, // 0x5f
  Letter.UP_S, // 0x60
  Letter.LO_S, // 0x61
  Letter.UP_T, // 0x62
  Letter.LO_T, // 0x63
  Letter.UP_T, // 0x64
  Letter.LO_T, // 0x65
  Letter.UP_T, // 0x66
  Letter.LO_T, // 0x67
  Letter.UP_U, // 0x68
  Letter.LO_U, // 0x69
  Letter.UP_U, // 0x6a
  Letter.LO_U, // 0x6b
  Letter.UP_U, // 0x6c
  Letter.LO_U, // 0x6d
  Letter.UP_U, // 0x6e
  Letter.LO_U, // 0x6f
  Letter.UP_U, // 0x70
  Letter.LO_U, // 0x71
  Letter.UP_U, // 0x72
  Letter.LO_U, // 0x73
  Letter.UP_W, // 0x74
  Letter.LO_W, // 0x75
  Letter.UP_Y, // 0x76
  Letter.LO_Y, // 0x77
  Letter.UP_Y, // 0x78
  Letter.UP_Z, // 0x79
  Letter.LO_Z, // 0x7a
  Letter.UP_Z, // 0x7b
  Letter.LO_Z, // 0x7c
  Letter.UP_Z, // 0x7d
  Letter.LO_Z, // 0x7e
  Letter.LO_S, // 0x7f
  Letter.LO_B, // 0x80
  Letter.UP_B, // 0x81
  Letter.UP_B, // 0x82
  Letter.LO_B, // 0x83
  Digit._6, // 0x84
  Digit._6, // 0x85
  Letter.UP_O, // 0x86
  Letter.UP_C, // 0x87
  Letter.LO_C, // 0x88
  Letter.UP_D, // 0x89
  Letter.UP_D, // 0x8a
  Letter.UP_D, // 0x8b
  Letter.LO_D, // 0x8c
  Letter.LO_D, // 0x8d
  Digit._3, // 0x8e
  Char.AT, // 0x8f
  Letter.UP_E, // 0x90
  Letter.UP_F, // 0x91
  Letter.LO_F, // 0x92
  Letter.UP_G, // 0x93
  Letter.UP_G, // 0x94
  new Chars("hv"), // 0x95
  Letter.UP_I, // 0x96
  Letter.UP_I, // 0x97
  Letter.UP_K, // 0x98
  Letter.LO_K, // 0x99
  Letter.LO_L, // 0x9a
  Letter.LO_L, // 0x9b
  Letter.UP_W, // 0x9c
  Letter.UP_N, // 0x9d
  Letter.LO_N, // 0x9e
  Letter.UP_O, // 0x9f
  Letter.UP_O, // 0xa0
  Letter.LO_O, // 0xa1
  UP_OI, // 0xa2
  LO_OI, // 0xa3
  Letter.UP_P, // 0xa4
  Letter.LO_P, // 0xa5
  new Chars("Yr"), // 0xa6
  Digit._2, // 0xa7
  Digit._2, // 0xa8
  CAP_SH, // 0xa9
  LO_SH, // 0xaa
  Letter.LO_T, // 0xab
  Letter.UP_T, // 0xac
  Letter.LO_T, // 0xad
  Letter.UP_T, // 0xae
  Letter.UP_U, // 0xaf
  Letter.LO_U, // 0xb0
  Letter.UP_Y, // 0xb1
  Letter.UP_V, // 0xb2
  Letter.UP_Y, // 0xb3
  Letter.LO_Y, // 0xb4
  Letter.UP_Z, // 0xb5
  Letter.LO_Z, // 0xb6
  CAP_ZH, // 0xb7
  CAP_ZH, // 0xb8
  LO_ZH, // 0xb9
  LO_ZH, // 0xba
  Digit._2, // 0xbb
  Digit._5, // 0xbc
  Digit._5, // 0xbd
  LO_TS, // 0xbe
  Letter.LO_W, // 0xbf
  Char.PIPE, // 0xc0
  new Chars("||"), // 0xc1
  new Chars("|="), // 0xc2
  Char.EXCLAMATION, // 0xc3
  UP_DZ, // 0xc4
  CAP_DZ, // 0xc5
  LO_DZ, // 0xc6
  new Chars("LJ"), // 0xc7
  new Chars("Lj"), // 0xc8
  LO_LJ, // 0xc9
  UP_NJ, // 0xca
  CAP_NJ, // 0xcb
  LO_NJ, // 0xcc
  Letter.UP_A, // 0xcd
  Letter.LO_A, // 0xce
  Letter.UP_I, // 0xcf
  Letter.LO_I, // 0xd0
  Letter.UP_O, // 0xd1
  Letter.LO_O, // 0xd2
  Letter.UP_U, // 0xd3
  Letter.LO_U, // 0xd4
  Letter.UP_U, // 0xd5
  Letter.LO_U, // 0xd6
  Letter.UP_U, // 0xd7
  Letter.LO_U, // 0xd8
  Letter.UP_U, // 0xd9
  Letter.LO_U, // 0xda
  Letter.UP_U, // 0xdb
  Letter.LO_U, // 0xdc
  Char.AT, // 0xdd
  Letter.UP_A, // 0xde
  Letter.LO_A, // 0xdf
  Letter.UP_A, // 0xe0
  Letter.LO_A, // 0xe1
  UP_AE, // 0xe2
  LO_AE, // 0xe3
  Letter.UP_G, // 0xe4
  Letter.LO_G, // 0xe5
  Letter.UP_G, // 0xe6
  Letter.LO_G, // 0xe7
  Letter.UP_K, // 0xe8
  Letter.LO_K, // 0xe9
  Letter.UP_O, // 0xea
  Letter.LO_O, // 0xeb
  Letter.UP_O, // 0xec
  Letter.LO_O, // 0xed
  CAP_ZH, // 0xee
  LO_ZH, // 0xef
  Letter.LO_J, // 0xf0
  UP_DZ, // 0xf1
  CAP_DZ, // 0xf2
  LO_DZ, // 0xf3
  Letter.UP_G, // 0xf4
  Letter.LO_G, // 0xf5
  new Chars("HV"), // 0xf6
  Letter.UP_W, // 0xf7
  Letter.UP_N, // 0xf8
  Letter.LO_N, // 0xf9
  Letter.UP_A, // 0xfa
  Letter.LO_A, // 0xfb
  UP_AE, // 0xfc
  LO_AE, // 0xfd
  Letter.UP_O, // 0xfe
  Letter.LO_O };
}
