/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+1Fxx (Greek Extended).
 */
final class X1f extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  Letter.LO_A, // 0x00
  Letter.LO_A, // 0x01
  Letter.LO_A, // 0x02
  Letter.LO_A, // 0x03
  Letter.LO_A, // 0x04
  Letter.LO_A, // 0x05
  Letter.LO_A, // 0x06
  Letter.LO_A, // 0x07
  Letter.UP_A, // 0x08
  Letter.UP_A, // 0x09
  Letter.UP_A, // 0x0a
  Letter.UP_A, // 0x0b
  Letter.UP_A, // 0x0c
  Letter.UP_A, // 0x0d
  Letter.UP_A, // 0x0e
  Letter.UP_A, // 0x0f
  Letter.LO_E, // 0x10
  Letter.LO_E, // 0x11
  Letter.LO_E, // 0x12
  Letter.LO_E, // 0x13
  Letter.LO_E, // 0x14
  Letter.LO_E, // 0x15
  null, // 0x16
  null, // 0x17
  Letter.UP_E, // 0x18
  Letter.UP_E, // 0x19
  Letter.UP_E, // 0x1a
  Letter.UP_E, // 0x1b
  Letter.UP_E, // 0x1c
  Letter.UP_E, // 0x1d
  null, // 0x1e
  null, // 0x1f
  Letter.LO_E, // 0x20
  Letter.LO_E, // 0x21
  Letter.LO_E, // 0x22
  Letter.LO_E, // 0x23
  Letter.LO_E, // 0x24
  Letter.LO_E, // 0x25
  Letter.LO_E, // 0x26
  Letter.LO_E, // 0x27
  Letter.UP_E, // 0x28
  Letter.UP_E, // 0x29
  Letter.UP_E, // 0x2a
  Letter.UP_E, // 0x2b
  Letter.UP_E, // 0x2c
  Letter.UP_E, // 0x2d
  Letter.UP_E, // 0x2e
  Letter.UP_E, // 0x2f
  Letter.LO_I, // 0x30
  Letter.LO_I, // 0x31
  Letter.LO_I, // 0x32
  Letter.LO_I, // 0x33
  Letter.LO_I, // 0x34
  Letter.LO_I, // 0x35
  Letter.LO_I, // 0x36
  Letter.LO_I, // 0x37
  Letter.UP_I, // 0x38
  Letter.UP_I, // 0x39
  Letter.UP_I, // 0x3a
  Letter.UP_I, // 0x3b
  Letter.UP_I, // 0x3c
  Letter.UP_I, // 0x3d
  Letter.UP_I, // 0x3e
  Letter.UP_I, // 0x3f
  Letter.LO_O, // 0x40
  Letter.LO_O, // 0x41
  Letter.LO_O, // 0x42
  Letter.LO_O, // 0x43
  Letter.LO_O, // 0x44
  Letter.LO_O, // 0x45
  null, // 0x46
  null, // 0x47
  Letter.UP_O, // 0x48
  Letter.UP_O, // 0x49
  Letter.UP_O, // 0x4a
  Letter.UP_O, // 0x4b
  Letter.UP_O, // 0x4c
  Letter.UP_O, // 0x4d
  null, // 0x4e
  null, // 0x4f
  Letter.LO_U, // 0x50
  Letter.LO_U, // 0x51
  Letter.LO_U, // 0x52
  Letter.LO_U, // 0x53
  Letter.LO_U, // 0x54
  Letter.LO_U, // 0x55
  Letter.LO_U, // 0x56
  Letter.LO_U, // 0x57
  null, // 0x58
  Letter.UP_U, // 0x59
  null, // 0x5a
  Letter.UP_U, // 0x5b
  null, // 0x5c
  Letter.UP_U, // 0x5d
  null, // 0x5e
  Letter.UP_U, // 0x5f
  Letter.LO_O, // 0x60
  Letter.LO_O, // 0x61
  Letter.LO_O, // 0x62
  Letter.LO_O, // 0x63
  Letter.LO_O, // 0x64
  Letter.LO_O, // 0x65
  Letter.LO_O, // 0x66
  Letter.LO_O, // 0x67
  Letter.UP_O, // 0x68
  Letter.UP_O, // 0x69
  Letter.UP_O, // 0x6a
  Letter.UP_O, // 0x6b
  Letter.UP_O, // 0x6c
  Letter.UP_O, // 0x6d
  Letter.UP_O, // 0x6e
  Letter.UP_O, // 0x6f
  Letter.LO_A, // 0x70
  Letter.LO_A, // 0x71
  Letter.LO_E, // 0x72
  Letter.LO_E, // 0x73
  Letter.LO_E, // 0x74
  Letter.LO_E, // 0x75
  Letter.LO_I, // 0x76
  Letter.LO_I, // 0x77
  Letter.LO_O, // 0x78
  Letter.LO_O, // 0x79
  Letter.LO_U, // 0x7a
  Letter.LO_U, // 0x7b
  Letter.LO_O, // 0x7c
  Letter.LO_O, // 0x7d
  null, // 0x7e
  null, // 0x7f
  Letter.LO_A, // 0x80
  Letter.LO_A, // 0x81
  Letter.LO_A, // 0x82
  Letter.LO_A, // 0x83
  Letter.LO_A, // 0x84
  Letter.LO_A, // 0x85
  Letter.LO_A, // 0x86
  Letter.LO_A, // 0x87
  Letter.UP_A, // 0x88
  Letter.UP_A, // 0x89
  Letter.UP_A, // 0x8a
  Letter.UP_A, // 0x8b
  Letter.UP_A, // 0x8c
  Letter.UP_A, // 0x8d
  Letter.UP_A, // 0x8e
  Letter.UP_A, // 0x8f
  Letter.LO_E, // 0x90
  Letter.LO_E, // 0x91
  Letter.LO_E, // 0x92
  Letter.LO_E, // 0x93
  Letter.LO_E, // 0x94
  Letter.LO_E, // 0x95
  Letter.LO_E, // 0x96
  Letter.LO_E, // 0x97
  Letter.UP_E, // 0x98
  Letter.UP_E, // 0x99
  Letter.UP_E, // 0x9a
  Letter.UP_E, // 0x9b
  Letter.UP_E, // 0x9c
  Letter.UP_E, // 0x9d
  Letter.UP_E, // 0x9e
  Letter.UP_E, // 0x9f
  Letter.LO_O, // 0xa0
  Letter.LO_O, // 0xa1
  Letter.LO_O, // 0xa2
  Letter.LO_O, // 0xa3
  Letter.LO_O, // 0xa4
  Letter.LO_O, // 0xa5
  Letter.LO_O, // 0xa6
  Letter.LO_O, // 0xa7
  Letter.UP_O, // 0xa8
  Letter.UP_O, // 0xa9
  Letter.UP_O, // 0xaa
  Letter.UP_O, // 0xab
  Letter.UP_O, // 0xac
  Letter.UP_O, // 0xad
  Letter.UP_O, // 0xae
  Letter.UP_O, // 0xaf
  Letter.LO_A, // 0xb0
  Letter.LO_A, // 0xb1
  Letter.LO_A, // 0xb2
  Letter.LO_A, // 0xb3
  Letter.LO_A, // 0xb4
  null, // 0xb5
  Letter.LO_A, // 0xb6
  Letter.LO_A, // 0xb7
  Letter.UP_A, // 0xb8
  Letter.UP_A, // 0xb9
  Letter.UP_A, // 0xba
  Letter.UP_A, // 0xbb
  Letter.UP_A, // 0xbc
  Letter.QUOTE1, // 0xbd
  Letter.LO_I, // 0xbe
  Letter.QUOTE1, // 0xbf
  Letter.TILDE, // 0xc0
  new Chars("\"~"), // 0xc1
  Letter.LO_E, // 0xc2
  Letter.LO_E, // 0xc3
  Letter.LO_E, // 0xc4
  null, // 0xc5
  Letter.LO_E, // 0xc6
  Letter.LO_E, // 0xc7
  Letter.UP_E, // 0xc8
  Letter.UP_E, // 0xc9
  Letter.UP_E, // 0xca
  Letter.UP_E, // 0xcb
  Letter.UP_E, // 0xcc
  new Chars("'`"), // 0xcd
  new Chars("''"), // 0xce
  new Chars("'~"), // 0xcf
  Letter.LO_I, // 0xd0
  Letter.LO_I, // 0xd1
  Letter.LO_I, // 0xd2
  Letter.LO_I, // 0xd3
  null, // 0xd4
  null, // 0xd5
  Letter.LO_I, // 0xd6
  Letter.LO_I, // 0xd7
  Letter.UP_I, // 0xd8
  Letter.UP_I, // 0xd9
  Letter.UP_I, // 0xda
  Letter.UP_I, // 0xdb
  null, // 0xdc
  new Chars("``"), // 0xdd
  new Chars("`'"), // 0xde
  new Chars("`~"), // 0xdf
  Letter.LO_U, // 0xe0
  Letter.LO_U, // 0xe1
  Letter.LO_U, // 0xe2
  Letter.LO_U, // 0xe3
  Letter.UP_R, // 0xe4
  Letter.UP_R, // 0xe5
  Letter.LO_U, // 0xe6
  Letter.LO_U, // 0xe7
  Letter.UP_U, // 0xe8
  Letter.UP_U, // 0xe9
  Letter.UP_U, // 0xea
  Letter.UP_U, // 0xeb
  Letter.UP_R, // 0xec
  new Chars("'`'"), // 0xed
  new Chars("'''"), // 0xee
  Char.GRAVE, // 0xef
  null, // 0xf0
  null, // 0xf1
  Letter.LO_O, // 0xf2
  Letter.LO_O, // 0xf3
  Letter.LO_O, // 0xf4
  null, // 0xf5
  Letter.LO_O, // 0xf6
  Letter.LO_O, // 0xf7
  Letter.UP_O, // 0xf8
  Letter.UP_O, // 0xf9
  Letter.UP_O, // 0xfa
  Letter.UP_O, // 0xfb
  Letter.UP_O, // 0xfc
  Letter.QUOTE1, // 0xfd
  Letter.GRAVE, // 0xfe
  null, // 0xff
  };
}
