/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+25xx (Box Drawing, Block Elements, Geometric Shapes).
 */
final class X25 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  Char.MINUS, // 0x00
  Char.MINUS, // 0x01
  Char.PIPE, // 0x02
  Char.PIPE, // 0x03
  Char.MINUS, // 0x04
  Char.MINUS, // 0x05
  Char.PIPE, // 0x06
  Char.PIPE, // 0x07
  Char.MINUS, // 0x08
  Char.MINUS, // 0x09
  Char.PIPE, // 0x0a
  Char.PIPE, // 0x0b
  Char.PLUS, // 0x0c
  Char.PLUS, // 0x0d
  Char.PLUS, // 0x0e
  Char.PLUS, // 0x0f
  Char.PLUS, // 0x10
  Char.PLUS, // 0x11
  Char.PLUS, // 0x12
  Char.PLUS, // 0x13
  Char.PLUS, // 0x14
  Char.PLUS, // 0x15
  Char.PLUS, // 0x16
  Char.PLUS, // 0x17
  Char.PLUS, // 0x18
  Char.PLUS, // 0x19
  Char.PLUS, // 0x1a
  Char.PLUS, // 0x1b
  Char.PLUS, // 0x1c
  Char.PLUS, // 0x1d
  Char.PLUS, // 0x1e
  Char.PLUS, // 0x1f
  Char.PLUS, // 0x20
  Char.PLUS, // 0x21
  Char.PLUS, // 0x22
  Char.PLUS, // 0x23
  Char.PLUS, // 0x24
  Char.PLUS, // 0x25
  Char.PLUS, // 0x26
  Char.PLUS, // 0x27
  Char.PLUS, // 0x28
  Char.PLUS, // 0x29
  Char.PLUS, // 0x2a
  Char.PLUS, // 0x2b
  Char.PLUS, // 0x2c
  Char.PLUS, // 0x2d
  Char.PLUS, // 0x2e
  Char.PLUS, // 0x2f
  Char.PLUS, // 0x30
  Char.PLUS, // 0x31
  Char.PLUS, // 0x32
  Char.PLUS, // 0x33
  Char.PLUS, // 0x34
  Char.PLUS, // 0x35
  Char.PLUS, // 0x36
  Char.PLUS, // 0x37
  Char.PLUS, // 0x38
  Char.PLUS, // 0x39
  Char.PLUS, // 0x3a
  Char.PLUS, // 0x3b
  Char.PLUS, // 0x3c
  Char.PLUS, // 0x3d
  Char.PLUS, // 0x3e
  Char.PLUS, // 0x3f
  Char.PLUS, // 0x40
  Char.PLUS, // 0x41
  Char.PLUS, // 0x42
  Char.PLUS, // 0x43
  Char.PLUS, // 0x44
  Char.PLUS, // 0x45
  Char.PLUS, // 0x46
  Char.PLUS, // 0x47
  Char.PLUS, // 0x48
  Char.PLUS, // 0x49
  Char.PLUS, // 0x4a
  Char.PLUS, // 0x4b
  Char.MINUS, // 0x4c
  Char.MINUS, // 0x4d
  Char.PIPE, // 0x4e
  Char.PIPE, // 0x4f
  Char.MINUS, // 0x50
  Char.PIPE, // 0x51
  Char.PLUS, // 0x52
  Char.PLUS, // 0x53
  Char.PLUS, // 0x54
  Char.PLUS, // 0x55
  Char.PLUS, // 0x56
  Char.PLUS, // 0x57
  Char.PLUS, // 0x58
  Char.PLUS, // 0x59
  Char.PLUS, // 0x5a
  Char.PLUS, // 0x5b
  Char.PLUS, // 0x5c
  Char.PLUS, // 0x5d
  Char.PLUS, // 0x5e
  Char.PLUS, // 0x5f
  Char.PLUS, // 0x60
  Char.PLUS, // 0x61
  Char.PLUS, // 0x62
  Char.PLUS, // 0x63
  Char.PLUS, // 0x64
  Char.PLUS, // 0x65
  Char.PLUS, // 0x66
  Char.PLUS, // 0x67
  Char.PLUS, // 0x68
  Char.PLUS, // 0x69
  Char.PLUS, // 0x6a
  Char.PLUS, // 0x6b
  Char.PLUS, // 0x6c
  Char.PLUS, // 0x6d
  Char.PLUS, // 0x6e
  Char.PLUS, // 0x6f
  Char.PLUS, // 0x70
  Char.SLASH, // 0x71
  Char.BKSLASH, // 0x72
  Letter.UP_X, // 0x73
  Char.MINUS, // 0x74
  Char.PIPE, // 0x75
  Char.MINUS, // 0x76
  Char.PIPE, // 0x77
  Char.MINUS, // 0x78
  Char.PIPE, // 0x79
  Char.MINUS, // 0x7a
  Char.PIPE, // 0x7b
  Char.MINUS, // 0x7c
  Char.PIPE, // 0x7d
  Char.MINUS, // 0x7e
  Char.PIPE, // 0x7f
  Char.HASH, // 0x80
  Char.HASH, // 0x81
  Char.HASH, // 0x82
  Char.HASH, // 0x83
  Char.HASH, // 0x84
  Char.HASH, // 0x85
  Char.HASH, // 0x86
  Char.HASH, // 0x87
  Char.HASH, // 0x88
  Char.HASH, // 0x89
  Char.HASH, // 0x8a
  Char.HASH, // 0x8b
  Char.HASH, // 0x8c
  Char.HASH, // 0x8d
  Char.HASH, // 0x8e
  Char.HASH, // 0x8f
  Char.HASH, // 0x90
  Char.HASH, // 0x91
  Char.HASH, // 0x92
  Char.HASH, // 0x93
  Char.MINUS, // 0x94
  Char.PIPE, // 0x95
  null, // 0x96
  null, // 0x97
  null, // 0x98
  null, // 0x99
  null, // 0x9a
  null, // 0x9b
  null, // 0x9c
  null, // 0x9d
  null, // 0x9e
  null, // 0x9f
  Char.HASH, // 0xa0
  Char.HASH, // 0xa1
  Char.HASH, // 0xa2
  Char.HASH, // 0xa3
  Char.HASH, // 0xa4
  Char.HASH, // 0xa5
  Char.HASH, // 0xa6
  Char.HASH, // 0xa7
  Char.HASH, // 0xa8
  Char.HASH, // 0xa9
  Char.HASH, // 0xaa
  Char.HASH, // 0xab
  Char.HASH, // 0xac
  Char.HASH, // 0xad
  Char.HASH, // 0xae
  Char.HASH, // 0xaf
  Char.HASH, // 0xb0
  Char.HASH, // 0xb1
  Char.CARET, // 0xb2
  Char.CARET, // 0xb3
  Char.CARET, // 0xb4
  Char.CARET, // 0xb5
  Char.GREATER, // 0xb6
  Char.GREATER, // 0xb7
  Char.GREATER, // 0xb8
  Char.GREATER, // 0xb9
  Char.GREATER, // 0xba
  Char.GREATER, // 0xbb
  Letter.UP_V, // 0xbc
  Letter.UP_V, // 0xbd
  Letter.UP_V, // 0xbe
  Letter.UP_V, // 0xbf
  Char.LESS, // 0xc0
  Char.LESS, // 0xc1
  Char.LESS, // 0xc2
  Char.LESS, // 0xc3
  Char.LESS, // 0xc4
  Char.LESS, // 0xc5
  Char.ASTERISK, // 0xc6
  Char.ASTERISK, // 0xc7
  Char.ASTERISK, // 0xc8
  Char.ASTERISK, // 0xc9
  Char.ASTERISK, // 0xca
  Char.ASTERISK, // 0xcb
  Char.ASTERISK, // 0xcc
  Char.ASTERISK, // 0xcd
  Char.ASTERISK, // 0xce
  Char.ASTERISK, // 0xcf
  Char.ASTERISK, // 0xd0
  Char.ASTERISK, // 0xd1
  Char.ASTERISK, // 0xd2
  Char.ASTERISK, // 0xd3
  Char.ASTERISK, // 0xd4
  Char.ASTERISK, // 0xd5
  Char.ASTERISK, // 0xd6
  Char.ASTERISK, // 0xd7
  Char.ASTERISK, // 0xd8
  Char.ASTERISK, // 0xd9
  Char.ASTERISK, // 0xda
  Char.ASTERISK, // 0xdb
  Char.ASTERISK, // 0xdc
  Char.ASTERISK, // 0xdd
  Char.ASTERISK, // 0xde
  Char.ASTERISK, // 0xdf
  Char.ASTERISK, // 0xe0
  Char.ASTERISK, // 0xe1
  Char.ASTERISK, // 0xe2
  Char.ASTERISK, // 0xe3
  Char.ASTERISK, // 0xe4
  Char.ASTERISK, // 0xe5
  Char.ASTERISK, // 0xe6
  Char.HASH, // 0xe7
  Char.HASH, // 0xe8
  Char.HASH, // 0xe9
  Char.HASH, // 0xea
  Char.HASH, // 0xeb
  Char.CARET, // 0xec
  Char.CARET, // 0xed
  Char.CARET, // 0xee
  Letter.UP_O, // 0xef
  Char.HASH, // 0xf0
  Char.HASH, // 0xf1
  Char.HASH, // 0xf2
  Char.HASH, // 0xf3
  Letter.UP_O, // 0xf4
  Letter.UP_O, // 0xf5
  Letter.UP_O, // 0xf6
  Letter.UP_O, // 0xf7
  Char.SLASH, // 0xf8
  Char.BKSLASH, // 0xf9
  Char.BKSLASH, // 0xfa
  Char.HASH, // 0xfb
  Char.HASH, // 0xfc
  Char.HASH, // 0xfd
  Char.HASH, // 0xfe
  Char.SLASH };
}
