/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+50xx (CJK Unified Ideographs).
 */
final class X50 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Chang"), // 0x00
  new Word("Chi"), // 0x01
  new Word("Bing"), // 0x02
  new Word("Zan"), // 0x03
  new Word("Yao"), // 0x04
  new Word("Cui"), // 0x05
  new Word("Lia"), // 0x06
  new Word("Wan"), // 0x07
  new Word("Lai"), // 0x08
  new Word("Cang"), // 0x09
  new Word("Zong"), // 0x0a
  new Word("Ge"), // 0x0b
  new Word("Guan"), // 0x0c
  new Word("Bei"), // 0x0d
  new Word("Tian"), // 0x0e
  new Word("Shu"), // 0x0f
  new Word("Shu"), // 0x10
  new Word("Men"), // 0x11
  new Word("Dao"), // 0x12
  new Word("Tan"), // 0x13
  new Word("Jue"), // 0x14
  new Word("Chui"), // 0x15
  new Word("Xing"), // 0x16
  new Word("Peng"), // 0x17
  new Word("Tang"), // 0x18
  new Word("Hou"), // 0x19
  new Word("Yi"), // 0x1a
  new Word("Qi"), // 0x1b
  new Word("Ti"), // 0x1c
  new Word("Gan"), // 0x1d
  new Word("Jing"), // 0x1e
  new Word("Jie"), // 0x1f
  new Word("Sui"), // 0x20
  new Word("Chang"), // 0x21
  new Word("Jie"), // 0x22
  new Word("Fang"), // 0x23
  new Word("Zhi"), // 0x24
  new Word("Kong"), // 0x25
  new Word("Juan"), // 0x26
  new Word("Zong"), // 0x27
  new Word("Ju"), // 0x28
  new Word("Qian"), // 0x29
  new Word("Ni"), // 0x2a
  new Word("Lun"), // 0x2b
  new Word("Zhuo"), // 0x2c
  new Word("Wei"), // 0x2d
  new Word("Luo"), // 0x2e
  new Word("Song"), // 0x2f
  new Word("Leng"), // 0x30
  new Word("Hun"), // 0x31
  new Word("Dong"), // 0x32
  new Word("Zi"), // 0x33
  new Word("Ben"), // 0x34
  new Word("Wu"), // 0x35
  new Word("Ju"), // 0x36
  new Word("Nai"), // 0x37
  new Word("Cai"), // 0x38
  new Word("Jian"), // 0x39
  new Word("Zhai"), // 0x3a
  new Word("Ye"), // 0x3b
  new Word("Zhi"), // 0x3c
  new Word("Sha"), // 0x3d
  new Word("Qing"), // 0x3e
  null, // 0x3f
  new Word("Ying"), // 0x40
  new Word("Cheng"), // 0x41
  new Word("Jian"), // 0x42
  new Word("Yan"), // 0x43
  new Word("Nuan"), // 0x44
  new Word("Zhong"), // 0x45
  new Word("Chun"), // 0x46
  new Word("Jia"), // 0x47
  new Word("Jie"), // 0x48
  new Word("Wei"), // 0x49
  new Word("Yu"), // 0x4a
  new Word("Bing"), // 0x4b
  new Word("Ruo"), // 0x4c
  new Word("Ti"), // 0x4d
  new Word("Wei"), // 0x4e
  new Word("Pian"), // 0x4f
  new Word("Yan"), // 0x50
  new Word("Feng"), // 0x51
  new Word("Tang"), // 0x52
  new Word("Wo"), // 0x53
  new Word("E"), // 0x54
  new Word("Xie"), // 0x55
  new Word("Che"), // 0x56
  new Word("Sheng"), // 0x57
  new Word("Kan"), // 0x58
  new Word("Di"), // 0x59
  new Word("Zuo"), // 0x5a
  new Word("Cha"), // 0x5b
  new Word("Ting"), // 0x5c
  new Word("Bei"), // 0x5d
  new Word("Ye"), // 0x5e
  new Word("Huang"), // 0x5f
  new Word("Yao"), // 0x60
  new Word("Zhan"), // 0x61
  new Word("Chou"), // 0x62
  new Word("Yan"), // 0x63
  new Word("You"), // 0x64
  new Word("Jian"), // 0x65
  new Word("Xu"), // 0x66
  new Word("Zha"), // 0x67
  new Word("Ci"), // 0x68
  new Word("Fu"), // 0x69
  new Word("Bi"), // 0x6a
  new Word("Zhi"), // 0x6b
  new Word("Zong"), // 0x6c
  new Word("Mian"), // 0x6d
  new Word("Ji"), // 0x6e
  new Word("Yi"), // 0x6f
  new Word("Xie"), // 0x70
  new Word("Xun"), // 0x71
  new Word("Si"), // 0x72
  new Word("Duan"), // 0x73
  new Word("Ce"), // 0x74
  new Word("Zhen"), // 0x75
  new Word("Ou"), // 0x76
  new Word("Tou"), // 0x77
  new Word("Tou"), // 0x78
  new Word("Bei"), // 0x79
  new Word("Za"), // 0x7a
  new Word("Lu"), // 0x7b
  new Word("Jie"), // 0x7c
  new Word("Wei"), // 0x7d
  new Word("Fen"), // 0x7e
  new Word("Chang"), // 0x7f
  new Word("Gui"), // 0x80
  new Word("Sou"), // 0x81
  new Word("Zhi"), // 0x82
  new Word("Su"), // 0x83
  new Word("Xia"), // 0x84
  new Word("Fu"), // 0x85
  new Word("Yuan"), // 0x86
  new Word("Rong"), // 0x87
  new Word("Li"), // 0x88
  new Word("Ru"), // 0x89
  new Word("Yun"), // 0x8a
  new Word("Gou"), // 0x8b
  new Word("Ma"), // 0x8c
  new Word("Bang"), // 0x8d
  new Word("Dian"), // 0x8e
  new Word("Tang"), // 0x8f
  new Word("Hao"), // 0x90
  new Word("Jie"), // 0x91
  new Word("Xi"), // 0x92
  new Word("Shan"), // 0x93
  new Word("Qian"), // 0x94
  new Word("Jue"), // 0x95
  new Word("Cang"), // 0x96
  new Word("Chu"), // 0x97
  new Word("San"), // 0x98
  new Word("Bei"), // 0x99
  new Word("Xiao"), // 0x9a
  new Word("Yong"), // 0x9b
  new Word("Yao"), // 0x9c
  new Word("Tan"), // 0x9d
  new Word("Suo"), // 0x9e
  new Word("Yang"), // 0x9f
  new Word("Fa"), // 0xa0
  new Word("Bing"), // 0xa1
  new Word("Jia"), // 0xa2
  new Word("Dai"), // 0xa3
  new Word("Zai"), // 0xa4
  new Word("Tang"), // 0xa5
  null, // 0xa6
  new Word("Bin"), // 0xa7
  new Word("Chu"), // 0xa8
  new Word("Nuo"), // 0xa9
  new Word("Can"), // 0xaa
  new Word("Lei"), // 0xab
  new Word("Cui"), // 0xac
  new Word("Yong"), // 0xad
  new Word("Zao"), // 0xae
  new Word("Zong"), // 0xaf
  new Word("Peng"), // 0xb0
  new Word("Song"), // 0xb1
  new Word("Ao"), // 0xb2
  new Word("Chuan"), // 0xb3
  new Word("Yu"), // 0xb4
  new Word("Zhai"), // 0xb5
  new Word("Cou"), // 0xb6
  new Word("Shang"), // 0xb7
  new Word("Qiang"), // 0xb8
  new Word("Jing"), // 0xb9
  new Word("Chi"), // 0xba
  new Word("Sha"), // 0xbb
  new Word("Han"), // 0xbc
  new Word("Zhang"), // 0xbd
  new Word("Qing"), // 0xbe
  new Word("Yan"), // 0xbf
  new Word("Di"), // 0xc0
  new Word("Xi"), // 0xc1
  new Word("Lu"), // 0xc2
  new Word("Bei"), // 0xc3
  new Word("Piao"), // 0xc4
  new Word("Jin"), // 0xc5
  new Word("Lian"), // 0xc6
  new Word("Lu"), // 0xc7
  new Word("Man"), // 0xc8
  new Word("Qian"), // 0xc9
  new Word("Xian"), // 0xca
  new Word("Tan"), // 0xcb
  new Word("Ying"), // 0xcc
  new Word("Dong"), // 0xcd
  new Word("Zhuan"), // 0xce
  new Word("Xiang"), // 0xcf
  new Word("Shan"), // 0xd0
  new Word("Qiao"), // 0xd1
  new Word("Jiong"), // 0xd2
  new Word("Tui"), // 0xd3
  new Word("Zun"), // 0xd4
  new Word("Pu"), // 0xd5
  new Word("Xi"), // 0xd6
  new Word("Lao"), // 0xd7
  new Word("Chang"), // 0xd8
  new Word("Guang"), // 0xd9
  new Word("Liao"), // 0xda
  new Word("Qi"), // 0xdb
  new Word("Deng"), // 0xdc
  new Word("Chan"), // 0xdd
  new Word("Wei"), // 0xde
  new Word("Ji"), // 0xdf
  new Word("Fan"), // 0xe0
  new Word("Hui"), // 0xe1
  new Word("Chuan"), // 0xe2
  new Word("Jian"), // 0xe3
  new Word("Dan"), // 0xe4
  new Word("Jiao"), // 0xe5
  new Word("Jiu"), // 0xe6
  new Word("Seng"), // 0xe7
  new Word("Fen"), // 0xe8
  new Word("Xian"), // 0xe9
  new Word("Jue"), // 0xea
  new Word("E"), // 0xeb
  new Word("Jiao"), // 0xec
  new Word("Jian"), // 0xed
  new Word("Tong"), // 0xee
  new Word("Lin"), // 0xef
  new Word("Bo"), // 0xf0
  new Word("Gu"), // 0xf1
  null, // 0xf2
  new Word("Su"), // 0xf3
  new Word("Xian"), // 0xf4
  new Word("Jiang"), // 0xf5
  new Word("Min"), // 0xf6
  new Word("Ye"), // 0xf7
  new Word("Jin"), // 0xf8
  new Word("Jia"), // 0xf9
  new Word("Qiao"), // 0xfa
  new Word("Pi"), // 0xfb
  new Word("Feng"), // 0xfc
  new Word("Zhou"), // 0xfd
  new Word("Ai"), // 0xfe
  new Word("Sai") // 0xff
  };
}