/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+52xx (CJK Unified Ideographs).
 */
final class X52 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Dao"), // 0x00
  new Word("Diao"), // 0x01
  new Word("Dao"), // 0x02
  new Word("Ren"), // 0x03
  new Word("Ren"), // 0x04
  new Word("Chuang"), // 0x05
  new Word("Fen"), // 0x06
  new Word("Qie"), // 0x07
  new Word("Yi"), // 0x08
  new Word("Ji"), // 0x09
  new Word("Kan"), // 0x0a
  new Word("Qian"), // 0x0b
  new Word("Cun"), // 0x0c
  new Word("Chu"), // 0x0d
  new Word("Wen"), // 0x0e
  new Word("Ji"), // 0x0f
  new Word("Dan"), // 0x10
  new Word("Xing"), // 0x11
  new Word("Hua"), // 0x12
  new Word("Wan"), // 0x13
  new Word("Jue"), // 0x14
  new Word("Li"), // 0x15
  new Word("Yue"), // 0x16
  new Word("Lie"), // 0x17
  new Word("Liu"), // 0x18
  new Word("Ze"), // 0x19
  new Word("Gang"), // 0x1a
  new Word("Chuang"), // 0x1b
  new Word("Fu"), // 0x1c
  new Word("Chu"), // 0x1d
  new Word("Qu"), // 0x1e
  new Word("Ju"), // 0x1f
  new Word("Shan"), // 0x20
  new Word("Min"), // 0x21
  new Word("Ling"), // 0x22
  new Word("Zhong"), // 0x23
  new Word("Pan"), // 0x24
  new Word("Bie"), // 0x25
  new Word("Jie"), // 0x26
  new Word("Jie"), // 0x27
  new Word("Bao"), // 0x28
  new Word("Li"), // 0x29
  new Word("Shan"), // 0x2a
  new Word("Bie"), // 0x2b
  new Word("Chan"), // 0x2c
  new Word("Jing"), // 0x2d
  new Word("Gua"), // 0x2e
  new Word("Gen"), // 0x2f
  new Word("Dao"), // 0x30
  new Word("Chuang"), // 0x31
  new Word("Kui"), // 0x32
  new Word("Ku"), // 0x33
  new Word("Duo"), // 0x34
  new Word("Er"), // 0x35
  new Word("Zhi"), // 0x36
  new Word("Shua"), // 0x37
  new Word("Quan"), // 0x38
  new Word("Cha"), // 0x39
  new Word("Ci"), // 0x3a
  new Word("Ke"), // 0x3b
  new Word("Jie"), // 0x3c
  new Word("Gui"), // 0x3d
  new Word("Ci"), // 0x3e
  new Word("Gui"), // 0x3f
  new Word("Kai"), // 0x40
  new Word("Duo"), // 0x41
  new Word("Ji"), // 0x42
  new Word("Ti"), // 0x43
  new Word("Jing"), // 0x44
  new Word("Lou"), // 0x45
  new Word("Gen"), // 0x46
  new Word("Ze"), // 0x47
  new Word("Yuan"), // 0x48
  new Word("Cuo"), // 0x49
  new Word("Xue"), // 0x4a
  new Word("Ke"), // 0x4b
  new Word("La"), // 0x4c
  new Word("Qian"), // 0x4d
  new Word("Cha"), // 0x4e
  new Word("Chuang"), // 0x4f
  new Word("Gua"), // 0x50
  new Word("Jian"), // 0x51
  new Word("Cuo"), // 0x52
  new Word("Li"), // 0x53
  new Word("Ti"), // 0x54
  new Word("Fei"), // 0x55
  new Word("Pou"), // 0x56
  new Word("Chan"), // 0x57
  new Word("Qi"), // 0x58
  new Word("Chuang"), // 0x59
  new Word("Zi"), // 0x5a
  new Word("Gang"), // 0x5b
  new Word("Wan"), // 0x5c
  new Word("Bo"), // 0x5d
  new Word("Ji"), // 0x5e
  new Word("Duo"), // 0x5f
  new Word("Qing"), // 0x60
  new Word("Yan"), // 0x61
  new Word("Zhuo"), // 0x62
  new Word("Jian"), // 0x63
  new Word("Ji"), // 0x64
  new Word("Bo"), // 0x65
  new Word("Yan"), // 0x66
  new Word("Ju"), // 0x67
  new Word("Huo"), // 0x68
  new Word("Sheng"), // 0x69
  new Word("Jian"), // 0x6a
  new Word("Duo"), // 0x6b
  new Word("Duan"), // 0x6c
  new Word("Wu"), // 0x6d
  new Word("Gua"), // 0x6e
  new Word("Fu"), // 0x6f
  new Word("Sheng"), // 0x70
  new Word("Jian"), // 0x71
  new Word("Ge"), // 0x72
  new Word("Zha"), // 0x73
  new Word("Kai"), // 0x74
  new Word("Chuang"), // 0x75
  new Word("Juan"), // 0x76
  new Word("Chan"), // 0x77
  new Word("Tuan"), // 0x78
  new Word("Lu"), // 0x79
  new Word("Li"), // 0x7a
  new Word("Fou"), // 0x7b
  new Word("Shan"), // 0x7c
  new Word("Piao"), // 0x7d
  new Word("Kou"), // 0x7e
  new Word("Jiao"), // 0x7f
  new Word("Gua"), // 0x80
  new Word("Qiao"), // 0x81
  new Word("Jue"), // 0x82
  new Word("Hua"), // 0x83
  new Word("Zha"), // 0x84
  new Word("Zhuo"), // 0x85
  new Word("Lian"), // 0x86
  new Word("Ju"), // 0x87
  new Word("Pi"), // 0x88
  new Word("Liu"), // 0x89
  new Word("Gui"), // 0x8a
  new Word("Jiao"), // 0x8b
  new Word("Gui"), // 0x8c
  new Word("Jian"), // 0x8d
  new Word("Jian"), // 0x8e
  new Word("Tang"), // 0x8f
  new Word("Huo"), // 0x90
  new Word("Ji"), // 0x91
  new Word("Jian"), // 0x92
  new Word("Yi"), // 0x93
  new Word("Jian"), // 0x94
  new Word("Zhi"), // 0x95
  new Word("Chan"), // 0x96
  new Word("Cuan"), // 0x97
  new Word("Mo"), // 0x98
  new Word("Li"), // 0x99
  new Word("Zhu"), // 0x9a
  new Word("Li"), // 0x9b
  new Word("Ya"), // 0x9c
  new Word("Quan"), // 0x9d
  new Word("Ban"), // 0x9e
  new Word("Gong"), // 0x9f
  new Word("Jia"), // 0xa0
  new Word("Wu"), // 0xa1
  new Word("Mai"), // 0xa2
  new Word("Lie"), // 0xa3
  new Word("Jin"), // 0xa4
  new Word("Keng"), // 0xa5
  new Word("Xie"), // 0xa6
  new Word("Zhi"), // 0xa7
  new Word("Dong"), // 0xa8
  new Word("Zhu"), // 0xa9
  new Word("Nu"), // 0xaa
  new Word("Jie"), // 0xab
  new Word("Qu"), // 0xac
  new Word("Shao"), // 0xad
  new Word("Yi"), // 0xae
  new Word("Zhu"), // 0xaf
  new Word("Miao"), // 0xb0
  new Word("Li"), // 0xb1
  new Word("Jing"), // 0xb2
  new Word("Lao"), // 0xb3
  new Word("Lao"), // 0xb4
  new Word("Juan"), // 0xb5
  new Word("Kou"), // 0xb6
  new Word("Yang"), // 0xb7
  new Word("Wa"), // 0xb8
  new Word("Xiao"), // 0xb9
  new Word("Mou"), // 0xba
  new Word("Kuang"), // 0xbb
  new Word("Jie"), // 0xbc
  new Word("Lie"), // 0xbd
  new Word("He"), // 0xbe
  new Word("Shi"), // 0xbf
  new Word("Ke"), // 0xc0
  new Word("Jing"), // 0xc1
  new Word("Hao"), // 0xc2
  new Word("Bo"), // 0xc3
  new Word("Min"), // 0xc4
  new Word("Chi"), // 0xc5
  new Word("Lang"), // 0xc6
  new Word("Yong"), // 0xc7
  new Word("Yong"), // 0xc8
  new Word("Mian"), // 0xc9
  new Word("Ke"), // 0xca
  new Word("Xun"), // 0xcb
  new Word("Juan"), // 0xcc
  new Word("Qing"), // 0xcd
  new Word("Lu"), // 0xce
  new Word("Pou"), // 0xcf
  new Word("Meng"), // 0xd0
  new Word("Lai"), // 0xd1
  new Word("Le"), // 0xd2
  new Word("Kai"), // 0xd3
  new Word("Mian"), // 0xd4
  new Word("Dong"), // 0xd5
  new Word("Xu"), // 0xd6
  new Word("Xu"), // 0xd7
  new Word("Kan"), // 0xd8
  new Word("Wu"), // 0xd9
  new Word("Yi"), // 0xda
  new Word("Xun"), // 0xdb
  new Word("Weng"), // 0xdc
  new Word("Sheng"), // 0xdd
  new Word("Lao"), // 0xde
  new Word("Mu"), // 0xdf
  new Word("Lu"), // 0xe0
  new Word("Piao"), // 0xe1
  new Word("Shi"), // 0xe2
  new Word("Ji"), // 0xe3
  new Word("Qin"), // 0xe4
  new Word("Qiang"), // 0xe5
  new Word("Jiao"), // 0xe6
  new Word("Quan"), // 0xe7
  new Word("Yang"), // 0xe8
  new Word("Yi"), // 0xe9
  new Word("Jue"), // 0xea
  new Word("Fan"), // 0xeb
  new Word("Juan"), // 0xec
  new Word("Tong"), // 0xed
  new Word("Ju"), // 0xee
  new Word("Dan"), // 0xef
  new Word("Xie"), // 0xf0
  new Word("Mai"), // 0xf1
  new Word("Xun"), // 0xf2
  new Word("Xun"), // 0xf3
  new Word("Lu"), // 0xf4
  new Word("Li"), // 0xf5
  new Word("Che"), // 0xf6
  new Word("Rang"), // 0xf7
  new Word("Quan"), // 0xf8
  new Word("Bao"), // 0xf9
  new Word("Shao"), // 0xfa
  new Word("Yun"), // 0xfb
  new Word("Jiu"), // 0xfc
  new Word("Bao"), // 0xfd
  new Word("Gou"), // 0xfe
  new Word("Wu") // 0xff
  };
}