/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+53xx (CJK Unified Ideographs).
 */
final class X53 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Yun"), // 0x00
  new Word("Mwun"), // 0x01
  new Word("Nay"), // 0x02
  new Word("Gai"), // 0x03
  new Word("Gai"), // 0x04
  new Word("Bao"), // 0x05
  new Word("Cong"), // 0x06
  null, // 0x07
  new Word("Xiong"), // 0x08
  new Word("Peng"), // 0x09
  new Word("Ju"), // 0x0a
  new Word("Tao"), // 0x0b
  new Word("Ge"), // 0x0c
  new Word("Pu"), // 0x0d
  new Word("An"), // 0x0e
  new Word("Pao"), // 0x0f
  new Word("Fu"), // 0x10
  new Word("Gong"), // 0x11
  new Word("Da"), // 0x12
  new Word("Jiu"), // 0x13
  new Word("Qiong"), // 0x14
  new Word("Bi"), // 0x15
  new Word("Hua"), // 0x16
  new Word("Bei"), // 0x17
  new Word("Nao"), // 0x18
  new Word("Chi"), // 0x19
  new Word("Fang"), // 0x1a
  new Word("Jiu"), // 0x1b
  new Word("Yi"), // 0x1c
  new Word("Za"), // 0x1d
  new Word("Jiang"), // 0x1e
  new Word("Kang"), // 0x1f
  new Word("Jiang"), // 0x20
  new Word("Kuang"), // 0x21
  new Word("Hu"), // 0x22
  new Word("Xia"), // 0x23
  new Word("Qu"), // 0x24
  new Word("Bian"), // 0x25
  new Word("Gui"), // 0x26
  new Word("Qie"), // 0x27
  new Word("Zang"), // 0x28
  new Word("Kuang"), // 0x29
  new Word("Fei"), // 0x2a
  new Word("Hu"), // 0x2b
  new Word("Tou"), // 0x2c
  new Word("Gui"), // 0x2d
  new Word("Gui"), // 0x2e
  new Word("Hui"), // 0x2f
  new Word("Dan"), // 0x30
  new Word("Gui"), // 0x31
  new Word("Lian"), // 0x32
  new Word("Lian"), // 0x33
  new Word("Suan"), // 0x34
  new Word("Du"), // 0x35
  new Word("Jiu"), // 0x36
  new Word("Qu"), // 0x37
  new Word("Xi"), // 0x38
  new Word("Pi"), // 0x39
  new Word("Qu"), // 0x3a
  new Word("Yi"), // 0x3b
  new Word("Qia"), // 0x3c
  new Word("Yan"), // 0x3d
  new Word("Bian"), // 0x3e
  new Word("Ni"), // 0x3f
  new Word("Qu"), // 0x40
  new Word("Shi"), // 0x41
  new Word("Xin"), // 0x42
  new Word("Qian"), // 0x43
  new Word("Nian"), // 0x44
  new Word("Sa"), // 0x45
  new Word("Zu"), // 0x46
  new Word("Sheng"), // 0x47
  new Word("Wu"), // 0x48
  new Word("Hui"), // 0x49
  new Word("Ban"), // 0x4a
  new Word("Shi"), // 0x4b
  new Word("Xi"), // 0x4c
  new Word("Wan"), // 0x4d
  new Word("Hua"), // 0x4e
  new Word("Xie"), // 0x4f
  new Word("Wan"), // 0x50
  new Word("Bei"), // 0x51
  new Word("Zu"), // 0x52
  new Word("Zhuo"), // 0x53
  new Word("Xie"), // 0x54
  new Word("Dan"), // 0x55
  new Word("Mai"), // 0x56
  new Word("Nan"), // 0x57
  new Word("Dan"), // 0x58
  new Word("Ji"), // 0x59
  new Word("Bo"), // 0x5a
  new Word("Shuai"), // 0x5b
  new Word("Bu"), // 0x5c
  new Word("Kuang"), // 0x5d
  new Word("Bian"), // 0x5e
  new Word("Bu"), // 0x5f
  new Word("Zhan"), // 0x60
  new Word("Qia"), // 0x61
  new Word("Lu"), // 0x62
  new Word("You"), // 0x63
  new Word("Lu"), // 0x64
  new Word("Xi"), // 0x65
  new Word("Gua"), // 0x66
  new Word("Wo"), // 0x67
  new Word("Xie"), // 0x68
  new Word("Jie"), // 0x69
  new Word("Jie"), // 0x6a
  new Word("Wei"), // 0x6b
  new Word("Ang"), // 0x6c
  new Word("Qiong"), // 0x6d
  new Word("Zhi"), // 0x6e
  new Word("Mao"), // 0x6f
  new Word("Yin"), // 0x70
  new Word("Wei"), // 0x71
  new Word("Shao"), // 0x72
  new Word("Ji"), // 0x73
  new Word("Que"), // 0x74
  new Word("Luan"), // 0x75
  new Word("Shi"), // 0x76
  new Word("Juan"), // 0x77
  new Word("Xie"), // 0x78
  new Word("Xu"), // 0x79
  new Word("Jin"), // 0x7a
  new Word("Que"), // 0x7b
  new Word("Wu"), // 0x7c
  new Word("Ji"), // 0x7d
  new Word("E"), // 0x7e
  new Word("Qing"), // 0x7f
  new Word("Xi"), // 0x80
  null, // 0x81
  new Word("Han"), // 0x82
  new Word("Zhan"), // 0x83
  new Word("E"), // 0x84
  new Word("Ting"), // 0x85
  new Word("Li"), // 0x86
  new Word("Zhe"), // 0x87
  new Word("Han"), // 0x88
  new Word("Li"), // 0x89
  new Word("Ya"), // 0x8a
  new Word("Ya"), // 0x8b
  new Word("Yan"), // 0x8c
  new Word("She"), // 0x8d
  new Word("Zhi"), // 0x8e
  new Word("Zha"), // 0x8f
  new Word("Pang"), // 0x90
  null, // 0x91
  new Word("He"), // 0x92
  new Word("Ya"), // 0x93
  new Word("Zhi"), // 0x94
  new Word("Ce"), // 0x95
  new Word("Pang"), // 0x96
  new Word("Ti"), // 0x97
  new Word("Li"), // 0x98
  new Word("She"), // 0x99
  new Word("Hou"), // 0x9a
  new Word("Ting"), // 0x9b
  new Word("Zui"), // 0x9c
  new Word("Cuo"), // 0x9d
  new Word("Fei"), // 0x9e
  new Word("Yuan"), // 0x9f
  new Word("Ce"), // 0xa0
  new Word("Yuan"), // 0xa1
  new Word("Xiang"), // 0xa2
  new Word("Yan"), // 0xa3
  new Word("Li"), // 0xa4
  new Word("Jue"), // 0xa5
  new Word("Sha"), // 0xa6
  new Word("Dian"), // 0xa7
  new Word("Chu"), // 0xa8
  new Word("Jiu"), // 0xa9
  new Word("Qin"), // 0xaa
  new Word("Ao"), // 0xab
  new Word("Gui"), // 0xac
  new Word("Yan"), // 0xad
  new Word("Si"), // 0xae
  new Word("Li"), // 0xaf
  new Word("Chang"), // 0xb0
  new Word("Lan"), // 0xb1
  new Word("Li"), // 0xb2
  new Word("Yan"), // 0xb3
  new Word("Yan"), // 0xb4
  new Word("Yuan"), // 0xb5
  new Word("Si"), // 0xb6
  new Word("Gong"), // 0xb7
  new Word("Lin"), // 0xb8
  new Word("Qiu"), // 0xb9
  new Word("Qu"), // 0xba
  new Word("Qu"), // 0xbb
  new Word("Uk"), // 0xbc
  new Word("Lei"), // 0xbd
  new Word("Du"), // 0xbe
  new Word("Xian"), // 0xbf
  new Word("Zhuan"), // 0xc0
  new Word("San"), // 0xc1
  new Word("Can"), // 0xc2
  new Word("Can"), // 0xc3
  new Word("Can"), // 0xc4
  new Word("Can"), // 0xc5
  new Word("Ai"), // 0xc6
  new Word("Dai"), // 0xc7
  new Word("You"), // 0xc8
  new Word("Cha"), // 0xc9
  new Word("Ji"), // 0xca
  new Word("You"), // 0xcb
  new Word("Shuang"), // 0xcc
  new Word("Fan"), // 0xcd
  new Word("Shou"), // 0xce
  new Word("Guai"), // 0xcf
  new Word("Ba"), // 0xd0
  new Word("Fa"), // 0xd1
  new Word("Ruo"), // 0xd2
  new Word("Shi"), // 0xd3
  new Word("Shu"), // 0xd4
  new Word("Zhuo"), // 0xd5
  new Word("Qu"), // 0xd6
  new Word("Shou"), // 0xd7
  new Word("Bian"), // 0xd8
  new Word("Xu"), // 0xd9
  new Word("Jia"), // 0xda
  new Word("Pan"), // 0xdb
  new Word("Sou"), // 0xdc
  new Word("Gao"), // 0xdd
  new Word("Wei"), // 0xde
  new Word("Sou"), // 0xdf
  new Word("Die"), // 0xe0
  new Word("Rui"), // 0xe1
  new Word("Cong"), // 0xe2
  new Word("Kou"), // 0xe3
  new Word("Gu"), // 0xe4
  new Word("Ju"), // 0xe5
  new Word("Ling"), // 0xe6
  new Word("Gua"), // 0xe7
  new Word("Tao"), // 0xe8
  new Word("Kou"), // 0xe9
  new Word("Zhi"), // 0xea
  new Word("Jiao"), // 0xeb
  new Word("Zhao"), // 0xec
  new Word("Ba"), // 0xed
  new Word("Ding"), // 0xee
  new Word("Ke"), // 0xef
  new Word("Tai"), // 0xf0
  new Word("Chi"), // 0xf1
  new Word("Shi"), // 0xf2
  new Word("You"), // 0xf3
  new Word("Qiu"), // 0xf4
  new Word("Po"), // 0xf5
  new Word("Xie"), // 0xf6
  new Word("Hao"), // 0xf7
  new Word("Si"), // 0xf8
  new Word("Tan"), // 0xf9
  new Word("Chi"), // 0xfa
  new Word("Le"), // 0xfb
  new Word("Diao"), // 0xfc
  new Word("Ji"), // 0xfd
  null, // 0xfe
  new Word("Hong") // 0xff
  };
}