/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+54xx (CJK Unified Ideographs).
 */
final class X54 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Mie"), // 0x00
  new Word("Xu"), // 0x01
  new Word("Mang"), // 0x02
  new Word("Chi"), // 0x03
  new Word("Ge"), // 0x04
  new Word("Xuan"), // 0x05
  new Word("Yao"), // 0x06
  new Word("Zi"), // 0x07
  new Word("He"), // 0x08
  new Word("Ji"), // 0x09
  new Word("Diao"), // 0x0a
  new Word("Cun"), // 0x0b
  new Word("Tong"), // 0x0c
  new Word("Ming"), // 0x0d
  new Word("Hou"), // 0x0e
  new Word("Li"), // 0x0f
  new Word("Tu"), // 0x10
  new Word("Xiang"), // 0x11
  new Word("Zha"), // 0x12
  new Word("Xia"), // 0x13
  new Word("Ye"), // 0x14
  new Word("Lu"), // 0x15
  new Word("A"), // 0x16
  new Word("Ma"), // 0x17
  new Word("Ou"), // 0x18
  new Word("Xue"), // 0x19
  new Word("Yi"), // 0x1a
  new Word("Jun"), // 0x1b
  new Word("Chou"), // 0x1c
  new Word("Lin"), // 0x1d
  new Word("Tun"), // 0x1e
  new Word("Yin"), // 0x1f
  new Word("Fei"), // 0x20
  new Word("Bi"), // 0x21
  new Word("Qin"), // 0x22
  new Word("Qin"), // 0x23
  new Word("Jie"), // 0x24
  new Word("Bu"), // 0x25
  new Word("Fou"), // 0x26
  new Word("Ba"), // 0x27
  new Word("Dun"), // 0x28
  new Word("Fen"), // 0x29
  new Word("E"), // 0x2a
  new Word("Han"), // 0x2b
  new Word("Ting"), // 0x2c
  new Word("Hang"), // 0x2d
  new Word("Shun"), // 0x2e
  new Word("Qi"), // 0x2f
  new Word("Hong"), // 0x30
  new Word("Zhi"), // 0x31
  new Word("Shen"), // 0x32
  new Word("Wu"), // 0x33
  new Word("Wu"), // 0x34
  new Word("Chao"), // 0x35
  new Word("Ne"), // 0x36
  new Word("Xue"), // 0x37
  new Word("Xi"), // 0x38
  new Word("Chui"), // 0x39
  new Word("Dou"), // 0x3a
  new Word("Wen"), // 0x3b
  new Word("Hou"), // 0x3c
  new Word("Ou"), // 0x3d
  new Word("Wu"), // 0x3e
  new Word("Gao"), // 0x3f
  new Word("Ya"), // 0x40
  new Word("Jun"), // 0x41
  new Word("Lu"), // 0x42
  new Word("E"), // 0x43
  new Word("Ge"), // 0x44
  new Word("Mei"), // 0x45
  new Word("Ai"), // 0x46
  new Word("Qi"), // 0x47
  new Word("Cheng"), // 0x48
  new Word("Wu"), // 0x49
  new Word("Gao"), // 0x4a
  new Word("Fu"), // 0x4b
  new Word("Jiao"), // 0x4c
  new Word("Hong"), // 0x4d
  new Word("Chi"), // 0x4e
  new Word("Sheng"), // 0x4f
  new Word("Ne"), // 0x50
  new Word("Tun"), // 0x51
  new Word("Fu"), // 0x52
  new Word("Yi"), // 0x53
  new Word("Dai"), // 0x54
  new Word("Ou"), // 0x55
  new Word("Li"), // 0x56
  new Word("Bai"), // 0x57
  new Word("Yuan"), // 0x58
  new Word("Kuai"), // 0x59
  null, // 0x5a
  new Word("Qiang"), // 0x5b
  new Word("Wu"), // 0x5c
  new Word("E"), // 0x5d
  new Word("Shi"), // 0x5e
  new Word("Quan"), // 0x5f
  new Word("Pen"), // 0x60
  new Word("Wen"), // 0x61
  new Word("Ni"), // 0x62
  new Word("M"), // 0x63
  new Word("Ling"), // 0x64
  new Word("Ran"), // 0x65
  new Word("You"), // 0x66
  new Word("Di"), // 0x67
  new Word("Zhou"), // 0x68
  new Word("Shi"), // 0x69
  new Word("Zhou"), // 0x6a
  new Word("Tie"), // 0x6b
  new Word("Xi"), // 0x6c
  new Word("Yi"), // 0x6d
  new Word("Qi"), // 0x6e
  new Word("Ping"), // 0x6f
  new Word("Zi"), // 0x70
  new Word("Gu"), // 0x71
  new Word("Zi"), // 0x72
  new Word("Wei"), // 0x73
  new Word("Xu"), // 0x74
  new Word("He"), // 0x75
  new Word("Nao"), // 0x76
  new Word("Xia"), // 0x77
  new Word("Pei"), // 0x78
  new Word("Yi"), // 0x79
  new Word("Xiao"), // 0x7a
  new Word("Shen"), // 0x7b
  new Word("Hu"), // 0x7c
  new Word("Ming"), // 0x7d
  new Word("Da"), // 0x7e
  new Word("Qu"), // 0x7f
  new Word("Ju"), // 0x80
  new Word("Gem"), // 0x81
  new Word("Za"), // 0x82
  new Word("Tuo"), // 0x83
  new Word("Duo"), // 0x84
  new Word("Pou"), // 0x85
  new Word("Pao"), // 0x86
  new Word("Bi"), // 0x87
  new Word("Fu"), // 0x88
  new Word("Yang"), // 0x89
  new Word("He"), // 0x8a
  new Word("Zha"), // 0x8b
  new Word("He"), // 0x8c
  new Word("Hai"), // 0x8d
  new Word("Jiu"), // 0x8e
  new Word("Yong"), // 0x8f
  new Word("Fu"), // 0x90
  new Word("Que"), // 0x91
  new Word("Zhou"), // 0x92
  new Word("Wa"), // 0x93
  new Word("Ka"), // 0x94
  new Word("Gu"), // 0x95
  new Word("Ka"), // 0x96
  new Word("Zuo"), // 0x97
  new Word("Bu"), // 0x98
  new Word("Long"), // 0x99
  new Word("Dong"), // 0x9a
  new Word("Ning"), // 0x9b
  new Word("Tha"), // 0x9c
  new Word("Si"), // 0x9d
  new Word("Xian"), // 0x9e
  new Word("Huo"), // 0x9f
  new Word("Qi"), // 0xa0
  new Word("Er"), // 0xa1
  new Word("E"), // 0xa2
  new Word("Guang"), // 0xa3
  new Word("Zha"), // 0xa4
  new Word("Xi"), // 0xa5
  new Word("Yi"), // 0xa6
  new Word("Lie"), // 0xa7
  new Word("Zi"), // 0xa8
  new Word("Mie"), // 0xa9
  new Word("Mi"), // 0xaa
  new Word("Zhi"), // 0xab
  new Word("Yao"), // 0xac
  new Word("Ji"), // 0xad
  new Word("Zhou"), // 0xae
  new Word("Ge"), // 0xaf
  new Word("Shuai"), // 0xb0
  new Word("Zan"), // 0xb1
  new Word("Xiao"), // 0xb2
  new Word("Ke"), // 0xb3
  new Word("Hui"), // 0xb4
  new Word("Kua"), // 0xb5
  new Word("Huai"), // 0xb6
  new Word("Tao"), // 0xb7
  new Word("Xian"), // 0xb8
  new Word("E"), // 0xb9
  new Word("Xuan"), // 0xba
  new Word("Xiu"), // 0xbb
  new Word("Wai"), // 0xbc
  new Word("Yan"), // 0xbd
  new Word("Lao"), // 0xbe
  new Word("Yi"), // 0xbf
  new Word("Ai"), // 0xc0
  new Word("Pin"), // 0xc1
  new Word("Shen"), // 0xc2
  new Word("Tong"), // 0xc3
  new Word("Hong"), // 0xc4
  new Word("Xiong"), // 0xc5
  new Word("Chi"), // 0xc6
  new Word("Wa"), // 0xc7
  new Word("Ha"), // 0xc8
  new Word("Zai"), // 0xc9
  new Word("Yu"), // 0xca
  new Word("Di"), // 0xcb
  new Word("Pai"), // 0xcc
  new Word("Xiang"), // 0xcd
  new Word("Ai"), // 0xce
  new Word("Hen"), // 0xcf
  new Word("Kuang"), // 0xd0
  new Word("Ya"), // 0xd1
  new Word("Da"), // 0xd2
  new Word("Xiao"), // 0xd3
  new Word("Bi"), // 0xd4
  new Word("Yue"), // 0xd5
  null, // 0xd6
  new Word("Hua"), // 0xd7
  new Word("Sasou"), // 0xd8
  new Word("Kuai"), // 0xd9
  new Word("Duo"), // 0xda
  null, // 0xdb
  new Word("Ji"), // 0xdc
  new Word("Nong"), // 0xdd
  new Word("Mou"), // 0xde
  new Word("Yo"), // 0xdf
  new Word("Hao"), // 0xe0
  new Word("Yuan"), // 0xe1
  new Word("Long"), // 0xe2
  new Word("Pou"), // 0xe3
  new Word("Mang"), // 0xe4
  new Word("Ge"), // 0xe5
  new Word("E"), // 0xe6
  new Word("Chi"), // 0xe7
  new Word("Shao"), // 0xe8
  new Word("Li"), // 0xe9
  new Word("Na"), // 0xea
  new Word("Zu"), // 0xeb
  new Word("He"), // 0xec
  new Word("Ku"), // 0xed
  new Word("Xiao"), // 0xee
  new Word("Xian"), // 0xef
  new Word("Lao"), // 0xf0
  new Word("Bo"), // 0xf1
  new Word("Zhe"), // 0xf2
  new Word("Zha"), // 0xf3
  new Word("Liang"), // 0xf4
  new Word("Ba"), // 0xf5
  new Word("Mie"), // 0xf6
  new Word("Le"), // 0xf7
  new Word("Sui"), // 0xf8
  new Word("Fou"), // 0xf9
  new Word("Bu"), // 0xfa
  new Word("Han"), // 0xfb
  new Word("Heng"), // 0xfc
  new Word("Geng"), // 0xfd
  new Word("Shuo"), // 0xfe
  new Word("Ge") // 0xff
  };
}