/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+55xx (CJK Unified Ideographs).
 */
final class X55 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("You"), // 0x00
  new Word("Yan"), // 0x01
  new Word("Gu"), // 0x02
  new Word("Gu"), // 0x03
  new Word("Bai"), // 0x04
  new Word("Han"), // 0x05
  new Word("Suo"), // 0x06
  new Word("Chun"), // 0x07
  new Word("Yi"), // 0x08
  new Word("Ai"), // 0x09
  new Word("Jia"), // 0x0a
  new Word("Tu"), // 0x0b
  new Word("Xian"), // 0x0c
  new Word("Huan"), // 0x0d
  new Word("Li"), // 0x0e
  new Word("Xi"), // 0x0f
  new Word("Tang"), // 0x10
  new Word("Zuo"), // 0x11
  new Word("Qiu"), // 0x12
  new Word("Che"), // 0x13
  new Word("Wu"), // 0x14
  new Word("Zao"), // 0x15
  new Word("Ya"), // 0x16
  new Word("Dou"), // 0x17
  new Word("Qi"), // 0x18
  new Word("Di"), // 0x19
  new Word("Qin"), // 0x1a
  new Word("Ma"), // 0x1b
  new Word("Mal"), // 0x1c
  new Word("Hong"), // 0x1d
  new Word("Dou"), // 0x1e
  new Word("Kes"), // 0x1f
  new Word("Lao"), // 0x20
  new Word("Liang"), // 0x21
  new Word("Suo"), // 0x22
  new Word("Zao"), // 0x23
  new Word("Huan"), // 0x24
  new Word("Lang"), // 0x25
  new Word("Sha"), // 0x26
  new Word("Ji"), // 0x27
  new Word("Zuo"), // 0x28
  new Word("Wo"), // 0x29
  new Word("Feng"), // 0x2a
  new Word("Yin"), // 0x2b
  new Word("Hu"), // 0x2c
  new Word("Qi"), // 0x2d
  new Word("Shou"), // 0x2e
  new Word("Wei"), // 0x2f
  new Word("Shua"), // 0x30
  new Word("Chang"), // 0x31
  new Word("Er"), // 0x32
  new Word("Li"), // 0x33
  new Word("Qiang"), // 0x34
  new Word("An"), // 0x35
  new Word("Jie"), // 0x36
  new Word("Yo"), // 0x37
  new Word("Nian"), // 0x38
  new Word("Yu"), // 0x39
  new Word("Tian"), // 0x3a
  new Word("Lai"), // 0x3b
  new Word("Sha"), // 0x3c
  new Word("Xi"), // 0x3d
  new Word("Tuo"), // 0x3e
  new Word("Hu"), // 0x3f
  new Word("Ai"), // 0x40
  new Word("Zhou"), // 0x41
  new Word("Nou"), // 0x42
  new Word("Ken"), // 0x43
  new Word("Zhuo"), // 0x44
  new Word("Zhuo"), // 0x45
  new Word("Shang"), // 0x46
  new Word("Di"), // 0x47
  new Word("Heng"), // 0x48
  new Word("Lan"), // 0x49
  new Word("A"), // 0x4a
  new Word("Xiao"), // 0x4b
  new Word("Xiang"), // 0x4c
  new Word("Tun"), // 0x4d
  new Word("Wu"), // 0x4e
  new Word("Wen"), // 0x4f
  new Word("Cui"), // 0x50
  new Word("Sha"), // 0x51
  new Word("Hu"), // 0x52
  new Word("Qi"), // 0x53
  new Word("Qi"), // 0x54
  new Word("Tao"), // 0x55
  new Word("Dan"), // 0x56
  new Word("Dan"), // 0x57
  new Word("Ye"), // 0x58
  new Word("Zi"), // 0x59
  new Word("Bi"), // 0x5a
  new Word("Cui"), // 0x5b
  new Word("Chuo"), // 0x5c
  new Word("He"), // 0x5d
  new Word("Ya"), // 0x5e
  new Word("Qi"), // 0x5f
  new Word("Zhe"), // 0x60
  new Word("Pei"), // 0x61
  new Word("Liang"), // 0x62
  new Word("Xian"), // 0x63
  new Word("Pi"), // 0x64
  new Word("Sha"), // 0x65
  new Word("La"), // 0x66
  new Word("Ze"), // 0x67
  new Word("Qing"), // 0x68
  new Word("Gua"), // 0x69
  new Word("Pa"), // 0x6a
  new Word("Zhe"), // 0x6b
  new Word("Se"), // 0x6c
  new Word("Zhuan"), // 0x6d
  new Word("Nie"), // 0x6e
  new Word("Guo"), // 0x6f
  new Word("Luo"), // 0x70
  new Word("Yan"), // 0x71
  new Word("Di"), // 0x72
  new Word("Quan"), // 0x73
  new Word("Tan"), // 0x74
  new Word("Bo"), // 0x75
  new Word("Ding"), // 0x76
  new Word("Lang"), // 0x77
  new Word("Xiao"), // 0x78
  null, // 0x79
  new Word("Tang"), // 0x7a
  new Word("Chi"), // 0x7b
  new Word("Ti"), // 0x7c
  new Word("An"), // 0x7d
  new Word("Jiu"), // 0x7e
  new Word("Dan"), // 0x7f
  new Word("Ke"), // 0x80
  new Word("Yong"), // 0x81
  new Word("Wei"), // 0x82
  new Word("Nan"), // 0x83
  new Word("Shan"), // 0x84
  new Word("Yu"), // 0x85
  new Word("Zhe"), // 0x86
  new Word("La"), // 0x87
  new Word("Jie"), // 0x88
  new Word("Hou"), // 0x89
  new Word("Han"), // 0x8a
  new Word("Die"), // 0x8b
  new Word("Zhou"), // 0x8c
  new Word("Chai"), // 0x8d
  new Word("Wai"), // 0x8e
  new Word("Re"), // 0x8f
  new Word("Yu"), // 0x90
  new Word("Yin"), // 0x91
  new Word("Zan"), // 0x92
  new Word("Yao"), // 0x93
  new Word("Wo"), // 0x94
  new Word("Mian"), // 0x95
  new Word("Hu"), // 0x96
  new Word("Yun"), // 0x97
  new Word("Chuan"), // 0x98
  new Word("Hui"), // 0x99
  new Word("Huan"), // 0x9a
  new Word("Huan"), // 0x9b
  new Word("Xi"), // 0x9c
  new Word("He"), // 0x9d
  new Word("Ji"), // 0x9e
  new Word("Kui"), // 0x9f
  new Word("Zhong"), // 0xa0
  new Word("Wei"), // 0xa1
  new Word("Sha"), // 0xa2
  new Word("Xu"), // 0xa3
  new Word("Huang"), // 0xa4
  new Word("Du"), // 0xa5
  new Word("Nie"), // 0xa6
  new Word("Xuan"), // 0xa7
  new Word("Liang"), // 0xa8
  new Word("Yu"), // 0xa9
  new Word("Sang"), // 0xaa
  new Word("Chi"), // 0xab
  new Word("Qiao"), // 0xac
  new Word("Yan"), // 0xad
  new Word("Dan"), // 0xae
  new Word("Pen"), // 0xaf
  new Word("Can"), // 0xb0
  new Word("Li"), // 0xb1
  new Word("Yo"), // 0xb2
  new Word("Zha"), // 0xb3
  new Word("Wei"), // 0xb4
  new Word("Miao"), // 0xb5
  new Word("Ying"), // 0xb6
  new Word("Pen"), // 0xb7
  new Word("Phos"), // 0xb8
  new Word("Kui"), // 0xb9
  new Word("Xi"), // 0xba
  new Word("Yu"), // 0xbb
  new Word("Jie"), // 0xbc
  new Word("Lou"), // 0xbd
  new Word("Ku"), // 0xbe
  new Word("Sao"), // 0xbf
  new Word("Huo"), // 0xc0
  new Word("Ti"), // 0xc1
  new Word("Yao"), // 0xc2
  new Word("He"), // 0xc3
  new Word("A"), // 0xc4
  new Word("Xiu"), // 0xc5
  new Word("Qiang"), // 0xc6
  new Word("Se"), // 0xc7
  new Word("Yong"), // 0xc8
  new Word("Su"), // 0xc9
  new Word("Hong"), // 0xca
  new Word("Xie"), // 0xcb
  new Word("Yi"), // 0xcc
  new Word("Suo"), // 0xcd
  new Word("Ma"), // 0xce
  new Word("Cha"), // 0xcf
  new Word("Hai"), // 0xd0
  new Word("Ke"), // 0xd1
  new Word("Ta"), // 0xd2
  new Word("Sang"), // 0xd3
  new Word("Tian"), // 0xd4
  new Word("Ru"), // 0xd5
  new Word("Sou"), // 0xd6
  new Word("Wa"), // 0xd7
  new Word("Ji"), // 0xd8
  new Word("Pang"), // 0xd9
  new Word("Wu"), // 0xda
  new Word("Xian"), // 0xdb
  new Word("Shi"), // 0xdc
  new Word("Ge"), // 0xdd
  new Word("Zi"), // 0xde
  new Word("Jie"), // 0xdf
  new Word("Luo"), // 0xe0
  new Word("Weng"), // 0xe1
  new Word("Wa"), // 0xe2
  new Word("Si"), // 0xe3
  new Word("Chi"), // 0xe4
  new Word("Hao"), // 0xe5
  new Word("Suo"), // 0xe6
  new Word("Jia"), // 0xe7
  new Word("Hai"), // 0xe8
  new Word("Suo"), // 0xe9
  new Word("Qin"), // 0xea
  new Word("Nie"), // 0xeb
  new Word("He"), // 0xec
  new Word("Cis"), // 0xed
  new Word("Sai"), // 0xee
  new Word("Ng"), // 0xef
  new Word("Ge"), // 0xf0
  new Word("Na"), // 0xf1
  new Word("Dia"), // 0xf2
  new Word("Ai"), // 0xf3
  null, // 0xf4
  new Word("Tong"), // 0xf5
  new Word("Bi"), // 0xf6
  new Word("Ao"), // 0xf7
  new Word("Ao"), // 0xf8
  new Word("Lian"), // 0xf9
  new Word("Cui"), // 0xfa
  new Word("Zhe"), // 0xfb
  new Word("Mo"), // 0xfc
  new Word("Sou"), // 0xfd
  new Word("Sou"), // 0xfe
  new Word("Tan") // 0xff
  };
}