/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+57xx (CJK Unified Ideographs).
 */
final class X57 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Guo"), // 0x00
  new Word("Yin"), // 0x01
  new Word("Hun"), // 0x02
  new Word("Pu"), // 0x03
  new Word("Yu"), // 0x04
  new Word("Han"), // 0x05
  new Word("Yuan"), // 0x06
  new Word("Lun"), // 0x07
  new Word("Quan"), // 0x08
  new Word("Yu"), // 0x09
  new Word("Qing"), // 0x0a
  new Word("Guo"), // 0x0b
  new Word("Chuan"), // 0x0c
  new Word("Wei"), // 0x0d
  new Word("Yuan"), // 0x0e
  new Word("Quan"), // 0x0f
  new Word("Ku"), // 0x10
  new Word("Fu"), // 0x11
  new Word("Yuan"), // 0x12
  new Word("Yuan"), // 0x13
  new Word("E"), // 0x14
  new Word("Tu"), // 0x15
  new Word("Tu"), // 0x16
  new Word("Tu"), // 0x17
  new Word("Tuan"), // 0x18
  new Word("Lue"), // 0x19
  new Word("Hui"), // 0x1a
  new Word("Yi"), // 0x1b
  new Word("Yuan"), // 0x1c
  new Word("Luan"), // 0x1d
  new Word("Luan"), // 0x1e
  new Word("Tu"), // 0x1f
  new Word("Ya"), // 0x20
  new Word("Tu"), // 0x21
  new Word("Ting"), // 0x22
  new Word("Sheng"), // 0x23
  new Word("Pu"), // 0x24
  new Word("Lu"), // 0x25
  new Word("Iri"), // 0x26
  new Word("Ya"), // 0x27
  new Word("Zai"), // 0x28
  new Word("Wei"), // 0x29
  new Word("Ge"), // 0x2a
  new Word("Yu"), // 0x2b
  new Word("Wu"), // 0x2c
  new Word("Gui"), // 0x2d
  new Word("Pi"), // 0x2e
  new Word("Yi"), // 0x2f
  new Word("Di"), // 0x30
  new Word("Qian"), // 0x31
  new Word("Qian"), // 0x32
  new Word("Zhen"), // 0x33
  new Word("Zhuo"), // 0x34
  new Word("Dang"), // 0x35
  new Word("Qia"), // 0x36
  new Word("Akutsu"), // 0x37
  new Word("Yama"), // 0x38
  new Word("Kuang"), // 0x39
  new Word("Chang"), // 0x3a
  new Word("Qi"), // 0x3b
  new Word("Nie"), // 0x3c
  new Word("Mo"), // 0x3d
  new Word("Ji"), // 0x3e
  new Word("Jia"), // 0x3f
  new Word("Zhi"), // 0x40
  new Word("Zhi"), // 0x41
  new Word("Ban"), // 0x42
  new Word("Xun"), // 0x43
  new Word("Tou"), // 0x44
  new Word("Qin"), // 0x45
  new Word("Fen"), // 0x46
  new Word("Jun"), // 0x47
  new Word("Keng"), // 0x48
  new Word("Tun"), // 0x49
  new Word("Fang"), // 0x4a
  new Word("Fen"), // 0x4b
  new Word("Ben"), // 0x4c
  new Word("Tan"), // 0x4d
  new Word("Kan"), // 0x4e
  new Word("Pi"), // 0x4f
  new Word("Zuo"), // 0x50
  new Word("Keng"), // 0x51
  new Word("Bi"), // 0x52
  new Word("Xing"), // 0x53
  new Word("Di"), // 0x54
  new Word("Jing"), // 0x55
  new Word("Ji"), // 0x56
  new Word("Kuai"), // 0x57
  new Word("Di"), // 0x58
  new Word("Jing"), // 0x59
  new Word("Jian"), // 0x5a
  new Word("Tan"), // 0x5b
  new Word("Li"), // 0x5c
  new Word("Ba"), // 0x5d
  new Word("Wu"), // 0x5e
  new Word("Fen"), // 0x5f
  new Word("Zhui"), // 0x60
  new Word("Po"), // 0x61
  new Word("Pan"), // 0x62
  new Word("Tang"), // 0x63
  new Word("Kun"), // 0x64
  new Word("Qu"), // 0x65
  new Word("Tan"), // 0x66
  new Word("Zhi"), // 0x67
  new Word("Tuo"), // 0x68
  new Word("Gan"), // 0x69
  new Word("Ping"), // 0x6a
  new Word("Dian"), // 0x6b
  new Word("Gua"), // 0x6c
  new Word("Ni"), // 0x6d
  new Word("Tai"), // 0x6e
  new Word("Pi"), // 0x6f
  new Word("Jiong"), // 0x70
  new Word("Yang"), // 0x71
  new Word("Fo"), // 0x72
  new Word("Ao"), // 0x73
  new Word("Liu"), // 0x74
  new Word("Qiu"), // 0x75
  new Word("Mu"), // 0x76
  new Word("Ke"), // 0x77
  new Word("Gou"), // 0x78
  new Word("Xue"), // 0x79
  new Word("Ba"), // 0x7a
  new Word("Chi"), // 0x7b
  new Word("Che"), // 0x7c
  new Word("Ling"), // 0x7d
  new Word("Zhu"), // 0x7e
  new Word("Fu"), // 0x7f
  new Word("Hu"), // 0x80
  new Word("Zhi"), // 0x81
  new Word("Chui"), // 0x82
  new Word("La"), // 0x83
  new Word("Long"), // 0x84
  new Word("Long"), // 0x85
  new Word("Lu"), // 0x86
  new Word("Ao"), // 0x87
  new Word("Tay"), // 0x88
  new Word("Pao"), // 0x89
  null, // 0x8a
  new Word("Xing"), // 0x8b
  new Word("Dong"), // 0x8c
  new Word("Ji"), // 0x8d
  new Word("Ke"), // 0x8e
  new Word("Lu"), // 0x8f
  new Word("Ci"), // 0x90
  new Word("Chi"), // 0x91
  new Word("Lei"), // 0x92
  new Word("Gai"), // 0x93
  new Word("Yin"), // 0x94
  new Word("Hou"), // 0x95
  new Word("Dui"), // 0x96
  new Word("Zhao"), // 0x97
  new Word("Fu"), // 0x98
  new Word("Guang"), // 0x99
  new Word("Yao"), // 0x9a
  new Word("Duo"), // 0x9b
  new Word("Duo"), // 0x9c
  new Word("Gui"), // 0x9d
  new Word("Cha"), // 0x9e
  new Word("Yang"), // 0x9f
  new Word("Yin"), // 0xa0
  new Word("Fa"), // 0xa1
  new Word("Gou"), // 0xa2
  new Word("Yuan"), // 0xa3
  new Word("Die"), // 0xa4
  new Word("Xie"), // 0xa5
  new Word("Ken"), // 0xa6
  new Word("Jiong"), // 0xa7
  new Word("Shou"), // 0xa8
  new Word("E"), // 0xa9
  new Word("Ha"), // 0xaa
  new Word("Dian"), // 0xab
  new Word("Hong"), // 0xac
  new Word("Wu"), // 0xad
  new Word("Kua"), // 0xae
  null, // 0xaf
  new Word("Tao"), // 0xb0
  new Word("Dang"), // 0xb1
  new Word("Kai"), // 0xb2
  new Word("Gake"), // 0xb3
  new Word("Nao"), // 0xb4
  new Word("An"), // 0xb5
  new Word("Xing"), // 0xb6
  new Word("Xian"), // 0xb7
  new Word("Huan"), // 0xb8
  new Word("Bang"), // 0xb9
  new Word("Pei"), // 0xba
  new Word("Ba"), // 0xbb
  new Word("Yi"), // 0xbc
  new Word("Yin"), // 0xbd
  new Word("Han"), // 0xbe
  new Word("Xu"), // 0xbf
  new Word("Chui"), // 0xc0
  new Word("Cen"), // 0xc1
  new Word("Geng"), // 0xc2
  new Word("Ai"), // 0xc3
  new Word("Peng"), // 0xc4
  new Word("Fang"), // 0xc5
  new Word("Que"), // 0xc6
  new Word("Yong"), // 0xc7
  new Word("Xun"), // 0xc8
  new Word("Jia"), // 0xc9
  new Word("Di"), // 0xca
  new Word("Mai"), // 0xcb
  new Word("Lang"), // 0xcc
  new Word("Xuan"), // 0xcd
  new Word("Cheng"), // 0xce
  new Word("Yan"), // 0xcf
  new Word("Jin"), // 0xd0
  new Word("Zhe"), // 0xd1
  new Word("Lei"), // 0xd2
  new Word("Lie"), // 0xd3
  new Word("Bu"), // 0xd4
  new Word("Cheng"), // 0xd5
  new Word("Gomi"), // 0xd6
  new Word("Bu"), // 0xd7
  new Word("Shi"), // 0xd8
  new Word("Xun"), // 0xd9
  new Word("Guo"), // 0xda
  new Word("Jiong"), // 0xdb
  new Word("Ye"), // 0xdc
  new Word("Nian"), // 0xdd
  new Word("Di"), // 0xde
  new Word("Yu"), // 0xdf
  new Word("Bu"), // 0xe0
  new Word("Ya"), // 0xe1
  new Word("Juan"), // 0xe2
  new Word("Sui"), // 0xe3
  new Word("Pi"), // 0xe4
  new Word("Cheng"), // 0xe5
  new Word("Wan"), // 0xe6
  new Word("Ju"), // 0xe7
  new Word("Lun"), // 0xe8
  new Word("Zheng"), // 0xe9
  new Word("Kong"), // 0xea
  new Word("Chong"), // 0xeb
  new Word("Dong"), // 0xec
  new Word("Dai"), // 0xed
  new Word("Tan"), // 0xee
  new Word("An"), // 0xef
  new Word("Cai"), // 0xf0
  new Word("Shu"), // 0xf1
  new Word("Beng"), // 0xf2
  new Word("Kan"), // 0xf3
  new Word("Zhi"), // 0xf4
  new Word("Duo"), // 0xf5
  new Word("Yi"), // 0xf6
  new Word("Zhi"), // 0xf7
  new Word("Yi"), // 0xf8
  new Word("Pei"), // 0xf9
  new Word("Ji"), // 0xfa
  new Word("Zhun"), // 0xfb
  new Word("Qi"), // 0xfc
  new Word("Sao"), // 0xfd
  new Word("Ju"), // 0xfe
  new Word("Ni") // 0xff
  };
}