/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+58xx (CJK Unified Ideographs).
 */
final class X58 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Ku"), // 0x00
  new Word("Ke"), // 0x01
  new Word("Tang"), // 0x02
  new Word("Kun"), // 0x03
  new Word("Ni"), // 0x04
  new Word("Jian"), // 0x05
  new Word("Dui"), // 0x06
  new Word("Jin"), // 0x07
  new Word("Gang"), // 0x08
  new Word("Yu"), // 0x09
  new Word("E"), // 0x0a
  new Word("Peng"), // 0x0b
  new Word("Gu"), // 0x0c
  new Word("Tu"), // 0x0d
  new Word("Leng"), // 0x0e
  null, // 0x0f
  new Word("Ya"), // 0x10
  new Word("Qian"), // 0x11
  null, // 0x12
  new Word("An"), // 0x13
  null, // 0x14
  new Word("Duo"), // 0x15
  new Word("Nao"), // 0x16
  new Word("Tu"), // 0x17
  new Word("Cheng"), // 0x18
  new Word("Yin"), // 0x19
  new Word("Hun"), // 0x1a
  new Word("Bi"), // 0x1b
  new Word("Lian"), // 0x1c
  new Word("Guo"), // 0x1d
  new Word("Die"), // 0x1e
  new Word("Zhuan"), // 0x1f
  new Word("Hou"), // 0x20
  new Word("Bao"), // 0x21
  new Word("Bao"), // 0x22
  new Word("Yu"), // 0x23
  new Word("Di"), // 0x24
  new Word("Mao"), // 0x25
  new Word("Jie"), // 0x26
  new Word("Ruan"), // 0x27
  new Word("E"), // 0x28
  new Word("Geng"), // 0x29
  new Word("Kan"), // 0x2a
  new Word("Zong"), // 0x2b
  new Word("Yu"), // 0x2c
  new Word("Huang"), // 0x2d
  new Word("E"), // 0x2e
  new Word("Yao"), // 0x2f
  new Word("Yan"), // 0x30
  new Word("Bao"), // 0x31
  new Word("Ji"), // 0x32
  new Word("Mei"), // 0x33
  new Word("Chang"), // 0x34
  new Word("Du"), // 0x35
  new Word("Tuo"), // 0x36
  new Word("Yin"), // 0x37
  new Word("Feng"), // 0x38
  new Word("Zhong"), // 0x39
  new Word("Jie"), // 0x3a
  new Word("Zhen"), // 0x3b
  new Word("Feng"), // 0x3c
  new Word("Gang"), // 0x3d
  new Word("Chuan"), // 0x3e
  new Word("Jian"), // 0x3f
  new Word("Pyeng"), // 0x40
  new Word("Toride"), // 0x41
  new Word("Xiang"), // 0x42
  new Word("Huang"), // 0x43
  new Word("Leng"), // 0x44
  new Word("Duan"), // 0x45
  null, // 0x46
  new Word("Xuan"), // 0x47
  new Word("Ji"), // 0x48
  new Word("Ji"), // 0x49
  new Word("Kuai"), // 0x4a
  new Word("Ying"), // 0x4b
  new Word("Ta"), // 0x4c
  new Word("Cheng"), // 0x4d
  new Word("Yong"), // 0x4e
  new Word("Kai"), // 0x4f
  new Word("Su"), // 0x50
  new Word("Su"), // 0x51
  new Word("Shi"), // 0x52
  new Word("Mi"), // 0x53
  new Word("Ta"), // 0x54
  new Word("Weng"), // 0x55
  new Word("Cheng"), // 0x56
  new Word("Tu"), // 0x57
  new Word("Tang"), // 0x58
  new Word("Que"), // 0x59
  new Word("Zhong"), // 0x5a
  new Word("Li"), // 0x5b
  new Word("Peng"), // 0x5c
  new Word("Bang"), // 0x5d
  new Word("Sai"), // 0x5e
  new Word("Zang"), // 0x5f
  new Word("Dui"), // 0x60
  new Word("Tian"), // 0x61
  new Word("Wu"), // 0x62
  new Word("Cheng"), // 0x63
  new Word("Xun"), // 0x64
  new Word("Ge"), // 0x65
  new Word("Zhen"), // 0x66
  new Word("Ai"), // 0x67
  new Word("Gong"), // 0x68
  new Word("Yan"), // 0x69
  new Word("Kan"), // 0x6a
  new Word("Tian"), // 0x6b
  new Word("Yuan"), // 0x6c
  new Word("Wen"), // 0x6d
  new Word("Xie"), // 0x6e
  new Word("Liu"), // 0x6f
  new Word("Ama"), // 0x70
  new Word("Lang"), // 0x71
  new Word("Chang"), // 0x72
  new Word("Peng"), // 0x73
  new Word("Beng"), // 0x74
  new Word("Chen"), // 0x75
  new Word("Cu"), // 0x76
  new Word("Lu"), // 0x77
  new Word("Ou"), // 0x78
  new Word("Qian"), // 0x79
  new Word("Mei"), // 0x7a
  new Word("Mo"), // 0x7b
  new Word("Zhuan"), // 0x7c
  new Word("Shuang"), // 0x7d
  new Word("Shu"), // 0x7e
  new Word("Lou"), // 0x7f
  new Word("Chi"), // 0x80
  new Word("Man"), // 0x81
  new Word("Biao"), // 0x82
  new Word("Jing"), // 0x83
  new Word("Qi"), // 0x84
  new Word("Shu"), // 0x85
  new Word("Di"), // 0x86
  new Word("Zhang"), // 0x87
  new Word("Kan"), // 0x88
  new Word("Yong"), // 0x89
  new Word("Dian"), // 0x8a
  new Word("Chen"), // 0x8b
  new Word("Zhi"), // 0x8c
  new Word("Xi"), // 0x8d
  new Word("Guo"), // 0x8e
  new Word("Qiang"), // 0x8f
  new Word("Jin"), // 0x90
  new Word("Di"), // 0x91
  new Word("Shang"), // 0x92
  new Word("Mu"), // 0x93
  new Word("Cui"), // 0x94
  new Word("Yan"), // 0x95
  new Word("Ta"), // 0x96
  new Word("Zeng"), // 0x97
  new Word("Qi"), // 0x98
  new Word("Qiang"), // 0x99
  new Word("Liang"), // 0x9a
  null, // 0x9b
  new Word("Zhui"), // 0x9c
  new Word("Qiao"), // 0x9d
  new Word("Zeng"), // 0x9e
  new Word("Xu"), // 0x9f
  new Word("Shan"), // 0xa0
  new Word("Shan"), // 0xa1
  new Word("Ba"), // 0xa2
  new Word("Pu"), // 0xa3
  new Word("Kuai"), // 0xa4
  new Word("Dong"), // 0xa5
  new Word("Fan"), // 0xa6
  new Word("Que"), // 0xa7
  new Word("Mo"), // 0xa8
  new Word("Dun"), // 0xa9
  new Word("Dun"), // 0xaa
  new Word("Dun"), // 0xab
  new Word("Di"), // 0xac
  new Word("Sheng"), // 0xad
  new Word("Duo"), // 0xae
  new Word("Duo"), // 0xaf
  new Word("Tan"), // 0xb0
  new Word("Deng"), // 0xb1
  new Word("Wu"), // 0xb2
  new Word("Fen"), // 0xb3
  new Word("Huang"), // 0xb4
  new Word("Tan"), // 0xb5
  new Word("Da"), // 0xb6
  new Word("Ye"), // 0xb7
  new Word("Sho"), // 0xb8
  new Word("Mama"), // 0xb9
  new Word("Yu"), // 0xba
  new Word("Qiang"), // 0xbb
  new Word("Ji"), // 0xbc
  new Word("Qiao"), // 0xbd
  new Word("Ken"), // 0xbe
  new Word("Yi"), // 0xbf
  new Word("Pi"), // 0xc0
  new Word("Bi"), // 0xc1
  new Word("Dian"), // 0xc2
  new Word("Jiang"), // 0xc3
  new Word("Ye"), // 0xc4
  new Word("Yong"), // 0xc5
  new Word("Bo"), // 0xc6
  new Word("Tan"), // 0xc7
  new Word("Lan"), // 0xc8
  new Word("Ju"), // 0xc9
  new Word("Huai"), // 0xca
  new Word("Dang"), // 0xcb
  new Word("Rang"), // 0xcc
  new Word("Qian"), // 0xcd
  new Word("Xun"), // 0xce
  new Word("Lan"), // 0xcf
  new Word("Xi"), // 0xd0
  new Word("He"), // 0xd1
  new Word("Ai"), // 0xd2
  new Word("Ya"), // 0xd3
  new Word("Dao"), // 0xd4
  new Word("Hao"), // 0xd5
  new Word("Ruan"), // 0xd6
  new Word("Mama"), // 0xd7
  new Word("Lei"), // 0xd8
  new Word("Kuang"), // 0xd9
  new Word("Lu"), // 0xda
  new Word("Yan"), // 0xdb
  new Word("Tan"), // 0xdc
  new Word("Wei"), // 0xdd
  new Word("Huai"), // 0xde
  new Word("Long"), // 0xdf
  new Word("Long"), // 0xe0
  new Word("Rui"), // 0xe1
  new Word("Li"), // 0xe2
  new Word("Lin"), // 0xe3
  new Word("Rang"), // 0xe4
  new Word("Ten"), // 0xe5
  new Word("Xun"), // 0xe6
  new Word("Yan"), // 0xe7
  new Word("Lei"), // 0xe8
  new Word("Ba"), // 0xe9
  null, // 0xea
  new Word("Shi"), // 0xeb
  new Word("Ren"), // 0xec
  null, // 0xed
  new Word("Zhuang"), // 0xee
  new Word("Zhuang"), // 0xef
  new Word("Sheng"), // 0xf0
  new Word("Yi"), // 0xf1
  new Word("Mai"), // 0xf2
  new Word("Ke"), // 0xf3
  new Word("Zhu"), // 0xf4
  new Word("Zhuang"), // 0xf5
  new Word("Hu"), // 0xf6
  new Word("Hu"), // 0xf7
  new Word("Kun"), // 0xf8
  new Word("Yi"), // 0xf9
  new Word("Hu"), // 0xfa
  new Word("Xu"), // 0xfb
  new Word("Kun"), // 0xfc
  new Word("Shou"), // 0xfd
  new Word("Mang"), // 0xfe
  new Word("Zun") // 0xff
  };
}