/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+59xx (CJK Unified Ideographs).
 */
final class X59 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Shou"), // 0x00
  new Word("Yi"), // 0x01
  new Word("Zhi"), // 0x02
  new Word("Gu"), // 0x03
  new Word("Chu"), // 0x04
  new Word("Jiang"), // 0x05
  new Word("Feng"), // 0x06
  new Word("Bei"), // 0x07
  new Word("Cay"), // 0x08
  new Word("Bian"), // 0x09
  new Word("Sui"), // 0x0a
  new Word("Qun"), // 0x0b
  new Word("Ling"), // 0x0c
  new Word("Fu"), // 0x0d
  new Word("Zuo"), // 0x0e
  new Word("Xia"), // 0x0f
  new Word("Xiong"), // 0x10
  null, // 0x11
  new Word("Nao"), // 0x12
  new Word("Xia"), // 0x13
  new Word("Kui"), // 0x14
  new Word("Xi"), // 0x15
  new Word("Wai"), // 0x16
  new Word("Yuan"), // 0x17
  new Word("Mao"), // 0x18
  new Word("Su"), // 0x19
  new Word("Duo"), // 0x1a
  new Word("Duo"), // 0x1b
  new Word("Ye"), // 0x1c
  new Word("Qing"), // 0x1d
  new Word("Uys"), // 0x1e
  new Word("Gou"), // 0x1f
  new Word("Gou"), // 0x20
  new Word("Qi"), // 0x21
  new Word("Meng"), // 0x22
  new Word("Meng"), // 0x23
  new Word("Yin"), // 0x24
  new Word("Huo"), // 0x25
  new Word("Chen"), // 0x26
  new Word("Da"), // 0x27
  new Word("Ze"), // 0x28
  new Word("Tian"), // 0x29
  new Word("Tai"), // 0x2a
  new Word("Fu"), // 0x2b
  new Word("Guai"), // 0x2c
  new Word("Yao"), // 0x2d
  new Word("Yang"), // 0x2e
  new Word("Hang"), // 0x2f
  new Word("Gao"), // 0x30
  new Word("Shi"), // 0x31
  new Word("Ben"), // 0x32
  new Word("Tai"), // 0x33
  new Word("Tou"), // 0x34
  new Word("Yan"), // 0x35
  new Word("Bi"), // 0x36
  new Word("Yi"), // 0x37
  new Word("Kua"), // 0x38
  new Word("Jia"), // 0x39
  new Word("Duo"), // 0x3a
  new Word("Kwu"), // 0x3b
  new Word("Kuang"), // 0x3c
  new Word("Yun"), // 0x3d
  new Word("Jia"), // 0x3e
  new Word("Pa"), // 0x3f
  new Word("En"), // 0x40
  new Word("Lian"), // 0x41
  new Word("Huan"), // 0x42
  new Word("Di"), // 0x43
  new Word("Yan"), // 0x44
  new Word("Pao"), // 0x45
  new Word("Quan"), // 0x46
  new Word("Qi"), // 0x47
  new Word("Nai"), // 0x48
  new Word("Feng"), // 0x49
  new Word("Xie"), // 0x4a
  new Word("Fen"), // 0x4b
  new Word("Dian"), // 0x4c
  null, // 0x4d
  new Word("Kui"), // 0x4e
  new Word("Zou"), // 0x4f
  new Word("Huan"), // 0x50
  new Word("Qi"), // 0x51
  new Word("Kai"), // 0x52
  new Word("Zha"), // 0x53
  new Word("Ben"), // 0x54
  new Word("Yi"), // 0x55
  new Word("Jiang"), // 0x56
  new Word("Tao"), // 0x57
  new Word("Zang"), // 0x58
  new Word("Ben"), // 0x59
  new Word("Xi"), // 0x5a
  new Word("Xiang"), // 0x5b
  new Word("Fei"), // 0x5c
  new Word("Diao"), // 0x5d
  new Word("Xun"), // 0x5e
  new Word("Keng"), // 0x5f
  new Word("Dian"), // 0x60
  new Word("Ao"), // 0x61
  new Word("She"), // 0x62
  new Word("Weng"), // 0x63
  new Word("Pan"), // 0x64
  new Word("Ao"), // 0x65
  new Word("Wu"), // 0x66
  new Word("Ao"), // 0x67
  new Word("Jiang"), // 0x68
  new Word("Lian"), // 0x69
  new Word("Duo"), // 0x6a
  new Word("Yun"), // 0x6b
  new Word("Jiang"), // 0x6c
  new Word("Shi"), // 0x6d
  new Word("Fen"), // 0x6e
  new Word("Huo"), // 0x6f
  new Word("Bi"), // 0x70
  new Word("Lian"), // 0x71
  new Word("Duo"), // 0x72
  new Word("Nu"), // 0x73
  new Word("Nu"), // 0x74
  new Word("Ding"), // 0x75
  new Word("Nai"), // 0x76
  new Word("Qian"), // 0x77
  new Word("Jian"), // 0x78
  new Word("Ta"), // 0x79
  new Word("Jiu"), // 0x7a
  new Word("Nan"), // 0x7b
  new Word("Cha"), // 0x7c
  new Word("Hao"), // 0x7d
  new Word("Xian"), // 0x7e
  new Word("Fan"), // 0x7f
  new Word("Ji"), // 0x80
  new Word("Shuo"), // 0x81
  new Word("Ru"), // 0x82
  new Word("Fei"), // 0x83
  new Word("Wang"), // 0x84
  new Word("Hong"), // 0x85
  new Word("Zhuang"), // 0x86
  new Word("Fu"), // 0x87
  new Word("Ma"), // 0x88
  new Word("Dan"), // 0x89
  new Word("Ren"), // 0x8a
  new Word("Fu"), // 0x8b
  new Word("Jing"), // 0x8c
  new Word("Yan"), // 0x8d
  new Word("Xie"), // 0x8e
  new Word("Wen"), // 0x8f
  new Word("Zhong"), // 0x90
  new Word("Pa"), // 0x91
  new Word("Du"), // 0x92
  new Word("Ji"), // 0x93
  new Word("Keng"), // 0x94
  new Word("Zhong"), // 0x95
  new Word("Yao"), // 0x96
  new Word("Jin"), // 0x97
  new Word("Yun"), // 0x98
  new Word("Miao"), // 0x99
  new Word("Pei"), // 0x9a
  new Word("Shi"), // 0x9b
  new Word("Yue"), // 0x9c
  new Word("Zhuang"), // 0x9d
  new Word("Niu"), // 0x9e
  new Word("Yan"), // 0x9f
  new Word("Na"), // 0xa0
  new Word("Xin"), // 0xa1
  new Word("Fen"), // 0xa2
  new Word("Bi"), // 0xa3
  new Word("Yu"), // 0xa4
  new Word("Tuo"), // 0xa5
  new Word("Feng"), // 0xa6
  new Word("Yuan"), // 0xa7
  new Word("Fang"), // 0xa8
  new Word("Wu"), // 0xa9
  new Word("Yu"), // 0xaa
  new Word("Gui"), // 0xab
  new Word("Du"), // 0xac
  new Word("Ba"), // 0xad
  new Word("Ni"), // 0xae
  new Word("Zhou"), // 0xaf
  new Word("Zhuo"), // 0xb0
  new Word("Zhao"), // 0xb1
  new Word("Da"), // 0xb2
  new Word("Nai"), // 0xb3
  new Word("Yuan"), // 0xb4
  new Word("Tou"), // 0xb5
  new Word("Xuan"), // 0xb6
  new Word("Zhi"), // 0xb7
  new Word("E"), // 0xb8
  new Word("Mei"), // 0xb9
  new Word("Mo"), // 0xba
  new Word("Qi"), // 0xbb
  new Word("Bi"), // 0xbc
  new Word("Shen"), // 0xbd
  new Word("Qie"), // 0xbe
  new Word("E"), // 0xbf
  new Word("He"), // 0xc0
  new Word("Xu"), // 0xc1
  new Word("Fa"), // 0xc2
  new Word("Zheng"), // 0xc3
  new Word("Min"), // 0xc4
  new Word("Ban"), // 0xc5
  new Word("Mu"), // 0xc6
  new Word("Fu"), // 0xc7
  new Word("Ling"), // 0xc8
  new Word("Zi"), // 0xc9
  new Word("Zi"), // 0xca
  new Word("Shi"), // 0xcb
  new Word("Ran"), // 0xcc
  new Word("Shan"), // 0xcd
  new Word("Yang"), // 0xce
  new Word("Man"), // 0xcf
  new Word("Jie"), // 0xd0
  new Word("Gu"), // 0xd1
  new Word("Si"), // 0xd2
  new Word("Xing"), // 0xd3
  new Word("Wei"), // 0xd4
  new Word("Zi"), // 0xd5
  new Word("Ju"), // 0xd6
  new Word("Shan"), // 0xd7
  new Word("Pin"), // 0xd8
  new Word("Ren"), // 0xd9
  new Word("Yao"), // 0xda
  new Word("Tong"), // 0xdb
  new Word("Jiang"), // 0xdc
  new Word("Shu"), // 0xdd
  new Word("Ji"), // 0xde
  new Word("Gai"), // 0xdf
  new Word("Shang"), // 0xe0
  new Word("Kuo"), // 0xe1
  new Word("Juan"), // 0xe2
  new Word("Jiao"), // 0xe3
  new Word("Gou"), // 0xe4
  new Word("Mu"), // 0xe5
  new Word("Jian"), // 0xe6
  new Word("Jian"), // 0xe7
  new Word("Yi"), // 0xe8
  new Word("Nian"), // 0xe9
  new Word("Zhi"), // 0xea
  new Word("Ji"), // 0xeb
  new Word("Ji"), // 0xec
  new Word("Xian"), // 0xed
  new Word("Heng"), // 0xee
  new Word("Guang"), // 0xef
  new Word("Jun"), // 0xf0
  new Word("Kua"), // 0xf1
  new Word("Yan"), // 0xf2
  new Word("Ming"), // 0xf3
  new Word("Lie"), // 0xf4
  new Word("Pei"), // 0xf5
  new Word("Yan"), // 0xf6
  new Word("You"), // 0xf7
  new Word("Yan"), // 0xf8
  new Word("Cha"), // 0xf9
  new Word("Shen"), // 0xfa
  new Word("Yin"), // 0xfb
  new Word("Chi"), // 0xfc
  new Word("Gui"), // 0xfd
  new Word("Quan"), // 0xfe
  new Word("Zi") // 0xff
  };
}