/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+5Cxx (CJK Unified Ideographs).
 */
final class X5c extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Po"), // 0x00
  new Word("Feng"), // 0x01
  new Word("Zhuan"), // 0x02
  new Word("Fu"), // 0x03
  new Word("She"), // 0x04
  new Word("Ke"), // 0x05
  new Word("Jiang"), // 0x06
  new Word("Jiang"), // 0x07
  new Word("Zhuan"), // 0x08
  new Word("Wei"), // 0x09
  new Word("Zun"), // 0x0a
  new Word("Xun"), // 0x0b
  new Word("Shu"), // 0x0c
  new Word("Dui"), // 0x0d
  new Word("Dao"), // 0x0e
  new Word("Xiao"), // 0x0f
  new Word("Ji"), // 0x10
  new Word("Shao"), // 0x11
  new Word("Er"), // 0x12
  new Word("Er"), // 0x13
  new Word("Er"), // 0x14
  new Word("Ga"), // 0x15
  new Word("Jian"), // 0x16
  new Word("Shu"), // 0x17
  new Word("Chen"), // 0x18
  new Word("Shang"), // 0x19
  new Word("Shang"), // 0x1a
  new Word("Mo"), // 0x1b
  new Word("Ga"), // 0x1c
  new Word("Chang"), // 0x1d
  new Word("Liao"), // 0x1e
  new Word("Xian"), // 0x1f
  new Word("Xian"), // 0x20
  null, // 0x21
  new Word("Wang"), // 0x22
  new Word("Wang"), // 0x23
  new Word("You"), // 0x24
  new Word("Liao"), // 0x25
  new Word("Liao"), // 0x26
  new Word("Yao"), // 0x27
  new Word("Mang"), // 0x28
  new Word("Wang"), // 0x29
  new Word("Wang"), // 0x2a
  new Word("Wang"), // 0x2b
  new Word("Ga"), // 0x2c
  new Word("Yao"), // 0x2d
  new Word("Duo"), // 0x2e
  new Word("Kui"), // 0x2f
  new Word("Zhong"), // 0x30
  new Word("Jiu"), // 0x31
  new Word("Gan"), // 0x32
  new Word("Gu"), // 0x33
  new Word("Gan"), // 0x34
  new Word("Tui"), // 0x35
  new Word("Gan"), // 0x36
  new Word("Gan"), // 0x37
  new Word("Shi"), // 0x38
  new Word("Yin"), // 0x39
  new Word("Chi"), // 0x3a
  new Word("Kao"), // 0x3b
  new Word("Ni"), // 0x3c
  new Word("Jin"), // 0x3d
  new Word("Wei"), // 0x3e
  new Word("Niao"), // 0x3f
  new Word("Ju"), // 0x40
  new Word("Pi"), // 0x41
  new Word("Ceng"), // 0x42
  new Word("Xi"), // 0x43
  new Word("Bi"), // 0x44
  new Word("Ju"), // 0x45
  new Word("Jie"), // 0x46
  new Word("Tian"), // 0x47
  new Word("Qu"), // 0x48
  new Word("Ti"), // 0x49
  new Word("Jie"), // 0x4a
  new Word("Wu"), // 0x4b
  new Word("Diao"), // 0x4c
  new Word("Shi"), // 0x4d
  new Word("Shi"), // 0x4e
  new Word("Ping"), // 0x4f
  new Word("Ji"), // 0x50
  new Word("Xie"), // 0x51
  new Word("Chen"), // 0x52
  new Word("Xi"), // 0x53
  new Word("Ni"), // 0x54
  new Word("Zhan"), // 0x55
  new Word("Xi"), // 0x56
  null, // 0x57
  new Word("Man"), // 0x58
  new Word("E"), // 0x59
  new Word("Lou"), // 0x5a
  new Word("Ping"), // 0x5b
  new Word("Ti"), // 0x5c
  new Word("Fei"), // 0x5d
  new Word("Shu"), // 0x5e
  new Word("Xie"), // 0x5f
  new Word("Tu"), // 0x60
  new Word("Lu"), // 0x61
  new Word("Lu"), // 0x62
  new Word("Xi"), // 0x63
  new Word("Ceng"), // 0x64
  new Word("Lu"), // 0x65
  new Word("Ju"), // 0x66
  new Word("Xie"), // 0x67
  new Word("Ju"), // 0x68
  new Word("Jue"), // 0x69
  new Word("Liao"), // 0x6a
  new Word("Jue"), // 0x6b
  new Word("Shu"), // 0x6c
  new Word("Xi"), // 0x6d
  new Word("Che"), // 0x6e
  new Word("Tun"), // 0x6f
  new Word("Ni"), // 0x70
  new Word("Shan"), // 0x71
  null, // 0x72
  new Word("Xian"), // 0x73
  new Word("Li"), // 0x74
  new Word("Xue"), // 0x75
  new Word("Nata"), // 0x76
  null, // 0x77
  new Word("Long"), // 0x78
  new Word("Yi"), // 0x79
  new Word("Qi"), // 0x7a
  new Word("Ren"), // 0x7b
  new Word("Wu"), // 0x7c
  new Word("Han"), // 0x7d
  new Word("Shen"), // 0x7e
  new Word("Yu"), // 0x7f
  new Word("Chu"), // 0x80
  new Word("Sui"), // 0x81
  new Word("Qi"), // 0x82
  null, // 0x83
  new Word("Yue"), // 0x84
  new Word("Ban"), // 0x85
  new Word("Yao"), // 0x86
  new Word("Ang"), // 0x87
  new Word("Ya"), // 0x88
  new Word("Wu"), // 0x89
  new Word("Jie"), // 0x8a
  new Word("E"), // 0x8b
  new Word("Ji"), // 0x8c
  new Word("Qian"), // 0x8d
  new Word("Fen"), // 0x8e
  new Word("Yuan"), // 0x8f
  new Word("Qi"), // 0x90
  new Word("Cen"), // 0x91
  new Word("Qian"), // 0x92
  new Word("Qi"), // 0x93
  new Word("Cha"), // 0x94
  new Word("Jie"), // 0x95
  new Word("Qu"), // 0x96
  new Word("Gang"), // 0x97
  new Word("Xian"), // 0x98
  new Word("Ao"), // 0x99
  new Word("Lan"), // 0x9a
  new Word("Dao"), // 0x9b
  new Word("Ba"), // 0x9c
  new Word("Zuo"), // 0x9d
  new Word("Zuo"), // 0x9e
  new Word("Yang"), // 0x9f
  new Word("Ju"), // 0xa0
  new Word("Gang"), // 0xa1
  new Word("Ke"), // 0xa2
  new Word("Gou"), // 0xa3
  new Word("Xue"), // 0xa4
  new Word("Bei"), // 0xa5
  new Word("Li"), // 0xa6
  new Word("Tiao"), // 0xa7
  new Word("Ju"), // 0xa8
  new Word("Yan"), // 0xa9
  new Word("Fu"), // 0xaa
  new Word("Xiu"), // 0xab
  new Word("Jia"), // 0xac
  new Word("Ling"), // 0xad
  new Word("Tuo"), // 0xae
  new Word("Pei"), // 0xaf
  new Word("You"), // 0xb0
  new Word("Dai"), // 0xb1
  new Word("Kuang"), // 0xb2
  new Word("Yue"), // 0xb3
  new Word("Qu"), // 0xb4
  new Word("Hu"), // 0xb5
  new Word("Po"), // 0xb6
  new Word("Min"), // 0xb7
  new Word("An"), // 0xb8
  new Word("Tiao"), // 0xb9
  new Word("Ling"), // 0xba
  new Word("Chi"), // 0xbb
  new Word("Yuri"), // 0xbc
  new Word("Dong"), // 0xbd
  new Word("Cem"), // 0xbe
  new Word("Kui"), // 0xbf
  new Word("Xiu"), // 0xc0
  new Word("Mao"), // 0xc1
  new Word("Tong"), // 0xc2
  new Word("Xue"), // 0xc3
  new Word("Yi"), // 0xc4
  new Word("Kura"), // 0xc5
  new Word("He"), // 0xc6
  new Word("Ke"), // 0xc7
  new Word("Luo"), // 0xc8
  new Word("E"), // 0xc9
  new Word("Fu"), // 0xca
  new Word("Xun"), // 0xcb
  new Word("Die"), // 0xcc
  new Word("Lu"), // 0xcd
  new Word("An"), // 0xce
  new Word("Er"), // 0xcf
  new Word("Gai"), // 0xd0
  new Word("Quan"), // 0xd1
  new Word("Tong"), // 0xd2
  new Word("Yi"), // 0xd3
  new Word("Mu"), // 0xd4
  new Word("Shi"), // 0xd5
  new Word("An"), // 0xd6
  new Word("Wei"), // 0xd7
  new Word("Hu"), // 0xd8
  new Word("Zhi"), // 0xd9
  new Word("Mi"), // 0xda
  new Word("Li"), // 0xdb
  new Word("Ji"), // 0xdc
  new Word("Tong"), // 0xdd
  new Word("Wei"), // 0xde
  new Word("You"), // 0xdf
  new Word("Sang"), // 0xe0
  new Word("Xia"), // 0xe1
  new Word("Li"), // 0xe2
  new Word("Yao"), // 0xe3
  new Word("Jiao"), // 0xe4
  new Word("Zheng"), // 0xe5
  new Word("Luan"), // 0xe6
  new Word("Jiao"), // 0xe7
  new Word("E"), // 0xe8
  new Word("E"), // 0xe9
  new Word("Yu"), // 0xea
  new Word("Ye"), // 0xeb
  new Word("Bu"), // 0xec
  new Word("Qiao"), // 0xed
  new Word("Qun"), // 0xee
  new Word("Feng"), // 0xef
  new Word("Feng"), // 0xf0
  new Word("Nao"), // 0xf1
  new Word("Li"), // 0xf2
  new Word("You"), // 0xf3
  new Word("Xian"), // 0xf4
  new Word("Hong"), // 0xf5
  new Word("Dao"), // 0xf6
  new Word("Shen"), // 0xf7
  new Word("Cheng"), // 0xf8
  new Word("Tu"), // 0xf9
  new Word("Geng"), // 0xfa
  new Word("Jun"), // 0xfb
  new Word("Hao"), // 0xfc
  new Word("Xia"), // 0xfd
  new Word("Yin"), // 0xfe
  new Word("Yu") // 0xff
  };
}