/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+5Dxx (CJK Unified Ideographs).
 */
final class X5d extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Lang"), // 0x00
  new Word("Kan"), // 0x01
  new Word("Lao"), // 0x02
  new Word("Lai"), // 0x03
  new Word("Xian"), // 0x04
  new Word("Que"), // 0x05
  new Word("Kong"), // 0x06
  new Word("Chong"), // 0x07
  new Word("Chong"), // 0x08
  new Word("Ta"), // 0x09
  new Word("Lin"), // 0x0a
  new Word("Hua"), // 0x0b
  new Word("Ju"), // 0x0c
  new Word("Lai"), // 0x0d
  new Word("Qi"), // 0x0e
  new Word("Min"), // 0x0f
  new Word("Kun"), // 0x10
  new Word("Kun"), // 0x11
  new Word("Zu"), // 0x12
  new Word("Gu"), // 0x13
  new Word("Cui"), // 0x14
  new Word("Ya"), // 0x15
  new Word("Ya"), // 0x16
  new Word("Gang"), // 0x17
  new Word("Lun"), // 0x18
  new Word("Lun"), // 0x19
  new Word("Leng"), // 0x1a
  new Word("Jue"), // 0x1b
  new Word("Duo"), // 0x1c
  new Word("Zheng"), // 0x1d
  new Word("Guo"), // 0x1e
  new Word("Yin"), // 0x1f
  new Word("Dong"), // 0x20
  new Word("Han"), // 0x21
  new Word("Zheng"), // 0x22
  new Word("Wei"), // 0x23
  new Word("Yao"), // 0x24
  new Word("Pi"), // 0x25
  new Word("Yan"), // 0x26
  new Word("Song"), // 0x27
  new Word("Jie"), // 0x28
  new Word("Beng"), // 0x29
  new Word("Zu"), // 0x2a
  new Word("Jue"), // 0x2b
  new Word("Dong"), // 0x2c
  new Word("Zhan"), // 0x2d
  new Word("Gu"), // 0x2e
  new Word("Yin"), // 0x2f
  null, // 0x30
  new Word("Ze"), // 0x31
  new Word("Huang"), // 0x32
  new Word("Yu"), // 0x33
  new Word("Wei"), // 0x34
  new Word("Yang"), // 0x35
  new Word("Feng"), // 0x36
  new Word("Qiu"), // 0x37
  new Word("Dun"), // 0x38
  new Word("Ti"), // 0x39
  new Word("Yi"), // 0x3a
  new Word("Zhi"), // 0x3b
  new Word("Shi"), // 0x3c
  new Word("Zai"), // 0x3d
  new Word("Yao"), // 0x3e
  new Word("E"), // 0x3f
  new Word("Zhu"), // 0x40
  new Word("Kan"), // 0x41
  new Word("Lu"), // 0x42
  new Word("Yan"), // 0x43
  new Word("Mei"), // 0x44
  new Word("Gan"), // 0x45
  new Word("Ji"), // 0x46
  new Word("Ji"), // 0x47
  new Word("Huan"), // 0x48
  new Word("Ting"), // 0x49
  new Word("Sheng"), // 0x4a
  new Word("Mei"), // 0x4b
  new Word("Qian"), // 0x4c
  new Word("Wu"), // 0x4d
  new Word("Yu"), // 0x4e
  new Word("Zong"), // 0x4f
  new Word("Lan"), // 0x50
  new Word("Jue"), // 0x51
  new Word("Yan"), // 0x52
  new Word("Yan"), // 0x53
  new Word("Wei"), // 0x54
  new Word("Zong"), // 0x55
  new Word("Cha"), // 0x56
  new Word("Sui"), // 0x57
  new Word("Rong"), // 0x58
  new Word("Yamashina"), // 0x59
  new Word("Qin"), // 0x5a
  new Word("Yu"), // 0x5b
  new Word("Kewashii"), // 0x5c
  new Word("Lou"), // 0x5d
  new Word("Tu"), // 0x5e
  new Word("Dui"), // 0x5f
  new Word("Xi"), // 0x60
  new Word("Weng"), // 0x61
  new Word("Cang"), // 0x62
  new Word("Dang"), // 0x63
  new Word("Hong"), // 0x64
  new Word("Jie"), // 0x65
  new Word("Ai"), // 0x66
  new Word("Liu"), // 0x67
  new Word("Wu"), // 0x68
  new Word("Song"), // 0x69
  new Word("Qiao"), // 0x6a
  new Word("Zi"), // 0x6b
  new Word("Wei"), // 0x6c
  new Word("Beng"), // 0x6d
  new Word("Dian"), // 0x6e
  new Word("Cuo"), // 0x6f
  new Word("Qian"), // 0x70
  new Word("Yong"), // 0x71
  new Word("Nie"), // 0x72
  new Word("Cuo"), // 0x73
  new Word("Ji"), // 0x74
  null, // 0x75
  new Word("Tao"), // 0x76
  new Word("Song"), // 0x77
  new Word("Zong"), // 0x78
  new Word("Jiang"), // 0x79
  new Word("Liao"), // 0x7a
  new Word("Kang"), // 0x7b
  new Word("Chan"), // 0x7c
  new Word("Die"), // 0x7d
  new Word("Cen"), // 0x7e
  new Word("Ding"), // 0x7f
  new Word("Tu"), // 0x80
  new Word("Lou"), // 0x81
  new Word("Zhang"), // 0x82
  new Word("Zhan"), // 0x83
  new Word("Zhan"), // 0x84
  new Word("Ao"), // 0x85
  new Word("Cao"), // 0x86
  new Word("Qu"), // 0x87
  new Word("Qiang"), // 0x88
  new Word("Zui"), // 0x89
  new Word("Zui"), // 0x8a
  new Word("Dao"), // 0x8b
  new Word("Dao"), // 0x8c
  new Word("Xi"), // 0x8d
  new Word("Yu"), // 0x8e
  new Word("Bo"), // 0x8f
  new Word("Long"), // 0x90
  new Word("Xiang"), // 0x91
  new Word("Ceng"), // 0x92
  new Word("Bo"), // 0x93
  new Word("Qin"), // 0x94
  new Word("Jiao"), // 0x95
  new Word("Yan"), // 0x96
  new Word("Lao"), // 0x97
  new Word("Zhan"), // 0x98
  new Word("Lin"), // 0x99
  new Word("Liao"), // 0x9a
  new Word("Liao"), // 0x9b
  new Word("Jin"), // 0x9c
  new Word("Deng"), // 0x9d
  new Word("Duo"), // 0x9e
  new Word("Zun"), // 0x9f
  new Word("Jiao"), // 0xa0
  new Word("Gui"), // 0xa1
  new Word("Yao"), // 0xa2
  new Word("Qiao"), // 0xa3
  new Word("Yao"), // 0xa4
  new Word("Jue"), // 0xa5
  new Word("Zhan"), // 0xa6
  new Word("Yi"), // 0xa7
  new Word("Xue"), // 0xa8
  new Word("Nao"), // 0xa9
  new Word("Ye"), // 0xaa
  new Word("Ye"), // 0xab
  new Word("Yi"), // 0xac
  new Word("E"), // 0xad
  new Word("Xian"), // 0xae
  new Word("Ji"), // 0xaf
  new Word("Xie"), // 0xb0
  new Word("Ke"), // 0xb1
  new Word("Xi"), // 0xb2
  new Word("Di"), // 0xb3
  new Word("Ao"), // 0xb4
  new Word("Zui"), // 0xb5
  null, // 0xb6
  new Word("Ni"), // 0xb7
  new Word("Rong"), // 0xb8
  new Word("Dao"), // 0xb9
  new Word("Ling"), // 0xba
  new Word("Za"), // 0xbb
  new Word("Yu"), // 0xbc
  new Word("Yue"), // 0xbd
  new Word("Yin"), // 0xbe
  null, // 0xbf
  new Word("Jie"), // 0xc0
  new Word("Li"), // 0xc1
  new Word("Sui"), // 0xc2
  new Word("Long"), // 0xc3
  new Word("Long"), // 0xc4
  new Word("Dian"), // 0xc5
  new Word("Ying"), // 0xc6
  new Word("Xi"), // 0xc7
  new Word("Ju"), // 0xc8
  new Word("Chan"), // 0xc9
  new Word("Ying"), // 0xca
  new Word("Kui"), // 0xcb
  new Word("Yan"), // 0xcc
  new Word("Wei"), // 0xcd
  new Word("Nao"), // 0xce
  new Word("Quan"), // 0xcf
  new Word("Chao"), // 0xd0
  new Word("Cuan"), // 0xd1
  new Word("Luan"), // 0xd2
  new Word("Dian"), // 0xd3
  new Word("Dian"), // 0xd4
  null, // 0xd5
  new Word("Yan"), // 0xd6
  new Word("Yan"), // 0xd7
  new Word("Yan"), // 0xd8
  new Word("Nao"), // 0xd9
  new Word("Yan"), // 0xda
  new Word("Chuan"), // 0xdb
  new Word("Gui"), // 0xdc
  new Word("Chuan"), // 0xdd
  new Word("Zhou"), // 0xde
  new Word("Huang"), // 0xdf
  new Word("Jing"), // 0xe0
  new Word("Xun"), // 0xe1
  new Word("Chao"), // 0xe2
  new Word("Chao"), // 0xe3
  new Word("Lie"), // 0xe4
  new Word("Gong"), // 0xe5
  new Word("Zuo"), // 0xe6
  new Word("Qiao"), // 0xe7
  new Word("Ju"), // 0xe8
  new Word("Gong"), // 0xe9
  new Word("Kek"), // 0xea
  new Word("Wu"), // 0xeb
  new Word("Pwu"), // 0xec
  new Word("Pwu"), // 0xed
  new Word("Chai"), // 0xee
  new Word("Qiu"), // 0xef
  new Word("Qiu"), // 0xf0
  new Word("Ji"), // 0xf1
  new Word("Yi"), // 0xf2
  new Word("Si"), // 0xf3
  new Word("Ba"), // 0xf4
  new Word("Zhi"), // 0xf5
  new Word("Zhao"), // 0xf6
  new Word("Xiang"), // 0xf7
  new Word("Yi"), // 0xf8
  new Word("Jin"), // 0xf9
  new Word("Xun"), // 0xfa
  new Word("Juan"), // 0xfb
  new Word("Phas"), // 0xfc
  new Word("Xun"), // 0xfd
  new Word("Jin"), // 0xfe
  new Word("Fu") // 0xff
  };
}