/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+60xx (CJK Unified Ideographs).
 */
final class X60 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Huai"), // 0x00
  new Word("Tai"), // 0x01
  new Word("Song"), // 0x02
  new Word("Wu"), // 0x03
  new Word("Ou"), // 0x04
  new Word("Chang"), // 0x05
  new Word("Chuang"), // 0x06
  new Word("Ju"), // 0x07
  new Word("Yi"), // 0x08
  new Word("Bao"), // 0x09
  new Word("Chao"), // 0x0a
  new Word("Min"), // 0x0b
  new Word("Pei"), // 0x0c
  new Word("Zuo"), // 0x0d
  new Word("Zen"), // 0x0e
  new Word("Yang"), // 0x0f
  new Word("Kou"), // 0x10
  new Word("Ban"), // 0x11
  new Word("Nu"), // 0x12
  new Word("Nao"), // 0x13
  new Word("Zheng"), // 0x14
  new Word("Pa"), // 0x15
  new Word("Bu"), // 0x16
  new Word("Tie"), // 0x17
  new Word("Gu"), // 0x18
  new Word("Hu"), // 0x19
  new Word("Ju"), // 0x1a
  new Word("Da"), // 0x1b
  new Word("Lian"), // 0x1c
  new Word("Si"), // 0x1d
  new Word("Chou"), // 0x1e
  new Word("Di"), // 0x1f
  new Word("Dai"), // 0x20
  new Word("Yi"), // 0x21
  new Word("Tu"), // 0x22
  new Word("You"), // 0x23
  new Word("Fu"), // 0x24
  new Word("Ji"), // 0x25
  new Word("Peng"), // 0x26
  new Word("Xing"), // 0x27
  new Word("Yuan"), // 0x28
  new Word("Ni"), // 0x29
  new Word("Guai"), // 0x2a
  new Word("Fu"), // 0x2b
  new Word("Xi"), // 0x2c
  new Word("Bi"), // 0x2d
  new Word("You"), // 0x2e
  new Word("Qie"), // 0x2f
  new Word("Xuan"), // 0x30
  new Word("Cong"), // 0x31
  new Word("Bing"), // 0x32
  new Word("Huang"), // 0x33
  new Word("Xu"), // 0x34
  new Word("Chu"), // 0x35
  new Word("Pi"), // 0x36
  new Word("Xi"), // 0x37
  new Word("Xi"), // 0x38
  new Word("Tan"), // 0x39
  new Word("Koraeru"), // 0x3a
  new Word("Zong"), // 0x3b
  new Word("Dui"), // 0x3c
  null, // 0x3d
  new Word("Ki"), // 0x3e
  new Word("Yi"), // 0x3f
  new Word("Chi"), // 0x40
  new Word("Ren"), // 0x41
  new Word("Xun"), // 0x42
  new Word("Shi"), // 0x43
  new Word("Xi"), // 0x44
  new Word("Lao"), // 0x45
  new Word("Heng"), // 0x46
  new Word("Kuang"), // 0x47
  new Word("Mu"), // 0x48
  new Word("Zhi"), // 0x49
  new Word("Xie"), // 0x4a
  new Word("Lian"), // 0x4b
  new Word("Tiao"), // 0x4c
  new Word("Huang"), // 0x4d
  new Word("Die"), // 0x4e
  new Word("Hao"), // 0x4f
  new Word("Kong"), // 0x50
  new Word("Gui"), // 0x51
  new Word("Heng"), // 0x52
  new Word("Xi"), // 0x53
  new Word("Xiao"), // 0x54
  new Word("Shu"), // 0x55
  new Word("S"), // 0x56
  new Word("Kua"), // 0x57
  new Word("Qiu"), // 0x58
  new Word("Yang"), // 0x59
  new Word("Hui"), // 0x5a
  new Word("Hui"), // 0x5b
  new Word("Chi"), // 0x5c
  new Word("Jia"), // 0x5d
  new Word("Yi"), // 0x5e
  new Word("Xiong"), // 0x5f
  new Word("Guai"), // 0x60
  new Word("Lin"), // 0x61
  new Word("Hui"), // 0x62
  new Word("Zi"), // 0x63
  new Word("Xu"), // 0x64
  new Word("Chi"), // 0x65
  new Word("Xiang"), // 0x66
  new Word("Nu"), // 0x67
  new Word("Hen"), // 0x68
  new Word("En"), // 0x69
  new Word("Ke"), // 0x6a
  new Word("Tong"), // 0x6b
  new Word("Tian"), // 0x6c
  new Word("Gong"), // 0x6d
  new Word("Quan"), // 0x6e
  new Word("Xi"), // 0x6f
  new Word("Qia"), // 0x70
  new Word("Yue"), // 0x71
  new Word("Peng"), // 0x72
  new Word("Ken"), // 0x73
  new Word("De"), // 0x74
  new Word("Hui"), // 0x75
  new Word("E"), // 0x76
  new Word("Kyuu"), // 0x77
  new Word("Tong"), // 0x78
  new Word("Yan"), // 0x79
  new Word("Kai"), // 0x7a
  new Word("Ce"), // 0x7b
  new Word("Nao"), // 0x7c
  new Word("Yun"), // 0x7d
  new Word("Mang"), // 0x7e
  new Word("Yong"), // 0x7f
  new Word("Yong"), // 0x80
  new Word("Yuan"), // 0x81
  new Word("Pi"), // 0x82
  new Word("Kun"), // 0x83
  new Word("Qiao"), // 0x84
  new Word("Yue"), // 0x85
  new Word("Yu"), // 0x86
  new Word("Yu"), // 0x87
  new Word("Jie"), // 0x88
  new Word("Xi"), // 0x89
  new Word("Zhe"), // 0x8a
  new Word("Lin"), // 0x8b
  new Word("Ti"), // 0x8c
  new Word("Han"), // 0x8d
  new Word("Hao"), // 0x8e
  new Word("Qie"), // 0x8f
  new Word("Ti"), // 0x90
  new Word("Bu"), // 0x91
  new Word("Yi"), // 0x92
  new Word("Qian"), // 0x93
  new Word("Hui"), // 0x94
  new Word("Xi"), // 0x95
  new Word("Bei"), // 0x96
  new Word("Man"), // 0x97
  new Word("Yi"), // 0x98
  new Word("Heng"), // 0x99
  new Word("Song"), // 0x9a
  new Word("Quan"), // 0x9b
  new Word("Cheng"), // 0x9c
  new Word("Hui"), // 0x9d
  new Word("Wu"), // 0x9e
  new Word("Wu"), // 0x9f
  new Word("You"), // 0xa0
  new Word("Li"), // 0xa1
  new Word("Liang"), // 0xa2
  new Word("Huan"), // 0xa3
  new Word("Cong"), // 0xa4
  new Word("Yi"), // 0xa5
  new Word("Yue"), // 0xa6
  new Word("Li"), // 0xa7
  new Word("Nin"), // 0xa8
  new Word("Nao"), // 0xa9
  new Word("E"), // 0xaa
  new Word("Que"), // 0xab
  new Word("Xuan"), // 0xac
  new Word("Qian"), // 0xad
  new Word("Wu"), // 0xae
  new Word("Min"), // 0xaf
  new Word("Cong"), // 0xb0
  new Word("Fei"), // 0xb1
  new Word("Bei"), // 0xb2
  new Word("Duo"), // 0xb3
  new Word("Cui"), // 0xb4
  new Word("Chang"), // 0xb5
  new Word("Men"), // 0xb6
  new Word("Li"), // 0xb7
  new Word("Ji"), // 0xb8
  new Word("Guan"), // 0xb9
  new Word("Guan"), // 0xba
  new Word("Xing"), // 0xbb
  new Word("Dao"), // 0xbc
  new Word("Qi"), // 0xbd
  new Word("Kong"), // 0xbe
  new Word("Tian"), // 0xbf
  new Word("Lun"), // 0xc0
  new Word("Xi"), // 0xc1
  new Word("Kan"), // 0xc2
  new Word("Kun"), // 0xc3
  new Word("Ni"), // 0xc4
  new Word("Qing"), // 0xc5
  new Word("Chou"), // 0xc6
  new Word("Dun"), // 0xc7
  new Word("Guo"), // 0xc8
  new Word("Chan"), // 0xc9
  new Word("Liang"), // 0xca
  new Word("Wan"), // 0xcb
  new Word("Yuan"), // 0xcc
  new Word("Jin"), // 0xcd
  new Word("Ji"), // 0xce
  new Word("Lin"), // 0xcf
  new Word("Yu"), // 0xd0
  new Word("Huo"), // 0xd1
  new Word("He"), // 0xd2
  new Word("Quan"), // 0xd3
  new Word("Tan"), // 0xd4
  new Word("Ti"), // 0xd5
  new Word("Ti"), // 0xd6
  new Word("Nie"), // 0xd7
  new Word("Wang"), // 0xd8
  new Word("Chuo"), // 0xd9
  new Word("Bu"), // 0xda
  new Word("Hun"), // 0xdb
  new Word("Xi"), // 0xdc
  new Word("Tang"), // 0xdd
  new Word("Xin"), // 0xde
  new Word("Wei"), // 0xdf
  new Word("Hui"), // 0xe0
  new Word("E"), // 0xe1
  new Word("Rui"), // 0xe2
  new Word("Zong"), // 0xe3
  new Word("Jian"), // 0xe4
  new Word("Yong"), // 0xe5
  new Word("Dian"), // 0xe6
  new Word("Ju"), // 0xe7
  new Word("Can"), // 0xe8
  new Word("Cheng"), // 0xe9
  new Word("De"), // 0xea
  new Word("Bei"), // 0xeb
  new Word("Qie"), // 0xec
  new Word("Can"), // 0xed
  new Word("Dan"), // 0xee
  new Word("Guan"), // 0xef
  new Word("Duo"), // 0xf0
  new Word("Nao"), // 0xf1
  new Word("Yun"), // 0xf2
  new Word("Xiang"), // 0xf3
  new Word("Zhui"), // 0xf4
  new Word("Die"), // 0xf5
  new Word("Huang"), // 0xf6
  new Word("Chun"), // 0xf7
  new Word("Qiong"), // 0xf8
  new Word("Re"), // 0xf9
  new Word("Xing"), // 0xfa
  new Word("Ce"), // 0xfb
  new Word("Bian"), // 0xfc
  new Word("Hun"), // 0xfd
  new Word("Zong"), // 0xfe
  new Word("Ti") // 0xff
  };
}