/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+62xx (CJK Unified Ideographs).
 */
final class X62 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Lian"), // 0x00
  new Word("Nan"), // 0x01
  new Word("Mi"), // 0x02
  new Word("Tang"), // 0x03
  new Word("Jue"), // 0x04
  new Word("Gang"), // 0x05
  new Word("Gang"), // 0x06
  new Word("Gang"), // 0x07
  new Word("Ge"), // 0x08
  new Word("Yue"), // 0x09
  new Word("Wu"), // 0x0a
  new Word("Jian"), // 0x0b
  new Word("Xu"), // 0x0c
  new Word("Shu"), // 0x0d
  new Word("Rong"), // 0x0e
  new Word("Xi"), // 0x0f
  new Word("Cheng"), // 0x10
  new Word("Wo"), // 0x11
  new Word("Jie"), // 0x12
  new Word("Ge"), // 0x13
  new Word("Jian"), // 0x14
  new Word("Qiang"), // 0x15
  new Word("Huo"), // 0x16
  new Word("Qiang"), // 0x17
  new Word("Zhan"), // 0x18
  new Word("Dong"), // 0x19
  new Word("Qi"), // 0x1a
  new Word("Jia"), // 0x1b
  new Word("Die"), // 0x1c
  new Word("Zei"), // 0x1d
  new Word("Jia"), // 0x1e
  new Word("Ji"), // 0x1f
  new Word("Shi"), // 0x20
  new Word("Kan"), // 0x21
  new Word("Ji"), // 0x22
  new Word("Kui"), // 0x23
  new Word("Gai"), // 0x24
  new Word("Deng"), // 0x25
  new Word("Zhan"), // 0x26
  new Word("Chuang"), // 0x27
  new Word("Ge"), // 0x28
  new Word("Jian"), // 0x29
  new Word("Jie"), // 0x2a
  new Word("Yu"), // 0x2b
  new Word("Jian"), // 0x2c
  new Word("Yan"), // 0x2d
  new Word("Lu"), // 0x2e
  new Word("Xi"), // 0x2f
  new Word("Zhan"), // 0x30
  new Word("Xi"), // 0x31
  new Word("Xi"), // 0x32
  new Word("Chuo"), // 0x33
  new Word("Dai"), // 0x34
  new Word("Qu"), // 0x35
  new Word("Hu"), // 0x36
  new Word("Hu"), // 0x37
  new Word("Hu"), // 0x38
  new Word("E"), // 0x39
  new Word("Shi"), // 0x3a
  new Word("Li"), // 0x3b
  new Word("Mao"), // 0x3c
  new Word("Hu"), // 0x3d
  new Word("Li"), // 0x3e
  new Word("Fang"), // 0x3f
  new Word("Suo"), // 0x40
  new Word("Bian"), // 0x41
  new Word("Dian"), // 0x42
  new Word("Jiong"), // 0x43
  new Word("Shang"), // 0x44
  new Word("Yi"), // 0x45
  new Word("Yi"), // 0x46
  new Word("Shan"), // 0x47
  new Word("Hu"), // 0x48
  new Word("Fei"), // 0x49
  new Word("Yan"), // 0x4a
  new Word("Shou"), // 0x4b
  new Word("T"), // 0x4c
  new Word("Cai"), // 0x4d
  new Word("Zha"), // 0x4e
  new Word("Qiu"), // 0x4f
  new Word("Le"), // 0x50
  new Word("Bu"), // 0x51
  new Word("Ba"), // 0x52
  new Word("Da"), // 0x53
  new Word("Reng"), // 0x54
  new Word("Fu"), // 0x55
  new Word("Hameru"), // 0x56
  new Word("Zai"), // 0x57
  new Word("Tuo"), // 0x58
  new Word("Zhang"), // 0x59
  new Word("Diao"), // 0x5a
  new Word("Kang"), // 0x5b
  new Word("Yu"), // 0x5c
  new Word("Ku"), // 0x5d
  new Word("Han"), // 0x5e
  new Word("Shen"), // 0x5f
  new Word("Cha"), // 0x60
  new Word("Yi"), // 0x61
  new Word("Gu"), // 0x62
  new Word("Kou"), // 0x63
  new Word("Wu"), // 0x64
  new Word("Tuo"), // 0x65
  new Word("Qian"), // 0x66
  new Word("Zhi"), // 0x67
  new Word("Ren"), // 0x68
  new Word("Kuo"), // 0x69
  new Word("Men"), // 0x6a
  new Word("Sao"), // 0x6b
  new Word("Yang"), // 0x6c
  new Word("Niu"), // 0x6d
  new Word("Ban"), // 0x6e
  new Word("Che"), // 0x6f
  new Word("Rao"), // 0x70
  new Word("Xi"), // 0x71
  new Word("Qian"), // 0x72
  new Word("Ban"), // 0x73
  new Word("Jia"), // 0x74
  new Word("Yu"), // 0x75
  new Word("Fu"), // 0x76
  new Word("Ao"), // 0x77
  new Word("Xi"), // 0x78
  new Word("Pi"), // 0x79
  new Word("Zhi"), // 0x7a
  new Word("Zi"), // 0x7b
  new Word("E"), // 0x7c
  new Word("Dun"), // 0x7d
  new Word("Zhao"), // 0x7e
  new Word("Cheng"), // 0x7f
  new Word("Ji"), // 0x80
  new Word("Yan"), // 0x81
  new Word("Kuang"), // 0x82
  new Word("Bian"), // 0x83
  new Word("Chao"), // 0x84
  new Word("Ju"), // 0x85
  new Word("Wen"), // 0x86
  new Word("Hu"), // 0x87
  new Word("Yue"), // 0x88
  new Word("Jue"), // 0x89
  new Word("Ba"), // 0x8a
  new Word("Qin"), // 0x8b
  new Word("Zhen"), // 0x8c
  new Word("Zheng"), // 0x8d
  new Word("Yun"), // 0x8e
  new Word("Wan"), // 0x8f
  new Word("Nu"), // 0x90
  new Word("Yi"), // 0x91
  new Word("Shu"), // 0x92
  new Word("Zhua"), // 0x93
  new Word("Pou"), // 0x94
  new Word("Tou"), // 0x95
  new Word("Dou"), // 0x96
  new Word("Kang"), // 0x97
  new Word("Zhe"), // 0x98
  new Word("Pou"), // 0x99
  new Word("Fu"), // 0x9a
  new Word("Pao"), // 0x9b
  new Word("Ba"), // 0x9c
  new Word("Ao"), // 0x9d
  new Word("Ze"), // 0x9e
  new Word("Tuan"), // 0x9f
  new Word("Kou"), // 0xa0
  new Word("Lun"), // 0xa1
  new Word("Qiang"), // 0xa2
  null, // 0xa3
  new Word("Hu"), // 0xa4
  new Word("Bao"), // 0xa5
  new Word("Bing"), // 0xa6
  new Word("Zhi"), // 0xa7
  new Word("Peng"), // 0xa8
  new Word("Tan"), // 0xa9
  new Word("Pu"), // 0xaa
  new Word("Pi"), // 0xab
  new Word("Tai"), // 0xac
  new Word("Yao"), // 0xad
  new Word("Zhen"), // 0xae
  new Word("Zha"), // 0xaf
  new Word("Yang"), // 0xb0
  new Word("Bao"), // 0xb1
  new Word("He"), // 0xb2
  new Word("Ni"), // 0xb3
  new Word("Yi"), // 0xb4
  new Word("Di"), // 0xb5
  new Word("Chi"), // 0xb6
  new Word("Pi"), // 0xb7
  new Word("Za"), // 0xb8
  new Word("Mo"), // 0xb9
  new Word("Mo"), // 0xba
  new Word("Shen"), // 0xbb
  new Word("Ya"), // 0xbc
  new Word("Chou"), // 0xbd
  new Word("Qu"), // 0xbe
  new Word("Min"), // 0xbf
  new Word("Chu"), // 0xc0
  new Word("Jia"), // 0xc1
  new Word("Fu"), // 0xc2
  new Word("Zhan"), // 0xc3
  new Word("Zhu"), // 0xc4
  new Word("Dan"), // 0xc5
  new Word("Chai"), // 0xc6
  new Word("Mu"), // 0xc7
  new Word("Nian"), // 0xc8
  new Word("La"), // 0xc9
  new Word("Fu"), // 0xca
  new Word("Pao"), // 0xcb
  new Word("Ban"), // 0xcc
  new Word("Pai"), // 0xcd
  new Word("Ling"), // 0xce
  new Word("Na"), // 0xcf
  new Word("Guai"), // 0xd0
  new Word("Qian"), // 0xd1
  new Word("Ju"), // 0xd2
  new Word("Tuo"), // 0xd3
  new Word("Ba"), // 0xd4
  new Word("Tuo"), // 0xd5
  new Word("Tuo"), // 0xd6
  new Word("Ao"), // 0xd7
  new Word("Ju"), // 0xd8
  new Word("Zhuo"), // 0xd9
  new Word("Pan"), // 0xda
  new Word("Zhao"), // 0xdb
  new Word("Bai"), // 0xdc
  new Word("Bai"), // 0xdd
  new Word("Di"), // 0xde
  new Word("Ni"), // 0xdf
  new Word("Ju"), // 0xe0
  new Word("Kuo"), // 0xe1
  new Word("Long"), // 0xe2
  new Word("Jian"), // 0xe3
  null, // 0xe4
  new Word("Yong"), // 0xe5
  new Word("Lan"), // 0xe6
  new Word("Ning"), // 0xe7
  new Word("Bo"), // 0xe8
  new Word("Ze"), // 0xe9
  new Word("Qian"), // 0xea
  new Word("Hen"), // 0xeb
  new Word("Gua"), // 0xec
  new Word("Shi"), // 0xed
  new Word("Jie"), // 0xee
  new Word("Zheng"), // 0xef
  new Word("Nin"), // 0xf0
  new Word("Gong"), // 0xf1
  new Word("Gong"), // 0xf2
  new Word("Quan"), // 0xf3
  new Word("Shuan"), // 0xf4
  new Word("Cun"), // 0xf5
  new Word("Zan"), // 0xf6
  new Word("Kao"), // 0xf7
  new Word("Chi"), // 0xf8
  new Word("Xie"), // 0xf9
  new Word("Ce"), // 0xfa
  new Word("Hui"), // 0xfb
  new Word("Pin"), // 0xfc
  new Word("Zhuai"), // 0xfd
  new Word("Shi"), // 0xfe
  new Word("Na") // 0xff
  };
}