/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+63xx (CJK Unified Ideographs).
 */
final class X63 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Bo"), // 0x00
  new Word("Chi"), // 0x01
  new Word("Gua"), // 0x02
  new Word("Zhi"), // 0x03
  new Word("Kuo"), // 0x04
  new Word("Duo"), // 0x05
  new Word("Duo"), // 0x06
  new Word("Zhi"), // 0x07
  new Word("Qie"), // 0x08
  new Word("An"), // 0x09
  new Word("Nong"), // 0x0a
  new Word("Zhen"), // 0x0b
  new Word("Ge"), // 0x0c
  new Word("Jiao"), // 0x0d
  new Word("Ku"), // 0x0e
  new Word("Dong"), // 0x0f
  new Word("Ru"), // 0x10
  new Word("Tiao"), // 0x11
  new Word("Lie"), // 0x12
  new Word("Zha"), // 0x13
  new Word("Lu"), // 0x14
  new Word("Die"), // 0x15
  new Word("Wa"), // 0x16
  new Word("Jue"), // 0x17
  new Word("Mushiru"), // 0x18
  new Word("Ju"), // 0x19
  new Word("Zhi"), // 0x1a
  new Word("Luan"), // 0x1b
  new Word("Ya"), // 0x1c
  new Word("Zhua"), // 0x1d
  new Word("Ta"), // 0x1e
  new Word("Xie"), // 0x1f
  new Word("Nao"), // 0x20
  new Word("Dang"), // 0x21
  new Word("Jiao"), // 0x22
  new Word("Zheng"), // 0x23
  new Word("Ji"), // 0x24
  new Word("Hui"), // 0x25
  new Word("Xun"), // 0x26
  new Word("Ku"), // 0x27
  new Word("Ai"), // 0x28
  new Word("Tuo"), // 0x29
  new Word("Nuo"), // 0x2a
  new Word("Cuo"), // 0x2b
  new Word("Bo"), // 0x2c
  new Word("Geng"), // 0x2d
  new Word("Ti"), // 0x2e
  new Word("Zhen"), // 0x2f
  new Word("Cheng"), // 0x30
  new Word("Suo"), // 0x31
  new Word("Suo"), // 0x32
  new Word("Keng"), // 0x33
  new Word("Mei"), // 0x34
  new Word("Long"), // 0x35
  new Word("Ju"), // 0x36
  new Word("Peng"), // 0x37
  new Word("Jian"), // 0x38
  new Word("Yi"), // 0x39
  new Word("Ting"), // 0x3a
  new Word("Shan"), // 0x3b
  new Word("Nuo"), // 0x3c
  new Word("Wan"), // 0x3d
  new Word("Xie"), // 0x3e
  new Word("Cha"), // 0x3f
  new Word("Feng"), // 0x40
  new Word("Jiao"), // 0x41
  new Word("Wu"), // 0x42
  new Word("Jun"), // 0x43
  new Word("Jiu"), // 0x44
  new Word("Tong"), // 0x45
  new Word("Kun"), // 0x46
  new Word("Huo"), // 0x47
  new Word("Tu"), // 0x48
  new Word("Zhuo"), // 0x49
  new Word("Pou"), // 0x4a
  new Word("Le"), // 0x4b
  new Word("Ba"), // 0x4c
  new Word("Han"), // 0x4d
  new Word("Shao"), // 0x4e
  new Word("Nie"), // 0x4f
  new Word("Juan"), // 0x50
  new Word("Ze"), // 0x51
  new Word("Song"), // 0x52
  new Word("Ye"), // 0x53
  new Word("Jue"), // 0x54
  new Word("Bu"), // 0x55
  new Word("Huan"), // 0x56
  new Word("Bu"), // 0x57
  new Word("Zun"), // 0x58
  new Word("Yi"), // 0x59
  new Word("Zhai"), // 0x5a
  new Word("Lu"), // 0x5b
  new Word("Sou"), // 0x5c
  new Word("Tuo"), // 0x5d
  new Word("Lao"), // 0x5e
  new Word("Sun"), // 0x5f
  new Word("Bang"), // 0x60
  new Word("Jian"), // 0x61
  new Word("Huan"), // 0x62
  new Word("Dao"), // 0x63
  null, // 0x64
  new Word("Wan"), // 0x65
  new Word("Qin"), // 0x66
  new Word("Peng"), // 0x67
  new Word("She"), // 0x68
  new Word("Lie"), // 0x69
  new Word("Min"), // 0x6a
  new Word("Men"), // 0x6b
  new Word("Fu"), // 0x6c
  new Word("Bai"), // 0x6d
  new Word("Ju"), // 0x6e
  new Word("Dao"), // 0x6f
  new Word("Wo"), // 0x70
  new Word("Ai"), // 0x71
  new Word("Juan"), // 0x72
  new Word("Yue"), // 0x73
  new Word("Zong"), // 0x74
  new Word("Chen"), // 0x75
  new Word("Chui"), // 0x76
  new Word("Jie"), // 0x77
  new Word("Tu"), // 0x78
  new Word("Ben"), // 0x79
  new Word("Na"), // 0x7a
  new Word("Nian"), // 0x7b
  new Word("Nuo"), // 0x7c
  new Word("Zu"), // 0x7d
  new Word("Wo"), // 0x7e
  new Word("Xi"), // 0x7f
  new Word("Xian"), // 0x80
  new Word("Cheng"), // 0x81
  new Word("Dian"), // 0x82
  new Word("Sao"), // 0x83
  new Word("Lun"), // 0x84
  new Word("Qing"), // 0x85
  new Word("Gang"), // 0x86
  new Word("Duo"), // 0x87
  new Word("Shou"), // 0x88
  new Word("Diao"), // 0x89
  new Word("Pou"), // 0x8a
  new Word("Di"), // 0x8b
  new Word("Zhang"), // 0x8c
  new Word("Gun"), // 0x8d
  new Word("Ji"), // 0x8e
  new Word("Tao"), // 0x8f
  new Word("Qia"), // 0x90
  new Word("Qi"), // 0x91
  new Word("Pai"), // 0x92
  new Word("Shu"), // 0x93
  new Word("Qian"), // 0x94
  new Word("Ling"), // 0x95
  new Word("Yi"), // 0x96
  new Word("Ya"), // 0x97
  new Word("Jue"), // 0x98
  new Word("Zheng"), // 0x99
  new Word("Liang"), // 0x9a
  new Word("Gua"), // 0x9b
  new Word("Yi"), // 0x9c
  new Word("Huo"), // 0x9d
  new Word("Shan"), // 0x9e
  new Word("Zheng"), // 0x9f
  new Word("Lue"), // 0xa0
  new Word("Cai"), // 0xa1
  new Word("Tan"), // 0xa2
  new Word("Che"), // 0xa3
  new Word("Bing"), // 0xa4
  new Word("Jie"), // 0xa5
  new Word("Ti"), // 0xa6
  new Word("Kong"), // 0xa7
  new Word("Tui"), // 0xa8
  new Word("Yan"), // 0xa9
  new Word("Cuo"), // 0xaa
  new Word("Zou"), // 0xab
  new Word("Ju"), // 0xac
  new Word("Tian"), // 0xad
  new Word("Qian"), // 0xae
  new Word("Ken"), // 0xaf
  new Word("Bai"), // 0xb0
  new Word("Shou"), // 0xb1
  new Word("Jie"), // 0xb2
  new Word("Lu"), // 0xb3
  new Word("Guo"), // 0xb4
  new Word("Haba"), // 0xb5
  null, // 0xb6
  new Word("Zhi"), // 0xb7
  new Word("Dan"), // 0xb8
  new Word("Mang"), // 0xb9
  new Word("Xian"), // 0xba
  new Word("Sao"), // 0xbb
  new Word("Guan"), // 0xbc
  new Word("Peng"), // 0xbd
  new Word("Yuan"), // 0xbe
  new Word("Nuo"), // 0xbf
  new Word("Jian"), // 0xc0
  new Word("Zhen"), // 0xc1
  new Word("Jiu"), // 0xc2
  new Word("Jian"), // 0xc3
  new Word("Yu"), // 0xc4
  new Word("Yan"), // 0xc5
  new Word("Kui"), // 0xc6
  new Word("Nan"), // 0xc7
  new Word("Hong"), // 0xc8
  new Word("Rou"), // 0xc9
  new Word("Pi"), // 0xca
  new Word("Wei"), // 0xcb
  new Word("Sai"), // 0xcc
  new Word("Zou"), // 0xcd
  new Word("Xuan"), // 0xce
  new Word("Miao"), // 0xcf
  new Word("Ti"), // 0xd0
  new Word("Nie"), // 0xd1
  new Word("Cha"), // 0xd2
  new Word("Shi"), // 0xd3
  new Word("Zong"), // 0xd4
  new Word("Zhen"), // 0xd5
  new Word("Yi"), // 0xd6
  new Word("Shun"), // 0xd7
  new Word("Heng"), // 0xd8
  new Word("Bian"), // 0xd9
  new Word("Yang"), // 0xda
  new Word("Huan"), // 0xdb
  new Word("Yan"), // 0xdc
  new Word("Zuan"), // 0xdd
  new Word("An"), // 0xde
  new Word("Xu"), // 0xdf
  new Word("Ya"), // 0xe0
  new Word("Wo"), // 0xe1
  new Word("Ke"), // 0xe2
  new Word("Chuai"), // 0xe3
  new Word("Ji"), // 0xe4
  new Word("Ti"), // 0xe5
  new Word("La"), // 0xe6
  new Word("La"), // 0xe7
  new Word("Cheng"), // 0xe8
  new Word("Kai"), // 0xe9
  new Word("Jiu"), // 0xea
  new Word("Jiu"), // 0xeb
  new Word("Tu"), // 0xec
  new Word("Jie"), // 0xed
  new Word("Hui"), // 0xee
  new Word("Geng"), // 0xef
  new Word("Chong"), // 0xf0
  new Word("Shuo"), // 0xf1
  new Word("She"), // 0xf2
  new Word("Xie"), // 0xf3
  new Word("Yuan"), // 0xf4
  new Word("Qian"), // 0xf5
  new Word("Ye"), // 0xf6
  new Word("Cha"), // 0xf7
  new Word("Zha"), // 0xf8
  new Word("Bei"), // 0xf9
  new Word("Yao"), // 0xfa
  null, // 0xfb
  null, // 0xfc
  new Word("Lan"), // 0xfd
  new Word("Wen"), // 0xfe
  new Word("Qin") // 0xff
  };
}