/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+65xx (CJK Unified Ideographs).
 */
final class X65 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Pan"), // 0x00
  new Word("Yang"), // 0x01
  new Word("Lei"), // 0x02
  new Word("Sa"), // 0x03
  new Word("Shu"), // 0x04
  new Word("Zan"), // 0x05
  new Word("Nian"), // 0x06
  new Word("Xian"), // 0x07
  new Word("Jun"), // 0x08
  new Word("Huo"), // 0x09
  new Word("Li"), // 0x0a
  new Word("La"), // 0x0b
  new Word("Han"), // 0x0c
  new Word("Ying"), // 0x0d
  new Word("Lu"), // 0x0e
  new Word("Long"), // 0x0f
  new Word("Qian"), // 0x10
  new Word("Qian"), // 0x11
  new Word("Zan"), // 0x12
  new Word("Qian"), // 0x13
  new Word("Lan"), // 0x14
  new Word("San"), // 0x15
  new Word("Ying"), // 0x16
  new Word("Mei"), // 0x17
  new Word("Rang"), // 0x18
  new Word("Chan"), // 0x19
  null, // 0x1a
  new Word("Cuan"), // 0x1b
  new Word("Xi"), // 0x1c
  new Word("She"), // 0x1d
  new Word("Luo"), // 0x1e
  new Word("Jun"), // 0x1f
  new Word("Mi"), // 0x20
  new Word("Li"), // 0x21
  new Word("Zan"), // 0x22
  new Word("Luan"), // 0x23
  new Word("Tan"), // 0x24
  new Word("Zuan"), // 0x25
  new Word("Li"), // 0x26
  new Word("Dian"), // 0x27
  new Word("Wa"), // 0x28
  new Word("Dang"), // 0x29
  new Word("Jiao"), // 0x2a
  new Word("Jue"), // 0x2b
  new Word("Lan"), // 0x2c
  new Word("Li"), // 0x2d
  new Word("Nang"), // 0x2e
  new Word("Zhi"), // 0x2f
  new Word("Gui"), // 0x30
  new Word("Gui"), // 0x31
  new Word("Qi"), // 0x32
  new Word("Xin"), // 0x33
  new Word("Pu"), // 0x34
  new Word("Sui"), // 0x35
  new Word("Shou"), // 0x36
  new Word("Kao"), // 0x37
  new Word("You"), // 0x38
  new Word("Gai"), // 0x39
  new Word("Yi"), // 0x3a
  new Word("Gong"), // 0x3b
  new Word("Gan"), // 0x3c
  new Word("Ban"), // 0x3d
  new Word("Fang"), // 0x3e
  new Word("Zheng"), // 0x3f
  new Word("Bo"), // 0x40
  new Word("Dian"), // 0x41
  new Word("Kou"), // 0x42
  new Word("Min"), // 0x43
  new Word("Wu"), // 0x44
  new Word("Gu"), // 0x45
  new Word("He"), // 0x46
  new Word("Ce"), // 0x47
  new Word("Xiao"), // 0x48
  new Word("Mi"), // 0x49
  new Word("Chu"), // 0x4a
  new Word("Ge"), // 0x4b
  new Word("Di"), // 0x4c
  new Word("Xu"), // 0x4d
  new Word("Jiao"), // 0x4e
  new Word("Min"), // 0x4f
  new Word("Chen"), // 0x50
  new Word("Jiu"), // 0x51
  new Word("Zhen"), // 0x52
  new Word("Duo"), // 0x53
  new Word("Yu"), // 0x54
  new Word("Chi"), // 0x55
  new Word("Ao"), // 0x56
  new Word("Bai"), // 0x57
  new Word("Xu"), // 0x58
  new Word("Jiao"), // 0x59
  new Word("Duo"), // 0x5a
  new Word("Lian"), // 0x5b
  new Word("Nie"), // 0x5c
  new Word("Bi"), // 0x5d
  new Word("Chang"), // 0x5e
  new Word("Dian"), // 0x5f
  new Word("Duo"), // 0x60
  new Word("Yi"), // 0x61
  new Word("Gan"), // 0x62
  new Word("San"), // 0x63
  new Word("Ke"), // 0x64
  new Word("Yan"), // 0x65
  new Word("Dun"), // 0x66
  new Word("Qi"), // 0x67
  new Word("Dou"), // 0x68
  new Word("Xiao"), // 0x69
  new Word("Duo"), // 0x6a
  new Word("Jiao"), // 0x6b
  new Word("Jing"), // 0x6c
  new Word("Yang"), // 0x6d
  new Word("Xia"), // 0x6e
  new Word("Min"), // 0x6f
  new Word("Shu"), // 0x70
  new Word("Ai"), // 0x71
  new Word("Qiao"), // 0x72
  new Word("Ai"), // 0x73
  new Word("Zheng"), // 0x74
  new Word("Di"), // 0x75
  new Word("Zhen"), // 0x76
  new Word("Fu"), // 0x77
  new Word("Shu"), // 0x78
  new Word("Liao"), // 0x79
  new Word("Qu"), // 0x7a
  new Word("Xiong"), // 0x7b
  new Word("Xi"), // 0x7c
  new Word("Jiao"), // 0x7d
  new Word("Sen"), // 0x7e
  new Word("Jiao"), // 0x7f
  new Word("Zhuo"), // 0x80
  new Word("Yi"), // 0x81
  new Word("Lian"), // 0x82
  new Word("Bi"), // 0x83
  new Word("Li"), // 0x84
  new Word("Xiao"), // 0x85
  new Word("Xiao"), // 0x86
  new Word("Wen"), // 0x87
  new Word("Xue"), // 0x88
  new Word("Qi"), // 0x89
  new Word("Qi"), // 0x8a
  new Word("Zhai"), // 0x8b
  new Word("Bin"), // 0x8c
  new Word("Jue"), // 0x8d
  new Word("Zhai"), // 0x8e
  null, // 0x8f
  new Word("Fei"), // 0x90
  new Word("Ban"), // 0x91
  new Word("Ban"), // 0x92
  new Word("Lan"), // 0x93
  new Word("Yu"), // 0x94
  new Word("Lan"), // 0x95
  new Word("Wei"), // 0x96
  new Word("Dou"), // 0x97
  new Word("Sheng"), // 0x98
  new Word("Liao"), // 0x99
  new Word("Jia"), // 0x9a
  new Word("Hu"), // 0x9b
  new Word("Xie"), // 0x9c
  new Word("Jia"), // 0x9d
  new Word("Yu"), // 0x9e
  new Word("Zhen"), // 0x9f
  new Word("Jiao"), // 0xa0
  new Word("Wo"), // 0xa1
  new Word("Tou"), // 0xa2
  new Word("Chu"), // 0xa3
  new Word("Jin"), // 0xa4
  new Word("Chi"), // 0xa5
  new Word("Yin"), // 0xa6
  new Word("Fu"), // 0xa7
  new Word("Qiang"), // 0xa8
  new Word("Zhan"), // 0xa9
  new Word("Qu"), // 0xaa
  new Word("Zhuo"), // 0xab
  new Word("Zhan"), // 0xac
  new Word("Duan"), // 0xad
  new Word("Zhuo"), // 0xae
  new Word("Si"), // 0xaf
  new Word("Xin"), // 0xb0
  new Word("Zhuo"), // 0xb1
  new Word("Zhuo"), // 0xb2
  new Word("Qin"), // 0xb3
  new Word("Lin"), // 0xb4
  new Word("Zhuo"), // 0xb5
  new Word("Chu"), // 0xb6
  new Word("Duan"), // 0xb7
  new Word("Zhu"), // 0xb8
  new Word("Fang"), // 0xb9
  new Word("Xie"), // 0xba
  new Word("Hang"), // 0xbb
  new Word("Yu"), // 0xbc
  new Word("Shi"), // 0xbd
  new Word("Pei"), // 0xbe
  new Word("You"), // 0xbf
  new Word("Mye"), // 0xc0
  new Word("Pang"), // 0xc1
  new Word("Qi"), // 0xc2
  new Word("Zhan"), // 0xc3
  new Word("Mao"), // 0xc4
  new Word("Lu"), // 0xc5
  new Word("Pei"), // 0xc6
  new Word("Pi"), // 0xc7
  new Word("Liu"), // 0xc8
  new Word("Fu"), // 0xc9
  new Word("Fang"), // 0xca
  new Word("Xuan"), // 0xcb
  new Word("Jing"), // 0xcc
  new Word("Jing"), // 0xcd
  new Word("Ni"), // 0xce
  new Word("Zu"), // 0xcf
  new Word("Zhao"), // 0xd0
  new Word("Yi"), // 0xd1
  new Word("Liu"), // 0xd2
  new Word("Shao"), // 0xd3
  new Word("Jian"), // 0xd4
  new Word("Es"), // 0xd5
  new Word("Yi"), // 0xd6
  new Word("Qi"), // 0xd7
  new Word("Zhi"), // 0xd8
  new Word("Fan"), // 0xd9
  new Word("Piao"), // 0xda
  new Word("Fan"), // 0xdb
  new Word("Zhan"), // 0xdc
  new Word("Guai"), // 0xdd
  new Word("Sui"), // 0xde
  new Word("Yu"), // 0xdf
  new Word("Wu"), // 0xe0
  new Word("Ji"), // 0xe1
  new Word("Ji"), // 0xe2
  new Word("Ji"), // 0xe3
  new Word("Huo"), // 0xe4
  new Word("Ri"), // 0xe5
  new Word("Dan"), // 0xe6
  new Word("Jiu"), // 0xe7
  new Word("Zhi"), // 0xe8
  new Word("Zao"), // 0xe9
  new Word("Xie"), // 0xea
  new Word("Tiao"), // 0xeb
  new Word("Xun"), // 0xec
  new Word("Xu"), // 0xed
  new Word("Xu"), // 0xee
  new Word("Xu"), // 0xef
  new Word("Gan"), // 0xf0
  new Word("Han"), // 0xf1
  new Word("Tai"), // 0xf2
  new Word("Di"), // 0xf3
  new Word("Xu"), // 0xf4
  new Word("Chan"), // 0xf5
  new Word("Shi"), // 0xf6
  new Word("Kuang"), // 0xf7
  new Word("Yang"), // 0xf8
  new Word("Shi"), // 0xf9
  new Word("Wang"), // 0xfa
  new Word("Min"), // 0xfb
  new Word("Min"), // 0xfc
  new Word("Tun"), // 0xfd
  new Word("Chun"), // 0xfe
  new Word("Wu") // 0xff
  };
}