/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+66xx (CJK Unified Ideographs).
 */
final class X66 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Yun"), // 0x00
  new Word("Bei"), // 0x01
  new Word("Ang"), // 0x02
  new Word("Ze"), // 0x03
  new Word("Ban"), // 0x04
  new Word("Jie"), // 0x05
  new Word("Kun"), // 0x06
  new Word("Sheng"), // 0x07
  new Word("Hu"), // 0x08
  new Word("Fang"), // 0x09
  new Word("Hao"), // 0x0a
  new Word("Gui"), // 0x0b
  new Word("Chang"), // 0x0c
  new Word("Xuan"), // 0x0d
  new Word("Ming"), // 0x0e
  new Word("Hun"), // 0x0f
  new Word("Fen"), // 0x10
  new Word("Qin"), // 0x11
  new Word("Hu"), // 0x12
  new Word("Yi"), // 0x13
  new Word("Xi"), // 0x14
  new Word("Xin"), // 0x15
  new Word("Yan"), // 0x16
  new Word("Ze"), // 0x17
  new Word("Fang"), // 0x18
  new Word("Tan"), // 0x19
  new Word("Shen"), // 0x1a
  new Word("Ju"), // 0x1b
  new Word("Yang"), // 0x1c
  new Word("Zan"), // 0x1d
  new Word("Bing"), // 0x1e
  new Word("Xing"), // 0x1f
  new Word("Ying"), // 0x20
  new Word("Xuan"), // 0x21
  new Word("Pei"), // 0x22
  new Word("Zhen"), // 0x23
  new Word("Ling"), // 0x24
  new Word("Chun"), // 0x25
  new Word("Hao"), // 0x26
  new Word("Mei"), // 0x27
  new Word("Zuo"), // 0x28
  new Word("Mo"), // 0x29
  new Word("Bian"), // 0x2a
  new Word("Xu"), // 0x2b
  new Word("Hun"), // 0x2c
  new Word("Zhao"), // 0x2d
  new Word("Zong"), // 0x2e
  new Word("Shi"), // 0x2f
  new Word("Shi"), // 0x30
  new Word("Yu"), // 0x31
  new Word("Fei"), // 0x32
  new Word("Die"), // 0x33
  new Word("Mao"), // 0x34
  new Word("Ni"), // 0x35
  new Word("Chang"), // 0x36
  new Word("Wen"), // 0x37
  new Word("Dong"), // 0x38
  new Word("Ai"), // 0x39
  new Word("Bing"), // 0x3a
  new Word("Ang"), // 0x3b
  new Word("Zhou"), // 0x3c
  new Word("Long"), // 0x3d
  new Word("Xian"), // 0x3e
  new Word("Kuang"), // 0x3f
  new Word("Tiao"), // 0x40
  new Word("Chao"), // 0x41
  new Word("Shi"), // 0x42
  new Word("Huang"), // 0x43
  new Word("Huang"), // 0x44
  new Word("Xuan"), // 0x45
  new Word("Kui"), // 0x46
  new Word("Xu"), // 0x47
  new Word("Jiao"), // 0x48
  new Word("Jin"), // 0x49
  new Word("Zhi"), // 0x4a
  new Word("Jin"), // 0x4b
  new Word("Shang"), // 0x4c
  new Word("Tong"), // 0x4d
  new Word("Hong"), // 0x4e
  new Word("Yan"), // 0x4f
  new Word("Gai"), // 0x50
  new Word("Xiang"), // 0x51
  new Word("Shai"), // 0x52
  new Word("Xiao"), // 0x53
  new Word("Ye"), // 0x54
  new Word("Yun"), // 0x55
  new Word("Hui"), // 0x56
  new Word("Han"), // 0x57
  new Word("Han"), // 0x58
  new Word("Jun"), // 0x59
  new Word("Wan"), // 0x5a
  new Word("Xian"), // 0x5b
  new Word("Kun"), // 0x5c
  new Word("Zhou"), // 0x5d
  new Word("Xi"), // 0x5e
  new Word("Cheng"), // 0x5f
  new Word("Sheng"), // 0x60
  new Word("Bu"), // 0x61
  new Word("Zhe"), // 0x62
  new Word("Zhe"), // 0x63
  new Word("Wu"), // 0x64
  new Word("Han"), // 0x65
  new Word("Hui"), // 0x66
  new Word("Hao"), // 0x67
  new Word("Chen"), // 0x68
  new Word("Wan"), // 0x69
  new Word("Tian"), // 0x6a
  new Word("Zhuo"), // 0x6b
  new Word("Zui"), // 0x6c
  new Word("Zhou"), // 0x6d
  new Word("Pu"), // 0x6e
  new Word("Jing"), // 0x6f
  new Word("Xi"), // 0x70
  new Word("Shan"), // 0x71
  new Word("Yi"), // 0x72
  new Word("Xi"), // 0x73
  new Word("Qing"), // 0x74
  new Word("Qi"), // 0x75
  new Word("Jing"), // 0x76
  new Word("Gui"), // 0x77
  new Word("Zhen"), // 0x78
  new Word("Yi"), // 0x79
  new Word("Zhi"), // 0x7a
  new Word("An"), // 0x7b
  new Word("Wan"), // 0x7c
  new Word("Lin"), // 0x7d
  new Word("Liang"), // 0x7e
  new Word("Chang"), // 0x7f
  new Word("Wang"), // 0x80
  new Word("Xiao"), // 0x81
  new Word("Zan"), // 0x82
  new Word("Hi"), // 0x83
  new Word("Xuan"), // 0x84
  new Word("Xuan"), // 0x85
  new Word("Yi"), // 0x86
  new Word("Xia"), // 0x87
  new Word("Yun"), // 0x88
  new Word("Hui"), // 0x89
  new Word("Fu"), // 0x8a
  new Word("Min"), // 0x8b
  new Word("Kui"), // 0x8c
  new Word("He"), // 0x8d
  new Word("Ying"), // 0x8e
  new Word("Du"), // 0x8f
  new Word("Wei"), // 0x90
  new Word("Shu"), // 0x91
  new Word("Qing"), // 0x92
  new Word("Mao"), // 0x93
  new Word("Nan"), // 0x94
  new Word("Jian"), // 0x95
  new Word("Nuan"), // 0x96
  new Word("An"), // 0x97
  new Word("Yang"), // 0x98
  new Word("Chun"), // 0x99
  new Word("Yao"), // 0x9a
  new Word("Suo"), // 0x9b
  new Word("Jin"), // 0x9c
  new Word("Ming"), // 0x9d
  new Word("Jiao"), // 0x9e
  new Word("Kai"), // 0x9f
  new Word("Gao"), // 0xa0
  new Word("Weng"), // 0xa1
  new Word("Chang"), // 0xa2
  new Word("Qi"), // 0xa3
  new Word("Hao"), // 0xa4
  new Word("Yan"), // 0xa5
  new Word("Li"), // 0xa6
  new Word("Ai"), // 0xa7
  new Word("Ji"), // 0xa8
  new Word("Gui"), // 0xa9
  new Word("Men"), // 0xaa
  new Word("Zan"), // 0xab
  new Word("Xie"), // 0xac
  new Word("Hao"), // 0xad
  new Word("Mu"), // 0xae
  new Word("Mo"), // 0xaf
  new Word("Cong"), // 0xb0
  new Word("Ni"), // 0xb1
  new Word("Zhang"), // 0xb2
  new Word("Hui"), // 0xb3
  new Word("Bao"), // 0xb4
  new Word("Han"), // 0xb5
  new Word("Xuan"), // 0xb6
  new Word("Chuan"), // 0xb7
  new Word("Liao"), // 0xb8
  new Word("Xian"), // 0xb9
  new Word("Dan"), // 0xba
  new Word("Jing"), // 0xbb
  new Word("Pie"), // 0xbc
  new Word("Lin"), // 0xbd
  new Word("Tun"), // 0xbe
  new Word("Xi"), // 0xbf
  new Word("Yi"), // 0xc0
  new Word("Ji"), // 0xc1
  new Word("Huang"), // 0xc2
  new Word("Tai"), // 0xc3
  new Word("Ye"), // 0xc4
  new Word("Ye"), // 0xc5
  new Word("Li"), // 0xc6
  new Word("Tan"), // 0xc7
  new Word("Tong"), // 0xc8
  new Word("Xiao"), // 0xc9
  new Word("Fei"), // 0xca
  new Word("Qin"), // 0xcb
  new Word("Zhao"), // 0xcc
  new Word("Hao"), // 0xcd
  new Word("Yi"), // 0xce
  new Word("Xiang"), // 0xcf
  new Word("Xing"), // 0xd0
  new Word("Sen"), // 0xd1
  new Word("Jiao"), // 0xd2
  new Word("Bao"), // 0xd3
  new Word("Jing"), // 0xd4
  new Word("Yian"), // 0xd5
  new Word("Ai"), // 0xd6
  new Word("Ye"), // 0xd7
  new Word("Ru"), // 0xd8
  new Word("Shu"), // 0xd9
  new Word("Meng"), // 0xda
  new Word("Xun"), // 0xdb
  new Word("Yao"), // 0xdc
  new Word("Pu"), // 0xdd
  new Word("Li"), // 0xde
  new Word("Chen"), // 0xdf
  new Word("Kuang"), // 0xe0
  new Word("Die"), // 0xe1
  null, // 0xe2
  new Word("Yan"), // 0xe3
  new Word("Huo"), // 0xe4
  new Word("Lu"), // 0xe5
  new Word("Xi"), // 0xe6
  new Word("Rong"), // 0xe7
  new Word("Long"), // 0xe8
  new Word("Nang"), // 0xe9
  new Word("Luo"), // 0xea
  new Word("Luan"), // 0xeb
  new Word("Shai"), // 0xec
  new Word("Tang"), // 0xed
  new Word("Yan"), // 0xee
  new Word("Chu"), // 0xef
  new Word("Yue"), // 0xf0
  new Word("Yue"), // 0xf1
  new Word("Qu"), // 0xf2
  new Word("Yi"), // 0xf3
  new Word("Geng"), // 0xf4
  new Word("Ye"), // 0xf5
  new Word("Hu"), // 0xf6
  new Word("He"), // 0xf7
  new Word("Shu"), // 0xf8
  new Word("Cao"), // 0xf9
  new Word("Cao"), // 0xfa
  new Word("Noboru"), // 0xfb
  new Word("Man"), // 0xfc
  new Word("Ceng"), // 0xfd
  new Word("Ceng"), // 0xfe
  new Word("Ti") // 0xff
  };
}