/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+67xx (CJK Unified Ideographs).
 */
final class X67 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Zui"), // 0x00
  new Word("Can"), // 0x01
  new Word("Xu"), // 0x02
  new Word("Hui"), // 0x03
  new Word("Yin"), // 0x04
  new Word("Qie"), // 0x05
  new Word("Fen"), // 0x06
  new Word("Pi"), // 0x07
  new Word("Yue"), // 0x08
  new Word("You"), // 0x09
  new Word("Ruan"), // 0x0a
  new Word("Peng"), // 0x0b
  new Word("Ban"), // 0x0c
  new Word("Fu"), // 0x0d
  new Word("Ling"), // 0x0e
  new Word("Fei"), // 0x0f
  new Word("Qu"), // 0x10
  null, // 0x11
  new Word("Nu"), // 0x12
  new Word("Tiao"), // 0x13
  new Word("Shuo"), // 0x14
  new Word("Zhen"), // 0x15
  new Word("Lang"), // 0x16
  new Word("Lang"), // 0x17
  new Word("Juan"), // 0x18
  new Word("Ming"), // 0x19
  new Word("Huang"), // 0x1a
  new Word("Wang"), // 0x1b
  new Word("Tun"), // 0x1c
  new Word("Zhao"), // 0x1d
  new Word("Ji"), // 0x1e
  new Word("Qi"), // 0x1f
  new Word("Ying"), // 0x20
  new Word("Zong"), // 0x21
  new Word("Wang"), // 0x22
  new Word("Tong"), // 0x23
  new Word("Lang"), // 0x24
  null, // 0x25
  new Word("Meng"), // 0x26
  new Word("Long"), // 0x27
  new Word("Mu"), // 0x28
  new Word("Deng"), // 0x29
  new Word("Wei"), // 0x2a
  new Word("Mo"), // 0x2b
  new Word("Ben"), // 0x2c
  new Word("Zha"), // 0x2d
  new Word("Zhu"), // 0x2e
  new Word("Zhu"), // 0x2f
  null, // 0x30
  new Word("Zhu"), // 0x31
  new Word("Ren"), // 0x32
  new Word("Ba"), // 0x33
  new Word("Po"), // 0x34
  new Word("Duo"), // 0x35
  new Word("Duo"), // 0x36
  new Word("Dao"), // 0x37
  new Word("Li"), // 0x38
  new Word("Qiu"), // 0x39
  new Word("Ji"), // 0x3a
  new Word("Jiu"), // 0x3b
  new Word("Bi"), // 0x3c
  new Word("Xiu"), // 0x3d
  new Word("Ting"), // 0x3e
  new Word("Ci"), // 0x3f
  new Word("Sha"), // 0x40
  new Word("Eburi"), // 0x41
  new Word("Za"), // 0x42
  new Word("Quan"), // 0x43
  new Word("Qian"), // 0x44
  new Word("Yu"), // 0x45
  new Word("Gan"), // 0x46
  new Word("Wu"), // 0x47
  new Word("Cha"), // 0x48
  new Word("Shan"), // 0x49
  new Word("Xun"), // 0x4a
  new Word("Fan"), // 0x4b
  new Word("Wu"), // 0x4c
  new Word("Zi"), // 0x4d
  new Word("Li"), // 0x4e
  new Word("Xing"), // 0x4f
  new Word("Cai"), // 0x50
  new Word("Cun"), // 0x51
  new Word("Ren"), // 0x52
  new Word("Shao"), // 0x53
  new Word("Tuo"), // 0x54
  new Word("Di"), // 0x55
  new Word("Zhang"), // 0x56
  new Word("Mang"), // 0x57
  new Word("Chi"), // 0x58
  new Word("Yi"), // 0x59
  new Word("Gu"), // 0x5a
  new Word("Gong"), // 0x5b
  new Word("Du"), // 0x5c
  new Word("Yi"), // 0x5d
  new Word("Qi"), // 0x5e
  new Word("Shu"), // 0x5f
  new Word("Gang"), // 0x60
  new Word("Tiao"), // 0x61
  new Word("Moku"), // 0x62
  new Word("Soma"), // 0x63
  new Word("Tochi"), // 0x64
  new Word("Lai"), // 0x65
  new Word("Sugi"), // 0x66
  new Word("Mang"), // 0x67
  new Word("Yang"), // 0x68
  new Word("Ma"), // 0x69
  new Word("Miao"), // 0x6a
  new Word("Si"), // 0x6b
  new Word("Yuan"), // 0x6c
  new Word("Hang"), // 0x6d
  new Word("Fei"), // 0x6e
  new Word("Bei"), // 0x6f
  new Word("Jie"), // 0x70
  new Word("Dong"), // 0x71
  new Word("Gao"), // 0x72
  new Word("Yao"), // 0x73
  new Word("Xian"), // 0x74
  new Word("Chu"), // 0x75
  new Word("Qun"), // 0x76
  new Word("Pa"), // 0x77
  new Word("Shu"), // 0x78
  new Word("Hua"), // 0x79
  new Word("Xin"), // 0x7a
  new Word("Chou"), // 0x7b
  new Word("Zhu"), // 0x7c
  new Word("Chou"), // 0x7d
  new Word("Song"), // 0x7e
  new Word("Ban"), // 0x7f
  new Word("Song"), // 0x80
  new Word("Ji"), // 0x81
  new Word("Yue"), // 0x82
  new Word("Jin"), // 0x83
  new Word("Gou"), // 0x84
  new Word("Ji"), // 0x85
  new Word("Mao"), // 0x86
  new Word("Pi"), // 0x87
  new Word("Bi"), // 0x88
  new Word("Wang"), // 0x89
  new Word("Ang"), // 0x8a
  new Word("Fang"), // 0x8b
  new Word("Fen"), // 0x8c
  new Word("Yi"), // 0x8d
  new Word("Fu"), // 0x8e
  new Word("Nan"), // 0x8f
  new Word("Xi"), // 0x90
  new Word("Hu"), // 0x91
  new Word("Ya"), // 0x92
  new Word("Dou"), // 0x93
  new Word("Xun"), // 0x94
  new Word("Zhen"), // 0x95
  new Word("Yao"), // 0x96
  new Word("Lin"), // 0x97
  new Word("Rui"), // 0x98
  new Word("E"), // 0x99
  new Word("Mei"), // 0x9a
  new Word("Zhao"), // 0x9b
  new Word("Guo"), // 0x9c
  new Word("Zhi"), // 0x9d
  new Word("Cong"), // 0x9e
  new Word("Yun"), // 0x9f
  new Word("Waku"), // 0xa0
  new Word("Dou"), // 0xa1
  new Word("Shu"), // 0xa2
  new Word("Zao"), // 0xa3
  null, // 0xa4
  new Word("Li"), // 0xa5
  new Word("Haze"), // 0xa6
  new Word("Jian"), // 0xa7
  new Word("Cheng"), // 0xa8
  new Word("Matsu"), // 0xa9
  new Word("Qiang"), // 0xaa
  new Word("Feng"), // 0xab
  new Word("Nan"), // 0xac
  new Word("Xiao"), // 0xad
  new Word("Xian"), // 0xae
  new Word("Ku"), // 0xaf
  new Word("Ping"), // 0xb0
  new Word("Yi"), // 0xb1
  new Word("Xi"), // 0xb2
  new Word("Zhi"), // 0xb3
  new Word("Guai"), // 0xb4
  new Word("Xiao"), // 0xb5
  new Word("Jia"), // 0xb6
  new Word("Jia"), // 0xb7
  new Word("Gou"), // 0xb8
  new Word("Fu"), // 0xb9
  new Word("Mo"), // 0xba
  new Word("Yi"), // 0xbb
  new Word("Ye"), // 0xbc
  new Word("Ye"), // 0xbd
  new Word("Shi"), // 0xbe
  new Word("Nie"), // 0xbf
  new Word("Bi"), // 0xc0
  new Word("Duo"), // 0xc1
  new Word("Yi"), // 0xc2
  new Word("Ling"), // 0xc3
  new Word("Bing"), // 0xc4
  new Word("Ni"), // 0xc5
  new Word("La"), // 0xc6
  new Word("He"), // 0xc7
  new Word("Pan"), // 0xc8
  new Word("Fan"), // 0xc9
  new Word("Zhong"), // 0xca
  new Word("Dai"), // 0xcb
  new Word("Ci"), // 0xcc
  new Word("Yang"), // 0xcd
  new Word("Fu"), // 0xce
  new Word("Bo"), // 0xcf
  new Word("Mou"), // 0xd0
  new Word("Gan"), // 0xd1
  new Word("Qi"), // 0xd2
  new Word("Ran"), // 0xd3
  new Word("Rou"), // 0xd4
  new Word("Mao"), // 0xd5
  new Word("Zhao"), // 0xd6
  new Word("Song"), // 0xd7
  new Word("Zhe"), // 0xd8
  new Word("Xia"), // 0xd9
  new Word("You"), // 0xda
  new Word("Shen"), // 0xdb
  new Word("Ju"), // 0xdc
  new Word("Tuo"), // 0xdd
  new Word("Zuo"), // 0xde
  new Word("Nan"), // 0xdf
  new Word("Ning"), // 0xe0
  new Word("Yong"), // 0xe1
  new Word("Di"), // 0xe2
  new Word("Zhi"), // 0xe3
  new Word("Zha"), // 0xe4
  new Word("Cha"), // 0xe5
  new Word("Dan"), // 0xe6
  new Word("Gu"), // 0xe7
  new Word("Pu"), // 0xe8
  new Word("Jiu"), // 0xe9
  new Word("Ao"), // 0xea
  new Word("Fu"), // 0xeb
  new Word("Jian"), // 0xec
  new Word("Bo"), // 0xed
  new Word("Duo"), // 0xee
  new Word("Ke"), // 0xef
  new Word("Nai"), // 0xf0
  new Word("Zhu"), // 0xf1
  new Word("Bi"), // 0xf2
  new Word("Liu"), // 0xf3
  new Word("Chai"), // 0xf4
  new Word("Zha"), // 0xf5
  new Word("Si"), // 0xf6
  new Word("Zhu"), // 0xf7
  new Word("Pei"), // 0xf8
  new Word("Shi"), // 0xf9
  new Word("Guai"), // 0xfa
  new Word("Cha"), // 0xfb
  new Word("Yao"), // 0xfc
  new Word("Jue"), // 0xfd
  new Word("Jiu"), // 0xfe
  new Word("Shi") // 0xff
  };
}