/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+68xx (CJK Unified Ideographs).
 */
final class X68 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Zhi"), // 0x00
  new Word("Liu"), // 0x01
  new Word("Mei"), // 0x02
  new Word("Hoy"), // 0x03
  new Word("Rong"), // 0x04
  new Word("Zha"), // 0x05
  null, // 0x06
  new Word("Biao"), // 0x07
  new Word("Zhan"), // 0x08
  new Word("Jie"), // 0x09
  new Word("Long"), // 0x0a
  new Word("Dong"), // 0x0b
  new Word("Lu"), // 0x0c
  new Word("Sayng"), // 0x0d
  new Word("Li"), // 0x0e
  new Word("Lan"), // 0x0f
  new Word("Yong"), // 0x10
  new Word("Shu"), // 0x11
  new Word("Xun"), // 0x12
  new Word("Shuan"), // 0x13
  new Word("Qi"), // 0x14
  new Word("Zhen"), // 0x15
  new Word("Qi"), // 0x16
  new Word("Li"), // 0x17
  new Word("Yi"), // 0x18
  new Word("Xiang"), // 0x19
  new Word("Zhen"), // 0x1a
  new Word("Li"), // 0x1b
  new Word("Su"), // 0x1c
  new Word("Gua"), // 0x1d
  new Word("Kan"), // 0x1e
  new Word("Bing"), // 0x1f
  new Word("Ren"), // 0x20
  new Word("Xiao"), // 0x21
  new Word("Bo"), // 0x22
  new Word("Ren"), // 0x23
  new Word("Bing"), // 0x24
  new Word("Zi"), // 0x25
  new Word("Chou"), // 0x26
  new Word("Yi"), // 0x27
  new Word("Jie"), // 0x28
  new Word("Xu"), // 0x29
  new Word("Zhu"), // 0x2a
  new Word("Jian"), // 0x2b
  new Word("Zui"), // 0x2c
  new Word("Er"), // 0x2d
  new Word("Er"), // 0x2e
  new Word("You"), // 0x2f
  new Word("Fa"), // 0x30
  new Word("Gong"), // 0x31
  new Word("Kao"), // 0x32
  new Word("Lao"), // 0x33
  new Word("Zhan"), // 0x34
  new Word("Li"), // 0x35
  new Word("Yin"), // 0x36
  new Word("Yang"), // 0x37
  new Word("He"), // 0x38
  new Word("Gen"), // 0x39
  new Word("Zhi"), // 0x3a
  new Word("Chi"), // 0x3b
  new Word("Ge"), // 0x3c
  new Word("Zai"), // 0x3d
  new Word("Luan"), // 0x3e
  new Word("Fu"), // 0x3f
  new Word("Jie"), // 0x40
  new Word("Hang"), // 0x41
  new Word("Gui"), // 0x42
  new Word("Tao"), // 0x43
  new Word("Guang"), // 0x44
  new Word("Wei"), // 0x45
  new Word("Kuang"), // 0x46
  new Word("Ru"), // 0x47
  new Word("An"), // 0x48
  new Word("An"), // 0x49
  new Word("Juan"), // 0x4a
  new Word("Yi"), // 0x4b
  new Word("Zhuo"), // 0x4c
  new Word("Ku"), // 0x4d
  new Word("Zhi"), // 0x4e
  new Word("Qiong"), // 0x4f
  new Word("Tong"), // 0x50
  new Word("Sang"), // 0x51
  new Word("Sang"), // 0x52
  new Word("Huan"), // 0x53
  new Word("Jie"), // 0x54
  new Word("Jiu"), // 0x55
  new Word("Xue"), // 0x56
  new Word("Duo"), // 0x57
  new Word("Zhui"), // 0x58
  new Word("Yu"), // 0x59
  new Word("Zan"), // 0x5a
  new Word("Kasei"), // 0x5b
  new Word("Ying"), // 0x5c
  new Word("Masu"), // 0x5d
  null, // 0x5e
  new Word("Zhan"), // 0x5f
  new Word("Ya"), // 0x60
  new Word("Nao"), // 0x61
  new Word("Zhen"), // 0x62
  new Word("Dang"), // 0x63
  new Word("Qi"), // 0x64
  new Word("Qiao"), // 0x65
  new Word("Hua"), // 0x66
  new Word("Kuai"), // 0x67
  new Word("Jiang"), // 0x68
  new Word("Zhuang"), // 0x69
  new Word("Xun"), // 0x6a
  new Word("Suo"), // 0x6b
  new Word("Sha"), // 0x6c
  new Word("Zhen"), // 0x6d
  new Word("Bei"), // 0x6e
  new Word("Ting"), // 0x6f
  new Word("Gua"), // 0x70
  new Word("Jing"), // 0x71
  new Word("Bo"), // 0x72
  new Word("Ben"), // 0x73
  new Word("Fu"), // 0x74
  new Word("Rui"), // 0x75
  new Word("Tong"), // 0x76
  new Word("Jue"), // 0x77
  new Word("Xi"), // 0x78
  new Word("Lang"), // 0x79
  new Word("Liu"), // 0x7a
  new Word("Feng"), // 0x7b
  new Word("Qi"), // 0x7c
  new Word("Wen"), // 0x7d
  new Word("Jun"), // 0x7e
  new Word("Gan"), // 0x7f
  new Word("Cu"), // 0x80
  new Word("Liang"), // 0x81
  new Word("Qiu"), // 0x82
  new Word("Ting"), // 0x83
  new Word("You"), // 0x84
  new Word("Mei"), // 0x85
  new Word("Bang"), // 0x86
  new Word("Long"), // 0x87
  new Word("Peng"), // 0x88
  new Word("Zhuang"), // 0x89
  new Word("Di"), // 0x8a
  new Word("Xuan"), // 0x8b
  new Word("Tu"), // 0x8c
  new Word("Zao"), // 0x8d
  new Word("Ao"), // 0x8e
  new Word("Gu"), // 0x8f
  new Word("Bi"), // 0x90
  new Word("Di"), // 0x91
  new Word("Han"), // 0x92
  new Word("Zi"), // 0x93
  new Word("Zhi"), // 0x94
  new Word("Ren"), // 0x95
  new Word("Bei"), // 0x96
  new Word("Geng"), // 0x97
  new Word("Jian"), // 0x98
  new Word("Huan"), // 0x99
  new Word("Wan"), // 0x9a
  new Word("Nuo"), // 0x9b
  new Word("Jia"), // 0x9c
  new Word("Tiao"), // 0x9d
  new Word("Ji"), // 0x9e
  new Word("Xiao"), // 0x9f
  new Word("Lu"), // 0xa0
  new Word("Huan"), // 0xa1
  new Word("Shao"), // 0xa2
  new Word("Cen"), // 0xa3
  new Word("Fen"), // 0xa4
  new Word("Song"), // 0xa5
  new Word("Meng"), // 0xa6
  new Word("Wu"), // 0xa7
  new Word("Li"), // 0xa8
  new Word("Li"), // 0xa9
  new Word("Dou"), // 0xaa
  new Word("Cen"), // 0xab
  new Word("Ying"), // 0xac
  new Word("Suo"), // 0xad
  new Word("Ju"), // 0xae
  new Word("Ti"), // 0xaf
  new Word("Jie"), // 0xb0
  new Word("Kun"), // 0xb1
  new Word("Zhuo"), // 0xb2
  new Word("Shu"), // 0xb3
  new Word("Chan"), // 0xb4
  new Word("Fan"), // 0xb5
  new Word("Wei"), // 0xb6
  new Word("Jing"), // 0xb7
  new Word("Li"), // 0xb8
  new Word("Bing"), // 0xb9
  new Word("Fumoto"), // 0xba
  new Word("Shikimi"), // 0xbb
  new Word("Tao"), // 0xbc
  new Word("Zhi"), // 0xbd
  new Word("Lai"), // 0xbe
  new Word("Lian"), // 0xbf
  new Word("Jian"), // 0xc0
  new Word("Zhuo"), // 0xc1
  new Word("Ling"), // 0xc2
  new Word("Li"), // 0xc3
  new Word("Qi"), // 0xc4
  new Word("Bing"), // 0xc5
  new Word("Zhun"), // 0xc6
  new Word("Cong"), // 0xc7
  new Word("Qian"), // 0xc8
  new Word("Mian"), // 0xc9
  new Word("Qi"), // 0xca
  new Word("Qi"), // 0xcb
  new Word("Cai"), // 0xcc
  new Word("Gun"), // 0xcd
  new Word("Chan"), // 0xce
  new Word("Te"), // 0xcf
  new Word("Fei"), // 0xd0
  new Word("Pai"), // 0xd1
  new Word("Bang"), // 0xd2
  new Word("Pou"), // 0xd3
  new Word("Hun"), // 0xd4
  new Word("Zong"), // 0xd5
  new Word("Cheng"), // 0xd6
  new Word("Zao"), // 0xd7
  new Word("Ji"), // 0xd8
  new Word("Li"), // 0xd9
  new Word("Peng"), // 0xda
  new Word("Yu"), // 0xdb
  new Word("Yu"), // 0xdc
  new Word("Gu"), // 0xdd
  new Word("Hun"), // 0xde
  new Word("Dong"), // 0xdf
  new Word("Tang"), // 0xe0
  new Word("Gang"), // 0xe1
  new Word("Wang"), // 0xe2
  new Word("Di"), // 0xe3
  new Word("Xi"), // 0xe4
  new Word("Fan"), // 0xe5
  new Word("Cheng"), // 0xe6
  new Word("Zhan"), // 0xe7
  new Word("Qi"), // 0xe8
  new Word("Yuan"), // 0xe9
  new Word("Yan"), // 0xea
  new Word("Yu"), // 0xeb
  new Word("Quan"), // 0xec
  new Word("Yi"), // 0xed
  new Word("Sen"), // 0xee
  new Word("Ren"), // 0xef
  new Word("Chui"), // 0xf0
  new Word("Leng"), // 0xf1
  new Word("Qi"), // 0xf2
  new Word("Zhuo"), // 0xf3
  new Word("Fu"), // 0xf4
  new Word("Ke"), // 0xf5
  new Word("Lai"), // 0xf6
  new Word("Zou"), // 0xf7
  new Word("Zou"), // 0xf8
  new Word("Zhuo"), // 0xf9
  new Word("Guan"), // 0xfa
  new Word("Fen"), // 0xfb
  new Word("Fen"), // 0xfc
  new Word("Chen"), // 0xfd
  new Word("Qiong"), // 0xfe
  new Word("Nie") // 0xff
  };
}