/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+69xx (CJK Unified Ideographs).
 */
final class X69 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Wan"), // 0x00
  new Word("Guo"), // 0x01
  new Word("Lu"), // 0x02
  new Word("Hao"), // 0x03
  new Word("Jie"), // 0x04
  new Word("Yi"), // 0x05
  new Word("Chou"), // 0x06
  new Word("Ju"), // 0x07
  new Word("Ju"), // 0x08
  new Word("Cheng"), // 0x09
  new Word("Zuo"), // 0x0a
  new Word("Liang"), // 0x0b
  new Word("Qiang"), // 0x0c
  new Word("Zhi"), // 0x0d
  new Word("Zhui"), // 0x0e
  new Word("Ya"), // 0x0f
  new Word("Ju"), // 0x10
  new Word("Bei"), // 0x11
  new Word("Jiao"), // 0x12
  new Word("Zhuo"), // 0x13
  new Word("Zi"), // 0x14
  new Word("Bin"), // 0x15
  new Word("Peng"), // 0x16
  new Word("Ding"), // 0x17
  new Word("Chu"), // 0x18
  new Word("Chang"), // 0x19
  new Word("Kunugi"), // 0x1a
  new Word("Momiji"), // 0x1b
  new Word("Jian"), // 0x1c
  new Word("Gui"), // 0x1d
  new Word("Xi"), // 0x1e
  new Word("Du"), // 0x1f
  new Word("Qian"), // 0x20
  new Word("Kunugi"), // 0x21
  new Word("Soko"), // 0x22
  new Word("Shide"), // 0x23
  new Word("Luo"), // 0x24
  new Word("Zhi"), // 0x25
  new Word("Ken"), // 0x26
  new Word("Myeng"), // 0x27
  new Word("Tafu"), // 0x28
  null, // 0x29
  new Word("Peng"), // 0x2a
  new Word("Zhan"), // 0x2b
  null, // 0x2c
  new Word("Tuo"), // 0x2d
  new Word("Sen"), // 0x2e
  new Word("Duo"), // 0x2f
  new Word("Ye"), // 0x30
  new Word("Fou"), // 0x31
  new Word("Wei"), // 0x32
  new Word("Wei"), // 0x33
  new Word("Duan"), // 0x34
  new Word("Jia"), // 0x35
  new Word("Zong"), // 0x36
  new Word("Jian"), // 0x37
  new Word("Yi"), // 0x38
  new Word("Shen"), // 0x39
  new Word("Xi"), // 0x3a
  new Word("Yan"), // 0x3b
  new Word("Yan"), // 0x3c
  new Word("Chuan"), // 0x3d
  new Word("Zhan"), // 0x3e
  new Word("Chun"), // 0x3f
  new Word("Yu"), // 0x40
  new Word("He"), // 0x41
  new Word("Zha"), // 0x42
  new Word("Wo"), // 0x43
  new Word("Pian"), // 0x44
  new Word("Bi"), // 0x45
  new Word("Yao"), // 0x46
  new Word("Huo"), // 0x47
  new Word("Xu"), // 0x48
  new Word("Ruo"), // 0x49
  new Word("Yang"), // 0x4a
  new Word("La"), // 0x4b
  new Word("Yan"), // 0x4c
  new Word("Ben"), // 0x4d
  new Word("Hun"), // 0x4e
  new Word("Kui"), // 0x4f
  new Word("Jie"), // 0x50
  new Word("Kui"), // 0x51
  new Word("Si"), // 0x52
  new Word("Feng"), // 0x53
  new Word("Xie"), // 0x54
  new Word("Tuo"), // 0x55
  new Word("Zhi"), // 0x56
  new Word("Jian"), // 0x57
  new Word("Mu"), // 0x58
  new Word("Mao"), // 0x59
  new Word("Chu"), // 0x5a
  new Word("Hu"), // 0x5b
  new Word("Hu"), // 0x5c
  new Word("Lian"), // 0x5d
  new Word("Leng"), // 0x5e
  new Word("Ting"), // 0x5f
  new Word("Nan"), // 0x60
  new Word("Yu"), // 0x61
  new Word("You"), // 0x62
  new Word("Mei"), // 0x63
  new Word("Song"), // 0x64
  new Word("Xuan"), // 0x65
  new Word("Xuan"), // 0x66
  new Word("Ying"), // 0x67
  new Word("Zhen"), // 0x68
  new Word("Pian"), // 0x69
  new Word("Ye"), // 0x6a
  new Word("Ji"), // 0x6b
  new Word("Jie"), // 0x6c
  new Word("Ye"), // 0x6d
  new Word("Chu"), // 0x6e
  new Word("Shun"), // 0x6f
  new Word("Yu"), // 0x70
  new Word("Cou"), // 0x71
  new Word("Wei"), // 0x72
  new Word("Mei"), // 0x73
  new Word("Di"), // 0x74
  new Word("Ji"), // 0x75
  new Word("Jie"), // 0x76
  new Word("Kai"), // 0x77
  new Word("Qiu"), // 0x78
  new Word("Ying"), // 0x79
  new Word("Rou"), // 0x7a
  new Word("Heng"), // 0x7b
  new Word("Lou"), // 0x7c
  new Word("Le"), // 0x7d
  new Word("Hazou"), // 0x7e
  new Word("Katsura"), // 0x7f
  new Word("Pin"), // 0x80
  new Word("Muro"), // 0x81
  new Word("Gai"), // 0x82
  new Word("Tan"), // 0x83
  new Word("Lan"), // 0x84
  new Word("Yun"), // 0x85
  new Word("Yu"), // 0x86
  new Word("Chen"), // 0x87
  new Word("Lu"), // 0x88
  new Word("Ju"), // 0x89
  new Word("Sakaki"), // 0x8a
  null, // 0x8b
  new Word("Pi"), // 0x8c
  new Word("Xie"), // 0x8d
  new Word("Jia"), // 0x8e
  new Word("Yi"), // 0x8f
  new Word("Zhan"), // 0x90
  new Word("Fu"), // 0x91
  new Word("Nai"), // 0x92
  new Word("Mi"), // 0x93
  new Word("Lang"), // 0x94
  new Word("Rong"), // 0x95
  new Word("Gu"), // 0x96
  new Word("Jian"), // 0x97
  new Word("Ju"), // 0x98
  new Word("Ta"), // 0x99
  new Word("Yao"), // 0x9a
  new Word("Zhen"), // 0x9b
  new Word("Bang"), // 0x9c
  new Word("Sha"), // 0x9d
  new Word("Yuan"), // 0x9e
  new Word("Zi"), // 0x9f
  new Word("Ming"), // 0xa0
  new Word("Su"), // 0xa1
  new Word("Jia"), // 0xa2
  new Word("Yao"), // 0xa3
  new Word("Jie"), // 0xa4
  new Word("Huang"), // 0xa5
  new Word("Gan"), // 0xa6
  new Word("Fei"), // 0xa7
  new Word("Zha"), // 0xa8
  new Word("Qian"), // 0xa9
  new Word("Ma"), // 0xaa
  new Word("Sun"), // 0xab
  new Word("Yuan"), // 0xac
  new Word("Xie"), // 0xad
  new Word("Rong"), // 0xae
  new Word("Shi"), // 0xaf
  new Word("Zhi"), // 0xb0
  new Word("Cui"), // 0xb1
  new Word("Yun"), // 0xb2
  new Word("Ting"), // 0xb3
  new Word("Liu"), // 0xb4
  new Word("Rong"), // 0xb5
  new Word("Tang"), // 0xb6
  new Word("Que"), // 0xb7
  new Word("Zhai"), // 0xb8
  new Word("Si"), // 0xb9
  new Word("Sheng"), // 0xba
  new Word("Ta"), // 0xbb
  new Word("Ke"), // 0xbc
  new Word("Xi"), // 0xbd
  new Word("Gu"), // 0xbe
  new Word("Qi"), // 0xbf
  new Word("Kao"), // 0xc0
  new Word("Gao"), // 0xc1
  new Word("Sun"), // 0xc2
  new Word("Pan"), // 0xc3
  new Word("Tao"), // 0xc4
  new Word("Ge"), // 0xc5
  new Word("Xun"), // 0xc6
  new Word("Dian"), // 0xc7
  new Word("Nou"), // 0xc8
  new Word("Ji"), // 0xc9
  new Word("Shuo"), // 0xca
  new Word("Gou"), // 0xcb
  new Word("Chui"), // 0xcc
  new Word("Qiang"), // 0xcd
  new Word("Cha"), // 0xce
  new Word("Qian"), // 0xcf
  new Word("Huai"), // 0xd0
  new Word("Mei"), // 0xd1
  new Word("Xu"), // 0xd2
  new Word("Gang"), // 0xd3
  new Word("Gao"), // 0xd4
  new Word("Zhuo"), // 0xd5
  new Word("Tuo"), // 0xd6
  new Word("Hashi"), // 0xd7
  new Word("Yang"), // 0xd8
  new Word("Dian"), // 0xd9
  new Word("Jia"), // 0xda
  new Word("Jian"), // 0xdb
  new Word("Zui"), // 0xdc
  new Word("Kashi"), // 0xdd
  new Word("Ori"), // 0xde
  new Word("Bin"), // 0xdf
  new Word("Zhu"), // 0xe0
  null, // 0xe1
  new Word("Xi"), // 0xe2
  new Word("Qi"), // 0xe3
  new Word("Lian"), // 0xe4
  new Word("Hui"), // 0xe5
  new Word("Yong"), // 0xe6
  new Word("Qian"), // 0xe7
  new Word("Guo"), // 0xe8
  new Word("Gai"), // 0xe9
  new Word("Gai"), // 0xea
  new Word("Tuan"), // 0xeb
  new Word("Hua"), // 0xec
  new Word("Cu"), // 0xed
  new Word("Sen"), // 0xee
  new Word("Cui"), // 0xef
  new Word("Beng"), // 0xf0
  new Word("You"), // 0xf1
  new Word("Hu"), // 0xf2
  new Word("Jiang"), // 0xf3
  new Word("Hu"), // 0xf4
  new Word("Huan"), // 0xf5
  new Word("Kui"), // 0xf6
  new Word("Yi"), // 0xf7
  new Word("Nie"), // 0xf8
  new Word("Gao"), // 0xf9
  new Word("Kang"), // 0xfa
  new Word("Gui"), // 0xfb
  new Word("Gui"), // 0xfc
  new Word("Cao"), // 0xfd
  new Word("Man"), // 0xfe
  new Word("Jin") // 0xff
  };
}