/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+6Axx (CJK Unified Ideographs).
 */
final class X6a extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Di"), // 0x00
  new Word("Zhuang"), // 0x01
  new Word("Le"), // 0x02
  new Word("Lang"), // 0x03
  new Word("Chen"), // 0x04
  new Word("Cong"), // 0x05
  new Word("Li"), // 0x06
  new Word("Xiu"), // 0x07
  new Word("Qing"), // 0x08
  new Word("Shuang"), // 0x09
  new Word("Fan"), // 0x0a
  new Word("Tong"), // 0x0b
  new Word("Guan"), // 0x0c
  new Word("Ji"), // 0x0d
  new Word("Suo"), // 0x0e
  new Word("Lei"), // 0x0f
  new Word("Lu"), // 0x10
  new Word("Liang"), // 0x11
  new Word("Mi"), // 0x12
  new Word("Lou"), // 0x13
  new Word("Chao"), // 0x14
  new Word("Su"), // 0x15
  new Word("Ke"), // 0x16
  new Word("Shu"), // 0x17
  new Word("Tang"), // 0x18
  new Word("Biao"), // 0x19
  new Word("Lu"), // 0x1a
  new Word("Jiu"), // 0x1b
  new Word("Shu"), // 0x1c
  new Word("Zha"), // 0x1d
  new Word("Shu"), // 0x1e
  new Word("Zhang"), // 0x1f
  new Word("Men"), // 0x20
  new Word("Mo"), // 0x21
  new Word("Niao"), // 0x22
  new Word("Yang"), // 0x23
  new Word("Tiao"), // 0x24
  new Word("Peng"), // 0x25
  new Word("Zhu"), // 0x26
  new Word("Sha"), // 0x27
  new Word("Xi"), // 0x28
  new Word("Quan"), // 0x29
  new Word("Heng"), // 0x2a
  new Word("Jian"), // 0x2b
  new Word("Cong"), // 0x2c
  null, // 0x2d
  new Word("Hokuso"), // 0x2e
  new Word("Qiang"), // 0x2f
  new Word("Tara"), // 0x30
  new Word("Ying"), // 0x31
  new Word("Er"), // 0x32
  new Word("Xin"), // 0x33
  new Word("Zhi"), // 0x34
  new Word("Qiao"), // 0x35
  new Word("Zui"), // 0x36
  new Word("Cong"), // 0x37
  new Word("Pu"), // 0x38
  new Word("Shu"), // 0x39
  new Word("Hua"), // 0x3a
  new Word("Kui"), // 0x3b
  new Word("Zhen"), // 0x3c
  new Word("Zun"), // 0x3d
  new Word("Yue"), // 0x3e
  new Word("Zhan"), // 0x3f
  new Word("Xi"), // 0x40
  new Word("Xun"), // 0x41
  new Word("Dian"), // 0x42
  new Word("Fa"), // 0x43
  new Word("Gan"), // 0x44
  new Word("Mo"), // 0x45
  new Word("Wu"), // 0x46
  new Word("Qiao"), // 0x47
  new Word("Nao"), // 0x48
  new Word("Lin"), // 0x49
  new Word("Liu"), // 0x4a
  new Word("Qiao"), // 0x4b
  new Word("Xian"), // 0x4c
  new Word("Run"), // 0x4d
  new Word("Fan"), // 0x4e
  new Word("Zhan"), // 0x4f
  new Word("Tuo"), // 0x50
  new Word("Lao"), // 0x51
  new Word("Yun"), // 0x52
  new Word("Shun"), // 0x53
  new Word("Tui"), // 0x54
  new Word("Cheng"), // 0x55
  new Word("Tang"), // 0x56
  new Word("Meng"), // 0x57
  new Word("Ju"), // 0x58
  new Word("Cheng"), // 0x59
  new Word("Su"), // 0x5a
  new Word("Jue"), // 0x5b
  new Word("Jue"), // 0x5c
  new Word("Tan"), // 0x5d
  new Word("Hui"), // 0x5e
  new Word("Ji"), // 0x5f
  new Word("Nuo"), // 0x60
  new Word("Xiang"), // 0x61
  new Word("Tuo"), // 0x62
  new Word("Ning"), // 0x63
  new Word("Rui"), // 0x64
  new Word("Zhu"), // 0x65
  new Word("Chuang"), // 0x66
  new Word("Zeng"), // 0x67
  new Word("Fen"), // 0x68
  new Word("Qiong"), // 0x69
  new Word("Ran"), // 0x6a
  new Word("Heng"), // 0x6b
  new Word("Cen"), // 0x6c
  new Word("Gu"), // 0x6d
  new Word("Liu"), // 0x6e
  new Word("Lao"), // 0x6f
  new Word("Gao"), // 0x70
  new Word("Chu"), // 0x71
  new Word("Zusa"), // 0x72
  new Word("Nude"), // 0x73
  new Word("Ca"), // 0x74
  new Word("San"), // 0x75
  new Word("Ji"), // 0x76
  new Word("Dou"), // 0x77
  new Word("Shou"), // 0x78
  new Word("Lu"), // 0x79
  null, // 0x7a
  null, // 0x7b
  new Word("Yuan"), // 0x7c
  new Word("Ta"), // 0x7d
  new Word("Shu"), // 0x7e
  new Word("Jiang"), // 0x7f
  new Word("Tan"), // 0x80
  new Word("Lin"), // 0x81
  new Word("Nong"), // 0x82
  new Word("Yin"), // 0x83
  new Word("Xi"), // 0x84
  new Word("Sui"), // 0x85
  new Word("Shan"), // 0x86
  new Word("Zui"), // 0x87
  new Word("Xuan"), // 0x88
  new Word("Cheng"), // 0x89
  new Word("Gan"), // 0x8a
  new Word("Ju"), // 0x8b
  new Word("Zui"), // 0x8c
  new Word("Yi"), // 0x8d
  new Word("Qin"), // 0x8e
  new Word("Pu"), // 0x8f
  new Word("Yan"), // 0x90
  new Word("Lei"), // 0x91
  new Word("Feng"), // 0x92
  new Word("Hui"), // 0x93
  new Word("Dang"), // 0x94
  new Word("Ji"), // 0x95
  new Word("Sui"), // 0x96
  new Word("Bo"), // 0x97
  new Word("Bi"), // 0x98
  new Word("Ding"), // 0x99
  new Word("Chu"), // 0x9a
  new Word("Zhua"), // 0x9b
  new Word("Kuai"), // 0x9c
  new Word("Ji"), // 0x9d
  new Word("Jie"), // 0x9e
  new Word("Jia"), // 0x9f
  new Word("Qing"), // 0xa0
  new Word("Zhe"), // 0xa1
  new Word("Jian"), // 0xa2
  new Word("Qiang"), // 0xa3
  new Word("Dao"), // 0xa4
  new Word("Yi"), // 0xa5
  new Word("Biao"), // 0xa6
  new Word("Song"), // 0xa7
  new Word("She"), // 0xa8
  new Word("Lin"), // 0xa9
  new Word("Kunugi"), // 0xaa
  new Word("Cha"), // 0xab
  new Word("Meng"), // 0xac
  new Word("Yin"), // 0xad
  new Word("Tao"), // 0xae
  new Word("Tai"), // 0xaf
  new Word("Mian"), // 0xb0
  new Word("Qi"), // 0xb1
  new Word("Toan"), // 0xb2
  new Word("Bin"), // 0xb3
  new Word("Huo"), // 0xb4
  new Word("Ji"), // 0xb5
  new Word("Qian"), // 0xb6
  new Word("Mi"), // 0xb7
  new Word("Ning"), // 0xb8
  new Word("Yi"), // 0xb9
  new Word("Gao"), // 0xba
  new Word("Jian"), // 0xbb
  new Word("Yin"), // 0xbc
  new Word("Er"), // 0xbd
  new Word("Qing"), // 0xbe
  new Word("Yan"), // 0xbf
  new Word("Qi"), // 0xc0
  new Word("Mi"), // 0xc1
  new Word("Zhao"), // 0xc2
  new Word("Gui"), // 0xc3
  new Word("Chun"), // 0xc4
  new Word("Ji"), // 0xc5
  new Word("Kui"), // 0xc6
  new Word("Po"), // 0xc7
  new Word("Deng"), // 0xc8
  new Word("Chu"), // 0xc9
  null, // 0xca
  new Word("Mian"), // 0xcb
  new Word("You"), // 0xcc
  new Word("Zhi"), // 0xcd
  new Word("Guang"), // 0xce
  new Word("Qian"), // 0xcf
  new Word("Lei"), // 0xd0
  new Word("Lei"), // 0xd1
  new Word("Sa"), // 0xd2
  new Word("Lu"), // 0xd3
  new Word("Li"), // 0xd4
  new Word("Cuan"), // 0xd5
  new Word("Lu"), // 0xd6
  new Word("Mie"), // 0xd7
  new Word("Hui"), // 0xd8
  new Word("Ou"), // 0xd9
  new Word("Lu"), // 0xda
  new Word("Jie"), // 0xdb
  new Word("Gao"), // 0xdc
  new Word("Du"), // 0xdd
  new Word("Yuan"), // 0xde
  new Word("Li"), // 0xdf
  new Word("Fei"), // 0xe0
  new Word("Zhuo"), // 0xe1
  new Word("Sou"), // 0xe2
  new Word("Lian"), // 0xe3
  new Word("Tamo"), // 0xe4
  new Word("Chu"), // 0xe5
  null, // 0xe6
  new Word("Zhu"), // 0xe7
  new Word("Lu"), // 0xe8
  new Word("Yan"), // 0xe9
  new Word("Li"), // 0xea
  new Word("Zhu"), // 0xeb
  new Word("Chen"), // 0xec
  new Word("Jie"), // 0xed
  new Word("E"), // 0xee
  new Word("Su"), // 0xef
  new Word("Huai"), // 0xf0
  new Word("Nie"), // 0xf1
  new Word("Yu"), // 0xf2
  new Word("Long"), // 0xf3
  new Word("Lai"), // 0xf4
  null, // 0xf5
  new Word("Xian"), // 0xf6
  new Word("Kwi"), // 0xf7
  new Word("Ju"), // 0xf8
  new Word("Xiao"), // 0xf9
  new Word("Ling"), // 0xfa
  new Word("Ying"), // 0xfb
  new Word("Jian"), // 0xfc
  new Word("Yin"), // 0xfd
  new Word("You"), // 0xfe
  new Word("Ying") // 0xff
  };
}