/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+6Cxx (CJK Unified Ideographs).
 */
final class X6c extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Lu"), // 0x00
  new Word("Mu"), // 0x01
  new Word("Li"), // 0x02
  new Word("Tong"), // 0x03
  new Word("Rong"), // 0x04
  new Word("Chang"), // 0x05
  new Word("Pu"), // 0x06
  new Word("Luo"), // 0x07
  new Word("Zhan"), // 0x08
  new Word("Sao"), // 0x09
  new Word("Zhan"), // 0x0a
  new Word("Meng"), // 0x0b
  new Word("Luo"), // 0x0c
  new Word("Qu"), // 0x0d
  new Word("Die"), // 0x0e
  new Word("Shi"), // 0x0f
  new Word("Di"), // 0x10
  new Word("Min"), // 0x11
  new Word("Jue"), // 0x12
  new Word("Mang"), // 0x13
  new Word("Qi"), // 0x14
  new Word("Pie"), // 0x15
  new Word("Nai"), // 0x16
  new Word("Qi"), // 0x17
  new Word("Dao"), // 0x18
  new Word("Xian"), // 0x19
  new Word("Chuan"), // 0x1a
  new Word("Fen"), // 0x1b
  new Word("Ri"), // 0x1c
  new Word("Nei"), // 0x1d
  null, // 0x1e
  new Word("Fu"), // 0x1f
  new Word("Shen"), // 0x20
  new Word("Dong"), // 0x21
  new Word("Qing"), // 0x22
  new Word("Qi"), // 0x23
  new Word("Yin"), // 0x24
  new Word("Xi"), // 0x25
  new Word("Hai"), // 0x26
  new Word("Yang"), // 0x27
  new Word("An"), // 0x28
  new Word("Ya"), // 0x29
  new Word("Ke"), // 0x2a
  new Word("Qing"), // 0x2b
  new Word("Ya"), // 0x2c
  new Word("Dong"), // 0x2d
  new Word("Dan"), // 0x2e
  new Word("Lu"), // 0x2f
  new Word("Qing"), // 0x30
  new Word("Yang"), // 0x31
  new Word("Yun"), // 0x32
  new Word("Yun"), // 0x33
  new Word("Shui"), // 0x34
  new Word("San"), // 0x35
  new Word("Zheng"), // 0x36
  new Word("Bing"), // 0x37
  new Word("Yong"), // 0x38
  new Word("Dang"), // 0x39
  new Word("Shitamizu"), // 0x3a
  new Word("Le"), // 0x3b
  new Word("Ni"), // 0x3c
  new Word("Tun"), // 0x3d
  new Word("Fan"), // 0x3e
  new Word("Gui"), // 0x3f
  new Word("Ting"), // 0x40
  new Word("Zhi"), // 0x41
  new Word("Qiu"), // 0x42
  new Word("Bin"), // 0x43
  new Word("Ze"), // 0x44
  new Word("Mian"), // 0x45
  new Word("Cuan"), // 0x46
  new Word("Hui"), // 0x47
  new Word("Diao"), // 0x48
  new Word("Yi"), // 0x49
  new Word("Cha"), // 0x4a
  new Word("Zhuo"), // 0x4b
  new Word("Chuan"), // 0x4c
  new Word("Wan"), // 0x4d
  new Word("Fan"), // 0x4e
  new Word("Dai"), // 0x4f
  new Word("Xi"), // 0x50
  new Word("Tuo"), // 0x51
  new Word("Mang"), // 0x52
  new Word("Qiu"), // 0x53
  new Word("Qi"), // 0x54
  new Word("Shan"), // 0x55
  new Word("Pai"), // 0x56
  new Word("Han"), // 0x57
  new Word("Qian"), // 0x58
  new Word("Wu"), // 0x59
  new Word("Wu"), // 0x5a
  new Word("Xun"), // 0x5b
  new Word("Si"), // 0x5c
  new Word("Ru"), // 0x5d
  new Word("Gong"), // 0x5e
  new Word("Jiang"), // 0x5f
  new Word("Chi"), // 0x60
  new Word("Wu"), // 0x61
  new Word("Tsuchi"), // 0x62
  null, // 0x63
  new Word("Tang"), // 0x64
  new Word("Zhi"), // 0x65
  new Word("Chi"), // 0x66
  new Word("Qian"), // 0x67
  new Word("Mi"), // 0x68
  new Word("Yu"), // 0x69
  new Word("Wang"), // 0x6a
  new Word("Qing"), // 0x6b
  new Word("Jing"), // 0x6c
  new Word("Rui"), // 0x6d
  new Word("Jun"), // 0x6e
  new Word("Hong"), // 0x6f
  new Word("Tai"), // 0x70
  new Word("Quan"), // 0x71
  new Word("Ji"), // 0x72
  new Word("Bian"), // 0x73
  new Word("Bian"), // 0x74
  new Word("Gan"), // 0x75
  new Word("Wen"), // 0x76
  new Word("Zhong"), // 0x77
  new Word("Fang"), // 0x78
  new Word("Xiong"), // 0x79
  new Word("Jue"), // 0x7a
  new Word("Hang"), // 0x7b
  new Word("Niou"), // 0x7c
  new Word("Qi"), // 0x7d
  new Word("Fen"), // 0x7e
  new Word("Xu"), // 0x7f
  new Word("Xu"), // 0x80
  new Word("Qin"), // 0x81
  new Word("Yi"), // 0x82
  new Word("Wo"), // 0x83
  new Word("Yun"), // 0x84
  new Word("Yuan"), // 0x85
  new Word("Hang"), // 0x86
  new Word("Yan"), // 0x87
  new Word("Chen"), // 0x88
  new Word("Chen"), // 0x89
  new Word("Dan"), // 0x8a
  new Word("You"), // 0x8b
  new Word("Dun"), // 0x8c
  new Word("Hu"), // 0x8d
  new Word("Huo"), // 0x8e
  new Word("Qie"), // 0x8f
  new Word("Mu"), // 0x90
  new Word("Rou"), // 0x91
  new Word("Mei"), // 0x92
  new Word("Ta"), // 0x93
  new Word("Mian"), // 0x94
  new Word("Wu"), // 0x95
  new Word("Chong"), // 0x96
  new Word("Tian"), // 0x97
  new Word("Bi"), // 0x98
  new Word("Sha"), // 0x99
  new Word("Zhi"), // 0x9a
  new Word("Pei"), // 0x9b
  new Word("Pan"), // 0x9c
  new Word("Zhui"), // 0x9d
  new Word("Za"), // 0x9e
  new Word("Gou"), // 0x9f
  new Word("Liu"), // 0xa0
  new Word("Mei"), // 0xa1
  new Word("Ze"), // 0xa2
  new Word("Feng"), // 0xa3
  new Word("Ou"), // 0xa4
  new Word("Li"), // 0xa5
  new Word("Lun"), // 0xa6
  new Word("Cang"), // 0xa7
  new Word("Feng"), // 0xa8
  new Word("Wei"), // 0xa9
  new Word("Hu"), // 0xaa
  new Word("Mo"), // 0xab
  new Word("Mei"), // 0xac
  new Word("Shu"), // 0xad
  new Word("Ju"), // 0xae
  new Word("Zan"), // 0xaf
  new Word("Tuo"), // 0xb0
  new Word("Tuo"), // 0xb1
  new Word("Tuo"), // 0xb2
  new Word("He"), // 0xb3
  new Word("Li"), // 0xb4
  new Word("Mi"), // 0xb5
  new Word("Yi"), // 0xb6
  new Word("Fa"), // 0xb7
  new Word("Fei"), // 0xb8
  new Word("You"), // 0xb9
  new Word("Tian"), // 0xba
  new Word("Zhi"), // 0xbb
  new Word("Zhao"), // 0xbc
  new Word("Gu"), // 0xbd
  new Word("Zhan"), // 0xbe
  new Word("Yan"), // 0xbf
  new Word("Si"), // 0xc0
  new Word("Kuang"), // 0xc1
  new Word("Jiong"), // 0xc2
  new Word("Ju"), // 0xc3
  new Word("Xie"), // 0xc4
  new Word("Qiu"), // 0xc5
  new Word("Yi"), // 0xc6
  new Word("Jia"), // 0xc7
  new Word("Zhong"), // 0xc8
  new Word("Quan"), // 0xc9
  new Word("Bo"), // 0xca
  new Word("Hui"), // 0xcb
  new Word("Mi"), // 0xcc
  new Word("Ben"), // 0xcd
  new Word("Zhuo"), // 0xce
  new Word("Chu"), // 0xcf
  new Word("Le"), // 0xd0
  new Word("You"), // 0xd1
  new Word("Gu"), // 0xd2
  new Word("Hong"), // 0xd3
  new Word("Gan"), // 0xd4
  new Word("Fa"), // 0xd5
  new Word("Mao"), // 0xd6
  new Word("Si"), // 0xd7
  new Word("Hu"), // 0xd8
  new Word("Ping"), // 0xd9
  new Word("Ci"), // 0xda
  new Word("Fan"), // 0xdb
  new Word("Chi"), // 0xdc
  new Word("Su"), // 0xdd
  new Word("Ning"), // 0xde
  new Word("Cheng"), // 0xdf
  new Word("Ling"), // 0xe0
  new Word("Pao"), // 0xe1
  new Word("Bo"), // 0xe2
  new Word("Qi"), // 0xe3
  new Word("Si"), // 0xe4
  new Word("Ni"), // 0xe5
  new Word("Ju"), // 0xe6
  new Word("Yue"), // 0xe7
  new Word("Zhu"), // 0xe8
  new Word("Sheng"), // 0xe9
  new Word("Lei"), // 0xea
  new Word("Xuan"), // 0xeb
  new Word("Xue"), // 0xec
  new Word("Fu"), // 0xed
  new Word("Pan"), // 0xee
  new Word("Min"), // 0xef
  new Word("Tai"), // 0xf0
  new Word("Yang"), // 0xf1
  new Word("Ji"), // 0xf2
  new Word("Yong"), // 0xf3
  new Word("Guan"), // 0xf4
  new Word("Beng"), // 0xf5
  new Word("Xue"), // 0xf6
  new Word("Long"), // 0xf7
  new Word("Lu"), // 0xf8
  null, // 0xf9
  new Word("Bo"), // 0xfa
  new Word("Xie"), // 0xfb
  new Word("Po"), // 0xfc
  new Word("Ze"), // 0xfd
  new Word("Jing"), // 0xfe
  new Word("Yin") // 0xff
  };
}