/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+6Dxx (CJK Unified Ideographs).
 */
final class X6d extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Zhou"), // 0x00
  new Word("Ji"), // 0x01
  new Word("Yi"), // 0x02
  new Word("Hui"), // 0x03
  new Word("Hui"), // 0x04
  new Word("Zui"), // 0x05
  new Word("Cheng"), // 0x06
  new Word("Yin"), // 0x07
  new Word("Wei"), // 0x08
  new Word("Hou"), // 0x09
  new Word("Jian"), // 0x0a
  new Word("Yang"), // 0x0b
  new Word("Lie"), // 0x0c
  new Word("Si"), // 0x0d
  new Word("Ji"), // 0x0e
  new Word("Er"), // 0x0f
  new Word("Xing"), // 0x10
  new Word("Fu"), // 0x11
  new Word("Sa"), // 0x12
  new Word("Suo"), // 0x13
  new Word("Zhi"), // 0x14
  new Word("Yin"), // 0x15
  new Word("Wu"), // 0x16
  new Word("Xi"), // 0x17
  new Word("Kao"), // 0x18
  new Word("Zhu"), // 0x19
  new Word("Jiang"), // 0x1a
  new Word("Luo"), // 0x1b
  null, // 0x1c
  new Word("An"), // 0x1d
  new Word("Dong"), // 0x1e
  new Word("Yi"), // 0x1f
  new Word("Mou"), // 0x20
  new Word("Lei"), // 0x21
  new Word("Yi"), // 0x22
  new Word("Mi"), // 0x23
  new Word("Quan"), // 0x24
  new Word("Jin"), // 0x25
  new Word("Mo"), // 0x26
  new Word("Wei"), // 0x27
  new Word("Xiao"), // 0x28
  new Word("Xie"), // 0x29
  new Word("Hong"), // 0x2a
  new Word("Xu"), // 0x2b
  new Word("Shuo"), // 0x2c
  new Word("Kuang"), // 0x2d
  new Word("Tao"), // 0x2e
  new Word("Qie"), // 0x2f
  new Word("Ju"), // 0x30
  new Word("Er"), // 0x31
  new Word("Zhou"), // 0x32
  new Word("Ru"), // 0x33
  new Word("Ping"), // 0x34
  new Word("Xun"), // 0x35
  new Word("Xiong"), // 0x36
  new Word("Zhi"), // 0x37
  new Word("Guang"), // 0x38
  new Word("Huan"), // 0x39
  new Word("Ming"), // 0x3a
  new Word("Huo"), // 0x3b
  new Word("Wa"), // 0x3c
  new Word("Qia"), // 0x3d
  new Word("Pai"), // 0x3e
  new Word("Wu"), // 0x3f
  new Word("Qu"), // 0x40
  new Word("Liu"), // 0x41
  new Word("Yi"), // 0x42
  new Word("Jia"), // 0x43
  new Word("Jing"), // 0x44
  new Word("Qian"), // 0x45
  new Word("Jiang"), // 0x46
  new Word("Jiao"), // 0x47
  new Word("Cheng"), // 0x48
  new Word("Shi"), // 0x49
  new Word("Zhuo"), // 0x4a
  new Word("Ce"), // 0x4b
  new Word("Pal"), // 0x4c
  new Word("Kuai"), // 0x4d
  new Word("Ji"), // 0x4e
  new Word("Liu"), // 0x4f
  new Word("Chan"), // 0x50
  new Word("Hun"), // 0x51
  new Word("Hu"), // 0x52
  new Word("Nong"), // 0x53
  new Word("Xun"), // 0x54
  new Word("Jin"), // 0x55
  new Word("Lie"), // 0x56
  new Word("Qiu"), // 0x57
  new Word("Wei"), // 0x58
  new Word("Zhe"), // 0x59
  new Word("Jun"), // 0x5a
  new Word("Han"), // 0x5b
  new Word("Bang"), // 0x5c
  new Word("Mang"), // 0x5d
  new Word("Zhuo"), // 0x5e
  new Word("You"), // 0x5f
  new Word("Xi"), // 0x60
  new Word("Bo"), // 0x61
  new Word("Dou"), // 0x62
  new Word("Wan"), // 0x63
  new Word("Hong"), // 0x64
  new Word("Yi"), // 0x65
  new Word("Pu"), // 0x66
  new Word("Ying"), // 0x67
  new Word("Lan"), // 0x68
  new Word("Hao"), // 0x69
  new Word("Lang"), // 0x6a
  new Word("Han"), // 0x6b
  new Word("Li"), // 0x6c
  new Word("Geng"), // 0x6d
  new Word("Fu"), // 0x6e
  new Word("Wu"), // 0x6f
  new Word("Lian"), // 0x70
  new Word("Chun"), // 0x71
  new Word("Feng"), // 0x72
  new Word("Yi"), // 0x73
  new Word("Yu"), // 0x74
  new Word("Tong"), // 0x75
  new Word("Lao"), // 0x76
  new Word("Hai"), // 0x77
  new Word("Jin"), // 0x78
  new Word("Jia"), // 0x79
  new Word("Chong"), // 0x7a
  new Word("Weng"), // 0x7b
  new Word("Mei"), // 0x7c
  new Word("Sui"), // 0x7d
  new Word("Cheng"), // 0x7e
  new Word("Pei"), // 0x7f
  new Word("Xian"), // 0x80
  new Word("Shen"), // 0x81
  new Word("Tu"), // 0x82
  new Word("Kun"), // 0x83
  new Word("Pin"), // 0x84
  new Word("Nie"), // 0x85
  new Word("Han"), // 0x86
  new Word("Jing"), // 0x87
  new Word("Xiao"), // 0x88
  new Word("She"), // 0x89
  new Word("Nian"), // 0x8a
  new Word("Tu"), // 0x8b
  new Word("Yong"), // 0x8c
  new Word("Xiao"), // 0x8d
  new Word("Xian"), // 0x8e
  new Word("Ting"), // 0x8f
  new Word("E"), // 0x90
  new Word("Su"), // 0x91
  new Word("Tun"), // 0x92
  new Word("Juan"), // 0x93
  new Word("Cen"), // 0x94
  new Word("Ti"), // 0x95
  new Word("Li"), // 0x96
  new Word("Shui"), // 0x97
  new Word("Si"), // 0x98
  new Word("Lei"), // 0x99
  new Word("Shui"), // 0x9a
  new Word("Tao"), // 0x9b
  new Word("Du"), // 0x9c
  new Word("Lao"), // 0x9d
  new Word("Lai"), // 0x9e
  new Word("Lian"), // 0x9f
  new Word("Wei"), // 0xa0
  new Word("Wo"), // 0xa1
  new Word("Yun"), // 0xa2
  new Word("Huan"), // 0xa3
  new Word("Di"), // 0xa4
  null, // 0xa5
  new Word("Run"), // 0xa6
  new Word("Jian"), // 0xa7
  new Word("Zhang"), // 0xa8
  new Word("Se"), // 0xa9
  new Word("Fu"), // 0xaa
  new Word("Guan"), // 0xab
  new Word("Xing"), // 0xac
  new Word("Shou"), // 0xad
  new Word("Shuan"), // 0xae
  new Word("Ya"), // 0xaf
  new Word("Chuo"), // 0xb0
  new Word("Zhang"), // 0xb1
  new Word("Ye"), // 0xb2
  new Word("Kong"), // 0xb3
  new Word("Wo"), // 0xb4
  new Word("Han"), // 0xb5
  new Word("Tuo"), // 0xb6
  new Word("Dong"), // 0xb7
  new Word("He"), // 0xb8
  new Word("Wo"), // 0xb9
  new Word("Ju"), // 0xba
  new Word("Gan"), // 0xbb
  new Word("Liang"), // 0xbc
  new Word("Hun"), // 0xbd
  new Word("Ta"), // 0xbe
  new Word("Zhuo"), // 0xbf
  new Word("Dian"), // 0xc0
  new Word("Qie"), // 0xc1
  new Word("De"), // 0xc2
  new Word("Juan"), // 0xc3
  new Word("Zi"), // 0xc4
  new Word("Xi"), // 0xc5
  new Word("Yao"), // 0xc6
  new Word("Qi"), // 0xc7
  new Word("Gu"), // 0xc8
  new Word("Guo"), // 0xc9
  new Word("Han"), // 0xca
  new Word("Lin"), // 0xcb
  new Word("Tang"), // 0xcc
  new Word("Zhou"), // 0xcd
  new Word("Peng"), // 0xce
  new Word("Hao"), // 0xcf
  new Word("Chang"), // 0xd0
  new Word("Shu"), // 0xd1
  new Word("Qi"), // 0xd2
  new Word("Fang"), // 0xd3
  new Word("Chi"), // 0xd4
  new Word("Lu"), // 0xd5
  new Word("Nao"), // 0xd6
  new Word("Ju"), // 0xd7
  new Word("Tao"), // 0xd8
  new Word("Cong"), // 0xd9
  new Word("Lei"), // 0xda
  new Word("Zhi"), // 0xdb
  new Word("Peng"), // 0xdc
  new Word("Fei"), // 0xdd
  new Word("Song"), // 0xde
  new Word("Tian"), // 0xdf
  new Word("Pi"), // 0xe0
  new Word("Dan"), // 0xe1
  new Word("Yu"), // 0xe2
  new Word("Ni"), // 0xe3
  new Word("Yu"), // 0xe4
  new Word("Lu"), // 0xe5
  new Word("Gan"), // 0xe6
  new Word("Mi"), // 0xe7
  new Word("Jing"), // 0xe8
  new Word("Ling"), // 0xe9
  new Word("Lun"), // 0xea
  new Word("Yin"), // 0xeb
  new Word("Cui"), // 0xec
  new Word("Qu"), // 0xed
  new Word("Huai"), // 0xee
  new Word("Yu"), // 0xef
  new Word("Nian"), // 0xf0
  new Word("Shen"), // 0xf1
  new Word("Piao"), // 0xf2
  new Word("Chun"), // 0xf3
  new Word("Wa"), // 0xf4
  new Word("Yuan"), // 0xf5
  new Word("Lai"), // 0xf6
  new Word("Hun"), // 0xf7
  new Word("Qing"), // 0xf8
  new Word("Yan"), // 0xf9
  new Word("Qian"), // 0xfa
  new Word("Tian"), // 0xfb
  new Word("Miao"), // 0xfc
  new Word("Zhi"), // 0xfd
  new Word("Yin"), // 0xfe
  new Word("Mi") // 0xff
  };
}