/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+6Exx (CJK Unified Ideographs).
 */
final class X6e extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Ben"), // 0x00
  new Word("Yuan"), // 0x01
  new Word("Wen"), // 0x02
  new Word("Re"), // 0x03
  new Word("Fei"), // 0x04
  new Word("Qing"), // 0x05
  new Word("Yuan"), // 0x06
  new Word("Ke"), // 0x07
  new Word("Ji"), // 0x08
  new Word("She"), // 0x09
  new Word("Yuan"), // 0x0a
  new Word("Shibui"), // 0x0b
  new Word("Lu"), // 0x0c
  new Word("Zi"), // 0x0d
  new Word("Du"), // 0x0e
  null, // 0x0f
  new Word("Jian"), // 0x10
  new Word("Min"), // 0x11
  new Word("Pi"), // 0x12
  new Word("Tani"), // 0x13
  new Word("Yu"), // 0x14
  new Word("Yuan"), // 0x15
  new Word("Shen"), // 0x16
  new Word("Shen"), // 0x17
  new Word("Rou"), // 0x18
  new Word("Huan"), // 0x19
  new Word("Zhu"), // 0x1a
  new Word("Jian"), // 0x1b
  new Word("Nuan"), // 0x1c
  new Word("Yu"), // 0x1d
  new Word("Qiu"), // 0x1e
  new Word("Ting"), // 0x1f
  new Word("Qu"), // 0x20
  new Word("Du"), // 0x21
  new Word("Feng"), // 0x22
  new Word("Zha"), // 0x23
  new Word("Bo"), // 0x24
  new Word("Wo"), // 0x25
  new Word("Wo"), // 0x26
  new Word("Di"), // 0x27
  new Word("Wei"), // 0x28
  new Word("Wen"), // 0x29
  new Word("Ru"), // 0x2a
  new Word("Xie"), // 0x2b
  new Word("Ce"), // 0x2c
  new Word("Wei"), // 0x2d
  new Word("Ge"), // 0x2e
  new Word("Gang"), // 0x2f
  new Word("Yan"), // 0x30
  new Word("Hong"), // 0x31
  new Word("Xuan"), // 0x32
  new Word("Mi"), // 0x33
  new Word("Ke"), // 0x34
  new Word("Mao"), // 0x35
  new Word("Ying"), // 0x36
  new Word("Yan"), // 0x37
  new Word("You"), // 0x38
  new Word("Hong"), // 0x39
  new Word("Miao"), // 0x3a
  new Word("Xing"), // 0x3b
  new Word("Mei"), // 0x3c
  new Word("Zai"), // 0x3d
  new Word("Hun"), // 0x3e
  new Word("Nai"), // 0x3f
  new Word("Kui"), // 0x40
  new Word("Shi"), // 0x41
  new Word("E"), // 0x42
  new Word("Pai"), // 0x43
  new Word("Mei"), // 0x44
  new Word("Lian"), // 0x45
  new Word("Qi"), // 0x46
  new Word("Qi"), // 0x47
  new Word("Mei"), // 0x48
  new Word("Tian"), // 0x49
  new Word("Cou"), // 0x4a
  new Word("Wei"), // 0x4b
  new Word("Can"), // 0x4c
  new Word("Tuan"), // 0x4d
  new Word("Mian"), // 0x4e
  new Word("Hui"), // 0x4f
  new Word("Mo"), // 0x50
  new Word("Xu"), // 0x51
  new Word("Ji"), // 0x52
  new Word("Pen"), // 0x53
  new Word("Jian"), // 0x54
  new Word("Jian"), // 0x55
  new Word("Hu"), // 0x56
  new Word("Feng"), // 0x57
  new Word("Xiang"), // 0x58
  new Word("Yi"), // 0x59
  new Word("Yin"), // 0x5a
  new Word("Zhan"), // 0x5b
  new Word("Shi"), // 0x5c
  new Word("Jie"), // 0x5d
  new Word("Cheng"), // 0x5e
  new Word("Huang"), // 0x5f
  new Word("Tan"), // 0x60
  new Word("Yu"), // 0x61
  new Word("Bi"), // 0x62
  new Word("Min"), // 0x63
  new Word("Shi"), // 0x64
  new Word("Tu"), // 0x65
  new Word("Sheng"), // 0x66
  new Word("Yong"), // 0x67
  new Word("Qu"), // 0x68
  new Word("Zhong"), // 0x69
  new Word("Suei"), // 0x6a
  new Word("Jiu"), // 0x6b
  new Word("Jiao"), // 0x6c
  new Word("Qiou"), // 0x6d
  new Word("Yin"), // 0x6e
  new Word("Tang"), // 0x6f
  new Word("Long"), // 0x70
  new Word("Huo"), // 0x71
  new Word("Yuan"), // 0x72
  new Word("Nan"), // 0x73
  new Word("Ban"), // 0x74
  new Word("You"), // 0x75
  new Word("Quan"), // 0x76
  new Word("Chui"), // 0x77
  new Word("Liang"), // 0x78
  new Word("Chan"), // 0x79
  new Word("Yan"), // 0x7a
  new Word("Chun"), // 0x7b
  new Word("Nie"), // 0x7c
  new Word("Zi"), // 0x7d
  new Word("Wan"), // 0x7e
  new Word("Shi"), // 0x7f
  new Word("Man"), // 0x80
  new Word("Ying"), // 0x81
  new Word("Ratsu"), // 0x82
  new Word("Kui"), // 0x83
  null, // 0x84
  new Word("Jian"), // 0x85
  new Word("Xu"), // 0x86
  new Word("Lu"), // 0x87
  new Word("Gui"), // 0x88
  new Word("Gai"), // 0x89
  null, // 0x8a
  null, // 0x8b
  new Word("Po"), // 0x8c
  new Word("Jin"), // 0x8d
  new Word("Gui"), // 0x8e
  new Word("Tang"), // 0x8f
  new Word("Yuan"), // 0x90
  new Word("Suo"), // 0x91
  new Word("Yuan"), // 0x92
  new Word("Lian"), // 0x93
  new Word("Yao"), // 0x94
  new Word("Meng"), // 0x95
  new Word("Zhun"), // 0x96
  new Word("Sheng"), // 0x97
  new Word("Ke"), // 0x98
  new Word("Tai"), // 0x99
  new Word("Da"), // 0x9a
  new Word("Wa"), // 0x9b
  new Word("Liu"), // 0x9c
  new Word("Gou"), // 0x9d
  new Word("Sao"), // 0x9e
  new Word("Ming"), // 0x9f
  new Word("Zha"), // 0xa0
  new Word("Shi"), // 0xa1
  new Word("Yi"), // 0xa2
  new Word("Lun"), // 0xa3
  new Word("Ma"), // 0xa4
  new Word("Pu"), // 0xa5
  new Word("Wei"), // 0xa6
  new Word("Li"), // 0xa7
  new Word("Cai"), // 0xa8
  new Word("Wu"), // 0xa9
  new Word("Xi"), // 0xaa
  new Word("Wen"), // 0xab
  new Word("Qiang"), // 0xac
  new Word("Ze"), // 0xad
  new Word("Shi"), // 0xae
  new Word("Su"), // 0xaf
  new Word("Yi"), // 0xb0
  new Word("Zhen"), // 0xb1
  new Word("Sou"), // 0xb2
  new Word("Yun"), // 0xb3
  new Word("Xiu"), // 0xb4
  new Word("Yin"), // 0xb5
  new Word("Rong"), // 0xb6
  new Word("Hun"), // 0xb7
  new Word("Su"), // 0xb8
  new Word("Su"), // 0xb9
  new Word("Ni"), // 0xba
  new Word("Ta"), // 0xbb
  new Word("Shi"), // 0xbc
  new Word("Ru"), // 0xbd
  new Word("Wei"), // 0xbe
  new Word("Pan"), // 0xbf
  new Word("Chu"), // 0xc0
  new Word("Chu"), // 0xc1
  new Word("Pang"), // 0xc2
  new Word("Weng"), // 0xc3
  new Word("Cang"), // 0xc4
  new Word("Mie"), // 0xc5
  new Word("He"), // 0xc6
  new Word("Dian"), // 0xc7
  new Word("Hao"), // 0xc8
  new Word("Huang"), // 0xc9
  new Word("Xi"), // 0xca
  new Word("Zi"), // 0xcb
  new Word("Di"), // 0xcc
  new Word("Zhi"), // 0xcd
  new Word("Ying"), // 0xce
  new Word("Fu"), // 0xcf
  new Word("Jie"), // 0xd0
  new Word("Hua"), // 0xd1
  new Word("Ge"), // 0xd2
  new Word("Zi"), // 0xd3
  new Word("Tao"), // 0xd4
  new Word("Teng"), // 0xd5
  new Word("Sui"), // 0xd6
  new Word("Bi"), // 0xd7
  new Word("Jiao"), // 0xd8
  new Word("Hui"), // 0xd9
  new Word("Gun"), // 0xda
  new Word("Yin"), // 0xdb
  new Word("Gao"), // 0xdc
  new Word("Long"), // 0xdd
  new Word("Zhi"), // 0xde
  new Word("Yan"), // 0xdf
  new Word("She"), // 0xe0
  new Word("Man"), // 0xe1
  new Word("Ying"), // 0xe2
  new Word("Chun"), // 0xe3
  new Word("Lu"), // 0xe4
  new Word("Lan"), // 0xe5
  new Word("Luan"), // 0xe6
  null, // 0xe7
  new Word("Bin"), // 0xe8
  new Word("Tan"), // 0xe9
  new Word("Yu"), // 0xea
  new Word("Sou"), // 0xeb
  new Word("Hu"), // 0xec
  new Word("Bi"), // 0xed
  new Word("Biao"), // 0xee
  new Word("Zhi"), // 0xef
  new Word("Jiang"), // 0xf0
  new Word("Kou"), // 0xf1
  new Word("Shen"), // 0xf2
  new Word("Shang"), // 0xf3
  new Word("Di"), // 0xf4
  new Word("Mi"), // 0xf5
  new Word("Ao"), // 0xf6
  new Word("Lu"), // 0xf7
  new Word("Hu"), // 0xf8
  new Word("Hu"), // 0xf9
  new Word("You"), // 0xfa
  new Word("Chan"), // 0xfb
  new Word("Fan"), // 0xfc
  new Word("Yong"), // 0xfd
  new Word("Gun"), // 0xfe
  new Word("Man") // 0xff
  };
}