/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+6Fxx (CJK Unified Ideographs).
 */
final class X6f extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Qing"), // 0x00
  new Word("Yu"), // 0x01
  new Word("Piao"), // 0x02
  new Word("Ji"), // 0x03
  new Word("Ya"), // 0x04
  new Word("Jiao"), // 0x05
  new Word("Qi"), // 0x06
  new Word("Xi"), // 0x07
  new Word("Ji"), // 0x08
  new Word("Lu"), // 0x09
  new Word("Lu"), // 0x0a
  new Word("Long"), // 0x0b
  new Word("Jin"), // 0x0c
  new Word("Guo"), // 0x0d
  new Word("Cong"), // 0x0e
  new Word("Lou"), // 0x0f
  new Word("Zhi"), // 0x10
  new Word("Gai"), // 0x11
  new Word("Qiang"), // 0x12
  new Word("Li"), // 0x13
  new Word("Yan"), // 0x14
  new Word("Cao"), // 0x15
  new Word("Jiao"), // 0x16
  new Word("Cong"), // 0x17
  new Word("Qun"), // 0x18
  new Word("Tuan"), // 0x19
  new Word("Ou"), // 0x1a
  new Word("Teng"), // 0x1b
  new Word("Ye"), // 0x1c
  new Word("Xi"), // 0x1d
  new Word("Mi"), // 0x1e
  new Word("Tang"), // 0x1f
  new Word("Mo"), // 0x20
  new Word("Shang"), // 0x21
  new Word("Han"), // 0x22
  new Word("Lian"), // 0x23
  new Word("Lan"), // 0x24
  new Word("Wa"), // 0x25
  new Word("Li"), // 0x26
  new Word("Qian"), // 0x27
  new Word("Feng"), // 0x28
  new Word("Xuan"), // 0x29
  new Word("Yi"), // 0x2a
  new Word("Man"), // 0x2b
  new Word("Zi"), // 0x2c
  new Word("Mang"), // 0x2d
  new Word("Kang"), // 0x2e
  new Word("Lei"), // 0x2f
  new Word("Peng"), // 0x30
  new Word("Shu"), // 0x31
  new Word("Zhang"), // 0x32
  new Word("Zhang"), // 0x33
  new Word("Chong"), // 0x34
  new Word("Xu"), // 0x35
  new Word("Huan"), // 0x36
  new Word("Kuo"), // 0x37
  new Word("Jian"), // 0x38
  new Word("Yan"), // 0x39
  new Word("Chuang"), // 0x3a
  new Word("Liao"), // 0x3b
  new Word("Cui"), // 0x3c
  new Word("Ti"), // 0x3d
  new Word("Yang"), // 0x3e
  new Word("Jiang"), // 0x3f
  new Word("Cong"), // 0x40
  new Word("Ying"), // 0x41
  new Word("Hong"), // 0x42
  new Word("Xun"), // 0x43
  new Word("Shu"), // 0x44
  new Word("Guan"), // 0x45
  new Word("Ying"), // 0x46
  new Word("Xiao"), // 0x47
  null, // 0x48
  null, // 0x49
  new Word("Xu"), // 0x4a
  new Word("Lian"), // 0x4b
  new Word("Zhi"), // 0x4c
  new Word("Wei"), // 0x4d
  new Word("Pi"), // 0x4e
  new Word("Jue"), // 0x4f
  new Word("Jiao"), // 0x50
  new Word("Po"), // 0x51
  new Word("Dang"), // 0x52
  new Word("Hui"), // 0x53
  new Word("Jie"), // 0x54
  new Word("Wu"), // 0x55
  new Word("Pa"), // 0x56
  new Word("Ji"), // 0x57
  new Word("Pan"), // 0x58
  new Word("Gui"), // 0x59
  new Word("Xiao"), // 0x5a
  new Word("Qian"), // 0x5b
  new Word("Qian"), // 0x5c
  new Word("Xi"), // 0x5d
  new Word("Lu"), // 0x5e
  new Word("Xi"), // 0x5f
  new Word("Xuan"), // 0x60
  new Word("Dun"), // 0x61
  new Word("Huang"), // 0x62
  new Word("Min"), // 0x63
  new Word("Run"), // 0x64
  new Word("Su"), // 0x65
  new Word("Liao"), // 0x66
  new Word("Zhen"), // 0x67
  new Word("Zhong"), // 0x68
  new Word("Yi"), // 0x69
  new Word("Di"), // 0x6a
  new Word("Wan"), // 0x6b
  new Word("Dan"), // 0x6c
  new Word("Tan"), // 0x6d
  new Word("Chao"), // 0x6e
  new Word("Xun"), // 0x6f
  new Word("Kui"), // 0x70
  new Word("Yie"), // 0x71
  new Word("Shao"), // 0x72
  new Word("Tu"), // 0x73
  new Word("Zhu"), // 0x74
  new Word("San"), // 0x75
  new Word("Hei"), // 0x76
  new Word("Bi"), // 0x77
  new Word("Shan"), // 0x78
  new Word("Chan"), // 0x79
  new Word("Chan"), // 0x7a
  new Word("Shu"), // 0x7b
  new Word("Tong"), // 0x7c
  new Word("Pu"), // 0x7d
  new Word("Lin"), // 0x7e
  new Word("Wei"), // 0x7f
  new Word("Se"), // 0x80
  new Word("Se"), // 0x81
  new Word("Cheng"), // 0x82
  new Word("Jiong"), // 0x83
  new Word("Cheng"), // 0x84
  new Word("Hua"), // 0x85
  new Word("Jiao"), // 0x86
  new Word("Lao"), // 0x87
  new Word("Che"), // 0x88
  new Word("Gan"), // 0x89
  new Word("Cun"), // 0x8a
  new Word("Heng"), // 0x8b
  new Word("Si"), // 0x8c
  new Word("Shu"), // 0x8d
  new Word("Peng"), // 0x8e
  new Word("Han"), // 0x8f
  new Word("Yun"), // 0x90
  new Word("Liu"), // 0x91
  new Word("Hong"), // 0x92
  new Word("Fu"), // 0x93
  new Word("Hao"), // 0x94
  new Word("He"), // 0x95
  new Word("Xian"), // 0x96
  new Word("Jian"), // 0x97
  new Word("Shan"), // 0x98
  new Word("Xi"), // 0x99
  new Word("Oki"), // 0x9a
  null, // 0x9b
  new Word("Lan"), // 0x9c
  null, // 0x9d
  new Word("Yu"), // 0x9e
  new Word("Lin"), // 0x9f
  new Word("Min"), // 0xa0
  new Word("Zao"), // 0xa1
  new Word("Dang"), // 0xa2
  new Word("Wan"), // 0xa3
  new Word("Ze"), // 0xa4
  new Word("Xie"), // 0xa5
  new Word("Yu"), // 0xa6
  new Word("Li"), // 0xa7
  new Word("Shi"), // 0xa8
  new Word("Xue"), // 0xa9
  new Word("Ling"), // 0xaa
  new Word("Man"), // 0xab
  new Word("Zi"), // 0xac
  new Word("Yong"), // 0xad
  new Word("Kuai"), // 0xae
  new Word("Can"), // 0xaf
  new Word("Lian"), // 0xb0
  new Word("Dian"), // 0xb1
  new Word("Ye"), // 0xb2
  new Word("Ao"), // 0xb3
  new Word("Huan"), // 0xb4
  new Word("Zhen"), // 0xb5
  new Word("Chan"), // 0xb6
  new Word("Man"), // 0xb7
  new Word("Dan"), // 0xb8
  new Word("Dan"), // 0xb9
  new Word("Yi"), // 0xba
  new Word("Sui"), // 0xbb
  new Word("Pi"), // 0xbc
  new Word("Ju"), // 0xbd
  new Word("Ta"), // 0xbe
  new Word("Qin"), // 0xbf
  new Word("Ji"), // 0xc0
  new Word("Zhuo"), // 0xc1
  new Word("Lian"), // 0xc2
  new Word("Nong"), // 0xc3
  new Word("Guo"), // 0xc4
  new Word("Jin"), // 0xc5
  new Word("Fen"), // 0xc6
  new Word("Se"), // 0xc7
  new Word("Ji"), // 0xc8
  new Word("Sui"), // 0xc9
  new Word("Hui"), // 0xca
  new Word("Chu"), // 0xcb
  new Word("Ta"), // 0xcc
  new Word("Song"), // 0xcd
  new Word("Ding"), // 0xce
  null, // 0xcf
  new Word("Zhu"), // 0xd0
  new Word("Lai"), // 0xd1
  new Word("Bin"), // 0xd2
  new Word("Lian"), // 0xd3
  new Word("Mi"), // 0xd4
  new Word("Shi"), // 0xd5
  new Word("Shu"), // 0xd6
  new Word("Mi"), // 0xd7
  new Word("Ning"), // 0xd8
  new Word("Ying"), // 0xd9
  new Word("Ying"), // 0xda
  new Word("Meng"), // 0xdb
  new Word("Jin"), // 0xdc
  new Word("Qi"), // 0xdd
  new Word("Pi"), // 0xde
  new Word("Ji"), // 0xdf
  new Word("Hao"), // 0xe0
  new Word("Ru"), // 0xe1
  new Word("Zui"), // 0xe2
  new Word("Wo"), // 0xe3
  new Word("Tao"), // 0xe4
  new Word("Yin"), // 0xe5
  new Word("Yin"), // 0xe6
  new Word("Dui"), // 0xe7
  new Word("Ci"), // 0xe8
  new Word("Huo"), // 0xe9
  new Word("Jing"), // 0xea
  new Word("Lan"), // 0xeb
  new Word("Jun"), // 0xec
  new Word("Ai"), // 0xed
  new Word("Pu"), // 0xee
  new Word("Zhuo"), // 0xef
  new Word("Wei"), // 0xf0
  new Word("Bin"), // 0xf1
  new Word("Gu"), // 0xf2
  new Word("Qian"), // 0xf3
  new Word("Xing"), // 0xf4
  new Word("Hama"), // 0xf5
  new Word("Kuo"), // 0xf6
  new Word("Fei"), // 0xf7
  null, // 0xf8
  new Word("Boku"), // 0xf9
  new Word("Jian"), // 0xfa
  new Word("Wei"), // 0xfb
  new Word("Luo"), // 0xfc
  new Word("Zan"), // 0xfd
  new Word("Lu"), // 0xfe
  new Word("Li") // 0xff
  };
}