/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+71xx (CJK Unified Ideographs).
 */
final class X71 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Hu"), // 0x00
  new Word("Xi"), // 0x01
  new Word("Shu"), // 0x02
  new Word("He"), // 0x03
  new Word("Xun"), // 0x04
  new Word("Ku"), // 0x05
  new Word("Jue"), // 0x06
  new Word("Xiao"), // 0x07
  new Word("Xi"), // 0x08
  new Word("Yan"), // 0x09
  new Word("Han"), // 0x0a
  new Word("Zhuang"), // 0x0b
  new Word("Jun"), // 0x0c
  new Word("Di"), // 0x0d
  new Word("Xie"), // 0x0e
  new Word("Ji"), // 0x0f
  new Word("Wu"), // 0x10
  null, // 0x11
  null, // 0x12
  new Word("Han"), // 0x13
  new Word("Yan"), // 0x14
  new Word("Huan"), // 0x15
  new Word("Men"), // 0x16
  new Word("Ju"), // 0x17
  new Word("Chou"), // 0x18
  new Word("Bei"), // 0x19
  new Word("Fen"), // 0x1a
  new Word("Lin"), // 0x1b
  new Word("Kun"), // 0x1c
  new Word("Hun"), // 0x1d
  new Word("Tun"), // 0x1e
  new Word("Xi"), // 0x1f
  new Word("Cui"), // 0x20
  new Word("Wu"), // 0x21
  new Word("Hong"), // 0x22
  new Word("Ju"), // 0x23
  new Word("Fu"), // 0x24
  new Word("Wo"), // 0x25
  new Word("Jiao"), // 0x26
  new Word("Cong"), // 0x27
  new Word("Feng"), // 0x28
  new Word("Ping"), // 0x29
  new Word("Qiong"), // 0x2a
  new Word("Ruo"), // 0x2b
  new Word("Xi"), // 0x2c
  new Word("Qiong"), // 0x2d
  new Word("Xin"), // 0x2e
  new Word("Zhuo"), // 0x2f
  new Word("Yan"), // 0x30
  new Word("Yan"), // 0x31
  new Word("Yi"), // 0x32
  new Word("Jue"), // 0x33
  new Word("Yu"), // 0x34
  new Word("Gang"), // 0x35
  new Word("Ran"), // 0x36
  new Word("Pi"), // 0x37
  new Word("Gu"), // 0x38
  null, // 0x39
  new Word("Sheng"), // 0x3a
  new Word("Chang"), // 0x3b
  new Word("Shao"), // 0x3c
  null, // 0x3d
  null, // 0x3e
  null, // 0x3f
  null, // 0x40
  new Word("Chen"), // 0x41
  new Word("He"), // 0x42
  new Word("Kui"), // 0x43
  new Word("Zhong"), // 0x44
  new Word("Duan"), // 0x45
  new Word("Xia"), // 0x46
  new Word("Hui"), // 0x47
  new Word("Feng"), // 0x48
  new Word("Lian"), // 0x49
  new Word("Xuan"), // 0x4a
  new Word("Xing"), // 0x4b
  new Word("Huang"), // 0x4c
  new Word("Jiao"), // 0x4d
  new Word("Jian"), // 0x4e
  new Word("Bi"), // 0x4f
  new Word("Ying"), // 0x50
  new Word("Zhu"), // 0x51
  new Word("Wei"), // 0x52
  new Word("Tuan"), // 0x53
  new Word("Tian"), // 0x54
  new Word("Xi"), // 0x55
  new Word("Nuan"), // 0x56
  new Word("Nuan"), // 0x57
  new Word("Chan"), // 0x58
  new Word("Yan"), // 0x59
  new Word("Jiong"), // 0x5a
  new Word("Jiong"), // 0x5b
  new Word("Yu"), // 0x5c
  new Word("Mei"), // 0x5d
  new Word("Sha"), // 0x5e
  new Word("Wei"), // 0x5f
  new Word("Ye"), // 0x60
  new Word("Xin"), // 0x61
  new Word("Qiong"), // 0x62
  new Word("Rou"), // 0x63
  new Word("Mei"), // 0x64
  new Word("Huan"), // 0x65
  new Word("Xu"), // 0x66
  new Word("Zhao"), // 0x67
  new Word("Wei"), // 0x68
  new Word("Fan"), // 0x69
  new Word("Qiu"), // 0x6a
  new Word("Sui"), // 0x6b
  new Word("Yang"), // 0x6c
  new Word("Lie"), // 0x6d
  new Word("Zhu"), // 0x6e
  new Word("Jie"), // 0x6f
  new Word("Gao"), // 0x70
  new Word("Gua"), // 0x71
  new Word("Bao"), // 0x72
  new Word("Hu"), // 0x73
  new Word("Yun"), // 0x74
  new Word("Xia"), // 0x75
  null, // 0x76
  null, // 0x77
  new Word("Bian"), // 0x78
  new Word("Gou"), // 0x79
  new Word("Tui"), // 0x7a
  new Word("Tang"), // 0x7b
  new Word("Chao"), // 0x7c
  new Word("Shan"), // 0x7d
  new Word("N"), // 0x7e
  new Word("Bo"), // 0x7f
  new Word("Huang"), // 0x80
  new Word("Xie"), // 0x81
  new Word("Xi"), // 0x82
  new Word("Wu"), // 0x83
  new Word("Xi"), // 0x84
  new Word("Yun"), // 0x85
  new Word("He"), // 0x86
  new Word("He"), // 0x87
  new Word("Xi"), // 0x88
  new Word("Yun"), // 0x89
  new Word("Xiong"), // 0x8a
  new Word("Nai"), // 0x8b
  new Word("Shan"), // 0x8c
  new Word("Qiong"), // 0x8d
  new Word("Yao"), // 0x8e
  new Word("Xun"), // 0x8f
  new Word("Mi"), // 0x90
  new Word("Lian"), // 0x91
  new Word("Ying"), // 0x92
  new Word("Wen"), // 0x93
  new Word("Rong"), // 0x94
  new Word("Oozutsu"), // 0x95
  null, // 0x96
  new Word("Qiang"), // 0x97
  new Word("Liu"), // 0x98
  new Word("Xi"), // 0x99
  new Word("Bi"), // 0x9a
  new Word("Biao"), // 0x9b
  new Word("Zong"), // 0x9c
  new Word("Lu"), // 0x9d
  new Word("Jian"), // 0x9e
  new Word("Shou"), // 0x9f
  new Word("Yi"), // 0xa0
  new Word("Lou"), // 0xa1
  new Word("Feng"), // 0xa2
  new Word("Sui"), // 0xa3
  new Word("Yi"), // 0xa4
  new Word("Tong"), // 0xa5
  new Word("Jue"), // 0xa6
  new Word("Zong"), // 0xa7
  new Word("Yun"), // 0xa8
  new Word("Hu"), // 0xa9
  new Word("Yi"), // 0xaa
  new Word("Zhi"), // 0xab
  new Word("Ao"), // 0xac
  new Word("Wei"), // 0xad
  new Word("Liao"), // 0xae
  new Word("Han"), // 0xaf
  new Word("Ou"), // 0xb0
  new Word("Re"), // 0xb1
  new Word("Jiong"), // 0xb2
  new Word("Man"), // 0xb3
  null, // 0xb4
  new Word("Shang"), // 0xb5
  new Word("Cuan"), // 0xb6
  new Word("Zeng"), // 0xb7
  new Word("Jian"), // 0xb8
  new Word("Xi"), // 0xb9
  new Word("Xi"), // 0xba
  new Word("Xi"), // 0xbb
  new Word("Yi"), // 0xbc
  new Word("Xiao"), // 0xbd
  new Word("Chi"), // 0xbe
  new Word("Huang"), // 0xbf
  new Word("Chan"), // 0xc0
  new Word("Ye"), // 0xc1
  new Word("Qian"), // 0xc2
  new Word("Ran"), // 0xc3
  new Word("Yan"), // 0xc4
  new Word("Xian"), // 0xc5
  new Word("Qiao"), // 0xc6
  new Word("Zun"), // 0xc7
  new Word("Deng"), // 0xc8
  new Word("Dun"), // 0xc9
  new Word("Shen"), // 0xca
  new Word("Jiao"), // 0xcb
  new Word("Fen"), // 0xcc
  new Word("Si"), // 0xcd
  new Word("Liao"), // 0xce
  new Word("Yu"), // 0xcf
  new Word("Lin"), // 0xd0
  new Word("Tong"), // 0xd1
  new Word("Shao"), // 0xd2
  new Word("Fen"), // 0xd3
  new Word("Fan"), // 0xd4
  new Word("Yan"), // 0xd5
  new Word("Xun"), // 0xd6
  new Word("Lan"), // 0xd7
  new Word("Mei"), // 0xd8
  new Word("Tang"), // 0xd9
  new Word("Yi"), // 0xda
  new Word("Jing"), // 0xdb
  new Word("Men"), // 0xdc
  null, // 0xdd
  null, // 0xde
  new Word("Ying"), // 0xdf
  new Word("Yu"), // 0xe0
  new Word("Yi"), // 0xe1
  new Word("Xue"), // 0xe2
  new Word("Lan"), // 0xe3
  new Word("Tai"), // 0xe4
  new Word("Zao"), // 0xe5
  new Word("Can"), // 0xe6
  new Word("Sui"), // 0xe7
  new Word("Xi"), // 0xe8
  new Word("Que"), // 0xe9
  new Word("Cong"), // 0xea
  new Word("Lian"), // 0xeb
  new Word("Hui"), // 0xec
  new Word("Zhu"), // 0xed
  new Word("Xie"), // 0xee
  new Word("Ling"), // 0xef
  new Word("Wei"), // 0xf0
  new Word("Yi"), // 0xf1
  new Word("Xie"), // 0xf2
  new Word("Zhao"), // 0xf3
  new Word("Hui"), // 0xf4
  new Word("Tatsu"), // 0xf5
  new Word("Nung"), // 0xf6
  new Word("Lan"), // 0xf7
  new Word("Ru"), // 0xf8
  new Word("Xian"), // 0xf9
  new Word("Kao"), // 0xfa
  new Word("Xun"), // 0xfb
  new Word("Jin"), // 0xfc
  new Word("Chou"), // 0xfd
  new Word("Chou"), // 0xfe
  new Word("Yao") // 0xff
  };
}