/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+72xx (CJK Unified Ideographs).
 */
final class X72 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("He"), // 0x00
  new Word("Lan"), // 0x01
  new Word("Biao"), // 0x02
  new Word("Rong"), // 0x03
  new Word("Li"), // 0x04
  new Word("Mo"), // 0x05
  new Word("Bao"), // 0x06
  new Word("Ruo"), // 0x07
  new Word("Lu"), // 0x08
  new Word("La"), // 0x09
  new Word("Ao"), // 0x0a
  new Word("Xun"), // 0x0b
  new Word("Kuang"), // 0x0c
  new Word("Shuo"), // 0x0d
  null, // 0x0e
  new Word("Li"), // 0x0f
  new Word("Lu"), // 0x10
  new Word("Jue"), // 0x11
  new Word("Liao"), // 0x12
  new Word("Yan"), // 0x13
  new Word("Xi"), // 0x14
  new Word("Xie"), // 0x15
  new Word("Long"), // 0x16
  new Word("Ye"), // 0x17
  null, // 0x18
  new Word("Rang"), // 0x19
  new Word("Yue"), // 0x1a
  new Word("Lan"), // 0x1b
  new Word("Cong"), // 0x1c
  new Word("Jue"), // 0x1d
  new Word("Tong"), // 0x1e
  new Word("Guan"), // 0x1f
  null, // 0x20
  new Word("Che"), // 0x21
  new Word("Mi"), // 0x22
  new Word("Tang"), // 0x23
  new Word("Lan"), // 0x24
  new Word("Zhu"), // 0x25
  null, // 0x26
  new Word("Ling"), // 0x27
  new Word("Cuan"), // 0x28
  new Word("Yu"), // 0x29
  new Word("Zhua"), // 0x2a
  new Word("Tsumekanmuri"), // 0x2b
  new Word("Pa"), // 0x2c
  new Word("Zheng"), // 0x2d
  new Word("Pao"), // 0x2e
  new Word("Cheng"), // 0x2f
  new Word("Yuan"), // 0x30
  new Word("Ai"), // 0x31
  new Word("Wei"), // 0x32
  null, // 0x33
  new Word("Jue"), // 0x34
  new Word("Jue"), // 0x35
  new Word("Fu"), // 0x36
  new Word("Ye"), // 0x37
  new Word("Ba"), // 0x38
  new Word("Die"), // 0x39
  new Word("Ye"), // 0x3a
  new Word("Yao"), // 0x3b
  new Word("Zu"), // 0x3c
  new Word("Shuang"), // 0x3d
  new Word("Er"), // 0x3e
  new Word("Qiang"), // 0x3f
  new Word("Chuang"), // 0x40
  new Word("Ge"), // 0x41
  new Word("Zang"), // 0x42
  new Word("Die"), // 0x43
  new Word("Qiang"), // 0x44
  new Word("Yong"), // 0x45
  new Word("Qiang"), // 0x46
  new Word("Pian"), // 0x47
  new Word("Ban"), // 0x48
  new Word("Pan"), // 0x49
  new Word("Shao"), // 0x4a
  new Word("Jian"), // 0x4b
  new Word("Pai"), // 0x4c
  new Word("Du"), // 0x4d
  new Word("Chuang"), // 0x4e
  new Word("Tou"), // 0x4f
  new Word("Zha"), // 0x50
  new Word("Bian"), // 0x51
  new Word("Die"), // 0x52
  new Word("Bang"), // 0x53
  new Word("Bo"), // 0x54
  new Word("Chuang"), // 0x55
  new Word("You"), // 0x56
  null, // 0x57
  new Word("Du"), // 0x58
  new Word("Ya"), // 0x59
  new Word("Cheng"), // 0x5a
  new Word("Niu"), // 0x5b
  new Word("Ushihen"), // 0x5c
  new Word("Pin"), // 0x5d
  new Word("Jiu"), // 0x5e
  new Word("Mou"), // 0x5f
  new Word("Tuo"), // 0x60
  new Word("Mu"), // 0x61
  new Word("Lao"), // 0x62
  new Word("Ren"), // 0x63
  new Word("Mang"), // 0x64
  new Word("Fang"), // 0x65
  new Word("Mao"), // 0x66
  new Word("Mu"), // 0x67
  new Word("Gang"), // 0x68
  new Word("Wu"), // 0x69
  new Word("Yan"), // 0x6a
  new Word("Ge"), // 0x6b
  new Word("Bei"), // 0x6c
  new Word("Si"), // 0x6d
  new Word("Jian"), // 0x6e
  new Word("Gu"), // 0x6f
  new Word("You"), // 0x70
  new Word("Ge"), // 0x71
  new Word("Sheng"), // 0x72
  new Word("Mu"), // 0x73
  new Word("Di"), // 0x74
  new Word("Qian"), // 0x75
  new Word("Quan"), // 0x76
  new Word("Quan"), // 0x77
  new Word("Zi"), // 0x78
  new Word("Te"), // 0x79
  new Word("Xi"), // 0x7a
  new Word("Mang"), // 0x7b
  new Word("Keng"), // 0x7c
  new Word("Qian"), // 0x7d
  new Word("Wu"), // 0x7e
  new Word("Gu"), // 0x7f
  new Word("Xi"), // 0x80
  new Word("Li"), // 0x81
  new Word("Li"), // 0x82
  new Word("Pou"), // 0x83
  new Word("Ji"), // 0x84
  new Word("Gang"), // 0x85
  new Word("Zhi"), // 0x86
  new Word("Ben"), // 0x87
  new Word("Quan"), // 0x88
  new Word("Run"), // 0x89
  new Word("Du"), // 0x8a
  new Word("Ju"), // 0x8b
  new Word("Jia"), // 0x8c
  new Word("Jian"), // 0x8d
  new Word("Feng"), // 0x8e
  new Word("Pian"), // 0x8f
  new Word("Ke"), // 0x90
  new Word("Ju"), // 0x91
  new Word("Kao"), // 0x92
  new Word("Chu"), // 0x93
  new Word("Xi"), // 0x94
  new Word("Bei"), // 0x95
  new Word("Luo"), // 0x96
  new Word("Jie"), // 0x97
  new Word("Ma"), // 0x98
  new Word("San"), // 0x99
  new Word("Wei"), // 0x9a
  new Word("Li"), // 0x9b
  new Word("Dun"), // 0x9c
  new Word("Tong"), // 0x9d
  null, // 0x9e
  new Word("Jiang"), // 0x9f
  new Word("Ikenie"), // 0xa0
  new Word("Li"), // 0xa1
  new Word("Du"), // 0xa2
  new Word("Lie"), // 0xa3
  new Word("Pi"), // 0xa4
  new Word("Piao"), // 0xa5
  new Word("Bao"), // 0xa6
  new Word("Xi"), // 0xa7
  new Word("Chou"), // 0xa8
  new Word("Wei"), // 0xa9
  new Word("Kui"), // 0xaa
  new Word("Chou"), // 0xab
  new Word("Quan"), // 0xac
  new Word("Fan"), // 0xad
  new Word("Ba"), // 0xae
  new Word("Fan"), // 0xaf
  new Word("Qiu"), // 0xb0
  new Word("Ji"), // 0xb1
  new Word("Cai"), // 0xb2
  new Word("Chuo"), // 0xb3
  new Word("An"), // 0xb4
  new Word("Jie"), // 0xb5
  new Word("Zhuang"), // 0xb6
  new Word("Guang"), // 0xb7
  new Word("Ma"), // 0xb8
  new Word("You"), // 0xb9
  new Word("Kang"), // 0xba
  new Word("Bo"), // 0xbb
  new Word("Hou"), // 0xbc
  new Word("Ya"), // 0xbd
  new Word("Yin"), // 0xbe
  new Word("Huan"), // 0xbf
  new Word("Zhuang"), // 0xc0
  new Word("Yun"), // 0xc1
  new Word("Kuang"), // 0xc2
  new Word("Niu"), // 0xc3
  new Word("Di"), // 0xc4
  new Word("Qing"), // 0xc5
  new Word("Zhong"), // 0xc6
  new Word("Mu"), // 0xc7
  new Word("Bei"), // 0xc8
  new Word("Pi"), // 0xc9
  new Word("Ju"), // 0xca
  new Word("Ni"), // 0xcb
  new Word("Sheng"), // 0xcc
  new Word("Pao"), // 0xcd
  new Word("Xia"), // 0xce
  new Word("Tuo"), // 0xcf
  new Word("Hu"), // 0xd0
  new Word("Ling"), // 0xd1
  new Word("Fei"), // 0xd2
  new Word("Pi"), // 0xd3
  new Word("Ni"), // 0xd4
  new Word("Ao"), // 0xd5
  new Word("You"), // 0xd6
  new Word("Gou"), // 0xd7
  new Word("Yue"), // 0xd8
  new Word("Ju"), // 0xd9
  new Word("Dan"), // 0xda
  new Word("Po"), // 0xdb
  new Word("Gu"), // 0xdc
  new Word("Xian"), // 0xdd
  new Word("Ning"), // 0xde
  new Word("Huan"), // 0xdf
  new Word("Hen"), // 0xe0
  new Word("Jiao"), // 0xe1
  new Word("He"), // 0xe2
  new Word("Zhao"), // 0xe3
  new Word("Ji"), // 0xe4
  new Word("Xun"), // 0xe5
  new Word("Shan"), // 0xe6
  new Word("Ta"), // 0xe7
  new Word("Rong"), // 0xe8
  new Word("Shou"), // 0xe9
  new Word("Tong"), // 0xea
  new Word("Lao"), // 0xeb
  new Word("Du"), // 0xec
  new Word("Xia"), // 0xed
  new Word("Shi"), // 0xee
  new Word("Hua"), // 0xef
  new Word("Zheng"), // 0xf0
  new Word("Yu"), // 0xf1
  new Word("Sun"), // 0xf2
  new Word("Yu"), // 0xf3
  new Word("Bi"), // 0xf4
  new Word("Mang"), // 0xf5
  new Word("Xi"), // 0xf6
  new Word("Juan"), // 0xf7
  new Word("Li"), // 0xf8
  new Word("Xia"), // 0xf9
  new Word("Yin"), // 0xfa
  new Word("Suan"), // 0xfb
  new Word("Lang"), // 0xfc
  new Word("Bei"), // 0xfd
  new Word("Zhi"), // 0xfe
  new Word("Yan") // 0xff
  };
}