/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+73xx (CJK Unified Ideographs).
 */
final class X73 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Sha"), // 0x00
  new Word("Li"), // 0x01
  new Word("Han"), // 0x02
  new Word("Xian"), // 0x03
  new Word("Jing"), // 0x04
  new Word("Pai"), // 0x05
  new Word("Fei"), // 0x06
  new Word("Yao"), // 0x07
  new Word("Ba"), // 0x08
  new Word("Qi"), // 0x09
  new Word("Ni"), // 0x0a
  new Word("Biao"), // 0x0b
  new Word("Yin"), // 0x0c
  new Word("Lai"), // 0x0d
  new Word("Xi"), // 0x0e
  new Word("Jian"), // 0x0f
  new Word("Qiang"), // 0x10
  new Word("Kun"), // 0x11
  new Word("Yan"), // 0x12
  new Word("Guo"), // 0x13
  new Word("Zong"), // 0x14
  new Word("Mi"), // 0x15
  new Word("Chang"), // 0x16
  new Word("Yi"), // 0x17
  new Word("Zhi"), // 0x18
  new Word("Zheng"), // 0x19
  new Word("Ya"), // 0x1a
  new Word("Meng"), // 0x1b
  new Word("Cai"), // 0x1c
  new Word("Cu"), // 0x1d
  new Word("She"), // 0x1e
  new Word("Kari"), // 0x1f
  new Word("Cen"), // 0x20
  new Word("Luo"), // 0x21
  new Word("Hu"), // 0x22
  new Word("Zong"), // 0x23
  new Word("Ji"), // 0x24
  new Word("Wei"), // 0x25
  new Word("Feng"), // 0x26
  new Word("Wo"), // 0x27
  new Word("Yuan"), // 0x28
  new Word("Xing"), // 0x29
  new Word("Zhu"), // 0x2a
  new Word("Mao"), // 0x2b
  new Word("Wei"), // 0x2c
  new Word("Yuan"), // 0x2d
  new Word("Xian"), // 0x2e
  new Word("Tuan"), // 0x2f
  new Word("Ya"), // 0x30
  new Word("Nao"), // 0x31
  new Word("Xie"), // 0x32
  new Word("Jia"), // 0x33
  new Word("Hou"), // 0x34
  new Word("Bian"), // 0x35
  new Word("You"), // 0x36
  new Word("You"), // 0x37
  new Word("Mei"), // 0x38
  new Word("Zha"), // 0x39
  new Word("Yao"), // 0x3a
  new Word("Sun"), // 0x3b
  new Word("Bo"), // 0x3c
  new Word("Ming"), // 0x3d
  new Word("Hua"), // 0x3e
  new Word("Yuan"), // 0x3f
  new Word("Sou"), // 0x40
  new Word("Ma"), // 0x41
  new Word("Yuan"), // 0x42
  new Word("Dai"), // 0x43
  new Word("Yu"), // 0x44
  new Word("Shi"), // 0x45
  new Word("Hao"), // 0x46
  null, // 0x47
  new Word("Yi"), // 0x48
  new Word("Zhen"), // 0x49
  new Word("Chuang"), // 0x4a
  new Word("Hao"), // 0x4b
  new Word("Man"), // 0x4c
  new Word("Jing"), // 0x4d
  new Word("Jiang"), // 0x4e
  new Word("Mu"), // 0x4f
  new Word("Zhang"), // 0x50
  new Word("Chan"), // 0x51
  new Word("Ao"), // 0x52
  new Word("Ao"), // 0x53
  new Word("Hao"), // 0x54
  new Word("Cui"), // 0x55
  new Word("Fen"), // 0x56
  new Word("Jue"), // 0x57
  new Word("Bi"), // 0x58
  new Word("Bi"), // 0x59
  new Word("Huang"), // 0x5a
  new Word("Pu"), // 0x5b
  new Word("Lin"), // 0x5c
  new Word("Yu"), // 0x5d
  new Word("Tong"), // 0x5e
  new Word("Yao"), // 0x5f
  new Word("Liao"), // 0x60
  new Word("Shuo"), // 0x61
  new Word("Xiao"), // 0x62
  new Word("Swu"), // 0x63
  new Word("Ton"), // 0x64
  new Word("Xi"), // 0x65
  new Word("Ge"), // 0x66
  new Word("Juan"), // 0x67
  new Word("Du"), // 0x68
  new Word("Hui"), // 0x69
  new Word("Kuai"), // 0x6a
  new Word("Xian"), // 0x6b
  new Word("Xie"), // 0x6c
  new Word("Ta"), // 0x6d
  new Word("Xian"), // 0x6e
  new Word("Xun"), // 0x6f
  new Word("Ning"), // 0x70
  new Word("Pin"), // 0x71
  new Word("Huo"), // 0x72
  new Word("Nou"), // 0x73
  new Word("Meng"), // 0x74
  new Word("Lie"), // 0x75
  new Word("Nao"), // 0x76
  new Word("Guang"), // 0x77
  new Word("Shou"), // 0x78
  new Word("Lu"), // 0x79
  new Word("Ta"), // 0x7a
  new Word("Xian"), // 0x7b
  new Word("Mi"), // 0x7c
  new Word("Rang"), // 0x7d
  new Word("Huan"), // 0x7e
  new Word("Nao"), // 0x7f
  new Word("Luo"), // 0x80
  new Word("Xian"), // 0x81
  new Word("Qi"), // 0x82
  new Word("Jue"), // 0x83
  new Word("Xuan"), // 0x84
  new Word("Miao"), // 0x85
  new Word("Zi"), // 0x86
  new Word("Lu"), // 0x87
  new Word("Lu"), // 0x88
  new Word("Yu"), // 0x89
  new Word("Su"), // 0x8a
  new Word("Wang"), // 0x8b
  new Word("Qiu"), // 0x8c
  new Word("Ga"), // 0x8d
  new Word("Ding"), // 0x8e
  new Word("Le"), // 0x8f
  new Word("Ba"), // 0x90
  new Word("Ji"), // 0x91
  new Word("Hong"), // 0x92
  new Word("Di"), // 0x93
  new Word("Quan"), // 0x94
  new Word("Gan"), // 0x95
  new Word("Jiu"), // 0x96
  new Word("Yu"), // 0x97
  new Word("Ji"), // 0x98
  new Word("Yu"), // 0x99
  new Word("Yang"), // 0x9a
  new Word("Ma"), // 0x9b
  new Word("Gong"), // 0x9c
  new Word("Wu"), // 0x9d
  new Word("Fu"), // 0x9e
  new Word("Wen"), // 0x9f
  new Word("Jie"), // 0xa0
  new Word("Ya"), // 0xa1
  new Word("Fen"), // 0xa2
  new Word("Bian"), // 0xa3
  new Word("Beng"), // 0xa4
  new Word("Yue"), // 0xa5
  new Word("Jue"), // 0xa6
  new Word("Yun"), // 0xa7
  new Word("Jue"), // 0xa8
  new Word("Wan"), // 0xa9
  new Word("Jian"), // 0xaa
  new Word("Mei"), // 0xab
  new Word("Dan"), // 0xac
  new Word("Pi"), // 0xad
  new Word("Wei"), // 0xae
  new Word("Huan"), // 0xaf
  new Word("Xian"), // 0xb0
  new Word("Qiang"), // 0xb1
  new Word("Ling"), // 0xb2
  new Word("Dai"), // 0xb3
  new Word("Yi"), // 0xb4
  new Word("An"), // 0xb5
  new Word("Ping"), // 0xb6
  new Word("Dian"), // 0xb7
  new Word("Fu"), // 0xb8
  new Word("Xuan"), // 0xb9
  new Word("Xi"), // 0xba
  new Word("Bo"), // 0xbb
  new Word("Ci"), // 0xbc
  new Word("Gou"), // 0xbd
  new Word("Jia"), // 0xbe
  new Word("Shao"), // 0xbf
  new Word("Po"), // 0xc0
  new Word("Ci"), // 0xc1
  new Word("Ke"), // 0xc2
  new Word("Ran"), // 0xc3
  new Word("Sheng"), // 0xc4
  new Word("Shen"), // 0xc5
  new Word("Yi"), // 0xc6
  new Word("Zu"), // 0xc7
  new Word("Jia"), // 0xc8
  new Word("Min"), // 0xc9
  new Word("Shan"), // 0xca
  new Word("Liu"), // 0xcb
  new Word("Bi"), // 0xcc
  new Word("Zhen"), // 0xcd
  new Word("Zhen"), // 0xce
  new Word("Jue"), // 0xcf
  new Word("Fa"), // 0xd0
  new Word("Long"), // 0xd1
  new Word("Jin"), // 0xd2
  new Word("Jiao"), // 0xd3
  new Word("Jian"), // 0xd4
  new Word("Li"), // 0xd5
  new Word("Guang"), // 0xd6
  new Word("Xian"), // 0xd7
  new Word("Zhou"), // 0xd8
  new Word("Gong"), // 0xd9
  new Word("Yan"), // 0xda
  new Word("Xiu"), // 0xdb
  new Word("Yang"), // 0xdc
  new Word("Xu"), // 0xdd
  new Word("Luo"), // 0xde
  new Word("Su"), // 0xdf
  new Word("Zhu"), // 0xe0
  new Word("Qin"), // 0xe1
  new Word("Ken"), // 0xe2
  new Word("Xun"), // 0xe3
  new Word("Bao"), // 0xe4
  new Word("Er"), // 0xe5
  new Word("Xiang"), // 0xe6
  new Word("Yao"), // 0xe7
  new Word("Xia"), // 0xe8
  new Word("Heng"), // 0xe9
  new Word("Gui"), // 0xea
  new Word("Chong"), // 0xeb
  new Word("Xu"), // 0xec
  new Word("Ban"), // 0xed
  new Word("Pei"), // 0xee
  null, // 0xef
  new Word("Dang"), // 0xf0
  new Word("Ei"), // 0xf1
  new Word("Hun"), // 0xf2
  new Word("Wen"), // 0xf3
  new Word("E"), // 0xf4
  new Word("Cheng"), // 0xf5
  new Word("Ti"), // 0xf6
  new Word("Wu"), // 0xf7
  new Word("Wu"), // 0xf8
  new Word("Cheng"), // 0xf9
  new Word("Jun"), // 0xfa
  new Word("Mei"), // 0xfb
  new Word("Bei"), // 0xfc
  new Word("Ting"), // 0xfd
  new Word("Xian"), // 0xfe
  new Word("Chuo") // 0xff
  };
}