/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+74xx (CJK Unified Ideographs).
 */
final class X74 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Han"), // 0x00
  new Word("Xuan"), // 0x01
  new Word("Yan"), // 0x02
  new Word("Qiu"), // 0x03
  new Word("Quan"), // 0x04
  new Word("Lang"), // 0x05
  new Word("Li"), // 0x06
  new Word("Xiu"), // 0x07
  new Word("Fu"), // 0x08
  new Word("Liu"), // 0x09
  new Word("Ye"), // 0x0a
  new Word("Xi"), // 0x0b
  new Word("Ling"), // 0x0c
  new Word("Li"), // 0x0d
  new Word("Jin"), // 0x0e
  new Word("Lian"), // 0x0f
  new Word("Suo"), // 0x10
  new Word("Chiisai"), // 0x11
  null, // 0x12
  new Word("Wan"), // 0x13
  new Word("Dian"), // 0x14
  new Word("Pin"), // 0x15
  new Word("Zhan"), // 0x16
  new Word("Cui"), // 0x17
  new Word("Min"), // 0x18
  new Word("Yu"), // 0x19
  new Word("Ju"), // 0x1a
  new Word("Chen"), // 0x1b
  new Word("Lai"), // 0x1c
  new Word("Wen"), // 0x1d
  new Word("Sheng"), // 0x1e
  new Word("Wei"), // 0x1f
  new Word("Dian"), // 0x20
  new Word("Chu"), // 0x21
  new Word("Zhuo"), // 0x22
  new Word("Pei"), // 0x23
  new Word("Cheng"), // 0x24
  new Word("Hu"), // 0x25
  new Word("Qi"), // 0x26
  new Word("E"), // 0x27
  new Word("Kun"), // 0x28
  new Word("Chang"), // 0x29
  new Word("Qi"), // 0x2a
  new Word("Beng"), // 0x2b
  new Word("Wan"), // 0x2c
  new Word("Lu"), // 0x2d
  new Word("Cong"), // 0x2e
  new Word("Guan"), // 0x2f
  new Word("Yan"), // 0x30
  new Word("Diao"), // 0x31
  new Word("Bei"), // 0x32
  new Word("Lin"), // 0x33
  new Word("Qin"), // 0x34
  new Word("Pi"), // 0x35
  new Word("Pa"), // 0x36
  new Word("Que"), // 0x37
  new Word("Zhuo"), // 0x38
  new Word("Qin"), // 0x39
  new Word("Fa"), // 0x3a
  null, // 0x3b
  new Word("Qiong"), // 0x3c
  new Word("Du"), // 0x3d
  new Word("Jie"), // 0x3e
  new Word("Hun"), // 0x3f
  new Word("Yu"), // 0x40
  new Word("Mao"), // 0x41
  new Word("Mei"), // 0x42
  new Word("Chun"), // 0x43
  new Word("Xuan"), // 0x44
  new Word("Ti"), // 0x45
  new Word("Xing"), // 0x46
  new Word("Dai"), // 0x47
  new Word("Rou"), // 0x48
  new Word("Min"), // 0x49
  new Word("Zhen"), // 0x4a
  new Word("Wei"), // 0x4b
  new Word("Ruan"), // 0x4c
  new Word("Huan"), // 0x4d
  new Word("Jie"), // 0x4e
  new Word("Chuan"), // 0x4f
  new Word("Jian"), // 0x50
  new Word("Zhuan"), // 0x51
  new Word("Yang"), // 0x52
  new Word("Lian"), // 0x53
  new Word("Quan"), // 0x54
  new Word("Xia"), // 0x55
  new Word("Duan"), // 0x56
  new Word("Yuan"), // 0x57
  new Word("Ye"), // 0x58
  new Word("Nao"), // 0x59
  new Word("Hu"), // 0x5a
  new Word("Ying"), // 0x5b
  new Word("Yu"), // 0x5c
  new Word("Huang"), // 0x5d
  new Word("Rui"), // 0x5e
  new Word("Se"), // 0x5f
  new Word("Liu"), // 0x60
  new Word("Shi"), // 0x61
  new Word("Rong"), // 0x62
  new Word("Suo"), // 0x63
  new Word("Yao"), // 0x64
  new Word("Wen"), // 0x65
  new Word("Wu"), // 0x66
  new Word("Jin"), // 0x67
  new Word("Jin"), // 0x68
  new Word("Ying"), // 0x69
  new Word("Ma"), // 0x6a
  new Word("Tao"), // 0x6b
  new Word("Liu"), // 0x6c
  new Word("Tang"), // 0x6d
  new Word("Li"), // 0x6e
  new Word("Lang"), // 0x6f
  new Word("Gui"), // 0x70
  new Word("Zhen"), // 0x71
  new Word("Qiang"), // 0x72
  new Word("Cuo"), // 0x73
  new Word("Jue"), // 0x74
  new Word("Zhao"), // 0x75
  new Word("Yao"), // 0x76
  new Word("Ai"), // 0x77
  new Word("Bin"), // 0x78
  new Word("Tu"), // 0x79
  new Word("Chang"), // 0x7a
  new Word("Kun"), // 0x7b
  new Word("Zhuan"), // 0x7c
  new Word("Cong"), // 0x7d
  new Word("Jin"), // 0x7e
  new Word("Yi"), // 0x7f
  new Word("Cui"), // 0x80
  new Word("Cong"), // 0x81
  new Word("Qi"), // 0x82
  new Word("Li"), // 0x83
  new Word("Ying"), // 0x84
  new Word("Suo"), // 0x85
  new Word("Qiu"), // 0x86
  new Word("Xuan"), // 0x87
  new Word("Ao"), // 0x88
  new Word("Lian"), // 0x89
  new Word("Man"), // 0x8a
  new Word("Zhang"), // 0x8b
  new Word("Yin"), // 0x8c
  null, // 0x8d
  new Word("Ying"), // 0x8e
  new Word("Zhi"), // 0x8f
  new Word("Lu"), // 0x90
  new Word("Wu"), // 0x91
  new Word("Deng"), // 0x92
  new Word("Xiou"), // 0x93
  new Word("Zeng"), // 0x94
  new Word("Xun"), // 0x95
  new Word("Qu"), // 0x96
  new Word("Dang"), // 0x97
  new Word("Lin"), // 0x98
  new Word("Liao"), // 0x99
  new Word("Qiong"), // 0x9a
  new Word("Su"), // 0x9b
  new Word("Huang"), // 0x9c
  new Word("Gui"), // 0x9d
  new Word("Pu"), // 0x9e
  new Word("Jing"), // 0x9f
  new Word("Fan"), // 0xa0
  new Word("Jin"), // 0xa1
  new Word("Liu"), // 0xa2
  new Word("Ji"), // 0xa3
  null, // 0xa4
  new Word("Jing"), // 0xa5
  new Word("Ai"), // 0xa6
  new Word("Bi"), // 0xa7
  new Word("Can"), // 0xa8
  new Word("Qu"), // 0xa9
  new Word("Zao"), // 0xaa
  new Word("Dang"), // 0xab
  new Word("Jiao"), // 0xac
  new Word("Gun"), // 0xad
  new Word("Tan"), // 0xae
  new Word("Hui"), // 0xaf
  new Word("Huan"), // 0xb0
  new Word("Se"), // 0xb1
  new Word("Sui"), // 0xb2
  new Word("Tian"), // 0xb3
  null, // 0xb4
  new Word("Yu"), // 0xb5
  new Word("Jin"), // 0xb6
  new Word("Lu"), // 0xb7
  new Word("Bin"), // 0xb8
  new Word("Shou"), // 0xb9
  new Word("Wen"), // 0xba
  new Word("Zui"), // 0xbb
  new Word("Lan"), // 0xbc
  new Word("Xi"), // 0xbd
  new Word("Ji"), // 0xbe
  new Word("Xuan"), // 0xbf
  new Word("Ruan"), // 0xc0
  new Word("Huo"), // 0xc1
  new Word("Gai"), // 0xc2
  new Word("Lei"), // 0xc3
  new Word("Du"), // 0xc4
  new Word("Li"), // 0xc5
  new Word("Zhi"), // 0xc6
  new Word("Rou"), // 0xc7
  new Word("Li"), // 0xc8
  new Word("Zan"), // 0xc9
  new Word("Qiong"), // 0xca
  new Word("Zhe"), // 0xcb
  new Word("Gui"), // 0xcc
  new Word("Sui"), // 0xcd
  new Word("La"), // 0xce
  new Word("Long"), // 0xcf
  new Word("Lu"), // 0xd0
  new Word("Li"), // 0xd1
  new Word("Zan"), // 0xd2
  new Word("Lan"), // 0xd3
  new Word("Ying"), // 0xd4
  new Word("Mi"), // 0xd5
  new Word("Xiang"), // 0xd6
  new Word("Xi"), // 0xd7
  new Word("Guan"), // 0xd8
  new Word("Dao"), // 0xd9
  new Word("Zan"), // 0xda
  new Word("Huan"), // 0xdb
  new Word("Gua"), // 0xdc
  new Word("Bo"), // 0xdd
  new Word("Die"), // 0xde
  new Word("Bao"), // 0xdf
  new Word("Hu"), // 0xe0
  new Word("Zhi"), // 0xe1
  new Word("Piao"), // 0xe2
  new Word("Ban"), // 0xe3
  new Word("Rang"), // 0xe4
  new Word("Li"), // 0xe5
  new Word("Wa"), // 0xe6
  new Word("Dekaguramu"), // 0xe7
  new Word("Jiang"), // 0xe8
  new Word("Qian"), // 0xe9
  new Word("Fan"), // 0xea
  new Word("Pen"), // 0xeb
  new Word("Fang"), // 0xec
  new Word("Dan"), // 0xed
  new Word("Weng"), // 0xee
  new Word("Ou"), // 0xef
  new Word("Deshiguramu"), // 0xf0
  new Word("Miriguramu"), // 0xf1
  new Word("Thon"), // 0xf2
  new Word("Hu"), // 0xf3
  new Word("Ling"), // 0xf4
  new Word("Yi"), // 0xf5
  new Word("Ping"), // 0xf6
  new Word("Ci"), // 0xf7
  new Word("Hekutogura"), // 0xf8
  new Word("Juan"), // 0xf9
  new Word("Chang"), // 0xfa
  new Word("Chi"), // 0xfb
  new Word("Sarake"), // 0xfc
  new Word("Dang"), // 0xfd
  new Word("Meng"), // 0xfe
  new Word("Pou") // 0xff
  };
}