/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+75xx (CJK Unified Ideographs).
 */
final class X75 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Zhui"), // 0x00
  new Word("Ping"), // 0x01
  new Word("Bian"), // 0x02
  new Word("Zhou"), // 0x03
  new Word("Zhen"), // 0x04
  new Word("Senchigura"), // 0x05
  new Word("Ci"), // 0x06
  new Word("Ying"), // 0x07
  new Word("Qi"), // 0x08
  new Word("Xian"), // 0x09
  new Word("Lou"), // 0x0a
  new Word("Di"), // 0x0b
  new Word("Ou"), // 0x0c
  new Word("Meng"), // 0x0d
  new Word("Zhuan"), // 0x0e
  new Word("Peng"), // 0x0f
  new Word("Lin"), // 0x10
  new Word("Zeng"), // 0x11
  new Word("Wu"), // 0x12
  new Word("Pi"), // 0x13
  new Word("Dan"), // 0x14
  new Word("Weng"), // 0x15
  new Word("Ying"), // 0x16
  new Word("Yan"), // 0x17
  new Word("Gan"), // 0x18
  new Word("Dai"), // 0x19
  new Word("Shen"), // 0x1a
  new Word("Tian"), // 0x1b
  new Word("Tian"), // 0x1c
  new Word("Han"), // 0x1d
  new Word("Chang"), // 0x1e
  new Word("Sheng"), // 0x1f
  new Word("Qing"), // 0x20
  new Word("Sheng"), // 0x21
  new Word("Chan"), // 0x22
  new Word("Chan"), // 0x23
  new Word("Rui"), // 0x24
  new Word("Sheng"), // 0x25
  new Word("Su"), // 0x26
  new Word("Sen"), // 0x27
  new Word("Yong"), // 0x28
  new Word("Shuai"), // 0x29
  new Word("Lu"), // 0x2a
  new Word("Fu"), // 0x2b
  new Word("Yong"), // 0x2c
  new Word("Beng"), // 0x2d
  new Word("Feng"), // 0x2e
  new Word("Ning"), // 0x2f
  new Word("Tian"), // 0x30
  new Word("You"), // 0x31
  new Word("Jia"), // 0x32
  new Word("Shen"), // 0x33
  new Word("Zha"), // 0x34
  new Word("Dian"), // 0x35
  new Word("Fu"), // 0x36
  new Word("Nan"), // 0x37
  new Word("Dian"), // 0x38
  new Word("Ping"), // 0x39
  new Word("Ting"), // 0x3a
  new Word("Hua"), // 0x3b
  new Word("Ting"), // 0x3c
  new Word("Quan"), // 0x3d
  new Word("Zi"), // 0x3e
  new Word("Meng"), // 0x3f
  new Word("Bi"), // 0x40
  new Word("Qi"), // 0x41
  new Word("Liu"), // 0x42
  new Word("Xun"), // 0x43
  new Word("Liu"), // 0x44
  new Word("Chang"), // 0x45
  new Word("Mu"), // 0x46
  new Word("Yun"), // 0x47
  new Word("Fan"), // 0x48
  new Word("Fu"), // 0x49
  new Word("Geng"), // 0x4a
  new Word("Tian"), // 0x4b
  new Word("Jie"), // 0x4c
  new Word("Jie"), // 0x4d
  new Word("Quan"), // 0x4e
  new Word("Wei"), // 0x4f
  new Word("Fu"), // 0x50
  new Word("Tian"), // 0x51
  new Word("Mu"), // 0x52
  new Word("Tap"), // 0x53
  new Word("Pan"), // 0x54
  new Word("Jiang"), // 0x55
  new Word("Wa"), // 0x56
  new Word("Da"), // 0x57
  new Word("Nan"), // 0x58
  new Word("Liu"), // 0x59
  new Word("Ben"), // 0x5a
  new Word("Zhen"), // 0x5b
  new Word("Chu"), // 0x5c
  new Word("Mu"), // 0x5d
  new Word("Mu"), // 0x5e
  new Word("Ce"), // 0x5f
  new Word("Cen"), // 0x60
  new Word("Gai"), // 0x61
  new Word("Bi"), // 0x62
  new Word("Da"), // 0x63
  new Word("Zhi"), // 0x64
  new Word("Lue"), // 0x65
  new Word("Qi"), // 0x66
  new Word("Lue"), // 0x67
  new Word("Pan"), // 0x68
  new Word("Kesa"), // 0x69
  new Word("Fan"), // 0x6a
  new Word("Hua"), // 0x6b
  new Word("Yu"), // 0x6c
  new Word("Yu"), // 0x6d
  new Word("Mu"), // 0x6e
  new Word("Jun"), // 0x6f
  new Word("Yi"), // 0x70
  new Word("Liu"), // 0x71
  new Word("Yu"), // 0x72
  new Word("Die"), // 0x73
  new Word("Chou"), // 0x74
  new Word("Hua"), // 0x75
  new Word("Dang"), // 0x76
  new Word("Chuo"), // 0x77
  new Word("Ji"), // 0x78
  new Word("Wan"), // 0x79
  new Word("Jiang"), // 0x7a
  new Word("Sheng"), // 0x7b
  new Word("Chang"), // 0x7c
  new Word("Tuan"), // 0x7d
  new Word("Lei"), // 0x7e
  new Word("Ji"), // 0x7f
  new Word("Cha"), // 0x80
  new Word("Liu"), // 0x81
  new Word("Tatamu"), // 0x82
  new Word("Tuan"), // 0x83
  new Word("Lin"), // 0x84
  new Word("Jiang"), // 0x85
  new Word("Jiang"), // 0x86
  new Word("Chou"), // 0x87
  new Word("Bo"), // 0x88
  new Word("Die"), // 0x89
  new Word("Die"), // 0x8a
  new Word("Pi"), // 0x8b
  new Word("Nie"), // 0x8c
  new Word("Dan"), // 0x8d
  new Word("Shu"), // 0x8e
  new Word("Shu"), // 0x8f
  new Word("Zhi"), // 0x90
  new Word("Yi"), // 0x91
  new Word("Chuang"), // 0x92
  new Word("Nai"), // 0x93
  new Word("Ding"), // 0x94
  new Word("Bi"), // 0x95
  new Word("Jie"), // 0x96
  new Word("Liao"), // 0x97
  new Word("Gong"), // 0x98
  new Word("Ge"), // 0x99
  new Word("Jiu"), // 0x9a
  new Word("Zhou"), // 0x9b
  new Word("Xia"), // 0x9c
  new Word("Shan"), // 0x9d
  new Word("Xu"), // 0x9e
  new Word("Nue"), // 0x9f
  new Word("Li"), // 0xa0
  new Word("Yang"), // 0xa1
  new Word("Chen"), // 0xa2
  new Word("You"), // 0xa3
  new Word("Ba"), // 0xa4
  new Word("Jie"), // 0xa5
  new Word("Jue"), // 0xa6
  new Word("Zhi"), // 0xa7
  new Word("Xia"), // 0xa8
  new Word("Cui"), // 0xa9
  new Word("Bi"), // 0xaa
  new Word("Yi"), // 0xab
  new Word("Li"), // 0xac
  new Word("Zong"), // 0xad
  new Word("Chuang"), // 0xae
  new Word("Feng"), // 0xaf
  new Word("Zhu"), // 0xb0
  new Word("Pao"), // 0xb1
  new Word("Pi"), // 0xb2
  new Word("Gan"), // 0xb3
  new Word("Ke"), // 0xb4
  new Word("Ci"), // 0xb5
  new Word("Xie"), // 0xb6
  new Word("Qi"), // 0xb7
  new Word("Dan"), // 0xb8
  new Word("Zhen"), // 0xb9
  new Word("Fa"), // 0xba
  new Word("Zhi"), // 0xbb
  new Word("Teng"), // 0xbc
  new Word("Ju"), // 0xbd
  new Word("Ji"), // 0xbe
  new Word("Fei"), // 0xbf
  new Word("Qu"), // 0xc0
  new Word("Dian"), // 0xc1
  new Word("Jia"), // 0xc2
  new Word("Xian"), // 0xc3
  new Word("Cha"), // 0xc4
  new Word("Bing"), // 0xc5
  new Word("Ni"), // 0xc6
  new Word("Zheng"), // 0xc7
  new Word("Yong"), // 0xc8
  new Word("Jing"), // 0xc9
  new Word("Quan"), // 0xca
  new Word("Chong"), // 0xcb
  new Word("Tong"), // 0xcc
  new Word("Yi"), // 0xcd
  new Word("Kai"), // 0xce
  new Word("Wei"), // 0xcf
  new Word("Hui"), // 0xd0
  new Word("Duo"), // 0xd1
  new Word("Yang"), // 0xd2
  new Word("Chi"), // 0xd3
  new Word("Zhi"), // 0xd4
  new Word("Hen"), // 0xd5
  new Word("Ya"), // 0xd6
  new Word("Mei"), // 0xd7
  new Word("Dou"), // 0xd8
  new Word("Jing"), // 0xd9
  new Word("Xiao"), // 0xda
  new Word("Tong"), // 0xdb
  new Word("Tu"), // 0xdc
  new Word("Mang"), // 0xdd
  new Word("Pi"), // 0xde
  new Word("Xiao"), // 0xdf
  new Word("Suan"), // 0xe0
  new Word("Pu"), // 0xe1
  new Word("Li"), // 0xe2
  new Word("Zhi"), // 0xe3
  new Word("Cuo"), // 0xe4
  new Word("Duo"), // 0xe5
  new Word("Wu"), // 0xe6
  new Word("Sha"), // 0xe7
  new Word("Lao"), // 0xe8
  new Word("Shou"), // 0xe9
  new Word("Huan"), // 0xea
  new Word("Xian"), // 0xeb
  new Word("Yi"), // 0xec
  new Word("Peng"), // 0xed
  new Word("Zhang"), // 0xee
  new Word("Guan"), // 0xef
  new Word("Tan"), // 0xf0
  new Word("Fei"), // 0xf1
  new Word("Ma"), // 0xf2
  new Word("Lin"), // 0xf3
  new Word("Chi"), // 0xf4
  new Word("Ji"), // 0xf5
  new Word("Dian"), // 0xf6
  new Word("An"), // 0xf7
  new Word("Chi"), // 0xf8
  new Word("Bi"), // 0xf9
  new Word("Bei"), // 0xfa
  new Word("Min"), // 0xfb
  new Word("Gu"), // 0xfc
  new Word("Dui"), // 0xfd
  new Word("E"), // 0xfe
  new Word("Wei") // 0xff
  };
}