/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+76xx (CJK Unified Ideographs).
 */
final class X76 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Yu"), // 0x00
  new Word("Cui"), // 0x01
  new Word("Ya"), // 0x02
  new Word("Zhu"), // 0x03
  new Word("Cu"), // 0x04
  new Word("Dan"), // 0x05
  new Word("Shen"), // 0x06
  new Word("Zhung"), // 0x07
  new Word("Ji"), // 0x08
  new Word("Yu"), // 0x09
  new Word("Hou"), // 0x0a
  new Word("Feng"), // 0x0b
  new Word("La"), // 0x0c
  new Word("Yang"), // 0x0d
  new Word("Shen"), // 0x0e
  new Word("Tu"), // 0x0f
  new Word("Yu"), // 0x10
  new Word("Gua"), // 0x11
  new Word("Wen"), // 0x12
  new Word("Huan"), // 0x13
  new Word("Ku"), // 0x14
  new Word("Jia"), // 0x15
  new Word("Yin"), // 0x16
  new Word("Yi"), // 0x17
  new Word("Lu"), // 0x18
  new Word("Sao"), // 0x19
  new Word("Jue"), // 0x1a
  new Word("Chi"), // 0x1b
  new Word("Xi"), // 0x1c
  new Word("Guan"), // 0x1d
  new Word("Yi"), // 0x1e
  new Word("Wen"), // 0x1f
  new Word("Ji"), // 0x20
  new Word("Chuang"), // 0x21
  new Word("Ban"), // 0x22
  new Word("Lei"), // 0x23
  new Word("Liu"), // 0x24
  new Word("Chai"), // 0x25
  new Word("Shou"), // 0x26
  new Word("Nue"), // 0x27
  new Word("Dian"), // 0x28
  new Word("Da"), // 0x29
  new Word("Pie"), // 0x2a
  new Word("Tan"), // 0x2b
  new Word("Zhang"), // 0x2c
  new Word("Biao"), // 0x2d
  new Word("Shen"), // 0x2e
  new Word("Cu"), // 0x2f
  new Word("Luo"), // 0x30
  new Word("Yi"), // 0x31
  new Word("Zong"), // 0x32
  new Word("Chou"), // 0x33
  new Word("Zhang"), // 0x34
  new Word("Zhai"), // 0x35
  new Word("Sou"), // 0x36
  new Word("Suo"), // 0x37
  new Word("Que"), // 0x38
  new Word("Diao"), // 0x39
  new Word("Lou"), // 0x3a
  new Word("Lu"), // 0x3b
  new Word("Mo"), // 0x3c
  new Word("Jin"), // 0x3d
  new Word("Yin"), // 0x3e
  new Word("Ying"), // 0x3f
  new Word("Huang"), // 0x40
  new Word("Fu"), // 0x41
  new Word("Liao"), // 0x42
  new Word("Long"), // 0x43
  new Word("Qiao"), // 0x44
  new Word("Liu"), // 0x45
  new Word("Lao"), // 0x46
  new Word("Xian"), // 0x47
  new Word("Fei"), // 0x48
  new Word("Dan"), // 0x49
  new Word("Yin"), // 0x4a
  new Word("He"), // 0x4b
  new Word("Yan"), // 0x4c
  new Word("Ban"), // 0x4d
  new Word("Xian"), // 0x4e
  new Word("Guan"), // 0x4f
  new Word("Guai"), // 0x50
  new Word("Nong"), // 0x51
  new Word("Yu"), // 0x52
  new Word("Wei"), // 0x53
  new Word("Yi"), // 0x54
  new Word("Yong"), // 0x55
  new Word("Pi"), // 0x56
  new Word("Lei"), // 0x57
  new Word("Li"), // 0x58
  new Word("Shu"), // 0x59
  new Word("Dan"), // 0x5a
  new Word("Lin"), // 0x5b
  new Word("Dian"), // 0x5c
  new Word("Lin"), // 0x5d
  new Word("Lai"), // 0x5e
  new Word("Pie"), // 0x5f
  new Word("Ji"), // 0x60
  new Word("Chi"), // 0x61
  new Word("Yang"), // 0x62
  new Word("Xian"), // 0x63
  new Word("Jie"), // 0x64
  new Word("Zheng"), // 0x65
  null, // 0x66
  new Word("Li"), // 0x67
  new Word("Huo"), // 0x68
  new Word("Lai"), // 0x69
  new Word("Shaku"), // 0x6a
  new Word("Dian"), // 0x6b
  new Word("Xian"), // 0x6c
  new Word("Ying"), // 0x6d
  new Word("Yin"), // 0x6e
  new Word("Qu"), // 0x6f
  new Word("Yong"), // 0x70
  new Word("Tan"), // 0x71
  new Word("Dian"), // 0x72
  new Word("Luo"), // 0x73
  new Word("Luan"), // 0x74
  new Word("Luan"), // 0x75
  new Word("Bo"), // 0x76
  null, // 0x77
  new Word("Gui"), // 0x78
  new Word("Po"), // 0x79
  new Word("Fa"), // 0x7a
  new Word("Deng"), // 0x7b
  new Word("Fa"), // 0x7c
  new Word("Bai"), // 0x7d
  new Word("Bai"), // 0x7e
  new Word("Qie"), // 0x7f
  new Word("Bi"), // 0x80
  new Word("Zao"), // 0x81
  new Word("Zao"), // 0x82
  new Word("Mao"), // 0x83
  new Word("De"), // 0x84
  new Word("Pa"), // 0x85
  new Word("Jie"), // 0x86
  new Word("Huang"), // 0x87
  new Word("Gui"), // 0x88
  new Word("Ci"), // 0x89
  new Word("Ling"), // 0x8a
  new Word("Gao"), // 0x8b
  new Word("Mo"), // 0x8c
  new Word("Ji"), // 0x8d
  new Word("Jiao"), // 0x8e
  new Word("Peng"), // 0x8f
  new Word("Gao"), // 0x90
  new Word("Ai"), // 0x91
  new Word("E"), // 0x92
  new Word("Hao"), // 0x93
  new Word("Han"), // 0x94
  new Word("Bi"), // 0x95
  new Word("Wan"), // 0x96
  new Word("Chou"), // 0x97
  new Word("Qian"), // 0x98
  new Word("Xi"), // 0x99
  new Word("Ai"), // 0x9a
  new Word("Jiong"), // 0x9b
  new Word("Hao"), // 0x9c
  new Word("Huang"), // 0x9d
  new Word("Hao"), // 0x9e
  new Word("Ze"), // 0x9f
  new Word("Cui"), // 0xa0
  new Word("Hao"), // 0xa1
  new Word("Xiao"), // 0xa2
  new Word("Ye"), // 0xa3
  new Word("Po"), // 0xa4
  new Word("Hao"), // 0xa5
  new Word("Jiao"), // 0xa6
  new Word("Ai"), // 0xa7
  new Word("Xing"), // 0xa8
  new Word("Huang"), // 0xa9
  new Word("Li"), // 0xaa
  new Word("Piao"), // 0xab
  new Word("He"), // 0xac
  new Word("Jiao"), // 0xad
  new Word("Pi"), // 0xae
  new Word("Gan"), // 0xaf
  new Word("Pao"), // 0xb0
  new Word("Zhou"), // 0xb1
  new Word("Jun"), // 0xb2
  new Word("Qiu"), // 0xb3
  new Word("Cun"), // 0xb4
  new Word("Que"), // 0xb5
  new Word("Zha"), // 0xb6
  new Word("Gu"), // 0xb7
  new Word("Jun"), // 0xb8
  new Word("Jun"), // 0xb9
  new Word("Zhou"), // 0xba
  new Word("Zha"), // 0xbb
  new Word("Gu"), // 0xbc
  new Word("Zhan"), // 0xbd
  new Word("Du"), // 0xbe
  new Word("Min"), // 0xbf
  new Word("Qi"), // 0xc0
  new Word("Ying"), // 0xc1
  new Word("Yu"), // 0xc2
  new Word("Bei"), // 0xc3
  new Word("Zhao"), // 0xc4
  new Word("Zhong"), // 0xc5
  new Word("Pen"), // 0xc6
  new Word("He"), // 0xc7
  new Word("Ying"), // 0xc8
  new Word("He"), // 0xc9
  new Word("Yi"), // 0xca
  new Word("Bo"), // 0xcb
  new Word("Wan"), // 0xcc
  new Word("He"), // 0xcd
  new Word("Ang"), // 0xce
  new Word("Zhan"), // 0xcf
  new Word("Yan"), // 0xd0
  new Word("Jian"), // 0xd1
  new Word("He"), // 0xd2
  new Word("Yu"), // 0xd3
  new Word("Kui"), // 0xd4
  new Word("Fan"), // 0xd5
  new Word("Gai"), // 0xd6
  new Word("Dao"), // 0xd7
  new Word("Pan"), // 0xd8
  new Word("Fu"), // 0xd9
  new Word("Qiu"), // 0xda
  new Word("Sheng"), // 0xdb
  new Word("Dao"), // 0xdc
  new Word("Lu"), // 0xdd
  new Word("Zhan"), // 0xde
  new Word("Meng"), // 0xdf
  new Word("Li"), // 0xe0
  new Word("Jin"), // 0xe1
  new Word("Xu"), // 0xe2
  new Word("Jian"), // 0xe3
  new Word("Pan"), // 0xe4
  new Word("Guan"), // 0xe5
  new Word("An"), // 0xe6
  new Word("Lu"), // 0xe7
  new Word("Shu"), // 0xe8
  new Word("Zhou"), // 0xe9
  new Word("Dang"), // 0xea
  new Word("An"), // 0xeb
  new Word("Gu"), // 0xec
  new Word("Li"), // 0xed
  new Word("Mu"), // 0xee
  new Word("Cheng"), // 0xef
  new Word("Gan"), // 0xf0
  new Word("Xu"), // 0xf1
  new Word("Mang"), // 0xf2
  new Word("Mang"), // 0xf3
  new Word("Zhi"), // 0xf4
  new Word("Qi"), // 0xf5
  new Word("Ruan"), // 0xf6
  new Word("Tian"), // 0xf7
  new Word("Xiang"), // 0xf8
  new Word("Dun"), // 0xf9
  new Word("Xin"), // 0xfa
  new Word("Xi"), // 0xfb
  new Word("Pan"), // 0xfc
  new Word("Feng"), // 0xfd
  new Word("Dun"), // 0xfe
  new Word("Min") // 0xff
  };
}