/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+77xx (CJK Unified Ideographs).
 */
final class X77 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Ming"), // 0x00
  new Word("Sheng"), // 0x01
  new Word("Shi"), // 0x02
  new Word("Yun"), // 0x03
  new Word("Mian"), // 0x04
  new Word("Pan"), // 0x05
  new Word("Fang"), // 0x06
  new Word("Miao"), // 0x07
  new Word("Dan"), // 0x08
  new Word("Mei"), // 0x09
  new Word("Mao"), // 0x0a
  new Word("Kan"), // 0x0b
  new Word("Xian"), // 0x0c
  new Word("Ou"), // 0x0d
  new Word("Shi"), // 0x0e
  new Word("Yang"), // 0x0f
  new Word("Zheng"), // 0x10
  new Word("Yao"), // 0x11
  new Word("Shen"), // 0x12
  new Word("Huo"), // 0x13
  new Word("Da"), // 0x14
  new Word("Zhen"), // 0x15
  new Word("Kuang"), // 0x16
  new Word("Ju"), // 0x17
  new Word("Shen"), // 0x18
  new Word("Chi"), // 0x19
  new Word("Sheng"), // 0x1a
  new Word("Mei"), // 0x1b
  new Word("Mo"), // 0x1c
  new Word("Zhu"), // 0x1d
  new Word("Zhen"), // 0x1e
  new Word("Zhen"), // 0x1f
  new Word("Mian"), // 0x20
  new Word("Di"), // 0x21
  new Word("Yuan"), // 0x22
  new Word("Die"), // 0x23
  new Word("Yi"), // 0x24
  new Word("Zi"), // 0x25
  new Word("Zi"), // 0x26
  new Word("Chao"), // 0x27
  new Word("Zha"), // 0x28
  new Word("Xuan"), // 0x29
  new Word("Bing"), // 0x2a
  new Word("Mi"), // 0x2b
  new Word("Long"), // 0x2c
  new Word("Sui"), // 0x2d
  new Word("Dong"), // 0x2e
  new Word("Mi"), // 0x2f
  new Word("Die"), // 0x30
  new Word("Yi"), // 0x31
  new Word("Er"), // 0x32
  new Word("Ming"), // 0x33
  new Word("Xuan"), // 0x34
  new Word("Chi"), // 0x35
  new Word("Kuang"), // 0x36
  new Word("Juan"), // 0x37
  new Word("Mou"), // 0x38
  new Word("Zhen"), // 0x39
  new Word("Tiao"), // 0x3a
  new Word("Yang"), // 0x3b
  new Word("Yan"), // 0x3c
  new Word("Mo"), // 0x3d
  new Word("Zhong"), // 0x3e
  new Word("Mai"), // 0x3f
  new Word("Zhao"), // 0x40
  new Word("Zheng"), // 0x41
  new Word("Mei"), // 0x42
  new Word("Jun"), // 0x43
  new Word("Shao"), // 0x44
  new Word("Han"), // 0x45
  new Word("Huan"), // 0x46
  new Word("Di"), // 0x47
  new Word("Cheng"), // 0x48
  new Word("Cuo"), // 0x49
  new Word("Juan"), // 0x4a
  new Word("E"), // 0x4b
  new Word("Wan"), // 0x4c
  new Word("Xian"), // 0x4d
  new Word("Xi"), // 0x4e
  new Word("Kun"), // 0x4f
  new Word("Lai"), // 0x50
  new Word("Jian"), // 0x51
  new Word("Shan"), // 0x52
  new Word("Tian"), // 0x53
  new Word("Hun"), // 0x54
  new Word("Wan"), // 0x55
  new Word("Ling"), // 0x56
  new Word("Shi"), // 0x57
  new Word("Qiong"), // 0x58
  new Word("Lie"), // 0x59
  new Word("Yai"), // 0x5a
  new Word("Jing"), // 0x5b
  new Word("Zheng"), // 0x5c
  new Word("Li"), // 0x5d
  new Word("Lai"), // 0x5e
  new Word("Sui"), // 0x5f
  new Word("Juan"), // 0x60
  new Word("Shui"), // 0x61
  new Word("Sui"), // 0x62
  new Word("Du"), // 0x63
  new Word("Bi"), // 0x64
  new Word("Bi"), // 0x65
  new Word("Mu"), // 0x66
  new Word("Hun"), // 0x67
  new Word("Ni"), // 0x68
  new Word("Lu"), // 0x69
  new Word("Yi"), // 0x6a
  new Word("Jie"), // 0x6b
  new Word("Cai"), // 0x6c
  new Word("Zhou"), // 0x6d
  new Word("Yu"), // 0x6e
  new Word("Hun"), // 0x6f
  new Word("Ma"), // 0x70
  new Word("Xia"), // 0x71
  new Word("Xing"), // 0x72
  new Word("Xi"), // 0x73
  new Word("Gun"), // 0x74
  new Word("Cai"), // 0x75
  new Word("Chun"), // 0x76
  new Word("Jian"), // 0x77
  new Word("Mei"), // 0x78
  new Word("Du"), // 0x79
  new Word("Hou"), // 0x7a
  new Word("Xuan"), // 0x7b
  new Word("Ti"), // 0x7c
  new Word("Kui"), // 0x7d
  new Word("Gao"), // 0x7e
  new Word("Rui"), // 0x7f
  new Word("Mou"), // 0x80
  new Word("Xu"), // 0x81
  new Word("Fa"), // 0x82
  new Word("Wen"), // 0x83
  new Word("Miao"), // 0x84
  new Word("Chou"), // 0x85
  new Word("Kui"), // 0x86
  new Word("Mi"), // 0x87
  new Word("Weng"), // 0x88
  new Word("Kou"), // 0x89
  new Word("Dang"), // 0x8a
  new Word("Chen"), // 0x8b
  new Word("Ke"), // 0x8c
  new Word("Sou"), // 0x8d
  new Word("Xia"), // 0x8e
  new Word("Qiong"), // 0x8f
  new Word("Mao"), // 0x90
  new Word("Ming"), // 0x91
  new Word("Man"), // 0x92
  new Word("Shui"), // 0x93
  new Word("Ze"), // 0x94
  new Word("Zhang"), // 0x95
  new Word("Yi"), // 0x96
  new Word("Diao"), // 0x97
  new Word("Ou"), // 0x98
  new Word("Mo"), // 0x99
  new Word("Shun"), // 0x9a
  new Word("Cong"), // 0x9b
  new Word("Lou"), // 0x9c
  new Word("Chi"), // 0x9d
  new Word("Man"), // 0x9e
  new Word("Piao"), // 0x9f
  new Word("Cheng"), // 0xa0
  new Word("Ji"), // 0xa1
  new Word("Meng"), // 0xa2
  null, // 0xa3
  new Word("Run"), // 0xa4
  new Word("Pie"), // 0xa5
  new Word("Xi"), // 0xa6
  new Word("Qiao"), // 0xa7
  new Word("Pu"), // 0xa8
  new Word("Zhu"), // 0xa9
  new Word("Deng"), // 0xaa
  new Word("Shen"), // 0xab
  new Word("Shun"), // 0xac
  new Word("Liao"), // 0xad
  new Word("Che"), // 0xae
  new Word("Xian"), // 0xaf
  new Word("Kan"), // 0xb0
  new Word("Ye"), // 0xb1
  new Word("Xu"), // 0xb2
  new Word("Tong"), // 0xb3
  new Word("Mou"), // 0xb4
  new Word("Lin"), // 0xb5
  new Word("Kui"), // 0xb6
  new Word("Xian"), // 0xb7
  new Word("Ye"), // 0xb8
  new Word("Ai"), // 0xb9
  new Word("Hui"), // 0xba
  new Word("Zhan"), // 0xbb
  new Word("Jian"), // 0xbc
  new Word("Gu"), // 0xbd
  new Word("Zhao"), // 0xbe
  new Word("Qu"), // 0xbf
  new Word("Wei"), // 0xc0
  new Word("Chou"), // 0xc1
  new Word("Sao"), // 0xc2
  new Word("Ning"), // 0xc3
  new Word("Xun"), // 0xc4
  new Word("Yao"), // 0xc5
  new Word("Huo"), // 0xc6
  new Word("Meng"), // 0xc7
  new Word("Mian"), // 0xc8
  new Word("Bin"), // 0xc9
  new Word("Mian"), // 0xca
  new Word("Li"), // 0xcb
  new Word("Kuang"), // 0xcc
  new Word("Jue"), // 0xcd
  new Word("Xuan"), // 0xce
  new Word("Mian"), // 0xcf
  new Word("Huo"), // 0xd0
  new Word("Lu"), // 0xd1
  new Word("Meng"), // 0xd2
  new Word("Long"), // 0xd3
  new Word("Guan"), // 0xd4
  new Word("Man"), // 0xd5
  new Word("Xi"), // 0xd6
  new Word("Chu"), // 0xd7
  new Word("Tang"), // 0xd8
  new Word("Kan"), // 0xd9
  new Word("Zhu"), // 0xda
  new Word("Mao"), // 0xdb
  new Word("Jin"), // 0xdc
  new Word("Lin"), // 0xdd
  new Word("Yu"), // 0xde
  new Word("Shuo"), // 0xdf
  new Word("Ce"), // 0xe0
  new Word("Jue"), // 0xe1
  new Word("Shi"), // 0xe2
  new Word("Yi"), // 0xe3
  new Word("Shen"), // 0xe4
  new Word("Zhi"), // 0xe5
  new Word("Hou"), // 0xe6
  new Word("Shen"), // 0xe7
  new Word("Ying"), // 0xe8
  new Word("Ju"), // 0xe9
  new Word("Zhou"), // 0xea
  new Word("Jiao"), // 0xeb
  new Word("Cuo"), // 0xec
  new Word("Duan"), // 0xed
  new Word("Ai"), // 0xee
  new Word("Jiao"), // 0xef
  new Word("Zeng"), // 0xf0
  new Word("Huo"), // 0xf1
  new Word("Bai"), // 0xf2
  new Word("Shi"), // 0xf3
  new Word("Ding"), // 0xf4
  new Word("Qi"), // 0xf5
  new Word("Ji"), // 0xf6
  new Word("Zi"), // 0xf7
  new Word("Gan"), // 0xf8
  new Word("Wu"), // 0xf9
  new Word("Tuo"), // 0xfa
  new Word("Ku"), // 0xfb
  new Word("Qiang"), // 0xfc
  new Word("Xi"), // 0xfd
  new Word("Fan"), // 0xfe
  new Word("Kuang") // 0xff
  };
}