/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+79xx (CJK Unified Ideographs).
 */
final class X79 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Tani"), // 0x00
  new Word("Jiao"), // 0x01
  null, // 0x02
  new Word("Zhang"), // 0x03
  new Word("Qiao"), // 0x04
  new Word("Dun"), // 0x05
  new Word("Xian"), // 0x06
  new Word("Yu"), // 0x07
  new Word("Zhui"), // 0x08
  new Word("He"), // 0x09
  new Word("Huo"), // 0x0a
  new Word("Zhai"), // 0x0b
  new Word("Lei"), // 0x0c
  new Word("Ke"), // 0x0d
  new Word("Chu"), // 0x0e
  new Word("Ji"), // 0x0f
  new Word("Que"), // 0x10
  new Word("Dang"), // 0x11
  new Word("Yi"), // 0x12
  new Word("Jiang"), // 0x13
  new Word("Pi"), // 0x14
  new Word("Pi"), // 0x15
  new Word("Yu"), // 0x16
  new Word("Pin"), // 0x17
  new Word("Qi"), // 0x18
  new Word("Ai"), // 0x19
  new Word("Kai"), // 0x1a
  new Word("Jian"), // 0x1b
  new Word("Yu"), // 0x1c
  new Word("Ruan"), // 0x1d
  new Word("Meng"), // 0x1e
  new Word("Pao"), // 0x1f
  new Word("Ci"), // 0x20
  null, // 0x21
  null, // 0x22
  new Word("Mie"), // 0x23
  new Word("Ca"), // 0x24
  new Word("Xian"), // 0x25
  new Word("Kuang"), // 0x26
  new Word("Lei"), // 0x27
  new Word("Lei"), // 0x28
  new Word("Zhi"), // 0x29
  new Word("Li"), // 0x2a
  new Word("Li"), // 0x2b
  new Word("Fan"), // 0x2c
  new Word("Que"), // 0x2d
  new Word("Pao"), // 0x2e
  new Word("Ying"), // 0x2f
  new Word("Li"), // 0x30
  new Word("Long"), // 0x31
  new Word("Long"), // 0x32
  new Word("Mo"), // 0x33
  new Word("Bo"), // 0x34
  new Word("Shuang"), // 0x35
  new Word("Guan"), // 0x36
  new Word("Lan"), // 0x37
  new Word("Zan"), // 0x38
  new Word("Yan"), // 0x39
  new Word("Shi"), // 0x3a
  new Word("Shi"), // 0x3b
  new Word("Li"), // 0x3c
  new Word("Reng"), // 0x3d
  new Word("She"), // 0x3e
  new Word("Yue"), // 0x3f
  new Word("Si"), // 0x40
  new Word("Qi"), // 0x41
  new Word("Ta"), // 0x42
  new Word("Ma"), // 0x43
  new Word("Xie"), // 0x44
  new Word("Xian"), // 0x45
  new Word("Xian"), // 0x46
  new Word("Zhi"), // 0x47
  new Word("Qi"), // 0x48
  new Word("Zhi"), // 0x49
  new Word("Beng"), // 0x4a
  new Word("Dui"), // 0x4b
  new Word("Zhong"), // 0x4c
  null, // 0x4d
  new Word("Yi"), // 0x4e
  new Word("Shi"), // 0x4f
  new Word("You"), // 0x50
  new Word("Zhi"), // 0x51
  new Word("Tiao"), // 0x52
  new Word("Fu"), // 0x53
  new Word("Fu"), // 0x54
  new Word("Mi"), // 0x55
  new Word("Zu"), // 0x56
  new Word("Zhi"), // 0x57
  new Word("Suan"), // 0x58
  new Word("Mei"), // 0x59
  new Word("Zuo"), // 0x5a
  new Word("Qu"), // 0x5b
  new Word("Hu"), // 0x5c
  new Word("Zhu"), // 0x5d
  new Word("Shen"), // 0x5e
  new Word("Sui"), // 0x5f
  new Word("Ci"), // 0x60
  new Word("Chai"), // 0x61
  new Word("Mi"), // 0x62
  new Word("Lu"), // 0x63
  new Word("Yu"), // 0x64
  new Word("Xiang"), // 0x65
  new Word("Wu"), // 0x66
  new Word("Tiao"), // 0x67
  new Word("Piao"), // 0x68
  new Word("Zhu"), // 0x69
  new Word("Gui"), // 0x6a
  new Word("Xia"), // 0x6b
  new Word("Zhi"), // 0x6c
  new Word("Ji"), // 0x6d
  new Word("Gao"), // 0x6e
  new Word("Zhen"), // 0x6f
  new Word("Gao"), // 0x70
  new Word("Shui"), // 0x71
  new Word("Jin"), // 0x72
  new Word("Chen"), // 0x73
  new Word("Gai"), // 0x74
  new Word("Kun"), // 0x75
  new Word("Di"), // 0x76
  new Word("Dao"), // 0x77
  new Word("Huo"), // 0x78
  new Word("Tao"), // 0x79
  new Word("Qi"), // 0x7a
  new Word("Gu"), // 0x7b
  new Word("Guan"), // 0x7c
  new Word("Zui"), // 0x7d
  new Word("Ling"), // 0x7e
  new Word("Lu"), // 0x7f
  new Word("Bing"), // 0x80
  new Word("Jin"), // 0x81
  new Word("Dao"), // 0x82
  new Word("Zhi"), // 0x83
  new Word("Lu"), // 0x84
  new Word("Shan"), // 0x85
  new Word("Bei"), // 0x86
  new Word("Zhe"), // 0x87
  new Word("Hui"), // 0x88
  new Word("You"), // 0x89
  new Word("Xi"), // 0x8a
  new Word("Yin"), // 0x8b
  new Word("Zi"), // 0x8c
  new Word("Huo"), // 0x8d
  new Word("Zhen"), // 0x8e
  new Word("Fu"), // 0x8f
  new Word("Yuan"), // 0x90
  new Word("Wu"), // 0x91
  new Word("Xian"), // 0x92
  new Word("Yang"), // 0x93
  new Word("Ti"), // 0x94
  new Word("Yi"), // 0x95
  new Word("Mei"), // 0x96
  new Word("Si"), // 0x97
  new Word("Di"), // 0x98
  null, // 0x99
  new Word("Zhuo"), // 0x9a
  new Word("Zhen"), // 0x9b
  new Word("Yong"), // 0x9c
  new Word("Ji"), // 0x9d
  new Word("Gao"), // 0x9e
  new Word("Tang"), // 0x9f
  new Word("Si"), // 0xa0
  new Word("Ma"), // 0xa1
  new Word("Ta"), // 0xa2
  null, // 0xa3
  new Word("Xuan"), // 0xa4
  new Word("Qi"), // 0xa5
  new Word("Yu"), // 0xa6
  new Word("Xi"), // 0xa7
  new Word("Ji"), // 0xa8
  new Word("Si"), // 0xa9
  new Word("Chan"), // 0xaa
  new Word("Tan"), // 0xab
  new Word("Kuai"), // 0xac
  new Word("Sui"), // 0xad
  new Word("Li"), // 0xae
  new Word("Nong"), // 0xaf
  new Word("Ni"), // 0xb0
  new Word("Dao"), // 0xb1
  new Word("Li"), // 0xb2
  new Word("Rang"), // 0xb3
  new Word("Yue"), // 0xb4
  new Word("Ti"), // 0xb5
  new Word("Zan"), // 0xb6
  new Word("Lei"), // 0xb7
  new Word("Rou"), // 0xb8
  new Word("Yu"), // 0xb9
  new Word("Yu"), // 0xba
  new Word("Chi"), // 0xbb
  new Word("Xie"), // 0xbc
  new Word("Qin"), // 0xbd
  new Word("He"), // 0xbe
  new Word("Tu"), // 0xbf
  new Word("Xiu"), // 0xc0
  new Word("Si"), // 0xc1
  new Word("Ren"), // 0xc2
  new Word("Tu"), // 0xc3
  new Word("Zi"), // 0xc4
  new Word("Cha"), // 0xc5
  new Word("Gan"), // 0xc6
  new Word("Yi"), // 0xc7
  new Word("Xian"), // 0xc8
  new Word("Bing"), // 0xc9
  new Word("Nian"), // 0xca
  new Word("Qiu"), // 0xcb
  new Word("Qiu"), // 0xcc
  new Word("Chong"), // 0xcd
  new Word("Fen"), // 0xce
  new Word("Hao"), // 0xcf
  new Word("Yun"), // 0xd0
  new Word("Ke"), // 0xd1
  new Word("Miao"), // 0xd2
  new Word("Zhi"), // 0xd3
  new Word("Geng"), // 0xd4
  new Word("Bi"), // 0xd5
  new Word("Zhi"), // 0xd6
  new Word("Yu"), // 0xd7
  new Word("Mi"), // 0xd8
  new Word("Ku"), // 0xd9
  new Word("Ban"), // 0xda
  new Word("Pi"), // 0xdb
  new Word("Ni"), // 0xdc
  new Word("Li"), // 0xdd
  new Word("You"), // 0xde
  new Word("Zu"), // 0xdf
  new Word("Pi"), // 0xe0
  new Word("Ba"), // 0xe1
  new Word("Ling"), // 0xe2
  new Word("Mo"), // 0xe3
  new Word("Cheng"), // 0xe4
  new Word("Nian"), // 0xe5
  new Word("Qin"), // 0xe6
  new Word("Yang"), // 0xe7
  new Word("Zuo"), // 0xe8
  new Word("Zhi"), // 0xe9
  new Word("Zhi"), // 0xea
  new Word("Shu"), // 0xeb
  new Word("Ju"), // 0xec
  new Word("Zi"), // 0xed
  new Word("Huo"), // 0xee
  new Word("Ji"), // 0xef
  new Word("Cheng"), // 0xf0
  new Word("Tong"), // 0xf1
  new Word("Zhi"), // 0xf2
  new Word("Huo"), // 0xf3
  new Word("He"), // 0xf4
  new Word("Yin"), // 0xf5
  new Word("Zi"), // 0xf6
  new Word("Zhi"), // 0xf7
  new Word("Jie"), // 0xf8
  new Word("Ren"), // 0xf9
  new Word("Du"), // 0xfa
  new Word("Yi"), // 0xfb
  new Word("Zhu"), // 0xfc
  new Word("Hui"), // 0xfd
  new Word("Nong"), // 0xfe
  new Word("Fu") // 0xff
  };
}