/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+7Axx (CJK Unified Ideographs).
 */
final class X7a extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Xi"), // 0x00
  new Word("Kao"), // 0x01
  new Word("Lang"), // 0x02
  new Word("Fu"), // 0x03
  new Word("Ze"), // 0x04
  new Word("Shui"), // 0x05
  new Word("Lu"), // 0x06
  new Word("Kun"), // 0x07
  new Word("Gan"), // 0x08
  new Word("Geng"), // 0x09
  new Word("Ti"), // 0x0a
  new Word("Cheng"), // 0x0b
  new Word("Tu"), // 0x0c
  new Word("Shao"), // 0x0d
  new Word("Shui"), // 0x0e
  new Word("Ya"), // 0x0f
  new Word("Lun"), // 0x10
  new Word("Lu"), // 0x11
  new Word("Gu"), // 0x12
  new Word("Zuo"), // 0x13
  new Word("Ren"), // 0x14
  new Word("Zhun"), // 0x15
  new Word("Bang"), // 0x16
  new Word("Bai"), // 0x17
  new Word("Ji"), // 0x18
  new Word("Zhi"), // 0x19
  new Word("Zhi"), // 0x1a
  new Word("Kun"), // 0x1b
  new Word("Leng"), // 0x1c
  new Word("Peng"), // 0x1d
  new Word("Ke"), // 0x1e
  new Word("Bing"), // 0x1f
  new Word("Chou"), // 0x20
  new Word("Zu"), // 0x21
  new Word("Yu"), // 0x22
  new Word("Su"), // 0x23
  new Word("Lue"), // 0x24
  null, // 0x25
  new Word("Yi"), // 0x26
  new Word("Xi"), // 0x27
  new Word("Bian"), // 0x28
  new Word("Ji"), // 0x29
  new Word("Fu"), // 0x2a
  new Word("Bi"), // 0x2b
  new Word("Nuo"), // 0x2c
  new Word("Jie"), // 0x2d
  new Word("Zhong"), // 0x2e
  new Word("Zong"), // 0x2f
  new Word("Xu"), // 0x30
  new Word("Cheng"), // 0x31
  new Word("Dao"), // 0x32
  new Word("Wen"), // 0x33
  new Word("Lian"), // 0x34
  new Word("Zi"), // 0x35
  new Word("Yu"), // 0x36
  new Word("Ji"), // 0x37
  new Word("Xu"), // 0x38
  new Word("Zhen"), // 0x39
  new Word("Zhi"), // 0x3a
  new Word("Dao"), // 0x3b
  new Word("Jia"), // 0x3c
  new Word("Ji"), // 0x3d
  new Word("Gao"), // 0x3e
  new Word("Gao"), // 0x3f
  new Word("Gu"), // 0x40
  new Word("Rong"), // 0x41
  new Word("Sui"), // 0x42
  new Word("You"), // 0x43
  new Word("Ji"), // 0x44
  new Word("Kang"), // 0x45
  new Word("Mu"), // 0x46
  new Word("Shan"), // 0x47
  new Word("Men"), // 0x48
  new Word("Zhi"), // 0x49
  new Word("Ji"), // 0x4a
  new Word("Lu"), // 0x4b
  new Word("Su"), // 0x4c
  new Word("Ji"), // 0x4d
  new Word("Ying"), // 0x4e
  new Word("Wen"), // 0x4f
  new Word("Qiu"), // 0x50
  new Word("Se"), // 0x51
  null, // 0x52
  new Word("Yi"), // 0x53
  new Word("Huang"), // 0x54
  new Word("Qie"), // 0x55
  new Word("Ji"), // 0x56
  new Word("Sui"), // 0x57
  new Word("Xiao"), // 0x58
  new Word("Pu"), // 0x59
  new Word("Jiao"), // 0x5a
  new Word("Zhuo"), // 0x5b
  new Word("Tong"), // 0x5c
  new Word("Sai"), // 0x5d
  new Word("Lu"), // 0x5e
  new Word("Sui"), // 0x5f
  new Word("Nong"), // 0x60
  new Word("Se"), // 0x61
  new Word("Hui"), // 0x62
  new Word("Rang"), // 0x63
  new Word("Nuo"), // 0x64
  new Word("Yu"), // 0x65
  new Word("Bin"), // 0x66
  new Word("Ji"), // 0x67
  new Word("Tui"), // 0x68
  new Word("Wen"), // 0x69
  new Word("Cheng"), // 0x6a
  new Word("Huo"), // 0x6b
  new Word("Gong"), // 0x6c
  new Word("Lu"), // 0x6d
  new Word("Biao"), // 0x6e
  null, // 0x6f
  new Word("Rang"), // 0x70
  new Word("Zhuo"), // 0x71
  new Word("Li"), // 0x72
  new Word("Zan"), // 0x73
  new Word("Xue"), // 0x74
  new Word("Wa"), // 0x75
  new Word("Jiu"), // 0x76
  new Word("Qiong"), // 0x77
  new Word("Xi"), // 0x78
  new Word("Qiong"), // 0x79
  new Word("Kong"), // 0x7a
  new Word("Yu"), // 0x7b
  new Word("Sen"), // 0x7c
  new Word("Jing"), // 0x7d
  new Word("Yao"), // 0x7e
  new Word("Chuan"), // 0x7f
  new Word("Zhun"), // 0x80
  new Word("Tu"), // 0x81
  new Word("Lao"), // 0x82
  new Word("Qie"), // 0x83
  new Word("Zhai"), // 0x84
  new Word("Yao"), // 0x85
  new Word("Bian"), // 0x86
  new Word("Bao"), // 0x87
  new Word("Yao"), // 0x88
  new Word("Bing"), // 0x89
  new Word("Wa"), // 0x8a
  new Word("Zhu"), // 0x8b
  new Word("Jiao"), // 0x8c
  new Word("Qiao"), // 0x8d
  new Word("Diao"), // 0x8e
  new Word("Wu"), // 0x8f
  new Word("Gui"), // 0x90
  new Word("Yao"), // 0x91
  new Word("Zhi"), // 0x92
  new Word("Chuang"), // 0x93
  new Word("Yao"), // 0x94
  new Word("Tiao"), // 0x95
  new Word("Jiao"), // 0x96
  new Word("Chuang"), // 0x97
  new Word("Jiong"), // 0x98
  new Word("Xiao"), // 0x99
  new Word("Cheng"), // 0x9a
  new Word("Kou"), // 0x9b
  new Word("Cuan"), // 0x9c
  new Word("Wo"), // 0x9d
  new Word("Dan"), // 0x9e
  new Word("Ku"), // 0x9f
  new Word("Ke"), // 0xa0
  new Word("Zhui"), // 0xa1
  new Word("Xu"), // 0xa2
  new Word("Su"), // 0xa3
  new Word("Guan"), // 0xa4
  new Word("Kui"), // 0xa5
  new Word("Dou"), // 0xa6
  null, // 0xa7
  new Word("Yin"), // 0xa8
  new Word("Wo"), // 0xa9
  new Word("Wa"), // 0xaa
  new Word("Ya"), // 0xab
  new Word("Yu"), // 0xac
  new Word("Ju"), // 0xad
  new Word("Qiong"), // 0xae
  new Word("Yao"), // 0xaf
  new Word("Yao"), // 0xb0
  new Word("Tiao"), // 0xb1
  new Word("Chao"), // 0xb2
  new Word("Yu"), // 0xb3
  new Word("Tian"), // 0xb4
  new Word("Diao"), // 0xb5
  new Word("Ju"), // 0xb6
  new Word("Liao"), // 0xb7
  new Word("Xi"), // 0xb8
  new Word("Wu"), // 0xb9
  new Word("Kui"), // 0xba
  new Word("Chuang"), // 0xbb
  new Word("Zhao"), // 0xbc
  null, // 0xbd
  new Word("Kuan"), // 0xbe
  new Word("Long"), // 0xbf
  new Word("Cheng"), // 0xc0
  new Word("Cui"), // 0xc1
  new Word("Piao"), // 0xc2
  new Word("Zao"), // 0xc3
  new Word("Cuan"), // 0xc4
  new Word("Qiao"), // 0xc5
  new Word("Qiong"), // 0xc6
  new Word("Dou"), // 0xc7
  new Word("Zao"), // 0xc8
  new Word("Long"), // 0xc9
  new Word("Qie"), // 0xca
  new Word("Li"), // 0xcb
  new Word("Chu"), // 0xcc
  new Word("Shi"), // 0xcd
  new Word("Fou"), // 0xce
  new Word("Qian"), // 0xcf
  new Word("Chu"), // 0xd0
  new Word("Hong"), // 0xd1
  new Word("Qi"), // 0xd2
  new Word("Qian"), // 0xd3
  new Word("Gong"), // 0xd4
  new Word("Shi"), // 0xd5
  new Word("Shu"), // 0xd6
  new Word("Miao"), // 0xd7
  new Word("Ju"), // 0xd8
  new Word("Zhan"), // 0xd9
  new Word("Zhu"), // 0xda
  new Word("Ling"), // 0xdb
  new Word("Long"), // 0xdc
  new Word("Bing"), // 0xdd
  new Word("Jing"), // 0xde
  new Word("Jing"), // 0xdf
  new Word("Zhang"), // 0xe0
  new Word("Yi"), // 0xe1
  new Word("Si"), // 0xe2
  new Word("Jun"), // 0xe3
  new Word("Hong"), // 0xe4
  new Word("Tong"), // 0xe5
  new Word("Song"), // 0xe6
  new Word("Jing"), // 0xe7
  new Word("Diao"), // 0xe8
  new Word("Yi"), // 0xe9
  new Word("Shu"), // 0xea
  new Word("Jing"), // 0xeb
  new Word("Qu"), // 0xec
  new Word("Jie"), // 0xed
  new Word("Ping"), // 0xee
  new Word("Duan"), // 0xef
  new Word("Shao"), // 0xf0
  new Word("Zhuan"), // 0xf1
  new Word("Ceng"), // 0xf2
  new Word("Deng"), // 0xf3
  new Word("Cui"), // 0xf4
  new Word("Huai"), // 0xf5
  new Word("Jing"), // 0xf6
  new Word("Kan"), // 0xf7
  new Word("Jing"), // 0xf8
  new Word("Zhu"), // 0xf9
  new Word("Zhu"), // 0xfa
  new Word("Le"), // 0xfb
  new Word("Peng"), // 0xfc
  new Word("Yu"), // 0xfd
  new Word("Chi"), // 0xfe
  new Word("Gan") // 0xff
  };
}