/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+7Bxx (CJK Unified Ideographs).
 */
final class X7b extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Mang"), // 0x00
  new Word("Zhu"), // 0x01
  new Word("Utsubo"), // 0x02
  new Word("Du"), // 0x03
  new Word("Ji"), // 0x04
  new Word("Xiao"), // 0x05
  new Word("Ba"), // 0x06
  new Word("Suan"), // 0x07
  new Word("Ji"), // 0x08
  new Word("Zhen"), // 0x09
  new Word("Zhao"), // 0x0a
  new Word("Sun"), // 0x0b
  new Word("Ya"), // 0x0c
  new Word("Zhui"), // 0x0d
  new Word("Yuan"), // 0x0e
  new Word("Hu"), // 0x0f
  new Word("Gang"), // 0x10
  new Word("Xiao"), // 0x11
  new Word("Cen"), // 0x12
  new Word("Pi"), // 0x13
  new Word("Bi"), // 0x14
  new Word("Jian"), // 0x15
  new Word("Yi"), // 0x16
  new Word("Dong"), // 0x17
  new Word("Shan"), // 0x18
  new Word("Sheng"), // 0x19
  new Word("Xia"), // 0x1a
  new Word("Di"), // 0x1b
  new Word("Zhu"), // 0x1c
  new Word("Na"), // 0x1d
  new Word("Chi"), // 0x1e
  new Word("Gu"), // 0x1f
  new Word("Li"), // 0x20
  new Word("Qie"), // 0x21
  new Word("Min"), // 0x22
  new Word("Bao"), // 0x23
  new Word("Tiao"), // 0x24
  new Word("Si"), // 0x25
  new Word("Fu"), // 0x26
  new Word("Ce"), // 0x27
  new Word("Ben"), // 0x28
  new Word("Pei"), // 0x29
  new Word("Da"), // 0x2a
  new Word("Zi"), // 0x2b
  new Word("Di"), // 0x2c
  new Word("Ling"), // 0x2d
  new Word("Ze"), // 0x2e
  new Word("Nu"), // 0x2f
  new Word("Fu"), // 0x30
  new Word("Gou"), // 0x31
  new Word("Fan"), // 0x32
  new Word("Jia"), // 0x33
  new Word("Ge"), // 0x34
  new Word("Fan"), // 0x35
  new Word("Shi"), // 0x36
  new Word("Mao"), // 0x37
  new Word("Po"), // 0x38
  new Word("Sey"), // 0x39
  new Word("Jian"), // 0x3a
  new Word("Qiong"), // 0x3b
  new Word("Long"), // 0x3c
  new Word("Souke"), // 0x3d
  new Word("Bian"), // 0x3e
  new Word("Luo"), // 0x3f
  new Word("Gui"), // 0x40
  new Word("Qu"), // 0x41
  new Word("Chi"), // 0x42
  new Word("Yin"), // 0x43
  new Word("Yao"), // 0x44
  new Word("Xian"), // 0x45
  new Word("Bi"), // 0x46
  new Word("Qiong"), // 0x47
  new Word("Gua"), // 0x48
  new Word("Deng"), // 0x49
  new Word("Jiao"), // 0x4a
  new Word("Jin"), // 0x4b
  new Word("Quan"), // 0x4c
  new Word("Sun"), // 0x4d
  new Word("Ru"), // 0x4e
  new Word("Fa"), // 0x4f
  new Word("Kuang"), // 0x50
  new Word("Zhu"), // 0x51
  new Word("Tong"), // 0x52
  new Word("Ji"), // 0x53
  new Word("Da"), // 0x54
  new Word("Xing"), // 0x55
  new Word("Ce"), // 0x56
  new Word("Zhong"), // 0x57
  new Word("Kou"), // 0x58
  new Word("Lai"), // 0x59
  new Word("Bi"), // 0x5a
  new Word("Shai"), // 0x5b
  new Word("Dang"), // 0x5c
  new Word("Zheng"), // 0x5d
  new Word("Ce"), // 0x5e
  new Word("Fu"), // 0x5f
  new Word("Yun"), // 0x60
  new Word("Tu"), // 0x61
  new Word("Pa"), // 0x62
  new Word("Li"), // 0x63
  new Word("Lang"), // 0x64
  new Word("Ju"), // 0x65
  new Word("Guan"), // 0x66
  new Word("Jian"), // 0x67
  new Word("Han"), // 0x68
  new Word("Tong"), // 0x69
  new Word("Xia"), // 0x6a
  new Word("Zhi"), // 0x6b
  new Word("Cheng"), // 0x6c
  new Word("Suan"), // 0x6d
  new Word("Shi"), // 0x6e
  new Word("Zhu"), // 0x6f
  new Word("Zuo"), // 0x70
  new Word("Xiao"), // 0x71
  new Word("Shao"), // 0x72
  new Word("Ting"), // 0x73
  new Word("Ce"), // 0x74
  new Word("Yan"), // 0x75
  new Word("Gao"), // 0x76
  new Word("Kuai"), // 0x77
  new Word("Gan"), // 0x78
  new Word("Chou"), // 0x79
  new Word("Kago"), // 0x7a
  new Word("Gang"), // 0x7b
  new Word("Yun"), // 0x7c
  new Word("O"), // 0x7d
  new Word("Qian"), // 0x7e
  new Word("Xiao"), // 0x7f
  new Word("Jian"), // 0x80
  new Word("Pu"), // 0x81
  new Word("Lai"), // 0x82
  new Word("Zou"), // 0x83
  new Word("Bi"), // 0x84
  new Word("Bi"), // 0x85
  new Word("Bi"), // 0x86
  new Word("Ge"), // 0x87
  new Word("Chi"), // 0x88
  new Word("Guai"), // 0x89
  new Word("Yu"), // 0x8a
  new Word("Jian"), // 0x8b
  new Word("Zhao"), // 0x8c
  new Word("Gu"), // 0x8d
  new Word("Chi"), // 0x8e
  new Word("Zheng"), // 0x8f
  new Word("Jing"), // 0x90
  new Word("Sha"), // 0x91
  new Word("Zhou"), // 0x92
  new Word("Lu"), // 0x93
  new Word("Bo"), // 0x94
  new Word("Ji"), // 0x95
  new Word("Lin"), // 0x96
  new Word("Suan"), // 0x97
  new Word("Jun"), // 0x98
  new Word("Fu"), // 0x99
  new Word("Zha"), // 0x9a
  new Word("Gu"), // 0x9b
  new Word("Kong"), // 0x9c
  new Word("Qian"), // 0x9d
  new Word("Quan"), // 0x9e
  new Word("Jun"), // 0x9f
  new Word("Chui"), // 0xa0
  new Word("Guan"), // 0xa1
  new Word("Yuan"), // 0xa2
  new Word("Ce"), // 0xa3
  new Word("Ju"), // 0xa4
  new Word("Bo"), // 0xa5
  new Word("Ze"), // 0xa6
  new Word("Qie"), // 0xa7
  new Word("Tuo"), // 0xa8
  new Word("Luo"), // 0xa9
  new Word("Dan"), // 0xaa
  new Word("Xiao"), // 0xab
  new Word("Ruo"), // 0xac
  new Word("Jian"), // 0xad
  new Word("Xuan"), // 0xae
  new Word("Bian"), // 0xaf
  new Word("Sun"), // 0xb0
  new Word("Xiang"), // 0xb1
  new Word("Xian"), // 0xb2
  new Word("Ping"), // 0xb3
  new Word("Zhen"), // 0xb4
  new Word("Sheng"), // 0xb5
  new Word("Hu"), // 0xb6
  new Word("Shi"), // 0xb7
  new Word("Zhu"), // 0xb8
  new Word("Yue"), // 0xb9
  new Word("Chun"), // 0xba
  new Word("Lu"), // 0xbb
  new Word("Wu"), // 0xbc
  new Word("Dong"), // 0xbd
  new Word("Xiao"), // 0xbe
  new Word("Ji"), // 0xbf
  new Word("Jie"), // 0xc0
  new Word("Huang"), // 0xc1
  new Word("Xing"), // 0xc2
  new Word("Mei"), // 0xc3
  new Word("Fan"), // 0xc4
  new Word("Chui"), // 0xc5
  new Word("Zhuan"), // 0xc6
  new Word("Pian"), // 0xc7
  new Word("Feng"), // 0xc8
  new Word("Zhu"), // 0xc9
  new Word("Hong"), // 0xca
  new Word("Qie"), // 0xcb
  new Word("Hou"), // 0xcc
  new Word("Qiu"), // 0xcd
  new Word("Miao"), // 0xce
  new Word("Qian"), // 0xcf
  null, // 0xd0
  new Word("Kui"), // 0xd1
  new Word("Sik"), // 0xd2
  new Word("Lou"), // 0xd3
  new Word("Yun"), // 0xd4
  new Word("He"), // 0xd5
  new Word("Tang"), // 0xd6
  new Word("Yue"), // 0xd7
  new Word("Chou"), // 0xd8
  new Word("Gao"), // 0xd9
  new Word("Fei"), // 0xda
  new Word("Ruo"), // 0xdb
  new Word("Zheng"), // 0xdc
  new Word("Gou"), // 0xdd
  new Word("Nie"), // 0xde
  new Word("Qian"), // 0xdf
  new Word("Xiao"), // 0xe0
  new Word("Cuan"), // 0xe1
  new Word("Gong"), // 0xe2
  new Word("Pang"), // 0xe3
  new Word("Du"), // 0xe4
  new Word("Li"), // 0xe5
  new Word("Bi"), // 0xe6
  new Word("Zhuo"), // 0xe7
  new Word("Chu"), // 0xe8
  new Word("Shai"), // 0xe9
  new Word("Chi"), // 0xea
  new Word("Zhu"), // 0xeb
  new Word("Qiang"), // 0xec
  new Word("Long"), // 0xed
  new Word("Lan"), // 0xee
  new Word("Jian"), // 0xef
  new Word("Bu"), // 0xf0
  new Word("Li"), // 0xf1
  new Word("Hui"), // 0xf2
  new Word("Bi"), // 0xf3
  new Word("Di"), // 0xf4
  new Word("Cong"), // 0xf5
  new Word("Yan"), // 0xf6
  new Word("Peng"), // 0xf7
  new Word("Sen"), // 0xf8
  new Word("Zhuan"), // 0xf9
  new Word("Pai"), // 0xfa
  new Word("Piao"), // 0xfb
  new Word("Dou"), // 0xfc
  new Word("Yu"), // 0xfd
  new Word("Mie"), // 0xfe
  new Word("Zhuan") // 0xff
  };
}