/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+7Cxx (CJK Unified Ideographs).
 */
final class X7c extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Ze"), // 0x00
  new Word("Xi"), // 0x01
  new Word("Guo"), // 0x02
  new Word("Yi"), // 0x03
  new Word("Hu"), // 0x04
  new Word("Chan"), // 0x05
  new Word("Kou"), // 0x06
  new Word("Cu"), // 0x07
  new Word("Ping"), // 0x08
  new Word("Chou"), // 0x09
  new Word("Ji"), // 0x0a
  new Word("Gui"), // 0x0b
  new Word("Su"), // 0x0c
  new Word("Lou"), // 0x0d
  new Word("Zha"), // 0x0e
  new Word("Lu"), // 0x0f
  new Word("Nian"), // 0x10
  new Word("Suo"), // 0x11
  new Word("Cuan"), // 0x12
  new Word("Sasara"), // 0x13
  new Word("Suo"), // 0x14
  new Word("Le"), // 0x15
  new Word("Duan"), // 0x16
  new Word("Yana"), // 0x17
  new Word("Xiao"), // 0x18
  new Word("Bo"), // 0x19
  new Word("Mi"), // 0x1a
  new Word("Si"), // 0x1b
  new Word("Dang"), // 0x1c
  new Word("Liao"), // 0x1d
  new Word("Dan"), // 0x1e
  new Word("Dian"), // 0x1f
  new Word("Fu"), // 0x20
  new Word("Jian"), // 0x21
  new Word("Min"), // 0x22
  new Word("Kui"), // 0x23
  new Word("Dai"), // 0x24
  new Word("Qiao"), // 0x25
  new Word("Deng"), // 0x26
  new Word("Huang"), // 0x27
  new Word("Sun"), // 0x28
  new Word("Lao"), // 0x29
  new Word("Zan"), // 0x2a
  new Word("Xiao"), // 0x2b
  new Word("Du"), // 0x2c
  new Word("Shi"), // 0x2d
  new Word("Zan"), // 0x2e
  null, // 0x2f
  new Word("Pai"), // 0x30
  new Word("Hata"), // 0x31
  new Word("Pai"), // 0x32
  new Word("Gan"), // 0x33
  new Word("Ju"), // 0x34
  new Word("Du"), // 0x35
  new Word("Lu"), // 0x36
  new Word("Yan"), // 0x37
  new Word("Bo"), // 0x38
  new Word("Dang"), // 0x39
  new Word("Sai"), // 0x3a
  new Word("Ke"), // 0x3b
  new Word("Long"), // 0x3c
  new Word("Qian"), // 0x3d
  new Word("Lian"), // 0x3e
  new Word("Bo"), // 0x3f
  new Word("Zhou"), // 0x40
  new Word("Lai"), // 0x41
  null, // 0x42
  new Word("Lan"), // 0x43
  new Word("Kui"), // 0x44
  new Word("Yu"), // 0x45
  new Word("Yue"), // 0x46
  new Word("Hao"), // 0x47
  new Word("Zhen"), // 0x48
  new Word("Tai"), // 0x49
  new Word("Ti"), // 0x4a
  new Word("Mi"), // 0x4b
  new Word("Chou"), // 0x4c
  new Word("Ji"), // 0x4d
  null, // 0x4e
  new Word("Hata"), // 0x4f
  new Word("Teng"), // 0x50
  new Word("Zhuan"), // 0x51
  new Word("Zhou"), // 0x52
  new Word("Fan"), // 0x53
  new Word("Sou"), // 0x54
  new Word("Zhou"), // 0x55
  new Word("Kuji"), // 0x56
  new Word("Zhuo"), // 0x57
  new Word("Teng"), // 0x58
  new Word("Lu"), // 0x59
  new Word("Lu"), // 0x5a
  new Word("Jian"), // 0x5b
  new Word("Tuo"), // 0x5c
  new Word("Ying"), // 0x5d
  new Word("Yu"), // 0x5e
  new Word("Lai"), // 0x5f
  new Word("Long"), // 0x60
  new Word("Shinshi"), // 0x61
  new Word("Lian"), // 0x62
  new Word("Lan"), // 0x63
  new Word("Qian"), // 0x64
  new Word("Yue"), // 0x65
  new Word("Zhong"), // 0x66
  new Word("Qu"), // 0x67
  new Word("Lian"), // 0x68
  new Word("Bian"), // 0x69
  new Word("Duan"), // 0x6a
  new Word("Zuan"), // 0x6b
  new Word("Li"), // 0x6c
  new Word("Si"), // 0x6d
  new Word("Luo"), // 0x6e
  new Word("Ying"), // 0x6f
  new Word("Yue"), // 0x70
  new Word("Zhuo"), // 0x71
  new Word("Xu"), // 0x72
  new Word("Mi"), // 0x73
  new Word("Di"), // 0x74
  new Word("Fan"), // 0x75
  new Word("Shen"), // 0x76
  new Word("Zhe"), // 0x77
  new Word("Shen"), // 0x78
  new Word("Nu"), // 0x79
  new Word("Xie"), // 0x7a
  new Word("Lei"), // 0x7b
  new Word("Xian"), // 0x7c
  new Word("Zi"), // 0x7d
  new Word("Ni"), // 0x7e
  new Word("Cun"), // 0x7f
  null, // 0x80
  new Word("Qian"), // 0x81
  new Word("Kume"), // 0x82
  new Word("Bi"), // 0x83
  new Word("Ban"), // 0x84
  new Word("Wu"), // 0x85
  new Word("Sha"), // 0x86
  new Word("Kang"), // 0x87
  new Word("Rou"), // 0x88
  new Word("Fen"), // 0x89
  new Word("Bi"), // 0x8a
  new Word("Cui"), // 0x8b
  null, // 0x8c
  new Word("Li"), // 0x8d
  new Word("Chi"), // 0x8e
  new Word("Nukamiso"), // 0x8f
  new Word("Ro"), // 0x90
  new Word("Ba"), // 0x91
  new Word("Li"), // 0x92
  new Word("Gan"), // 0x93
  new Word("Ju"), // 0x94
  new Word("Po"), // 0x95
  new Word("Mo"), // 0x96
  new Word("Cu"), // 0x97
  new Word("Nian"), // 0x98
  new Word("Zhou"), // 0x99
  new Word("Li"), // 0x9a
  new Word("Su"), // 0x9b
  new Word("Tiao"), // 0x9c
  new Word("Li"), // 0x9d
  new Word("Qi"), // 0x9e
  new Word("Su"), // 0x9f
  new Word("Hong"), // 0xa0
  new Word("Tong"), // 0xa1
  new Word("Zi"), // 0xa2
  new Word("Ce"), // 0xa3
  new Word("Yue"), // 0xa4
  new Word("Zhou"), // 0xa5
  new Word("Lin"), // 0xa6
  new Word("Zhuang"), // 0xa7
  new Word("Bai"), // 0xa8
  null, // 0xa9
  new Word("Fen"), // 0xaa
  new Word("Ji"), // 0xab
  null, // 0xac
  new Word("Sukumo"), // 0xad
  new Word("Liang"), // 0xae
  new Word("Xian"), // 0xaf
  new Word("Fu"), // 0xb0
  new Word("Liang"), // 0xb1
  new Word("Can"), // 0xb2
  new Word("Geng"), // 0xb3
  new Word("Li"), // 0xb4
  new Word("Yue"), // 0xb5
  new Word("Lu"), // 0xb6
  new Word("Ju"), // 0xb7
  new Word("Qi"), // 0xb8
  new Word("Cui"), // 0xb9
  new Word("Bai"), // 0xba
  new Word("Zhang"), // 0xbb
  new Word("Lin"), // 0xbc
  new Word("Zong"), // 0xbd
  new Word("Jing"), // 0xbe
  new Word("Guo"), // 0xbf
  new Word("Kouji"), // 0xc0
  new Word("San"), // 0xc1
  new Word("San"), // 0xc2
  new Word("Tang"), // 0xc3
  new Word("Bian"), // 0xc4
  new Word("Rou"), // 0xc5
  new Word("Mian"), // 0xc6
  new Word("Hou"), // 0xc7
  new Word("Xu"), // 0xc8
  new Word("Zong"), // 0xc9
  new Word("Hu"), // 0xca
  new Word("Jian"), // 0xcb
  new Word("Zan"), // 0xcc
  new Word("Ci"), // 0xcd
  new Word("Li"), // 0xce
  new Word("Xie"), // 0xcf
  new Word("Fu"), // 0xd0
  new Word("Ni"), // 0xd1
  new Word("Bei"), // 0xd2
  new Word("Gu"), // 0xd3
  new Word("Xiu"), // 0xd4
  new Word("Gao"), // 0xd5
  new Word("Tang"), // 0xd6
  new Word("Qiu"), // 0xd7
  new Word("Sukumo"), // 0xd8
  new Word("Cao"), // 0xd9
  new Word("Zhuang"), // 0xda
  new Word("Tang"), // 0xdb
  new Word("Mi"), // 0xdc
  new Word("San"), // 0xdd
  new Word("Fen"), // 0xde
  new Word("Zao"), // 0xdf
  new Word("Kang"), // 0xe0
  new Word("Jiang"), // 0xe1
  new Word("Mo"), // 0xe2
  new Word("San"), // 0xe3
  new Word("San"), // 0xe4
  new Word("Nuo"), // 0xe5
  new Word("Xi"), // 0xe6
  new Word("Liang"), // 0xe7
  new Word("Jiang"), // 0xe8
  new Word("Kuai"), // 0xe9
  new Word("Bo"), // 0xea
  new Word("Huan"), // 0xeb
  null, // 0xec
  new Word("Zong"), // 0xed
  new Word("Xian"), // 0xee
  new Word("Nuo"), // 0xef
  new Word("Tuan"), // 0xf0
  new Word("Nie"), // 0xf1
  new Word("Li"), // 0xf2
  new Word("Zuo"), // 0xf3
  new Word("Di"), // 0xf4
  new Word("Nie"), // 0xf5
  new Word("Tiao"), // 0xf6
  new Word("Lan"), // 0xf7
  new Word("Mi"), // 0xf8
  new Word("Jiao"), // 0xf9
  new Word("Jiu"), // 0xfa
  new Word("Xi"), // 0xfb
  new Word("Gong"), // 0xfc
  new Word("Zheng"), // 0xfd
  new Word("Jiu"), // 0xfe
  new Word("You") // 0xff
  };
}