/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+7Fxx (CJK Unified Ideographs).
 */
final class X7f extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Zhui"), // 0x00
  new Word("Zi"), // 0x01
  new Word("Ke"), // 0x02
  new Word("Xiang"), // 0x03
  new Word("Jian"), // 0x04
  new Word("Mian"), // 0x05
  new Word("Lan"), // 0x06
  new Word("Ti"), // 0x07
  new Word("Miao"), // 0x08
  new Word("Qi"), // 0x09
  new Word("Yun"), // 0x0a
  new Word("Hui"), // 0x0b
  new Word("Si"), // 0x0c
  new Word("Duo"), // 0x0d
  new Word("Duan"), // 0x0e
  new Word("Bian"), // 0x0f
  new Word("Xian"), // 0x10
  new Word("Gou"), // 0x11
  new Word("Zhui"), // 0x12
  new Word("Huan"), // 0x13
  new Word("Di"), // 0x14
  new Word("Lu"), // 0x15
  new Word("Bian"), // 0x16
  new Word("Min"), // 0x17
  new Word("Yuan"), // 0x18
  new Word("Jin"), // 0x19
  new Word("Fu"), // 0x1a
  new Word("Ru"), // 0x1b
  new Word("Zhen"), // 0x1c
  new Word("Feng"), // 0x1d
  new Word("Shuai"), // 0x1e
  new Word("Gao"), // 0x1f
  new Word("Chan"), // 0x20
  new Word("Li"), // 0x21
  new Word("Yi"), // 0x22
  new Word("Jian"), // 0x23
  new Word("Bin"), // 0x24
  new Word("Piao"), // 0x25
  new Word("Man"), // 0x26
  new Word("Lei"), // 0x27
  new Word("Ying"), // 0x28
  new Word("Suo"), // 0x29
  new Word("Mou"), // 0x2a
  new Word("Sao"), // 0x2b
  new Word("Xie"), // 0x2c
  new Word("Liao"), // 0x2d
  new Word("Shan"), // 0x2e
  new Word("Zeng"), // 0x2f
  new Word("Jiang"), // 0x30
  new Word("Qian"), // 0x31
  new Word("Zao"), // 0x32
  new Word("Huan"), // 0x33
  new Word("Jiao"), // 0x34
  new Word("Zuan"), // 0x35
  new Word("Fou"), // 0x36
  new Word("Xie"), // 0x37
  new Word("Gang"), // 0x38
  new Word("Fou"), // 0x39
  new Word("Que"), // 0x3a
  new Word("Fou"), // 0x3b
  new Word("Kaakeru"), // 0x3c
  new Word("Bo"), // 0x3d
  new Word("Ping"), // 0x3e
  new Word("Hou"), // 0x3f
  null, // 0x40
  new Word("Gang"), // 0x41
  new Word("Ying"), // 0x42
  new Word("Ying"), // 0x43
  new Word("Qing"), // 0x44
  new Word("Xia"), // 0x45
  new Word("Guan"), // 0x46
  new Word("Zun"), // 0x47
  new Word("Tan"), // 0x48
  new Word("Chang"), // 0x49
  new Word("Qi"), // 0x4a
  new Word("Weng"), // 0x4b
  new Word("Ying"), // 0x4c
  new Word("Lei"), // 0x4d
  new Word("Tan"), // 0x4e
  new Word("Lu"), // 0x4f
  new Word("Guan"), // 0x50
  new Word("Wang"), // 0x51
  new Word("Wang"), // 0x52
  new Word("Gang"), // 0x53
  new Word("Wang"), // 0x54
  new Word("Han"), // 0x55
  null, // 0x56
  new Word("Luo"), // 0x57
  new Word("Fu"), // 0x58
  new Word("Mi"), // 0x59
  new Word("Fa"), // 0x5a
  new Word("Gu"), // 0x5b
  new Word("Zhu"), // 0x5c
  new Word("Ju"), // 0x5d
  new Word("Mao"), // 0x5e
  new Word("Gu"), // 0x5f
  new Word("Min"), // 0x60
  new Word("Gang"), // 0x61
  new Word("Ba"), // 0x62
  new Word("Gua"), // 0x63
  new Word("Ti"), // 0x64
  new Word("Juan"), // 0x65
  new Word("Fu"), // 0x66
  new Word("Lin"), // 0x67
  new Word("Yan"), // 0x68
  new Word("Zhao"), // 0x69
  new Word("Zui"), // 0x6a
  new Word("Gua"), // 0x6b
  new Word("Zhuo"), // 0x6c
  new Word("Yu"), // 0x6d
  new Word("Zhi"), // 0x6e
  new Word("An"), // 0x6f
  new Word("Fa"), // 0x70
  new Word("Nan"), // 0x71
  new Word("Shu"), // 0x72
  new Word("Si"), // 0x73
  new Word("Pi"), // 0x74
  new Word("Ma"), // 0x75
  new Word("Liu"), // 0x76
  new Word("Ba"), // 0x77
  new Word("Fa"), // 0x78
  new Word("Li"), // 0x79
  new Word("Chao"), // 0x7a
  new Word("Wei"), // 0x7b
  new Word("Bi"), // 0x7c
  new Word("Ji"), // 0x7d
  new Word("Zeng"), // 0x7e
  new Word("Tong"), // 0x7f
  new Word("Liu"), // 0x80
  new Word("Ji"), // 0x81
  new Word("Juan"), // 0x82
  new Word("Mi"), // 0x83
  new Word("Zhao"), // 0x84
  new Word("Luo"), // 0x85
  new Word("Pi"), // 0x86
  new Word("Ji"), // 0x87
  new Word("Ji"), // 0x88
  new Word("Luan"), // 0x89
  new Word("Yang"), // 0x8a
  new Word("Mie"), // 0x8b
  new Word("Qiang"), // 0x8c
  new Word("Ta"), // 0x8d
  new Word("Mei"), // 0x8e
  new Word("Yang"), // 0x8f
  new Word("You"), // 0x90
  new Word("You"), // 0x91
  new Word("Fen"), // 0x92
  new Word("Ba"), // 0x93
  new Word("Gao"), // 0x94
  new Word("Yang"), // 0x95
  new Word("Gu"), // 0x96
  new Word("Qiang"), // 0x97
  new Word("Zang"), // 0x98
  new Word("Gao"), // 0x99
  new Word("Ling"), // 0x9a
  new Word("Yi"), // 0x9b
  new Word("Zhu"), // 0x9c
  new Word("Di"), // 0x9d
  new Word("Xiu"), // 0x9e
  new Word("Qian"), // 0x9f
  new Word("Yi"), // 0xa0
  new Word("Xian"), // 0xa1
  new Word("Rong"), // 0xa2
  new Word("Qun"), // 0xa3
  new Word("Qun"), // 0xa4
  new Word("Qian"), // 0xa5
  new Word("Huan"), // 0xa6
  new Word("Zui"), // 0xa7
  new Word("Xian"), // 0xa8
  new Word("Yi"), // 0xa9
  new Word("Yashinau"), // 0xaa
  new Word("Qiang"), // 0xab
  new Word("Xian"), // 0xac
  new Word("Yu"), // 0xad
  new Word("Geng"), // 0xae
  new Word("Jie"), // 0xaf
  new Word("Tang"), // 0xb0
  new Word("Yuan"), // 0xb1
  new Word("Xi"), // 0xb2
  new Word("Fan"), // 0xb3
  new Word("Shan"), // 0xb4
  new Word("Fen"), // 0xb5
  new Word("Shan"), // 0xb6
  new Word("Lian"), // 0xb7
  new Word("Lei"), // 0xb8
  new Word("Geng"), // 0xb9
  new Word("Nou"), // 0xba
  new Word("Qiang"), // 0xbb
  new Word("Chan"), // 0xbc
  new Word("Yu"), // 0xbd
  new Word("Gong"), // 0xbe
  new Word("Yi"), // 0xbf
  new Word("Chong"), // 0xc0
  new Word("Weng"), // 0xc1
  new Word("Fen"), // 0xc2
  new Word("Hong"), // 0xc3
  new Word("Chi"), // 0xc4
  new Word("Chi"), // 0xc5
  new Word("Cui"), // 0xc6
  new Word("Fu"), // 0xc7
  new Word("Xia"), // 0xc8
  new Word("Pen"), // 0xc9
  new Word("Yi"), // 0xca
  new Word("La"), // 0xcb
  new Word("Yi"), // 0xcc
  new Word("Pi"), // 0xcd
  new Word("Ling"), // 0xce
  new Word("Liu"), // 0xcf
  new Word("Zhi"), // 0xd0
  new Word("Qu"), // 0xd1
  new Word("Xi"), // 0xd2
  new Word("Xie"), // 0xd3
  new Word("Xiang"), // 0xd4
  new Word("Xi"), // 0xd5
  new Word("Xi"), // 0xd6
  new Word("Qi"), // 0xd7
  new Word("Qiao"), // 0xd8
  new Word("Hui"), // 0xd9
  new Word("Hui"), // 0xda
  new Word("Xiao"), // 0xdb
  new Word("Se"), // 0xdc
  new Word("Hong"), // 0xdd
  new Word("Jiang"), // 0xde
  new Word("Di"), // 0xdf
  new Word("Cui"), // 0xe0
  new Word("Fei"), // 0xe1
  new Word("Tao"), // 0xe2
  new Word("Sha"), // 0xe3
  new Word("Chi"), // 0xe4
  new Word("Zhu"), // 0xe5
  new Word("Jian"), // 0xe6
  new Word("Xuan"), // 0xe7
  new Word("Shi"), // 0xe8
  new Word("Pian"), // 0xe9
  new Word("Zong"), // 0xea
  new Word("Wan"), // 0xeb
  new Word("Hui"), // 0xec
  new Word("Hou"), // 0xed
  new Word("He"), // 0xee
  new Word("He"), // 0xef
  new Word("Han"), // 0xf0
  new Word("Ao"), // 0xf1
  new Word("Piao"), // 0xf2
  new Word("Yi"), // 0xf3
  new Word("Lian"), // 0xf4
  new Word("Qu"), // 0xf5
  null, // 0xf6
  new Word("Lin"), // 0xf7
  new Word("Pen"), // 0xf8
  new Word("Qiao"), // 0xf9
  new Word("Ao"), // 0xfa
  new Word("Fan"), // 0xfb
  new Word("Yi"), // 0xfc
  new Word("Hui"), // 0xfd
  new Word("Xuan"), // 0xfe
  new Word("Dao") // 0xff
  };
}