/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+80xx (CJK Unified Ideographs).
 */
final class X80 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Yao"), // 0x00
  new Word("Lao"), // 0x01
  null, // 0x02
  new Word("Kao"), // 0x03
  new Word("Mao"), // 0x04
  new Word("Zhe"), // 0x05
  new Word("Qi"), // 0x06
  new Word("Gou"), // 0x07
  new Word("Gou"), // 0x08
  new Word("Gou"), // 0x09
  new Word("Die"), // 0x0a
  new Word("Die"), // 0x0b
  new Word("Er"), // 0x0c
  new Word("Shua"), // 0x0d
  new Word("Ruan"), // 0x0e
  new Word("Er"), // 0x0f
  new Word("Nai"), // 0x10
  new Word("Zhuan"), // 0x11
  new Word("Lei"), // 0x12
  new Word("Ting"), // 0x13
  new Word("Zi"), // 0x14
  new Word("Geng"), // 0x15
  new Word("Chao"), // 0x16
  new Word("Hao"), // 0x17
  new Word("Yun"), // 0x18
  new Word("Pa"), // 0x19
  new Word("Pi"), // 0x1a
  new Word("Chi"), // 0x1b
  new Word("Si"), // 0x1c
  new Word("Chu"), // 0x1d
  new Word("Jia"), // 0x1e
  new Word("Ju"), // 0x1f
  new Word("He"), // 0x20
  new Word("Chu"), // 0x21
  new Word("Lao"), // 0x22
  new Word("Lun"), // 0x23
  new Word("Ji"), // 0x24
  new Word("Tang"), // 0x25
  new Word("Ou"), // 0x26
  new Word("Lou"), // 0x27
  new Word("Nou"), // 0x28
  new Word("Gou"), // 0x29
  new Word("Pang"), // 0x2a
  new Word("Ze"), // 0x2b
  new Word("Lou"), // 0x2c
  new Word("Ji"), // 0x2d
  new Word("Lao"), // 0x2e
  new Word("Huo"), // 0x2f
  new Word("You"), // 0x30
  new Word("Mo"), // 0x31
  new Word("Huai"), // 0x32
  new Word("Er"), // 0x33
  new Word("Zhe"), // 0x34
  new Word("Ting"), // 0x35
  new Word("Ye"), // 0x36
  new Word("Da"), // 0x37
  new Word("Song"), // 0x38
  new Word("Qin"), // 0x39
  new Word("Yun"), // 0x3a
  new Word("Chi"), // 0x3b
  new Word("Dan"), // 0x3c
  new Word("Dan"), // 0x3d
  new Word("Hong"), // 0x3e
  new Word("Geng"), // 0x3f
  new Word("Zhi"), // 0x40
  null, // 0x41
  new Word("Nie"), // 0x42
  new Word("Dan"), // 0x43
  new Word("Zhen"), // 0x44
  new Word("Che"), // 0x45
  new Word("Ling"), // 0x46
  new Word("Zheng"), // 0x47
  new Word("You"), // 0x48
  new Word("Wa"), // 0x49
  new Word("Liao"), // 0x4a
  new Word("Long"), // 0x4b
  new Word("Zhi"), // 0x4c
  new Word("Ning"), // 0x4d
  new Word("Tiao"), // 0x4e
  new Word("Er"), // 0x4f
  new Word("Ya"), // 0x50
  new Word("Die"), // 0x51
  new Word("Gua"), // 0x52
  null, // 0x53
  new Word("Lian"), // 0x54
  new Word("Hao"), // 0x55
  new Word("Sheng"), // 0x56
  new Word("Lie"), // 0x57
  new Word("Pin"), // 0x58
  new Word("Jing"), // 0x59
  new Word("Ju"), // 0x5a
  new Word("Bi"), // 0x5b
  new Word("Di"), // 0x5c
  new Word("Guo"), // 0x5d
  new Word("Wen"), // 0x5e
  new Word("Xu"), // 0x5f
  new Word("Ping"), // 0x60
  new Word("Cong"), // 0x61
  new Word("Shikato"), // 0x62
  null, // 0x63
  new Word("Ting"), // 0x64
  new Word("Yu"), // 0x65
  new Word("Cong"), // 0x66
  new Word("Kui"), // 0x67
  new Word("Tsuraneru"), // 0x68
  new Word("Kui"), // 0x69
  new Word("Cong"), // 0x6a
  new Word("Lian"), // 0x6b
  new Word("Weng"), // 0x6c
  new Word("Kui"), // 0x6d
  new Word("Lian"), // 0x6e
  new Word("Lian"), // 0x6f
  new Word("Cong"), // 0x70
  new Word("Ao"), // 0x71
  new Word("Sheng"), // 0x72
  new Word("Song"), // 0x73
  new Word("Ting"), // 0x74
  new Word("Kui"), // 0x75
  new Word("Nie"), // 0x76
  new Word("Zhi"), // 0x77
  new Word("Dan"), // 0x78
  new Word("Ning"), // 0x79
  new Word("Qie"), // 0x7a
  new Word("Ji"), // 0x7b
  new Word("Ting"), // 0x7c
  new Word("Ting"), // 0x7d
  new Word("Long"), // 0x7e
  new Word("Yu"), // 0x7f
  new Word("Yu"), // 0x80
  new Word("Zhao"), // 0x81
  new Word("Si"), // 0x82
  new Word("Su"), // 0x83
  new Word("Yi"), // 0x84
  new Word("Su"), // 0x85
  new Word("Si"), // 0x86
  new Word("Zhao"), // 0x87
  new Word("Zhao"), // 0x88
  new Word("Rou"), // 0x89
  new Word("Yi"), // 0x8a
  new Word("Le"), // 0x8b
  new Word("Ji"), // 0x8c
  new Word("Qiu"), // 0x8d
  new Word("Ken"), // 0x8e
  new Word("Cao"), // 0x8f
  new Word("Ge"), // 0x90
  new Word("Di"), // 0x91
  new Word("Huan"), // 0x92
  new Word("Huang"), // 0x93
  new Word("Yi"), // 0x94
  new Word("Ren"), // 0x95
  new Word("Xiao"), // 0x96
  new Word("Ru"), // 0x97
  new Word("Zhou"), // 0x98
  new Word("Yuan"), // 0x99
  new Word("Du"), // 0x9a
  new Word("Gang"), // 0x9b
  new Word("Rong"), // 0x9c
  new Word("Gan"), // 0x9d
  new Word("Cha"), // 0x9e
  new Word("Wo"), // 0x9f
  new Word("Chang"), // 0xa0
  new Word("Gu"), // 0xa1
  new Word("Zhi"), // 0xa2
  new Word("Han"), // 0xa3
  new Word("Fu"), // 0xa4
  new Word("Fei"), // 0xa5
  new Word("Fen"), // 0xa6
  new Word("Pei"), // 0xa7
  new Word("Pang"), // 0xa8
  new Word("Jian"), // 0xa9
  new Word("Fang"), // 0xaa
  new Word("Zhun"), // 0xab
  new Word("You"), // 0xac
  new Word("Na"), // 0xad
  new Word("Hang"), // 0xae
  new Word("Ken"), // 0xaf
  new Word("Ran"), // 0xb0
  new Word("Gong"), // 0xb1
  new Word("Yu"), // 0xb2
  new Word("Wen"), // 0xb3
  new Word("Yao"), // 0xb4
  new Word("Jin"), // 0xb5
  new Word("Pi"), // 0xb6
  new Word("Qian"), // 0xb7
  new Word("Xi"), // 0xb8
  new Word("Xi"), // 0xb9
  new Word("Fei"), // 0xba
  new Word("Ken"), // 0xbb
  new Word("Jing"), // 0xbc
  new Word("Tai"), // 0xbd
  new Word("Shen"), // 0xbe
  new Word("Zhong"), // 0xbf
  new Word("Zhang"), // 0xc0
  new Word("Xie"), // 0xc1
  new Word("Shen"), // 0xc2
  new Word("Wei"), // 0xc3
  new Word("Zhou"), // 0xc4
  new Word("Die"), // 0xc5
  new Word("Dan"), // 0xc6
  new Word("Fei"), // 0xc7
  new Word("Ba"), // 0xc8
  new Word("Bo"), // 0xc9
  new Word("Qu"), // 0xca
  new Word("Tian"), // 0xcb
  new Word("Bei"), // 0xcc
  new Word("Gua"), // 0xcd
  new Word("Tai"), // 0xce
  new Word("Zi"), // 0xcf
  new Word("Ku"), // 0xd0
  new Word("Zhi"), // 0xd1
  new Word("Ni"), // 0xd2
  new Word("Ping"), // 0xd3
  new Word("Zi"), // 0xd4
  new Word("Fu"), // 0xd5
  new Word("Pang"), // 0xd6
  new Word("Zhen"), // 0xd7
  new Word("Xian"), // 0xd8
  new Word("Zuo"), // 0xd9
  new Word("Pei"), // 0xda
  new Word("Jia"), // 0xdb
  new Word("Sheng"), // 0xdc
  new Word("Zhi"), // 0xdd
  new Word("Bao"), // 0xde
  new Word("Mu"), // 0xdf
  new Word("Qu"), // 0xe0
  new Word("Hu"), // 0xe1
  new Word("Ke"), // 0xe2
  new Word("Yi"), // 0xe3
  new Word("Yin"), // 0xe4
  new Word("Xu"), // 0xe5
  new Word("Yang"), // 0xe6
  new Word("Long"), // 0xe7
  new Word("Dong"), // 0xe8
  new Word("Ka"), // 0xe9
  new Word("Lu"), // 0xea
  new Word("Jing"), // 0xeb
  new Word("Nu"), // 0xec
  new Word("Yan"), // 0xed
  new Word("Pang"), // 0xee
  new Word("Kua"), // 0xef
  new Word("Yi"), // 0xf0
  new Word("Guang"), // 0xf1
  new Word("Gai"), // 0xf2
  new Word("Ge"), // 0xf3
  new Word("Dong"), // 0xf4
  new Word("Zhi"), // 0xf5
  new Word("Xiao"), // 0xf6
  new Word("Xiong"), // 0xf7
  new Word("Xiong"), // 0xf8
  new Word("Er"), // 0xf9
  new Word("E"), // 0xfa
  new Word("Xing"), // 0xfb
  new Word("Pian"), // 0xfc
  new Word("Neng"), // 0xfd
  new Word("Zi"), // 0xfe
  new Word("Gui") // 0xff
  };
}