/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+81xx (CJK Unified Ideographs).
 */
final class X81 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Cheng"), // 0x00
  new Word("Tiao"), // 0x01
  new Word("Zhi"), // 0x02
  new Word("Cui"), // 0x03
  new Word("Mei"), // 0x04
  new Word("Xie"), // 0x05
  new Word("Cui"), // 0x06
  new Word("Xie"), // 0x07
  new Word("Mo"), // 0x08
  new Word("Mai"), // 0x09
  new Word("Ji"), // 0x0a
  new Word("Obiyaakasu"), // 0x0b
  null, // 0x0c
  new Word("Kuai"), // 0x0d
  new Word("Sa"), // 0x0e
  new Word("Zang"), // 0x0f
  new Word("Qi"), // 0x10
  new Word("Nao"), // 0x11
  new Word("Mi"), // 0x12
  new Word("Nong"), // 0x13
  new Word("Luan"), // 0x14
  new Word("Wan"), // 0x15
  new Word("Bo"), // 0x16
  new Word("Wen"), // 0x17
  new Word("Guan"), // 0x18
  new Word("Qiu"), // 0x19
  new Word("Jiao"), // 0x1a
  new Word("Jing"), // 0x1b
  new Word("Rou"), // 0x1c
  new Word("Heng"), // 0x1d
  new Word("Cuo"), // 0x1e
  new Word("Lie"), // 0x1f
  new Word("Shan"), // 0x20
  new Word("Ting"), // 0x21
  new Word("Mei"), // 0x22
  new Word("Chun"), // 0x23
  new Word("Shen"), // 0x24
  new Word("Xie"), // 0x25
  new Word("De"), // 0x26
  new Word("Zui"), // 0x27
  new Word("Cu"), // 0x28
  new Word("Xiu"), // 0x29
  new Word("Xin"), // 0x2a
  new Word("Tuo"), // 0x2b
  new Word("Pao"), // 0x2c
  new Word("Cheng"), // 0x2d
  new Word("Nei"), // 0x2e
  new Word("Fu"), // 0x2f
  new Word("Dou"), // 0x30
  new Word("Tuo"), // 0x31
  new Word("Niao"), // 0x32
  new Word("Noy"), // 0x33
  new Word("Pi"), // 0x34
  new Word("Gu"), // 0x35
  new Word("Gua"), // 0x36
  new Word("Li"), // 0x37
  new Word("Lian"), // 0x38
  new Word("Zhang"), // 0x39
  new Word("Cui"), // 0x3a
  new Word("Jie"), // 0x3b
  new Word("Liang"), // 0x3c
  new Word("Zhou"), // 0x3d
  new Word("Pi"), // 0x3e
  new Word("Biao"), // 0x3f
  new Word("Lun"), // 0x40
  new Word("Pian"), // 0x41
  new Word("Guo"), // 0x42
  new Word("Kui"), // 0x43
  new Word("Chui"), // 0x44
  new Word("Dan"), // 0x45
  new Word("Tian"), // 0x46
  new Word("Nei"), // 0x47
  new Word("Jing"), // 0x48
  new Word("Jie"), // 0x49
  new Word("La"), // 0x4a
  new Word("Yi"), // 0x4b
  new Word("An"), // 0x4c
  new Word("Ren"), // 0x4d
  new Word("Shen"), // 0x4e
  new Word("Chuo"), // 0x4f
  new Word("Fu"), // 0x50
  new Word("Fu"), // 0x51
  new Word("Ju"), // 0x52
  new Word("Fei"), // 0x53
  new Word("Qiang"), // 0x54
  new Word("Wan"), // 0x55
  new Word("Dong"), // 0x56
  new Word("Pi"), // 0x57
  new Word("Guo"), // 0x58
  new Word("Zong"), // 0x59
  new Word("Ding"), // 0x5a
  new Word("Wu"), // 0x5b
  new Word("Mei"), // 0x5c
  new Word("Ruan"), // 0x5d
  new Word("Zhuan"), // 0x5e
  new Word("Zhi"), // 0x5f
  new Word("Cou"), // 0x60
  new Word("Gua"), // 0x61
  new Word("Ou"), // 0x62
  new Word("Di"), // 0x63
  new Word("An"), // 0x64
  new Word("Xing"), // 0x65
  new Word("Nao"), // 0x66
  new Word("Yu"), // 0x67
  new Word("Chuan"), // 0x68
  new Word("Nan"), // 0x69
  new Word("Yun"), // 0x6a
  new Word("Zhong"), // 0x6b
  new Word("Rou"), // 0x6c
  new Word("E"), // 0x6d
  new Word("Sai"), // 0x6e
  new Word("Tu"), // 0x6f
  new Word("Yao"), // 0x70
  new Word("Jian"), // 0x71
  new Word("Wei"), // 0x72
  new Word("Jiao"), // 0x73
  new Word("Yu"), // 0x74
  new Word("Jia"), // 0x75
  new Word("Duan"), // 0x76
  new Word("Bi"), // 0x77
  new Word("Chang"), // 0x78
  new Word("Fu"), // 0x79
  new Word("Xian"), // 0x7a
  new Word("Ni"), // 0x7b
  new Word("Mian"), // 0x7c
  new Word("Wa"), // 0x7d
  new Word("Teng"), // 0x7e
  new Word("Tui"), // 0x7f
  new Word("Bang"), // 0x80
  new Word("Qian"), // 0x81
  new Word("Lu"), // 0x82
  new Word("Wa"), // 0x83
  new Word("Sou"), // 0x84
  new Word("Tang"), // 0x85
  new Word("Su"), // 0x86
  new Word("Zhui"), // 0x87
  new Word("Ge"), // 0x88
  new Word("Yi"), // 0x89
  new Word("Bo"), // 0x8a
  new Word("Liao"), // 0x8b
  new Word("Ji"), // 0x8c
  new Word("Pi"), // 0x8d
  new Word("Xie"), // 0x8e
  new Word("Gao"), // 0x8f
  new Word("Lu"), // 0x90
  new Word("Bin"), // 0x91
  new Word("Ou"), // 0x92
  new Word("Chang"), // 0x93
  new Word("Lu"), // 0x94
  new Word("Guo"), // 0x95
  new Word("Pang"), // 0x96
  new Word("Chuai"), // 0x97
  new Word("Piao"), // 0x98
  new Word("Jiang"), // 0x99
  new Word("Fu"), // 0x9a
  new Word("Tang"), // 0x9b
  new Word("Mo"), // 0x9c
  new Word("Xi"), // 0x9d
  new Word("Zhuan"), // 0x9e
  new Word("Lu"), // 0x9f
  new Word("Jiao"), // 0xa0
  new Word("Ying"), // 0xa1
  new Word("Lu"), // 0xa2
  new Word("Zhi"), // 0xa3
  new Word("Tara"), // 0xa4
  new Word("Chun"), // 0xa5
  new Word("Lian"), // 0xa6
  new Word("Tong"), // 0xa7
  new Word("Peng"), // 0xa8
  new Word("Ni"), // 0xa9
  new Word("Zha"), // 0xaa
  new Word("Liao"), // 0xab
  new Word("Cui"), // 0xac
  new Word("Gui"), // 0xad
  new Word("Xiao"), // 0xae
  new Word("Teng"), // 0xaf
  new Word("Fan"), // 0xb0
  new Word("Zhi"), // 0xb1
  new Word("Jiao"), // 0xb2
  new Word("Shan"), // 0xb3
  new Word("Wu"), // 0xb4
  new Word("Cui"), // 0xb5
  new Word("Run"), // 0xb6
  new Word("Xiang"), // 0xb7
  new Word("Sui"), // 0xb8
  new Word("Fen"), // 0xb9
  new Word("Ying"), // 0xba
  new Word("Tan"), // 0xbb
  new Word("Zhua"), // 0xbc
  new Word("Dan"), // 0xbd
  new Word("Kuai"), // 0xbe
  new Word("Nong"), // 0xbf
  new Word("Tun"), // 0xc0
  new Word("Lian"), // 0xc1
  new Word("Bi"), // 0xc2
  new Word("Yong"), // 0xc3
  new Word("Jue"), // 0xc4
  new Word("Chu"), // 0xc5
  new Word("Yi"), // 0xc6
  new Word("Juan"), // 0xc7
  new Word("La"), // 0xc8
  new Word("Lian"), // 0xc9
  new Word("Sao"), // 0xca
  new Word("Tun"), // 0xcb
  new Word("Gu"), // 0xcc
  new Word("Qi"), // 0xcd
  new Word("Cui"), // 0xce
  new Word("Bin"), // 0xcf
  new Word("Xun"), // 0xd0
  new Word("Ru"), // 0xd1
  new Word("Huo"), // 0xd2
  new Word("Zang"), // 0xd3
  new Word("Xian"), // 0xd4
  new Word("Biao"), // 0xd5
  new Word("Xing"), // 0xd6
  new Word("Kuan"), // 0xd7
  new Word("La"), // 0xd8
  new Word("Yan"), // 0xd9
  new Word("Lu"), // 0xda
  new Word("Huo"), // 0xdb
  new Word("Zang"), // 0xdc
  new Word("Luo"), // 0xdd
  new Word("Qu"), // 0xde
  new Word("Zang"), // 0xdf
  new Word("Luan"), // 0xe0
  new Word("Ni"), // 0xe1
  new Word("Zang"), // 0xe2
  new Word("Chen"), // 0xe3
  new Word("Qian"), // 0xe4
  new Word("Wo"), // 0xe5
  new Word("Guang"), // 0xe6
  new Word("Zang"), // 0xe7
  new Word("Lin"), // 0xe8
  new Word("Guang"), // 0xe9
  new Word("Zi"), // 0xea
  new Word("Jiao"), // 0xeb
  new Word("Nie"), // 0xec
  new Word("Chou"), // 0xed
  new Word("Ji"), // 0xee
  new Word("Gao"), // 0xef
  new Word("Chou"), // 0xf0
  new Word("Mian"), // 0xf1
  new Word("Nie"), // 0xf2
  new Word("Zhi"), // 0xf3
  new Word("Zhi"), // 0xf4
  new Word("Ge"), // 0xf5
  new Word("Jian"), // 0xf6
  new Word("Die"), // 0xf7
  new Word("Zhi"), // 0xf8
  new Word("Xiu"), // 0xf9
  new Word("Tai"), // 0xfa
  new Word("Zhen"), // 0xfb
  new Word("Jiu"), // 0xfc
  new Word("Xian"), // 0xfd
  new Word("Yu"), // 0xfe
  new Word("Cha") // 0xff
  };
}