/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+82xx (CJK Unified Ideographs).
 */
final class X82 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Yao"), // 0x00
  new Word("Yu"), // 0x01
  new Word("Chong"), // 0x02
  new Word("Xi"), // 0x03
  new Word("Xi"), // 0x04
  new Word("Jiu"), // 0x05
  new Word("Yu"), // 0x06
  new Word("Yu"), // 0x07
  new Word("Xing"), // 0x08
  new Word("Ju"), // 0x09
  new Word("Jiu"), // 0x0a
  new Word("Xin"), // 0x0b
  new Word("She"), // 0x0c
  new Word("She"), // 0x0d
  new Word("Yadoru"), // 0x0e
  new Word("Jiu"), // 0x0f
  new Word("Shi"), // 0x10
  new Word("Tan"), // 0x11
  new Word("Shu"), // 0x12
  new Word("Shi"), // 0x13
  new Word("Tian"), // 0x14
  new Word("Dan"), // 0x15
  new Word("Pu"), // 0x16
  new Word("Pu"), // 0x17
  new Word("Guan"), // 0x18
  new Word("Hua"), // 0x19
  new Word("Tan"), // 0x1a
  new Word("Chuan"), // 0x1b
  new Word("Shun"), // 0x1c
  new Word("Xia"), // 0x1d
  new Word("Wu"), // 0x1e
  new Word("Zhou"), // 0x1f
  new Word("Dao"), // 0x20
  new Word("Gang"), // 0x21
  new Word("Shan"), // 0x22
  new Word("Yi"), // 0x23
  null, // 0x24
  new Word("Pa"), // 0x25
  new Word("Tai"), // 0x26
  new Word("Fan"), // 0x27
  new Word("Ban"), // 0x28
  new Word("Chuan"), // 0x29
  new Word("Hang"), // 0x2a
  new Word("Fang"), // 0x2b
  new Word("Ban"), // 0x2c
  new Word("Que"), // 0x2d
  new Word("Hesaki"), // 0x2e
  new Word("Zhong"), // 0x2f
  new Word("Jian"), // 0x30
  new Word("Cang"), // 0x31
  new Word("Ling"), // 0x32
  new Word("Zhu"), // 0x33
  new Word("Ze"), // 0x34
  new Word("Duo"), // 0x35
  new Word("Bo"), // 0x36
  new Word("Xian"), // 0x37
  new Word("Ge"), // 0x38
  new Word("Chuan"), // 0x39
  new Word("Jia"), // 0x3a
  new Word("Lu"), // 0x3b
  new Word("Hong"), // 0x3c
  new Word("Pang"), // 0x3d
  new Word("Xi"), // 0x3e
  null, // 0x3f
  new Word("Fu"), // 0x40
  new Word("Zao"), // 0x41
  new Word("Feng"), // 0x42
  new Word("Li"), // 0x43
  new Word("Shao"), // 0x44
  new Word("Yu"), // 0x45
  new Word("Lang"), // 0x46
  new Word("Ting"), // 0x47
  null, // 0x48
  new Word("Wei"), // 0x49
  new Word("Bo"), // 0x4a
  new Word("Meng"), // 0x4b
  new Word("Nian"), // 0x4c
  new Word("Ju"), // 0x4d
  new Word("Huang"), // 0x4e
  new Word("Shou"), // 0x4f
  new Word("Zong"), // 0x50
  new Word("Bian"), // 0x51
  new Word("Mao"), // 0x52
  new Word("Die"), // 0x53
  null, // 0x54
  new Word("Bang"), // 0x55
  new Word("Cha"), // 0x56
  new Word("Yi"), // 0x57
  new Word("Sao"), // 0x58
  new Word("Cang"), // 0x59
  new Word("Cao"), // 0x5a
  new Word("Lou"), // 0x5b
  new Word("Dai"), // 0x5c
  new Word("Sori"), // 0x5d
  new Word("Yao"), // 0x5e
  new Word("Tong"), // 0x5f
  new Word("Yofune"), // 0x60
  new Word("Dang"), // 0x61
  new Word("Tan"), // 0x62
  new Word("Lu"), // 0x63
  new Word("Yi"), // 0x64
  new Word("Jie"), // 0x65
  new Word("Jian"), // 0x66
  new Word("Huo"), // 0x67
  new Word("Meng"), // 0x68
  new Word("Qi"), // 0x69
  new Word("Lu"), // 0x6a
  new Word("Lu"), // 0x6b
  new Word("Chan"), // 0x6c
  new Word("Shuang"), // 0x6d
  new Word("Gen"), // 0x6e
  new Word("Liang"), // 0x6f
  new Word("Jian"), // 0x70
  new Word("Jian"), // 0x71
  new Word("Se"), // 0x72
  new Word("Yan"), // 0x73
  new Word("Fu"), // 0x74
  new Word("Ping"), // 0x75
  new Word("Yan"), // 0x76
  new Word("Yan"), // 0x77
  new Word("Cao"), // 0x78
  new Word("Cao"), // 0x79
  new Word("Yi"), // 0x7a
  new Word("Le"), // 0x7b
  new Word("Ting"), // 0x7c
  new Word("Qiu"), // 0x7d
  new Word("Ai"), // 0x7e
  new Word("Nai"), // 0x7f
  new Word("Tiao"), // 0x80
  new Word("Jiao"), // 0x81
  new Word("Jie"), // 0x82
  new Word("Peng"), // 0x83
  new Word("Wan"), // 0x84
  new Word("Yi"), // 0x85
  new Word("Chai"), // 0x86
  new Word("Mian"), // 0x87
  new Word("Mie"), // 0x88
  new Word("Gan"), // 0x89
  new Word("Qian"), // 0x8a
  new Word("Yu"), // 0x8b
  new Word("Yu"), // 0x8c
  new Word("Shuo"), // 0x8d
  new Word("Qiong"), // 0x8e
  new Word("Tu"), // 0x8f
  new Word("Xia"), // 0x90
  new Word("Qi"), // 0x91
  new Word("Mang"), // 0x92
  new Word("Zi"), // 0x93
  new Word("Hui"), // 0x94
  new Word("Sui"), // 0x95
  new Word("Zhi"), // 0x96
  new Word("Xiang"), // 0x97
  new Word("Bi"), // 0x98
  new Word("Fu"), // 0x99
  new Word("Tun"), // 0x9a
  new Word("Wei"), // 0x9b
  new Word("Wu"), // 0x9c
  new Word("Zhi"), // 0x9d
  new Word("Qi"), // 0x9e
  new Word("Shan"), // 0x9f
  new Word("Wen"), // 0xa0
  new Word("Qian"), // 0xa1
  new Word("Ren"), // 0xa2
  new Word("Fou"), // 0xa3
  new Word("Kou"), // 0xa4
  new Word("Jie"), // 0xa5
  new Word("Lu"), // 0xa6
  new Word("Xu"), // 0xa7
  new Word("Ji"), // 0xa8
  new Word("Qin"), // 0xa9
  new Word("Qi"), // 0xaa
  new Word("Yuan"), // 0xab
  new Word("Fen"), // 0xac
  new Word("Ba"), // 0xad
  new Word("Rui"), // 0xae
  new Word("Xin"), // 0xaf
  new Word("Ji"), // 0xb0
  new Word("Hua"), // 0xb1
  new Word("Hua"), // 0xb2
  new Word("Fang"), // 0xb3
  new Word("Wu"), // 0xb4
  new Word("Jue"), // 0xb5
  new Word("Gou"), // 0xb6
  new Word("Zhi"), // 0xb7
  new Word("Yun"), // 0xb8
  new Word("Qin"), // 0xb9
  new Word("Ao"), // 0xba
  new Word("Chu"), // 0xbb
  new Word("Mao"), // 0xbc
  new Word("Ya"), // 0xbd
  new Word("Fei"), // 0xbe
  new Word("Reng"), // 0xbf
  new Word("Hang"), // 0xc0
  new Word("Cong"), // 0xc1
  new Word("Yin"), // 0xc2
  new Word("You"), // 0xc3
  new Word("Bian"), // 0xc4
  new Word("Yi"), // 0xc5
  new Word("Susa"), // 0xc6
  new Word("Wei"), // 0xc7
  new Word("Li"), // 0xc8
  new Word("Pi"), // 0xc9
  new Word("E"), // 0xca
  new Word("Xian"), // 0xcb
  new Word("Chang"), // 0xcc
  new Word("Cang"), // 0xcd
  new Word("Meng"), // 0xce
  new Word("Su"), // 0xcf
  new Word("Yi"), // 0xd0
  new Word("Yuan"), // 0xd1
  new Word("Ran"), // 0xd2
  new Word("Ling"), // 0xd3
  new Word("Tai"), // 0xd4
  new Word("Tiao"), // 0xd5
  new Word("Di"), // 0xd6
  new Word("Miao"), // 0xd7
  new Word("Qiong"), // 0xd8
  new Word("Li"), // 0xd9
  new Word("Yong"), // 0xda
  new Word("Ke"), // 0xdb
  new Word("Mu"), // 0xdc
  new Word("Pei"), // 0xdd
  new Word("Bao"), // 0xde
  new Word("Gou"), // 0xdf
  new Word("Min"), // 0xe0
  new Word("Yi"), // 0xe1
  new Word("Yi"), // 0xe2
  new Word("Ju"), // 0xe3
  new Word("Pi"), // 0xe4
  new Word("Ruo"), // 0xe5
  new Word("Ku"), // 0xe6
  new Word("Zhu"), // 0xe7
  new Word("Ni"), // 0xe8
  new Word("Bo"), // 0xe9
  new Word("Bing"), // 0xea
  new Word("Shan"), // 0xeb
  new Word("Qiu"), // 0xec
  new Word("Yao"), // 0xed
  new Word("Xian"), // 0xee
  new Word("Ben"), // 0xef
  new Word("Hong"), // 0xf0
  new Word("Ying"), // 0xf1
  new Word("Zha"), // 0xf2
  new Word("Dong"), // 0xf3
  new Word("Ju"), // 0xf4
  new Word("Die"), // 0xf5
  new Word("Nie"), // 0xf6
  new Word("Gan"), // 0xf7
  new Word("Hu"), // 0xf8
  new Word("Ping"), // 0xf9
  new Word("Mei"), // 0xfa
  new Word("Fu"), // 0xfb
  new Word("Sheng"), // 0xfc
  new Word("Gu"), // 0xfd
  new Word("Bi"), // 0xfe
  new Word("Wei") // 0xff
  };
}