/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+83xx (CJK Unified Ideographs).
 */
final class X83 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Fu"), // 0x00
  new Word("Zhuo"), // 0x01
  new Word("Mao"), // 0x02
  new Word("Fan"), // 0x03
  new Word("Qie"), // 0x04
  new Word("Mao"), // 0x05
  new Word("Mao"), // 0x06
  new Word("Ba"), // 0x07
  new Word("Zi"), // 0x08
  new Word("Mo"), // 0x09
  new Word("Zi"), // 0x0a
  new Word("Di"), // 0x0b
  new Word("Chi"), // 0x0c
  new Word("Ji"), // 0x0d
  new Word("Jing"), // 0x0e
  new Word("Long"), // 0x0f
  null, // 0x10
  new Word("Niao"), // 0x11
  null, // 0x12
  new Word("Xue"), // 0x13
  new Word("Ying"), // 0x14
  new Word("Qiong"), // 0x15
  new Word("Ge"), // 0x16
  new Word("Ming"), // 0x17
  new Word("Li"), // 0x18
  new Word("Rong"), // 0x19
  new Word("Yin"), // 0x1a
  new Word("Gen"), // 0x1b
  new Word("Qian"), // 0x1c
  new Word("Chai"), // 0x1d
  new Word("Chen"), // 0x1e
  new Word("Yu"), // 0x1f
  new Word("Xiu"), // 0x20
  new Word("Zi"), // 0x21
  new Word("Lie"), // 0x22
  new Word("Wu"), // 0x23
  new Word("Ji"), // 0x24
  new Word("Kui"), // 0x25
  new Word("Ce"), // 0x26
  new Word("Chong"), // 0x27
  new Word("Ci"), // 0x28
  new Word("Gou"), // 0x29
  new Word("Guang"), // 0x2a
  new Word("Mang"), // 0x2b
  new Word("Chi"), // 0x2c
  new Word("Jiao"), // 0x2d
  new Word("Jiao"), // 0x2e
  new Word("Fu"), // 0x2f
  new Word("Yu"), // 0x30
  new Word("Zhu"), // 0x31
  new Word("Zi"), // 0x32
  new Word("Jiang"), // 0x33
  new Word("Hui"), // 0x34
  new Word("Yin"), // 0x35
  new Word("Cha"), // 0x36
  new Word("Fa"), // 0x37
  new Word("Rong"), // 0x38
  new Word("Ru"), // 0x39
  new Word("Chong"), // 0x3a
  new Word("Mang"), // 0x3b
  new Word("Tong"), // 0x3c
  new Word("Zhong"), // 0x3d
  null, // 0x3e
  new Word("Zhu"), // 0x3f
  new Word("Xun"), // 0x40
  new Word("Huan"), // 0x41
  new Word("Kua"), // 0x42
  new Word("Quan"), // 0x43
  new Word("Gai"), // 0x44
  new Word("Da"), // 0x45
  new Word("Jing"), // 0x46
  new Word("Xing"), // 0x47
  new Word("Quan"), // 0x48
  new Word("Cao"), // 0x49
  new Word("Jing"), // 0x4a
  new Word("Er"), // 0x4b
  new Word("An"), // 0x4c
  new Word("Shou"), // 0x4d
  new Word("Chi"), // 0x4e
  new Word("Ren"), // 0x4f
  new Word("Jian"), // 0x50
  new Word("Ti"), // 0x51
  new Word("Huang"), // 0x52
  new Word("Ping"), // 0x53
  new Word("Li"), // 0x54
  new Word("Jin"), // 0x55
  new Word("Lao"), // 0x56
  new Word("Shu"), // 0x57
  new Word("Zhuang"), // 0x58
  new Word("Da"), // 0x59
  new Word("Jia"), // 0x5a
  new Word("Rao"), // 0x5b
  new Word("Bi"), // 0x5c
  new Word("Ze"), // 0x5d
  new Word("Qiao"), // 0x5e
  new Word("Hui"), // 0x5f
  new Word("Qi"), // 0x60
  new Word("Dang"), // 0x61
  null, // 0x62
  new Word("Rong"), // 0x63
  new Word("Hun"), // 0x64
  new Word("Ying"), // 0x65
  new Word("Luo"), // 0x66
  new Word("Ying"), // 0x67
  new Word("Xun"), // 0x68
  new Word("Jin"), // 0x69
  new Word("Sun"), // 0x6a
  new Word("Yin"), // 0x6b
  new Word("Mai"), // 0x6c
  new Word("Hong"), // 0x6d
  new Word("Zhou"), // 0x6e
  new Word("Yao"), // 0x6f
  new Word("Du"), // 0x70
  new Word("Wei"), // 0x71
  new Word("Chu"), // 0x72
  new Word("Dou"), // 0x73
  new Word("Fu"), // 0x74
  new Word("Ren"), // 0x75
  new Word("Yin"), // 0x76
  new Word("He"), // 0x77
  new Word("Bi"), // 0x78
  new Word("Bu"), // 0x79
  new Word("Yun"), // 0x7a
  new Word("Di"), // 0x7b
  new Word("Tu"), // 0x7c
  new Word("Sui"), // 0x7d
  new Word("Sui"), // 0x7e
  new Word("Cheng"), // 0x7f
  new Word("Chen"), // 0x80
  new Word("Wu"), // 0x81
  new Word("Bie"), // 0x82
  new Word("Xi"), // 0x83
  new Word("Geng"), // 0x84
  new Word("Li"), // 0x85
  new Word("Fu"), // 0x86
  new Word("Zhu"), // 0x87
  new Word("Mo"), // 0x88
  new Word("Li"), // 0x89
  new Word("Zhuang"), // 0x8a
  new Word("Ji"), // 0x8b
  new Word("Duo"), // 0x8c
  new Word("Qiu"), // 0x8d
  new Word("Sha"), // 0x8e
  new Word("Suo"), // 0x8f
  new Word("Chen"), // 0x90
  new Word("Feng"), // 0x91
  new Word("Ju"), // 0x92
  new Word("Mei"), // 0x93
  new Word("Meng"), // 0x94
  new Word("Xing"), // 0x95
  new Word("Jing"), // 0x96
  new Word("Che"), // 0x97
  new Word("Xin"), // 0x98
  new Word("Jun"), // 0x99
  new Word("Yan"), // 0x9a
  new Word("Ting"), // 0x9b
  new Word("Diao"), // 0x9c
  new Word("Cuo"), // 0x9d
  new Word("Wan"), // 0x9e
  new Word("Han"), // 0x9f
  new Word("You"), // 0xa0
  new Word("Cuo"), // 0xa1
  new Word("Jia"), // 0xa2
  new Word("Wang"), // 0xa3
  new Word("You"), // 0xa4
  new Word("Niu"), // 0xa5
  new Word("Shao"), // 0xa6
  new Word("Xian"), // 0xa7
  new Word("Lang"), // 0xa8
  new Word("Fu"), // 0xa9
  new Word("E"), // 0xaa
  new Word("Mo"), // 0xab
  new Word("Wen"), // 0xac
  new Word("Jie"), // 0xad
  new Word("Nan"), // 0xae
  new Word("Mu"), // 0xaf
  new Word("Kan"), // 0xb0
  new Word("Lai"), // 0xb1
  new Word("Lian"), // 0xb2
  new Word("Shi"), // 0xb3
  new Word("Wo"), // 0xb4
  new Word("Usagi"), // 0xb5
  new Word("Lian"), // 0xb6
  new Word("Huo"), // 0xb7
  new Word("You"), // 0xb8
  new Word("Ying"), // 0xb9
  new Word("Ying"), // 0xba
  new Word("Nuc"), // 0xbb
  new Word("Chun"), // 0xbc
  new Word("Mang"), // 0xbd
  new Word("Mang"), // 0xbe
  new Word("Ci"), // 0xbf
  new Word("Wan"), // 0xc0
  new Word("Jing"), // 0xc1
  new Word("Di"), // 0xc2
  new Word("Qu"), // 0xc3
  new Word("Dong"), // 0xc4
  new Word("Jian"), // 0xc5
  new Word("Zou"), // 0xc6
  new Word("Gu"), // 0xc7
  new Word("La"), // 0xc8
  new Word("Lu"), // 0xc9
  new Word("Ju"), // 0xca
  new Word("Wei"), // 0xcb
  new Word("Jun"), // 0xcc
  new Word("Nie"), // 0xcd
  new Word("Kun"), // 0xce
  new Word("He"), // 0xcf
  new Word("Pu"), // 0xd0
  new Word("Zi"), // 0xd1
  new Word("Gao"), // 0xd2
  new Word("Guo"), // 0xd3
  new Word("Fu"), // 0xd4
  new Word("Lun"), // 0xd5
  new Word("Chang"), // 0xd6
  new Word("Chou"), // 0xd7
  new Word("Song"), // 0xd8
  new Word("Chui"), // 0xd9
  new Word("Zhan"), // 0xda
  new Word("Men"), // 0xdb
  new Word("Cai"), // 0xdc
  new Word("Ba"), // 0xdd
  new Word("Li"), // 0xde
  new Word("Tu"), // 0xdf
  new Word("Bo"), // 0xe0
  new Word("Han"), // 0xe1
  new Word("Bao"), // 0xe2
  new Word("Qin"), // 0xe3
  new Word("Juan"), // 0xe4
  new Word("Xi"), // 0xe5
  new Word("Qin"), // 0xe6
  new Word("Di"), // 0xe7
  new Word("Jie"), // 0xe8
  new Word("Pu"), // 0xe9
  new Word("Dang"), // 0xea
  new Word("Jin"), // 0xeb
  new Word("Zhao"), // 0xec
  new Word("Tai"), // 0xed
  new Word("Geng"), // 0xee
  new Word("Hua"), // 0xef
  new Word("Gu"), // 0xf0
  new Word("Ling"), // 0xf1
  new Word("Fei"), // 0xf2
  new Word("Jin"), // 0xf3
  new Word("An"), // 0xf4
  new Word("Wang"), // 0xf5
  new Word("Beng"), // 0xf6
  new Word("Zhou"), // 0xf7
  new Word("Yan"), // 0xf8
  new Word("Ju"), // 0xf9
  new Word("Jian"), // 0xfa
  new Word("Lin"), // 0xfb
  new Word("Tan"), // 0xfc
  new Word("Shu"), // 0xfd
  new Word("Tian"), // 0xfe
  new Word("Dao") // 0xff
  };
}