/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+84xx (CJK Unified Ideographs).
 */
final class X84 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Hu"), // 0x00
  new Word("Qi"), // 0x01
  new Word("He"), // 0x02
  new Word("Cui"), // 0x03
  new Word("Tao"), // 0x04
  new Word("Chun"), // 0x05
  new Word("Bei"), // 0x06
  new Word("Chang"), // 0x07
  new Word("Huan"), // 0x08
  new Word("Fei"), // 0x09
  new Word("Lai"), // 0x0a
  new Word("Qi"), // 0x0b
  new Word("Meng"), // 0x0c
  new Word("Ping"), // 0x0d
  new Word("Wei"), // 0x0e
  new Word("Dan"), // 0x0f
  new Word("Sha"), // 0x10
  new Word("Huan"), // 0x11
  new Word("Yan"), // 0x12
  new Word("Yi"), // 0x13
  new Word("Tiao"), // 0x14
  new Word("Qi"), // 0x15
  new Word("Wan"), // 0x16
  new Word("Ce"), // 0x17
  new Word("Nai"), // 0x18
  new Word("Kutabireru"), // 0x19
  new Word("Tuo"), // 0x1a
  new Word("Jiu"), // 0x1b
  new Word("Tie"), // 0x1c
  new Word("Luo"), // 0x1d
  null, // 0x1e
  null, // 0x1f
  new Word("Meng"), // 0x20
  null, // 0x21
  new Word("Yaji"), // 0x22
  null, // 0x23
  new Word("Ying"), // 0x24
  new Word("Ying"), // 0x25
  new Word("Ying"), // 0x26
  new Word("Xiao"), // 0x27
  new Word("Sa"), // 0x28
  new Word("Qiu"), // 0x29
  new Word("Ke"), // 0x2a
  new Word("Xiang"), // 0x2b
  new Word("Wan"), // 0x2c
  new Word("Yu"), // 0x2d
  new Word("Yu"), // 0x2e
  new Word("Fu"), // 0x2f
  new Word("Lian"), // 0x30
  new Word("Xuan"), // 0x31
  new Word("Yuan"), // 0x32
  new Word("Nan"), // 0x33
  new Word("Ze"), // 0x34
  new Word("Wo"), // 0x35
  new Word("Chun"), // 0x36
  new Word("Xiao"), // 0x37
  new Word("Yu"), // 0x38
  new Word("Pian"), // 0x39
  new Word("Mao"), // 0x3a
  new Word("An"), // 0x3b
  new Word("E"), // 0x3c
  new Word("Luo"), // 0x3d
  new Word("Ying"), // 0x3e
  new Word("Huo"), // 0x3f
  new Word("Gua"), // 0x40
  new Word("Jiang"), // 0x41
  new Word("Mian"), // 0x42
  new Word("Zuo"), // 0x43
  new Word("Zuo"), // 0x44
  new Word("Ju"), // 0x45
  new Word("Bao"), // 0x46
  new Word("Rou"), // 0x47
  new Word("Xi"), // 0x48
  new Word("Xie"), // 0x49
  new Word("An"), // 0x4a
  new Word("Qu"), // 0x4b
  new Word("Jian"), // 0x4c
  new Word("Fu"), // 0x4d
  new Word("Lu"), // 0x4e
  new Word("Jing"), // 0x4f
  new Word("Pen"), // 0x50
  new Word("Feng"), // 0x51
  new Word("Hong"), // 0x52
  new Word("Hong"), // 0x53
  new Word("Hou"), // 0x54
  new Word("Yan"), // 0x55
  new Word("Tu"), // 0x56
  new Word("Zhu"), // 0x57
  new Word("Zi"), // 0x58
  new Word("Xiang"), // 0x59
  new Word("Shen"), // 0x5a
  new Word("Ge"), // 0x5b
  new Word("Jie"), // 0x5c
  new Word("Jing"), // 0x5d
  new Word("Mi"), // 0x5e
  new Word("Huang"), // 0x5f
  new Word("Shen"), // 0x60
  new Word("Pu"), // 0x61
  new Word("Gai"), // 0x62
  new Word("Dong"), // 0x63
  new Word("Zhou"), // 0x64
  new Word("Qian"), // 0x65
  new Word("Wei"), // 0x66
  new Word("Bo"), // 0x67
  new Word("Wei"), // 0x68
  new Word("Pa"), // 0x69
  new Word("Ji"), // 0x6a
  new Word("Hu"), // 0x6b
  new Word("Zang"), // 0x6c
  new Word("Jia"), // 0x6d
  new Word("Duan"), // 0x6e
  new Word("Yao"), // 0x6f
  new Word("Jun"), // 0x70
  new Word("Cong"), // 0x71
  new Word("Quan"), // 0x72
  new Word("Wei"), // 0x73
  new Word("Xian"), // 0x74
  new Word("Kui"), // 0x75
  new Word("Ting"), // 0x76
  new Word("Hun"), // 0x77
  new Word("Xi"), // 0x78
  new Word("Shi"), // 0x79
  new Word("Qi"), // 0x7a
  new Word("Lan"), // 0x7b
  new Word("Zong"), // 0x7c
  new Word("Yao"), // 0x7d
  new Word("Yuan"), // 0x7e
  new Word("Mei"), // 0x7f
  new Word("Yun"), // 0x80
  new Word("Shu"), // 0x81
  new Word("Di"), // 0x82
  new Word("Zhuan"), // 0x83
  new Word("Guan"), // 0x84
  new Word("Sukumo"), // 0x85
  new Word("Xue"), // 0x86
  new Word("Chan"), // 0x87
  new Word("Kai"), // 0x88
  new Word("Kui"), // 0x89
  null, // 0x8a
  new Word("Jiang"), // 0x8b
  new Word("Lou"), // 0x8c
  new Word("Wei"), // 0x8d
  new Word("Pai"), // 0x8e
  null, // 0x8f
  new Word("Sou"), // 0x90
  new Word("Yin"), // 0x91
  new Word("Shi"), // 0x92
  new Word("Chun"), // 0x93
  new Word("Shi"), // 0x94
  new Word("Yun"), // 0x95
  new Word("Zhen"), // 0x96
  new Word("Lang"), // 0x97
  new Word("Nu"), // 0x98
  new Word("Meng"), // 0x99
  new Word("He"), // 0x9a
  new Word("Que"), // 0x9b
  new Word("Suan"), // 0x9c
  new Word("Yuan"), // 0x9d
  new Word("Li"), // 0x9e
  new Word("Ju"), // 0x9f
  new Word("Xi"), // 0xa0
  new Word("Pang"), // 0xa1
  new Word("Chu"), // 0xa2
  new Word("Xu"), // 0xa3
  new Word("Tu"), // 0xa4
  new Word("Liu"), // 0xa5
  new Word("Wo"), // 0xa6
  new Word("Zhen"), // 0xa7
  new Word("Qian"), // 0xa8
  new Word("Zu"), // 0xa9
  new Word("Po"), // 0xaa
  new Word("Cuo"), // 0xab
  new Word("Yuan"), // 0xac
  new Word("Chu"), // 0xad
  new Word("Yu"), // 0xae
  new Word("Kuai"), // 0xaf
  new Word("Pan"), // 0xb0
  new Word("Pu"), // 0xb1
  new Word("Pu"), // 0xb2
  new Word("Na"), // 0xb3
  new Word("Shuo"), // 0xb4
  new Word("Xi"), // 0xb5
  new Word("Fen"), // 0xb6
  new Word("Yun"), // 0xb7
  new Word("Zheng"), // 0xb8
  new Word("Jian"), // 0xb9
  new Word("Ji"), // 0xba
  new Word("Ruo"), // 0xbb
  new Word("Cang"), // 0xbc
  new Word("En"), // 0xbd
  new Word("Mi"), // 0xbe
  new Word("Hao"), // 0xbf
  new Word("Sun"), // 0xc0
  new Word("Zhen"), // 0xc1
  new Word("Ming"), // 0xc2
  new Word("Sou"), // 0xc3
  new Word("Xu"), // 0xc4
  new Word("Liu"), // 0xc5
  new Word("Xi"), // 0xc6
  new Word("Gu"), // 0xc7
  new Word("Lang"), // 0xc8
  new Word("Rong"), // 0xc9
  new Word("Weng"), // 0xca
  new Word("Gai"), // 0xcb
  new Word("Cuo"), // 0xcc
  new Word("Shi"), // 0xcd
  new Word("Tang"), // 0xce
  new Word("Luo"), // 0xcf
  new Word("Ru"), // 0xd0
  new Word("Suo"), // 0xd1
  new Word("Xian"), // 0xd2
  new Word("Bei"), // 0xd3
  new Word("Yao"), // 0xd4
  new Word("Gui"), // 0xd5
  new Word("Bi"), // 0xd6
  new Word("Zong"), // 0xd7
  new Word("Gun"), // 0xd8
  new Word("Za"), // 0xd9
  new Word("Xiu"), // 0xda
  new Word("Ce"), // 0xdb
  new Word("Hai"), // 0xdc
  new Word("Lan"), // 0xdd
  null, // 0xde
  new Word("Ji"), // 0xdf
  new Word("Li"), // 0xe0
  new Word("Can"), // 0xe1
  new Word("Lang"), // 0xe2
  new Word("Yu"), // 0xe3
  null, // 0xe4
  new Word("Ying"), // 0xe5
  new Word("Mo"), // 0xe6
  new Word("Diao"), // 0xe7
  new Word("Tiao"), // 0xe8
  new Word("Mao"), // 0xe9
  new Word("Tong"), // 0xea
  new Word("Zhu"), // 0xeb
  new Word("Peng"), // 0xec
  new Word("An"), // 0xed
  new Word("Lian"), // 0xee
  new Word("Cong"), // 0xef
  new Word("Xi"), // 0xf0
  new Word("Ping"), // 0xf1
  new Word("Qiu"), // 0xf2
  new Word("Jin"), // 0xf3
  new Word("Chun"), // 0xf4
  new Word("Jie"), // 0xf5
  new Word("Wei"), // 0xf6
  new Word("Tui"), // 0xf7
  new Word("Cao"), // 0xf8
  new Word("Yu"), // 0xf9
  new Word("Yi"), // 0xfa
  new Word("Ji"), // 0xfb
  new Word("Liao"), // 0xfc
  new Word("Bi"), // 0xfd
  new Word("Lu"), // 0xfe
  new Word("Su") // 0xff
  };
}