/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+85xx (CJK Unified Ideographs).
 */
final class X85 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Bu"), // 0x00
  new Word("Zhang"), // 0x01
  new Word("Luo"), // 0x02
  new Word("Jiang"), // 0x03
  new Word("Man"), // 0x04
  new Word("Yan"), // 0x05
  new Word("Ling"), // 0x06
  new Word("Ji"), // 0x07
  new Word("Piao"), // 0x08
  new Word("Gun"), // 0x09
  new Word("Han"), // 0x0a
  new Word("Di"), // 0x0b
  new Word("Su"), // 0x0c
  new Word("Lu"), // 0x0d
  new Word("She"), // 0x0e
  new Word("Shang"), // 0x0f
  new Word("Di"), // 0x10
  new Word("Mie"), // 0x11
  new Word("Xun"), // 0x12
  new Word("Man"), // 0x13
  new Word("Bo"), // 0x14
  new Word("Di"), // 0x15
  new Word("Cuo"), // 0x16
  new Word("Zhe"), // 0x17
  new Word("Sen"), // 0x18
  new Word("Xuan"), // 0x19
  new Word("Wei"), // 0x1a
  new Word("Hu"), // 0x1b
  new Word("Ao"), // 0x1c
  new Word("Mi"), // 0x1d
  new Word("Lou"), // 0x1e
  new Word("Cu"), // 0x1f
  new Word("Zhong"), // 0x20
  new Word("Cai"), // 0x21
  new Word("Po"), // 0x22
  new Word("Jiang"), // 0x23
  new Word("Mi"), // 0x24
  new Word("Cong"), // 0x25
  new Word("Niao"), // 0x26
  new Word("Hui"), // 0x27
  new Word("Jun"), // 0x28
  new Word("Yin"), // 0x29
  new Word("Jian"), // 0x2a
  new Word("Yan"), // 0x2b
  new Word("Shu"), // 0x2c
  new Word("Yin"), // 0x2d
  new Word("Kui"), // 0x2e
  new Word("Chen"), // 0x2f
  new Word("Hu"), // 0x30
  new Word("Sha"), // 0x31
  new Word("Kou"), // 0x32
  new Word("Qian"), // 0x33
  new Word("Ma"), // 0x34
  new Word("Zang"), // 0x35
  new Word("Sonoko"), // 0x36
  new Word("Qiang"), // 0x37
  new Word("Dou"), // 0x38
  new Word("Lian"), // 0x39
  new Word("Lin"), // 0x3a
  new Word("Kou"), // 0x3b
  new Word("Ai"), // 0x3c
  new Word("Bi"), // 0x3d
  new Word("Li"), // 0x3e
  new Word("Wei"), // 0x3f
  new Word("Ji"), // 0x40
  new Word("Xun"), // 0x41
  new Word("Sheng"), // 0x42
  new Word("Fan"), // 0x43
  new Word("Meng"), // 0x44
  new Word("Ou"), // 0x45
  new Word("Chan"), // 0x46
  new Word("Dian"), // 0x47
  new Word("Xun"), // 0x48
  new Word("Jiao"), // 0x49
  new Word("Rui"), // 0x4a
  new Word("Rui"), // 0x4b
  new Word("Lei"), // 0x4c
  new Word("Yu"), // 0x4d
  new Word("Qiao"), // 0x4e
  new Word("Chu"), // 0x4f
  new Word("Hua"), // 0x50
  new Word("Jian"), // 0x51
  new Word("Mai"), // 0x52
  new Word("Yun"), // 0x53
  new Word("Bao"), // 0x54
  new Word("You"), // 0x55
  new Word("Qu"), // 0x56
  new Word("Lu"), // 0x57
  new Word("Rao"), // 0x58
  new Word("Hui"), // 0x59
  new Word("E"), // 0x5a
  new Word("Teng"), // 0x5b
  new Word("Fei"), // 0x5c
  new Word("Jue"), // 0x5d
  new Word("Zui"), // 0x5e
  new Word("Fa"), // 0x5f
  new Word("Ru"), // 0x60
  new Word("Fen"), // 0x61
  new Word("Kui"), // 0x62
  new Word("Shun"), // 0x63
  new Word("Rui"), // 0x64
  new Word("Ya"), // 0x65
  new Word("Xu"), // 0x66
  new Word("Fu"), // 0x67
  new Word("Jue"), // 0x68
  new Word("Dang"), // 0x69
  new Word("Wu"), // 0x6a
  new Word("Tong"), // 0x6b
  new Word("Si"), // 0x6c
  new Word("Xiao"), // 0x6d
  new Word("Xi"), // 0x6e
  new Word("Long"), // 0x6f
  new Word("Yun"), // 0x70
  null, // 0x71
  new Word("Qi"), // 0x72
  new Word("Jian"), // 0x73
  new Word("Yun"), // 0x74
  new Word("Sun"), // 0x75
  new Word("Ling"), // 0x76
  new Word("Yu"), // 0x77
  new Word("Xia"), // 0x78
  new Word("Yong"), // 0x79
  new Word("Ji"), // 0x7a
  new Word("Hong"), // 0x7b
  new Word("Si"), // 0x7c
  new Word("Nong"), // 0x7d
  new Word("Lei"), // 0x7e
  new Word("Xuan"), // 0x7f
  new Word("Yun"), // 0x80
  new Word("Yu"), // 0x81
  new Word("Xi"), // 0x82
  new Word("Hao"), // 0x83
  new Word("Bo"), // 0x84
  new Word("Hao"), // 0x85
  new Word("Ai"), // 0x86
  new Word("Wei"), // 0x87
  new Word("Hui"), // 0x88
  new Word("Wei"), // 0x89
  new Word("Ji"), // 0x8a
  new Word("Ci"), // 0x8b
  new Word("Xiang"), // 0x8c
  new Word("Luan"), // 0x8d
  new Word("Mie"), // 0x8e
  new Word("Yi"), // 0x8f
  new Word("Leng"), // 0x90
  new Word("Jiang"), // 0x91
  new Word("Can"), // 0x92
  new Word("Shen"), // 0x93
  new Word("Qiang"), // 0x94
  new Word("Lian"), // 0x95
  new Word("Ke"), // 0x96
  new Word("Yuan"), // 0x97
  new Word("Da"), // 0x98
  new Word("Ti"), // 0x99
  new Word("Tang"), // 0x9a
  new Word("Xie"), // 0x9b
  new Word("Bi"), // 0x9c
  new Word("Zhan"), // 0x9d
  new Word("Sun"), // 0x9e
  new Word("Lian"), // 0x9f
  new Word("Fan"), // 0xa0
  new Word("Ding"), // 0xa1
  new Word("Jie"), // 0xa2
  new Word("Gu"), // 0xa3
  new Word("Xie"), // 0xa4
  new Word("Shu"), // 0xa5
  new Word("Jian"), // 0xa6
  new Word("Kao"), // 0xa7
  new Word("Hong"), // 0xa8
  new Word("Sa"), // 0xa9
  new Word("Xin"), // 0xaa
  new Word("Xun"), // 0xab
  new Word("Yao"), // 0xac
  new Word("Hie"), // 0xad
  new Word("Sou"), // 0xae
  new Word("Shu"), // 0xaf
  new Word("Xun"), // 0xb0
  new Word("Dui"), // 0xb1
  new Word("Pin"), // 0xb2
  new Word("Wei"), // 0xb3
  new Word("Neng"), // 0xb4
  new Word("Chou"), // 0xb5
  new Word("Mai"), // 0xb6
  new Word("Ru"), // 0xb7
  new Word("Piao"), // 0xb8
  new Word("Tai"), // 0xb9
  new Word("Qi"), // 0xba
  new Word("Zao"), // 0xbb
  new Word("Chen"), // 0xbc
  new Word("Zhen"), // 0xbd
  new Word("Er"), // 0xbe
  new Word("Ni"), // 0xbf
  new Word("Ying"), // 0xc0
  new Word("Gao"), // 0xc1
  new Word("Cong"), // 0xc2
  new Word("Xiao"), // 0xc3
  new Word("Qi"), // 0xc4
  new Word("Fa"), // 0xc5
  new Word("Jian"), // 0xc6
  new Word("Xu"), // 0xc7
  new Word("Kui"), // 0xc8
  new Word("Jie"), // 0xc9
  new Word("Bian"), // 0xca
  new Word("Diao"), // 0xcb
  new Word("Mi"), // 0xcc
  new Word("Lan"), // 0xcd
  new Word("Jin"), // 0xce
  new Word("Cang"), // 0xcf
  new Word("Miao"), // 0xd0
  new Word("Qiong"), // 0xd1
  new Word("Qie"), // 0xd2
  new Word("Xian"), // 0xd3
  null, // 0xd4
  new Word("Ou"), // 0xd5
  new Word("Xian"), // 0xd6
  new Word("Su"), // 0xd7
  new Word("Lu"), // 0xd8
  new Word("Yi"), // 0xd9
  new Word("Xu"), // 0xda
  new Word("Xie"), // 0xdb
  new Word("Li"), // 0xdc
  new Word("Yi"), // 0xdd
  new Word("La"), // 0xde
  new Word("Lei"), // 0xdf
  new Word("Xiao"), // 0xe0
  new Word("Di"), // 0xe1
  new Word("Zhi"), // 0xe2
  new Word("Bei"), // 0xe3
  new Word("Teng"), // 0xe4
  new Word("Yao"), // 0xe5
  new Word("Mo"), // 0xe6
  new Word("Huan"), // 0xe7
  new Word("Piao"), // 0xe8
  new Word("Fan"), // 0xe9
  new Word("Sou"), // 0xea
  new Word("Tan"), // 0xeb
  new Word("Tui"), // 0xec
  new Word("Qiong"), // 0xed
  new Word("Qiao"), // 0xee
  new Word("Wei"), // 0xef
  new Word("Liu"), // 0xf0
  new Word("Hui"), // 0xf1
  null, // 0xf2
  new Word("Gao"), // 0xf3
  new Word("Yun"), // 0xf4
  null, // 0xf5
  new Word("Li"), // 0xf6
  new Word("Shu"), // 0xf7
  new Word("Chu"), // 0xf8
  new Word("Ai"), // 0xf9
  new Word("Lin"), // 0xfa
  new Word("Zao"), // 0xfb
  new Word("Xuan"), // 0xfc
  new Word("Chen"), // 0xfd
  new Word("Lai"), // 0xfe
  new Word("Huo") // 0xff
  };
}