/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+88xx (CJK Unified Ideographs).
 */
final class X88 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Ci"), // 0x00
  new Word("Xiang"), // 0x01
  new Word("She"), // 0x02
  new Word("Luo"), // 0x03
  new Word("Qin"), // 0x04
  new Word("Ying"), // 0x05
  new Word("Chai"), // 0x06
  new Word("Li"), // 0x07
  new Word("Ze"), // 0x08
  new Word("Xuan"), // 0x09
  new Word("Lian"), // 0x0a
  new Word("Zhu"), // 0x0b
  new Word("Ze"), // 0x0c
  new Word("Xie"), // 0x0d
  new Word("Mang"), // 0x0e
  new Word("Xie"), // 0x0f
  new Word("Qi"), // 0x10
  new Word("Rong"), // 0x11
  new Word("Jian"), // 0x12
  new Word("Meng"), // 0x13
  new Word("Hao"), // 0x14
  new Word("Ruan"), // 0x15
  new Word("Huo"), // 0x16
  new Word("Zhuo"), // 0x17
  new Word("Jie"), // 0x18
  new Word("Bin"), // 0x19
  new Word("He"), // 0x1a
  new Word("Mie"), // 0x1b
  new Word("Fan"), // 0x1c
  new Word("Lei"), // 0x1d
  new Word("Jie"), // 0x1e
  new Word("La"), // 0x1f
  new Word("Mi"), // 0x20
  new Word("Li"), // 0x21
  new Word("Chun"), // 0x22
  new Word("Li"), // 0x23
  new Word("Qiu"), // 0x24
  new Word("Nie"), // 0x25
  new Word("Lu"), // 0x26
  new Word("Du"), // 0x27
  new Word("Xiao"), // 0x28
  new Word("Zhu"), // 0x29
  new Word("Long"), // 0x2a
  new Word("Li"), // 0x2b
  new Word("Long"), // 0x2c
  new Word("Feng"), // 0x2d
  new Word("Ye"), // 0x2e
  new Word("Beng"), // 0x2f
  new Word("Shang"), // 0x30
  new Word("Gu"), // 0x31
  new Word("Juan"), // 0x32
  new Word("Ying"), // 0x33
  null, // 0x34
  new Word("Xi"), // 0x35
  new Word("Can"), // 0x36
  new Word("Qu"), // 0x37
  new Word("Quan"), // 0x38
  new Word("Du"), // 0x39
  new Word("Can"), // 0x3a
  new Word("Man"), // 0x3b
  new Word("Jue"), // 0x3c
  new Word("Jie"), // 0x3d
  new Word("Zhu"), // 0x3e
  new Word("Zha"), // 0x3f
  new Word("Xie"), // 0x40
  new Word("Huang"), // 0x41
  new Word("Niu"), // 0x42
  new Word("Pei"), // 0x43
  new Word("Nu"), // 0x44
  new Word("Xin"), // 0x45
  new Word("Zhong"), // 0x46
  new Word("Mo"), // 0x47
  new Word("Er"), // 0x48
  new Word("Ke"), // 0x49
  new Word("Mie"), // 0x4a
  new Word("Xi"), // 0x4b
  new Word("Xing"), // 0x4c
  new Word("Yan"), // 0x4d
  new Word("Kan"), // 0x4e
  new Word("Yuan"), // 0x4f
  null, // 0x50
  new Word("Ling"), // 0x51
  new Word("Xuan"), // 0x52
  new Word("Shu"), // 0x53
  new Word("Xian"), // 0x54
  new Word("Tong"), // 0x55
  new Word("Long"), // 0x56
  new Word("Jie"), // 0x57
  new Word("Xian"), // 0x58
  new Word("Ya"), // 0x59
  new Word("Hu"), // 0x5a
  new Word("Wei"), // 0x5b
  new Word("Dao"), // 0x5c
  new Word("Chong"), // 0x5d
  new Word("Wei"), // 0x5e
  new Word("Dao"), // 0x5f
  new Word("Zhun"), // 0x60
  new Word("Heng"), // 0x61
  new Word("Qu"), // 0x62
  new Word("Yi"), // 0x63
  new Word("Yi"), // 0x64
  new Word("Bu"), // 0x65
  new Word("Gan"), // 0x66
  new Word("Yu"), // 0x67
  new Word("Biao"), // 0x68
  new Word("Cha"), // 0x69
  new Word("Yi"), // 0x6a
  new Word("Shan"), // 0x6b
  new Word("Chen"), // 0x6c
  new Word("Fu"), // 0x6d
  new Word("Gun"), // 0x6e
  new Word("Fen"), // 0x6f
  new Word("Shuai"), // 0x70
  new Word("Jie"), // 0x71
  new Word("Na"), // 0x72
  new Word("Zhong"), // 0x73
  new Word("Dan"), // 0x74
  new Word("Ri"), // 0x75
  new Word("Zhong"), // 0x76
  new Word("Zhong"), // 0x77
  new Word("Xie"), // 0x78
  new Word("Qi"), // 0x79
  new Word("Xie"), // 0x7a
  new Word("Ran"), // 0x7b
  new Word("Zhi"), // 0x7c
  new Word("Ren"), // 0x7d
  new Word("Qin"), // 0x7e
  new Word("Jin"), // 0x7f
  new Word("Jun"), // 0x80
  new Word("Yuan"), // 0x81
  new Word("Mei"), // 0x82
  new Word("Chai"), // 0x83
  new Word("Ao"), // 0x84
  new Word("Niao"), // 0x85
  new Word("Hui"), // 0x86
  new Word("Ran"), // 0x87
  new Word("Jia"), // 0x88
  new Word("Tuo"), // 0x89
  new Word("Ling"), // 0x8a
  new Word("Dai"), // 0x8b
  new Word("Bao"), // 0x8c
  new Word("Pao"), // 0x8d
  new Word("Yao"), // 0x8e
  new Word("Zuo"), // 0x8f
  new Word("Bi"), // 0x90
  new Word("Shao"), // 0x91
  new Word("Tan"), // 0x92
  new Word("Ju"), // 0x93
  new Word("He"), // 0x94
  new Word("Shu"), // 0x95
  new Word("Xiu"), // 0x96
  new Word("Zhen"), // 0x97
  new Word("Yi"), // 0x98
  new Word("Pa"), // 0x99
  new Word("Bo"), // 0x9a
  new Word("Di"), // 0x9b
  new Word("Wa"), // 0x9c
  new Word("Fu"), // 0x9d
  new Word("Gun"), // 0x9e
  new Word("Zhi"), // 0x9f
  new Word("Zhi"), // 0xa0
  new Word("Ran"), // 0xa1
  new Word("Pan"), // 0xa2
  new Word("Yi"), // 0xa3
  new Word("Mao"), // 0xa4
  new Word("Tuo"), // 0xa5
  new Word("Na"), // 0xa6
  new Word("Kou"), // 0xa7
  new Word("Xian"), // 0xa8
  new Word("Chan"), // 0xa9
  new Word("Qu"), // 0xaa
  new Word("Bei"), // 0xab
  new Word("Gun"), // 0xac
  new Word("Xi"), // 0xad
  new Word("Ne"), // 0xae
  new Word("Bo"), // 0xaf
  new Word("Horo"), // 0xb0
  new Word("Fu"), // 0xb1
  new Word("Yi"), // 0xb2
  new Word("Chi"), // 0xb3
  new Word("Ku"), // 0xb4
  new Word("Ren"), // 0xb5
  new Word("Jiang"), // 0xb6
  new Word("Jia"), // 0xb7
  new Word("Cun"), // 0xb8
  new Word("Mo"), // 0xb9
  new Word("Jie"), // 0xba
  new Word("Er"), // 0xbb
  new Word("Luo"), // 0xbc
  new Word("Ru"), // 0xbd
  new Word("Zhu"), // 0xbe
  new Word("Gui"), // 0xbf
  new Word("Yin"), // 0xc0
  new Word("Cai"), // 0xc1
  new Word("Lie"), // 0xc2
  new Word("Kamishimo"), // 0xc3
  new Word("Yuki"), // 0xc4
  new Word("Zhuang"), // 0xc5
  new Word("Dang"), // 0xc6
  null, // 0xc7
  new Word("Kun"), // 0xc8
  new Word("Ken"), // 0xc9
  new Word("Niao"), // 0xca
  new Word("Shu"), // 0xcb
  new Word("Jia"), // 0xcc
  new Word("Kun"), // 0xcd
  new Word("Cheng"), // 0xce
  new Word("Li"), // 0xcf
  new Word("Juan"), // 0xd0
  new Word("Shen"), // 0xd1
  new Word("Pou"), // 0xd2
  new Word("Ge"), // 0xd3
  new Word("Yi"), // 0xd4
  new Word("Yu"), // 0xd5
  new Word("Zhen"), // 0xd6
  new Word("Liu"), // 0xd7
  new Word("Qiu"), // 0xd8
  new Word("Qun"), // 0xd9
  new Word("Ji"), // 0xda
  new Word("Yi"), // 0xdb
  new Word("Bu"), // 0xdc
  new Word("Zhuang"), // 0xdd
  new Word("Shui"), // 0xde
  new Word("Sha"), // 0xdf
  new Word("Qun"), // 0xe0
  new Word("Li"), // 0xe1
  new Word("Lian"), // 0xe2
  new Word("Lian"), // 0xe3
  new Word("Ku"), // 0xe4
  new Word("Jian"), // 0xe5
  new Word("Fou"), // 0xe6
  new Word("Chan"), // 0xe7
  new Word("Bi"), // 0xe8
  new Word("Gun"), // 0xe9
  new Word("Tao"), // 0xea
  new Word("Yuan"), // 0xeb
  new Word("Ling"), // 0xec
  new Word("Chi"), // 0xed
  new Word("Chang"), // 0xee
  new Word("Chou"), // 0xef
  new Word("Duo"), // 0xf0
  new Word("Biao"), // 0xf1
  new Word("Liang"), // 0xf2
  new Word("Chang"), // 0xf3
  new Word("Pei"), // 0xf4
  new Word("Pei"), // 0xf5
  new Word("Fei"), // 0xf6
  new Word("Yuan"), // 0xf7
  new Word("Luo"), // 0xf8
  new Word("Guo"), // 0xf9
  new Word("Yan"), // 0xfa
  new Word("Du"), // 0xfb
  new Word("Xi"), // 0xfc
  new Word("Zhi"), // 0xfd
  new Word("Ju"), // 0xfe
  new Word("Qi") // 0xff
  };
}