/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+8Fxx (CJK Unified Ideographs).
 */
final class X8f extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Er"), // 0x00
  new Word("Qiong"), // 0x01
  new Word("Ju"), // 0x02
  new Word("Jiao"), // 0x03
  new Word("Guang"), // 0x04
  new Word("Lu"), // 0x05
  new Word("Kai"), // 0x06
  new Word("Quan"), // 0x07
  new Word("Zhou"), // 0x08
  new Word("Zai"), // 0x09
  new Word("Zhi"), // 0x0a
  new Word("She"), // 0x0b
  new Word("Liang"), // 0x0c
  new Word("Yu"), // 0x0d
  new Word("Shao"), // 0x0e
  new Word("You"), // 0x0f
  new Word("Huan"), // 0x10
  new Word("Yun"), // 0x11
  new Word("Zhe"), // 0x12
  new Word("Wan"), // 0x13
  new Word("Fu"), // 0x14
  new Word("Qing"), // 0x15
  new Word("Zhou"), // 0x16
  new Word("Ni"), // 0x17
  new Word("Ling"), // 0x18
  new Word("Zhe"), // 0x19
  new Word("Zhan"), // 0x1a
  new Word("Liang"), // 0x1b
  new Word("Zi"), // 0x1c
  new Word("Hui"), // 0x1d
  new Word("Wang"), // 0x1e
  new Word("Chuo"), // 0x1f
  new Word("Guo"), // 0x20
  new Word("Kan"), // 0x21
  new Word("Yi"), // 0x22
  new Word("Peng"), // 0x23
  new Word("Qian"), // 0x24
  new Word("Gun"), // 0x25
  new Word("Nian"), // 0x26
  new Word("Pian"), // 0x27
  new Word("Guan"), // 0x28
  new Word("Bei"), // 0x29
  new Word("Lun"), // 0x2a
  new Word("Pai"), // 0x2b
  new Word("Liang"), // 0x2c
  new Word("Ruan"), // 0x2d
  new Word("Rou"), // 0x2e
  new Word("Ji"), // 0x2f
  new Word("Yang"), // 0x30
  new Word("Xian"), // 0x31
  new Word("Chuan"), // 0x32
  new Word("Cou"), // 0x33
  new Word("Qun"), // 0x34
  new Word("Ge"), // 0x35
  new Word("You"), // 0x36
  new Word("Hong"), // 0x37
  new Word("Shu"), // 0x38
  new Word("Fu"), // 0x39
  new Word("Zi"), // 0x3a
  new Word("Fu"), // 0x3b
  new Word("Wen"), // 0x3c
  new Word("Ben"), // 0x3d
  new Word("Zhan"), // 0x3e
  new Word("Yu"), // 0x3f
  new Word("Wen"), // 0x40
  new Word("Tao"), // 0x41
  new Word("Gu"), // 0x42
  new Word("Zhen"), // 0x43
  new Word("Xia"), // 0x44
  new Word("Yuan"), // 0x45
  new Word("Lu"), // 0x46
  new Word("Jiu"), // 0x47
  new Word("Chao"), // 0x48
  new Word("Zhuan"), // 0x49
  new Word("Wei"), // 0x4a
  new Word("Hun"), // 0x4b
  new Word("Sori"), // 0x4c
  new Word("Che"), // 0x4d
  new Word("Jiao"), // 0x4e
  new Word("Zhan"), // 0x4f
  new Word("Pu"), // 0x50
  new Word("Lao"), // 0x51
  new Word("Fen"), // 0x52
  new Word("Fan"), // 0x53
  new Word("Lin"), // 0x54
  new Word("Ge"), // 0x55
  new Word("Se"), // 0x56
  new Word("Kan"), // 0x57
  new Word("Huan"), // 0x58
  new Word("Yi"), // 0x59
  new Word("Ji"), // 0x5a
  new Word("Dui"), // 0x5b
  new Word("Er"), // 0x5c
  new Word("Yu"), // 0x5d
  new Word("Xian"), // 0x5e
  new Word("Hong"), // 0x5f
  new Word("Lei"), // 0x60
  new Word("Pei"), // 0x61
  new Word("Li"), // 0x62
  new Word("Li"), // 0x63
  new Word("Lu"), // 0x64
  new Word("Lin"), // 0x65
  new Word("Che"), // 0x66
  new Word("Ya"), // 0x67
  new Word("Gui"), // 0x68
  new Word("Xuan"), // 0x69
  new Word("Di"), // 0x6a
  new Word("Ren"), // 0x6b
  new Word("Zhuan"), // 0x6c
  new Word("E"), // 0x6d
  new Word("Lun"), // 0x6e
  new Word("Ruan"), // 0x6f
  new Word("Hong"), // 0x70
  new Word("Ku"), // 0x71
  new Word("Ke"), // 0x72
  new Word("Lu"), // 0x73
  new Word("Zhou"), // 0x74
  new Word("Zhi"), // 0x75
  new Word("Yi"), // 0x76
  new Word("Hu"), // 0x77
  new Word("Zhen"), // 0x78
  new Word("Li"), // 0x79
  new Word("Yao"), // 0x7a
  new Word("Qing"), // 0x7b
  new Word("Shi"), // 0x7c
  new Word("Zai"), // 0x7d
  new Word("Zhi"), // 0x7e
  new Word("Jiao"), // 0x7f
  new Word("Zhou"), // 0x80
  new Word("Quan"), // 0x81
  new Word("Lu"), // 0x82
  new Word("Jiao"), // 0x83
  new Word("Zhe"), // 0x84
  new Word("Fu"), // 0x85
  new Word("Liang"), // 0x86
  new Word("Nian"), // 0x87
  new Word("Bei"), // 0x88
  new Word("Hui"), // 0x89
  new Word("Gun"), // 0x8a
  new Word("Wang"), // 0x8b
  new Word("Liang"), // 0x8c
  new Word("Chuo"), // 0x8d
  new Word("Zi"), // 0x8e
  new Word("Cou"), // 0x8f
  new Word("Fu"), // 0x90
  new Word("Ji"), // 0x91
  new Word("Wen"), // 0x92
  new Word("Shu"), // 0x93
  new Word("Pei"), // 0x94
  new Word("Yuan"), // 0x95
  new Word("Xia"), // 0x96
  new Word("Zhan"), // 0x97
  new Word("Lu"), // 0x98
  new Word("Che"), // 0x99
  new Word("Lin"), // 0x9a
  new Word("Xin"), // 0x9b
  new Word("Gu"), // 0x9c
  new Word("Ci"), // 0x9d
  new Word("Ci"), // 0x9e
  new Word("Pi"), // 0x9f
  new Word("Zui"), // 0xa0
  new Word("Bian"), // 0xa1
  new Word("La"), // 0xa2
  new Word("La"), // 0xa3
  new Word("Ci"), // 0xa4
  new Word("Xue"), // 0xa5
  new Word("Ban"), // 0xa6
  new Word("Bian"), // 0xa7
  new Word("Bian"), // 0xa8
  new Word("Bian"), // 0xa9
  null, // 0xaa
  new Word("Bian"), // 0xab
  new Word("Ban"), // 0xac
  new Word("Ci"), // 0xad
  new Word("Bian"), // 0xae
  new Word("Bian"), // 0xaf
  new Word("Chen"), // 0xb0
  new Word("Ru"), // 0xb1
  new Word("Nong"), // 0xb2
  new Word("Nong"), // 0xb3
  new Word("Zhen"), // 0xb4
  new Word("Chuo"), // 0xb5
  new Word("Chuo"), // 0xb6
  new Word("Suberu"), // 0xb7
  new Word("Reng"), // 0xb8
  new Word("Bian"), // 0xb9
  new Word("Bian"), // 0xba
  new Word("Sip"), // 0xbb
  new Word("Ip"), // 0xbc
  new Word("Liao"), // 0xbd
  new Word("Da"), // 0xbe
  new Word("Chan"), // 0xbf
  new Word("Gan"), // 0xc0
  new Word("Qian"), // 0xc1
  new Word("Yu"), // 0xc2
  new Word("Yu"), // 0xc3
  new Word("Qi"), // 0xc4
  new Word("Xun"), // 0xc5
  new Word("Yi"), // 0xc6
  new Word("Guo"), // 0xc7
  new Word("Mai"), // 0xc8
  new Word("Qi"), // 0xc9
  new Word("Za"), // 0xca
  new Word("Wang"), // 0xcb
  new Word("Jia"), // 0xcc
  new Word("Zhun"), // 0xcd
  new Word("Ying"), // 0xce
  new Word("Ti"), // 0xcf
  new Word("Yun"), // 0xd0
  new Word("Jin"), // 0xd1
  new Word("Hang"), // 0xd2
  new Word("Ya"), // 0xd3
  new Word("Fan"), // 0xd4
  new Word("Wu"), // 0xd5
  new Word("Da"), // 0xd6
  new Word("E"), // 0xd7
  new Word("Huan"), // 0xd8
  new Word("Zhe"), // 0xd9
  new Word("Totemo"), // 0xda
  new Word("Jin"), // 0xdb
  new Word("Yuan"), // 0xdc
  new Word("Wei"), // 0xdd
  new Word("Lian"), // 0xde
  new Word("Chi"), // 0xdf
  new Word("Che"), // 0xe0
  new Word("Ni"), // 0xe1
  new Word("Tiao"), // 0xe2
  new Word("Zhi"), // 0xe3
  new Word("Yi"), // 0xe4
  new Word("Jiong"), // 0xe5
  new Word("Jia"), // 0xe6
  new Word("Chen"), // 0xe7
  new Word("Dai"), // 0xe8
  new Word("Er"), // 0xe9
  new Word("Di"), // 0xea
  new Word("Po"), // 0xeb
  new Word("Wang"), // 0xec
  new Word("Die"), // 0xed
  new Word("Ze"), // 0xee
  new Word("Tao"), // 0xef
  new Word("Shu"), // 0xf0
  new Word("Tuo"), // 0xf1
  new Word("Kep"), // 0xf2
  new Word("Jing"), // 0xf3
  new Word("Hui"), // 0xf4
  new Word("Tong"), // 0xf5
  new Word("You"), // 0xf6
  new Word("Mi"), // 0xf7
  new Word("Beng"), // 0xf8
  new Word("Ji"), // 0xf9
  new Word("Nai"), // 0xfa
  new Word("Yi"), // 0xfb
  new Word("Jie"), // 0xfc
  new Word("Zhui"), // 0xfd
  new Word("Lie"), // 0xfe
  new Word("Xun") // 0xff
  };
}