/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+90xx (CJK Unified Ideographs).
 */
final class X90 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Tui"), // 0x00
  new Word("Song"), // 0x01
  new Word("Gua"), // 0x02
  new Word("Tao"), // 0x03
  new Word("Pang"), // 0x04
  new Word("Hou"), // 0x05
  new Word("Ni"), // 0x06
  new Word("Dun"), // 0x07
  new Word("Jiong"), // 0x08
  new Word("Xuan"), // 0x09
  new Word("Xun"), // 0x0a
  new Word("Bu"), // 0x0b
  new Word("You"), // 0x0c
  new Word("Xiao"), // 0x0d
  new Word("Qiu"), // 0x0e
  new Word("Tou"), // 0x0f
  new Word("Zhu"), // 0x10
  new Word("Qiu"), // 0x11
  new Word("Di"), // 0x12
  new Word("Di"), // 0x13
  new Word("Tu"), // 0x14
  new Word("Jing"), // 0x15
  new Word("Ti"), // 0x16
  new Word("Dou"), // 0x17
  new Word("Yi"), // 0x18
  new Word("Zhe"), // 0x19
  new Word("Tong"), // 0x1a
  new Word("Guang"), // 0x1b
  new Word("Wu"), // 0x1c
  new Word("Shi"), // 0x1d
  new Word("Cheng"), // 0x1e
  new Word("Su"), // 0x1f
  new Word("Zao"), // 0x20
  new Word("Qun"), // 0x21
  new Word("Feng"), // 0x22
  new Word("Lian"), // 0x23
  new Word("Suo"), // 0x24
  new Word("Hui"), // 0x25
  new Word("Li"), // 0x26
  new Word("Sako"), // 0x27
  new Word("Lai"), // 0x28
  new Word("Ben"), // 0x29
  new Word("Cuo"), // 0x2a
  new Word("Jue"), // 0x2b
  new Word("Beng"), // 0x2c
  new Word("Huan"), // 0x2d
  new Word("Dai"), // 0x2e
  new Word("Lu"), // 0x2f
  new Word("You"), // 0x30
  new Word("Zhou"), // 0x31
  new Word("Jin"), // 0x32
  new Word("Yu"), // 0x33
  new Word("Chuo"), // 0x34
  new Word("Kui"), // 0x35
  new Word("Wei"), // 0x36
  new Word("Ti"), // 0x37
  new Word("Yi"), // 0x38
  new Word("Da"), // 0x39
  new Word("Yuan"), // 0x3a
  new Word("Luo"), // 0x3b
  new Word("Bi"), // 0x3c
  new Word("Nuo"), // 0x3d
  new Word("Yu"), // 0x3e
  new Word("Dang"), // 0x3f
  new Word("Sui"), // 0x40
  new Word("Dun"), // 0x41
  new Word("Sui"), // 0x42
  new Word("Yan"), // 0x43
  new Word("Chuan"), // 0x44
  new Word("Chi"), // 0x45
  new Word("Ti"), // 0x46
  new Word("Yu"), // 0x47
  new Word("Shi"), // 0x48
  new Word("Zhen"), // 0x49
  new Word("You"), // 0x4a
  new Word("Yun"), // 0x4b
  new Word("E"), // 0x4c
  new Word("Bian"), // 0x4d
  new Word("Guo"), // 0x4e
  new Word("E"), // 0x4f
  new Word("Xia"), // 0x50
  new Word("Huang"), // 0x51
  new Word("Qiu"), // 0x52
  new Word("Dao"), // 0x53
  new Word("Da"), // 0x54
  new Word("Wei"), // 0x55
  new Word("Appare"), // 0x56
  new Word("Yi"), // 0x57
  new Word("Gou"), // 0x58
  new Word("Yao"), // 0x59
  new Word("Chu"), // 0x5a
  new Word("Liu"), // 0x5b
  new Word("Xun"), // 0x5c
  new Word("Ta"), // 0x5d
  new Word("Di"), // 0x5e
  new Word("Chi"), // 0x5f
  new Word("Yuan"), // 0x60
  new Word("Su"), // 0x61
  new Word("Ta"), // 0x62
  new Word("Qian"), // 0x63
  null, // 0x64
  new Word("Yao"), // 0x65
  new Word("Guan"), // 0x66
  new Word("Zhang"), // 0x67
  new Word("Ao"), // 0x68
  new Word("Shi"), // 0x69
  new Word("Ce"), // 0x6a
  new Word("Chi"), // 0x6b
  new Word("Su"), // 0x6c
  new Word("Zao"), // 0x6d
  new Word("Zhe"), // 0x6e
  new Word("Dun"), // 0x6f
  new Word("Di"), // 0x70
  new Word("Lou"), // 0x71
  new Word("Chi"), // 0x72
  new Word("Cuo"), // 0x73
  new Word("Lin"), // 0x74
  new Word("Zun"), // 0x75
  new Word("Rao"), // 0x76
  new Word("Qian"), // 0x77
  new Word("Xuan"), // 0x78
  new Word("Yu"), // 0x79
  new Word("Yi"), // 0x7a
  new Word("Wu"), // 0x7b
  new Word("Liao"), // 0x7c
  new Word("Ju"), // 0x7d
  new Word("Shi"), // 0x7e
  new Word("Bi"), // 0x7f
  new Word("Yao"), // 0x80
  new Word("Mai"), // 0x81
  new Word("Xie"), // 0x82
  new Word("Sui"), // 0x83
  new Word("Huan"), // 0x84
  new Word("Zhan"), // 0x85
  new Word("Teng"), // 0x86
  new Word("Er"), // 0x87
  new Word("Miao"), // 0x88
  new Word("Bian"), // 0x89
  new Word("Bian"), // 0x8a
  new Word("La"), // 0x8b
  new Word("Li"), // 0x8c
  new Word("Yuan"), // 0x8d
  new Word("Yao"), // 0x8e
  new Word("Luo"), // 0x8f
  new Word("Li"), // 0x90
  new Word("Yi"), // 0x91
  new Word("Ting"), // 0x92
  new Word("Deng"), // 0x93
  new Word("Qi"), // 0x94
  new Word("Yong"), // 0x95
  new Word("Shan"), // 0x96
  new Word("Han"), // 0x97
  new Word("Yu"), // 0x98
  new Word("Mang"), // 0x99
  new Word("Ru"), // 0x9a
  new Word("Qiong"), // 0x9b
  null, // 0x9c
  new Word("Kuang"), // 0x9d
  new Word("Fu"), // 0x9e
  new Word("Kang"), // 0x9f
  new Word("Bin"), // 0xa0
  new Word("Fang"), // 0xa1
  new Word("Xing"), // 0xa2
  new Word("Na"), // 0xa3
  new Word("Xin"), // 0xa4
  new Word("Shen"), // 0xa5
  new Word("Bang"), // 0xa6
  new Word("Yuan"), // 0xa7
  new Word("Cun"), // 0xa8
  new Word("Huo"), // 0xa9
  new Word("Xie"), // 0xaa
  new Word("Bang"), // 0xab
  new Word("Wu"), // 0xac
  new Word("Ju"), // 0xad
  new Word("You"), // 0xae
  new Word("Han"), // 0xaf
  new Word("Tai"), // 0xb0
  new Word("Qiu"), // 0xb1
  new Word("Bi"), // 0xb2
  new Word("Pei"), // 0xb3
  new Word("Bing"), // 0xb4
  new Word("Shao"), // 0xb5
  new Word("Bei"), // 0xb6
  new Word("Wa"), // 0xb7
  new Word("Di"), // 0xb8
  new Word("Zou"), // 0xb9
  new Word("Ye"), // 0xba
  new Word("Lin"), // 0xbb
  new Word("Kuang"), // 0xbc
  new Word("Gui"), // 0xbd
  new Word("Zhu"), // 0xbe
  new Word("Shi"), // 0xbf
  new Word("Ku"), // 0xc0
  new Word("Yu"), // 0xc1
  new Word("Gai"), // 0xc2
  new Word("Ge"), // 0xc3
  new Word("Xi"), // 0xc4
  new Word("Zhi"), // 0xc5
  new Word("Ji"), // 0xc6
  new Word("Xun"), // 0xc7
  new Word("Hou"), // 0xc8
  new Word("Xing"), // 0xc9
  new Word("Jiao"), // 0xca
  new Word("Xi"), // 0xcb
  new Word("Gui"), // 0xcc
  new Word("Nuo"), // 0xcd
  new Word("Lang"), // 0xce
  new Word("Jia"), // 0xcf
  new Word("Kuai"), // 0xd0
  new Word("Zheng"), // 0xd1
  new Word("Otoko"), // 0xd2
  new Word("Yun"), // 0xd3
  new Word("Yan"), // 0xd4
  new Word("Cheng"), // 0xd5
  new Word("Dou"), // 0xd6
  new Word("Chi"), // 0xd7
  new Word("Lu"), // 0xd8
  new Word("Fu"), // 0xd9
  new Word("Wu"), // 0xda
  new Word("Fu"), // 0xdb
  new Word("Gao"), // 0xdc
  new Word("Hao"), // 0xdd
  new Word("Lang"), // 0xde
  new Word("Jia"), // 0xdf
  new Word("Geng"), // 0xe0
  new Word("Jun"), // 0xe1
  new Word("Ying"), // 0xe2
  new Word("Bo"), // 0xe3
  new Word("Xi"), // 0xe4
  new Word("Bei"), // 0xe5
  new Word("Li"), // 0xe6
  new Word("Yun"), // 0xe7
  new Word("Bu"), // 0xe8
  new Word("Xiao"), // 0xe9
  new Word("Qi"), // 0xea
  new Word("Pi"), // 0xeb
  new Word("Qing"), // 0xec
  new Word("Guo"), // 0xed
  new Word("Zhou"), // 0xee
  new Word("Tan"), // 0xef
  new Word("Zou"), // 0xf0
  new Word("Ping"), // 0xf1
  new Word("Lai"), // 0xf2
  new Word("Ni"), // 0xf3
  new Word("Chen"), // 0xf4
  new Word("You"), // 0xf5
  new Word("Bu"), // 0xf6
  new Word("Xiang"), // 0xf7
  new Word("Dan"), // 0xf8
  new Word("Ju"), // 0xf9
  new Word("Yong"), // 0xfa
  new Word("Qiao"), // 0xfb
  new Word("Yi"), // 0xfc
  new Word("Du"), // 0xfd
  new Word("Yan"), // 0xfe
  new Word("Mei") // 0xff
  };
}