/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+91xx (CJK Unified Ideographs).
 */
final class X91 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Ruo"), // 0x00
  new Word("Bei"), // 0x01
  new Word("E"), // 0x02
  new Word("Yu"), // 0x03
  new Word("Juan"), // 0x04
  new Word("Yu"), // 0x05
  new Word("Yun"), // 0x06
  new Word("Hou"), // 0x07
  new Word("Kui"), // 0x08
  new Word("Xiang"), // 0x09
  new Word("Xiang"), // 0x0a
  new Word("Sou"), // 0x0b
  new Word("Tang"), // 0x0c
  new Word("Ming"), // 0x0d
  new Word("Xi"), // 0x0e
  new Word("Ru"), // 0x0f
  new Word("Chu"), // 0x10
  new Word("Zi"), // 0x11
  new Word("Zou"), // 0x12
  new Word("Ju"), // 0x13
  new Word("Wu"), // 0x14
  new Word("Xiang"), // 0x15
  new Word("Yun"), // 0x16
  new Word("Hao"), // 0x17
  new Word("Yong"), // 0x18
  new Word("Bi"), // 0x19
  new Word("Mo"), // 0x1a
  new Word("Chao"), // 0x1b
  new Word("Fu"), // 0x1c
  new Word("Liao"), // 0x1d
  new Word("Yin"), // 0x1e
  new Word("Zhuan"), // 0x1f
  new Word("Hu"), // 0x20
  new Word("Qiao"), // 0x21
  new Word("Yan"), // 0x22
  new Word("Zhang"), // 0x23
  new Word("Fan"), // 0x24
  new Word("Qiao"), // 0x25
  new Word("Xu"), // 0x26
  new Word("Deng"), // 0x27
  new Word("Bi"), // 0x28
  new Word("Xin"), // 0x29
  new Word("Bi"), // 0x2a
  new Word("Ceng"), // 0x2b
  new Word("Wei"), // 0x2c
  new Word("Zheng"), // 0x2d
  new Word("Mao"), // 0x2e
  new Word("Shan"), // 0x2f
  new Word("Lin"), // 0x30
  new Word("Po"), // 0x31
  new Word("Dan"), // 0x32
  new Word("Meng"), // 0x33
  new Word("Ye"), // 0x34
  new Word("Cao"), // 0x35
  new Word("Kuai"), // 0x36
  new Word("Feng"), // 0x37
  new Word("Meng"), // 0x38
  new Word("Zou"), // 0x39
  new Word("Kuang"), // 0x3a
  new Word("Lian"), // 0x3b
  new Word("Zan"), // 0x3c
  new Word("Chan"), // 0x3d
  new Word("You"), // 0x3e
  new Word("Qi"), // 0x3f
  new Word("Yan"), // 0x40
  new Word("Chan"), // 0x41
  new Word("Zan"), // 0x42
  new Word("Ling"), // 0x43
  new Word("Huan"), // 0x44
  new Word("Xi"), // 0x45
  new Word("Feng"), // 0x46
  new Word("Zan"), // 0x47
  new Word("Li"), // 0x48
  new Word("You"), // 0x49
  new Word("Ding"), // 0x4a
  new Word("Qiu"), // 0x4b
  new Word("Zhuo"), // 0x4c
  new Word("Pei"), // 0x4d
  new Word("Zhou"), // 0x4e
  new Word("Yi"), // 0x4f
  new Word("Hang"), // 0x50
  new Word("Yu"), // 0x51
  new Word("Jiu"), // 0x52
  new Word("Yan"), // 0x53
  new Word("Zui"), // 0x54
  new Word("Mao"), // 0x55
  new Word("Dan"), // 0x56
  new Word("Xu"), // 0x57
  new Word("Tou"), // 0x58
  new Word("Zhen"), // 0x59
  new Word("Fen"), // 0x5a
  new Word("Sakenomoto"), // 0x5b
  null, // 0x5c
  new Word("Yun"), // 0x5d
  new Word("Tai"), // 0x5e
  new Word("Tian"), // 0x5f
  new Word("Qia"), // 0x60
  new Word("Tuo"), // 0x61
  new Word("Zuo"), // 0x62
  new Word("Han"), // 0x63
  new Word("Gu"), // 0x64
  new Word("Su"), // 0x65
  new Word("Po"), // 0x66
  new Word("Chou"), // 0x67
  new Word("Zai"), // 0x68
  new Word("Ming"), // 0x69
  new Word("Luo"), // 0x6a
  new Word("Chuo"), // 0x6b
  new Word("Chou"), // 0x6c
  new Word("You"), // 0x6d
  new Word("Tong"), // 0x6e
  new Word("Zhi"), // 0x6f
  new Word("Xian"), // 0x70
  new Word("Jiang"), // 0x71
  new Word("Cheng"), // 0x72
  new Word("Yin"), // 0x73
  new Word("Tu"), // 0x74
  new Word("Xiao"), // 0x75
  new Word("Mei"), // 0x76
  new Word("Ku"), // 0x77
  new Word("Suan"), // 0x78
  new Word("Lei"), // 0x79
  new Word("Pu"), // 0x7a
  new Word("Zui"), // 0x7b
  new Word("Hai"), // 0x7c
  new Word("Yan"), // 0x7d
  new Word("Xi"), // 0x7e
  new Word("Niang"), // 0x7f
  new Word("Wei"), // 0x80
  new Word("Lu"), // 0x81
  new Word("Lan"), // 0x82
  new Word("Yan"), // 0x83
  new Word("Tao"), // 0x84
  new Word("Pei"), // 0x85
  new Word("Zhan"), // 0x86
  new Word("Chun"), // 0x87
  new Word("Tan"), // 0x88
  new Word("Zui"), // 0x89
  new Word("Chuo"), // 0x8a
  new Word("Cu"), // 0x8b
  new Word("Kun"), // 0x8c
  new Word("Ti"), // 0x8d
  new Word("Mian"), // 0x8e
  new Word("Du"), // 0x8f
  new Word("Hu"), // 0x90
  new Word("Xu"), // 0x91
  new Word("Xing"), // 0x92
  new Word("Tan"), // 0x93
  new Word("Jiu"), // 0x94
  new Word("Chun"), // 0x95
  new Word("Yun"), // 0x96
  new Word("Po"), // 0x97
  new Word("Ke"), // 0x98
  new Word("Sou"), // 0x99
  new Word("Mi"), // 0x9a
  new Word("Quan"), // 0x9b
  new Word("Chou"), // 0x9c
  new Word("Cuo"), // 0x9d
  new Word("Yun"), // 0x9e
  new Word("Yong"), // 0x9f
  new Word("Ang"), // 0xa0
  new Word("Zha"), // 0xa1
  new Word("Hai"), // 0xa2
  new Word("Tang"), // 0xa3
  new Word("Jiang"), // 0xa4
  new Word("Piao"), // 0xa5
  new Word("Shan"), // 0xa6
  new Word("Yu"), // 0xa7
  new Word("Li"), // 0xa8
  new Word("Zao"), // 0xa9
  new Word("Lao"), // 0xaa
  new Word("Yi"), // 0xab
  new Word("Jiang"), // 0xac
  new Word("Pu"), // 0xad
  new Word("Jiao"), // 0xae
  new Word("Xi"), // 0xaf
  new Word("Tan"), // 0xb0
  new Word("Po"), // 0xb1
  new Word("Nong"), // 0xb2
  new Word("Yi"), // 0xb3
  new Word("Li"), // 0xb4
  new Word("Ju"), // 0xb5
  new Word("Jiao"), // 0xb6
  new Word("Yi"), // 0xb7
  new Word("Niang"), // 0xb8
  new Word("Ru"), // 0xb9
  new Word("Xun"), // 0xba
  new Word("Chou"), // 0xbb
  new Word("Yan"), // 0xbc
  new Word("Ling"), // 0xbd
  new Word("Mi"), // 0xbe
  new Word("Mi"), // 0xbf
  new Word("Niang"), // 0xc0
  new Word("Xin"), // 0xc1
  new Word("Jiao"), // 0xc2
  new Word("Xi"), // 0xc3
  new Word("Mi"), // 0xc4
  new Word("Yan"), // 0xc5
  new Word("Bian"), // 0xc6
  new Word("Cai"), // 0xc7
  new Word("Shi"), // 0xc8
  new Word("You"), // 0xc9
  new Word("Shi"), // 0xca
  new Word("Shi"), // 0xcb
  new Word("Li"), // 0xcc
  new Word("Zhong"), // 0xcd
  new Word("Ye"), // 0xce
  new Word("Liang"), // 0xcf
  new Word("Li"), // 0xd0
  new Word("Jin"), // 0xd1
  new Word("Jin"), // 0xd2
  new Word("Qiu"), // 0xd3
  new Word("Yi"), // 0xd4
  new Word("Diao"), // 0xd5
  new Word("Dao"), // 0xd6
  new Word("Zhao"), // 0xd7
  new Word("Ding"), // 0xd8
  new Word("Po"), // 0xd9
  new Word("Qiu"), // 0xda
  new Word("He"), // 0xdb
  new Word("Fu"), // 0xdc
  new Word("Zhen"), // 0xdd
  new Word("Zhi"), // 0xde
  new Word("Ba"), // 0xdf
  new Word("Luan"), // 0xe0
  new Word("Fu"), // 0xe1
  new Word("Nai"), // 0xe2
  new Word("Diao"), // 0xe3
  new Word("Shan"), // 0xe4
  new Word("Qiao"), // 0xe5
  new Word("Kou"), // 0xe6
  new Word("Chuan"), // 0xe7
  new Word("Zi"), // 0xe8
  new Word("Fan"), // 0xe9
  new Word("Yu"), // 0xea
  new Word("Hua"), // 0xeb
  new Word("Han"), // 0xec
  new Word("Gong"), // 0xed
  new Word("Qi"), // 0xee
  new Word("Mang"), // 0xef
  new Word("Ri"), // 0xf0
  new Word("Di"), // 0xf1
  new Word("Si"), // 0xf2
  new Word("Xi"), // 0xf3
  new Word("Yi"), // 0xf4
  new Word("Chai"), // 0xf5
  new Word("Shi"), // 0xf6
  new Word("Tu"), // 0xf7
  new Word("Xi"), // 0xf8
  new Word("Nu"), // 0xf9
  new Word("Qian"), // 0xfa
  new Word("Ishiyumi"), // 0xfb
  new Word("Jian"), // 0xfc
  new Word("Pi"), // 0xfd
  new Word("Ye"), // 0xfe
  new Word("Yin") // 0xff
  };
}