/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+92xx (CJK Unified Ideographs).
 */
final class X92 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Ba"), // 0x00
  new Word("Fang"), // 0x01
  new Word("Chen"), // 0x02
  new Word("Xing"), // 0x03
  new Word("Tou"), // 0x04
  new Word("Yue"), // 0x05
  new Word("Yan"), // 0x06
  new Word("Fu"), // 0x07
  new Word("Pi"), // 0x08
  new Word("Na"), // 0x09
  new Word("Xin"), // 0x0a
  new Word("E"), // 0x0b
  new Word("Jue"), // 0x0c
  new Word("Dun"), // 0x0d
  new Word("Gou"), // 0x0e
  new Word("Yin"), // 0x0f
  new Word("Qian"), // 0x10
  new Word("Ban"), // 0x11
  new Word("Ji"), // 0x12
  new Word("Ren"), // 0x13
  new Word("Chao"), // 0x14
  new Word("Niu"), // 0x15
  new Word("Fen"), // 0x16
  new Word("Yun"), // 0x17
  new Word("Ji"), // 0x18
  new Word("Qin"), // 0x19
  new Word("Pi"), // 0x1a
  new Word("Guo"), // 0x1b
  new Word("Hong"), // 0x1c
  new Word("Yin"), // 0x1d
  new Word("Jun"), // 0x1e
  new Word("Shi"), // 0x1f
  new Word("Yi"), // 0x20
  new Word("Zhong"), // 0x21
  new Word("Nie"), // 0x22
  new Word("Gai"), // 0x23
  new Word("Ri"), // 0x24
  new Word("Huo"), // 0x25
  new Word("Tai"), // 0x26
  new Word("Kang"), // 0x27
  new Word("Habaki"), // 0x28
  new Word("Irori"), // 0x29
  new Word("Ngaak"), // 0x2a
  null, // 0x2b
  new Word("Duo"), // 0x2c
  new Word("Zi"), // 0x2d
  new Word("Ni"), // 0x2e
  new Word("Tu"), // 0x2f
  new Word("Shi"), // 0x30
  new Word("Min"), // 0x31
  new Word("Gu"), // 0x32
  new Word("E"), // 0x33
  new Word("Ling"), // 0x34
  new Word("Bing"), // 0x35
  new Word("Yi"), // 0x36
  new Word("Gu"), // 0x37
  new Word("Ba"), // 0x38
  new Word("Pi"), // 0x39
  new Word("Yu"), // 0x3a
  new Word("Si"), // 0x3b
  new Word("Zuo"), // 0x3c
  new Word("Bu"), // 0x3d
  new Word("You"), // 0x3e
  new Word("Dian"), // 0x3f
  new Word("Jia"), // 0x40
  new Word("Zhen"), // 0x41
  new Word("Shi"), // 0x42
  new Word("Shi"), // 0x43
  new Word("Tie"), // 0x44
  new Word("Ju"), // 0x45
  new Word("Zhan"), // 0x46
  new Word("Shi"), // 0x47
  new Word("She"), // 0x48
  new Word("Xuan"), // 0x49
  new Word("Zhao"), // 0x4a
  new Word("Bao"), // 0x4b
  new Word("He"), // 0x4c
  new Word("Bi"), // 0x4d
  new Word("Sheng"), // 0x4e
  new Word("Chu"), // 0x4f
  new Word("Shi"), // 0x50
  new Word("Bo"), // 0x51
  new Word("Zhu"), // 0x52
  new Word("Chi"), // 0x53
  new Word("Za"), // 0x54
  new Word("Po"), // 0x55
  new Word("Tong"), // 0x56
  new Word("Qian"), // 0x57
  new Word("Fu"), // 0x58
  new Word("Zhai"), // 0x59
  new Word("Liu"), // 0x5a
  new Word("Qian"), // 0x5b
  new Word("Fu"), // 0x5c
  new Word("Li"), // 0x5d
  new Word("Yue"), // 0x5e
  new Word("Pi"), // 0x5f
  new Word("Yang"), // 0x60
  new Word("Ban"), // 0x61
  new Word("Bo"), // 0x62
  new Word("Jie"), // 0x63
  new Word("Gou"), // 0x64
  new Word("Shu"), // 0x65
  new Word("Zheng"), // 0x66
  new Word("Mu"), // 0x67
  new Word("Ni"), // 0x68
  new Word("Nie"), // 0x69
  new Word("Di"), // 0x6a
  new Word("Jia"), // 0x6b
  new Word("Mu"), // 0x6c
  new Word("Dan"), // 0x6d
  new Word("Shen"), // 0x6e
  new Word("Yi"), // 0x6f
  new Word("Si"), // 0x70
  new Word("Kuang"), // 0x71
  new Word("Ka"), // 0x72
  new Word("Bei"), // 0x73
  new Word("Jian"), // 0x74
  new Word("Tong"), // 0x75
  new Word("Xing"), // 0x76
  new Word("Hong"), // 0x77
  new Word("Jiao"), // 0x78
  new Word("Chi"), // 0x79
  new Word("Er"), // 0x7a
  new Word("Ge"), // 0x7b
  new Word("Bing"), // 0x7c
  new Word("Shi"), // 0x7d
  new Word("Mou"), // 0x7e
  new Word("Jia"), // 0x7f
  new Word("Yin"), // 0x80
  new Word("Jun"), // 0x81
  new Word("Zhou"), // 0x82
  new Word("Chong"), // 0x83
  new Word("Shang"), // 0x84
  new Word("Tong"), // 0x85
  new Word("Mo"), // 0x86
  new Word("Lei"), // 0x87
  new Word("Ji"), // 0x88
  new Word("Yu"), // 0x89
  new Word("Xu"), // 0x8a
  new Word("Ren"), // 0x8b
  new Word("Zun"), // 0x8c
  new Word("Zhi"), // 0x8d
  new Word("Qiong"), // 0x8e
  new Word("Shan"), // 0x8f
  new Word("Chi"), // 0x90
  new Word("Xian"), // 0x91
  new Word("Xing"), // 0x92
  new Word("Quan"), // 0x93
  new Word("Pi"), // 0x94
  new Word("Tie"), // 0x95
  new Word("Zhu"), // 0x96
  new Word("Hou"), // 0x97
  new Word("Ming"), // 0x98
  new Word("Kua"), // 0x99
  new Word("Yao"), // 0x9a
  new Word("Xian"), // 0x9b
  new Word("Xian"), // 0x9c
  new Word("Xiu"), // 0x9d
  new Word("Jun"), // 0x9e
  new Word("Cha"), // 0x9f
  new Word("Lao"), // 0xa0
  new Word("Ji"), // 0xa1
  new Word("Pi"), // 0xa2
  new Word("Ru"), // 0xa3
  new Word("Mi"), // 0xa4
  new Word("Yi"), // 0xa5
  new Word("Yin"), // 0xa6
  new Word("Guang"), // 0xa7
  new Word("An"), // 0xa8
  new Word("Diou"), // 0xa9
  new Word("You"), // 0xaa
  new Word("Se"), // 0xab
  new Word("Kao"), // 0xac
  new Word("Qian"), // 0xad
  new Word("Luan"), // 0xae
  new Word("Kasugai"), // 0xaf
  new Word("Ai"), // 0xb0
  new Word("Diao"), // 0xb1
  new Word("Han"), // 0xb2
  new Word("Rui"), // 0xb3
  new Word("Shi"), // 0xb4
  new Word("Keng"), // 0xb5
  new Word("Qiu"), // 0xb6
  new Word("Xiao"), // 0xb7
  new Word("Zhe"), // 0xb8
  new Word("Xiu"), // 0xb9
  new Word("Zang"), // 0xba
  new Word("Ti"), // 0xbb
  new Word("Cuo"), // 0xbc
  new Word("Gua"), // 0xbd
  new Word("Gong"), // 0xbe
  new Word("Zhong"), // 0xbf
  new Word("Dou"), // 0xc0
  new Word("Lu"), // 0xc1
  new Word("Mei"), // 0xc2
  new Word("Lang"), // 0xc3
  new Word("Wan"), // 0xc4
  new Word("Xin"), // 0xc5
  new Word("Yun"), // 0xc6
  new Word("Bei"), // 0xc7
  new Word("Wu"), // 0xc8
  new Word("Su"), // 0xc9
  new Word("Yu"), // 0xca
  new Word("Chan"), // 0xcb
  new Word("Ting"), // 0xcc
  new Word("Bo"), // 0xcd
  new Word("Han"), // 0xce
  new Word("Jia"), // 0xcf
  new Word("Hong"), // 0xd0
  new Word("Cuan"), // 0xd1
  new Word("Feng"), // 0xd2
  new Word("Chan"), // 0xd3
  new Word("Wan"), // 0xd4
  new Word("Zhi"), // 0xd5
  new Word("Si"), // 0xd6
  new Word("Xuan"), // 0xd7
  new Word("Wu"), // 0xd8
  new Word("Wu"), // 0xd9
  new Word("Tiao"), // 0xda
  new Word("Gong"), // 0xdb
  new Word("Zhuo"), // 0xdc
  new Word("Lue"), // 0xdd
  new Word("Xing"), // 0xde
  new Word("Qian"), // 0xdf
  new Word("Shen"), // 0xe0
  new Word("Han"), // 0xe1
  new Word("Lue"), // 0xe2
  new Word("Xie"), // 0xe3
  new Word("Chu"), // 0xe4
  new Word("Zheng"), // 0xe5
  new Word("Ju"), // 0xe6
  new Word("Xian"), // 0xe7
  new Word("Tie"), // 0xe8
  new Word("Mang"), // 0xe9
  new Word("Pu"), // 0xea
  new Word("Li"), // 0xeb
  new Word("Pan"), // 0xec
  new Word("Rui"), // 0xed
  new Word("Cheng"), // 0xee
  new Word("Gao"), // 0xef
  new Word("Li"), // 0xf0
  new Word("Te"), // 0xf1
  new Word("Pyeng"), // 0xf2
  new Word("Zhu"), // 0xf3
  null, // 0xf4
  new Word("Tu"), // 0xf5
  new Word("Liu"), // 0xf6
  new Word("Zui"), // 0xf7
  new Word("Ju"), // 0xf8
  new Word("Chang"), // 0xf9
  new Word("Yuan"), // 0xfa
  new Word("Jian"), // 0xfb
  new Word("Gang"), // 0xfc
  new Word("Diao"), // 0xfd
  new Word("Tao"), // 0xfe
  new Word("Chang") // 0xff
  };
}