/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+93xx (CJK Unified Ideographs).
 */
final class X93 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Lun"), // 0x00
  new Word("Kua"), // 0x01
  new Word("Ling"), // 0x02
  new Word("Bei"), // 0x03
  new Word("Lu"), // 0x04
  new Word("Li"), // 0x05
  new Word("Qiang"), // 0x06
  new Word("Pou"), // 0x07
  new Word("Juan"), // 0x08
  new Word("Min"), // 0x09
  new Word("Zui"), // 0x0a
  new Word("Peng"), // 0x0b
  new Word("An"), // 0x0c
  new Word("Pi"), // 0x0d
  new Word("Xian"), // 0x0e
  new Word("Ya"), // 0x0f
  new Word("Zhui"), // 0x10
  new Word("Lei"), // 0x11
  new Word("A"), // 0x12
  new Word("Kong"), // 0x13
  new Word("Ta"), // 0x14
  new Word("Kun"), // 0x15
  new Word("Du"), // 0x16
  new Word("Wei"), // 0x17
  new Word("Chui"), // 0x18
  new Word("Zi"), // 0x19
  new Word("Zheng"), // 0x1a
  new Word("Ben"), // 0x1b
  new Word("Nie"), // 0x1c
  new Word("Cong"), // 0x1d
  new Word("Qun"), // 0x1e
  new Word("Tan"), // 0x1f
  new Word("Ding"), // 0x20
  new Word("Qi"), // 0x21
  new Word("Qian"), // 0x22
  new Word("Zhuo"), // 0x23
  new Word("Qi"), // 0x24
  new Word("Yu"), // 0x25
  new Word("Jin"), // 0x26
  new Word("Guan"), // 0x27
  new Word("Mao"), // 0x28
  new Word("Chang"), // 0x29
  new Word("Tian"), // 0x2a
  new Word("Xi"), // 0x2b
  new Word("Lian"), // 0x2c
  new Word("Tao"), // 0x2d
  new Word("Gu"), // 0x2e
  new Word("Cuo"), // 0x2f
  new Word("Shu"), // 0x30
  new Word("Zhen"), // 0x31
  new Word("Lu"), // 0x32
  new Word("Meng"), // 0x33
  new Word("Lu"), // 0x34
  new Word("Hua"), // 0x35
  new Word("Biao"), // 0x36
  new Word("Ga"), // 0x37
  new Word("Lai"), // 0x38
  new Word("Ken"), // 0x39
  new Word("Kazari"), // 0x3a
  new Word("Bu"), // 0x3b
  new Word("Nai"), // 0x3c
  new Word("Wan"), // 0x3d
  new Word("Zan"), // 0x3e
  null, // 0x3f
  new Word("De"), // 0x40
  new Word("Xian"), // 0x41
  null, // 0x42
  new Word("Huo"), // 0x43
  new Word("Liang"), // 0x44
  null, // 0x45
  new Word("Men"), // 0x46
  new Word("Kai"), // 0x47
  new Word("Ying"), // 0x48
  new Word("Di"), // 0x49
  new Word("Lian"), // 0x4a
  new Word("Guo"), // 0x4b
  new Word("Xian"), // 0x4c
  new Word("Du"), // 0x4d
  new Word("Tu"), // 0x4e
  new Word("Wei"), // 0x4f
  new Word("Cong"), // 0x50
  new Word("Fu"), // 0x51
  new Word("Rou"), // 0x52
  new Word("Ji"), // 0x53
  new Word("E"), // 0x54
  new Word("Rou"), // 0x55
  new Word("Chen"), // 0x56
  new Word("Ti"), // 0x57
  new Word("Zha"), // 0x58
  new Word("Hong"), // 0x59
  new Word("Yang"), // 0x5a
  new Word("Duan"), // 0x5b
  new Word("Xia"), // 0x5c
  new Word("Yu"), // 0x5d
  new Word("Keng"), // 0x5e
  new Word("Xing"), // 0x5f
  new Word("Huang"), // 0x60
  new Word("Wei"), // 0x61
  new Word("Fu"), // 0x62
  new Word("Zhao"), // 0x63
  new Word("Cha"), // 0x64
  new Word("Qie"), // 0x65
  new Word("She"), // 0x66
  new Word("Hong"), // 0x67
  new Word("Kui"), // 0x68
  new Word("Tian"), // 0x69
  new Word("Mou"), // 0x6a
  new Word("Qiao"), // 0x6b
  new Word("Qiao"), // 0x6c
  new Word("Hou"), // 0x6d
  new Word("Tou"), // 0x6e
  new Word("Cong"), // 0x6f
  new Word("Huan"), // 0x70
  new Word("Ye"), // 0x71
  new Word("Min"), // 0x72
  new Word("Jian"), // 0x73
  new Word("Duan"), // 0x74
  new Word("Jian"), // 0x75
  new Word("Song"), // 0x76
  new Word("Kui"), // 0x77
  new Word("Hu"), // 0x78
  new Word("Xuan"), // 0x79
  new Word("Duo"), // 0x7a
  new Word("Jie"), // 0x7b
  new Word("Zhen"), // 0x7c
  new Word("Bian"), // 0x7d
  new Word("Zhong"), // 0x7e
  new Word("Zi"), // 0x7f
  new Word("Xiu"), // 0x80
  new Word("Ye"), // 0x81
  new Word("Mei"), // 0x82
  new Word("Pai"), // 0x83
  new Word("Ai"), // 0x84
  new Word("Jie"), // 0x85
  null, // 0x86
  new Word("Mei"), // 0x87
  new Word("Chuo"), // 0x88
  new Word("Ta"), // 0x89
  new Word("Bang"), // 0x8a
  new Word("Xia"), // 0x8b
  new Word("Lian"), // 0x8c
  new Word("Suo"), // 0x8d
  new Word("Xi"), // 0x8e
  new Word("Liu"), // 0x8f
  new Word("Zu"), // 0x90
  new Word("Ye"), // 0x91
  new Word("Nou"), // 0x92
  new Word("Weng"), // 0x93
  new Word("Rong"), // 0x94
  new Word("Tang"), // 0x95
  new Word("Suo"), // 0x96
  new Word("Qiang"), // 0x97
  new Word("Ge"), // 0x98
  new Word("Shuo"), // 0x99
  new Word("Chui"), // 0x9a
  new Word("Bo"), // 0x9b
  new Word("Pan"), // 0x9c
  new Word("Sa"), // 0x9d
  new Word("Bi"), // 0x9e
  new Word("Sang"), // 0x9f
  new Word("Gang"), // 0xa0
  new Word("Zi"), // 0xa1
  new Word("Wu"), // 0xa2
  new Word("Ying"), // 0xa3
  new Word("Huang"), // 0xa4
  new Word("Tiao"), // 0xa5
  new Word("Liu"), // 0xa6
  new Word("Kai"), // 0xa7
  new Word("Sun"), // 0xa8
  new Word("Sha"), // 0xa9
  new Word("Sou"), // 0xaa
  new Word("Wan"), // 0xab
  new Word("Hao"), // 0xac
  new Word("Zhen"), // 0xad
  new Word("Zhen"), // 0xae
  new Word("Luo"), // 0xaf
  new Word("Yi"), // 0xb0
  new Word("Yuan"), // 0xb1
  new Word("Tang"), // 0xb2
  new Word("Nie"), // 0xb3
  new Word("Xi"), // 0xb4
  new Word("Jia"), // 0xb5
  new Word("Ge"), // 0xb6
  new Word("Ma"), // 0xb7
  new Word("Juan"), // 0xb8
  new Word("Kasugai"), // 0xb9
  new Word("Habaki"), // 0xba
  new Word("Suo"), // 0xbb
  null, // 0xbc
  null, // 0xbd
  null, // 0xbe
  new Word("Na"), // 0xbf
  new Word("Lu"), // 0xc0
  new Word("Suo"), // 0xc1
  new Word("Ou"), // 0xc2
  new Word("Zu"), // 0xc3
  new Word("Tuan"), // 0xc4
  new Word("Xiu"), // 0xc5
  new Word("Guan"), // 0xc6
  new Word("Xuan"), // 0xc7
  new Word("Lian"), // 0xc8
  new Word("Shou"), // 0xc9
  new Word("Ao"), // 0xca
  new Word("Man"), // 0xcb
  new Word("Mo"), // 0xcc
  new Word("Luo"), // 0xcd
  new Word("Bi"), // 0xce
  new Word("Wei"), // 0xcf
  new Word("Liu"), // 0xd0
  new Word("Di"), // 0xd1
  new Word("Qiao"), // 0xd2
  new Word("Cong"), // 0xd3
  new Word("Yi"), // 0xd4
  new Word("Lu"), // 0xd5
  new Word("Ao"), // 0xd6
  new Word("Keng"), // 0xd7
  new Word("Qiang"), // 0xd8
  new Word("Cui"), // 0xd9
  new Word("Qi"), // 0xda
  new Word("Chang"), // 0xdb
  new Word("Tang"), // 0xdc
  new Word("Man"), // 0xdd
  new Word("Yong"), // 0xde
  new Word("Chan"), // 0xdf
  new Word("Feng"), // 0xe0
  new Word("Jing"), // 0xe1
  new Word("Biao"), // 0xe2
  new Word("Shu"), // 0xe3
  new Word("Lou"), // 0xe4
  new Word("Xiu"), // 0xe5
  new Word("Cong"), // 0xe6
  new Word("Long"), // 0xe7
  new Word("Zan"), // 0xe8
  new Word("Jian"), // 0xe9
  new Word("Cao"), // 0xea
  new Word("Li"), // 0xeb
  new Word("Xia"), // 0xec
  new Word("Xi"), // 0xed
  new Word("Kang"), // 0xee
  null, // 0xef
  new Word("Beng"), // 0xf0
  null, // 0xf1
  null, // 0xf2
  new Word("Zheng"), // 0xf3
  new Word("Lu"), // 0xf4
  new Word("Hua"), // 0xf5
  new Word("Ji"), // 0xf6
  new Word("Pu"), // 0xf7
  new Word("Hui"), // 0xf8
  new Word("Qiang"), // 0xf9
  new Word("Po"), // 0xfa
  new Word("Lin"), // 0xfb
  new Word("Suo"), // 0xfc
  new Word("Xiu"), // 0xfd
  new Word("San"), // 0xfe
  new Word("Cheng") // 0xff
  };
}