/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+94xx (CJK Unified Ideographs).
 */
final class X94 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Kui"), // 0x00
  new Word("Si"), // 0x01
  new Word("Liu"), // 0x02
  new Word("Nao"), // 0x03
  new Word("Heng"), // 0x04
  new Word("Pie"), // 0x05
  new Word("Sui"), // 0x06
  new Word("Fan"), // 0x07
  new Word("Qiao"), // 0x08
  new Word("Quan"), // 0x09
  new Word("Yang"), // 0x0a
  new Word("Tang"), // 0x0b
  new Word("Xiang"), // 0x0c
  new Word("Jue"), // 0x0d
  new Word("Jiao"), // 0x0e
  new Word("Zun"), // 0x0f
  new Word("Liao"), // 0x10
  new Word("Jie"), // 0x11
  new Word("Lao"), // 0x12
  new Word("Dui"), // 0x13
  new Word("Tan"), // 0x14
  new Word("Zan"), // 0x15
  new Word("Ji"), // 0x16
  new Word("Jian"), // 0x17
  new Word("Zhong"), // 0x18
  new Word("Deng"), // 0x19
  new Word("Ya"), // 0x1a
  new Word("Ying"), // 0x1b
  new Word("Dui"), // 0x1c
  new Word("Jue"), // 0x1d
  new Word("Nou"), // 0x1e
  new Word("Ti"), // 0x1f
  new Word("Pu"), // 0x20
  new Word("Tie"), // 0x21
  null, // 0x22
  null, // 0x23
  new Word("Ding"), // 0x24
  new Word("Shan"), // 0x25
  new Word("Kai"), // 0x26
  new Word("Jian"), // 0x27
  new Word("Fei"), // 0x28
  new Word("Sui"), // 0x29
  new Word("Lu"), // 0x2a
  new Word("Juan"), // 0x2b
  new Word("Hui"), // 0x2c
  new Word("Yu"), // 0x2d
  new Word("Lian"), // 0x2e
  new Word("Zhuo"), // 0x2f
  new Word("Qiao"), // 0x30
  new Word("Qian"), // 0x31
  new Word("Zhuo"), // 0x32
  new Word("Lei"), // 0x33
  new Word("Bi"), // 0x34
  new Word("Tie"), // 0x35
  new Word("Huan"), // 0x36
  new Word("Ye"), // 0x37
  new Word("Duo"), // 0x38
  new Word("Guo"), // 0x39
  new Word("Dang"), // 0x3a
  new Word("Ju"), // 0x3b
  new Word("Fen"), // 0x3c
  new Word("Da"), // 0x3d
  new Word("Bei"), // 0x3e
  new Word("Yi"), // 0x3f
  new Word("Ai"), // 0x40
  new Word("Zong"), // 0x41
  new Word("Xun"), // 0x42
  new Word("Diao"), // 0x43
  new Word("Zhu"), // 0x44
  new Word("Heng"), // 0x45
  new Word("Zhui"), // 0x46
  new Word("Ji"), // 0x47
  new Word("Nie"), // 0x48
  new Word("Ta"), // 0x49
  new Word("Huo"), // 0x4a
  new Word("Qing"), // 0x4b
  new Word("Bin"), // 0x4c
  new Word("Ying"), // 0x4d
  new Word("Kui"), // 0x4e
  new Word("Ning"), // 0x4f
  new Word("Xu"), // 0x50
  new Word("Jian"), // 0x51
  new Word("Jian"), // 0x52
  new Word("Yari"), // 0x53
  new Word("Cha"), // 0x54
  new Word("Zhi"), // 0x55
  new Word("Mie"), // 0x56
  new Word("Li"), // 0x57
  new Word("Lei"), // 0x58
  new Word("Ji"), // 0x59
  new Word("Zuan"), // 0x5a
  new Word("Kuang"), // 0x5b
  new Word("Shang"), // 0x5c
  new Word("Peng"), // 0x5d
  new Word("La"), // 0x5e
  new Word("Du"), // 0x5f
  new Word("Shuo"), // 0x60
  new Word("Chuo"), // 0x61
  new Word("Lu"), // 0x62
  new Word("Biao"), // 0x63
  new Word("Bao"), // 0x64
  new Word("Lu"), // 0x65
  null, // 0x66
  null, // 0x67
  new Word("Long"), // 0x68
  new Word("E"), // 0x69
  new Word("Lu"), // 0x6a
  new Word("Xin"), // 0x6b
  new Word("Jian"), // 0x6c
  new Word("Lan"), // 0x6d
  new Word("Bo"), // 0x6e
  new Word("Jian"), // 0x6f
  new Word("Yao"), // 0x70
  new Word("Chan"), // 0x71
  new Word("Xiang"), // 0x72
  new Word("Jian"), // 0x73
  new Word("Xi"), // 0x74
  new Word("Guan"), // 0x75
  new Word("Cang"), // 0x76
  new Word("Nie"), // 0x77
  new Word("Lei"), // 0x78
  new Word("Cuan"), // 0x79
  new Word("Qu"), // 0x7a
  new Word("Pan"), // 0x7b
  new Word("Luo"), // 0x7c
  new Word("Zuan"), // 0x7d
  new Word("Luan"), // 0x7e
  new Word("Zao"), // 0x7f
  new Word("Nie"), // 0x80
  new Word("Jue"), // 0x81
  new Word("Tang"), // 0x82
  new Word("Shu"), // 0x83
  new Word("Lan"), // 0x84
  new Word("Jin"), // 0x85
  new Word("Qiu"), // 0x86
  new Word("Yi"), // 0x87
  new Word("Zhen"), // 0x88
  new Word("Ding"), // 0x89
  new Word("Zhao"), // 0x8a
  new Word("Po"), // 0x8b
  new Word("Diao"), // 0x8c
  new Word("Tu"), // 0x8d
  new Word("Qian"), // 0x8e
  new Word("Chuan"), // 0x8f
  new Word("Shan"), // 0x90
  new Word("Ji"), // 0x91
  new Word("Fan"), // 0x92
  new Word("Diao"), // 0x93
  new Word("Men"), // 0x94
  new Word("Nu"), // 0x95
  new Word("Xi"), // 0x96
  new Word("Chai"), // 0x97
  new Word("Xing"), // 0x98
  new Word("Gai"), // 0x99
  new Word("Bu"), // 0x9a
  new Word("Tai"), // 0x9b
  new Word("Ju"), // 0x9c
  new Word("Dun"), // 0x9d
  new Word("Chao"), // 0x9e
  new Word("Zhong"), // 0x9f
  new Word("Na"), // 0xa0
  new Word("Bei"), // 0xa1
  new Word("Gang"), // 0xa2
  new Word("Ban"), // 0xa3
  new Word("Qian"), // 0xa4
  new Word("Yao"), // 0xa5
  new Word("Qin"), // 0xa6
  new Word("Jun"), // 0xa7
  new Word("Wu"), // 0xa8
  new Word("Gou"), // 0xa9
  new Word("Kang"), // 0xaa
  new Word("Fang"), // 0xab
  new Word("Huo"), // 0xac
  new Word("Tou"), // 0xad
  new Word("Niu"), // 0xae
  new Word("Ba"), // 0xaf
  new Word("Yu"), // 0xb0
  new Word("Qian"), // 0xb1
  new Word("Zheng"), // 0xb2
  new Word("Qian"), // 0xb3
  new Word("Gu"), // 0xb4
  new Word("Bo"), // 0xb5
  new Word("E"), // 0xb6
  new Word("Po"), // 0xb7
  new Word("Bu"), // 0xb8
  new Word("Ba"), // 0xb9
  new Word("Yue"), // 0xba
  new Word("Zuan"), // 0xbb
  new Word("Mu"), // 0xbc
  new Word("Dan"), // 0xbd
  new Word("Jia"), // 0xbe
  new Word("Dian"), // 0xbf
  new Word("You"), // 0xc0
  new Word("Tie"), // 0xc1
  new Word("Bo"), // 0xc2
  new Word("Ling"), // 0xc3
  new Word("Shuo"), // 0xc4
  new Word("Qian"), // 0xc5
  new Word("Liu"), // 0xc6
  new Word("Bao"), // 0xc7
  new Word("Shi"), // 0xc8
  new Word("Xuan"), // 0xc9
  new Word("She"), // 0xca
  new Word("Bi"), // 0xcb
  new Word("Ni"), // 0xcc
  new Word("Pi"), // 0xcd
  new Word("Duo"), // 0xce
  new Word("Xing"), // 0xcf
  new Word("Kao"), // 0xd0
  new Word("Lao"), // 0xd1
  new Word("Er"), // 0xd2
  new Word("Mang"), // 0xd3
  new Word("Ya"), // 0xd4
  new Word("You"), // 0xd5
  new Word("Cheng"), // 0xd6
  new Word("Jia"), // 0xd7
  new Word("Ye"), // 0xd8
  new Word("Nao"), // 0xd9
  new Word("Zhi"), // 0xda
  new Word("Dang"), // 0xdb
  new Word("Tong"), // 0xdc
  new Word("Lu"), // 0xdd
  new Word("Diao"), // 0xde
  new Word("Yin"), // 0xdf
  new Word("Kai"), // 0xe0
  new Word("Zha"), // 0xe1
  new Word("Zhu"), // 0xe2
  new Word("Xian"), // 0xe3
  new Word("Ting"), // 0xe4
  new Word("Diu"), // 0xe5
  new Word("Xian"), // 0xe6
  new Word("Hua"), // 0xe7
  new Word("Quan"), // 0xe8
  new Word("Sha"), // 0xe9
  new Word("Jia"), // 0xea
  new Word("Yao"), // 0xeb
  new Word("Ge"), // 0xec
  new Word("Ming"), // 0xed
  new Word("Zheng"), // 0xee
  new Word("Se"), // 0xef
  new Word("Jiao"), // 0xf0
  new Word("Yi"), // 0xf1
  new Word("Chan"), // 0xf2
  new Word("Chong"), // 0xf3
  new Word("Tang"), // 0xf4
  new Word("An"), // 0xf5
  new Word("Yin"), // 0xf6
  new Word("Ru"), // 0xf7
  new Word("Zhu"), // 0xf8
  new Word("Lao"), // 0xf9
  new Word("Pu"), // 0xfa
  new Word("Wu"), // 0xfb
  new Word("Lai"), // 0xfc
  new Word("Te"), // 0xfd
  new Word("Lian"), // 0xfe
  new Word("Keng") // 0xff
  };
}