/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+95xx (CJK Unified Ideographs).
 */
final class X95 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Xiao"), // 0x00
  new Word("Suo"), // 0x01
  new Word("Li"), // 0x02
  new Word("Zheng"), // 0x03
  new Word("Chu"), // 0x04
  new Word("Guo"), // 0x05
  new Word("Gao"), // 0x06
  new Word("Tie"), // 0x07
  new Word("Xiu"), // 0x08
  new Word("Cuo"), // 0x09
  new Word("Lue"), // 0x0a
  new Word("Feng"), // 0x0b
  new Word("Xin"), // 0x0c
  new Word("Liu"), // 0x0d
  new Word("Kai"), // 0x0e
  new Word("Jian"), // 0x0f
  new Word("Rui"), // 0x10
  new Word("Ti"), // 0x11
  new Word("Lang"), // 0x12
  new Word("Qian"), // 0x13
  new Word("Ju"), // 0x14
  new Word("A"), // 0x15
  new Word("Qiang"), // 0x16
  new Word("Duo"), // 0x17
  new Word("Tian"), // 0x18
  new Word("Cuo"), // 0x19
  new Word("Mao"), // 0x1a
  new Word("Ben"), // 0x1b
  new Word("Qi"), // 0x1c
  new Word("De"), // 0x1d
  new Word("Kua"), // 0x1e
  new Word("Kun"), // 0x1f
  new Word("Chang"), // 0x20
  new Word("Xi"), // 0x21
  new Word("Gu"), // 0x22
  new Word("Luo"), // 0x23
  new Word("Chui"), // 0x24
  new Word("Zhui"), // 0x25
  new Word("Jin"), // 0x26
  new Word("Zhi"), // 0x27
  new Word("Xian"), // 0x28
  new Word("Juan"), // 0x29
  new Word("Huo"), // 0x2a
  new Word("Pou"), // 0x2b
  new Word("Tan"), // 0x2c
  new Word("Ding"), // 0x2d
  new Word("Jian"), // 0x2e
  new Word("Ju"), // 0x2f
  new Word("Meng"), // 0x30
  new Word("Zi"), // 0x31
  new Word("Qie"), // 0x32
  new Word("Ying"), // 0x33
  new Word("Kai"), // 0x34
  new Word("Qiang"), // 0x35
  new Word("Song"), // 0x36
  new Word("E"), // 0x37
  new Word("Cha"), // 0x38
  new Word("Qiao"), // 0x39
  new Word("Zhong"), // 0x3a
  new Word("Duan"), // 0x3b
  new Word("Sou"), // 0x3c
  new Word("Huang"), // 0x3d
  new Word("Huan"), // 0x3e
  new Word("Ai"), // 0x3f
  new Word("Du"), // 0x40
  new Word("Mei"), // 0x41
  new Word("Lou"), // 0x42
  new Word("Zi"), // 0x43
  new Word("Fei"), // 0x44
  new Word("Mei"), // 0x45
  new Word("Mo"), // 0x46
  new Word("Zhen"), // 0x47
  new Word("Bo"), // 0x48
  new Word("Ge"), // 0x49
  new Word("Nie"), // 0x4a
  new Word("Tang"), // 0x4b
  new Word("Juan"), // 0x4c
  new Word("Nie"), // 0x4d
  new Word("Na"), // 0x4e
  new Word("Liu"), // 0x4f
  new Word("Hao"), // 0x50
  new Word("Bang"), // 0x51
  new Word("Yi"), // 0x52
  new Word("Jia"), // 0x53
  new Word("Bin"), // 0x54
  new Word("Rong"), // 0x55
  new Word("Biao"), // 0x56
  new Word("Tang"), // 0x57
  new Word("Man"), // 0x58
  new Word("Luo"), // 0x59
  new Word("Beng"), // 0x5a
  new Word("Yong"), // 0x5b
  new Word("Jing"), // 0x5c
  new Word("Di"), // 0x5d
  new Word("Zu"), // 0x5e
  new Word("Xuan"), // 0x5f
  new Word("Liu"), // 0x60
  new Word("Tan"), // 0x61
  new Word("Jue"), // 0x62
  new Word("Liao"), // 0x63
  new Word("Pu"), // 0x64
  new Word("Lu"), // 0x65
  new Word("Dui"), // 0x66
  new Word("Lan"), // 0x67
  new Word("Pu"), // 0x68
  new Word("Cuan"), // 0x69
  new Word("Qiang"), // 0x6a
  new Word("Deng"), // 0x6b
  new Word("Huo"), // 0x6c
  new Word("Lei"), // 0x6d
  new Word("Huan"), // 0x6e
  new Word("Zhuo"), // 0x6f
  new Word("Lian"), // 0x70
  new Word("Yi"), // 0x71
  new Word("Cha"), // 0x72
  new Word("Biao"), // 0x73
  new Word("La"), // 0x74
  new Word("Chan"), // 0x75
  new Word("Xiang"), // 0x76
  new Word("Chang"), // 0x77
  new Word("Chang"), // 0x78
  new Word("Jiu"), // 0x79
  new Word("Ao"), // 0x7a
  new Word("Die"), // 0x7b
  new Word("Qu"), // 0x7c
  new Word("Liao"), // 0x7d
  new Word("Mi"), // 0x7e
  new Word("Chang"), // 0x7f
  new Word("Men"), // 0x80
  new Word("Ma"), // 0x81
  new Word("Shuan"), // 0x82
  new Word("Shan"), // 0x83
  new Word("Huo"), // 0x84
  new Word("Men"), // 0x85
  new Word("Yan"), // 0x86
  new Word("Bi"), // 0x87
  new Word("Han"), // 0x88
  new Word("Bi"), // 0x89
  new Word("San"), // 0x8a
  new Word("Kai"), // 0x8b
  new Word("Kang"), // 0x8c
  new Word("Beng"), // 0x8d
  new Word("Hong"), // 0x8e
  new Word("Run"), // 0x8f
  new Word("San"), // 0x90
  new Word("Xian"), // 0x91
  new Word("Xian"), // 0x92
  new Word("Jian"), // 0x93
  new Word("Min"), // 0x94
  new Word("Xia"), // 0x95
  new Word("Yuru"), // 0x96
  new Word("Dou"), // 0x97
  new Word("Zha"), // 0x98
  new Word("Nao"), // 0x99
  new Word("Jian"), // 0x9a
  new Word("Peng"), // 0x9b
  new Word("Xia"), // 0x9c
  new Word("Ling"), // 0x9d
  new Word("Bian"), // 0x9e
  new Word("Bi"), // 0x9f
  new Word("Run"), // 0xa0
  new Word("He"), // 0xa1
  new Word("Guan"), // 0xa2
  new Word("Ge"), // 0xa3
  new Word("Ge"), // 0xa4
  new Word("Fa"), // 0xa5
  new Word("Chu"), // 0xa6
  new Word("Hong"), // 0xa7
  new Word("Gui"), // 0xa8
  new Word("Min"), // 0xa9
  new Word("Se"), // 0xaa
  new Word("Kun"), // 0xab
  new Word("Lang"), // 0xac
  new Word("Lu"), // 0xad
  new Word("Ting"), // 0xae
  new Word("Sha"), // 0xaf
  new Word("Ju"), // 0xb0
  new Word("Yue"), // 0xb1
  new Word("Yue"), // 0xb2
  new Word("Chan"), // 0xb3
  new Word("Qu"), // 0xb4
  new Word("Lin"), // 0xb5
  new Word("Chang"), // 0xb6
  new Word("Shai"), // 0xb7
  new Word("Kun"), // 0xb8
  new Word("Yan"), // 0xb9
  new Word("Min"), // 0xba
  new Word("Yan"), // 0xbb
  new Word("E"), // 0xbc
  new Word("Hun"), // 0xbd
  new Word("Yu"), // 0xbe
  new Word("Wen"), // 0xbf
  new Word("Xiang"), // 0xc0
  new Word("Bao"), // 0xc1
  new Word("Xiang"), // 0xc2
  new Word("Qu"), // 0xc3
  new Word("Yao"), // 0xc4
  new Word("Wen"), // 0xc5
  new Word("Ban"), // 0xc6
  new Word("An"), // 0xc7
  new Word("Wei"), // 0xc8
  new Word("Yin"), // 0xc9
  new Word("Kuo"), // 0xca
  new Word("Que"), // 0xcb
  new Word("Lan"), // 0xcc
  new Word("Du"), // 0xcd
  null, // 0xce
  new Word("Phwung"), // 0xcf
  new Word("Tian"), // 0xd0
  new Word("Nie"), // 0xd1
  new Word("Ta"), // 0xd2
  new Word("Kai"), // 0xd3
  new Word("He"), // 0xd4
  new Word("Que"), // 0xd5
  new Word("Chuang"), // 0xd6
  new Word("Guan"), // 0xd7
  new Word("Dou"), // 0xd8
  new Word("Qi"), // 0xd9
  new Word("Kui"), // 0xda
  new Word("Tang"), // 0xdb
  new Word("Guan"), // 0xdc
  new Word("Piao"), // 0xdd
  new Word("Kan"), // 0xde
  new Word("Xi"), // 0xdf
  new Word("Hui"), // 0xe0
  new Word("Chan"), // 0xe1
  new Word("Pi"), // 0xe2
  new Word("Dang"), // 0xe3
  new Word("Huan"), // 0xe4
  new Word("Ta"), // 0xe5
  new Word("Wen"), // 0xe6
  null, // 0xe7
  new Word("Men"), // 0xe8
  new Word("Shuan"), // 0xe9
  new Word("Shan"), // 0xea
  new Word("Yan"), // 0xeb
  new Word("Han"), // 0xec
  new Word("Bi"), // 0xed
  new Word("Wen"), // 0xee
  new Word("Chuang"), // 0xef
  new Word("Run"), // 0xf0
  new Word("Wei"), // 0xf1
  new Word("Xian"), // 0xf2
  new Word("Hong"), // 0xf3
  new Word("Jian"), // 0xf4
  new Word("Min"), // 0xf5
  new Word("Kang"), // 0xf6
  new Word("Men"), // 0xf7
  new Word("Zha"), // 0xf8
  new Word("Nao"), // 0xf9
  new Word("Gui"), // 0xfa
  new Word("Wen"), // 0xfb
  new Word("Ta"), // 0xfc
  new Word("Min"), // 0xfd
  new Word("Lu"), // 0xfe
  new Word("Kai") // 0xff
  };
}