/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+96xx (CJK Unified Ideographs).
 */
final class X96 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Fa"), // 0x00
  new Word("Ge"), // 0x01
  new Word("He"), // 0x02
  new Word("Kun"), // 0x03
  new Word("Jiu"), // 0x04
  new Word("Yue"), // 0x05
  new Word("Lang"), // 0x06
  new Word("Du"), // 0x07
  new Word("Yu"), // 0x08
  new Word("Yan"), // 0x09
  new Word("Chang"), // 0x0a
  new Word("Xi"), // 0x0b
  new Word("Wen"), // 0x0c
  new Word("Hun"), // 0x0d
  new Word("Yan"), // 0x0e
  new Word("E"), // 0x0f
  new Word("Chan"), // 0x10
  new Word("Lan"), // 0x11
  new Word("Qu"), // 0x12
  new Word("Hui"), // 0x13
  new Word("Kuo"), // 0x14
  new Word("Que"), // 0x15
  new Word("Ge"), // 0x16
  new Word("Tian"), // 0x17
  new Word("Ta"), // 0x18
  new Word("Que"), // 0x19
  new Word("Kan"), // 0x1a
  new Word("Huan"), // 0x1b
  new Word("Fu"), // 0x1c
  new Word("Fu"), // 0x1d
  new Word("Le"), // 0x1e
  new Word("Dui"), // 0x1f
  new Word("Xin"), // 0x20
  new Word("Qian"), // 0x21
  new Word("Wu"), // 0x22
  new Word("Yi"), // 0x23
  new Word("Tuo"), // 0x24
  new Word("Yin"), // 0x25
  new Word("Yang"), // 0x26
  new Word("Dou"), // 0x27
  new Word("E"), // 0x28
  new Word("Sheng"), // 0x29
  new Word("Ban"), // 0x2a
  new Word("Pei"), // 0x2b
  new Word("Keng"), // 0x2c
  new Word("Yun"), // 0x2d
  new Word("Ruan"), // 0x2e
  new Word("Zhi"), // 0x2f
  new Word("Pi"), // 0x30
  new Word("Jing"), // 0x31
  new Word("Fang"), // 0x32
  new Word("Yang"), // 0x33
  new Word("Yin"), // 0x34
  new Word("Zhen"), // 0x35
  new Word("Jie"), // 0x36
  new Word("Cheng"), // 0x37
  new Word("E"), // 0x38
  new Word("Qu"), // 0x39
  new Word("Di"), // 0x3a
  new Word("Zu"), // 0x3b
  new Word("Zuo"), // 0x3c
  new Word("Dian"), // 0x3d
  new Word("Ling"), // 0x3e
  new Word("A"), // 0x3f
  new Word("Tuo"), // 0x40
  new Word("Tuo"), // 0x41
  new Word("Po"), // 0x42
  new Word("Bing"), // 0x43
  new Word("Fu"), // 0x44
  new Word("Ji"), // 0x45
  new Word("Lu"), // 0x46
  new Word("Long"), // 0x47
  new Word("Chen"), // 0x48
  new Word("Xing"), // 0x49
  new Word("Duo"), // 0x4a
  new Word("Lou"), // 0x4b
  new Word("Mo"), // 0x4c
  new Word("Jiang"), // 0x4d
  new Word("Shu"), // 0x4e
  new Word("Duo"), // 0x4f
  new Word("Xian"), // 0x50
  new Word("Er"), // 0x51
  new Word("Gui"), // 0x52
  new Word("Yu"), // 0x53
  new Word("Gai"), // 0x54
  new Word("Shan"), // 0x55
  new Word("Xun"), // 0x56
  new Word("Qiao"), // 0x57
  new Word("Xing"), // 0x58
  new Word("Chun"), // 0x59
  new Word("Fu"), // 0x5a
  new Word("Bi"), // 0x5b
  new Word("Xia"), // 0x5c
  new Word("Shan"), // 0x5d
  new Word("Sheng"), // 0x5e
  new Word("Zhi"), // 0x5f
  new Word("Pu"), // 0x60
  new Word("Dou"), // 0x61
  new Word("Yuan"), // 0x62
  new Word("Zhen"), // 0x63
  new Word("Chu"), // 0x64
  new Word("Xian"), // 0x65
  new Word("Tou"), // 0x66
  new Word("Nie"), // 0x67
  new Word("Yun"), // 0x68
  new Word("Xian"), // 0x69
  new Word("Pei"), // 0x6a
  new Word("Pei"), // 0x6b
  new Word("Zou"), // 0x6c
  new Word("Yi"), // 0x6d
  new Word("Dui"), // 0x6e
  new Word("Lun"), // 0x6f
  new Word("Yin"), // 0x70
  new Word("Ju"), // 0x71
  new Word("Chui"), // 0x72
  new Word("Chen"), // 0x73
  new Word("Pi"), // 0x74
  new Word("Ling"), // 0x75
  new Word("Tao"), // 0x76
  new Word("Xian"), // 0x77
  new Word("Lu"), // 0x78
  new Word("Sheng"), // 0x79
  new Word("Xian"), // 0x7a
  new Word("Yin"), // 0x7b
  new Word("Zhu"), // 0x7c
  new Word("Yang"), // 0x7d
  new Word("Reng"), // 0x7e
  new Word("Shan"), // 0x7f
  new Word("Chong"), // 0x80
  new Word("Yan"), // 0x81
  new Word("Yin"), // 0x82
  new Word("Yu"), // 0x83
  new Word("Ti"), // 0x84
  new Word("Yu"), // 0x85
  new Word("Long"), // 0x86
  new Word("Wei"), // 0x87
  new Word("Wei"), // 0x88
  new Word("Nie"), // 0x89
  new Word("Dui"), // 0x8a
  new Word("Sui"), // 0x8b
  new Word("An"), // 0x8c
  new Word("Huang"), // 0x8d
  new Word("Jie"), // 0x8e
  new Word("Sui"), // 0x8f
  new Word("Yin"), // 0x90
  new Word("Gai"), // 0x91
  new Word("Yan"), // 0x92
  new Word("Hui"), // 0x93
  new Word("Ge"), // 0x94
  new Word("Yun"), // 0x95
  new Word("Wu"), // 0x96
  new Word("Wei"), // 0x97
  new Word("Ai"), // 0x98
  new Word("Xi"), // 0x99
  new Word("Tang"), // 0x9a
  new Word("Ji"), // 0x9b
  new Word("Zhang"), // 0x9c
  new Word("Dao"), // 0x9d
  new Word("Ao"), // 0x9e
  new Word("Xi"), // 0x9f
  new Word("Yin"), // 0xa0
  null, // 0xa1
  new Word("Rao"), // 0xa2
  new Word("Lin"), // 0xa3
  new Word("Tui"), // 0xa4
  new Word("Deng"), // 0xa5
  new Word("Pi"), // 0xa6
  new Word("Sui"), // 0xa7
  new Word("Sui"), // 0xa8
  new Word("Yu"), // 0xa9
  new Word("Xian"), // 0xaa
  new Word("Fen"), // 0xab
  new Word("Ni"), // 0xac
  new Word("Er"), // 0xad
  new Word("Ji"), // 0xae
  new Word("Dao"), // 0xaf
  new Word("Xi"), // 0xb0
  new Word("Yin"), // 0xb1
  new Word("E"), // 0xb2
  new Word("Hui"), // 0xb3
  new Word("Long"), // 0xb4
  new Word("Xi"), // 0xb5
  new Word("Li"), // 0xb6
  new Word("Li"), // 0xb7
  new Word("Li"), // 0xb8
  new Word("Zhui"), // 0xb9
  new Word("He"), // 0xba
  new Word("Zhi"), // 0xbb
  new Word("Zhun"), // 0xbc
  new Word("Jun"), // 0xbd
  new Word("Nan"), // 0xbe
  new Word("Yi"), // 0xbf
  new Word("Que"), // 0xc0
  new Word("Yan"), // 0xc1
  new Word("Qian"), // 0xc2
  new Word("Ya"), // 0xc3
  new Word("Xiong"), // 0xc4
  new Word("Ya"), // 0xc5
  new Word("Ji"), // 0xc6
  new Word("Gu"), // 0xc7
  new Word("Huan"), // 0xc8
  new Word("Zhi"), // 0xc9
  new Word("Gou"), // 0xca
  new Word("Jun"), // 0xcb
  new Word("Ci"), // 0xcc
  new Word("Yong"), // 0xcd
  new Word("Ju"), // 0xce
  new Word("Chu"), // 0xcf
  new Word("Hu"), // 0xd0
  new Word("Za"), // 0xd1
  new Word("Luo"), // 0xd2
  new Word("Yu"), // 0xd3
  new Word("Chou"), // 0xd4
  new Word("Diao"), // 0xd5
  new Word("Sui"), // 0xd6
  new Word("Han"), // 0xd7
  new Word("Huo"), // 0xd8
  new Word("Shuang"), // 0xd9
  new Word("Guan"), // 0xda
  new Word("Chu"), // 0xdb
  new Word("Za"), // 0xdc
  new Word("Yong"), // 0xdd
  new Word("Ji"), // 0xde
  new Word("Xi"), // 0xdf
  new Word("Chou"), // 0xe0
  new Word("Liu"), // 0xe1
  new Word("Li"), // 0xe2
  new Word("Nan"), // 0xe3
  new Word("Xue"), // 0xe4
  new Word("Za"), // 0xe5
  new Word("Ji"), // 0xe6
  new Word("Ji"), // 0xe7
  new Word("Yu"), // 0xe8
  new Word("Yu"), // 0xe9
  new Word("Xue"), // 0xea
  new Word("Na"), // 0xeb
  new Word("Fou"), // 0xec
  new Word("Se"), // 0xed
  new Word("Mu"), // 0xee
  new Word("Wen"), // 0xef
  new Word("Fen"), // 0xf0
  new Word("Pang"), // 0xf1
  new Word("Yun"), // 0xf2
  new Word("Li"), // 0xf3
  new Word("Li"), // 0xf4
  new Word("Ang"), // 0xf5
  new Word("Ling"), // 0xf6
  new Word("Lei"), // 0xf7
  new Word("An"), // 0xf8
  new Word("Bao"), // 0xf9
  new Word("Meng"), // 0xfa
  new Word("Dian"), // 0xfb
  new Word("Dang"), // 0xfc
  new Word("Xing"), // 0xfd
  new Word("Wu"), // 0xfe
  new Word("Zhao") // 0xff
  };
}