/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+97xx (CJK Unified Ideographs).
 */
final class X97 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Xu"), // 0x00
  new Word("Ji"), // 0x01
  new Word("Mu"), // 0x02
  new Word("Chen"), // 0x03
  new Word("Xiao"), // 0x04
  new Word("Zha"), // 0x05
  new Word("Ting"), // 0x06
  new Word("Zhen"), // 0x07
  new Word("Pei"), // 0x08
  new Word("Mei"), // 0x09
  new Word("Ling"), // 0x0a
  new Word("Qi"), // 0x0b
  new Word("Chou"), // 0x0c
  new Word("Huo"), // 0x0d
  new Word("Sha"), // 0x0e
  new Word("Fei"), // 0x0f
  new Word("Weng"), // 0x10
  new Word("Zhan"), // 0x11
  new Word("Yin"), // 0x12
  new Word("Ni"), // 0x13
  new Word("Chou"), // 0x14
  new Word("Tun"), // 0x15
  new Word("Lin"), // 0x16
  null, // 0x17
  new Word("Dong"), // 0x18
  new Word("Ying"), // 0x19
  new Word("Wu"), // 0x1a
  new Word("Ling"), // 0x1b
  new Word("Shuang"), // 0x1c
  new Word("Ling"), // 0x1d
  new Word("Xia"), // 0x1e
  new Word("Hong"), // 0x1f
  new Word("Yin"), // 0x20
  new Word("Mo"), // 0x21
  new Word("Mai"), // 0x22
  new Word("Yun"), // 0x23
  new Word("Liu"), // 0x24
  new Word("Meng"), // 0x25
  new Word("Bin"), // 0x26
  new Word("Wu"), // 0x27
  new Word("Wei"), // 0x28
  new Word("Huo"), // 0x29
  new Word("Yin"), // 0x2a
  new Word("Xi"), // 0x2b
  new Word("Yi"), // 0x2c
  new Word("Ai"), // 0x2d
  new Word("Dan"), // 0x2e
  new Word("Deng"), // 0x2f
  new Word("Xian"), // 0x30
  new Word("Yu"), // 0x31
  new Word("Lu"), // 0x32
  new Word("Long"), // 0x33
  new Word("Dai"), // 0x34
  new Word("Ji"), // 0x35
  new Word("Pang"), // 0x36
  new Word("Yang"), // 0x37
  new Word("Ba"), // 0x38
  new Word("Pi"), // 0x39
  new Word("Wei"), // 0x3a
  null, // 0x3b
  new Word("Xi"), // 0x3c
  new Word("Ji"), // 0x3d
  new Word("Mai"), // 0x3e
  new Word("Meng"), // 0x3f
  new Word("Meng"), // 0x40
  new Word("Lei"), // 0x41
  new Word("Li"), // 0x42
  new Word("Huo"), // 0x43
  new Word("Ai"), // 0x44
  new Word("Fei"), // 0x45
  new Word("Dai"), // 0x46
  new Word("Long"), // 0x47
  new Word("Ling"), // 0x48
  new Word("Ai"), // 0x49
  new Word("Feng"), // 0x4a
  new Word("Li"), // 0x4b
  new Word("Bao"), // 0x4c
  null, // 0x4d
  new Word("He"), // 0x4e
  new Word("He"), // 0x4f
  new Word("Bing"), // 0x50
  new Word("Qing"), // 0x51
  new Word("Qing"), // 0x52
  new Word("Jing"), // 0x53
  new Word("Tian"), // 0x54
  new Word("Zhen"), // 0x55
  new Word("Jing"), // 0x56
  new Word("Cheng"), // 0x57
  new Word("Qing"), // 0x58
  new Word("Jing"), // 0x59
  new Word("Jing"), // 0x5a
  new Word("Dian"), // 0x5b
  new Word("Jing"), // 0x5c
  new Word("Tian"), // 0x5d
  new Word("Fei"), // 0x5e
  new Word("Fei"), // 0x5f
  new Word("Kao"), // 0x60
  new Word("Mi"), // 0x61
  new Word("Mian"), // 0x62
  new Word("Mian"), // 0x63
  new Word("Pao"), // 0x64
  new Word("Ye"), // 0x65
  new Word("Tian"), // 0x66
  new Word("Hui"), // 0x67
  new Word("Ye"), // 0x68
  new Word("Ge"), // 0x69
  new Word("Ding"), // 0x6a
  new Word("Cha"), // 0x6b
  new Word("Jian"), // 0x6c
  new Word("Ren"), // 0x6d
  new Word("Di"), // 0x6e
  new Word("Du"), // 0x6f
  new Word("Wu"), // 0x70
  new Word("Ren"), // 0x71
  new Word("Qin"), // 0x72
  new Word("Jin"), // 0x73
  new Word("Xue"), // 0x74
  new Word("Niu"), // 0x75
  new Word("Ba"), // 0x76
  new Word("Yin"), // 0x77
  new Word("Sa"), // 0x78
  new Word("Na"), // 0x79
  new Word("Mo"), // 0x7a
  new Word("Zu"), // 0x7b
  new Word("Da"), // 0x7c
  new Word("Ban"), // 0x7d
  new Word("Yi"), // 0x7e
  new Word("Yao"), // 0x7f
  new Word("Tao"), // 0x80
  new Word("Tuo"), // 0x81
  new Word("Jia"), // 0x82
  new Word("Hong"), // 0x83
  new Word("Pao"), // 0x84
  new Word("Yang"), // 0x85
  new Word("Tomo"), // 0x86
  new Word("Yin"), // 0x87
  new Word("Jia"), // 0x88
  new Word("Tao"), // 0x89
  new Word("Ji"), // 0x8a
  new Word("Xie"), // 0x8b
  new Word("An"), // 0x8c
  new Word("An"), // 0x8d
  new Word("Hen"), // 0x8e
  new Word("Gong"), // 0x8f
  new Word("Kohaze"), // 0x90
  new Word("Da"), // 0x91
  new Word("Qiao"), // 0x92
  new Word("Ting"), // 0x93
  new Word("Wan"), // 0x94
  new Word("Ying"), // 0x95
  new Word("Sui"), // 0x96
  new Word("Tiao"), // 0x97
  new Word("Qiao"), // 0x98
  new Word("Xuan"), // 0x99
  new Word("Kong"), // 0x9a
  new Word("Beng"), // 0x9b
  new Word("Ta"), // 0x9c
  new Word("Zhang"), // 0x9d
  new Word("Bing"), // 0x9e
  new Word("Kuo"), // 0x9f
  new Word("Ju"), // 0xa0
  new Word("La"), // 0xa1
  new Word("Xie"), // 0xa2
  new Word("Rou"), // 0xa3
  new Word("Bang"), // 0xa4
  new Word("Yi"), // 0xa5
  new Word("Qiu"), // 0xa6
  new Word("Qiu"), // 0xa7
  new Word("He"), // 0xa8
  new Word("Xiao"), // 0xa9
  new Word("Mu"), // 0xaa
  new Word("Ju"), // 0xab
  new Word("Jian"), // 0xac
  new Word("Bian"), // 0xad
  new Word("Di"), // 0xae
  new Word("Jian"), // 0xaf
  new Word("On"), // 0xb0
  new Word("Tao"), // 0xb1
  new Word("Gou"), // 0xb2
  new Word("Ta"), // 0xb3
  new Word("Bei"), // 0xb4
  new Word("Xie"), // 0xb5
  new Word("Pan"), // 0xb6
  new Word("Ge"), // 0xb7
  new Word("Bi"), // 0xb8
  new Word("Kuo"), // 0xb9
  new Word("Tang"), // 0xba
  new Word("Lou"), // 0xbb
  new Word("Gui"), // 0xbc
  new Word("Qiao"), // 0xbd
  new Word("Xue"), // 0xbe
  new Word("Ji"), // 0xbf
  new Word("Jian"), // 0xc0
  new Word("Jiang"), // 0xc1
  new Word("Chan"), // 0xc2
  new Word("Da"), // 0xc3
  new Word("Huo"), // 0xc4
  new Word("Xian"), // 0xc5
  new Word("Qian"), // 0xc6
  new Word("Du"), // 0xc7
  new Word("Wa"), // 0xc8
  new Word("Jian"), // 0xc9
  new Word("Lan"), // 0xca
  new Word("Wei"), // 0xcb
  new Word("Ren"), // 0xcc
  new Word("Fu"), // 0xcd
  new Word("Mei"), // 0xce
  new Word("Juan"), // 0xcf
  new Word("Ge"), // 0xd0
  new Word("Wei"), // 0xd1
  new Word("Qiao"), // 0xd2
  new Word("Han"), // 0xd3
  new Word("Chang"), // 0xd4
  null, // 0xd5
  new Word("Rou"), // 0xd6
  new Word("Xun"), // 0xd7
  new Word("She"), // 0xd8
  new Word("Wei"), // 0xd9
  new Word("Ge"), // 0xda
  new Word("Bei"), // 0xdb
  new Word("Tao"), // 0xdc
  new Word("Gou"), // 0xdd
  new Word("Yun"), // 0xde
  null, // 0xdf
  new Word("Bi"), // 0xe0
  new Word("Wei"), // 0xe1
  new Word("Hui"), // 0xe2
  new Word("Du"), // 0xe3
  new Word("Wa"), // 0xe4
  new Word("Du"), // 0xe5
  new Word("Wei"), // 0xe6
  new Word("Ren"), // 0xe7
  new Word("Fu"), // 0xe8
  new Word("Han"), // 0xe9
  new Word("Wei"), // 0xea
  new Word("Yun"), // 0xeb
  new Word("Tao"), // 0xec
  new Word("Jiu"), // 0xed
  new Word("Jiu"), // 0xee
  new Word("Xian"), // 0xef
  new Word("Xie"), // 0xf0
  new Word("Xian"), // 0xf1
  new Word("Ji"), // 0xf2
  new Word("Yin"), // 0xf3
  new Word("Za"), // 0xf4
  new Word("Yun"), // 0xf5
  new Word("Shao"), // 0xf6
  new Word("Le"), // 0xf7
  new Word("Peng"), // 0xf8
  new Word("Heng"), // 0xf9
  new Word("Ying"), // 0xfa
  new Word("Yun"), // 0xfb
  new Word("Peng"), // 0xfc
  new Word("Yin"), // 0xfd
  new Word("Yin"), // 0xfe
  new Word("Xiang") // 0xff
  };
}