/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+98xx (CJK Unified Ideographs).
 */
final class X98 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Hu"), // 0x00
  new Word("Ye"), // 0x01
  new Word("Ding"), // 0x02
  new Word("Qing"), // 0x03
  new Word("Pan"), // 0x04
  new Word("Xiang"), // 0x05
  new Word("Shun"), // 0x06
  new Word("Han"), // 0x07
  new Word("Xu"), // 0x08
  new Word("Yi"), // 0x09
  new Word("Xu"), // 0x0a
  new Word("Gu"), // 0x0b
  new Word("Song"), // 0x0c
  new Word("Kui"), // 0x0d
  new Word("Qi"), // 0x0e
  new Word("Hang"), // 0x0f
  new Word("Yu"), // 0x10
  new Word("Wan"), // 0x11
  new Word("Ban"), // 0x12
  new Word("Dun"), // 0x13
  new Word("Di"), // 0x14
  new Word("Dan"), // 0x15
  new Word("Pan"), // 0x16
  new Word("Po"), // 0x17
  new Word("Ling"), // 0x18
  new Word("Ce"), // 0x19
  new Word("Jing"), // 0x1a
  new Word("Lei"), // 0x1b
  new Word("He"), // 0x1c
  new Word("Qiao"), // 0x1d
  new Word("E"), // 0x1e
  new Word("E"), // 0x1f
  new Word("Wei"), // 0x20
  new Word("Jie"), // 0x21
  new Word("Gua"), // 0x22
  new Word("Shen"), // 0x23
  new Word("Yi"), // 0x24
  new Word("Shen"), // 0x25
  new Word("Hai"), // 0x26
  new Word("Dui"), // 0x27
  new Word("Pian"), // 0x28
  new Word("Ping"), // 0x29
  new Word("Lei"), // 0x2a
  new Word("Fu"), // 0x2b
  new Word("Jia"), // 0x2c
  new Word("Tou"), // 0x2d
  new Word("Hui"), // 0x2e
  new Word("Kui"), // 0x2f
  new Word("Jia"), // 0x30
  new Word("Le"), // 0x31
  new Word("Tian"), // 0x32
  new Word("Cheng"), // 0x33
  new Word("Ying"), // 0x34
  new Word("Jun"), // 0x35
  new Word("Hu"), // 0x36
  new Word("Han"), // 0x37
  new Word("Jing"), // 0x38
  new Word("Tui"), // 0x39
  new Word("Tui"), // 0x3a
  new Word("Pin"), // 0x3b
  new Word("Lai"), // 0x3c
  new Word("Tui"), // 0x3d
  new Word("Zi"), // 0x3e
  new Word("Zi"), // 0x3f
  new Word("Chui"), // 0x40
  new Word("Ding"), // 0x41
  new Word("Lai"), // 0x42
  new Word("Yan"), // 0x43
  new Word("Han"), // 0x44
  new Word("Jian"), // 0x45
  new Word("Ke"), // 0x46
  new Word("Cui"), // 0x47
  new Word("Jiong"), // 0x48
  new Word("Qin"), // 0x49
  new Word("Yi"), // 0x4a
  new Word("Sai"), // 0x4b
  new Word("Ti"), // 0x4c
  new Word("E"), // 0x4d
  new Word("E"), // 0x4e
  new Word("Yan"), // 0x4f
  new Word("Hun"), // 0x50
  new Word("Kan"), // 0x51
  new Word("Yong"), // 0x52
  new Word("Zhuan"), // 0x53
  new Word("Yan"), // 0x54
  new Word("Xian"), // 0x55
  new Word("Xin"), // 0x56
  new Word("Yi"), // 0x57
  new Word("Yuan"), // 0x58
  new Word("Sang"), // 0x59
  new Word("Dian"), // 0x5a
  new Word("Dian"), // 0x5b
  new Word("Jiang"), // 0x5c
  new Word("Ku"), // 0x5d
  new Word("Lei"), // 0x5e
  new Word("Liao"), // 0x5f
  new Word("Piao"), // 0x60
  new Word("Yi"), // 0x61
  new Word("Man"), // 0x62
  new Word("Qi"), // 0x63
  new Word("Rao"), // 0x64
  new Word("Hao"), // 0x65
  new Word("Qiao"), // 0x66
  new Word("Gu"), // 0x67
  new Word("Xun"), // 0x68
  new Word("Qian"), // 0x69
  new Word("Hui"), // 0x6a
  new Word("Zhan"), // 0x6b
  new Word("Ru"), // 0x6c
  new Word("Hong"), // 0x6d
  new Word("Bin"), // 0x6e
  new Word("Xian"), // 0x6f
  new Word("Pin"), // 0x70
  new Word("Lu"), // 0x71
  new Word("Lan"), // 0x72
  new Word("Nie"), // 0x73
  new Word("Quan"), // 0x74
  new Word("Ye"), // 0x75
  new Word("Ding"), // 0x76
  new Word("Qing"), // 0x77
  new Word("Han"), // 0x78
  new Word("Xiang"), // 0x79
  new Word("Shun"), // 0x7a
  new Word("Xu"), // 0x7b
  new Word("Xu"), // 0x7c
  new Word("Wan"), // 0x7d
  new Word("Gu"), // 0x7e
  new Word("Dun"), // 0x7f
  new Word("Qi"), // 0x80
  new Word("Ban"), // 0x81
  new Word("Song"), // 0x82
  new Word("Hang"), // 0x83
  new Word("Yu"), // 0x84
  new Word("Lu"), // 0x85
  new Word("Ling"), // 0x86
  new Word("Po"), // 0x87
  new Word("Jing"), // 0x88
  new Word("Jie"), // 0x89
  new Word("Jia"), // 0x8a
  new Word("Tian"), // 0x8b
  new Word("Han"), // 0x8c
  new Word("Ying"), // 0x8d
  new Word("Jiong"), // 0x8e
  new Word("Hai"), // 0x8f
  new Word("Yi"), // 0x90
  new Word("Pin"), // 0x91
  new Word("Hui"), // 0x92
  new Word("Tui"), // 0x93
  new Word("Han"), // 0x94
  new Word("Ying"), // 0x95
  new Word("Ying"), // 0x96
  new Word("Ke"), // 0x97
  new Word("Ti"), // 0x98
  new Word("Yong"), // 0x99
  new Word("E"), // 0x9a
  new Word("Zhuan"), // 0x9b
  new Word("Yan"), // 0x9c
  new Word("E"), // 0x9d
  new Word("Nie"), // 0x9e
  new Word("Man"), // 0x9f
  new Word("Dian"), // 0xa0
  new Word("Sang"), // 0xa1
  new Word("Hao"), // 0xa2
  new Word("Lei"), // 0xa3
  new Word("Zhan"), // 0xa4
  new Word("Ru"), // 0xa5
  new Word("Pin"), // 0xa6
  new Word("Quan"), // 0xa7
  new Word("Feng"), // 0xa8
  new Word("Biao"), // 0xa9
  new Word("Oroshi"), // 0xaa
  new Word("Fu"), // 0xab
  new Word("Xia"), // 0xac
  new Word("Zhan"), // 0xad
  new Word("Biao"), // 0xae
  new Word("Sa"), // 0xaf
  new Word("Ba"), // 0xb0
  new Word("Tai"), // 0xb1
  new Word("Lie"), // 0xb2
  new Word("Gua"), // 0xb3
  new Word("Xuan"), // 0xb4
  new Word("Shao"), // 0xb5
  new Word("Ju"), // 0xb6
  new Word("Bi"), // 0xb7
  new Word("Si"), // 0xb8
  new Word("Wei"), // 0xb9
  new Word("Yang"), // 0xba
  new Word("Yao"), // 0xbb
  new Word("Sou"), // 0xbc
  new Word("Kai"), // 0xbd
  new Word("Sao"), // 0xbe
  new Word("Fan"), // 0xbf
  new Word("Liu"), // 0xc0
  new Word("Xi"), // 0xc1
  new Word("Liao"), // 0xc2
  new Word("Piao"), // 0xc3
  new Word("Piao"), // 0xc4
  new Word("Liu"), // 0xc5
  new Word("Biao"), // 0xc6
  new Word("Biao"), // 0xc7
  new Word("Biao"), // 0xc8
  new Word("Liao"), // 0xc9
  null, // 0xca
  new Word("Se"), // 0xcb
  new Word("Feng"), // 0xcc
  new Word("Biao"), // 0xcd
  new Word("Feng"), // 0xce
  new Word("Yang"), // 0xcf
  new Word("Zhan"), // 0xd0
  new Word("Biao"), // 0xd1
  new Word("Sa"), // 0xd2
  new Word("Ju"), // 0xd3
  new Word("Si"), // 0xd4
  new Word("Sou"), // 0xd5
  new Word("Yao"), // 0xd6
  new Word("Liu"), // 0xd7
  new Word("Piao"), // 0xd8
  new Word("Biao"), // 0xd9
  new Word("Biao"), // 0xda
  new Word("Fei"), // 0xdb
  new Word("Fan"), // 0xdc
  new Word("Fei"), // 0xdd
  new Word("Fei"), // 0xde
  new Word("Shi"), // 0xdf
  new Word("Shi"), // 0xe0
  new Word("Can"), // 0xe1
  new Word("Ji"), // 0xe2
  new Word("Ding"), // 0xe3
  new Word("Si"), // 0xe4
  new Word("Tuo"), // 0xe5
  new Word("Zhan"), // 0xe6
  new Word("Sun"), // 0xe7
  new Word("Xiang"), // 0xe8
  new Word("Tun"), // 0xe9
  new Word("Ren"), // 0xea
  new Word("Yu"), // 0xeb
  new Word("Juan"), // 0xec
  new Word("Chi"), // 0xed
  new Word("Yin"), // 0xee
  new Word("Fan"), // 0xef
  new Word("Fan"), // 0xf0
  new Word("Sun"), // 0xf1
  new Word("Yin"), // 0xf2
  new Word("Zhu"), // 0xf3
  new Word("Yi"), // 0xf4
  new Word("Zhai"), // 0xf5
  new Word("Bi"), // 0xf6
  new Word("Jie"), // 0xf7
  new Word("Tao"), // 0xf8
  new Word("Liu"), // 0xf9
  new Word("Ci"), // 0xfa
  new Word("Tie"), // 0xfb
  new Word("Si"), // 0xfc
  new Word("Bao"), // 0xfd
  new Word("Shi"), // 0xfe
  new Word("Duo") // 0xff
  };
}