/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+9Dxx (CJK Unified Ideographs).
 */
final class X9d extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Fou"), // 0x00
  new Word("Yiao"), // 0x01
  new Word("Jue"), // 0x02
  new Word("Jue"), // 0x03
  new Word("Pi"), // 0x04
  new Word("Huan"), // 0x05
  new Word("Zhen"), // 0x06
  new Word("Bao"), // 0x07
  new Word("Yan"), // 0x08
  new Word("Ya"), // 0x09
  new Word("Zheng"), // 0x0a
  new Word("Fang"), // 0x0b
  new Word("Feng"), // 0x0c
  new Word("Wen"), // 0x0d
  new Word("Ou"), // 0x0e
  new Word("Te"), // 0x0f
  new Word("Jia"), // 0x10
  new Word("Nu"), // 0x11
  new Word("Ling"), // 0x12
  new Word("Mie"), // 0x13
  new Word("Fu"), // 0x14
  new Word("Tuo"), // 0x15
  new Word("Wen"), // 0x16
  new Word("Li"), // 0x17
  new Word("Bian"), // 0x18
  new Word("Zhi"), // 0x19
  new Word("Ge"), // 0x1a
  new Word("Yuan"), // 0x1b
  new Word("Zi"), // 0x1c
  new Word("Qu"), // 0x1d
  new Word("Xiao"), // 0x1e
  new Word("Zhi"), // 0x1f
  new Word("Dan"), // 0x20
  new Word("Ju"), // 0x21
  new Word("You"), // 0x22
  new Word("Gu"), // 0x23
  new Word("Zhong"), // 0x24
  new Word("Yu"), // 0x25
  new Word("Yang"), // 0x26
  new Word("Rong"), // 0x27
  new Word("Ya"), // 0x28
  new Word("Tie"), // 0x29
  new Word("Yu"), // 0x2a
  new Word("Shigi"), // 0x2b
  new Word("Ying"), // 0x2c
  new Word("Zhui"), // 0x2d
  new Word("Wu"), // 0x2e
  new Word("Er"), // 0x2f
  new Word("Gua"), // 0x30
  new Word("Ai"), // 0x31
  new Word("Zhi"), // 0x32
  new Word("Yan"), // 0x33
  new Word("Heng"), // 0x34
  new Word("Jiao"), // 0x35
  new Word("Ji"), // 0x36
  new Word("Lie"), // 0x37
  new Word("Zhu"), // 0x38
  new Word("Ren"), // 0x39
  new Word("Yi"), // 0x3a
  new Word("Hong"), // 0x3b
  new Word("Luo"), // 0x3c
  new Word("Ru"), // 0x3d
  new Word("Mou"), // 0x3e
  new Word("Ge"), // 0x3f
  new Word("Ren"), // 0x40
  new Word("Jiao"), // 0x41
  new Word("Xiu"), // 0x42
  new Word("Zhou"), // 0x43
  new Word("Zhi"), // 0x44
  new Word("Luo"), // 0x45
  new Word("Chidori"), // 0x46
  new Word("Toki"), // 0x47
  new Word("Ten"), // 0x48
  new Word("Luan"), // 0x49
  new Word("Jia"), // 0x4a
  new Word("Ji"), // 0x4b
  new Word("Yu"), // 0x4c
  new Word("Huan"), // 0x4d
  new Word("Tuo"), // 0x4e
  new Word("Bu"), // 0x4f
  new Word("Wu"), // 0x50
  new Word("Juan"), // 0x51
  new Word("Yu"), // 0x52
  new Word("Bo"), // 0x53
  new Word("Xun"), // 0x54
  new Word("Xun"), // 0x55
  new Word("Bi"), // 0x56
  new Word("Xi"), // 0x57
  new Word("Jun"), // 0x58
  new Word("Ju"), // 0x59
  new Word("Tu"), // 0x5a
  new Word("Jing"), // 0x5b
  new Word("Ti"), // 0x5c
  new Word("E"), // 0x5d
  new Word("E"), // 0x5e
  new Word("Kuang"), // 0x5f
  new Word("Hu"), // 0x60
  new Word("Wu"), // 0x61
  new Word("Shen"), // 0x62
  new Word("Lai"), // 0x63
  new Word("Ikaruga"), // 0x64
  new Word("Kakesu"), // 0x65
  new Word("Lu"), // 0x66
  new Word("Ping"), // 0x67
  new Word("Shu"), // 0x68
  new Word("Fu"), // 0x69
  new Word("An"), // 0x6a
  new Word("Zhao"), // 0x6b
  new Word("Peng"), // 0x6c
  new Word("Qin"), // 0x6d
  new Word("Qian"), // 0x6e
  new Word("Bei"), // 0x6f
  new Word("Diao"), // 0x70
  new Word("Lu"), // 0x71
  new Word("Que"), // 0x72
  new Word("Jian"), // 0x73
  new Word("Ju"), // 0x74
  new Word("Tu"), // 0x75
  new Word("Ya"), // 0x76
  new Word("Yuan"), // 0x77
  new Word("Qi"), // 0x78
  new Word("Li"), // 0x79
  new Word("Ye"), // 0x7a
  new Word("Zhui"), // 0x7b
  new Word("Kong"), // 0x7c
  new Word("Zhui"), // 0x7d
  new Word("Kun"), // 0x7e
  new Word("Sheng"), // 0x7f
  new Word("Qi"), // 0x80
  new Word("Jing"), // 0x81
  new Word("Yi"), // 0x82
  new Word("Yi"), // 0x83
  new Word("Jing"), // 0x84
  new Word("Zi"), // 0x85
  new Word("Lai"), // 0x86
  new Word("Dong"), // 0x87
  new Word("Qi"), // 0x88
  new Word("Chun"), // 0x89
  new Word("Geng"), // 0x8a
  new Word("Ju"), // 0x8b
  new Word("Qu"), // 0x8c
  new Word("Isuka"), // 0x8d
  new Word("Kikuitadaki"), // 0x8e
  new Word("Ji"), // 0x8f
  new Word("Shu"), // 0x90
  null, // 0x91
  new Word("Chi"), // 0x92
  new Word("Miao"), // 0x93
  new Word("Rou"), // 0x94
  new Word("An"), // 0x95
  new Word("Qiu"), // 0x96
  new Word("Ti"), // 0x97
  new Word("Hu"), // 0x98
  new Word("Ti"), // 0x99
  new Word("E"), // 0x9a
  new Word("Jie"), // 0x9b
  new Word("Mao"), // 0x9c
  new Word("Fu"), // 0x9d
  new Word("Chun"), // 0x9e
  new Word("Tu"), // 0x9f
  new Word("Yan"), // 0xa0
  new Word("He"), // 0xa1
  new Word("Yuan"), // 0xa2
  new Word("Pian"), // 0xa3
  new Word("Yun"), // 0xa4
  new Word("Mei"), // 0xa5
  new Word("Hu"), // 0xa6
  new Word("Ying"), // 0xa7
  new Word("Dun"), // 0xa8
  new Word("Mu"), // 0xa9
  new Word("Ju"), // 0xaa
  new Word("Tsugumi"), // 0xab
  new Word("Cang"), // 0xac
  new Word("Fang"), // 0xad
  new Word("Gu"), // 0xae
  new Word("Ying"), // 0xaf
  new Word("Yuan"), // 0xb0
  new Word("Xuan"), // 0xb1
  new Word("Weng"), // 0xb2
  new Word("Shi"), // 0xb3
  new Word("He"), // 0xb4
  new Word("Chu"), // 0xb5
  new Word("Tang"), // 0xb6
  new Word("Xia"), // 0xb7
  new Word("Ruo"), // 0xb8
  new Word("Liu"), // 0xb9
  new Word("Ji"), // 0xba
  new Word("Gu"), // 0xbb
  new Word("Jian"), // 0xbc
  new Word("Zhun"), // 0xbd
  new Word("Han"), // 0xbe
  new Word("Zi"), // 0xbf
  new Word("Zi"), // 0xc0
  new Word("Ni"), // 0xc1
  new Word("Yao"), // 0xc2
  new Word("Yan"), // 0xc3
  new Word("Ji"), // 0xc4
  new Word("Li"), // 0xc5
  new Word("Tian"), // 0xc6
  new Word("Kou"), // 0xc7
  new Word("Ti"), // 0xc8
  new Word("Ti"), // 0xc9
  new Word("Ni"), // 0xca
  new Word("Tu"), // 0xcb
  new Word("Ma"), // 0xcc
  new Word("Jiao"), // 0xcd
  new Word("Gao"), // 0xce
  new Word("Tian"), // 0xcf
  new Word("Chen"), // 0xd0
  new Word("Li"), // 0xd1
  new Word("Zhuan"), // 0xd2
  new Word("Zhe"), // 0xd3
  new Word("Ao"), // 0xd4
  new Word("Yao"), // 0xd5
  new Word("Yi"), // 0xd6
  new Word("Ou"), // 0xd7
  new Word("Chi"), // 0xd8
  new Word("Zhi"), // 0xd9
  new Word("Liao"), // 0xda
  new Word("Rong"), // 0xdb
  new Word("Lou"), // 0xdc
  new Word("Bi"), // 0xdd
  new Word("Shuang"), // 0xde
  new Word("Zhuo"), // 0xdf
  new Word("Yu"), // 0xe0
  new Word("Wu"), // 0xe1
  new Word("Jue"), // 0xe2
  new Word("Yin"), // 0xe3
  new Word("Quan"), // 0xe4
  new Word("Si"), // 0xe5
  new Word("Jiao"), // 0xe6
  new Word("Yi"), // 0xe7
  new Word("Hua"), // 0xe8
  new Word("Bi"), // 0xe9
  new Word("Ying"), // 0xea
  new Word("Su"), // 0xeb
  new Word("Huang"), // 0xec
  new Word("Fan"), // 0xed
  new Word("Jiao"), // 0xee
  new Word("Liao"), // 0xef
  new Word("Yan"), // 0xf0
  new Word("Kao"), // 0xf1
  new Word("Jiu"), // 0xf2
  new Word("Xian"), // 0xf3
  new Word("Xian"), // 0xf4
  new Word("Tu"), // 0xf5
  new Word("Mai"), // 0xf6
  new Word("Zun"), // 0xf7
  new Word("Yu"), // 0xf8
  new Word("Ying"), // 0xf9
  new Word("Lu"), // 0xfa
  new Word("Tuan"), // 0xfb
  new Word("Xian"), // 0xfc
  new Word("Xue"), // 0xfd
  new Word("Yi"), // 0xfe
  new Word("Pi") // 0xff
  };
}