/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+A3xx (Yi Syllables).
 */
final class Xa3 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("nzup"), // 0x00
  new Letters("nzurx"), // 0x01
  new Letters("nzur"), // 0x02
  new Letters("nzyt"), // 0x03
  new Letters("nzyx"), // 0x04
  new Letters("nzy"), // 0x05
  new Letters("nzyp"), // 0x06
  new Letters("nzyrx"), // 0x07
  new Letters("nzyr"), // 0x08
  new Letters("sit"), // 0x09
  new Letters("six"), // 0x0a
  LO_SI, // 0x0b
  new Letters("sip"), // 0x0c
  new Letters("siex"), // 0x0d
  new Letters("sie"), // 0x0e
  new Letters("siep"), // 0x0f
  new Letters("sat"), // 0x10
  new Letters("sax"), // 0x11
  LO_SA, // 0x12
  new Letters("sap"), // 0x13
  new Letters("suox"), // 0x14
  new Letters("suo"), // 0x15
  new Letters("suop"), // 0x16
  new Letters("sot"), // 0x17
  new Letters("sox"), // 0x18
  LO_SO, // 0x19
  new Letters("sop"), // 0x1a
  new Letters("sex"), // 0x1b
  LO_SE, // 0x1c
  new Letters("sep"), // 0x1d
  new Letters("sut"), // 0x1e
  new Letters("sux"), // 0x1f
  LO_SU, // 0x20
  new Letters("sup"), // 0x21
  new Letters("surx"), // 0x22
  new Letters("sur"), // 0x23
  new Letters("syt"), // 0x24
  new Letters("syx"), // 0x25
  new Letters("sy"), // 0x26
  new Letters("syp"), // 0x27
  new Letters("syrx"), // 0x28
  new Letters("syr"), // 0x29
  new Letters("ssit"), // 0x2a
  new Letters("ssix"), // 0x2b
  new Letters("ssi"), // 0x2c
  new Letters("ssip"), // 0x2d
  new Letters("ssiex"), // 0x2e
  new Letters("ssie"), // 0x2f
  new Letters("ssiep"), // 0x30
  new Letters("ssat"), // 0x31
  new Letters("ssax"), // 0x32
  new Letters("ssa"), // 0x33
  new Letters("ssap"), // 0x34
  new Letters("ssot"), // 0x35
  new Letters("ssox"), // 0x36
  new Letters("sso"), // 0x37
  new Letters("ssop"), // 0x38
  new Letters("ssex"), // 0x39
  new Letters("sse"), // 0x3a
  new Letters("ssep"), // 0x3b
  new Letters("ssut"), // 0x3c
  new Letters("ssux"), // 0x3d
  new Letters("ssu"), // 0x3e
  new Letters("ssup"), // 0x3f
  new Letters("ssyt"), // 0x40
  new Letters("ssyx"), // 0x41
  new Letters("ssy"), // 0x42
  new Letters("ssyp"), // 0x43
  new Letters("ssyrx"), // 0x44
  new Letters("ssyr"), // 0x45
  new Letters("zhat"), // 0x46
  new Letters("zhax"), // 0x47
  new Letters("zha"), // 0x48
  new Letters("zhap"), // 0x49
  new Letters("zhuox"), // 0x4a
  new Letters("zhuo"), // 0x4b
  new Letters("zhuop"), // 0x4c
  new Letters("zhot"), // 0x4d
  new Letters("zhox"), // 0x4e
  new Letters("zho"), // 0x4f
  new Letters("zhop"), // 0x50
  new Letters("zhet"), // 0x51
  new Letters("zhex"), // 0x52
  new Letters("zhe"), // 0x53
  new Letters("zhep"), // 0x54
  new Letters("zhut"), // 0x55
  new Letters("zhux"), // 0x56
  new Letters("zhu"), // 0x57
  new Letters("zhup"), // 0x58
  new Letters("zhurx"), // 0x59
  new Letters("zhur"), // 0x5a
  new Letters("zhyt"), // 0x5b
  new Letters("zhyx"), // 0x5c
  new Letters("zhy"), // 0x5d
  new Letters("zhyp"), // 0x5e
  new Letters("zhyrx"), // 0x5f
  new Letters("zhyr"), // 0x60
  new Letters("chat"), // 0x61
  new Letters("chax"), // 0x62
  new Letters("cha"), // 0x63
  new Letters("chap"), // 0x64
  new Letters("chuot"), // 0x65
  new Letters("chuox"), // 0x66
  new Letters("chuo"), // 0x67
  new Letters("chuop"), // 0x68
  new Letters("chot"), // 0x69
  new Letters("chox"), // 0x6a
  new Letters("cho"), // 0x6b
  new Letters("chop"), // 0x6c
  new Letters("chet"), // 0x6d
  new Letters("chex"), // 0x6e
  new Letters("che"), // 0x6f
  new Letters("chep"), // 0x70
  new Letters("chux"), // 0x71
  new Letters("chu"), // 0x72
  new Letters("chup"), // 0x73
  new Letters("churx"), // 0x74
  new Letters("chur"), // 0x75
  new Letters("chyt"), // 0x76
  new Letters("chyx"), // 0x77
  new Letters("chy"), // 0x78
  new Letters("chyp"), // 0x79
  new Letters("chyrx"), // 0x7a
  new Letters("chyr"), // 0x7b
  new Letters("rrax"), // 0x7c
  new Letters("rra"), // 0x7d
  new Letters("rruox"), // 0x7e
  new Letters("rruo"), // 0x7f
  new Letters("rrot"), // 0x80
  new Letters("rrox"), // 0x81
  new Letters("rro"), // 0x82
  new Letters("rrop"), // 0x83
  new Letters("rret"), // 0x84
  new Letters("rrex"), // 0x85
  new Letters("rre"), // 0x86
  new Letters("rrep"), // 0x87
  new Letters("rrut"), // 0x88
  new Letters("rrux"), // 0x89
  new Letters("rru"), // 0x8a
  new Letters("rrup"), // 0x8b
  new Letters("rrurx"), // 0x8c
  new Letters("rrur"), // 0x8d
  new Letters("rryt"), // 0x8e
  new Letters("rryx"), // 0x8f
  new Letters("rry"), // 0x90
  new Letters("rryp"), // 0x91
  new Letters("rryrx"), // 0x92
  new Letters("rryr"), // 0x93
  new Letters("nrat"), // 0x94
  new Letters("nrax"), // 0x95
  new Letters("nra"), // 0x96
  new Letters("nrap"), // 0x97
  new Letters("nrox"), // 0x98
  new Letters("nro"), // 0x99
  new Letters("nrop"), // 0x9a
  new Letters("nret"), // 0x9b
  new Letters("nrex"), // 0x9c
  new Letters("nre"), // 0x9d
  new Letters("nrep"), // 0x9e
  new Letters("nrut"), // 0x9f
  new Letters("nrux"), // 0xa0
  new Letters("nru"), // 0xa1
  new Letters("nrup"), // 0xa2
  new Letters("nrurx"), // 0xa3
  new Letters("nrur"), // 0xa4
  new Letters("nryt"), // 0xa5
  new Letters("nryx"), // 0xa6
  new Letters("nry"), // 0xa7
  new Letters("nryp"), // 0xa8
  new Letters("nryrx"), // 0xa9
  new Letters("nryr"), // 0xaa
  new Letters("shat"), // 0xab
  new Letters("shax"), // 0xac
  new Letters("sha"), // 0xad
  new Letters("shap"), // 0xae
  new Letters("shuox"), // 0xaf
  new Letters("shuo"), // 0xb0
  new Letters("shuop"), // 0xb1
  new Letters("shot"), // 0xb2
  new Letters("shox"), // 0xb3
  new Letters("sho"), // 0xb4
  new Letters("shop"), // 0xb5
  new Letters("shet"), // 0xb6
  new Letters("shex"), // 0xb7
  new Letters("she"), // 0xb8
  new Letters("shep"), // 0xb9
  new Letters("shut"), // 0xba
  new Letters("shux"), // 0xbb
  new Letters("shu"), // 0xbc
  new Letters("shup"), // 0xbd
  new Letters("shurx"), // 0xbe
  new Letters("shur"), // 0xbf
  new Letters("shyt"), // 0xc0
  new Letters("shyx"), // 0xc1
  new Letters("shy"), // 0xc2
  new Letters("shyp"), // 0xc3
  new Letters("shyrx"), // 0xc4
  new Letters("shyr"), // 0xc5
  new Letters("rat"), // 0xc6
  new Letters("rax"), // 0xc7
  LO_RA, // 0xc8
  new Letters("rap"), // 0xc9
  new Letters("ruox"), // 0xca
  new Letters("ruo"), // 0xcb
  new Letters("ruop"), // 0xcc
  new Letters("rot"), // 0xcd
  new Letters("rox"), // 0xce
  LO_RO, // 0xcf
  new Letters("rop"), // 0xd0
  new Letters("rex"), // 0xd1
  LO_RE, // 0xd2
  new Letters("rep"), // 0xd3
  new Letters("rut"), // 0xd4
  new Letters("rux"), // 0xd5
  LO_RU, // 0xd6
  new Letters("rup"), // 0xd7
  new Letters("rurx"), // 0xd8
  new Letters("rur"), // 0xd9
  new Letters("ryt"), // 0xda
  new Letters("ryx"), // 0xdb
  new Letters("ry"), // 0xdc
  new Letters("ryp"), // 0xdd
  new Letters("ryrx"), // 0xde
  new Letters("ryr"), // 0xdf
  new Letters("jit"), // 0xe0
  new Letters("jix"), // 0xe1
  new Letters("ji"), // 0xe2
  new Letters("jip"), // 0xe3
  new Letters("jiet"), // 0xe4
  new Letters("jiex"), // 0xe5
  new Letters("jie"), // 0xe6
  new Letters("jiep"), // 0xe7
  new Letters("juot"), // 0xe8
  new Letters("juox"), // 0xe9
  new Letters("juo"), // 0xea
  new Letters("juop"), // 0xeb
  new Letters("jot"), // 0xec
  new Letters("jox"), // 0xed
  LO_JO, // 0xee
  new Letters("jop"), // 0xef
  new Letters("jut"), // 0xf0
  new Letters("jux"), // 0xf1
  LO_JU, // 0xf2
  new Letters("jup"), // 0xf3
  new Letters("jurx"), // 0xf4
  new Letters("jur"), // 0xf5
  new Letters("jyt"), // 0xf6
  new Letters("jyx"), // 0xf7
  new Letters("jy"), // 0xf8
  new Letters("jyp"), // 0xf9
  new Letters("jyrx"), // 0xfa
  new Letters("jyr"), // 0xfb
  new Letters("qit"), // 0xfc
  new Letters("qix"), // 0xfd
  new Letters("qi"), // 0xfe
  new Letters("qip") // 0xff
  };
}