/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+ACxx (Hangul Syllables for Korean).
 */
final class Xac extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  LO_GA, // 0x00
  new Letters("gag"), // 0x01
  new Letters("gagg"), // 0x02
  new Letters("gags"), // 0x03
  new Letters("gan"), // 0x04
  new Letters("ganj"), // 0x05
  new Letters("ganh"), // 0x06
  new Letters("gad"), // 0x07
  new Letters("gal"), // 0x08
  new Letters("galg"), // 0x09
  new Letters("galm"), // 0x0a
  new Letters("galb"), // 0x0b
  new Letters("gals"), // 0x0c
  new Letters("galt"), // 0x0d
  new Letters("galp"), // 0x0e
  new Letters("galh"), // 0x0f
  new Letters("gam"), // 0x10
  new Letters("gab"), // 0x11
  new Letters("gabs"), // 0x12
  new Letters("gas"), // 0x13
  new Letters("gass"), // 0x14
  new Letters("gang"), // 0x15
  new Letters("gaj"), // 0x16
  new Letters("gac"), // 0x17
  new Letters("gak"), // 0x18
  new Letters("gat"), // 0x19
  new Letters("gap"), // 0x1a
  new Letters("gah"), // 0x1b
  new Letters("gae"), // 0x1c
  new Letters("gaeg"), // 0x1d
  new Letters("gaegg"), // 0x1e
  new Letters("gaegs"), // 0x1f
  new Letters("gaen"), // 0x20
  new Letters("gaenj"), // 0x21
  new Letters("gaenh"), // 0x22
  new Letters("gaed"), // 0x23
  new Letters("gael"), // 0x24
  new Letters("gaelg"), // 0x25
  new Letters("gaelm"), // 0x26
  new Letters("gaelb"), // 0x27
  new Letters("gaels"), // 0x28
  new Letters("gaelt"), // 0x29
  new Letters("gaelp"), // 0x2a
  new Letters("gaelh"), // 0x2b
  new Letters("gaem"), // 0x2c
  new Letters("gaeb"), // 0x2d
  new Letters("gaebs"), // 0x2e
  new Letters("gaes"), // 0x2f
  new Letters("gaess"), // 0x30
  new Letters("gaeng"), // 0x31
  new Letters("gaej"), // 0x32
  new Letters("gaec"), // 0x33
  new Letters("gaek"), // 0x34
  new Letters("gaet"), // 0x35
  new Letters("gaep"), // 0x36
  new Letters("gaeh"), // 0x37
  new Letters("gya"), // 0x38
  new Letters("gyag"), // 0x39
  new Letters("gyagg"), // 0x3a
  new Letters("gyags"), // 0x3b
  new Letters("gyan"), // 0x3c
  new Letters("gyanj"), // 0x3d
  new Letters("gyanh"), // 0x3e
  new Letters("gyad"), // 0x3f
  new Letters("gyal"), // 0x40
  new Letters("gyalg"), // 0x41
  new Letters("gyalm"), // 0x42
  new Letters("gyalb"), // 0x43
  new Letters("gyals"), // 0x44
  new Letters("gyalt"), // 0x45
  new Letters("gyalp"), // 0x46
  new Letters("gyalh"), // 0x47
  new Letters("gyam"), // 0x48
  new Letters("gyab"), // 0x49
  new Letters("gyabs"), // 0x4a
  new Letters("gyas"), // 0x4b
  new Letters("gyass"), // 0x4c
  new Letters("gyang"), // 0x4d
  new Letters("gyaj"), // 0x4e
  new Letters("gyac"), // 0x4f
  new Letters("gyak"), // 0x50
  new Letters("gyat"), // 0x51
  new Letters("gyap"), // 0x52
  new Letters("gyah"), // 0x53
  new Letters("gyae"), // 0x54
  new Letters("gyaeg"), // 0x55
  new Letters("gyaegg"), // 0x56
  new Letters("gyaegs"), // 0x57
  new Letters("gyaen"), // 0x58
  new Letters("gyaenj"), // 0x59
  new Letters("gyaenh"), // 0x5a
  new Letters("gyaed"), // 0x5b
  new Letters("gyael"), // 0x5c
  new Letters("gyaelg"), // 0x5d
  new Letters("gyaelm"), // 0x5e
  new Letters("gyaelb"), // 0x5f
  new Letters("gyaels"), // 0x60
  new Letters("gyaelt"), // 0x61
  new Letters("gyaelp"), // 0x62
  new Letters("gyaelh"), // 0x63
  new Letters("gyaem"), // 0x64
  new Letters("gyaeb"), // 0x65
  new Letters("gyaebs"), // 0x66
  new Letters("gyaes"), // 0x67
  new Letters("gyaess"), // 0x68
  new Letters("gyaeng"), // 0x69
  new Letters("gyaej"), // 0x6a
  new Letters("gyaec"), // 0x6b
  new Letters("gyaek"), // 0x6c
  new Letters("gyaet"), // 0x6d
  new Letters("gyaep"), // 0x6e
  new Letters("gyaeh"), // 0x6f
  new Letters("geo"), // 0x70
  new Letters("geog"), // 0x71
  new Letters("geogg"), // 0x72
  new Letters("geogs"), // 0x73
  new Letters("geon"), // 0x74
  new Letters("geonj"), // 0x75
  new Letters("geonh"), // 0x76
  new Letters("geod"), // 0x77
  new Letters("geol"), // 0x78
  new Letters("geolg"), // 0x79
  new Letters("geolm"), // 0x7a
  new Letters("geolb"), // 0x7b
  new Letters("geols"), // 0x7c
  new Letters("geolt"), // 0x7d
  new Letters("geolp"), // 0x7e
  new Letters("geolh"), // 0x7f
  new Letters("geom"), // 0x80
  new Letters("geob"), // 0x81
  new Letters("geobs"), // 0x82
  new Letters("geos"), // 0x83
  new Letters("geoss"), // 0x84
  new Letters("geong"), // 0x85
  new Letters("geoj"), // 0x86
  new Letters("geoc"), // 0x87
  new Letters("geok"), // 0x88
  new Letters("geot"), // 0x89
  new Letters("geop"), // 0x8a
  new Letters("geoh"), // 0x8b
  LO_GE, // 0x8c
  new Letters("geg"), // 0x8d
  new Letters("gegg"), // 0x8e
  new Letters("gegs"), // 0x8f
  new Letters("gen"), // 0x90
  new Letters("genj"), // 0x91
  new Letters("genh"), // 0x92
  new Letters("ged"), // 0x93
  new Letters("gel"), // 0x94
  new Letters("gelg"), // 0x95
  new Letters("gelm"), // 0x96
  new Letters("gelb"), // 0x97
  new Letters("gels"), // 0x98
  new Letters("gelt"), // 0x99
  new Letters("gelp"), // 0x9a
  new Letters("gelh"), // 0x9b
  new Letters("gem"), // 0x9c
  new Letters("geb"), // 0x9d
  new Letters("gebs"), // 0x9e
  new Letters("ges"), // 0x9f
  new Letters("gess"), // 0xa0
  new Letters("geng"), // 0xa1
  new Letters("gej"), // 0xa2
  new Letters("gec"), // 0xa3
  new Letters("gek"), // 0xa4
  new Letters("get"), // 0xa5
  new Letters("gep"), // 0xa6
  new Letters("geh"), // 0xa7
  new Letters("gyeo"), // 0xa8
  new Letters("gyeog"), // 0xa9
  new Letters("gyeogg"), // 0xaa
  new Letters("gyeogs"), // 0xab
  new Letters("gyeon"), // 0xac
  new Letters("gyeonj"), // 0xad
  new Letters("gyeonh"), // 0xae
  new Letters("gyeod"), // 0xaf
  new Letters("gyeol"), // 0xb0
  new Letters("gyeolg"), // 0xb1
  new Letters("gyeolm"), // 0xb2
  new Letters("gyeolb"), // 0xb3
  new Letters("gyeols"), // 0xb4
  new Letters("gyeolt"), // 0xb5
  new Letters("gyeolp"), // 0xb6
  new Letters("gyeolh"), // 0xb7
  new Letters("gyeom"), // 0xb8
  new Letters("gyeob"), // 0xb9
  new Letters("gyeobs"), // 0xba
  new Letters("gyeos"), // 0xbb
  new Letters("gyeoss"), // 0xbc
  new Letters("gyeong"), // 0xbd
  new Letters("gyeoj"), // 0xbe
  new Letters("gyeoc"), // 0xbf
  new Letters("gyeok"), // 0xc0
  new Letters("gyeot"), // 0xc1
  new Letters("gyeop"), // 0xc2
  new Letters("gyeoh"), // 0xc3
  new Letters("gye"), // 0xc4
  new Letters("gyeg"), // 0xc5
  new Letters("gyegg"), // 0xc6
  new Letters("gyegs"), // 0xc7
  new Letters("gyen"), // 0xc8
  new Letters("gyenj"), // 0xc9
  new Letters("gyenh"), // 0xca
  new Letters("gyed"), // 0xcb
  new Letters("gyel"), // 0xcc
  new Letters("gyelg"), // 0xcd
  new Letters("gyelm"), // 0xce
  new Letters("gyelb"), // 0xcf
  new Letters("gyels"), // 0xd0
  new Letters("gyelt"), // 0xd1
  new Letters("gyelp"), // 0xd2
  new Letters("gyelh"), // 0xd3
  new Letters("gyem"), // 0xd4
  new Letters("gyeb"), // 0xd5
  new Letters("gyebs"), // 0xd6
  new Letters("gyes"), // 0xd7
  new Letters("gyess"), // 0xd8
  new Letters("gyeng"), // 0xd9
  new Letters("gyej"), // 0xda
  new Letters("gyec"), // 0xdb
  new Letters("gyek"), // 0xdc
  new Letters("gyet"), // 0xdd
  new Letters("gyep"), // 0xde
  new Letters("gyeh"), // 0xdf
  new Letters("go"), // 0xe0
  new Letters("gog"), // 0xe1
  new Letters("gogg"), // 0xe2
  new Letters("gogs"), // 0xe3
  new Letters("gon"), // 0xe4
  new Letters("gonj"), // 0xe5
  new Letters("gonh"), // 0xe6
  new Letters("god"), // 0xe7
  new Letters("gol"), // 0xe8
  new Letters("golg"), // 0xe9
  new Letters("golm"), // 0xea
  new Letters("golb"), // 0xeb
  new Letters("gols"), // 0xec
  new Letters("golt"), // 0xed
  new Letters("golp"), // 0xee
  new Letters("golh"), // 0xef
  new Letters("gom"), // 0xf0
  new Letters("gob"), // 0xf1
  new Letters("gobs"), // 0xf2
  new Letters("gos"), // 0xf3
  new Letters("goss"), // 0xf4
  new Letters("gong"), // 0xf5
  new Letters("goj"), // 0xf6
  new Letters("goc"), // 0xf7
  new Letters("gok"), // 0xf8
  new Letters("got"), // 0xf9
  new Letters("gop"), // 0xfa
  new Letters("goh"), // 0xfb
  new Letters("gwa"), // 0xfc
  new Letters("gwag"), // 0xfd
  new Letters("gwagg"), // 0xfe
  new Letters("gwags") // 0xff
  };
}