/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+AExx (Hangul Syllables for Korean).
 */
final class Xae extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("geul"), // 0x00
  new Letters("geulg"), // 0x01
  new Letters("geulm"), // 0x02
  new Letters("geulb"), // 0x03
  new Letters("geuls"), // 0x04
  new Letters("geult"), // 0x05
  new Letters("geulp"), // 0x06
  new Letters("geulh"), // 0x07
  new Letters("geum"), // 0x08
  new Letters("geub"), // 0x09
  new Letters("geubs"), // 0x0a
  new Letters("geus"), // 0x0b
  new Letters("geuss"), // 0x0c
  new Letters("geung"), // 0x0d
  new Letters("geuj"), // 0x0e
  new Letters("geuc"), // 0x0f
  new Letters("geuk"), // 0x10
  new Letters("geut"), // 0x11
  new Letters("geup"), // 0x12
  new Letters("geuh"), // 0x13
  new Letters("gyi"), // 0x14
  new Letters("gyig"), // 0x15
  new Letters("gyigg"), // 0x16
  new Letters("gyigs"), // 0x17
  new Letters("gyin"), // 0x18
  new Letters("gyinj"), // 0x19
  new Letters("gyinh"), // 0x1a
  new Letters("gyid"), // 0x1b
  new Letters("gyil"), // 0x1c
  new Letters("gyilg"), // 0x1d
  new Letters("gyilm"), // 0x1e
  new Letters("gyilb"), // 0x1f
  new Letters("gyils"), // 0x20
  new Letters("gyilt"), // 0x21
  new Letters("gyilp"), // 0x22
  new Letters("gyilh"), // 0x23
  new Letters("gyim"), // 0x24
  new Letters("gyib"), // 0x25
  new Letters("gyibs"), // 0x26
  new Letters("gyis"), // 0x27
  new Letters("gyiss"), // 0x28
  new Letters("gying"), // 0x29
  new Letters("gyij"), // 0x2a
  new Letters("gyic"), // 0x2b
  new Letters("gyik"), // 0x2c
  new Letters("gyit"), // 0x2d
  new Letters("gyip"), // 0x2e
  new Letters("gyih"), // 0x2f
  LO_GI, // 0x30
  new Letters("gig"), // 0x31
  new Letters("gigg"), // 0x32
  new Letters("gigs"), // 0x33
  new Letters("gin"), // 0x34
  new Letters("ginj"), // 0x35
  new Letters("ginh"), // 0x36
  new Letters("gid"), // 0x37
  new Letters("gil"), // 0x38
  new Letters("gilg"), // 0x39
  new Letters("gilm"), // 0x3a
  new Letters("gilb"), // 0x3b
  new Letters("gils"), // 0x3c
  new Letters("gilt"), // 0x3d
  new Letters("gilp"), // 0x3e
  new Letters("gilh"), // 0x3f
  new Letters("gim"), // 0x40
  new Letters("gib"), // 0x41
  new Letters("gibs"), // 0x42
  new Letters("gis"), // 0x43
  new Letters("giss"), // 0x44
  new Letters("ging"), // 0x45
  new Letters("gij"), // 0x46
  new Letters("gic"), // 0x47
  new Letters("gik"), // 0x48
  new Letters("git"), // 0x49
  new Letters("gip"), // 0x4a
  new Letters("gih"), // 0x4b
  new Letters("gga"), // 0x4c
  new Letters("ggag"), // 0x4d
  new Letters("ggagg"), // 0x4e
  new Letters("ggags"), // 0x4f
  new Letters("ggan"), // 0x50
  new Letters("gganj"), // 0x51
  new Letters("gganh"), // 0x52
  new Letters("ggad"), // 0x53
  new Letters("ggal"), // 0x54
  new Letters("ggalg"), // 0x55
  new Letters("ggalm"), // 0x56
  new Letters("ggalb"), // 0x57
  new Letters("ggals"), // 0x58
  new Letters("ggalt"), // 0x59
  new Letters("ggalp"), // 0x5a
  new Letters("ggalh"), // 0x5b
  new Letters("ggam"), // 0x5c
  new Letters("ggab"), // 0x5d
  new Letters("ggabs"), // 0x5e
  new Letters("ggas"), // 0x5f
  new Letters("ggass"), // 0x60
  new Letters("ggang"), // 0x61
  new Letters("ggaj"), // 0x62
  new Letters("ggac"), // 0x63
  new Letters("ggak"), // 0x64
  new Letters("ggat"), // 0x65
  new Letters("ggap"), // 0x66
  new Letters("ggah"), // 0x67
  new Letters("ggae"), // 0x68
  new Letters("ggaeg"), // 0x69
  new Letters("ggaegg"), // 0x6a
  new Letters("ggaegs"), // 0x6b
  new Letters("ggaen"), // 0x6c
  new Letters("ggaenj"), // 0x6d
  new Letters("ggaenh"), // 0x6e
  new Letters("ggaed"), // 0x6f
  new Letters("ggael"), // 0x70
  new Letters("ggaelg"), // 0x71
  new Letters("ggaelm"), // 0x72
  new Letters("ggaelb"), // 0x73
  new Letters("ggaels"), // 0x74
  new Letters("ggaelt"), // 0x75
  new Letters("ggaelp"), // 0x76
  new Letters("ggaelh"), // 0x77
  new Letters("ggaem"), // 0x78
  new Letters("ggaeb"), // 0x79
  new Letters("ggaebs"), // 0x7a
  new Letters("ggaes"), // 0x7b
  new Letters("ggaess"), // 0x7c
  new Letters("ggaeng"), // 0x7d
  new Letters("ggaej"), // 0x7e
  new Letters("ggaec"), // 0x7f
  new Letters("ggaek"), // 0x80
  new Letters("ggaet"), // 0x81
  new Letters("ggaep"), // 0x82
  new Letters("ggaeh"), // 0x83
  new Letters("ggya"), // 0x84
  new Letters("ggyag"), // 0x85
  new Letters("ggyagg"), // 0x86
  new Letters("ggyags"), // 0x87
  new Letters("ggyan"), // 0x88
  new Letters("ggyanj"), // 0x89
  new Letters("ggyanh"), // 0x8a
  new Letters("ggyad"), // 0x8b
  new Letters("ggyal"), // 0x8c
  new Letters("ggyalg"), // 0x8d
  new Letters("ggyalm"), // 0x8e
  new Letters("ggyalb"), // 0x8f
  new Letters("ggyals"), // 0x90
  new Letters("ggyalt"), // 0x91
  new Letters("ggyalp"), // 0x92
  new Letters("ggyalh"), // 0x93
  new Letters("ggyam"), // 0x94
  new Letters("ggyab"), // 0x95
  new Letters("ggyabs"), // 0x96
  new Letters("ggyas"), // 0x97
  new Letters("ggyass"), // 0x98
  new Letters("ggyang"), // 0x99
  new Letters("ggyaj"), // 0x9a
  new Letters("ggyac"), // 0x9b
  new Letters("ggyak"), // 0x9c
  new Letters("ggyat"), // 0x9d
  new Letters("ggyap"), // 0x9e
  new Letters("ggyah"), // 0x9f
  new Letters("ggyae"), // 0xa0
  new Letters("ggyaeg"), // 0xa1
  new Letters("ggyaegg"), // 0xa2
  new Letters("ggyaegs"), // 0xa3
  new Letters("ggyaen"), // 0xa4
  new Letters("ggyaenj"), // 0xa5
  new Letters("ggyaenh"), // 0xa6
  new Letters("ggyaed"), // 0xa7
  new Letters("ggyael"), // 0xa8
  new Letters("ggyaelg"), // 0xa9
  new Letters("ggyaelm"), // 0xaa
  new Letters("ggyaelb"), // 0xab
  new Letters("ggyaels"), // 0xac
  new Letters("ggyaelt"), // 0xad
  new Letters("ggyaelp"), // 0xae
  new Letters("ggyaelh"), // 0xaf
  new Letters("ggyaem"), // 0xb0
  new Letters("ggyaeb"), // 0xb1
  new Letters("ggyaebs"), // 0xb2
  new Letters("ggyaes"), // 0xb3
  new Letters("ggyaess"), // 0xb4
  new Letters("ggyaeng"), // 0xb5
  new Letters("ggyaej"), // 0xb6
  new Letters("ggyaec"), // 0xb7
  new Letters("ggyaek"), // 0xb8
  new Letters("ggyaet"), // 0xb9
  new Letters("ggyaep"), // 0xba
  new Letters("ggyaeh"), // 0xbb
  new Letters("ggeo"), // 0xbc
  new Letters("ggeog"), // 0xbd
  new Letters("ggeogg"), // 0xbe
  new Letters("ggeogs"), // 0xbf
  new Letters("ggeon"), // 0xc0
  new Letters("ggeonj"), // 0xc1
  new Letters("ggeonh"), // 0xc2
  new Letters("ggeod"), // 0xc3
  new Letters("ggeol"), // 0xc4
  new Letters("ggeolg"), // 0xc5
  new Letters("ggeolm"), // 0xc6
  new Letters("ggeolb"), // 0xc7
  new Letters("ggeols"), // 0xc8
  new Letters("ggeolt"), // 0xc9
  new Letters("ggeolp"), // 0xca
  new Letters("ggeolh"), // 0xcb
  new Letters("ggeom"), // 0xcc
  new Letters("ggeob"), // 0xcd
  new Letters("ggeobs"), // 0xce
  new Letters("ggeos"), // 0xcf
  new Letters("ggeoss"), // 0xd0
  new Letters("ggeong"), // 0xd1
  new Letters("ggeoj"), // 0xd2
  new Letters("ggeoc"), // 0xd3
  new Letters("ggeok"), // 0xd4
  new Letters("ggeot"), // 0xd5
  new Letters("ggeop"), // 0xd6
  new Letters("ggeoh"), // 0xd7
  new Letters("gge"), // 0xd8
  new Letters("ggeg"), // 0xd9
  new Letters("ggegg"), // 0xda
  new Letters("ggegs"), // 0xdb
  new Letters("ggen"), // 0xdc
  new Letters("ggenj"), // 0xdd
  new Letters("ggenh"), // 0xde
  new Letters("gged"), // 0xdf
  new Letters("ggel"), // 0xe0
  new Letters("ggelg"), // 0xe1
  new Letters("ggelm"), // 0xe2
  new Letters("ggelb"), // 0xe3
  new Letters("ggels"), // 0xe4
  new Letters("ggelt"), // 0xe5
  new Letters("ggelp"), // 0xe6
  new Letters("ggelh"), // 0xe7
  new Letters("ggem"), // 0xe8
  new Letters("ggeb"), // 0xe9
  new Letters("ggebs"), // 0xea
  new Letters("gges"), // 0xeb
  new Letters("ggess"), // 0xec
  new Letters("ggeng"), // 0xed
  new Letters("ggej"), // 0xee
  new Letters("ggec"), // 0xef
  new Letters("ggek"), // 0xf0
  new Letters("gget"), // 0xf1
  new Letters("ggep"), // 0xf2
  new Letters("ggeh"), // 0xf3
  new Letters("ggyeo"), // 0xf4
  new Letters("ggyeog"), // 0xf5
  new Letters("ggyeogg"), // 0xf6
  new Letters("ggyeogs"), // 0xf7
  new Letters("ggyeon"), // 0xf8
  new Letters("ggyeonj"), // 0xf9
  new Letters("ggyeonh"), // 0xfa
  new Letters("ggyeod"), // 0xfb
  new Letters("ggyeol"), // 0xfc
  new Letters("ggyeolg"), // 0xfd
  new Letters("ggyeolm"), // 0xfe
  new Letters("ggyeolb") // 0xff
  };
}