/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+AFxx (Hangul Syllables for Korean).
 */
final class Xaf extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("ggyeols"), // 0x00
  new Letters("ggyeolt"), // 0x01
  new Letters("ggyeolp"), // 0x02
  new Letters("ggyeolh"), // 0x03
  new Letters("ggyeom"), // 0x04
  new Letters("ggyeob"), // 0x05
  new Letters("ggyeobs"), // 0x06
  new Letters("ggyeos"), // 0x07
  new Letters("ggyeoss"), // 0x08
  new Letters("ggyeong"), // 0x09
  new Letters("ggyeoj"), // 0x0a
  new Letters("ggyeoc"), // 0x0b
  new Letters("ggyeok"), // 0x0c
  new Letters("ggyeot"), // 0x0d
  new Letters("ggyeop"), // 0x0e
  new Letters("ggyeoh"), // 0x0f
  new Letters("ggye"), // 0x10
  new Letters("ggyeg"), // 0x11
  new Letters("ggyegg"), // 0x12
  new Letters("ggyegs"), // 0x13
  new Letters("ggyen"), // 0x14
  new Letters("ggyenj"), // 0x15
  new Letters("ggyenh"), // 0x16
  new Letters("ggyed"), // 0x17
  new Letters("ggyel"), // 0x18
  new Letters("ggyelg"), // 0x19
  new Letters("ggyelm"), // 0x1a
  new Letters("ggyelb"), // 0x1b
  new Letters("ggyels"), // 0x1c
  new Letters("ggyelt"), // 0x1d
  new Letters("ggyelp"), // 0x1e
  new Letters("ggyelh"), // 0x1f
  new Letters("ggyem"), // 0x20
  new Letters("ggyeb"), // 0x21
  new Letters("ggyebs"), // 0x22
  new Letters("ggyes"), // 0x23
  new Letters("ggyess"), // 0x24
  new Letters("ggyeng"), // 0x25
  new Letters("ggyej"), // 0x26
  new Letters("ggyec"), // 0x27
  new Letters("ggyek"), // 0x28
  new Letters("ggyet"), // 0x29
  new Letters("ggyep"), // 0x2a
  new Letters("ggyeh"), // 0x2b
  new Letters("ggo"), // 0x2c
  new Letters("ggog"), // 0x2d
  new Letters("ggogg"), // 0x2e
  new Letters("ggogs"), // 0x2f
  new Letters("ggon"), // 0x30
  new Letters("ggonj"), // 0x31
  new Letters("ggonh"), // 0x32
  new Letters("ggod"), // 0x33
  new Letters("ggol"), // 0x34
  new Letters("ggolg"), // 0x35
  new Letters("ggolm"), // 0x36
  new Letters("ggolb"), // 0x37
  new Letters("ggols"), // 0x38
  new Letters("ggolt"), // 0x39
  new Letters("ggolp"), // 0x3a
  new Letters("ggolh"), // 0x3b
  new Letters("ggom"), // 0x3c
  new Letters("ggob"), // 0x3d
  new Letters("ggobs"), // 0x3e
  new Letters("ggos"), // 0x3f
  new Letters("ggoss"), // 0x40
  new Letters("ggong"), // 0x41
  new Letters("ggoj"), // 0x42
  new Letters("ggoc"), // 0x43
  new Letters("ggok"), // 0x44
  new Letters("ggot"), // 0x45
  new Letters("ggop"), // 0x46
  new Letters("ggoh"), // 0x47
  new Letters("ggwa"), // 0x48
  new Letters("ggwag"), // 0x49
  new Letters("ggwagg"), // 0x4a
  new Letters("ggwags"), // 0x4b
  new Letters("ggwan"), // 0x4c
  new Letters("ggwanj"), // 0x4d
  new Letters("ggwanh"), // 0x4e
  new Letters("ggwad"), // 0x4f
  new Letters("ggwal"), // 0x50
  new Letters("ggwalg"), // 0x51
  new Letters("ggwalm"), // 0x52
  new Letters("ggwalb"), // 0x53
  new Letters("ggwals"), // 0x54
  new Letters("ggwalt"), // 0x55
  new Letters("ggwalp"), // 0x56
  new Letters("ggwalh"), // 0x57
  new Letters("ggwam"), // 0x58
  new Letters("ggwab"), // 0x59
  new Letters("ggwabs"), // 0x5a
  new Letters("ggwas"), // 0x5b
  new Letters("ggwass"), // 0x5c
  new Letters("ggwang"), // 0x5d
  new Letters("ggwaj"), // 0x5e
  new Letters("ggwac"), // 0x5f
  new Letters("ggwak"), // 0x60
  new Letters("ggwat"), // 0x61
  new Letters("ggwap"), // 0x62
  new Letters("ggwah"), // 0x63
  new Letters("ggwae"), // 0x64
  new Letters("ggwaeg"), // 0x65
  new Letters("ggwaegg"), // 0x66
  new Letters("ggwaegs"), // 0x67
  new Letters("ggwaen"), // 0x68
  new Letters("ggwaenj"), // 0x69
  new Letters("ggwaenh"), // 0x6a
  new Letters("ggwaed"), // 0x6b
  new Letters("ggwael"), // 0x6c
  new Letters("ggwaelg"), // 0x6d
  new Letters("ggwaelm"), // 0x6e
  new Letters("ggwaelb"), // 0x6f
  new Letters("ggwaels"), // 0x70
  new Letters("ggwaelt"), // 0x71
  new Letters("ggwaelp"), // 0x72
  new Letters("ggwaelh"), // 0x73
  new Letters("ggwaem"), // 0x74
  new Letters("ggwaeb"), // 0x75
  new Letters("ggwaebs"), // 0x76
  new Letters("ggwaes"), // 0x77
  new Letters("ggwaess"), // 0x78
  new Letters("ggwaeng"), // 0x79
  new Letters("ggwaej"), // 0x7a
  new Letters("ggwaec"), // 0x7b
  new Letters("ggwaek"), // 0x7c
  new Letters("ggwaet"), // 0x7d
  new Letters("ggwaep"), // 0x7e
  new Letters("ggwaeh"), // 0x7f
  new Letters("ggoe"), // 0x80
  new Letters("ggoeg"), // 0x81
  new Letters("ggoegg"), // 0x82
  new Letters("ggoegs"), // 0x83
  new Letters("ggoen"), // 0x84
  new Letters("ggoenj"), // 0x85
  new Letters("ggoenh"), // 0x86
  new Letters("ggoed"), // 0x87
  new Letters("ggoel"), // 0x88
  new Letters("ggoelg"), // 0x89
  new Letters("ggoelm"), // 0x8a
  new Letters("ggoelb"), // 0x8b
  new Letters("ggoels"), // 0x8c
  new Letters("ggoelt"), // 0x8d
  new Letters("ggoelp"), // 0x8e
  new Letters("ggoelh"), // 0x8f
  new Letters("ggoem"), // 0x90
  new Letters("ggoeb"), // 0x91
  new Letters("ggoebs"), // 0x92
  new Letters("ggoes"), // 0x93
  new Letters("ggoess"), // 0x94
  new Letters("ggoeng"), // 0x95
  new Letters("ggoej"), // 0x96
  new Letters("ggoec"), // 0x97
  new Letters("ggoek"), // 0x98
  new Letters("ggoet"), // 0x99
  new Letters("ggoep"), // 0x9a
  new Letters("ggoeh"), // 0x9b
  new Letters("ggyo"), // 0x9c
  new Letters("ggyog"), // 0x9d
  new Letters("ggyogg"), // 0x9e
  new Letters("ggyogs"), // 0x9f
  new Letters("ggyon"), // 0xa0
  new Letters("ggyonj"), // 0xa1
  new Letters("ggyonh"), // 0xa2
  new Letters("ggyod"), // 0xa3
  new Letters("ggyol"), // 0xa4
  new Letters("ggyolg"), // 0xa5
  new Letters("ggyolm"), // 0xa6
  new Letters("ggyolb"), // 0xa7
  new Letters("ggyols"), // 0xa8
  new Letters("ggyolt"), // 0xa9
  new Letters("ggyolp"), // 0xaa
  new Letters("ggyolh"), // 0xab
  new Letters("ggyom"), // 0xac
  new Letters("ggyob"), // 0xad
  new Letters("ggyobs"), // 0xae
  new Letters("ggyos"), // 0xaf
  new Letters("ggyoss"), // 0xb0
  new Letters("ggyong"), // 0xb1
  new Letters("ggyoj"), // 0xb2
  new Letters("ggyoc"), // 0xb3
  new Letters("ggyok"), // 0xb4
  new Letters("ggyot"), // 0xb5
  new Letters("ggyop"), // 0xb6
  new Letters("ggyoh"), // 0xb7
  new Letters("ggu"), // 0xb8
  new Letters("ggug"), // 0xb9
  new Letters("ggugg"), // 0xba
  new Letters("ggugs"), // 0xbb
  new Letters("ggun"), // 0xbc
  new Letters("ggunj"), // 0xbd
  new Letters("ggunh"), // 0xbe
  new Letters("ggud"), // 0xbf
  new Letters("ggul"), // 0xc0
  new Letters("ggulg"), // 0xc1
  new Letters("ggulm"), // 0xc2
  new Letters("ggulb"), // 0xc3
  new Letters("gguls"), // 0xc4
  new Letters("ggult"), // 0xc5
  new Letters("ggulp"), // 0xc6
  new Letters("ggulh"), // 0xc7
  new Letters("ggum"), // 0xc8
  new Letters("ggub"), // 0xc9
  new Letters("ggubs"), // 0xca
  new Letters("ggus"), // 0xcb
  new Letters("gguss"), // 0xcc
  new Letters("ggung"), // 0xcd
  new Letters("gguj"), // 0xce
  new Letters("gguc"), // 0xcf
  new Letters("gguk"), // 0xd0
  new Letters("ggut"), // 0xd1
  new Letters("ggup"), // 0xd2
  new Letters("gguh"), // 0xd3
  new Letters("ggweo"), // 0xd4
  new Letters("ggweog"), // 0xd5
  new Letters("ggweogg"), // 0xd6
  new Letters("ggweogs"), // 0xd7
  new Letters("ggweon"), // 0xd8
  new Letters("ggweonj"), // 0xd9
  new Letters("ggweonh"), // 0xda
  new Letters("ggweod"), // 0xdb
  new Letters("ggweol"), // 0xdc
  new Letters("ggweolg"), // 0xdd
  new Letters("ggweolm"), // 0xde
  new Letters("ggweolb"), // 0xdf
  new Letters("ggweols"), // 0xe0
  new Letters("ggweolt"), // 0xe1
  new Letters("ggweolp"), // 0xe2
  new Letters("ggweolh"), // 0xe3
  new Letters("ggweom"), // 0xe4
  new Letters("ggweob"), // 0xe5
  new Letters("ggweobs"), // 0xe6
  new Letters("ggweos"), // 0xe7
  new Letters("ggweoss"), // 0xe8
  new Letters("ggweong"), // 0xe9
  new Letters("ggweoj"), // 0xea
  new Letters("ggweoc"), // 0xeb
  new Letters("ggweok"), // 0xec
  new Letters("ggweot"), // 0xed
  new Letters("ggweop"), // 0xee
  new Letters("ggweoh"), // 0xef
  new Letters("ggwe"), // 0xf0
  new Letters("ggweg"), // 0xf1
  new Letters("ggwegg"), // 0xf2
  new Letters("ggwegs"), // 0xf3
  new Letters("ggwen"), // 0xf4
  new Letters("ggwenj"), // 0xf5
  new Letters("ggwenh"), // 0xf6
  new Letters("ggwed"), // 0xf7
  new Letters("ggwel"), // 0xf8
  new Letters("ggwelg"), // 0xf9
  new Letters("ggwelm"), // 0xfa
  new Letters("ggwelb"), // 0xfb
  new Letters("ggwels"), // 0xfc
  new Letters("ggwelt"), // 0xfd
  new Letters("ggwelp"), // 0xfe
  new Letters("ggwelh") // 0xff
  };
}