/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+B0xx (Hangul Syllables for Korean).
 */
final class Xb0 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("ggwem"), // 0x00
  new Letters("ggweb"), // 0x01
  new Letters("ggwebs"), // 0x02
  new Letters("ggwes"), // 0x03
  new Letters("ggwess"), // 0x04
  new Letters("ggweng"), // 0x05
  new Letters("ggwej"), // 0x06
  new Letters("ggwec"), // 0x07
  new Letters("ggwek"), // 0x08
  new Letters("ggwet"), // 0x09
  new Letters("ggwep"), // 0x0a
  new Letters("ggweh"), // 0x0b
  new Letters("ggwi"), // 0x0c
  new Letters("ggwig"), // 0x0d
  new Letters("ggwigg"), // 0x0e
  new Letters("ggwigs"), // 0x0f
  new Letters("ggwin"), // 0x10
  new Letters("ggwinj"), // 0x11
  new Letters("ggwinh"), // 0x12
  new Letters("ggwid"), // 0x13
  new Letters("ggwil"), // 0x14
  new Letters("ggwilg"), // 0x15
  new Letters("ggwilm"), // 0x16
  new Letters("ggwilb"), // 0x17
  new Letters("ggwils"), // 0x18
  new Letters("ggwilt"), // 0x19
  new Letters("ggwilp"), // 0x1a
  new Letters("ggwilh"), // 0x1b
  new Letters("ggwim"), // 0x1c
  new Letters("ggwib"), // 0x1d
  new Letters("ggwibs"), // 0x1e
  new Letters("ggwis"), // 0x1f
  new Letters("ggwiss"), // 0x20
  new Letters("ggwing"), // 0x21
  new Letters("ggwij"), // 0x22
  new Letters("ggwic"), // 0x23
  new Letters("ggwik"), // 0x24
  new Letters("ggwit"), // 0x25
  new Letters("ggwip"), // 0x26
  new Letters("ggwih"), // 0x27
  new Letters("ggyu"), // 0x28
  new Letters("ggyug"), // 0x29
  new Letters("ggyugg"), // 0x2a
  new Letters("ggyugs"), // 0x2b
  new Letters("ggyun"), // 0x2c
  new Letters("ggyunj"), // 0x2d
  new Letters("ggyunh"), // 0x2e
  new Letters("ggyud"), // 0x2f
  new Letters("ggyul"), // 0x30
  new Letters("ggyulg"), // 0x31
  new Letters("ggyulm"), // 0x32
  new Letters("ggyulb"), // 0x33
  new Letters("ggyuls"), // 0x34
  new Letters("ggyult"), // 0x35
  new Letters("ggyulp"), // 0x36
  new Letters("ggyulh"), // 0x37
  new Letters("ggyum"), // 0x38
  new Letters("ggyub"), // 0x39
  new Letters("ggyubs"), // 0x3a
  new Letters("ggyus"), // 0x3b
  new Letters("ggyuss"), // 0x3c
  new Letters("ggyung"), // 0x3d
  new Letters("ggyuj"), // 0x3e
  new Letters("ggyuc"), // 0x3f
  new Letters("ggyuk"), // 0x40
  new Letters("ggyut"), // 0x41
  new Letters("ggyup"), // 0x42
  new Letters("ggyuh"), // 0x43
  new Letters("ggeu"), // 0x44
  new Letters("ggeug"), // 0x45
  new Letters("ggeugg"), // 0x46
  new Letters("ggeugs"), // 0x47
  new Letters("ggeun"), // 0x48
  new Letters("ggeunj"), // 0x49
  new Letters("ggeunh"), // 0x4a
  new Letters("ggeud"), // 0x4b
  new Letters("ggeul"), // 0x4c
  new Letters("ggeulg"), // 0x4d
  new Letters("ggeulm"), // 0x4e
  new Letters("ggeulb"), // 0x4f
  new Letters("ggeuls"), // 0x50
  new Letters("ggeult"), // 0x51
  new Letters("ggeulp"), // 0x52
  new Letters("ggeulh"), // 0x53
  new Letters("ggeum"), // 0x54
  new Letters("ggeub"), // 0x55
  new Letters("ggeubs"), // 0x56
  new Letters("ggeus"), // 0x57
  new Letters("ggeuss"), // 0x58
  new Letters("ggeung"), // 0x59
  new Letters("ggeuj"), // 0x5a
  new Letters("ggeuc"), // 0x5b
  new Letters("ggeuk"), // 0x5c
  new Letters("ggeut"), // 0x5d
  new Letters("ggeup"), // 0x5e
  new Letters("ggeuh"), // 0x5f
  new Letters("ggyi"), // 0x60
  new Letters("ggyig"), // 0x61
  new Letters("ggyigg"), // 0x62
  new Letters("ggyigs"), // 0x63
  new Letters("ggyin"), // 0x64
  new Letters("ggyinj"), // 0x65
  new Letters("ggyinh"), // 0x66
  new Letters("ggyid"), // 0x67
  new Letters("ggyil"), // 0x68
  new Letters("ggyilg"), // 0x69
  new Letters("ggyilm"), // 0x6a
  new Letters("ggyilb"), // 0x6b
  new Letters("ggyils"), // 0x6c
  new Letters("ggyilt"), // 0x6d
  new Letters("ggyilp"), // 0x6e
  new Letters("ggyilh"), // 0x6f
  new Letters("ggyim"), // 0x70
  new Letters("ggyib"), // 0x71
  new Letters("ggyibs"), // 0x72
  new Letters("ggyis"), // 0x73
  new Letters("ggyiss"), // 0x74
  new Letters("ggying"), // 0x75
  new Letters("ggyij"), // 0x76
  new Letters("ggyic"), // 0x77
  new Letters("ggyik"), // 0x78
  new Letters("ggyit"), // 0x79
  new Letters("ggyip"), // 0x7a
  new Letters("ggyih"), // 0x7b
  new Letters("ggi"), // 0x7c
  new Letters("ggig"), // 0x7d
  new Letters("ggigg"), // 0x7e
  new Letters("ggigs"), // 0x7f
  new Letters("ggin"), // 0x80
  new Letters("gginj"), // 0x81
  new Letters("gginh"), // 0x82
  new Letters("ggid"), // 0x83
  new Letters("ggil"), // 0x84
  new Letters("ggilg"), // 0x85
  new Letters("ggilm"), // 0x86
  new Letters("ggilb"), // 0x87
  new Letters("ggils"), // 0x88
  new Letters("ggilt"), // 0x89
  new Letters("ggilp"), // 0x8a
  new Letters("ggilh"), // 0x8b
  new Letters("ggim"), // 0x8c
  new Letters("ggib"), // 0x8d
  new Letters("ggibs"), // 0x8e
  new Letters("ggis"), // 0x8f
  new Letters("ggiss"), // 0x90
  new Letters("gging"), // 0x91
  new Letters("ggij"), // 0x92
  new Letters("ggic"), // 0x93
  new Letters("ggik"), // 0x94
  new Letters("ggit"), // 0x95
  new Letters("ggip"), // 0x96
  new Letters("ggih"), // 0x97
  LO_NA, // 0x98
  new Letters("nag"), // 0x99
  new Letters("nagg"), // 0x9a
  new Letters("nags"), // 0x9b
  new Letters("nan"), // 0x9c
  new Letters("nanj"), // 0x9d
  new Letters("nanh"), // 0x9e
  new Letters("nad"), // 0x9f
  new Letters("nal"), // 0xa0
  new Letters("nalg"), // 0xa1
  new Letters("nalm"), // 0xa2
  new Letters("nalb"), // 0xa3
  new Letters("nals"), // 0xa4
  new Letters("nalt"), // 0xa5
  new Letters("nalp"), // 0xa6
  new Letters("nalh"), // 0xa7
  new Letters("nam"), // 0xa8
  new Letters("nab"), // 0xa9
  new Letters("nabs"), // 0xaa
  new Letters("nas"), // 0xab
  new Letters("nass"), // 0xac
  new Letters("nang"), // 0xad
  new Letters("naj"), // 0xae
  new Letters("nac"), // 0xaf
  new Letters("nak"), // 0xb0
  new Letters("nat"), // 0xb1
  new Letters("nap"), // 0xb2
  new Letters("nah"), // 0xb3
  new Letters("nae"), // 0xb4
  new Letters("naeg"), // 0xb5
  new Letters("naegg"), // 0xb6
  new Letters("naegs"), // 0xb7
  new Letters("naen"), // 0xb8
  new Letters("naenj"), // 0xb9
  new Letters("naenh"), // 0xba
  new Letters("naed"), // 0xbb
  new Letters("nael"), // 0xbc
  new Letters("naelg"), // 0xbd
  new Letters("naelm"), // 0xbe
  new Letters("naelb"), // 0xbf
  new Letters("naels"), // 0xc0
  new Letters("naelt"), // 0xc1
  new Letters("naelp"), // 0xc2
  new Letters("naelh"), // 0xc3
  new Letters("naem"), // 0xc4
  new Letters("naeb"), // 0xc5
  new Letters("naebs"), // 0xc6
  new Letters("naes"), // 0xc7
  new Letters("naess"), // 0xc8
  new Letters("naeng"), // 0xc9
  new Letters("naej"), // 0xca
  new Letters("naec"), // 0xcb
  new Letters("naek"), // 0xcc
  new Letters("naet"), // 0xcd
  new Letters("naep"), // 0xce
  new Letters("naeh"), // 0xcf
  new Letters("nya"), // 0xd0
  new Letters("nyag"), // 0xd1
  new Letters("nyagg"), // 0xd2
  new Letters("nyags"), // 0xd3
  new Letters("nyan"), // 0xd4
  new Letters("nyanj"), // 0xd5
  new Letters("nyanh"), // 0xd6
  new Letters("nyad"), // 0xd7
  new Letters("nyal"), // 0xd8
  new Letters("nyalg"), // 0xd9
  new Letters("nyalm"), // 0xda
  new Letters("nyalb"), // 0xdb
  new Letters("nyals"), // 0xdc
  new Letters("nyalt"), // 0xdd
  new Letters("nyalp"), // 0xde
  new Letters("nyalh"), // 0xdf
  new Letters("nyam"), // 0xe0
  new Letters("nyab"), // 0xe1
  new Letters("nyabs"), // 0xe2
  new Letters("nyas"), // 0xe3
  new Letters("nyass"), // 0xe4
  new Letters("nyang"), // 0xe5
  new Letters("nyaj"), // 0xe6
  new Letters("nyac"), // 0xe7
  new Letters("nyak"), // 0xe8
  new Letters("nyat"), // 0xe9
  new Letters("nyap"), // 0xea
  new Letters("nyah"), // 0xeb
  new Letters("nyae"), // 0xec
  new Letters("nyaeg"), // 0xed
  new Letters("nyaegg"), // 0xee
  new Letters("nyaegs"), // 0xef
  new Letters("nyaen"), // 0xf0
  new Letters("nyaenj"), // 0xf1
  new Letters("nyaenh"), // 0xf2
  new Letters("nyaed"), // 0xf3
  new Letters("nyael"), // 0xf4
  new Letters("nyaelg"), // 0xf5
  new Letters("nyaelm"), // 0xf6
  new Letters("nyaelb"), // 0xf7
  new Letters("nyaels"), // 0xf8
  new Letters("nyaelt"), // 0xf9
  new Letters("nyaelp"), // 0xfa
  new Letters("nyaelh"), // 0xfb
  new Letters("nyaem"), // 0xfc
  new Letters("nyaeb"), // 0xfd
  new Letters("nyaebs"), // 0xfe
  new Letters("nyaes") // 0xff
  };
}