/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+B1xx (Hangul Syllables for Korean).
 */
final class Xb1 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("nyaess"), // 0x00
  new Letters("nyaeng"), // 0x01
  new Letters("nyaej"), // 0x02
  new Letters("nyaec"), // 0x03
  new Letters("nyaek"), // 0x04
  new Letters("nyaet"), // 0x05
  new Letters("nyaep"), // 0x06
  new Letters("nyaeh"), // 0x07
  new Letters("neo"), // 0x08
  new Letters("neog"), // 0x09
  new Letters("neogg"), // 0x0a
  new Letters("neogs"), // 0x0b
  new Letters("neon"), // 0x0c
  new Letters("neonj"), // 0x0d
  new Letters("neonh"), // 0x0e
  new Letters("neod"), // 0x0f
  new Letters("neol"), // 0x10
  new Letters("neolg"), // 0x11
  new Letters("neolm"), // 0x12
  new Letters("neolb"), // 0x13
  new Letters("neols"), // 0x14
  new Letters("neolt"), // 0x15
  new Letters("neolp"), // 0x16
  new Letters("neolh"), // 0x17
  new Letters("neom"), // 0x18
  new Letters("neob"), // 0x19
  new Letters("neobs"), // 0x1a
  new Letters("neos"), // 0x1b
  new Letters("neoss"), // 0x1c
  new Letters("neong"), // 0x1d
  new Letters("neoj"), // 0x1e
  new Letters("neoc"), // 0x1f
  new Letters("neok"), // 0x20
  new Letters("neot"), // 0x21
  new Letters("neop"), // 0x22
  new Letters("neoh"), // 0x23
  LO_NE, // 0x24
  new Letters("neg"), // 0x25
  new Letters("negg"), // 0x26
  new Letters("negs"), // 0x27
  new Letters("nen"), // 0x28
  new Letters("nenj"), // 0x29
  new Letters("nenh"), // 0x2a
  new Letters("ned"), // 0x2b
  new Letters("nel"), // 0x2c
  new Letters("nelg"), // 0x2d
  new Letters("nelm"), // 0x2e
  new Letters("nelb"), // 0x2f
  new Letters("nels"), // 0x30
  new Letters("nelt"), // 0x31
  new Letters("nelp"), // 0x32
  new Letters("nelh"), // 0x33
  new Letters("nem"), // 0x34
  new Letters("neb"), // 0x35
  new Letters("nebs"), // 0x36
  new Letters("nes"), // 0x37
  new Letters("ness"), // 0x38
  new Letters("neng"), // 0x39
  new Letters("nej"), // 0x3a
  new Letters("nec"), // 0x3b
  new Letters("nek"), // 0x3c
  new Letters("net"), // 0x3d
  new Letters("nep"), // 0x3e
  new Letters("neh"), // 0x3f
  new Letters("nyeo"), // 0x40
  new Letters("nyeog"), // 0x41
  new Letters("nyeogg"), // 0x42
  new Letters("nyeogs"), // 0x43
  new Letters("nyeon"), // 0x44
  new Letters("nyeonj"), // 0x45
  new Letters("nyeonh"), // 0x46
  new Letters("nyeod"), // 0x47
  new Letters("nyeol"), // 0x48
  new Letters("nyeolg"), // 0x49
  new Letters("nyeolm"), // 0x4a
  new Letters("nyeolb"), // 0x4b
  new Letters("nyeols"), // 0x4c
  new Letters("nyeolt"), // 0x4d
  new Letters("nyeolp"), // 0x4e
  new Letters("nyeolh"), // 0x4f
  new Letters("nyeom"), // 0x50
  new Letters("nyeob"), // 0x51
  new Letters("nyeobs"), // 0x52
  new Letters("nyeos"), // 0x53
  new Letters("nyeoss"), // 0x54
  new Letters("nyeong"), // 0x55
  new Letters("nyeoj"), // 0x56
  new Letters("nyeoc"), // 0x57
  new Letters("nyeok"), // 0x58
  new Letters("nyeot"), // 0x59
  new Letters("nyeop"), // 0x5a
  new Letters("nyeoh"), // 0x5b
  new Letters("nye"), // 0x5c
  new Letters("nyeg"), // 0x5d
  new Letters("nyegg"), // 0x5e
  new Letters("nyegs"), // 0x5f
  new Letters("nyen"), // 0x60
  new Letters("nyenj"), // 0x61
  new Letters("nyenh"), // 0x62
  new Letters("nyed"), // 0x63
  new Letters("nyel"), // 0x64
  new Letters("nyelg"), // 0x65
  new Letters("nyelm"), // 0x66
  new Letters("nyelb"), // 0x67
  new Letters("nyels"), // 0x68
  new Letters("nyelt"), // 0x69
  new Letters("nyelp"), // 0x6a
  new Letters("nyelh"), // 0x6b
  new Letters("nyem"), // 0x6c
  new Letters("nyeb"), // 0x6d
  new Letters("nyebs"), // 0x6e
  new Letters("nyes"), // 0x6f
  new Letters("nyess"), // 0x70
  new Letters("nyeng"), // 0x71
  new Letters("nyej"), // 0x72
  new Letters("nyec"), // 0x73
  new Letters("nyek"), // 0x74
  new Letters("nyet"), // 0x75
  new Letters("nyep"), // 0x76
  new Letters("nyeh"), // 0x77
  LO_NO, // 0x78
  new Letters("nog"), // 0x79
  new Letters("nogg"), // 0x7a
  new Letters("nogs"), // 0x7b
  new Letters("non"), // 0x7c
  new Letters("nonj"), // 0x7d
  new Letters("nonh"), // 0x7e
  new Letters("nod"), // 0x7f
  new Letters("nol"), // 0x80
  new Letters("nolg"), // 0x81
  new Letters("nolm"), // 0x82
  new Letters("nolb"), // 0x83
  new Letters("nols"), // 0x84
  new Letters("nolt"), // 0x85
  new Letters("nolp"), // 0x86
  new Letters("nolh"), // 0x87
  new Letters("nom"), // 0x88
  new Letters("nob"), // 0x89
  new Letters("nobs"), // 0x8a
  new Letters("nos"), // 0x8b
  new Letters("noss"), // 0x8c
  new Letters("nong"), // 0x8d
  new Letters("noj"), // 0x8e
  new Letters("noc"), // 0x8f
  new Letters("nok"), // 0x90
  new Letters("not"), // 0x91
  new Letters("nop"), // 0x92
  new Letters("noh"), // 0x93
  new Letters("nwa"), // 0x94
  new Letters("nwag"), // 0x95
  new Letters("nwagg"), // 0x96
  new Letters("nwags"), // 0x97
  new Letters("nwan"), // 0x98
  new Letters("nwanj"), // 0x99
  new Letters("nwanh"), // 0x9a
  new Letters("nwad"), // 0x9b
  new Letters("nwal"), // 0x9c
  new Letters("nwalg"), // 0x9d
  new Letters("nwalm"), // 0x9e
  new Letters("nwalb"), // 0x9f
  new Letters("nwals"), // 0xa0
  new Letters("nwalt"), // 0xa1
  new Letters("nwalp"), // 0xa2
  new Letters("nwalh"), // 0xa3
  new Letters("nwam"), // 0xa4
  new Letters("nwab"), // 0xa5
  new Letters("nwabs"), // 0xa6
  new Letters("nwas"), // 0xa7
  new Letters("nwass"), // 0xa8
  new Letters("nwang"), // 0xa9
  new Letters("nwaj"), // 0xaa
  new Letters("nwac"), // 0xab
  new Letters("nwak"), // 0xac
  new Letters("nwat"), // 0xad
  new Letters("nwap"), // 0xae
  new Letters("nwah"), // 0xaf
  new Letters("nwae"), // 0xb0
  new Letters("nwaeg"), // 0xb1
  new Letters("nwaegg"), // 0xb2
  new Letters("nwaegs"), // 0xb3
  new Letters("nwaen"), // 0xb4
  new Letters("nwaenj"), // 0xb5
  new Letters("nwaenh"), // 0xb6
  new Letters("nwaed"), // 0xb7
  new Letters("nwael"), // 0xb8
  new Letters("nwaelg"), // 0xb9
  new Letters("nwaelm"), // 0xba
  new Letters("nwaelb"), // 0xbb
  new Letters("nwaels"), // 0xbc
  new Letters("nwaelt"), // 0xbd
  new Letters("nwaelp"), // 0xbe
  new Letters("nwaelh"), // 0xbf
  new Letters("nwaem"), // 0xc0
  new Letters("nwaeb"), // 0xc1
  new Letters("nwaebs"), // 0xc2
  new Letters("nwaes"), // 0xc3
  new Letters("nwaess"), // 0xc4
  new Letters("nwaeng"), // 0xc5
  new Letters("nwaej"), // 0xc6
  new Letters("nwaec"), // 0xc7
  new Letters("nwaek"), // 0xc8
  new Letters("nwaet"), // 0xc9
  new Letters("nwaep"), // 0xca
  new Letters("nwaeh"), // 0xcb
  new Letters("noe"), // 0xcc
  new Letters("noeg"), // 0xcd
  new Letters("noegg"), // 0xce
  new Letters("noegs"), // 0xcf
  new Letters("noen"), // 0xd0
  new Letters("noenj"), // 0xd1
  new Letters("noenh"), // 0xd2
  new Letters("noed"), // 0xd3
  new Letters("noel"), // 0xd4
  new Letters("noelg"), // 0xd5
  new Letters("noelm"), // 0xd6
  new Letters("noelb"), // 0xd7
  new Letters("noels"), // 0xd8
  new Letters("noelt"), // 0xd9
  new Letters("noelp"), // 0xda
  new Letters("noelh"), // 0xdb
  new Letters("noem"), // 0xdc
  new Letters("noeb"), // 0xdd
  new Letters("noebs"), // 0xde
  new Letters("noes"), // 0xdf
  new Letters("noess"), // 0xe0
  new Letters("noeng"), // 0xe1
  new Letters("noej"), // 0xe2
  new Letters("noec"), // 0xe3
  new Letters("noek"), // 0xe4
  new Letters("noet"), // 0xe5
  new Letters("noep"), // 0xe6
  new Letters("noeh"), // 0xe7
  new Letters("nyo"), // 0xe8
  new Letters("nyog"), // 0xe9
  new Letters("nyogg"), // 0xea
  new Letters("nyogs"), // 0xeb
  new Letters("nyon"), // 0xec
  new Letters("nyonj"), // 0xed
  new Letters("nyonh"), // 0xee
  new Letters("nyod"), // 0xef
  new Letters("nyol"), // 0xf0
  new Letters("nyolg"), // 0xf1
  new Letters("nyolm"), // 0xf2
  new Letters("nyolb"), // 0xf3
  new Letters("nyols"), // 0xf4
  new Letters("nyolt"), // 0xf5
  new Letters("nyolp"), // 0xf6
  new Letters("nyolh"), // 0xf7
  new Letters("nyom"), // 0xf8
  new Letters("nyob"), // 0xf9
  new Letters("nyobs"), // 0xfa
  new Letters("nyos"), // 0xfb
  new Letters("nyoss"), // 0xfc
  new Letters("nyong"), // 0xfd
  new Letters("nyoj"), // 0xfe
  new Letters("nyoc") // 0xff
  };
}