/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+B2xx (Hangul Syllables for Korean).
 */
final class Xb2 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("nyok"), // 0x00
  new Letters("nyot"), // 0x01
  new Letters("nyop"), // 0x02
  new Letters("nyoh"), // 0x03
  new Letters("nu"), // 0x04
  new Letters("nug"), // 0x05
  new Letters("nugg"), // 0x06
  new Letters("nugs"), // 0x07
  new Letters("nun"), // 0x08
  new Letters("nunj"), // 0x09
  new Letters("nunh"), // 0x0a
  new Letters("nud"), // 0x0b
  new Letters("nul"), // 0x0c
  new Letters("nulg"), // 0x0d
  new Letters("nulm"), // 0x0e
  new Letters("nulb"), // 0x0f
  new Letters("nuls"), // 0x10
  new Letters("nult"), // 0x11
  new Letters("nulp"), // 0x12
  new Letters("nulh"), // 0x13
  new Letters("num"), // 0x14
  new Letters("nub"), // 0x15
  new Letters("nubs"), // 0x16
  new Letters("nus"), // 0x17
  new Letters("nuss"), // 0x18
  new Letters("nung"), // 0x19
  new Letters("nuj"), // 0x1a
  new Letters("nuc"), // 0x1b
  new Letters("nuk"), // 0x1c
  new Letters("nut"), // 0x1d
  new Letters("nup"), // 0x1e
  new Letters("nuh"), // 0x1f
  new Letters("nweo"), // 0x20
  new Letters("nweog"), // 0x21
  new Letters("nweogg"), // 0x22
  new Letters("nweogs"), // 0x23
  new Letters("nweon"), // 0x24
  new Letters("nweonj"), // 0x25
  new Letters("nweonh"), // 0x26
  new Letters("nweod"), // 0x27
  new Letters("nweol"), // 0x28
  new Letters("nweolg"), // 0x29
  new Letters("nweolm"), // 0x2a
  new Letters("nweolb"), // 0x2b
  new Letters("nweols"), // 0x2c
  new Letters("nweolt"), // 0x2d
  new Letters("nweolp"), // 0x2e
  new Letters("nweolh"), // 0x2f
  new Letters("nweom"), // 0x30
  new Letters("nweob"), // 0x31
  new Letters("nweobs"), // 0x32
  new Letters("nweos"), // 0x33
  new Letters("nweoss"), // 0x34
  new Letters("nweong"), // 0x35
  new Letters("nweoj"), // 0x36
  new Letters("nweoc"), // 0x37
  new Letters("nweok"), // 0x38
  new Letters("nweot"), // 0x39
  new Letters("nweop"), // 0x3a
  new Letters("nweoh"), // 0x3b
  new Letters("nwe"), // 0x3c
  new Letters("nweg"), // 0x3d
  new Letters("nwegg"), // 0x3e
  new Letters("nwegs"), // 0x3f
  new Letters("nwen"), // 0x40
  new Letters("nwenj"), // 0x41
  new Letters("nwenh"), // 0x42
  new Letters("nwed"), // 0x43
  new Letters("nwel"), // 0x44
  new Letters("nwelg"), // 0x45
  new Letters("nwelm"), // 0x46
  new Letters("nwelb"), // 0x47
  new Letters("nwels"), // 0x48
  new Letters("nwelt"), // 0x49
  new Letters("nwelp"), // 0x4a
  new Letters("nwelh"), // 0x4b
  new Letters("nwem"), // 0x4c
  new Letters("nweb"), // 0x4d
  new Letters("nwebs"), // 0x4e
  new Letters("nwes"), // 0x4f
  new Letters("nwess"), // 0x50
  new Letters("nweng"), // 0x51
  new Letters("nwej"), // 0x52
  new Letters("nwec"), // 0x53
  new Letters("nwek"), // 0x54
  new Letters("nwet"), // 0x55
  new Letters("nwep"), // 0x56
  new Letters("nweh"), // 0x57
  new Letters("nwi"), // 0x58
  new Letters("nwig"), // 0x59
  new Letters("nwigg"), // 0x5a
  new Letters("nwigs"), // 0x5b
  new Letters("nwin"), // 0x5c
  new Letters("nwinj"), // 0x5d
  new Letters("nwinh"), // 0x5e
  new Letters("nwid"), // 0x5f
  new Letters("nwil"), // 0x60
  new Letters("nwilg"), // 0x61
  new Letters("nwilm"), // 0x62
  new Letters("nwilb"), // 0x63
  new Letters("nwils"), // 0x64
  new Letters("nwilt"), // 0x65
  new Letters("nwilp"), // 0x66
  new Letters("nwilh"), // 0x67
  new Letters("nwim"), // 0x68
  new Letters("nwib"), // 0x69
  new Letters("nwibs"), // 0x6a
  new Letters("nwis"), // 0x6b
  new Letters("nwiss"), // 0x6c
  new Letters("nwing"), // 0x6d
  new Letters("nwij"), // 0x6e
  new Letters("nwic"), // 0x6f
  new Letters("nwik"), // 0x70
  new Letters("nwit"), // 0x71
  new Letters("nwip"), // 0x72
  new Letters("nwih"), // 0x73
  new Letters("nyu"), // 0x74
  new Letters("nyug"), // 0x75
  new Letters("nyugg"), // 0x76
  new Letters("nyugs"), // 0x77
  new Letters("nyun"), // 0x78
  new Letters("nyunj"), // 0x79
  new Letters("nyunh"), // 0x7a
  new Letters("nyud"), // 0x7b
  new Letters("nyul"), // 0x7c
  new Letters("nyulg"), // 0x7d
  new Letters("nyulm"), // 0x7e
  new Letters("nyulb"), // 0x7f
  new Letters("nyuls"), // 0x80
  new Letters("nyult"), // 0x81
  new Letters("nyulp"), // 0x82
  new Letters("nyulh"), // 0x83
  new Letters("nyum"), // 0x84
  new Letters("nyub"), // 0x85
  new Letters("nyubs"), // 0x86
  new Letters("nyus"), // 0x87
  new Letters("nyuss"), // 0x88
  new Letters("nyung"), // 0x89
  new Letters("nyuj"), // 0x8a
  new Letters("nyuc"), // 0x8b
  new Letters("nyuk"), // 0x8c
  new Letters("nyut"), // 0x8d
  new Letters("nyup"), // 0x8e
  new Letters("nyuh"), // 0x8f
  new Letters("neu"), // 0x90
  new Letters("neug"), // 0x91
  new Letters("neugg"), // 0x92
  new Letters("neugs"), // 0x93
  new Letters("neun"), // 0x94
  new Letters("neunj"), // 0x95
  new Letters("neunh"), // 0x96
  new Letters("neud"), // 0x97
  new Letters("neul"), // 0x98
  new Letters("neulg"), // 0x99
  new Letters("neulm"), // 0x9a
  new Letters("neulb"), // 0x9b
  new Letters("neuls"), // 0x9c
  new Letters("neult"), // 0x9d
  new Letters("neulp"), // 0x9e
  new Letters("neulh"), // 0x9f
  new Letters("neum"), // 0xa0
  new Letters("neub"), // 0xa1
  new Letters("neubs"), // 0xa2
  new Letters("neus"), // 0xa3
  new Letters("neuss"), // 0xa4
  new Letters("neung"), // 0xa5
  new Letters("neuj"), // 0xa6
  new Letters("neuc"), // 0xa7
  new Letters("neuk"), // 0xa8
  new Letters("neut"), // 0xa9
  new Letters("neup"), // 0xaa
  new Letters("neuh"), // 0xab
  new Letters("nyi"), // 0xac
  new Letters("nyig"), // 0xad
  new Letters("nyigg"), // 0xae
  new Letters("nyigs"), // 0xaf
  new Letters("nyin"), // 0xb0
  new Letters("nyinj"), // 0xb1
  new Letters("nyinh"), // 0xb2
  new Letters("nyid"), // 0xb3
  new Letters("nyil"), // 0xb4
  new Letters("nyilg"), // 0xb5
  new Letters("nyilm"), // 0xb6
  new Letters("nyilb"), // 0xb7
  new Letters("nyils"), // 0xb8
  new Letters("nyilt"), // 0xb9
  new Letters("nyilp"), // 0xba
  new Letters("nyilh"), // 0xbb
  new Letters("nyim"), // 0xbc
  new Letters("nyib"), // 0xbd
  new Letters("nyibs"), // 0xbe
  new Letters("nyis"), // 0xbf
  new Letters("nyiss"), // 0xc0
  new Letters("nying"), // 0xc1
  new Letters("nyij"), // 0xc2
  new Letters("nyic"), // 0xc3
  new Letters("nyik"), // 0xc4
  new Letters("nyit"), // 0xc5
  new Letters("nyip"), // 0xc6
  new Letters("nyih"), // 0xc7
  LO_NI, // 0xc8
  new Letters("nig"), // 0xc9
  new Letters("nigg"), // 0xca
  new Letters("nigs"), // 0xcb
  new Letters("nin"), // 0xcc
  new Letters("ninj"), // 0xcd
  new Letters("ninh"), // 0xce
  new Letters("nid"), // 0xcf
  new Letters("nil"), // 0xd0
  new Letters("nilg"), // 0xd1
  new Letters("nilm"), // 0xd2
  new Letters("nilb"), // 0xd3
  new Letters("nils"), // 0xd4
  new Letters("nilt"), // 0xd5
  new Letters("nilp"), // 0xd6
  new Letters("nilh"), // 0xd7
  new Letters("nim"), // 0xd8
  new Letters("nib"), // 0xd9
  new Letters("nibs"), // 0xda
  new Letters("nis"), // 0xdb
  new Letters("niss"), // 0xdc
  new Letters("ning"), // 0xdd
  new Letters("nij"), // 0xde
  new Letters("nic"), // 0xdf
  new Letters("nik"), // 0xe0
  new Letters("nit"), // 0xe1
  new Letters("nip"), // 0xe2
  new Letters("nih"), // 0xe3
  LO_DA, // 0xe4
  new Letters("dag"), // 0xe5
  new Letters("dagg"), // 0xe6
  new Letters("dags"), // 0xe7
  new Letters("dan"), // 0xe8
  new Letters("danj"), // 0xe9
  new Letters("danh"), // 0xea
  new Letters("dad"), // 0xeb
  new Letters("dal"), // 0xec
  new Letters("dalg"), // 0xed
  new Letters("dalm"), // 0xee
  new Letters("dalb"), // 0xef
  new Letters("dals"), // 0xf0
  new Letters("dalt"), // 0xf1
  new Letters("dalp"), // 0xf2
  new Letters("dalh"), // 0xf3
  new Letters("dam"), // 0xf4
  new Letters("dab"), // 0xf5
  new Letters("dabs"), // 0xf6
  new Letters("das"), // 0xf7
  new Letters("dass"), // 0xf8
  new Letters("dang"), // 0xf9
  new Letters("daj"), // 0xfa
  new Letters("dac"), // 0xfb
  new Letters("dak"), // 0xfc
  new Letters("dat"), // 0xfd
  new Letters("dap"), // 0xfe
  new Letters("dah") // 0xff
  };
}