/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+B3xx (Hangul Syllables for Korean).
 */
final class Xb3 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("dae"), // 0x00
  new Letters("daeg"), // 0x01
  new Letters("daegg"), // 0x02
  new Letters("daegs"), // 0x03
  new Letters("daen"), // 0x04
  new Letters("daenj"), // 0x05
  new Letters("daenh"), // 0x06
  new Letters("daed"), // 0x07
  new Letters("dael"), // 0x08
  new Letters("daelg"), // 0x09
  new Letters("daelm"), // 0x0a
  new Letters("daelb"), // 0x0b
  new Letters("daels"), // 0x0c
  new Letters("daelt"), // 0x0d
  new Letters("daelp"), // 0x0e
  new Letters("daelh"), // 0x0f
  new Letters("daem"), // 0x10
  new Letters("daeb"), // 0x11
  new Letters("daebs"), // 0x12
  new Letters("daes"), // 0x13
  new Letters("daess"), // 0x14
  new Letters("daeng"), // 0x15
  new Letters("daej"), // 0x16
  new Letters("daec"), // 0x17
  new Letters("daek"), // 0x18
  new Letters("daet"), // 0x19
  new Letters("daep"), // 0x1a
  new Letters("daeh"), // 0x1b
  new Letters("dya"), // 0x1c
  new Letters("dyag"), // 0x1d
  new Letters("dyagg"), // 0x1e
  new Letters("dyags"), // 0x1f
  new Letters("dyan"), // 0x20
  new Letters("dyanj"), // 0x21
  new Letters("dyanh"), // 0x22
  new Letters("dyad"), // 0x23
  new Letters("dyal"), // 0x24
  new Letters("dyalg"), // 0x25
  new Letters("dyalm"), // 0x26
  new Letters("dyalb"), // 0x27
  new Letters("dyals"), // 0x28
  new Letters("dyalt"), // 0x29
  new Letters("dyalp"), // 0x2a
  new Letters("dyalh"), // 0x2b
  new Letters("dyam"), // 0x2c
  new Letters("dyab"), // 0x2d
  new Letters("dyabs"), // 0x2e
  new Letters("dyas"), // 0x2f
  new Letters("dyass"), // 0x30
  new Letters("dyang"), // 0x31
  new Letters("dyaj"), // 0x32
  new Letters("dyac"), // 0x33
  new Letters("dyak"), // 0x34
  new Letters("dyat"), // 0x35
  new Letters("dyap"), // 0x36
  new Letters("dyah"), // 0x37
  new Letters("dyae"), // 0x38
  new Letters("dyaeg"), // 0x39
  new Letters("dyaegg"), // 0x3a
  new Letters("dyaegs"), // 0x3b
  new Letters("dyaen"), // 0x3c
  new Letters("dyaenj"), // 0x3d
  new Letters("dyaenh"), // 0x3e
  new Letters("dyaed"), // 0x3f
  new Letters("dyael"), // 0x40
  new Letters("dyaelg"), // 0x41
  new Letters("dyaelm"), // 0x42
  new Letters("dyaelb"), // 0x43
  new Letters("dyaels"), // 0x44
  new Letters("dyaelt"), // 0x45
  new Letters("dyaelp"), // 0x46
  new Letters("dyaelh"), // 0x47
  new Letters("dyaem"), // 0x48
  new Letters("dyaeb"), // 0x49
  new Letters("dyaebs"), // 0x4a
  new Letters("dyaes"), // 0x4b
  new Letters("dyaess"), // 0x4c
  new Letters("dyaeng"), // 0x4d
  new Letters("dyaej"), // 0x4e
  new Letters("dyaec"), // 0x4f
  new Letters("dyaek"), // 0x50
  new Letters("dyaet"), // 0x51
  new Letters("dyaep"), // 0x52
  new Letters("dyaeh"), // 0x53
  new Letters("deo"), // 0x54
  new Letters("deog"), // 0x55
  new Letters("deogg"), // 0x56
  new Letters("deogs"), // 0x57
  new Letters("deon"), // 0x58
  new Letters("deonj"), // 0x59
  new Letters("deonh"), // 0x5a
  new Letters("deod"), // 0x5b
  new Letters("deol"), // 0x5c
  new Letters("deolg"), // 0x5d
  new Letters("deolm"), // 0x5e
  new Letters("deolb"), // 0x5f
  new Letters("deols"), // 0x60
  new Letters("deolt"), // 0x61
  new Letters("deolp"), // 0x62
  new Letters("deolh"), // 0x63
  new Letters("deom"), // 0x64
  new Letters("deob"), // 0x65
  new Letters("deobs"), // 0x66
  new Letters("deos"), // 0x67
  new Letters("deoss"), // 0x68
  new Letters("deong"), // 0x69
  new Letters("deoj"), // 0x6a
  new Letters("deoc"), // 0x6b
  new Letters("deok"), // 0x6c
  new Letters("deot"), // 0x6d
  new Letters("deop"), // 0x6e
  new Letters("deoh"), // 0x6f
  LO_DE, // 0x70
  new Letters("deg"), // 0x71
  new Letters("degg"), // 0x72
  new Letters("degs"), // 0x73
  new Letters("den"), // 0x74
  new Letters("denj"), // 0x75
  new Letters("denh"), // 0x76
  new Letters("ded"), // 0x77
  new Letters("del"), // 0x78
  new Letters("delg"), // 0x79
  new Letters("delm"), // 0x7a
  new Letters("delb"), // 0x7b
  new Letters("dels"), // 0x7c
  new Letters("delt"), // 0x7d
  new Letters("delp"), // 0x7e
  new Letters("delh"), // 0x7f
  new Letters("dem"), // 0x80
  new Letters("deb"), // 0x81
  new Letters("debs"), // 0x82
  new Letters("des"), // 0x83
  new Letters("dess"), // 0x84
  new Letters("deng"), // 0x85
  new Letters("dej"), // 0x86
  new Letters("dec"), // 0x87
  new Letters("dek"), // 0x88
  new Letters("det"), // 0x89
  new Letters("dep"), // 0x8a
  new Letters("deh"), // 0x8b
  new Letters("dyeo"), // 0x8c
  new Letters("dyeog"), // 0x8d
  new Letters("dyeogg"), // 0x8e
  new Letters("dyeogs"), // 0x8f
  new Letters("dyeon"), // 0x90
  new Letters("dyeonj"), // 0x91
  new Letters("dyeonh"), // 0x92
  new Letters("dyeod"), // 0x93
  new Letters("dyeol"), // 0x94
  new Letters("dyeolg"), // 0x95
  new Letters("dyeolm"), // 0x96
  new Letters("dyeolb"), // 0x97
  new Letters("dyeols"), // 0x98
  new Letters("dyeolt"), // 0x99
  new Letters("dyeolp"), // 0x9a
  new Letters("dyeolh"), // 0x9b
  new Letters("dyeom"), // 0x9c
  new Letters("dyeob"), // 0x9d
  new Letters("dyeobs"), // 0x9e
  new Letters("dyeos"), // 0x9f
  new Letters("dyeoss"), // 0xa0
  new Letters("dyeong"), // 0xa1
  new Letters("dyeoj"), // 0xa2
  new Letters("dyeoc"), // 0xa3
  new Letters("dyeok"), // 0xa4
  new Letters("dyeot"), // 0xa5
  new Letters("dyeop"), // 0xa6
  new Letters("dyeoh"), // 0xa7
  new Letters("dye"), // 0xa8
  new Letters("dyeg"), // 0xa9
  new Letters("dyegg"), // 0xaa
  new Letters("dyegs"), // 0xab
  new Letters("dyen"), // 0xac
  new Letters("dyenj"), // 0xad
  new Letters("dyenh"), // 0xae
  new Letters("dyed"), // 0xaf
  new Letters("dyel"), // 0xb0
  new Letters("dyelg"), // 0xb1
  new Letters("dyelm"), // 0xb2
  new Letters("dyelb"), // 0xb3
  new Letters("dyels"), // 0xb4
  new Letters("dyelt"), // 0xb5
  new Letters("dyelp"), // 0xb6
  new Letters("dyelh"), // 0xb7
  new Letters("dyem"), // 0xb8
  new Letters("dyeb"), // 0xb9
  new Letters("dyebs"), // 0xba
  new Letters("dyes"), // 0xbb
  new Letters("dyess"), // 0xbc
  new Letters("dyeng"), // 0xbd
  new Letters("dyej"), // 0xbe
  new Letters("dyec"), // 0xbf
  new Letters("dyek"), // 0xc0
  new Letters("dyet"), // 0xc1
  new Letters("dyep"), // 0xc2
  new Letters("dyeh"), // 0xc3
  LO_DO, // 0xc4
  new Letters("dog"), // 0xc5
  new Letters("dogg"), // 0xc6
  new Letters("dogs"), // 0xc7
  new Letters("don"), // 0xc8
  new Letters("donj"), // 0xc9
  new Letters("donh"), // 0xca
  new Letters("dod"), // 0xcb
  new Letters("dol"), // 0xcc
  new Letters("dolg"), // 0xcd
  new Letters("dolm"), // 0xce
  new Letters("dolb"), // 0xcf
  new Letters("dols"), // 0xd0
  new Letters("dolt"), // 0xd1
  new Letters("dolp"), // 0xd2
  new Letters("dolh"), // 0xd3
  new Letters("dom"), // 0xd4
  new Letters("dob"), // 0xd5
  new Letters("dobs"), // 0xd6
  new Letters("dos"), // 0xd7
  new Letters("doss"), // 0xd8
  new Letters("dong"), // 0xd9
  new Letters("doj"), // 0xda
  new Letters("doc"), // 0xdb
  new Letters("dok"), // 0xdc
  new Letters("dot"), // 0xdd
  new Letters("dop"), // 0xde
  new Letters("doh"), // 0xdf
  new Letters("dwa"), // 0xe0
  new Letters("dwag"), // 0xe1
  new Letters("dwagg"), // 0xe2
  new Letters("dwags"), // 0xe3
  new Letters("dwan"), // 0xe4
  new Letters("dwanj"), // 0xe5
  new Letters("dwanh"), // 0xe6
  new Letters("dwad"), // 0xe7
  new Letters("dwal"), // 0xe8
  new Letters("dwalg"), // 0xe9
  new Letters("dwalm"), // 0xea
  new Letters("dwalb"), // 0xeb
  new Letters("dwals"), // 0xec
  new Letters("dwalt"), // 0xed
  new Letters("dwalp"), // 0xee
  new Letters("dwalh"), // 0xef
  new Letters("dwam"), // 0xf0
  new Letters("dwab"), // 0xf1
  new Letters("dwabs"), // 0xf2
  new Letters("dwas"), // 0xf3
  new Letters("dwass"), // 0xf4
  new Letters("dwang"), // 0xf5
  new Letters("dwaj"), // 0xf6
  new Letters("dwac"), // 0xf7
  new Letters("dwak"), // 0xf8
  new Letters("dwat"), // 0xf9
  new Letters("dwap"), // 0xfa
  new Letters("dwah"), // 0xfb
  new Letters("dwae"), // 0xfc
  new Letters("dwaeg"), // 0xfd
  new Letters("dwaegg"), // 0xfe
  new Letters("dwaegs") // 0xff
  };
}