/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+B6xx (Hangul Syllables for Korean).
 */
final class Xb6 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("ddyels"), // 0x00
  new Letters("ddyelt"), // 0x01
  new Letters("ddyelp"), // 0x02
  new Letters("ddyelh"), // 0x03
  new Letters("ddyem"), // 0x04
  new Letters("ddyeb"), // 0x05
  new Letters("ddyebs"), // 0x06
  new Letters("ddyes"), // 0x07
  new Letters("ddyess"), // 0x08
  new Letters("ddyeng"), // 0x09
  new Letters("ddyej"), // 0x0a
  new Letters("ddyec"), // 0x0b
  new Letters("ddyek"), // 0x0c
  new Letters("ddyet"), // 0x0d
  new Letters("ddyep"), // 0x0e
  new Letters("ddyeh"), // 0x0f
  new Letters("ddo"), // 0x10
  new Letters("ddog"), // 0x11
  new Letters("ddogg"), // 0x12
  new Letters("ddogs"), // 0x13
  new Letters("ddon"), // 0x14
  new Letters("ddonj"), // 0x15
  new Letters("ddonh"), // 0x16
  new Letters("ddod"), // 0x17
  new Letters("ddol"), // 0x18
  new Letters("ddolg"), // 0x19
  new Letters("ddolm"), // 0x1a
  new Letters("ddolb"), // 0x1b
  new Letters("ddols"), // 0x1c
  new Letters("ddolt"), // 0x1d
  new Letters("ddolp"), // 0x1e
  new Letters("ddolh"), // 0x1f
  new Letters("ddom"), // 0x20
  new Letters("ddob"), // 0x21
  new Letters("ddobs"), // 0x22
  new Letters("ddos"), // 0x23
  new Letters("ddoss"), // 0x24
  new Letters("ddong"), // 0x25
  new Letters("ddoj"), // 0x26
  new Letters("ddoc"), // 0x27
  new Letters("ddok"), // 0x28
  new Letters("ddot"), // 0x29
  new Letters("ddop"), // 0x2a
  new Letters("ddoh"), // 0x2b
  new Letters("ddwa"), // 0x2c
  new Letters("ddwag"), // 0x2d
  new Letters("ddwagg"), // 0x2e
  new Letters("ddwags"), // 0x2f
  new Letters("ddwan"), // 0x30
  new Letters("ddwanj"), // 0x31
  new Letters("ddwanh"), // 0x32
  new Letters("ddwad"), // 0x33
  new Letters("ddwal"), // 0x34
  new Letters("ddwalg"), // 0x35
  new Letters("ddwalm"), // 0x36
  new Letters("ddwalb"), // 0x37
  new Letters("ddwals"), // 0x38
  new Letters("ddwalt"), // 0x39
  new Letters("ddwalp"), // 0x3a
  new Letters("ddwalh"), // 0x3b
  new Letters("ddwam"), // 0x3c
  new Letters("ddwab"), // 0x3d
  new Letters("ddwabs"), // 0x3e
  new Letters("ddwas"), // 0x3f
  new Letters("ddwass"), // 0x40
  new Letters("ddwang"), // 0x41
  new Letters("ddwaj"), // 0x42
  new Letters("ddwac"), // 0x43
  new Letters("ddwak"), // 0x44
  new Letters("ddwat"), // 0x45
  new Letters("ddwap"), // 0x46
  new Letters("ddwah"), // 0x47
  new Letters("ddwae"), // 0x48
  new Letters("ddwaeg"), // 0x49
  new Letters("ddwaegg"), // 0x4a
  new Letters("ddwaegs"), // 0x4b
  new Letters("ddwaen"), // 0x4c
  new Letters("ddwaenj"), // 0x4d
  new Letters("ddwaenh"), // 0x4e
  new Letters("ddwaed"), // 0x4f
  new Letters("ddwael"), // 0x50
  new Letters("ddwaelg"), // 0x51
  new Letters("ddwaelm"), // 0x52
  new Letters("ddwaelb"), // 0x53
  new Letters("ddwaels"), // 0x54
  new Letters("ddwaelt"), // 0x55
  new Letters("ddwaelp"), // 0x56
  new Letters("ddwaelh"), // 0x57
  new Letters("ddwaem"), // 0x58
  new Letters("ddwaeb"), // 0x59
  new Letters("ddwaebs"), // 0x5a
  new Letters("ddwaes"), // 0x5b
  new Letters("ddwaess"), // 0x5c
  new Letters("ddwaeng"), // 0x5d
  new Letters("ddwaej"), // 0x5e
  new Letters("ddwaec"), // 0x5f
  new Letters("ddwaek"), // 0x60
  new Letters("ddwaet"), // 0x61
  new Letters("ddwaep"), // 0x62
  new Letters("ddwaeh"), // 0x63
  new Letters("ddoe"), // 0x64
  new Letters("ddoeg"), // 0x65
  new Letters("ddoegg"), // 0x66
  new Letters("ddoegs"), // 0x67
  new Letters("ddoen"), // 0x68
  new Letters("ddoenj"), // 0x69
  new Letters("ddoenh"), // 0x6a
  new Letters("ddoed"), // 0x6b
  new Letters("ddoel"), // 0x6c
  new Letters("ddoelg"), // 0x6d
  new Letters("ddoelm"), // 0x6e
  new Letters("ddoelb"), // 0x6f
  new Letters("ddoels"), // 0x70
  new Letters("ddoelt"), // 0x71
  new Letters("ddoelp"), // 0x72
  new Letters("ddoelh"), // 0x73
  new Letters("ddoem"), // 0x74
  new Letters("ddoeb"), // 0x75
  new Letters("ddoebs"), // 0x76
  new Letters("ddoes"), // 0x77
  new Letters("ddoess"), // 0x78
  new Letters("ddoeng"), // 0x79
  new Letters("ddoej"), // 0x7a
  new Letters("ddoec"), // 0x7b
  new Letters("ddoek"), // 0x7c
  new Letters("ddoet"), // 0x7d
  new Letters("ddoep"), // 0x7e
  new Letters("ddoeh"), // 0x7f
  new Letters("ddyo"), // 0x80
  new Letters("ddyog"), // 0x81
  new Letters("ddyogg"), // 0x82
  new Letters("ddyogs"), // 0x83
  new Letters("ddyon"), // 0x84
  new Letters("ddyonj"), // 0x85
  new Letters("ddyonh"), // 0x86
  new Letters("ddyod"), // 0x87
  new Letters("ddyol"), // 0x88
  new Letters("ddyolg"), // 0x89
  new Letters("ddyolm"), // 0x8a
  new Letters("ddyolb"), // 0x8b
  new Letters("ddyols"), // 0x8c
  new Letters("ddyolt"), // 0x8d
  new Letters("ddyolp"), // 0x8e
  new Letters("ddyolh"), // 0x8f
  new Letters("ddyom"), // 0x90
  new Letters("ddyob"), // 0x91
  new Letters("ddyobs"), // 0x92
  new Letters("ddyos"), // 0x93
  new Letters("ddyoss"), // 0x94
  new Letters("ddyong"), // 0x95
  new Letters("ddyoj"), // 0x96
  new Letters("ddyoc"), // 0x97
  new Letters("ddyok"), // 0x98
  new Letters("ddyot"), // 0x99
  new Letters("ddyop"), // 0x9a
  new Letters("ddyoh"), // 0x9b
  new Letters("ddu"), // 0x9c
  new Letters("ddug"), // 0x9d
  new Letters("ddugg"), // 0x9e
  new Letters("ddugs"), // 0x9f
  new Letters("ddun"), // 0xa0
  new Letters("ddunj"), // 0xa1
  new Letters("ddunh"), // 0xa2
  new Letters("ddud"), // 0xa3
  new Letters("ddul"), // 0xa4
  new Letters("ddulg"), // 0xa5
  new Letters("ddulm"), // 0xa6
  new Letters("ddulb"), // 0xa7
  new Letters("dduls"), // 0xa8
  new Letters("ddult"), // 0xa9
  new Letters("ddulp"), // 0xaa
  new Letters("ddulh"), // 0xab
  new Letters("ddum"), // 0xac
  new Letters("ddub"), // 0xad
  new Letters("ddubs"), // 0xae
  new Letters("ddus"), // 0xaf
  new Letters("dduss"), // 0xb0
  new Letters("ddung"), // 0xb1
  new Letters("dduj"), // 0xb2
  new Letters("dduc"), // 0xb3
  new Letters("dduk"), // 0xb4
  new Letters("ddut"), // 0xb5
  new Letters("ddup"), // 0xb6
  new Letters("dduh"), // 0xb7
  new Letters("ddweo"), // 0xb8
  new Letters("ddweog"), // 0xb9
  new Letters("ddweogg"), // 0xba
  new Letters("ddweogs"), // 0xbb
  new Letters("ddweon"), // 0xbc
  new Letters("ddweonj"), // 0xbd
  new Letters("ddweonh"), // 0xbe
  new Letters("ddweod"), // 0xbf
  new Letters("ddweol"), // 0xc0
  new Letters("ddweolg"), // 0xc1
  new Letters("ddweolm"), // 0xc2
  new Letters("ddweolb"), // 0xc3
  new Letters("ddweols"), // 0xc4
  new Letters("ddweolt"), // 0xc5
  new Letters("ddweolp"), // 0xc6
  new Letters("ddweolh"), // 0xc7
  new Letters("ddweom"), // 0xc8
  new Letters("ddweob"), // 0xc9
  new Letters("ddweobs"), // 0xca
  new Letters("ddweos"), // 0xcb
  new Letters("ddweoss"), // 0xcc
  new Letters("ddweong"), // 0xcd
  new Letters("ddweoj"), // 0xce
  new Letters("ddweoc"), // 0xcf
  new Letters("ddweok"), // 0xd0
  new Letters("ddweot"), // 0xd1
  new Letters("ddweop"), // 0xd2
  new Letters("ddweoh"), // 0xd3
  new Letters("ddwe"), // 0xd4
  new Letters("ddweg"), // 0xd5
  new Letters("ddwegg"), // 0xd6
  new Letters("ddwegs"), // 0xd7
  new Letters("ddwen"), // 0xd8
  new Letters("ddwenj"), // 0xd9
  new Letters("ddwenh"), // 0xda
  new Letters("ddwed"), // 0xdb
  new Letters("ddwel"), // 0xdc
  new Letters("ddwelg"), // 0xdd
  new Letters("ddwelm"), // 0xde
  new Letters("ddwelb"), // 0xdf
  new Letters("ddwels"), // 0xe0
  new Letters("ddwelt"), // 0xe1
  new Letters("ddwelp"), // 0xe2
  new Letters("ddwelh"), // 0xe3
  new Letters("ddwem"), // 0xe4
  new Letters("ddweb"), // 0xe5
  new Letters("ddwebs"), // 0xe6
  new Letters("ddwes"), // 0xe7
  new Letters("ddwess"), // 0xe8
  new Letters("ddweng"), // 0xe9
  new Letters("ddwej"), // 0xea
  new Letters("ddwec"), // 0xeb
  new Letters("ddwek"), // 0xec
  new Letters("ddwet"), // 0xed
  new Letters("ddwep"), // 0xee
  new Letters("ddweh"), // 0xef
  new Letters("ddwi"), // 0xf0
  new Letters("ddwig"), // 0xf1
  new Letters("ddwigg"), // 0xf2
  new Letters("ddwigs"), // 0xf3
  new Letters("ddwin"), // 0xf4
  new Letters("ddwinj"), // 0xf5
  new Letters("ddwinh"), // 0xf6
  new Letters("ddwid"), // 0xf7
  new Letters("ddwil"), // 0xf8
  new Letters("ddwilg"), // 0xf9
  new Letters("ddwilm"), // 0xfa
  new Letters("ddwilb"), // 0xfb
  new Letters("ddwils"), // 0xfc
  new Letters("ddwilt"), // 0xfd
  new Letters("ddwilp"), // 0xfe
  new Letters("ddwilh") // 0xff
  };
}