/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+B7xx (Hangul Syllables for Korean).
 */
final class Xb7 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("ddwim"), // 0x00
  new Letters("ddwib"), // 0x01
  new Letters("ddwibs"), // 0x02
  new Letters("ddwis"), // 0x03
  new Letters("ddwiss"), // 0x04
  new Letters("ddwing"), // 0x05
  new Letters("ddwij"), // 0x06
  new Letters("ddwic"), // 0x07
  new Letters("ddwik"), // 0x08
  new Letters("ddwit"), // 0x09
  new Letters("ddwip"), // 0x0a
  new Letters("ddwih"), // 0x0b
  new Letters("ddyu"), // 0x0c
  new Letters("ddyug"), // 0x0d
  new Letters("ddyugg"), // 0x0e
  new Letters("ddyugs"), // 0x0f
  new Letters("ddyun"), // 0x10
  new Letters("ddyunj"), // 0x11
  new Letters("ddyunh"), // 0x12
  new Letters("ddyud"), // 0x13
  new Letters("ddyul"), // 0x14
  new Letters("ddyulg"), // 0x15
  new Letters("ddyulm"), // 0x16
  new Letters("ddyulb"), // 0x17
  new Letters("ddyuls"), // 0x18
  new Letters("ddyult"), // 0x19
  new Letters("ddyulp"), // 0x1a
  new Letters("ddyulh"), // 0x1b
  new Letters("ddyum"), // 0x1c
  new Letters("ddyub"), // 0x1d
  new Letters("ddyubs"), // 0x1e
  new Letters("ddyus"), // 0x1f
  new Letters("ddyuss"), // 0x20
  new Letters("ddyung"), // 0x21
  new Letters("ddyuj"), // 0x22
  new Letters("ddyuc"), // 0x23
  new Letters("ddyuk"), // 0x24
  new Letters("ddyut"), // 0x25
  new Letters("ddyup"), // 0x26
  new Letters("ddyuh"), // 0x27
  new Letters("ddeu"), // 0x28
  new Letters("ddeug"), // 0x29
  new Letters("ddeugg"), // 0x2a
  new Letters("ddeugs"), // 0x2b
  new Letters("ddeun"), // 0x2c
  new Letters("ddeunj"), // 0x2d
  new Letters("ddeunh"), // 0x2e
  new Letters("ddeud"), // 0x2f
  new Letters("ddeul"), // 0x30
  new Letters("ddeulg"), // 0x31
  new Letters("ddeulm"), // 0x32
  new Letters("ddeulb"), // 0x33
  new Letters("ddeuls"), // 0x34
  new Letters("ddeult"), // 0x35
  new Letters("ddeulp"), // 0x36
  new Letters("ddeulh"), // 0x37
  new Letters("ddeum"), // 0x38
  new Letters("ddeub"), // 0x39
  new Letters("ddeubs"), // 0x3a
  new Letters("ddeus"), // 0x3b
  new Letters("ddeuss"), // 0x3c
  new Letters("ddeung"), // 0x3d
  new Letters("ddeuj"), // 0x3e
  new Letters("ddeuc"), // 0x3f
  new Letters("ddeuk"), // 0x40
  new Letters("ddeut"), // 0x41
  new Letters("ddeup"), // 0x42
  new Letters("ddeuh"), // 0x43
  new Letters("ddyi"), // 0x44
  new Letters("ddyig"), // 0x45
  new Letters("ddyigg"), // 0x46
  new Letters("ddyigs"), // 0x47
  new Letters("ddyin"), // 0x48
  new Letters("ddyinj"), // 0x49
  new Letters("ddyinh"), // 0x4a
  new Letters("ddyid"), // 0x4b
  new Letters("ddyil"), // 0x4c
  new Letters("ddyilg"), // 0x4d
  new Letters("ddyilm"), // 0x4e
  new Letters("ddyilb"), // 0x4f
  new Letters("ddyils"), // 0x50
  new Letters("ddyilt"), // 0x51
  new Letters("ddyilp"), // 0x52
  new Letters("ddyilh"), // 0x53
  new Letters("ddyim"), // 0x54
  new Letters("ddyib"), // 0x55
  new Letters("ddyibs"), // 0x56
  new Letters("ddyis"), // 0x57
  new Letters("ddyiss"), // 0x58
  new Letters("ddying"), // 0x59
  new Letters("ddyij"), // 0x5a
  new Letters("ddyic"), // 0x5b
  new Letters("ddyik"), // 0x5c
  new Letters("ddyit"), // 0x5d
  new Letters("ddyip"), // 0x5e
  new Letters("ddyih"), // 0x5f
  new Letters("ddi"), // 0x60
  new Letters("ddig"), // 0x61
  new Letters("ddigg"), // 0x62
  new Letters("ddigs"), // 0x63
  new Letters("ddin"), // 0x64
  new Letters("ddinj"), // 0x65
  new Letters("ddinh"), // 0x66
  new Letters("ddid"), // 0x67
  new Letters("ddil"), // 0x68
  new Letters("ddilg"), // 0x69
  new Letters("ddilm"), // 0x6a
  new Letters("ddilb"), // 0x6b
  new Letters("ddils"), // 0x6c
  new Letters("ddilt"), // 0x6d
  new Letters("ddilp"), // 0x6e
  new Letters("ddilh"), // 0x6f
  new Letters("ddim"), // 0x70
  new Letters("ddib"), // 0x71
  new Letters("ddibs"), // 0x72
  new Letters("ddis"), // 0x73
  new Letters("ddiss"), // 0x74
  new Letters("dding"), // 0x75
  new Letters("ddij"), // 0x76
  new Letters("ddic"), // 0x77
  new Letters("ddik"), // 0x78
  new Letters("ddit"), // 0x79
  new Letters("ddip"), // 0x7a
  new Letters("ddih"), // 0x7b
  LO_RA, // 0x7c
  new Letters("rag"), // 0x7d
  new Letters("ragg"), // 0x7e
  new Letters("rags"), // 0x7f
  new Letters("ran"), // 0x80
  new Letters("ranj"), // 0x81
  new Letters("ranh"), // 0x82
  new Letters("rad"), // 0x83
  new Letters("ral"), // 0x84
  new Letters("ralg"), // 0x85
  new Letters("ralm"), // 0x86
  new Letters("ralb"), // 0x87
  new Letters("rals"), // 0x88
  new Letters("ralt"), // 0x89
  new Letters("ralp"), // 0x8a
  new Letters("ralh"), // 0x8b
  new Letters("ram"), // 0x8c
  new Letters("rab"), // 0x8d
  new Letters("rabs"), // 0x8e
  new Letters("ras"), // 0x8f
  new Letters("rass"), // 0x90
  new Letters("rang"), // 0x91
  new Letters("raj"), // 0x92
  new Letters("rac"), // 0x93
  new Letters("rak"), // 0x94
  new Letters("rat"), // 0x95
  new Letters("rap"), // 0x96
  new Letters("rah"), // 0x97
  new Letters("rae"), // 0x98
  new Letters("raeg"), // 0x99
  new Letters("raegg"), // 0x9a
  new Letters("raegs"), // 0x9b
  new Letters("raen"), // 0x9c
  new Letters("raenj"), // 0x9d
  new Letters("raenh"), // 0x9e
  new Letters("raed"), // 0x9f
  new Letters("rael"), // 0xa0
  new Letters("raelg"), // 0xa1
  new Letters("raelm"), // 0xa2
  new Letters("raelb"), // 0xa3
  new Letters("raels"), // 0xa4
  new Letters("raelt"), // 0xa5
  new Letters("raelp"), // 0xa6
  new Letters("raelh"), // 0xa7
  new Letters("raem"), // 0xa8
  new Letters("raeb"), // 0xa9
  new Letters("raebs"), // 0xaa
  new Letters("raes"), // 0xab
  new Letters("raess"), // 0xac
  new Letters("raeng"), // 0xad
  new Letters("raej"), // 0xae
  new Letters("raec"), // 0xaf
  new Letters("raek"), // 0xb0
  new Letters("raet"), // 0xb1
  new Letters("raep"), // 0xb2
  new Letters("raeh"), // 0xb3
  new Letters("rya"), // 0xb4
  new Letters("ryag"), // 0xb5
  new Letters("ryagg"), // 0xb6
  new Letters("ryags"), // 0xb7
  new Letters("ryan"), // 0xb8
  new Letters("ryanj"), // 0xb9
  new Letters("ryanh"), // 0xba
  new Letters("ryad"), // 0xbb
  new Letters("ryal"), // 0xbc
  new Letters("ryalg"), // 0xbd
  new Letters("ryalm"), // 0xbe
  new Letters("ryalb"), // 0xbf
  new Letters("ryals"), // 0xc0
  new Letters("ryalt"), // 0xc1
  new Letters("ryalp"), // 0xc2
  new Letters("ryalh"), // 0xc3
  new Letters("ryam"), // 0xc4
  new Letters("ryab"), // 0xc5
  new Letters("ryabs"), // 0xc6
  new Letters("ryas"), // 0xc7
  new Letters("ryass"), // 0xc8
  new Letters("ryang"), // 0xc9
  new Letters("ryaj"), // 0xca
  new Letters("ryac"), // 0xcb
  new Letters("ryak"), // 0xcc
  new Letters("ryat"), // 0xcd
  new Letters("ryap"), // 0xce
  new Letters("ryah"), // 0xcf
  new Letters("ryae"), // 0xd0
  new Letters("ryaeg"), // 0xd1
  new Letters("ryaegg"), // 0xd2
  new Letters("ryaegs"), // 0xd3
  new Letters("ryaen"), // 0xd4
  new Letters("ryaenj"), // 0xd5
  new Letters("ryaenh"), // 0xd6
  new Letters("ryaed"), // 0xd7
  new Letters("ryael"), // 0xd8
  new Letters("ryaelg"), // 0xd9
  new Letters("ryaelm"), // 0xda
  new Letters("ryaelb"), // 0xdb
  new Letters("ryaels"), // 0xdc
  new Letters("ryaelt"), // 0xdd
  new Letters("ryaelp"), // 0xde
  new Letters("ryaelh"), // 0xdf
  new Letters("ryaem"), // 0xe0
  new Letters("ryaeb"), // 0xe1
  new Letters("ryaebs"), // 0xe2
  new Letters("ryaes"), // 0xe3
  new Letters("ryaess"), // 0xe4
  new Letters("ryaeng"), // 0xe5
  new Letters("ryaej"), // 0xe6
  new Letters("ryaec"), // 0xe7
  new Letters("ryaek"), // 0xe8
  new Letters("ryaet"), // 0xe9
  new Letters("ryaep"), // 0xea
  new Letters("ryaeh"), // 0xeb
  new Letters("reo"), // 0xec
  new Letters("reog"), // 0xed
  new Letters("reogg"), // 0xee
  new Letters("reogs"), // 0xef
  new Letters("reon"), // 0xf0
  new Letters("reonj"), // 0xf1
  new Letters("reonh"), // 0xf2
  new Letters("reod"), // 0xf3
  new Letters("reol"), // 0xf4
  new Letters("reolg"), // 0xf5
  new Letters("reolm"), // 0xf6
  new Letters("reolb"), // 0xf7
  new Letters("reols"), // 0xf8
  new Letters("reolt"), // 0xf9
  new Letters("reolp"), // 0xfa
  new Letters("reolh"), // 0xfb
  new Letters("reom"), // 0xfc
  new Letters("reob"), // 0xfd
  new Letters("reobs"), // 0xfe
  new Letters("reos") // 0xff
  };
}