/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+B9xx (Hangul Syllables for Korean).
 */
final class Xb9 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("ruk"), // 0x00
  new Letters("rut"), // 0x01
  new Letters("rup"), // 0x02
  new Letters("ruh"), // 0x03
  new Letters("rweo"), // 0x04
  new Letters("rweog"), // 0x05
  new Letters("rweogg"), // 0x06
  new Letters("rweogs"), // 0x07
  new Letters("rweon"), // 0x08
  new Letters("rweonj"), // 0x09
  new Letters("rweonh"), // 0x0a
  new Letters("rweod"), // 0x0b
  new Letters("rweol"), // 0x0c
  new Letters("rweolg"), // 0x0d
  new Letters("rweolm"), // 0x0e
  new Letters("rweolb"), // 0x0f
  new Letters("rweols"), // 0x10
  new Letters("rweolt"), // 0x11
  new Letters("rweolp"), // 0x12
  new Letters("rweolh"), // 0x13
  new Letters("rweom"), // 0x14
  new Letters("rweob"), // 0x15
  new Letters("rweobs"), // 0x16
  new Letters("rweos"), // 0x17
  new Letters("rweoss"), // 0x18
  new Letters("rweong"), // 0x19
  new Letters("rweoj"), // 0x1a
  new Letters("rweoc"), // 0x1b
  new Letters("rweok"), // 0x1c
  new Letters("rweot"), // 0x1d
  new Letters("rweop"), // 0x1e
  new Letters("rweoh"), // 0x1f
  new Letters("rwe"), // 0x20
  new Letters("rweg"), // 0x21
  new Letters("rwegg"), // 0x22
  new Letters("rwegs"), // 0x23
  new Letters("rwen"), // 0x24
  new Letters("rwenj"), // 0x25
  new Letters("rwenh"), // 0x26
  new Letters("rwed"), // 0x27
  new Letters("rwel"), // 0x28
  new Letters("rwelg"), // 0x29
  new Letters("rwelm"), // 0x2a
  new Letters("rwelb"), // 0x2b
  new Letters("rwels"), // 0x2c
  new Letters("rwelt"), // 0x2d
  new Letters("rwelp"), // 0x2e
  new Letters("rwelh"), // 0x2f
  new Letters("rwem"), // 0x30
  new Letters("rweb"), // 0x31
  new Letters("rwebs"), // 0x32
  new Letters("rwes"), // 0x33
  new Letters("rwess"), // 0x34
  new Letters("rweng"), // 0x35
  new Letters("rwej"), // 0x36
  new Letters("rwec"), // 0x37
  new Letters("rwek"), // 0x38
  new Letters("rwet"), // 0x39
  new Letters("rwep"), // 0x3a
  new Letters("rweh"), // 0x3b
  new Letters("rwi"), // 0x3c
  new Letters("rwig"), // 0x3d
  new Letters("rwigg"), // 0x3e
  new Letters("rwigs"), // 0x3f
  new Letters("rwin"), // 0x40
  new Letters("rwinj"), // 0x41
  new Letters("rwinh"), // 0x42
  new Letters("rwid"), // 0x43
  new Letters("rwil"), // 0x44
  new Letters("rwilg"), // 0x45
  new Letters("rwilm"), // 0x46
  new Letters("rwilb"), // 0x47
  new Letters("rwils"), // 0x48
  new Letters("rwilt"), // 0x49
  new Letters("rwilp"), // 0x4a
  new Letters("rwilh"), // 0x4b
  new Letters("rwim"), // 0x4c
  new Letters("rwib"), // 0x4d
  new Letters("rwibs"), // 0x4e
  new Letters("rwis"), // 0x4f
  new Letters("rwiss"), // 0x50
  new Letters("rwing"), // 0x51
  new Letters("rwij"), // 0x52
  new Letters("rwic"), // 0x53
  new Letters("rwik"), // 0x54
  new Letters("rwit"), // 0x55
  new Letters("rwip"), // 0x56
  new Letters("rwih"), // 0x57
  new Letters("ryu"), // 0x58
  new Letters("ryug"), // 0x59
  new Letters("ryugg"), // 0x5a
  new Letters("ryugs"), // 0x5b
  new Letters("ryun"), // 0x5c
  new Letters("ryunj"), // 0x5d
  new Letters("ryunh"), // 0x5e
  new Letters("ryud"), // 0x5f
  new Letters("ryul"), // 0x60
  new Letters("ryulg"), // 0x61
  new Letters("ryulm"), // 0x62
  new Letters("ryulb"), // 0x63
  new Letters("ryuls"), // 0x64
  new Letters("ryult"), // 0x65
  new Letters("ryulp"), // 0x66
  new Letters("ryulh"), // 0x67
  new Letters("ryum"), // 0x68
  new Letters("ryub"), // 0x69
  new Letters("ryubs"), // 0x6a
  new Letters("ryus"), // 0x6b
  new Letters("ryuss"), // 0x6c
  new Letters("ryung"), // 0x6d
  new Letters("ryuj"), // 0x6e
  new Letters("ryuc"), // 0x6f
  new Letters("ryuk"), // 0x70
  new Letters("ryut"), // 0x71
  new Letters("ryup"), // 0x72
  new Letters("ryuh"), // 0x73
  new Letters("reu"), // 0x74
  new Letters("reug"), // 0x75
  new Letters("reugg"), // 0x76
  new Letters("reugs"), // 0x77
  new Letters("reun"), // 0x78
  new Letters("reunj"), // 0x79
  new Letters("reunh"), // 0x7a
  new Letters("reud"), // 0x7b
  new Letters("reul"), // 0x7c
  new Letters("reulg"), // 0x7d
  new Letters("reulm"), // 0x7e
  new Letters("reulb"), // 0x7f
  new Letters("reuls"), // 0x80
  new Letters("reult"), // 0x81
  new Letters("reulp"), // 0x82
  new Letters("reulh"), // 0x83
  new Letters("reum"), // 0x84
  new Letters("reub"), // 0x85
  new Letters("reubs"), // 0x86
  new Letters("reus"), // 0x87
  new Letters("reuss"), // 0x88
  new Letters("reung"), // 0x89
  new Letters("reuj"), // 0x8a
  new Letters("reuc"), // 0x8b
  new Letters("reuk"), // 0x8c
  new Letters("reut"), // 0x8d
  new Letters("reup"), // 0x8e
  new Letters("reuh"), // 0x8f
  new Letters("ryi"), // 0x90
  new Letters("ryig"), // 0x91
  new Letters("ryigg"), // 0x92
  new Letters("ryigs"), // 0x93
  new Letters("ryin"), // 0x94
  new Letters("ryinj"), // 0x95
  new Letters("ryinh"), // 0x96
  new Letters("ryid"), // 0x97
  new Letters("ryil"), // 0x98
  new Letters("ryilg"), // 0x99
  new Letters("ryilm"), // 0x9a
  new Letters("ryilb"), // 0x9b
  new Letters("ryils"), // 0x9c
  new Letters("ryilt"), // 0x9d
  new Letters("ryilp"), // 0x9e
  new Letters("ryilh"), // 0x9f
  new Letters("ryim"), // 0xa0
  new Letters("ryib"), // 0xa1
  new Letters("ryibs"), // 0xa2
  new Letters("ryis"), // 0xa3
  new Letters("ryiss"), // 0xa4
  new Letters("rying"), // 0xa5
  new Letters("ryij"), // 0xa6
  new Letters("ryic"), // 0xa7
  new Letters("ryik"), // 0xa8
  new Letters("ryit"), // 0xa9
  new Letters("ryip"), // 0xaa
  new Letters("ryih"), // 0xab
  LO_RI, // 0xac
  new Letters("rig"), // 0xad
  new Letters("rigg"), // 0xae
  new Letters("rigs"), // 0xaf
  new Letters("rin"), // 0xb0
  new Letters("rinj"), // 0xb1
  new Letters("rinh"), // 0xb2
  new Letters("rid"), // 0xb3
  new Letters("ril"), // 0xb4
  new Letters("rilg"), // 0xb5
  new Letters("rilm"), // 0xb6
  new Letters("rilb"), // 0xb7
  new Letters("rils"), // 0xb8
  new Letters("rilt"), // 0xb9
  new Letters("rilp"), // 0xba
  new Letters("rilh"), // 0xbb
  new Letters("rim"), // 0xbc
  new Letters("rib"), // 0xbd
  new Letters("ribs"), // 0xbe
  new Letters("ris"), // 0xbf
  new Letters("riss"), // 0xc0
  new Letters("ring"), // 0xc1
  new Letters("rij"), // 0xc2
  new Letters("ric"), // 0xc3
  new Letters("rik"), // 0xc4
  new Letters("rit"), // 0xc5
  new Letters("rip"), // 0xc6
  new Letters("rih"), // 0xc7
  LO_MA, // 0xc8
  new Letters("mag"), // 0xc9
  new Letters("magg"), // 0xca
  new Letters("mags"), // 0xcb
  new Letters("man"), // 0xcc
  new Letters("manj"), // 0xcd
  new Letters("manh"), // 0xce
  new Letters("mad"), // 0xcf
  new Letters("mal"), // 0xd0
  new Letters("malg"), // 0xd1
  new Letters("malm"), // 0xd2
  new Letters("malb"), // 0xd3
  new Letters("mals"), // 0xd4
  new Letters("malt"), // 0xd5
  new Letters("malp"), // 0xd6
  new Letters("malh"), // 0xd7
  new Letters("mam"), // 0xd8
  new Letters("mab"), // 0xd9
  new Letters("mabs"), // 0xda
  new Letters("mas"), // 0xdb
  new Letters("mass"), // 0xdc
  new Letters("mang"), // 0xdd
  new Letters("maj"), // 0xde
  new Letters("mac"), // 0xdf
  new Letters("mak"), // 0xe0
  new Letters("mat"), // 0xe1
  new Letters("map"), // 0xe2
  new Letters("mah"), // 0xe3
  new Letters("mae"), // 0xe4
  new Letters("maeg"), // 0xe5
  new Letters("maegg"), // 0xe6
  new Letters("maegs"), // 0xe7
  new Letters("maen"), // 0xe8
  new Letters("maenj"), // 0xe9
  new Letters("maenh"), // 0xea
  new Letters("maed"), // 0xeb
  new Letters("mael"), // 0xec
  new Letters("maelg"), // 0xed
  new Letters("maelm"), // 0xee
  new Letters("maelb"), // 0xef
  new Letters("maels"), // 0xf0
  new Letters("maelt"), // 0xf1
  new Letters("maelp"), // 0xf2
  new Letters("maelh"), // 0xf3
  new Letters("maem"), // 0xf4
  new Letters("maeb"), // 0xf5
  new Letters("maebs"), // 0xf6
  new Letters("maes"), // 0xf7
  new Letters("maess"), // 0xf8
  new Letters("maeng"), // 0xf9
  new Letters("maej"), // 0xfa
  new Letters("maec"), // 0xfb
  new Letters("maek"), // 0xfc
  new Letters("maet"), // 0xfd
  new Letters("maep"), // 0xfe
  new Letters("maeh") // 0xff
  };
}