/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+BAxx (Hangul Syllables for Korean).
 */
final class Xba extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("mya"), // 0x00
  new Letters("myag"), // 0x01
  new Letters("myagg"), // 0x02
  new Letters("myags"), // 0x03
  new Letters("myan"), // 0x04
  new Letters("myanj"), // 0x05
  new Letters("myanh"), // 0x06
  new Letters("myad"), // 0x07
  new Letters("myal"), // 0x08
  new Letters("myalg"), // 0x09
  new Letters("myalm"), // 0x0a
  new Letters("myalb"), // 0x0b
  new Letters("myals"), // 0x0c
  new Letters("myalt"), // 0x0d
  new Letters("myalp"), // 0x0e
  new Letters("myalh"), // 0x0f
  new Letters("myam"), // 0x10
  new Letters("myab"), // 0x11
  new Letters("myabs"), // 0x12
  new Letters("myas"), // 0x13
  new Letters("myass"), // 0x14
  new Letters("myang"), // 0x15
  new Letters("myaj"), // 0x16
  new Letters("myac"), // 0x17
  new Letters("myak"), // 0x18
  new Letters("myat"), // 0x19
  new Letters("myap"), // 0x1a
  new Letters("myah"), // 0x1b
  new Letters("myae"), // 0x1c
  new Letters("myaeg"), // 0x1d
  new Letters("myaegg"), // 0x1e
  new Letters("myaegs"), // 0x1f
  new Letters("myaen"), // 0x20
  new Letters("myaenj"), // 0x21
  new Letters("myaenh"), // 0x22
  new Letters("myaed"), // 0x23
  new Letters("myael"), // 0x24
  new Letters("myaelg"), // 0x25
  new Letters("myaelm"), // 0x26
  new Letters("myaelb"), // 0x27
  new Letters("myaels"), // 0x28
  new Letters("myaelt"), // 0x29
  new Letters("myaelp"), // 0x2a
  new Letters("myaelh"), // 0x2b
  new Letters("myaem"), // 0x2c
  new Letters("myaeb"), // 0x2d
  new Letters("myaebs"), // 0x2e
  new Letters("myaes"), // 0x2f
  new Letters("myaess"), // 0x30
  new Letters("myaeng"), // 0x31
  new Letters("myaej"), // 0x32
  new Letters("myaec"), // 0x33
  new Letters("myaek"), // 0x34
  new Letters("myaet"), // 0x35
  new Letters("myaep"), // 0x36
  new Letters("myaeh"), // 0x37
  new Letters("meo"), // 0x38
  new Letters("meog"), // 0x39
  new Letters("meogg"), // 0x3a
  new Letters("meogs"), // 0x3b
  new Letters("meon"), // 0x3c
  new Letters("meonj"), // 0x3d
  new Letters("meonh"), // 0x3e
  new Letters("meod"), // 0x3f
  new Letters("meol"), // 0x40
  new Letters("meolg"), // 0x41
  new Letters("meolm"), // 0x42
  new Letters("meolb"), // 0x43
  new Letters("meols"), // 0x44
  new Letters("meolt"), // 0x45
  new Letters("meolp"), // 0x46
  new Letters("meolh"), // 0x47
  new Letters("meom"), // 0x48
  new Letters("meob"), // 0x49
  new Letters("meobs"), // 0x4a
  new Letters("meos"), // 0x4b
  new Letters("meoss"), // 0x4c
  new Letters("meong"), // 0x4d
  new Letters("meoj"), // 0x4e
  new Letters("meoc"), // 0x4f
  new Letters("meok"), // 0x50
  new Letters("meot"), // 0x51
  new Letters("meop"), // 0x52
  new Letters("meoh"), // 0x53
  LO_ME, // 0x54
  new Letters("meg"), // 0x55
  new Letters("megg"), // 0x56
  new Letters("megs"), // 0x57
  new Letters("men"), // 0x58
  new Letters("menj"), // 0x59
  new Letters("menh"), // 0x5a
  new Letters("med"), // 0x5b
  new Letters("mel"), // 0x5c
  new Letters("melg"), // 0x5d
  new Letters("melm"), // 0x5e
  new Letters("melb"), // 0x5f
  new Letters("mels"), // 0x60
  new Letters("melt"), // 0x61
  new Letters("melp"), // 0x62
  new Letters("melh"), // 0x63
  new Letters("mem"), // 0x64
  new Letters("meb"), // 0x65
  new Letters("mebs"), // 0x66
  new Letters("mes"), // 0x67
  new Letters("mess"), // 0x68
  new Letters("meng"), // 0x69
  new Letters("mej"), // 0x6a
  new Letters("mec"), // 0x6b
  new Letters("mek"), // 0x6c
  new Letters("met"), // 0x6d
  new Letters("mep"), // 0x6e
  new Letters("meh"), // 0x6f
  new Letters("myeo"), // 0x70
  new Letters("myeog"), // 0x71
  new Letters("myeogg"), // 0x72
  new Letters("myeogs"), // 0x73
  new Letters("myeon"), // 0x74
  new Letters("myeonj"), // 0x75
  new Letters("myeonh"), // 0x76
  new Letters("myeod"), // 0x77
  new Letters("myeol"), // 0x78
  new Letters("myeolg"), // 0x79
  new Letters("myeolm"), // 0x7a
  new Letters("myeolb"), // 0x7b
  new Letters("myeols"), // 0x7c
  new Letters("myeolt"), // 0x7d
  new Letters("myeolp"), // 0x7e
  new Letters("myeolh"), // 0x7f
  new Letters("myeom"), // 0x80
  new Letters("myeob"), // 0x81
  new Letters("myeobs"), // 0x82
  new Letters("myeos"), // 0x83
  new Letters("myeoss"), // 0x84
  new Letters("myeong"), // 0x85
  new Letters("myeoj"), // 0x86
  new Letters("myeoc"), // 0x87
  new Letters("myeok"), // 0x88
  new Letters("myeot"), // 0x89
  new Letters("myeop"), // 0x8a
  new Letters("myeoh"), // 0x8b
  new Letters("mye"), // 0x8c
  new Letters("myeg"), // 0x8d
  new Letters("myegg"), // 0x8e
  new Letters("myegs"), // 0x8f
  new Letters("myen"), // 0x90
  new Letters("myenj"), // 0x91
  new Letters("myenh"), // 0x92
  new Letters("myed"), // 0x93
  new Letters("myel"), // 0x94
  new Letters("myelg"), // 0x95
  new Letters("myelm"), // 0x96
  new Letters("myelb"), // 0x97
  new Letters("myels"), // 0x98
  new Letters("myelt"), // 0x99
  new Letters("myelp"), // 0x9a
  new Letters("myelh"), // 0x9b
  new Letters("myem"), // 0x9c
  new Letters("myeb"), // 0x9d
  new Letters("myebs"), // 0x9e
  new Letters("myes"), // 0x9f
  new Letters("myess"), // 0xa0
  new Letters("myeng"), // 0xa1
  new Letters("myej"), // 0xa2
  new Letters("myec"), // 0xa3
  new Letters("myek"), // 0xa4
  new Letters("myet"), // 0xa5
  new Letters("myep"), // 0xa6
  new Letters("myeh"), // 0xa7
  LO_MO, // 0xa8
  new Letters("mog"), // 0xa9
  new Letters("mogg"), // 0xaa
  new Letters("mogs"), // 0xab
  new Letters("mon"), // 0xac
  new Letters("monj"), // 0xad
  new Letters("monh"), // 0xae
  new Letters("mod"), // 0xaf
  new Letters("mol"), // 0xb0
  new Letters("molg"), // 0xb1
  new Letters("molm"), // 0xb2
  new Letters("molb"), // 0xb3
  new Letters("mols"), // 0xb4
  new Letters("molt"), // 0xb5
  new Letters("molp"), // 0xb6
  new Letters("molh"), // 0xb7
  new Letters("mom"), // 0xb8
  new Letters("mob"), // 0xb9
  new Letters("mobs"), // 0xba
  new Letters("mos"), // 0xbb
  new Letters("moss"), // 0xbc
  new Letters("mong"), // 0xbd
  new Letters("moj"), // 0xbe
  new Letters("moc"), // 0xbf
  new Letters("mok"), // 0xc0
  new Letters("mot"), // 0xc1
  new Letters("mop"), // 0xc2
  new Letters("moh"), // 0xc3
  new Letters("mwa"), // 0xc4
  new Letters("mwag"), // 0xc5
  new Letters("mwagg"), // 0xc6
  new Letters("mwags"), // 0xc7
  new Letters("mwan"), // 0xc8
  new Letters("mwanj"), // 0xc9
  new Letters("mwanh"), // 0xca
  new Letters("mwad"), // 0xcb
  new Letters("mwal"), // 0xcc
  new Letters("mwalg"), // 0xcd
  new Letters("mwalm"), // 0xce
  new Letters("mwalb"), // 0xcf
  new Letters("mwals"), // 0xd0
  new Letters("mwalt"), // 0xd1
  new Letters("mwalp"), // 0xd2
  new Letters("mwalh"), // 0xd3
  new Letters("mwam"), // 0xd4
  new Letters("mwab"), // 0xd5
  new Letters("mwabs"), // 0xd6
  new Letters("mwas"), // 0xd7
  new Letters("mwass"), // 0xd8
  new Letters("mwang"), // 0xd9
  new Letters("mwaj"), // 0xda
  new Letters("mwac"), // 0xdb
  new Letters("mwak"), // 0xdc
  new Letters("mwat"), // 0xdd
  new Letters("mwap"), // 0xde
  new Letters("mwah"), // 0xdf
  new Letters("mwae"), // 0xe0
  new Letters("mwaeg"), // 0xe1
  new Letters("mwaegg"), // 0xe2
  new Letters("mwaegs"), // 0xe3
  new Letters("mwaen"), // 0xe4
  new Letters("mwaenj"), // 0xe5
  new Letters("mwaenh"), // 0xe6
  new Letters("mwaed"), // 0xe7
  new Letters("mwael"), // 0xe8
  new Letters("mwaelg"), // 0xe9
  new Letters("mwaelm"), // 0xea
  new Letters("mwaelb"), // 0xeb
  new Letters("mwaels"), // 0xec
  new Letters("mwaelt"), // 0xed
  new Letters("mwaelp"), // 0xee
  new Letters("mwaelh"), // 0xef
  new Letters("mwaem"), // 0xf0
  new Letters("mwaeb"), // 0xf1
  new Letters("mwaebs"), // 0xf2
  new Letters("mwaes"), // 0xf3
  new Letters("mwaess"), // 0xf4
  new Letters("mwaeng"), // 0xf5
  new Letters("mwaej"), // 0xf6
  new Letters("mwaec"), // 0xf7
  new Letters("mwaek"), // 0xf8
  new Letters("mwaet"), // 0xf9
  new Letters("mwaep"), // 0xfa
  new Letters("mwaeh"), // 0xfb
  new Letters("moe"), // 0xfc
  new Letters("moeg"), // 0xfd
  new Letters("moegg"), // 0xfe
  new Letters("moegs") // 0xff
  };
}