/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+BBxx (Hangul Syllables for Korean).
 */
final class Xbb extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("moen"), // 0x00
  new Letters("moenj"), // 0x01
  new Letters("moenh"), // 0x02
  new Letters("moed"), // 0x03
  new Letters("moel"), // 0x04
  new Letters("moelg"), // 0x05
  new Letters("moelm"), // 0x06
  new Letters("moelb"), // 0x07
  new Letters("moels"), // 0x08
  new Letters("moelt"), // 0x09
  new Letters("moelp"), // 0x0a
  new Letters("moelh"), // 0x0b
  new Letters("moem"), // 0x0c
  new Letters("moeb"), // 0x0d
  new Letters("moebs"), // 0x0e
  new Letters("moes"), // 0x0f
  new Letters("moess"), // 0x10
  new Letters("moeng"), // 0x11
  new Letters("moej"), // 0x12
  new Letters("moec"), // 0x13
  new Letters("moek"), // 0x14
  new Letters("moet"), // 0x15
  new Letters("moep"), // 0x16
  new Letters("moeh"), // 0x17
  new Letters("myo"), // 0x18
  new Letters("myog"), // 0x19
  new Letters("myogg"), // 0x1a
  new Letters("myogs"), // 0x1b
  new Letters("myon"), // 0x1c
  new Letters("myonj"), // 0x1d
  new Letters("myonh"), // 0x1e
  new Letters("myod"), // 0x1f
  new Letters("myol"), // 0x20
  new Letters("myolg"), // 0x21
  new Letters("myolm"), // 0x22
  new Letters("myolb"), // 0x23
  new Letters("myols"), // 0x24
  new Letters("myolt"), // 0x25
  new Letters("myolp"), // 0x26
  new Letters("myolh"), // 0x27
  new Letters("myom"), // 0x28
  new Letters("myob"), // 0x29
  new Letters("myobs"), // 0x2a
  new Letters("myos"), // 0x2b
  new Letters("myoss"), // 0x2c
  new Letters("myong"), // 0x2d
  new Letters("myoj"), // 0x2e
  new Letters("myoc"), // 0x2f
  new Letters("myok"), // 0x30
  new Letters("myot"), // 0x31
  new Letters("myop"), // 0x32
  new Letters("myoh"), // 0x33
  LO_MU, // 0x34
  new Letters("mug"), // 0x35
  new Letters("mugg"), // 0x36
  new Letters("mugs"), // 0x37
  new Letters("mun"), // 0x38
  new Letters("munj"), // 0x39
  new Letters("munh"), // 0x3a
  new Letters("mud"), // 0x3b
  new Letters("mul"), // 0x3c
  new Letters("mulg"), // 0x3d
  new Letters("mulm"), // 0x3e
  new Letters("mulb"), // 0x3f
  new Letters("muls"), // 0x40
  new Letters("mult"), // 0x41
  new Letters("mulp"), // 0x42
  new Letters("mulh"), // 0x43
  new Letters("mum"), // 0x44
  new Letters("mub"), // 0x45
  new Letters("mubs"), // 0x46
  new Letters("mus"), // 0x47
  new Letters("muss"), // 0x48
  new Letters("mung"), // 0x49
  new Letters("muj"), // 0x4a
  new Letters("muc"), // 0x4b
  new Letters("muk"), // 0x4c
  new Letters("mut"), // 0x4d
  new Letters("mup"), // 0x4e
  new Letters("muh"), // 0x4f
  new Letters("mweo"), // 0x50
  new Letters("mweog"), // 0x51
  new Letters("mweogg"), // 0x52
  new Letters("mweogs"), // 0x53
  new Letters("mweon"), // 0x54
  new Letters("mweonj"), // 0x55
  new Letters("mweonh"), // 0x56
  new Letters("mweod"), // 0x57
  new Letters("mweol"), // 0x58
  new Letters("mweolg"), // 0x59
  new Letters("mweolm"), // 0x5a
  new Letters("mweolb"), // 0x5b
  new Letters("mweols"), // 0x5c
  new Letters("mweolt"), // 0x5d
  new Letters("mweolp"), // 0x5e
  new Letters("mweolh"), // 0x5f
  new Letters("mweom"), // 0x60
  new Letters("mweob"), // 0x61
  new Letters("mweobs"), // 0x62
  new Letters("mweos"), // 0x63
  new Letters("mweoss"), // 0x64
  new Letters("mweong"), // 0x65
  new Letters("mweoj"), // 0x66
  new Letters("mweoc"), // 0x67
  new Letters("mweok"), // 0x68
  new Letters("mweot"), // 0x69
  new Letters("mweop"), // 0x6a
  new Letters("mweoh"), // 0x6b
  new Letters("mwe"), // 0x6c
  new Letters("mweg"), // 0x6d
  new Letters("mwegg"), // 0x6e
  new Letters("mwegs"), // 0x6f
  new Letters("mwen"), // 0x70
  new Letters("mwenj"), // 0x71
  new Letters("mwenh"), // 0x72
  new Letters("mwed"), // 0x73
  new Letters("mwel"), // 0x74
  new Letters("mwelg"), // 0x75
  new Letters("mwelm"), // 0x76
  new Letters("mwelb"), // 0x77
  new Letters("mwels"), // 0x78
  new Letters("mwelt"), // 0x79
  new Letters("mwelp"), // 0x7a
  new Letters("mwelh"), // 0x7b
  new Letters("mwem"), // 0x7c
  new Letters("mweb"), // 0x7d
  new Letters("mwebs"), // 0x7e
  new Letters("mwes"), // 0x7f
  new Letters("mwess"), // 0x80
  new Letters("mweng"), // 0x81
  new Letters("mwej"), // 0x82
  new Letters("mwec"), // 0x83
  new Letters("mwek"), // 0x84
  new Letters("mwet"), // 0x85
  new Letters("mwep"), // 0x86
  new Letters("mweh"), // 0x87
  new Letters("mwi"), // 0x88
  new Letters("mwig"), // 0x89
  new Letters("mwigg"), // 0x8a
  new Letters("mwigs"), // 0x8b
  new Letters("mwin"), // 0x8c
  new Letters("mwinj"), // 0x8d
  new Letters("mwinh"), // 0x8e
  new Letters("mwid"), // 0x8f
  new Letters("mwil"), // 0x90
  new Letters("mwilg"), // 0x91
  new Letters("mwilm"), // 0x92
  new Letters("mwilb"), // 0x93
  new Letters("mwils"), // 0x94
  new Letters("mwilt"), // 0x95
  new Letters("mwilp"), // 0x96
  new Letters("mwilh"), // 0x97
  new Letters("mwim"), // 0x98
  new Letters("mwib"), // 0x99
  new Letters("mwibs"), // 0x9a
  new Letters("mwis"), // 0x9b
  new Letters("mwiss"), // 0x9c
  new Letters("mwing"), // 0x9d
  new Letters("mwij"), // 0x9e
  new Letters("mwic"), // 0x9f
  new Letters("mwik"), // 0xa0
  new Letters("mwit"), // 0xa1
  new Letters("mwip"), // 0xa2
  new Letters("mwih"), // 0xa3
  new Letters("myu"), // 0xa4
  new Letters("myug"), // 0xa5
  new Letters("myugg"), // 0xa6
  new Letters("myugs"), // 0xa7
  new Letters("myun"), // 0xa8
  new Letters("myunj"), // 0xa9
  new Letters("myunh"), // 0xaa
  new Letters("myud"), // 0xab
  new Letters("myul"), // 0xac
  new Letters("myulg"), // 0xad
  new Letters("myulm"), // 0xae
  new Letters("myulb"), // 0xaf
  new Letters("myuls"), // 0xb0
  new Letters("myult"), // 0xb1
  new Letters("myulp"), // 0xb2
  new Letters("myulh"), // 0xb3
  new Letters("myum"), // 0xb4
  new Letters("myub"), // 0xb5
  new Letters("myubs"), // 0xb6
  new Letters("myus"), // 0xb7
  new Letters("myuss"), // 0xb8
  new Letters("myung"), // 0xb9
  new Letters("myuj"), // 0xba
  new Letters("myuc"), // 0xbb
  new Letters("myuk"), // 0xbc
  new Letters("myut"), // 0xbd
  new Letters("myup"), // 0xbe
  new Letters("myuh"), // 0xbf
  new Letters("meu"), // 0xc0
  new Letters("meug"), // 0xc1
  new Letters("meugg"), // 0xc2
  new Letters("meugs"), // 0xc3
  new Letters("meun"), // 0xc4
  new Letters("meunj"), // 0xc5
  new Letters("meunh"), // 0xc6
  new Letters("meud"), // 0xc7
  new Letters("meul"), // 0xc8
  new Letters("meulg"), // 0xc9
  new Letters("meulm"), // 0xca
  new Letters("meulb"), // 0xcb
  new Letters("meuls"), // 0xcc
  new Letters("meult"), // 0xcd
  new Letters("meulp"), // 0xce
  new Letters("meulh"), // 0xcf
  new Letters("meum"), // 0xd0
  new Letters("meub"), // 0xd1
  new Letters("meubs"), // 0xd2
  new Letters("meus"), // 0xd3
  new Letters("meuss"), // 0xd4
  new Letters("meung"), // 0xd5
  new Letters("meuj"), // 0xd6
  new Letters("meuc"), // 0xd7
  new Letters("meuk"), // 0xd8
  new Letters("meut"), // 0xd9
  new Letters("meup"), // 0xda
  new Letters("meuh"), // 0xdb
  new Letters("myi"), // 0xdc
  new Letters("myig"), // 0xdd
  new Letters("myigg"), // 0xde
  new Letters("myigs"), // 0xdf
  new Letters("myin"), // 0xe0
  new Letters("myinj"), // 0xe1
  new Letters("myinh"), // 0xe2
  new Letters("myid"), // 0xe3
  new Letters("myil"), // 0xe4
  new Letters("myilg"), // 0xe5
  new Letters("myilm"), // 0xe6
  new Letters("myilb"), // 0xe7
  new Letters("myils"), // 0xe8
  new Letters("myilt"), // 0xe9
  new Letters("myilp"), // 0xea
  new Letters("myilh"), // 0xeb
  new Letters("myim"), // 0xec
  new Letters("myib"), // 0xed
  new Letters("myibs"), // 0xee
  new Letters("myis"), // 0xef
  new Letters("myiss"), // 0xf0
  new Letters("mying"), // 0xf1
  new Letters("myij"), // 0xf2
  new Letters("myic"), // 0xf3
  new Letters("myik"), // 0xf4
  new Letters("myit"), // 0xf5
  new Letters("myip"), // 0xf6
  new Letters("myih"), // 0xf7
  LO_MI, // 0xf8
  new Letters("mig"), // 0xf9
  new Letters("migg"), // 0xfa
  new Letters("migs"), // 0xfb
  new Letters("min"), // 0xfc
  new Letters("minj"), // 0xfd
  new Letters("minh"), // 0xfe
  new Letters("mid") // 0xff
  };
}