/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+BCxx (Hangul Syllables for Korean).
 */
final class Xbc extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("mil"), // 0x00
  new Letters("milg"), // 0x01
  new Letters("milm"), // 0x02
  new Letters("milb"), // 0x03
  new Letters("mils"), // 0x04
  new Letters("milt"), // 0x05
  new Letters("milp"), // 0x06
  new Letters("milh"), // 0x07
  new Letters("mim"), // 0x08
  new Letters("mib"), // 0x09
  new Letters("mibs"), // 0x0a
  new Letters("mis"), // 0x0b
  new Letters("miss"), // 0x0c
  new Letters("ming"), // 0x0d
  new Letters("mij"), // 0x0e
  new Letters("mic"), // 0x0f
  new Letters("mik"), // 0x10
  new Letters("mit"), // 0x11
  new Letters("mip"), // 0x12
  new Letters("mih"), // 0x13
  LO_BA, // 0x14
  new Letters("bag"), // 0x15
  new Letters("bagg"), // 0x16
  new Letters("bags"), // 0x17
  new Letters("ban"), // 0x18
  new Letters("banj"), // 0x19
  new Letters("banh"), // 0x1a
  new Letters("bad"), // 0x1b
  new Letters("bal"), // 0x1c
  new Letters("balg"), // 0x1d
  new Letters("balm"), // 0x1e
  new Letters("balb"), // 0x1f
  new Letters("bals"), // 0x20
  new Letters("balt"), // 0x21
  new Letters("balp"), // 0x22
  new Letters("balh"), // 0x23
  new Letters("bam"), // 0x24
  new Letters("bab"), // 0x25
  new Letters("babs"), // 0x26
  new Letters("bas"), // 0x27
  new Letters("bass"), // 0x28
  new Letters("bang"), // 0x29
  new Letters("baj"), // 0x2a
  new Letters("bac"), // 0x2b
  new Letters("bak"), // 0x2c
  new Letters("bat"), // 0x2d
  new Letters("bap"), // 0x2e
  new Letters("bah"), // 0x2f
  new Letters("bae"), // 0x30
  new Letters("baeg"), // 0x31
  new Letters("baegg"), // 0x32
  new Letters("baegs"), // 0x33
  new Letters("baen"), // 0x34
  new Letters("baenj"), // 0x35
  new Letters("baenh"), // 0x36
  new Letters("baed"), // 0x37
  new Letters("bael"), // 0x38
  new Letters("baelg"), // 0x39
  new Letters("baelm"), // 0x3a
  new Letters("baelb"), // 0x3b
  new Letters("baels"), // 0x3c
  new Letters("baelt"), // 0x3d
  new Letters("baelp"), // 0x3e
  new Letters("baelh"), // 0x3f
  new Letters("baem"), // 0x40
  new Letters("baeb"), // 0x41
  new Letters("baebs"), // 0x42
  new Letters("baes"), // 0x43
  new Letters("baess"), // 0x44
  new Letters("baeng"), // 0x45
  new Letters("baej"), // 0x46
  new Letters("baec"), // 0x47
  new Letters("baek"), // 0x48
  new Letters("baet"), // 0x49
  new Letters("baep"), // 0x4a
  new Letters("baeh"), // 0x4b
  new Letters("bya"), // 0x4c
  new Letters("byag"), // 0x4d
  new Letters("byagg"), // 0x4e
  new Letters("byags"), // 0x4f
  new Letters("byan"), // 0x50
  new Letters("byanj"), // 0x51
  new Letters("byanh"), // 0x52
  new Letters("byad"), // 0x53
  new Letters("byal"), // 0x54
  new Letters("byalg"), // 0x55
  new Letters("byalm"), // 0x56
  new Letters("byalb"), // 0x57
  new Letters("byals"), // 0x58
  new Letters("byalt"), // 0x59
  new Letters("byalp"), // 0x5a
  new Letters("byalh"), // 0x5b
  new Letters("byam"), // 0x5c
  new Letters("byab"), // 0x5d
  new Letters("byabs"), // 0x5e
  new Letters("byas"), // 0x5f
  new Letters("byass"), // 0x60
  new Letters("byang"), // 0x61
  new Letters("byaj"), // 0x62
  new Letters("byac"), // 0x63
  new Letters("byak"), // 0x64
  new Letters("byat"), // 0x65
  new Letters("byap"), // 0x66
  new Letters("byah"), // 0x67
  new Letters("byae"), // 0x68
  new Letters("byaeg"), // 0x69
  new Letters("byaegg"), // 0x6a
  new Letters("byaegs"), // 0x6b
  new Letters("byaen"), // 0x6c
  new Letters("byaenj"), // 0x6d
  new Letters("byaenh"), // 0x6e
  new Letters("byaed"), // 0x6f
  new Letters("byael"), // 0x70
  new Letters("byaelg"), // 0x71
  new Letters("byaelm"), // 0x72
  new Letters("byaelb"), // 0x73
  new Letters("byaels"), // 0x74
  new Letters("byaelt"), // 0x75
  new Letters("byaelp"), // 0x76
  new Letters("byaelh"), // 0x77
  new Letters("byaem"), // 0x78
  new Letters("byaeb"), // 0x79
  new Letters("byaebs"), // 0x7a
  new Letters("byaes"), // 0x7b
  new Letters("byaess"), // 0x7c
  new Letters("byaeng"), // 0x7d
  new Letters("byaej"), // 0x7e
  new Letters("byaec"), // 0x7f
  new Letters("byaek"), // 0x80
  new Letters("byaet"), // 0x81
  new Letters("byaep"), // 0x82
  new Letters("byaeh"), // 0x83
  new Letters("beo"), // 0x84
  new Letters("beog"), // 0x85
  new Letters("beogg"), // 0x86
  new Letters("beogs"), // 0x87
  new Letters("beon"), // 0x88
  new Letters("beonj"), // 0x89
  new Letters("beonh"), // 0x8a
  new Letters("beod"), // 0x8b
  new Letters("beol"), // 0x8c
  new Letters("beolg"), // 0x8d
  new Letters("beolm"), // 0x8e
  new Letters("beolb"), // 0x8f
  new Letters("beols"), // 0x90
  new Letters("beolt"), // 0x91
  new Letters("beolp"), // 0x92
  new Letters("beolh"), // 0x93
  new Letters("beom"), // 0x94
  new Letters("beob"), // 0x95
  new Letters("beobs"), // 0x96
  new Letters("beos"), // 0x97
  new Letters("beoss"), // 0x98
  new Letters("beong"), // 0x99
  new Letters("beoj"), // 0x9a
  new Letters("beoc"), // 0x9b
  new Letters("beok"), // 0x9c
  new Letters("beot"), // 0x9d
  new Letters("beop"), // 0x9e
  new Letters("beoh"), // 0x9f
  LO_BE, // 0xa0
  new Letters("beg"), // 0xa1
  new Letters("begg"), // 0xa2
  new Letters("begs"), // 0xa3
  new Letters("ben"), // 0xa4
  new Letters("benj"), // 0xa5
  new Letters("benh"), // 0xa6
  new Letters("bed"), // 0xa7
  new Letters("bel"), // 0xa8
  new Letters("belg"), // 0xa9
  new Letters("belm"), // 0xaa
  new Letters("belb"), // 0xab
  new Letters("bels"), // 0xac
  new Letters("belt"), // 0xad
  new Letters("belp"), // 0xae
  new Letters("belh"), // 0xaf
  new Letters("bem"), // 0xb0
  new Letters("beb"), // 0xb1
  new Letters("bebs"), // 0xb2
  new Letters("bes"), // 0xb3
  new Letters("bess"), // 0xb4
  new Letters("beng"), // 0xb5
  new Letters("bej"), // 0xb6
  new Letters("bec"), // 0xb7
  new Letters("bek"), // 0xb8
  new Letters("bet"), // 0xb9
  new Letters("bep"), // 0xba
  new Letters("beh"), // 0xbb
  new Letters("byeo"), // 0xbc
  new Letters("byeog"), // 0xbd
  new Letters("byeogg"), // 0xbe
  new Letters("byeogs"), // 0xbf
  new Letters("byeon"), // 0xc0
  new Letters("byeonj"), // 0xc1
  new Letters("byeonh"), // 0xc2
  new Letters("byeod"), // 0xc3
  new Letters("byeol"), // 0xc4
  new Letters("byeolg"), // 0xc5
  new Letters("byeolm"), // 0xc6
  new Letters("byeolb"), // 0xc7
  new Letters("byeols"), // 0xc8
  new Letters("byeolt"), // 0xc9
  new Letters("byeolp"), // 0xca
  new Letters("byeolh"), // 0xcb
  new Letters("byeom"), // 0xcc
  new Letters("byeob"), // 0xcd
  new Letters("byeobs"), // 0xce
  new Letters("byeos"), // 0xcf
  new Letters("byeoss"), // 0xd0
  new Letters("byeong"), // 0xd1
  new Letters("byeoj"), // 0xd2
  new Letters("byeoc"), // 0xd3
  new Letters("byeok"), // 0xd4
  new Letters("byeot"), // 0xd5
  new Letters("byeop"), // 0xd6
  new Letters("byeoh"), // 0xd7
  new Letters("bye"), // 0xd8
  new Letters("byeg"), // 0xd9
  new Letters("byegg"), // 0xda
  new Letters("byegs"), // 0xdb
  new Letters("byen"), // 0xdc
  new Letters("byenj"), // 0xdd
  new Letters("byenh"), // 0xde
  new Letters("byed"), // 0xdf
  new Letters("byel"), // 0xe0
  new Letters("byelg"), // 0xe1
  new Letters("byelm"), // 0xe2
  new Letters("byelb"), // 0xe3
  new Letters("byels"), // 0xe4
  new Letters("byelt"), // 0xe5
  new Letters("byelp"), // 0xe6
  new Letters("byelh"), // 0xe7
  new Letters("byem"), // 0xe8
  new Letters("byeb"), // 0xe9
  new Letters("byebs"), // 0xea
  new Letters("byes"), // 0xeb
  new Letters("byess"), // 0xec
  new Letters("byeng"), // 0xed
  new Letters("byej"), // 0xee
  new Letters("byec"), // 0xef
  new Letters("byek"), // 0xf0
  new Letters("byet"), // 0xf1
  new Letters("byep"), // 0xf2
  new Letters("byeh"), // 0xf3
  LO_BO, // 0xf4
  new Letters("bog"), // 0xf5
  new Letters("bogg"), // 0xf6
  new Letters("bogs"), // 0xf7
  new Letters("bon"), // 0xf8
  new Letters("bonj"), // 0xf9
  new Letters("bonh"), // 0xfa
  new Letters("bod"), // 0xfb
  new Letters("bol"), // 0xfc
  new Letters("bolg"), // 0xfd
  new Letters("bolm"), // 0xfe
  new Letters("bolb") // 0xff
  };
}