/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+BDxx (Hangul Syllables for Korean).
 */
final class Xbd extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("bols"), // 0x00
  new Letters("bolt"), // 0x01
  new Letters("bolp"), // 0x02
  new Letters("bolh"), // 0x03
  new Letters("bom"), // 0x04
  new Letters("bob"), // 0x05
  new Letters("bobs"), // 0x06
  new Letters("bos"), // 0x07
  new Letters("boss"), // 0x08
  new Letters("bong"), // 0x09
  new Letters("boj"), // 0x0a
  new Letters("boc"), // 0x0b
  new Letters("bok"), // 0x0c
  new Letters("bot"), // 0x0d
  new Letters("bop"), // 0x0e
  new Letters("boh"), // 0x0f
  new Letters("bwa"), // 0x10
  new Letters("bwag"), // 0x11
  new Letters("bwagg"), // 0x12
  new Letters("bwags"), // 0x13
  new Letters("bwan"), // 0x14
  new Letters("bwanj"), // 0x15
  new Letters("bwanh"), // 0x16
  new Letters("bwad"), // 0x17
  new Letters("bwal"), // 0x18
  new Letters("bwalg"), // 0x19
  new Letters("bwalm"), // 0x1a
  new Letters("bwalb"), // 0x1b
  new Letters("bwals"), // 0x1c
  new Letters("bwalt"), // 0x1d
  new Letters("bwalp"), // 0x1e
  new Letters("bwalh"), // 0x1f
  new Letters("bwam"), // 0x20
  new Letters("bwab"), // 0x21
  new Letters("bwabs"), // 0x22
  new Letters("bwas"), // 0x23
  new Letters("bwass"), // 0x24
  new Letters("bwang"), // 0x25
  new Letters("bwaj"), // 0x26
  new Letters("bwac"), // 0x27
  new Letters("bwak"), // 0x28
  new Letters("bwat"), // 0x29
  new Letters("bwap"), // 0x2a
  new Letters("bwah"), // 0x2b
  new Letters("bwae"), // 0x2c
  new Letters("bwaeg"), // 0x2d
  new Letters("bwaegg"), // 0x2e
  new Letters("bwaegs"), // 0x2f
  new Letters("bwaen"), // 0x30
  new Letters("bwaenj"), // 0x31
  new Letters("bwaenh"), // 0x32
  new Letters("bwaed"), // 0x33
  new Letters("bwael"), // 0x34
  new Letters("bwaelg"), // 0x35
  new Letters("bwaelm"), // 0x36
  new Letters("bwaelb"), // 0x37
  new Letters("bwaels"), // 0x38
  new Letters("bwaelt"), // 0x39
  new Letters("bwaelp"), // 0x3a
  new Letters("bwaelh"), // 0x3b
  new Letters("bwaem"), // 0x3c
  new Letters("bwaeb"), // 0x3d
  new Letters("bwaebs"), // 0x3e
  new Letters("bwaes"), // 0x3f
  new Letters("bwaess"), // 0x40
  new Letters("bwaeng"), // 0x41
  new Letters("bwaej"), // 0x42
  new Letters("bwaec"), // 0x43
  new Letters("bwaek"), // 0x44
  new Letters("bwaet"), // 0x45
  new Letters("bwaep"), // 0x46
  new Letters("bwaeh"), // 0x47
  new Letters("boe"), // 0x48
  new Letters("boeg"), // 0x49
  new Letters("boegg"), // 0x4a
  new Letters("boegs"), // 0x4b
  new Letters("boen"), // 0x4c
  new Letters("boenj"), // 0x4d
  new Letters("boenh"), // 0x4e
  new Letters("boed"), // 0x4f
  new Letters("boel"), // 0x50
  new Letters("boelg"), // 0x51
  new Letters("boelm"), // 0x52
  new Letters("boelb"), // 0x53
  new Letters("boels"), // 0x54
  new Letters("boelt"), // 0x55
  new Letters("boelp"), // 0x56
  new Letters("boelh"), // 0x57
  new Letters("boem"), // 0x58
  new Letters("boeb"), // 0x59
  new Letters("boebs"), // 0x5a
  new Letters("boes"), // 0x5b
  new Letters("boess"), // 0x5c
  new Letters("boeng"), // 0x5d
  new Letters("boej"), // 0x5e
  new Letters("boec"), // 0x5f
  new Letters("boek"), // 0x60
  new Letters("boet"), // 0x61
  new Letters("boep"), // 0x62
  new Letters("boeh"), // 0x63
  new Letters("byo"), // 0x64
  new Letters("byog"), // 0x65
  new Letters("byogg"), // 0x66
  new Letters("byogs"), // 0x67
  new Letters("byon"), // 0x68
  new Letters("byonj"), // 0x69
  new Letters("byonh"), // 0x6a
  new Letters("byod"), // 0x6b
  new Letters("byol"), // 0x6c
  new Letters("byolg"), // 0x6d
  new Letters("byolm"), // 0x6e
  new Letters("byolb"), // 0x6f
  new Letters("byols"), // 0x70
  new Letters("byolt"), // 0x71
  new Letters("byolp"), // 0x72
  new Letters("byolh"), // 0x73
  new Letters("byom"), // 0x74
  new Letters("byob"), // 0x75
  new Letters("byobs"), // 0x76
  new Letters("byos"), // 0x77
  new Letters("byoss"), // 0x78
  new Letters("byong"), // 0x79
  new Letters("byoj"), // 0x7a
  new Letters("byoc"), // 0x7b
  new Letters("byok"), // 0x7c
  new Letters("byot"), // 0x7d
  new Letters("byop"), // 0x7e
  new Letters("byoh"), // 0x7f
  LO_BU, // 0x80
  new Letters("bug"), // 0x81
  new Letters("bugg"), // 0x82
  new Letters("bugs"), // 0x83
  new Letters("bun"), // 0x84
  new Letters("bunj"), // 0x85
  new Letters("bunh"), // 0x86
  new Letters("bud"), // 0x87
  new Letters("bul"), // 0x88
  new Letters("bulg"), // 0x89
  new Letters("bulm"), // 0x8a
  new Letters("bulb"), // 0x8b
  new Letters("buls"), // 0x8c
  new Letters("bult"), // 0x8d
  new Letters("bulp"), // 0x8e
  new Letters("bulh"), // 0x8f
  new Letters("bum"), // 0x90
  new Letters("bub"), // 0x91
  new Letters("bubs"), // 0x92
  new Letters("bus"), // 0x93
  new Letters("buss"), // 0x94
  new Letters("bung"), // 0x95
  new Letters("buj"), // 0x96
  new Letters("buc"), // 0x97
  new Letters("buk"), // 0x98
  new Letters("but"), // 0x99
  new Letters("bup"), // 0x9a
  new Letters("buh"), // 0x9b
  new Letters("bweo"), // 0x9c
  new Letters("bweog"), // 0x9d
  new Letters("bweogg"), // 0x9e
  new Letters("bweogs"), // 0x9f
  new Letters("bweon"), // 0xa0
  new Letters("bweonj"), // 0xa1
  new Letters("bweonh"), // 0xa2
  new Letters("bweod"), // 0xa3
  new Letters("bweol"), // 0xa4
  new Letters("bweolg"), // 0xa5
  new Letters("bweolm"), // 0xa6
  new Letters("bweolb"), // 0xa7
  new Letters("bweols"), // 0xa8
  new Letters("bweolt"), // 0xa9
  new Letters("bweolp"), // 0xaa
  new Letters("bweolh"), // 0xab
  new Letters("bweom"), // 0xac
  new Letters("bweob"), // 0xad
  new Letters("bweobs"), // 0xae
  new Letters("bweos"), // 0xaf
  new Letters("bweoss"), // 0xb0
  new Letters("bweong"), // 0xb1
  new Letters("bweoj"), // 0xb2
  new Letters("bweoc"), // 0xb3
  new Letters("bweok"), // 0xb4
  new Letters("bweot"), // 0xb5
  new Letters("bweop"), // 0xb6
  new Letters("bweoh"), // 0xb7
  new Letters("bwe"), // 0xb8
  new Letters("bweg"), // 0xb9
  new Letters("bwegg"), // 0xba
  new Letters("bwegs"), // 0xbb
  new Letters("bwen"), // 0xbc
  new Letters("bwenj"), // 0xbd
  new Letters("bwenh"), // 0xbe
  new Letters("bwed"), // 0xbf
  new Letters("bwel"), // 0xc0
  new Letters("bwelg"), // 0xc1
  new Letters("bwelm"), // 0xc2
  new Letters("bwelb"), // 0xc3
  new Letters("bwels"), // 0xc4
  new Letters("bwelt"), // 0xc5
  new Letters("bwelp"), // 0xc6
  new Letters("bwelh"), // 0xc7
  new Letters("bwem"), // 0xc8
  new Letters("bweb"), // 0xc9
  new Letters("bwebs"), // 0xca
  new Letters("bwes"), // 0xcb
  new Letters("bwess"), // 0xcc
  new Letters("bweng"), // 0xcd
  new Letters("bwej"), // 0xce
  new Letters("bwec"), // 0xcf
  new Letters("bwek"), // 0xd0
  new Letters("bwet"), // 0xd1
  new Letters("bwep"), // 0xd2
  new Letters("bweh"), // 0xd3
  new Letters("bwi"), // 0xd4
  new Letters("bwig"), // 0xd5
  new Letters("bwigg"), // 0xd6
  new Letters("bwigs"), // 0xd7
  new Letters("bwin"), // 0xd8
  new Letters("bwinj"), // 0xd9
  new Letters("bwinh"), // 0xda
  new Letters("bwid"), // 0xdb
  new Letters("bwil"), // 0xdc
  new Letters("bwilg"), // 0xdd
  new Letters("bwilm"), // 0xde
  new Letters("bwilb"), // 0xdf
  new Letters("bwils"), // 0xe0
  new Letters("bwilt"), // 0xe1
  new Letters("bwilp"), // 0xe2
  new Letters("bwilh"), // 0xe3
  new Letters("bwim"), // 0xe4
  new Letters("bwib"), // 0xe5
  new Letters("bwibs"), // 0xe6
  new Letters("bwis"), // 0xe7
  new Letters("bwiss"), // 0xe8
  new Letters("bwing"), // 0xe9
  new Letters("bwij"), // 0xea
  new Letters("bwic"), // 0xeb
  new Letters("bwik"), // 0xec
  new Letters("bwit"), // 0xed
  new Letters("bwip"), // 0xee
  new Letters("bwih"), // 0xef
  new Letters("byu"), // 0xf0
  new Letters("byug"), // 0xf1
  new Letters("byugg"), // 0xf2
  new Letters("byugs"), // 0xf3
  new Letters("byun"), // 0xf4
  new Letters("byunj"), // 0xf5
  new Letters("byunh"), // 0xf6
  new Letters("byud"), // 0xf7
  new Letters("byul"), // 0xf8
  new Letters("byulg"), // 0xf9
  new Letters("byulm"), // 0xfa
  new Letters("byulb"), // 0xfb
  new Letters("byuls"), // 0xfc
  new Letters("byult"), // 0xfd
  new Letters("byulp"), // 0xfe
  new Letters("byulh") // 0xff
  };
}