/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+BExx (Hangul Syllables for Korean).
 */
final class Xbe extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("byum"), // 0x00
  new Letters("byub"), // 0x01
  new Letters("byubs"), // 0x02
  new Letters("byus"), // 0x03
  new Letters("byuss"), // 0x04
  new Letters("byung"), // 0x05
  new Letters("byuj"), // 0x06
  new Letters("byuc"), // 0x07
  new Letters("byuk"), // 0x08
  new Letters("byut"), // 0x09
  new Letters("byup"), // 0x0a
  new Letters("byuh"), // 0x0b
  new Letters("beu"), // 0x0c
  new Letters("beug"), // 0x0d
  new Letters("beugg"), // 0x0e
  new Letters("beugs"), // 0x0f
  new Letters("beun"), // 0x10
  new Letters("beunj"), // 0x11
  new Letters("beunh"), // 0x12
  new Letters("beud"), // 0x13
  new Letters("beul"), // 0x14
  new Letters("beulg"), // 0x15
  new Letters("beulm"), // 0x16
  new Letters("beulb"), // 0x17
  new Letters("beuls"), // 0x18
  new Letters("beult"), // 0x19
  new Letters("beulp"), // 0x1a
  new Letters("beulh"), // 0x1b
  new Letters("beum"), // 0x1c
  new Letters("beub"), // 0x1d
  new Letters("beubs"), // 0x1e
  new Letters("beus"), // 0x1f
  new Letters("beuss"), // 0x20
  new Letters("beung"), // 0x21
  new Letters("beuj"), // 0x22
  new Letters("beuc"), // 0x23
  new Letters("beuk"), // 0x24
  new Letters("beut"), // 0x25
  new Letters("beup"), // 0x26
  new Letters("beuh"), // 0x27
  new Letters("byi"), // 0x28
  new Letters("byig"), // 0x29
  new Letters("byigg"), // 0x2a
  new Letters("byigs"), // 0x2b
  new Letters("byin"), // 0x2c
  new Letters("byinj"), // 0x2d
  new Letters("byinh"), // 0x2e
  new Letters("byid"), // 0x2f
  new Letters("byil"), // 0x30
  new Letters("byilg"), // 0x31
  new Letters("byilm"), // 0x32
  new Letters("byilb"), // 0x33
  new Letters("byils"), // 0x34
  new Letters("byilt"), // 0x35
  new Letters("byilp"), // 0x36
  new Letters("byilh"), // 0x37
  new Letters("byim"), // 0x38
  new Letters("byib"), // 0x39
  new Letters("byibs"), // 0x3a
  new Letters("byis"), // 0x3b
  new Letters("byiss"), // 0x3c
  new Letters("bying"), // 0x3d
  new Letters("byij"), // 0x3e
  new Letters("byic"), // 0x3f
  new Letters("byik"), // 0x40
  new Letters("byit"), // 0x41
  new Letters("byip"), // 0x42
  new Letters("byih"), // 0x43
  LO_BI, // 0x44
  new Letters("big"), // 0x45
  new Letters("bigg"), // 0x46
  new Letters("bigs"), // 0x47
  new Letters("bin"), // 0x48
  new Letters("binj"), // 0x49
  new Letters("binh"), // 0x4a
  new Letters("bid"), // 0x4b
  new Letters("bil"), // 0x4c
  new Letters("bilg"), // 0x4d
  new Letters("bilm"), // 0x4e
  new Letters("bilb"), // 0x4f
  new Letters("bils"), // 0x50
  new Letters("bilt"), // 0x51
  new Letters("bilp"), // 0x52
  new Letters("bilh"), // 0x53
  new Letters("bim"), // 0x54
  new Letters("bib"), // 0x55
  new Letters("bibs"), // 0x56
  new Letters("bis"), // 0x57
  new Letters("biss"), // 0x58
  new Letters("bing"), // 0x59
  new Letters("bij"), // 0x5a
  new Letters("bic"), // 0x5b
  new Letters("bik"), // 0x5c
  new Letters("bit"), // 0x5d
  new Letters("bip"), // 0x5e
  new Letters("bih"), // 0x5f
  new Letters("bba"), // 0x60
  new Letters("bbag"), // 0x61
  new Letters("bbagg"), // 0x62
  new Letters("bbags"), // 0x63
  new Letters("bban"), // 0x64
  new Letters("bbanj"), // 0x65
  new Letters("bbanh"), // 0x66
  new Letters("bbad"), // 0x67
  new Letters("bbal"), // 0x68
  new Letters("bbalg"), // 0x69
  new Letters("bbalm"), // 0x6a
  new Letters("bbalb"), // 0x6b
  new Letters("bbals"), // 0x6c
  new Letters("bbalt"), // 0x6d
  new Letters("bbalp"), // 0x6e
  new Letters("bbalh"), // 0x6f
  new Letters("bbam"), // 0x70
  new Letters("bbab"), // 0x71
  new Letters("bbabs"), // 0x72
  new Letters("bbas"), // 0x73
  new Letters("bbass"), // 0x74
  new Letters("bbang"), // 0x75
  new Letters("bbaj"), // 0x76
  new Letters("bbac"), // 0x77
  new Letters("bbak"), // 0x78
  new Letters("bbat"), // 0x79
  new Letters("bbap"), // 0x7a
  new Letters("bbah"), // 0x7b
  new Letters("bbae"), // 0x7c
  new Letters("bbaeg"), // 0x7d
  new Letters("bbaegg"), // 0x7e
  new Letters("bbaegs"), // 0x7f
  new Letters("bbaen"), // 0x80
  new Letters("bbaenj"), // 0x81
  new Letters("bbaenh"), // 0x82
  new Letters("bbaed"), // 0x83
  new Letters("bbael"), // 0x84
  new Letters("bbaelg"), // 0x85
  new Letters("bbaelm"), // 0x86
  new Letters("bbaelb"), // 0x87
  new Letters("bbaels"), // 0x88
  new Letters("bbaelt"), // 0x89
  new Letters("bbaelp"), // 0x8a
  new Letters("bbaelh"), // 0x8b
  new Letters("bbaem"), // 0x8c
  new Letters("bbaeb"), // 0x8d
  new Letters("bbaebs"), // 0x8e
  new Letters("bbaes"), // 0x8f
  new Letters("bbaess"), // 0x90
  new Letters("bbaeng"), // 0x91
  new Letters("bbaej"), // 0x92
  new Letters("bbaec"), // 0x93
  new Letters("bbaek"), // 0x94
  new Letters("bbaet"), // 0x95
  new Letters("bbaep"), // 0x96
  new Letters("bbaeh"), // 0x97
  new Letters("bbya"), // 0x98
  new Letters("bbyag"), // 0x99
  new Letters("bbyagg"), // 0x9a
  new Letters("bbyags"), // 0x9b
  new Letters("bbyan"), // 0x9c
  new Letters("bbyanj"), // 0x9d
  new Letters("bbyanh"), // 0x9e
  new Letters("bbyad"), // 0x9f
  new Letters("bbyal"), // 0xa0
  new Letters("bbyalg"), // 0xa1
  new Letters("bbyalm"), // 0xa2
  new Letters("bbyalb"), // 0xa3
  new Letters("bbyals"), // 0xa4
  new Letters("bbyalt"), // 0xa5
  new Letters("bbyalp"), // 0xa6
  new Letters("bbyalh"), // 0xa7
  new Letters("bbyam"), // 0xa8
  new Letters("bbyab"), // 0xa9
  new Letters("bbyabs"), // 0xaa
  new Letters("bbyas"), // 0xab
  new Letters("bbyass"), // 0xac
  new Letters("bbyang"), // 0xad
  new Letters("bbyaj"), // 0xae
  new Letters("bbyac"), // 0xaf
  new Letters("bbyak"), // 0xb0
  new Letters("bbyat"), // 0xb1
  new Letters("bbyap"), // 0xb2
  new Letters("bbyah"), // 0xb3
  new Letters("bbyae"), // 0xb4
  new Letters("bbyaeg"), // 0xb5
  new Letters("bbyaegg"), // 0xb6
  new Letters("bbyaegs"), // 0xb7
  new Letters("bbyaen"), // 0xb8
  new Letters("bbyaenj"), // 0xb9
  new Letters("bbyaenh"), // 0xba
  new Letters("bbyaed"), // 0xbb
  new Letters("bbyael"), // 0xbc
  new Letters("bbyaelg"), // 0xbd
  new Letters("bbyaelm"), // 0xbe
  new Letters("bbyaelb"), // 0xbf
  new Letters("bbyaels"), // 0xc0
  new Letters("bbyaelt"), // 0xc1
  new Letters("bbyaelp"), // 0xc2
  new Letters("bbyaelh"), // 0xc3
  new Letters("bbyaem"), // 0xc4
  new Letters("bbyaeb"), // 0xc5
  new Letters("bbyaebs"), // 0xc6
  new Letters("bbyaes"), // 0xc7
  new Letters("bbyaess"), // 0xc8
  new Letters("bbyaeng"), // 0xc9
  new Letters("bbyaej"), // 0xca
  new Letters("bbyaec"), // 0xcb
  new Letters("bbyaek"), // 0xcc
  new Letters("bbyaet"), // 0xcd
  new Letters("bbyaep"), // 0xce
  new Letters("bbyaeh"), // 0xcf
  new Letters("bbeo"), // 0xd0
  new Letters("bbeog"), // 0xd1
  new Letters("bbeogg"), // 0xd2
  new Letters("bbeogs"), // 0xd3
  new Letters("bbeon"), // 0xd4
  new Letters("bbeonj"), // 0xd5
  new Letters("bbeonh"), // 0xd6
  new Letters("bbeod"), // 0xd7
  new Letters("bbeol"), // 0xd8
  new Letters("bbeolg"), // 0xd9
  new Letters("bbeolm"), // 0xda
  new Letters("bbeolb"), // 0xdb
  new Letters("bbeols"), // 0xdc
  new Letters("bbeolt"), // 0xdd
  new Letters("bbeolp"), // 0xde
  new Letters("bbeolh"), // 0xdf
  new Letters("bbeom"), // 0xe0
  new Letters("bbeob"), // 0xe1
  new Letters("bbeobs"), // 0xe2
  new Letters("bbeos"), // 0xe3
  new Letters("bbeoss"), // 0xe4
  new Letters("bbeong"), // 0xe5
  new Letters("bbeoj"), // 0xe6
  new Letters("bbeoc"), // 0xe7
  new Letters("bbeok"), // 0xe8
  new Letters("bbeot"), // 0xe9
  new Letters("bbeop"), // 0xea
  new Letters("bbeoh"), // 0xeb
  new Letters("bbe"), // 0xec
  new Letters("bbeg"), // 0xed
  new Letters("bbegg"), // 0xee
  new Letters("bbegs"), // 0xef
  new Letters("bben"), // 0xf0
  new Letters("bbenj"), // 0xf1
  new Letters("bbenh"), // 0xf2
  new Letters("bbed"), // 0xf3
  new Letters("bbel"), // 0xf4
  new Letters("bbelg"), // 0xf5
  new Letters("bbelm"), // 0xf6
  new Letters("bbelb"), // 0xf7
  new Letters("bbels"), // 0xf8
  new Letters("bbelt"), // 0xf9
  new Letters("bbelp"), // 0xfa
  new Letters("bbelh"), // 0xfb
  new Letters("bbem"), // 0xfc
  new Letters("bbeb"), // 0xfd
  new Letters("bbebs"), // 0xfe
  new Letters("bbes") // 0xff
  };
}