/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+C0xx (Hangul Syllables for Korean).
 */
final class Xc0 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("bbweok"), // 0x00
  new Letters("bbweot"), // 0x01
  new Letters("bbweop"), // 0x02
  new Letters("bbweoh"), // 0x03
  new Letters("bbwe"), // 0x04
  new Letters("bbweg"), // 0x05
  new Letters("bbwegg"), // 0x06
  new Letters("bbwegs"), // 0x07
  new Letters("bbwen"), // 0x08
  new Letters("bbwenj"), // 0x09
  new Letters("bbwenh"), // 0x0a
  new Letters("bbwed"), // 0x0b
  new Letters("bbwel"), // 0x0c
  new Letters("bbwelg"), // 0x0d
  new Letters("bbwelm"), // 0x0e
  new Letters("bbwelb"), // 0x0f
  new Letters("bbwels"), // 0x10
  new Letters("bbwelt"), // 0x11
  new Letters("bbwelp"), // 0x12
  new Letters("bbwelh"), // 0x13
  new Letters("bbwem"), // 0x14
  new Letters("bbweb"), // 0x15
  new Letters("bbwebs"), // 0x16
  new Letters("bbwes"), // 0x17
  new Letters("bbwess"), // 0x18
  new Letters("bbweng"), // 0x19
  new Letters("bbwej"), // 0x1a
  new Letters("bbwec"), // 0x1b
  new Letters("bbwek"), // 0x1c
  new Letters("bbwet"), // 0x1d
  new Letters("bbwep"), // 0x1e
  new Letters("bbweh"), // 0x1f
  new Letters("bbwi"), // 0x20
  new Letters("bbwig"), // 0x21
  new Letters("bbwigg"), // 0x22
  new Letters("bbwigs"), // 0x23
  new Letters("bbwin"), // 0x24
  new Letters("bbwinj"), // 0x25
  new Letters("bbwinh"), // 0x26
  new Letters("bbwid"), // 0x27
  new Letters("bbwil"), // 0x28
  new Letters("bbwilg"), // 0x29
  new Letters("bbwilm"), // 0x2a
  new Letters("bbwilb"), // 0x2b
  new Letters("bbwils"), // 0x2c
  new Letters("bbwilt"), // 0x2d
  new Letters("bbwilp"), // 0x2e
  new Letters("bbwilh"), // 0x2f
  new Letters("bbwim"), // 0x30
  new Letters("bbwib"), // 0x31
  new Letters("bbwibs"), // 0x32
  new Letters("bbwis"), // 0x33
  new Letters("bbwiss"), // 0x34
  new Letters("bbwing"), // 0x35
  new Letters("bbwij"), // 0x36
  new Letters("bbwic"), // 0x37
  new Letters("bbwik"), // 0x38
  new Letters("bbwit"), // 0x39
  new Letters("bbwip"), // 0x3a
  new Letters("bbwih"), // 0x3b
  new Letters("bbyu"), // 0x3c
  new Letters("bbyug"), // 0x3d
  new Letters("bbyugg"), // 0x3e
  new Letters("bbyugs"), // 0x3f
  new Letters("bbyun"), // 0x40
  new Letters("bbyunj"), // 0x41
  new Letters("bbyunh"), // 0x42
  new Letters("bbyud"), // 0x43
  new Letters("bbyul"), // 0x44
  new Letters("bbyulg"), // 0x45
  new Letters("bbyulm"), // 0x46
  new Letters("bbyulb"), // 0x47
  new Letters("bbyuls"), // 0x48
  new Letters("bbyult"), // 0x49
  new Letters("bbyulp"), // 0x4a
  new Letters("bbyulh"), // 0x4b
  new Letters("bbyum"), // 0x4c
  new Letters("bbyub"), // 0x4d
  new Letters("bbyubs"), // 0x4e
  new Letters("bbyus"), // 0x4f
  new Letters("bbyuss"), // 0x50
  new Letters("bbyung"), // 0x51
  new Letters("bbyuj"), // 0x52
  new Letters("bbyuc"), // 0x53
  new Letters("bbyuk"), // 0x54
  new Letters("bbyut"), // 0x55
  new Letters("bbyup"), // 0x56
  new Letters("bbyuh"), // 0x57
  new Letters("bbeu"), // 0x58
  new Letters("bbeug"), // 0x59
  new Letters("bbeugg"), // 0x5a
  new Letters("bbeugs"), // 0x5b
  new Letters("bbeun"), // 0x5c
  new Letters("bbeunj"), // 0x5d
  new Letters("bbeunh"), // 0x5e
  new Letters("bbeud"), // 0x5f
  new Letters("bbeul"), // 0x60
  new Letters("bbeulg"), // 0x61
  new Letters("bbeulm"), // 0x62
  new Letters("bbeulb"), // 0x63
  new Letters("bbeuls"), // 0x64
  new Letters("bbeult"), // 0x65
  new Letters("bbeulp"), // 0x66
  new Letters("bbeulh"), // 0x67
  new Letters("bbeum"), // 0x68
  new Letters("bbeub"), // 0x69
  new Letters("bbeubs"), // 0x6a
  new Letters("bbeus"), // 0x6b
  new Letters("bbeuss"), // 0x6c
  new Letters("bbeung"), // 0x6d
  new Letters("bbeuj"), // 0x6e
  new Letters("bbeuc"), // 0x6f
  new Letters("bbeuk"), // 0x70
  new Letters("bbeut"), // 0x71
  new Letters("bbeup"), // 0x72
  new Letters("bbeuh"), // 0x73
  new Letters("bbyi"), // 0x74
  new Letters("bbyig"), // 0x75
  new Letters("bbyigg"), // 0x76
  new Letters("bbyigs"), // 0x77
  new Letters("bbyin"), // 0x78
  new Letters("bbyinj"), // 0x79
  new Letters("bbyinh"), // 0x7a
  new Letters("bbyid"), // 0x7b
  new Letters("bbyil"), // 0x7c
  new Letters("bbyilg"), // 0x7d
  new Letters("bbyilm"), // 0x7e
  new Letters("bbyilb"), // 0x7f
  new Letters("bbyils"), // 0x80
  new Letters("bbyilt"), // 0x81
  new Letters("bbyilp"), // 0x82
  new Letters("bbyilh"), // 0x83
  new Letters("bbyim"), // 0x84
  new Letters("bbyib"), // 0x85
  new Letters("bbyibs"), // 0x86
  new Letters("bbyis"), // 0x87
  new Letters("bbyiss"), // 0x88
  new Letters("bbying"), // 0x89
  new Letters("bbyij"), // 0x8a
  new Letters("bbyic"), // 0x8b
  new Letters("bbyik"), // 0x8c
  new Letters("bbyit"), // 0x8d
  new Letters("bbyip"), // 0x8e
  new Letters("bbyih"), // 0x8f
  new Letters("bbi"), // 0x90
  new Letters("bbig"), // 0x91
  new Letters("bbigg"), // 0x92
  new Letters("bbigs"), // 0x93
  new Letters("bbin"), // 0x94
  new Letters("bbinj"), // 0x95
  new Letters("bbinh"), // 0x96
  new Letters("bbid"), // 0x97
  new Letters("bbil"), // 0x98
  new Letters("bbilg"), // 0x99
  new Letters("bbilm"), // 0x9a
  new Letters("bbilb"), // 0x9b
  new Letters("bbils"), // 0x9c
  new Letters("bbilt"), // 0x9d
  new Letters("bbilp"), // 0x9e
  new Letters("bbilh"), // 0x9f
  new Letters("bbim"), // 0xa0
  new Letters("bbib"), // 0xa1
  new Letters("bbibs"), // 0xa2
  new Letters("bbis"), // 0xa3
  new Letters("bbiss"), // 0xa4
  new Letters("bbing"), // 0xa5
  new Letters("bbij"), // 0xa6
  new Letters("bbic"), // 0xa7
  new Letters("bbik"), // 0xa8
  new Letters("bbit"), // 0xa9
  new Letters("bbip"), // 0xaa
  new Letters("bbih"), // 0xab
  LO_SA, // 0xac
  new Letters("sag"), // 0xad
  new Letters("sagg"), // 0xae
  new Letters("sags"), // 0xaf
  new Letters("san"), // 0xb0
  new Letters("sanj"), // 0xb1
  new Letters("sanh"), // 0xb2
  new Letters("sad"), // 0xb3
  new Letters("sal"), // 0xb4
  new Letters("salg"), // 0xb5
  new Letters("salm"), // 0xb6
  new Letters("salb"), // 0xb7
  new Letters("sals"), // 0xb8
  new Letters("salt"), // 0xb9
  new Letters("salp"), // 0xba
  new Letters("salh"), // 0xbb
  new Letters("sam"), // 0xbc
  new Letters("sab"), // 0xbd
  new Letters("sabs"), // 0xbe
  new Letters("sas"), // 0xbf
  new Letters("sass"), // 0xc0
  new Letters("sang"), // 0xc1
  new Letters("saj"), // 0xc2
  new Letters("sac"), // 0xc3
  new Letters("sak"), // 0xc4
  new Letters("sat"), // 0xc5
  new Letters("sap"), // 0xc6
  new Letters("sah"), // 0xc7
  new Letters("sae"), // 0xc8
  new Letters("saeg"), // 0xc9
  new Letters("saegg"), // 0xca
  new Letters("saegs"), // 0xcb
  new Letters("saen"), // 0xcc
  new Letters("saenj"), // 0xcd
  new Letters("saenh"), // 0xce
  new Letters("saed"), // 0xcf
  new Letters("sael"), // 0xd0
  new Letters("saelg"), // 0xd1
  new Letters("saelm"), // 0xd2
  new Letters("saelb"), // 0xd3
  new Letters("saels"), // 0xd4
  new Letters("saelt"), // 0xd5
  new Letters("saelp"), // 0xd6
  new Letters("saelh"), // 0xd7
  new Letters("saem"), // 0xd8
  new Letters("saeb"), // 0xd9
  new Letters("saebs"), // 0xda
  new Letters("saes"), // 0xdb
  new Letters("saess"), // 0xdc
  new Letters("saeng"), // 0xdd
  new Letters("saej"), // 0xde
  new Letters("saec"), // 0xdf
  new Letters("saek"), // 0xe0
  new Letters("saet"), // 0xe1
  new Letters("saep"), // 0xe2
  new Letters("saeh"), // 0xe3
  new Letters("sya"), // 0xe4
  new Letters("syag"), // 0xe5
  new Letters("syagg"), // 0xe6
  new Letters("syags"), // 0xe7
  new Letters("syan"), // 0xe8
  new Letters("syanj"), // 0xe9
  new Letters("syanh"), // 0xea
  new Letters("syad"), // 0xeb
  new Letters("syal"), // 0xec
  new Letters("syalg"), // 0xed
  new Letters("syalm"), // 0xee
  new Letters("syalb"), // 0xef
  new Letters("syals"), // 0xf0
  new Letters("syalt"), // 0xf1
  new Letters("syalp"), // 0xf2
  new Letters("syalh"), // 0xf3
  new Letters("syam"), // 0xf4
  new Letters("syab"), // 0xf5
  new Letters("syabs"), // 0xf6
  new Letters("syas"), // 0xf7
  new Letters("syass"), // 0xf8
  new Letters("syang"), // 0xf9
  new Letters("syaj"), // 0xfa
  new Letters("syac"), // 0xfb
  new Letters("syak"), // 0xfc
  new Letters("syat"), // 0xfd
  new Letters("syap"), // 0xfe
  new Letters("syah") // 0xff
  };
}