/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+C1xx (Hangul Syllables for Korean).
 */
final class Xc1 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("syae"), // 0x00
  new Letters("syaeg"), // 0x01
  new Letters("syaegg"), // 0x02
  new Letters("syaegs"), // 0x03
  new Letters("syaen"), // 0x04
  new Letters("syaenj"), // 0x05
  new Letters("syaenh"), // 0x06
  new Letters("syaed"), // 0x07
  new Letters("syael"), // 0x08
  new Letters("syaelg"), // 0x09
  new Letters("syaelm"), // 0x0a
  new Letters("syaelb"), // 0x0b
  new Letters("syaels"), // 0x0c
  new Letters("syaelt"), // 0x0d
  new Letters("syaelp"), // 0x0e
  new Letters("syaelh"), // 0x0f
  new Letters("syaem"), // 0x10
  new Letters("syaeb"), // 0x11
  new Letters("syaebs"), // 0x12
  new Letters("syaes"), // 0x13
  new Letters("syaess"), // 0x14
  new Letters("syaeng"), // 0x15
  new Letters("syaej"), // 0x16
  new Letters("syaec"), // 0x17
  new Letters("syaek"), // 0x18
  new Letters("syaet"), // 0x19
  new Letters("syaep"), // 0x1a
  new Letters("syaeh"), // 0x1b
  new Letters("seo"), // 0x1c
  new Letters("seog"), // 0x1d
  new Letters("seogg"), // 0x1e
  new Letters("seogs"), // 0x1f
  new Letters("seon"), // 0x20
  new Letters("seonj"), // 0x21
  new Letters("seonh"), // 0x22
  new Letters("seod"), // 0x23
  new Letters("seol"), // 0x24
  new Letters("seolg"), // 0x25
  new Letters("seolm"), // 0x26
  new Letters("seolb"), // 0x27
  new Letters("seols"), // 0x28
  new Letters("seolt"), // 0x29
  new Letters("seolp"), // 0x2a
  new Letters("seolh"), // 0x2b
  new Letters("seom"), // 0x2c
  new Letters("seob"), // 0x2d
  new Letters("seobs"), // 0x2e
  new Letters("seos"), // 0x2f
  new Letters("seoss"), // 0x30
  new Letters("seong"), // 0x31
  new Letters("seoj"), // 0x32
  new Letters("seoc"), // 0x33
  new Letters("seok"), // 0x34
  new Letters("seot"), // 0x35
  new Letters("seop"), // 0x36
  new Letters("seoh"), // 0x37
  LO_SE, // 0x38
  new Letters("seg"), // 0x39
  new Letters("segg"), // 0x3a
  new Letters("segs"), // 0x3b
  new Letters("sen"), // 0x3c
  new Letters("senj"), // 0x3d
  new Letters("senh"), // 0x3e
  new Letters("sed"), // 0x3f
  new Letters("sel"), // 0x40
  new Letters("selg"), // 0x41
  new Letters("selm"), // 0x42
  new Letters("selb"), // 0x43
  new Letters("sels"), // 0x44
  new Letters("selt"), // 0x45
  new Letters("selp"), // 0x46
  new Letters("selh"), // 0x47
  new Letters("sem"), // 0x48
  new Letters("seb"), // 0x49
  new Letters("sebs"), // 0x4a
  new Letters("ses"), // 0x4b
  new Letters("sess"), // 0x4c
  new Letters("seng"), // 0x4d
  new Letters("sej"), // 0x4e
  new Letters("sec"), // 0x4f
  new Letters("sek"), // 0x50
  new Letters("set"), // 0x51
  new Letters("sep"), // 0x52
  new Letters("seh"), // 0x53
  new Letters("syeo"), // 0x54
  new Letters("syeog"), // 0x55
  new Letters("syeogg"), // 0x56
  new Letters("syeogs"), // 0x57
  new Letters("syeon"), // 0x58
  new Letters("syeonj"), // 0x59
  new Letters("syeonh"), // 0x5a
  new Letters("syeod"), // 0x5b
  new Letters("syeol"), // 0x5c
  new Letters("syeolg"), // 0x5d
  new Letters("syeolm"), // 0x5e
  new Letters("syeolb"), // 0x5f
  new Letters("syeols"), // 0x60
  new Letters("syeolt"), // 0x61
  new Letters("syeolp"), // 0x62
  new Letters("syeolh"), // 0x63
  new Letters("syeom"), // 0x64
  new Letters("syeob"), // 0x65
  new Letters("syeobs"), // 0x66
  new Letters("syeos"), // 0x67
  new Letters("syeoss"), // 0x68
  new Letters("syeong"), // 0x69
  new Letters("syeoj"), // 0x6a
  new Letters("syeoc"), // 0x6b
  new Letters("syeok"), // 0x6c
  new Letters("syeot"), // 0x6d
  new Letters("syeop"), // 0x6e
  new Letters("syeoh"), // 0x6f
  new Letters("sye"), // 0x70
  new Letters("syeg"), // 0x71
  new Letters("syegg"), // 0x72
  new Letters("syegs"), // 0x73
  new Letters("syen"), // 0x74
  new Letters("syenj"), // 0x75
  new Letters("syenh"), // 0x76
  new Letters("syed"), // 0x77
  new Letters("syel"), // 0x78
  new Letters("syelg"), // 0x79
  new Letters("syelm"), // 0x7a
  new Letters("syelb"), // 0x7b
  new Letters("syels"), // 0x7c
  new Letters("syelt"), // 0x7d
  new Letters("syelp"), // 0x7e
  new Letters("syelh"), // 0x7f
  new Letters("syem"), // 0x80
  new Letters("syeb"), // 0x81
  new Letters("syebs"), // 0x82
  new Letters("syes"), // 0x83
  new Letters("syess"), // 0x84
  new Letters("syeng"), // 0x85
  new Letters("syej"), // 0x86
  new Letters("syec"), // 0x87
  new Letters("syek"), // 0x88
  new Letters("syet"), // 0x89
  new Letters("syep"), // 0x8a
  new Letters("syeh"), // 0x8b
  LO_SO, // 0x8c
  new Letters("sog"), // 0x8d
  new Letters("sogg"), // 0x8e
  new Letters("sogs"), // 0x8f
  new Letters("son"), // 0x90
  new Letters("sonj"), // 0x91
  new Letters("sonh"), // 0x92
  new Letters("sod"), // 0x93
  new Letters("sol"), // 0x94
  new Letters("solg"), // 0x95
  new Letters("solm"), // 0x96
  new Letters("solb"), // 0x97
  new Letters("sols"), // 0x98
  new Letters("solt"), // 0x99
  new Letters("solp"), // 0x9a
  new Letters("solh"), // 0x9b
  new Letters("som"), // 0x9c
  new Letters("sob"), // 0x9d
  new Letters("sobs"), // 0x9e
  new Letters("sos"), // 0x9f
  new Letters("soss"), // 0xa0
  new Letters("song"), // 0xa1
  new Letters("soj"), // 0xa2
  new Letters("soc"), // 0xa3
  new Letters("sok"), // 0xa4
  new Letters("sot"), // 0xa5
  new Letters("sop"), // 0xa6
  new Letters("soh"), // 0xa7
  new Letters("swa"), // 0xa8
  new Letters("swag"), // 0xa9
  new Letters("swagg"), // 0xaa
  new Letters("swags"), // 0xab
  new Letters("swan"), // 0xac
  new Letters("swanj"), // 0xad
  new Letters("swanh"), // 0xae
  new Letters("swad"), // 0xaf
  new Letters("swal"), // 0xb0
  new Letters("swalg"), // 0xb1
  new Letters("swalm"), // 0xb2
  new Letters("swalb"), // 0xb3
  new Letters("swals"), // 0xb4
  new Letters("swalt"), // 0xb5
  new Letters("swalp"), // 0xb6
  new Letters("swalh"), // 0xb7
  new Letters("swam"), // 0xb8
  new Letters("swab"), // 0xb9
  new Letters("swabs"), // 0xba
  new Letters("swas"), // 0xbb
  new Letters("swass"), // 0xbc
  new Letters("swang"), // 0xbd
  new Letters("swaj"), // 0xbe
  new Letters("swac"), // 0xbf
  new Letters("swak"), // 0xc0
  new Letters("swat"), // 0xc1
  new Letters("swap"), // 0xc2
  new Letters("swah"), // 0xc3
  new Letters("swae"), // 0xc4
  new Letters("swaeg"), // 0xc5
  new Letters("swaegg"), // 0xc6
  new Letters("swaegs"), // 0xc7
  new Letters("swaen"), // 0xc8
  new Letters("swaenj"), // 0xc9
  new Letters("swaenh"), // 0xca
  new Letters("swaed"), // 0xcb
  new Letters("swael"), // 0xcc
  new Letters("swaelg"), // 0xcd
  new Letters("swaelm"), // 0xce
  new Letters("swaelb"), // 0xcf
  new Letters("swaels"), // 0xd0
  new Letters("swaelt"), // 0xd1
  new Letters("swaelp"), // 0xd2
  new Letters("swaelh"), // 0xd3
  new Letters("swaem"), // 0xd4
  new Letters("swaeb"), // 0xd5
  new Letters("swaebs"), // 0xd6
  new Letters("swaes"), // 0xd7
  new Letters("swaess"), // 0xd8
  new Letters("swaeng"), // 0xd9
  new Letters("swaej"), // 0xda
  new Letters("swaec"), // 0xdb
  new Letters("swaek"), // 0xdc
  new Letters("swaet"), // 0xdd
  new Letters("swaep"), // 0xde
  new Letters("swaeh"), // 0xdf
  new Letters("soe"), // 0xe0
  new Letters("soeg"), // 0xe1
  new Letters("soegg"), // 0xe2
  new Letters("soegs"), // 0xe3
  new Letters("soen"), // 0xe4
  new Letters("soenj"), // 0xe5
  new Letters("soenh"), // 0xe6
  new Letters("soed"), // 0xe7
  new Letters("soel"), // 0xe8
  new Letters("soelg"), // 0xe9
  new Letters("soelm"), // 0xea
  new Letters("soelb"), // 0xeb
  new Letters("soels"), // 0xec
  new Letters("soelt"), // 0xed
  new Letters("soelp"), // 0xee
  new Letters("soelh"), // 0xef
  new Letters("soem"), // 0xf0
  new Letters("soeb"), // 0xf1
  new Letters("soebs"), // 0xf2
  new Letters("soes"), // 0xf3
  new Letters("soess"), // 0xf4
  new Letters("soeng"), // 0xf5
  new Letters("soej"), // 0xf6
  new Letters("soec"), // 0xf7
  new Letters("soek"), // 0xf8
  new Letters("soet"), // 0xf9
  new Letters("soep"), // 0xfa
  new Letters("soeh"), // 0xfb
  new Letters("syo"), // 0xfc
  new Letters("syog"), // 0xfd
  new Letters("syogg"), // 0xfe
  new Letters("syogs") // 0xff
  };
}