/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+C2xx (Hangul Syllables for Korean).
 */
final class Xc2 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("syon"), // 0x00
  new Letters("syonj"), // 0x01
  new Letters("syonh"), // 0x02
  new Letters("syod"), // 0x03
  new Letters("syol"), // 0x04
  new Letters("syolg"), // 0x05
  new Letters("syolm"), // 0x06
  new Letters("syolb"), // 0x07
  new Letters("syols"), // 0x08
  new Letters("syolt"), // 0x09
  new Letters("syolp"), // 0x0a
  new Letters("syolh"), // 0x0b
  new Letters("syom"), // 0x0c
  new Letters("syob"), // 0x0d
  new Letters("syobs"), // 0x0e
  new Letters("syos"), // 0x0f
  new Letters("syoss"), // 0x10
  new Letters("syong"), // 0x11
  new Letters("syoj"), // 0x12
  new Letters("syoc"), // 0x13
  new Letters("syok"), // 0x14
  new Letters("syot"), // 0x15
  new Letters("syop"), // 0x16
  new Letters("syoh"), // 0x17
  LO_SU, // 0x18
  new Letters("sug"), // 0x19
  new Letters("sugg"), // 0x1a
  new Letters("sugs"), // 0x1b
  new Letters("sun"), // 0x1c
  new Letters("sunj"), // 0x1d
  new Letters("sunh"), // 0x1e
  new Letters("sud"), // 0x1f
  new Letters("sul"), // 0x20
  new Letters("sulg"), // 0x21
  new Letters("sulm"), // 0x22
  new Letters("sulb"), // 0x23
  new Letters("suls"), // 0x24
  new Letters("sult"), // 0x25
  new Letters("sulp"), // 0x26
  new Letters("sulh"), // 0x27
  new Letters("sum"), // 0x28
  new Letters("sub"), // 0x29
  new Letters("subs"), // 0x2a
  new Letters("sus"), // 0x2b
  new Letters("suss"), // 0x2c
  new Letters("sung"), // 0x2d
  new Letters("suj"), // 0x2e
  new Letters("suc"), // 0x2f
  new Letters("suk"), // 0x30
  new Letters("sut"), // 0x31
  new Letters("sup"), // 0x32
  new Letters("suh"), // 0x33
  new Letters("sweo"), // 0x34
  new Letters("sweog"), // 0x35
  new Letters("sweogg"), // 0x36
  new Letters("sweogs"), // 0x37
  new Letters("sweon"), // 0x38
  new Letters("sweonj"), // 0x39
  new Letters("sweonh"), // 0x3a
  new Letters("sweod"), // 0x3b
  new Letters("sweol"), // 0x3c
  new Letters("sweolg"), // 0x3d
  new Letters("sweolm"), // 0x3e
  new Letters("sweolb"), // 0x3f
  new Letters("sweols"), // 0x40
  new Letters("sweolt"), // 0x41
  new Letters("sweolp"), // 0x42
  new Letters("sweolh"), // 0x43
  new Letters("sweom"), // 0x44
  new Letters("sweob"), // 0x45
  new Letters("sweobs"), // 0x46
  new Letters("sweos"), // 0x47
  new Letters("sweoss"), // 0x48
  new Letters("sweong"), // 0x49
  new Letters("sweoj"), // 0x4a
  new Letters("sweoc"), // 0x4b
  new Letters("sweok"), // 0x4c
  new Letters("sweot"), // 0x4d
  new Letters("sweop"), // 0x4e
  new Letters("sweoh"), // 0x4f
  new Letters("swe"), // 0x50
  new Letters("sweg"), // 0x51
  new Letters("swegg"), // 0x52
  new Letters("swegs"), // 0x53
  new Letters("swen"), // 0x54
  new Letters("swenj"), // 0x55
  new Letters("swenh"), // 0x56
  new Letters("swed"), // 0x57
  new Letters("swel"), // 0x58
  new Letters("swelg"), // 0x59
  new Letters("swelm"), // 0x5a
  new Letters("swelb"), // 0x5b
  new Letters("swels"), // 0x5c
  new Letters("swelt"), // 0x5d
  new Letters("swelp"), // 0x5e
  new Letters("swelh"), // 0x5f
  new Letters("swem"), // 0x60
  new Letters("sweb"), // 0x61
  new Letters("swebs"), // 0x62
  new Letters("swes"), // 0x63
  new Letters("swess"), // 0x64
  new Letters("sweng"), // 0x65
  new Letters("swej"), // 0x66
  new Letters("swec"), // 0x67
  new Letters("swek"), // 0x68
  new Letters("swet"), // 0x69
  new Letters("swep"), // 0x6a
  new Letters("sweh"), // 0x6b
  new Letters("swi"), // 0x6c
  new Letters("swig"), // 0x6d
  new Letters("swigg"), // 0x6e
  new Letters("swigs"), // 0x6f
  new Letters("swin"), // 0x70
  new Letters("swinj"), // 0x71
  new Letters("swinh"), // 0x72
  new Letters("swid"), // 0x73
  new Letters("swil"), // 0x74
  new Letters("swilg"), // 0x75
  new Letters("swilm"), // 0x76
  new Letters("swilb"), // 0x77
  new Letters("swils"), // 0x78
  new Letters("swilt"), // 0x79
  new Letters("swilp"), // 0x7a
  new Letters("swilh"), // 0x7b
  new Letters("swim"), // 0x7c
  new Letters("swib"), // 0x7d
  new Letters("swibs"), // 0x7e
  new Letters("swis"), // 0x7f
  new Letters("swiss"), // 0x80
  new Letters("swing"), // 0x81
  new Letters("swij"), // 0x82
  new Letters("swic"), // 0x83
  new Letters("swik"), // 0x84
  new Letters("swit"), // 0x85
  new Letters("swip"), // 0x86
  new Letters("swih"), // 0x87
  new Letters("syu"), // 0x88
  new Letters("syug"), // 0x89
  new Letters("syugg"), // 0x8a
  new Letters("syugs"), // 0x8b
  new Letters("syun"), // 0x8c
  new Letters("syunj"), // 0x8d
  new Letters("syunh"), // 0x8e
  new Letters("syud"), // 0x8f
  new Letters("syul"), // 0x90
  new Letters("syulg"), // 0x91
  new Letters("syulm"), // 0x92
  new Letters("syulb"), // 0x93
  new Letters("syuls"), // 0x94
  new Letters("syult"), // 0x95
  new Letters("syulp"), // 0x96
  new Letters("syulh"), // 0x97
  new Letters("syum"), // 0x98
  new Letters("syub"), // 0x99
  new Letters("syubs"), // 0x9a
  new Letters("syus"), // 0x9b
  new Letters("syuss"), // 0x9c
  new Letters("syung"), // 0x9d
  new Letters("syuj"), // 0x9e
  new Letters("syuc"), // 0x9f
  new Letters("syuk"), // 0xa0
  new Letters("syut"), // 0xa1
  new Letters("syup"), // 0xa2
  new Letters("syuh"), // 0xa3
  new Letters("seu"), // 0xa4
  new Letters("seug"), // 0xa5
  new Letters("seugg"), // 0xa6
  new Letters("seugs"), // 0xa7
  new Letters("seun"), // 0xa8
  new Letters("seunj"), // 0xa9
  new Letters("seunh"), // 0xaa
  new Letters("seud"), // 0xab
  new Letters("seul"), // 0xac
  new Letters("seulg"), // 0xad
  new Letters("seulm"), // 0xae
  new Letters("seulb"), // 0xaf
  new Letters("seuls"), // 0xb0
  new Letters("seult"), // 0xb1
  new Letters("seulp"), // 0xb2
  new Letters("seulh"), // 0xb3
  new Letters("seum"), // 0xb4
  new Letters("seub"), // 0xb5
  new Letters("seubs"), // 0xb6
  new Letters("seus"), // 0xb7
  new Letters("seuss"), // 0xb8
  new Letters("seung"), // 0xb9
  new Letters("seuj"), // 0xba
  new Letters("seuc"), // 0xbb
  new Letters("seuk"), // 0xbc
  new Letters("seut"), // 0xbd
  new Letters("seup"), // 0xbe
  new Letters("seuh"), // 0xbf
  new Letters("syi"), // 0xc0
  new Letters("syig"), // 0xc1
  new Letters("syigg"), // 0xc2
  new Letters("syigs"), // 0xc3
  new Letters("syin"), // 0xc4
  new Letters("syinj"), // 0xc5
  new Letters("syinh"), // 0xc6
  new Letters("syid"), // 0xc7
  new Letters("syil"), // 0xc8
  new Letters("syilg"), // 0xc9
  new Letters("syilm"), // 0xca
  new Letters("syilb"), // 0xcb
  new Letters("syils"), // 0xcc
  new Letters("syilt"), // 0xcd
  new Letters("syilp"), // 0xce
  new Letters("syilh"), // 0xcf
  new Letters("syim"), // 0xd0
  new Letters("syib"), // 0xd1
  new Letters("syibs"), // 0xd2
  new Letters("syis"), // 0xd3
  new Letters("syiss"), // 0xd4
  new Letters("sying"), // 0xd5
  new Letters("syij"), // 0xd6
  new Letters("syic"), // 0xd7
  new Letters("syik"), // 0xd8
  new Letters("syit"), // 0xd9
  new Letters("syip"), // 0xda
  new Letters("syih"), // 0xdb
  LO_SI, // 0xdc
  new Letters("sig"), // 0xdd
  new Letters("sigg"), // 0xde
  new Letters("sigs"), // 0xdf
  new Letters("sin"), // 0xe0
  new Letters("sinj"), // 0xe1
  new Letters("sinh"), // 0xe2
  new Letters("sid"), // 0xe3
  new Letters("sil"), // 0xe4
  new Letters("silg"), // 0xe5
  new Letters("silm"), // 0xe6
  new Letters("silb"), // 0xe7
  new Letters("sils"), // 0xe8
  new Letters("silt"), // 0xe9
  new Letters("silp"), // 0xea
  new Letters("silh"), // 0xeb
  new Letters("sim"), // 0xec
  new Letters("sib"), // 0xed
  new Letters("sibs"), // 0xee
  new Letters("sis"), // 0xef
  new Letters("siss"), // 0xf0
  new Letters("sing"), // 0xf1
  new Letters("sij"), // 0xf2
  new Letters("sic"), // 0xf3
  new Letters("sik"), // 0xf4
  new Letters("sit"), // 0xf5
  new Letters("sip"), // 0xf6
  new Letters("sih"), // 0xf7
  new Letters("ssa"), // 0xf8
  new Letters("ssag"), // 0xf9
  new Letters("ssagg"), // 0xfa
  new Letters("ssags"), // 0xfb
  new Letters("ssan"), // 0xfc
  new Letters("ssanj"), // 0xfd
  new Letters("ssanh"), // 0xfe
  new Letters("ssad") // 0xff
  };
}