/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+C3xx (Hangul Syllables for Korean).
 */
final class Xc3 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("ssal"), // 0x00
  new Letters("ssalg"), // 0x01
  new Letters("ssalm"), // 0x02
  new Letters("ssalb"), // 0x03
  new Letters("ssals"), // 0x04
  new Letters("ssalt"), // 0x05
  new Letters("ssalp"), // 0x06
  new Letters("ssalh"), // 0x07
  new Letters("ssam"), // 0x08
  new Letters("ssab"), // 0x09
  new Letters("ssabs"), // 0x0a
  new Letters("ssas"), // 0x0b
  new Letters("ssass"), // 0x0c
  new Letters("ssang"), // 0x0d
  new Letters("ssaj"), // 0x0e
  new Letters("ssac"), // 0x0f
  new Letters("ssak"), // 0x10
  new Letters("ssat"), // 0x11
  new Letters("ssap"), // 0x12
  new Letters("ssah"), // 0x13
  new Letters("ssae"), // 0x14
  new Letters("ssaeg"), // 0x15
  new Letters("ssaegg"), // 0x16
  new Letters("ssaegs"), // 0x17
  new Letters("ssaen"), // 0x18
  new Letters("ssaenj"), // 0x19
  new Letters("ssaenh"), // 0x1a
  new Letters("ssaed"), // 0x1b
  new Letters("ssael"), // 0x1c
  new Letters("ssaelg"), // 0x1d
  new Letters("ssaelm"), // 0x1e
  new Letters("ssaelb"), // 0x1f
  new Letters("ssaels"), // 0x20
  new Letters("ssaelt"), // 0x21
  new Letters("ssaelp"), // 0x22
  new Letters("ssaelh"), // 0x23
  new Letters("ssaem"), // 0x24
  new Letters("ssaeb"), // 0x25
  new Letters("ssaebs"), // 0x26
  new Letters("ssaes"), // 0x27
  new Letters("ssaess"), // 0x28
  new Letters("ssaeng"), // 0x29
  new Letters("ssaej"), // 0x2a
  new Letters("ssaec"), // 0x2b
  new Letters("ssaek"), // 0x2c
  new Letters("ssaet"), // 0x2d
  new Letters("ssaep"), // 0x2e
  new Letters("ssaeh"), // 0x2f
  new Letters("ssya"), // 0x30
  new Letters("ssyag"), // 0x31
  new Letters("ssyagg"), // 0x32
  new Letters("ssyags"), // 0x33
  new Letters("ssyan"), // 0x34
  new Letters("ssyanj"), // 0x35
  new Letters("ssyanh"), // 0x36
  new Letters("ssyad"), // 0x37
  new Letters("ssyal"), // 0x38
  new Letters("ssyalg"), // 0x39
  new Letters("ssyalm"), // 0x3a
  new Letters("ssyalb"), // 0x3b
  new Letters("ssyals"), // 0x3c
  new Letters("ssyalt"), // 0x3d
  new Letters("ssyalp"), // 0x3e
  new Letters("ssyalh"), // 0x3f
  new Letters("ssyam"), // 0x40
  new Letters("ssyab"), // 0x41
  new Letters("ssyabs"), // 0x42
  new Letters("ssyas"), // 0x43
  new Letters("ssyass"), // 0x44
  new Letters("ssyang"), // 0x45
  new Letters("ssyaj"), // 0x46
  new Letters("ssyac"), // 0x47
  new Letters("ssyak"), // 0x48
  new Letters("ssyat"), // 0x49
  new Letters("ssyap"), // 0x4a
  new Letters("ssyah"), // 0x4b
  new Letters("ssyae"), // 0x4c
  new Letters("ssyaeg"), // 0x4d
  new Letters("ssyaegg"), // 0x4e
  new Letters("ssyaegs"), // 0x4f
  new Letters("ssyaen"), // 0x50
  new Letters("ssyaenj"), // 0x51
  new Letters("ssyaenh"), // 0x52
  new Letters("ssyaed"), // 0x53
  new Letters("ssyael"), // 0x54
  new Letters("ssyaelg"), // 0x55
  new Letters("ssyaelm"), // 0x56
  new Letters("ssyaelb"), // 0x57
  new Letters("ssyaels"), // 0x58
  new Letters("ssyaelt"), // 0x59
  new Letters("ssyaelp"), // 0x5a
  new Letters("ssyaelh"), // 0x5b
  new Letters("ssyaem"), // 0x5c
  new Letters("ssyaeb"), // 0x5d
  new Letters("ssyaebs"), // 0x5e
  new Letters("ssyaes"), // 0x5f
  new Letters("ssyaess"), // 0x60
  new Letters("ssyaeng"), // 0x61
  new Letters("ssyaej"), // 0x62
  new Letters("ssyaec"), // 0x63
  new Letters("ssyaek"), // 0x64
  new Letters("ssyaet"), // 0x65
  new Letters("ssyaep"), // 0x66
  new Letters("ssyaeh"), // 0x67
  new Letters("sseo"), // 0x68
  new Letters("sseog"), // 0x69
  new Letters("sseogg"), // 0x6a
  new Letters("sseogs"), // 0x6b
  new Letters("sseon"), // 0x6c
  new Letters("sseonj"), // 0x6d
  new Letters("sseonh"), // 0x6e
  new Letters("sseod"), // 0x6f
  new Letters("sseol"), // 0x70
  new Letters("sseolg"), // 0x71
  new Letters("sseolm"), // 0x72
  new Letters("sseolb"), // 0x73
  new Letters("sseols"), // 0x74
  new Letters("sseolt"), // 0x75
  new Letters("sseolp"), // 0x76
  new Letters("sseolh"), // 0x77
  new Letters("sseom"), // 0x78
  new Letters("sseob"), // 0x79
  new Letters("sseobs"), // 0x7a
  new Letters("sseos"), // 0x7b
  new Letters("sseoss"), // 0x7c
  new Letters("sseong"), // 0x7d
  new Letters("sseoj"), // 0x7e
  new Letters("sseoc"), // 0x7f
  new Letters("sseok"), // 0x80
  new Letters("sseot"), // 0x81
  new Letters("sseop"), // 0x82
  new Letters("sseoh"), // 0x83
  new Letters("sse"), // 0x84
  new Letters("sseg"), // 0x85
  new Letters("ssegg"), // 0x86
  new Letters("ssegs"), // 0x87
  new Letters("ssen"), // 0x88
  new Letters("ssenj"), // 0x89
  new Letters("ssenh"), // 0x8a
  new Letters("ssed"), // 0x8b
  new Letters("ssel"), // 0x8c
  new Letters("sselg"), // 0x8d
  new Letters("sselm"), // 0x8e
  new Letters("sselb"), // 0x8f
  new Letters("ssels"), // 0x90
  new Letters("sselt"), // 0x91
  new Letters("sselp"), // 0x92
  new Letters("sselh"), // 0x93
  new Letters("ssem"), // 0x94
  new Letters("sseb"), // 0x95
  new Letters("ssebs"), // 0x96
  new Letters("sses"), // 0x97
  new Letters("ssess"), // 0x98
  new Letters("sseng"), // 0x99
  new Letters("ssej"), // 0x9a
  new Letters("ssec"), // 0x9b
  new Letters("ssek"), // 0x9c
  new Letters("sset"), // 0x9d
  new Letters("ssep"), // 0x9e
  new Letters("sseh"), // 0x9f
  new Letters("ssyeo"), // 0xa0
  new Letters("ssyeog"), // 0xa1
  new Letters("ssyeogg"), // 0xa2
  new Letters("ssyeogs"), // 0xa3
  new Letters("ssyeon"), // 0xa4
  new Letters("ssyeonj"), // 0xa5
  new Letters("ssyeonh"), // 0xa6
  new Letters("ssyeod"), // 0xa7
  new Letters("ssyeol"), // 0xa8
  new Letters("ssyeolg"), // 0xa9
  new Letters("ssyeolm"), // 0xaa
  new Letters("ssyeolb"), // 0xab
  new Letters("ssyeols"), // 0xac
  new Letters("ssyeolt"), // 0xad
  new Letters("ssyeolp"), // 0xae
  new Letters("ssyeolh"), // 0xaf
  new Letters("ssyeom"), // 0xb0
  new Letters("ssyeob"), // 0xb1
  new Letters("ssyeobs"), // 0xb2
  new Letters("ssyeos"), // 0xb3
  new Letters("ssyeoss"), // 0xb4
  new Letters("ssyeong"), // 0xb5
  new Letters("ssyeoj"), // 0xb6
  new Letters("ssyeoc"), // 0xb7
  new Letters("ssyeok"), // 0xb8
  new Letters("ssyeot"), // 0xb9
  new Letters("ssyeop"), // 0xba
  new Letters("ssyeoh"), // 0xbb
  new Letters("ssye"), // 0xbc
  new Letters("ssyeg"), // 0xbd
  new Letters("ssyegg"), // 0xbe
  new Letters("ssyegs"), // 0xbf
  new Letters("ssyen"), // 0xc0
  new Letters("ssyenj"), // 0xc1
  new Letters("ssyenh"), // 0xc2
  new Letters("ssyed"), // 0xc3
  new Letters("ssyel"), // 0xc4
  new Letters("ssyelg"), // 0xc5
  new Letters("ssyelm"), // 0xc6
  new Letters("ssyelb"), // 0xc7
  new Letters("ssyels"), // 0xc8
  new Letters("ssyelt"), // 0xc9
  new Letters("ssyelp"), // 0xca
  new Letters("ssyelh"), // 0xcb
  new Letters("ssyem"), // 0xcc
  new Letters("ssyeb"), // 0xcd
  new Letters("ssyebs"), // 0xce
  new Letters("ssyes"), // 0xcf
  new Letters("ssyess"), // 0xd0
  new Letters("ssyeng"), // 0xd1
  new Letters("ssyej"), // 0xd2
  new Letters("ssyec"), // 0xd3
  new Letters("ssyek"), // 0xd4
  new Letters("ssyet"), // 0xd5
  new Letters("ssyep"), // 0xd6
  new Letters("ssyeh"), // 0xd7
  new Letters("sso"), // 0xd8
  new Letters("ssog"), // 0xd9
  new Letters("ssogg"), // 0xda
  new Letters("ssogs"), // 0xdb
  new Letters("sson"), // 0xdc
  new Letters("ssonj"), // 0xdd
  new Letters("ssonh"), // 0xde
  new Letters("ssod"), // 0xdf
  new Letters("ssol"), // 0xe0
  new Letters("ssolg"), // 0xe1
  new Letters("ssolm"), // 0xe2
  new Letters("ssolb"), // 0xe3
  new Letters("ssols"), // 0xe4
  new Letters("ssolt"), // 0xe5
  new Letters("ssolp"), // 0xe6
  new Letters("ssolh"), // 0xe7
  new Letters("ssom"), // 0xe8
  new Letters("ssob"), // 0xe9
  new Letters("ssobs"), // 0xea
  new Letters("ssos"), // 0xeb
  new Letters("ssoss"), // 0xec
  new Letters("ssong"), // 0xed
  new Letters("ssoj"), // 0xee
  new Letters("ssoc"), // 0xef
  new Letters("ssok"), // 0xf0
  new Letters("ssot"), // 0xf1
  new Letters("ssop"), // 0xf2
  new Letters("ssoh"), // 0xf3
  new Letters("sswa"), // 0xf4
  new Letters("sswag"), // 0xf5
  new Letters("sswagg"), // 0xf6
  new Letters("sswags"), // 0xf7
  new Letters("sswan"), // 0xf8
  new Letters("sswanj"), // 0xf9
  new Letters("sswanh"), // 0xfa
  new Letters("sswad"), // 0xfb
  new Letters("sswal"), // 0xfc
  new Letters("sswalg"), // 0xfd
  new Letters("sswalm"), // 0xfe
  new Letters("sswalb") // 0xff
  };
}