/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@link Xxx} for codepoint U+C5xx (Hangul Syllables for Korean).
 */
final class Xc5 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("sseum"), // 0x00
  new Letters("sseub"), // 0x01
  new Letters("sseubs"), // 0x02
  new Letters("sseus"), // 0x03
  new Letters("sseuss"), // 0x04
  new Letters("sseung"), // 0x05
  new Letters("sseuj"), // 0x06
  new Letters("sseuc"), // 0x07
  new Letters("sseuk"), // 0x08
  new Letters("sseut"), // 0x09
  new Letters("sseup"), // 0x0a
  new Letters("sseuh"), // 0x0b
  new Letters("ssyi"), // 0x0c
  new Letters("ssyig"), // 0x0d
  new Letters("ssyigg"), // 0x0e
  new Letters("ssyigs"), // 0x0f
  new Letters("ssyin"), // 0x10
  new Letters("ssyinj"), // 0x11
  new Letters("ssyinh"), // 0x12
  new Letters("ssyid"), // 0x13
  new Letters("ssyil"), // 0x14
  new Letters("ssyilg"), // 0x15
  new Letters("ssyilm"), // 0x16
  new Letters("ssyilb"), // 0x17
  new Letters("ssyils"), // 0x18
  new Letters("ssyilt"), // 0x19
  new Letters("ssyilp"), // 0x1a
  new Letters("ssyilh"), // 0x1b
  new Letters("ssyim"), // 0x1c
  new Letters("ssyib"), // 0x1d
  new Letters("ssyibs"), // 0x1e
  new Letters("ssyis"), // 0x1f
  new Letters("ssyiss"), // 0x20
  new Letters("ssying"), // 0x21
  new Letters("ssyij"), // 0x22
  new Letters("ssyic"), // 0x23
  new Letters("ssyik"), // 0x24
  new Letters("ssyit"), // 0x25
  new Letters("ssyip"), // 0x26
  new Letters("ssyih"), // 0x27
  new Letters("ssi"), // 0x28
  new Letters("ssig"), // 0x29
  new Letters("ssigg"), // 0x2a
  new Letters("ssigs"), // 0x2b
  new Letters("ssin"), // 0x2c
  new Letters("ssinj"), // 0x2d
  new Letters("ssinh"), // 0x2e
  new Letters("ssid"), // 0x2f
  new Letters("ssil"), // 0x30
  new Letters("ssilg"), // 0x31
  new Letters("ssilm"), // 0x32
  new Letters("ssilb"), // 0x33
  new Letters("ssils"), // 0x34
  new Letters("ssilt"), // 0x35
  new Letters("ssilp"), // 0x36
  new Letters("ssilh"), // 0x37
  new Letters("ssim"), // 0x38
  new Letters("ssib"), // 0x39
  new Letters("ssibs"), // 0x3a
  new Letters("ssis"), // 0x3b
  new Letters("ssiss"), // 0x3c
  new Letters("ssing"), // 0x3d
  new Letters("ssij"), // 0x3e
  new Letters("ssic"), // 0x3f
  new Letters("ssik"), // 0x40
  new Letters("ssit"), // 0x41
  new Letters("ssip"), // 0x42
  new Letters("ssih"), // 0x43
  Letter.LO_A, // 0x44
  new Letters("ag"), // 0x45
  new Letters("agg"), // 0x46
  new Letters("ags"), // 0x47
  LO_AN, // 0x48
  new Letters("anj"), // 0x49
  new Letters("anh"), // 0x4a
  new Letters("ad"), // 0x4b
  new Letters("al"), // 0x4c
  new Letters("alg"), // 0x4d
  new Letters("alm"), // 0x4e
  new Letters("alb"), // 0x4f
  new Letters("als"), // 0x50
  new Letters("alt"), // 0x51
  new Letters("alp"), // 0x52
  new Letters("alh"), // 0x53
  new Letters("am"), // 0x54
  new Letters("ab"), // 0x55
  new Letters("abs"), // 0x56
  new Letters("as"), // 0x57
  new Letters("ass"), // 0x58
  new Letters("ang"), // 0x59
  new Letters("aj"), // 0x5a
  new Letters("ac"), // 0x5b
  new Letters("ak"), // 0x5c
  LO_AT, // 0x5d
  new Letters("ap"), // 0x5e
  new Letters("ah"), // 0x5f
  LO_AE, // 0x60
  new Letters("aeg"), // 0x61
  new Letters("aegg"), // 0x62
  new Letters("aegs"), // 0x63
  new Letters("aen"), // 0x64
  new Letters("aenj"), // 0x65
  new Letters("aenh"), // 0x66
  new Letters("aed"), // 0x67
  new Letters("ael"), // 0x68
  new Letters("aelg"), // 0x69
  new Letters("aelm"), // 0x6a
  new Letters("aelb"), // 0x6b
  new Letters("aels"), // 0x6c
  new Letters("aelt"), // 0x6d
  new Letters("aelp"), // 0x6e
  new Letters("aelh"), // 0x6f
  new Letters("aem"), // 0x70
  new Letters("aeb"), // 0x71
  new Letters("aebs"), // 0x72
  new Letters("aes"), // 0x73
  new Letters("aess"), // 0x74
  new Letters("aeng"), // 0x75
  new Letters("aej"), // 0x76
  new Letters("aec"), // 0x77
  new Letters("aek"), // 0x78
  new Letters("aet"), // 0x79
  new Letters("aep"), // 0x7a
  new Letters("aeh"), // 0x7b
  LO_YA, // 0x7c
  new Letters("yag"), // 0x7d
  new Letters("yagg"), // 0x7e
  new Letters("yags"), // 0x7f
  new Letters("yan"), // 0x80
  new Letters("yanj"), // 0x81
  new Letters("yanh"), // 0x82
  new Letters("yad"), // 0x83
  new Letters("yal"), // 0x84
  new Letters("yalg"), // 0x85
  new Letters("yalm"), // 0x86
  new Letters("yalb"), // 0x87
  new Letters("yals"), // 0x88
  new Letters("yalt"), // 0x89
  new Letters("yalp"), // 0x8a
  new Letters("yalh"), // 0x8b
  new Letters("yam"), // 0x8c
  new Letters("yab"), // 0x8d
  new Letters("yabs"), // 0x8e
  new Letters("yas"), // 0x8f
  new Letters("yass"), // 0x90
  new Letters("yang"), // 0x91
  new Letters("yaj"), // 0x92
  new Letters("yac"), // 0x93
  new Letters("yak"), // 0x94
  new Letters("yat"), // 0x95
  new Letters("yap"), // 0x96
  new Letters("yah"), // 0x97
  new Letters("yae"), // 0x98
  new Letters("yaeg"), // 0x99
  new Letters("yaegg"), // 0x9a
  new Letters("yaegs"), // 0x9b
  new Letters("yaen"), // 0x9c
  new Letters("yaenj"), // 0x9d
  new Letters("yaenh"), // 0x9e
  new Letters("yaed"), // 0x9f
  new Letters("yael"), // 0xa0
  new Letters("yaelg"), // 0xa1
  new Letters("yaelm"), // 0xa2
  new Letters("yaelb"), // 0xa3
  new Letters("yaels"), // 0xa4
  new Letters("yaelt"), // 0xa5
  new Letters("yaelp"), // 0xa6
  new Letters("yaelh"), // 0xa7
  new Letters("yaem"), // 0xa8
  new Letters("yaeb"), // 0xa9
  new Letters("yaebs"), // 0xaa
  new Letters("yaes"), // 0xab
  new Letters("yaess"), // 0xac
  new Letters("yaeng"), // 0xad
  new Letters("yaej"), // 0xae
  new Letters("yaec"), // 0xaf
  new Letters("yaek"), // 0xb0
  new Letters("yaet"), // 0xb1
  new Letters("yaep"), // 0xb2
  new Letters("yaeh"), // 0xb3
  LO_EO, // 0xb4
  new Letters("eog"), // 0xb5
  new Letters("eogg"), // 0xb6
  new Letters("eogs"), // 0xb7
  new Letters("eon"), // 0xb8
  new Letters("eonj"), // 0xb9
  new Letters("eonh"), // 0xba
  new Letters("eod"), // 0xbb
  new Letters("eol"), // 0xbc
  new Letters("eolg"), // 0xbd
  new Letters("eolm"), // 0xbe
  new Letters("eolb"), // 0xbf
  new Letters("eols"), // 0xc0
  new Letters("eolt"), // 0xc1
  new Letters("eolp"), // 0xc2
  new Letters("eolh"), // 0xc3
  new Letters("eom"), // 0xc4
  new Letters("eob"), // 0xc5
  new Letters("eobs"), // 0xc6
  new Letters("eos"), // 0xc7
  new Letters("eoss"), // 0xc8
  new Letters("eong"), // 0xc9
  new Letters("eoj"), // 0xca
  new Letters("eoc"), // 0xcb
  new Letters("eok"), // 0xcc
  new Letters("eot"), // 0xcd
  new Letters("eop"), // 0xce
  new Letters("eoh"), // 0xcf
  Letter.LO_E, // 0xd0
  new Letters("eg"), // 0xd1
  new Letters("egg"), // 0xd2
  new Letters("egs"), // 0xd3
  new Letters("en"), // 0xd4
  new Letters("enj"), // 0xd5
  new Letters("enh"), // 0xd6
  new Letters("ed"), // 0xd7
  new Letters("el"), // 0xd8
  new Letters("elg"), // 0xd9
  new Letters("elm"), // 0xda
  new Letters("elb"), // 0xdb
  new Letters("els"), // 0xdc
  new Letters("elt"), // 0xdd
  new Letters("elp"), // 0xde
  new Letters("elh"), // 0xdf
  new Letters("em"), // 0xe0
  new Letters("eb"), // 0xe1
  new Letters("ebs"), // 0xe2
  new Letters("es"), // 0xe3
  new Letters("ess"), // 0xe4
  new Letters("eng"), // 0xe5
  new Letters("ej"), // 0xe6
  new Letters("ec"), // 0xe7
  new Letters("ek"), // 0xe8
  new Letters("et"), // 0xe9
  new Letters("ep"), // 0xea
  new Letters("eh"), // 0xeb
  new Letters("yeo"), // 0xec
  new Letters("yeog"), // 0xed
  new Letters("yeogg"), // 0xee
  new Letters("yeogs"), // 0xef
  new Letters("yeon"), // 0xf0
  new Letters("yeonj"), // 0xf1
  new Letters("yeonh"), // 0xf2
  new Letters("yeod"), // 0xf3
  new Letters("yeol"), // 0xf4
  new Letters("yeolg"), // 0xf5
  new Letters("yeolm"), // 0xf6
  new Letters("yeolb"), // 0xf7
  new Letters("yeols"), // 0xf8
  new Letters("yeolt"), // 0xf9
  new Letters("yeolp"), // 0xfa
  new Letters("yeolh"), // 0xfb
  new Letters("yeom"), // 0xfc
  new Letters("yeob"), // 0xfd
  new Letters("yeobs"), // 0xfe
  new Letters("yeos") // 0xff
  };
}