/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@link Xxx} for codepoint U+C7xx (Hangul Syllables for Korean).
 */
final class Xc7 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("wek"), // 0x00
  new Letters("wet"), // 0x01
  new Letters("wep"), // 0x02
  new Letters("weh"), // 0x03
  LO_WI, // 0x04
  new Letters("wig"), // 0x05
  new Letters("wigg"), // 0x06
  new Letters("wigs"), // 0x07
  new Letters("win"), // 0x08
  new Letters("winj"), // 0x09
  new Letters("winh"), // 0x0a
  new Letters("wid"), // 0x0b
  new Letters("wil"), // 0x0c
  new Letters("wilg"), // 0x0d
  new Letters("wilm"), // 0x0e
  new Letters("wilb"), // 0x0f
  new Letters("wils"), // 0x10
  new Letters("wilt"), // 0x11
  new Letters("wilp"), // 0x12
  new Letters("wilh"), // 0x13
  new Letters("wim"), // 0x14
  new Letters("wib"), // 0x15
  new Letters("wibs"), // 0x16
  new Letters("wis"), // 0x17
  new Letters("wiss"), // 0x18
  new Letters("wing"), // 0x19
  new Letters("wij"), // 0x1a
  new Letters("wic"), // 0x1b
  new Letters("wik"), // 0x1c
  new Letters("wit"), // 0x1d
  new Letters("wip"), // 0x1e
  new Letters("wih"), // 0x1f
  LO_YU, // 0x20
  new Letters("yug"), // 0x21
  new Letters("yugg"), // 0x22
  new Letters("yugs"), // 0x23
  new Letters("yun"), // 0x24
  new Letters("yunj"), // 0x25
  new Letters("yunh"), // 0x26
  new Letters("yud"), // 0x27
  new Letters("yul"), // 0x28
  new Letters("yulg"), // 0x29
  new Letters("yulm"), // 0x2a
  new Letters("yulb"), // 0x2b
  new Letters("yuls"), // 0x2c
  new Letters("yult"), // 0x2d
  new Letters("yulp"), // 0x2e
  new Letters("yulh"), // 0x2f
  new Letters("yum"), // 0x30
  new Letters("yub"), // 0x31
  new Letters("yubs"), // 0x32
  new Letters("yus"), // 0x33
  new Letters("yuss"), // 0x34
  new Letters("yung"), // 0x35
  new Letters("yuj"), // 0x36
  new Letters("yuc"), // 0x37
  new Letters("yuk"), // 0x38
  new Letters("yut"), // 0x39
  new Letters("yup"), // 0x3a
  new Letters("yuh"), // 0x3b
  LO_EU, // 0x3c
  new Letters("eug"), // 0x3d
  new Letters("eugg"), // 0x3e
  new Letters("eugs"), // 0x3f
  new Letters("eun"), // 0x40
  new Letters("eunj"), // 0x41
  new Letters("eunh"), // 0x42
  new Letters("eud"), // 0x43
  new Letters("eul"), // 0x44
  new Letters("eulg"), // 0x45
  new Letters("eulm"), // 0x46
  new Letters("eulb"), // 0x47
  new Letters("euls"), // 0x48
  new Letters("eult"), // 0x49
  new Letters("eulp"), // 0x4a
  new Letters("eulh"), // 0x4b
  new Letters("eum"), // 0x4c
  new Letters("eub"), // 0x4d
  new Letters("eubs"), // 0x4e
  new Letters("eus"), // 0x4f
  new Letters("euss"), // 0x50
  new Letters("eung"), // 0x51
  new Letters("euj"), // 0x52
  new Letters("euc"), // 0x53
  new Letters("euk"), // 0x54
  new Letters("eut"), // 0x55
  new Letters("eup"), // 0x56
  new Letters("euh"), // 0x57
  LO_YI, // 0x58
  new Letters("yig"), // 0x59
  new Letters("yigg"), // 0x5a
  new Letters("yigs"), // 0x5b
  new Letters("yin"), // 0x5c
  new Letters("yinj"), // 0x5d
  new Letters("yinh"), // 0x5e
  new Letters("yid"), // 0x5f
  new Letters("yil"), // 0x60
  new Letters("yilg"), // 0x61
  new Letters("yilm"), // 0x62
  new Letters("yilb"), // 0x63
  new Letters("yils"), // 0x64
  new Letters("yilt"), // 0x65
  new Letters("yilp"), // 0x66
  new Letters("yilh"), // 0x67
  new Letters("yim"), // 0x68
  new Letters("yib"), // 0x69
  new Letters("yibs"), // 0x6a
  new Letters("yis"), // 0x6b
  new Letters("yiss"), // 0x6c
  new Letters("ying"), // 0x6d
  new Letters("yij"), // 0x6e
  new Letters("yic"), // 0x6f
  new Letters("yik"), // 0x70
  new Letters("yit"), // 0x71
  new Letters("yip"), // 0x72
  new Letters("yih"), // 0x73
  Letter.LO_I, // 0x74
  new Letters("ig"), // 0x75
  new Letters("igg"), // 0x76
  new Letters("igs"), // 0x77
  LO_IN, // 0x78
  new Letters("inj"), // 0x79
  new Letters("inh"), // 0x7a
  new Letters("id"), // 0x7b
  new Letters("il"), // 0x7c
  new Letters("ilg"), // 0x7d
  new Letters("ilm"), // 0x7e
  new Letters("ilb"), // 0x7f
  new Letters("ils"), // 0x80
  new Letters("ilt"), // 0x81
  new Letters("ilp"), // 0x82
  new Letters("ilh"), // 0x83
  new Letters("im"), // 0x84
  new Letters("ib"), // 0x85
  new Letters("ibs"), // 0x86
  new Letters("is"), // 0x87
  new Letters("iss"), // 0x88
  new Letters("ing"), // 0x89
  new Letters("ij"), // 0x8a
  new Letters("ic"), // 0x8b
  new Letters("ik"), // 0x8c
  new Letters("it"), // 0x8d
  new Letters("ip"), // 0x8e
  new Letters("ih"), // 0x8f
  LO_JA, // 0x90
  new Letters("jag"), // 0x91
  new Letters("jagg"), // 0x92
  new Letters("jags"), // 0x93
  new Letters("jan"), // 0x94
  new Letters("janj"), // 0x95
  new Letters("janh"), // 0x96
  new Letters("jad"), // 0x97
  new Letters("jal"), // 0x98
  new Letters("jalg"), // 0x99
  new Letters("jalm"), // 0x9a
  new Letters("jalb"), // 0x9b
  new Letters("jals"), // 0x9c
  new Letters("jalt"), // 0x9d
  new Letters("jalp"), // 0x9e
  new Letters("jalh"), // 0x9f
  new Letters("jam"), // 0xa0
  new Letters("jab"), // 0xa1
  new Letters("jabs"), // 0xa2
  new Letters("jas"), // 0xa3
  new Letters("jass"), // 0xa4
  new Letters("jang"), // 0xa5
  new Letters("jaj"), // 0xa6
  new Letters("jac"), // 0xa7
  new Letters("jak"), // 0xa8
  new Letters("jat"), // 0xa9
  new Letters("jap"), // 0xaa
  new Letters("jah"), // 0xab
  new Letters("jae"), // 0xac
  new Letters("jaeg"), // 0xad
  new Letters("jaegg"), // 0xae
  new Letters("jaegs"), // 0xaf
  new Letters("jaen"), // 0xb0
  new Letters("jaenj"), // 0xb1
  new Letters("jaenh"), // 0xb2
  new Letters("jaed"), // 0xb3
  new Letters("jael"), // 0xb4
  new Letters("jaelg"), // 0xb5
  new Letters("jaelm"), // 0xb6
  new Letters("jaelb"), // 0xb7
  new Letters("jaels"), // 0xb8
  new Letters("jaelt"), // 0xb9
  new Letters("jaelp"), // 0xba
  new Letters("jaelh"), // 0xbb
  new Letters("jaem"), // 0xbc
  new Letters("jaeb"), // 0xbd
  new Letters("jaebs"), // 0xbe
  new Letters("jaes"), // 0xbf
  new Letters("jaess"), // 0xc0
  new Letters("jaeng"), // 0xc1
  new Letters("jaej"), // 0xc2
  new Letters("jaec"), // 0xc3
  new Letters("jaek"), // 0xc4
  new Letters("jaet"), // 0xc5
  new Letters("jaep"), // 0xc6
  new Letters("jaeh"), // 0xc7
  new Letters("jya"), // 0xc8
  new Letters("jyag"), // 0xc9
  new Letters("jyagg"), // 0xca
  new Letters("jyags"), // 0xcb
  new Letters("jyan"), // 0xcc
  new Letters("jyanj"), // 0xcd
  new Letters("jyanh"), // 0xce
  new Letters("jyad"), // 0xcf
  new Letters("jyal"), // 0xd0
  new Letters("jyalg"), // 0xd1
  new Letters("jyalm"), // 0xd2
  new Letters("jyalb"), // 0xd3
  new Letters("jyals"), // 0xd4
  new Letters("jyalt"), // 0xd5
  new Letters("jyalp"), // 0xd6
  new Letters("jyalh"), // 0xd7
  new Letters("jyam"), // 0xd8
  new Letters("jyab"), // 0xd9
  new Letters("jyabs"), // 0xda
  new Letters("jyas"), // 0xdb
  new Letters("jyass"), // 0xdc
  new Letters("jyang"), // 0xdd
  new Letters("jyaj"), // 0xde
  new Letters("jyac"), // 0xdf
  new Letters("jyak"), // 0xe0
  new Letters("jyat"), // 0xe1
  new Letters("jyap"), // 0xe2
  new Letters("jyah"), // 0xe3
  new Letters("jyae"), // 0xe4
  new Letters("jyaeg"), // 0xe5
  new Letters("jyaegg"), // 0xe6
  new Letters("jyaegs"), // 0xe7
  new Letters("jyaen"), // 0xe8
  new Letters("jyaenj"), // 0xe9
  new Letters("jyaenh"), // 0xea
  new Letters("jyaed"), // 0xeb
  new Letters("jyael"), // 0xec
  new Letters("jyaelg"), // 0xed
  new Letters("jyaelm"), // 0xee
  new Letters("jyaelb"), // 0xef
  new Letters("jyaels"), // 0xf0
  new Letters("jyaelt"), // 0xf1
  new Letters("jyaelp"), // 0xf2
  new Letters("jyaelh"), // 0xf3
  new Letters("jyaem"), // 0xf4
  new Letters("jyaeb"), // 0xf5
  new Letters("jyaebs"), // 0xf6
  new Letters("jyaes"), // 0xf7
  new Letters("jyaess"), // 0xf8
  new Letters("jyaeng"), // 0xf9
  new Letters("jyaej"), // 0xfa
  new Letters("jyaec"), // 0xfb
  new Letters("jyaek"), // 0xfc
  new Letters("jyaet"), // 0xfd
  new Letters("jyaep"), // 0xfe
  new Letters("jyaeh") // 0xff
  };
}