/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+C8xx (Hangul Syllables for Korean).
 */
final class Xc8 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("jeo"), // 0x00
  new Letters("jeog"), // 0x01
  new Letters("jeogg"), // 0x02
  new Letters("jeogs"), // 0x03
  new Letters("jeon"), // 0x04
  new Letters("jeonj"), // 0x05
  new Letters("jeonh"), // 0x06
  new Letters("jeod"), // 0x07
  new Letters("jeol"), // 0x08
  new Letters("jeolg"), // 0x09
  new Letters("jeolm"), // 0x0a
  new Letters("jeolb"), // 0x0b
  new Letters("jeols"), // 0x0c
  new Letters("jeolt"), // 0x0d
  new Letters("jeolp"), // 0x0e
  new Letters("jeolh"), // 0x0f
  new Letters("jeom"), // 0x10
  new Letters("jeob"), // 0x11
  new Letters("jeobs"), // 0x12
  new Letters("jeos"), // 0x13
  new Letters("jeoss"), // 0x14
  new Letters("jeong"), // 0x15
  new Letters("jeoj"), // 0x16
  new Letters("jeoc"), // 0x17
  new Letters("jeok"), // 0x18
  new Letters("jeot"), // 0x19
  new Letters("jeop"), // 0x1a
  new Letters("jeoh"), // 0x1b
  new Letters("je"), // 0x1c
  new Letters("jeg"), // 0x1d
  new Letters("jegg"), // 0x1e
  new Letters("jegs"), // 0x1f
  new Letters("jen"), // 0x20
  new Letters("jenj"), // 0x21
  new Letters("jenh"), // 0x22
  new Letters("jed"), // 0x23
  new Letters("jel"), // 0x24
  new Letters("jelg"), // 0x25
  new Letters("jelm"), // 0x26
  new Letters("jelb"), // 0x27
  new Letters("jels"), // 0x28
  new Letters("jelt"), // 0x29
  new Letters("jelp"), // 0x2a
  new Letters("jelh"), // 0x2b
  new Letters("jem"), // 0x2c
  new Letters("jeb"), // 0x2d
  new Letters("jebs"), // 0x2e
  new Letters("jes"), // 0x2f
  new Letters("jess"), // 0x30
  new Letters("jeng"), // 0x31
  new Letters("jej"), // 0x32
  new Letters("jec"), // 0x33
  new Letters("jek"), // 0x34
  new Letters("jet"), // 0x35
  new Letters("jep"), // 0x36
  new Letters("jeh"), // 0x37
  new Letters("jyeo"), // 0x38
  new Letters("jyeog"), // 0x39
  new Letters("jyeogg"), // 0x3a
  new Letters("jyeogs"), // 0x3b
  new Letters("jyeon"), // 0x3c
  new Letters("jyeonj"), // 0x3d
  new Letters("jyeonh"), // 0x3e
  new Letters("jyeod"), // 0x3f
  new Letters("jyeol"), // 0x40
  new Letters("jyeolg"), // 0x41
  new Letters("jyeolm"), // 0x42
  new Letters("jyeolb"), // 0x43
  new Letters("jyeols"), // 0x44
  new Letters("jyeolt"), // 0x45
  new Letters("jyeolp"), // 0x46
  new Letters("jyeolh"), // 0x47
  new Letters("jyeom"), // 0x48
  new Letters("jyeob"), // 0x49
  new Letters("jyeobs"), // 0x4a
  new Letters("jyeos"), // 0x4b
  new Letters("jyeoss"), // 0x4c
  new Letters("jyeong"), // 0x4d
  new Letters("jyeoj"), // 0x4e
  new Letters("jyeoc"), // 0x4f
  new Letters("jyeok"), // 0x50
  new Letters("jyeot"), // 0x51
  new Letters("jyeop"), // 0x52
  new Letters("jyeoh"), // 0x53
  new Letters("jye"), // 0x54
  new Letters("jyeg"), // 0x55
  new Letters("jyegg"), // 0x56
  new Letters("jyegs"), // 0x57
  new Letters("jyen"), // 0x58
  new Letters("jyenj"), // 0x59
  new Letters("jyenh"), // 0x5a
  new Letters("jyed"), // 0x5b
  new Letters("jyel"), // 0x5c
  new Letters("jyelg"), // 0x5d
  new Letters("jyelm"), // 0x5e
  new Letters("jyelb"), // 0x5f
  new Letters("jyels"), // 0x60
  new Letters("jyelt"), // 0x61
  new Letters("jyelp"), // 0x62
  new Letters("jyelh"), // 0x63
  new Letters("jyem"), // 0x64
  new Letters("jyeb"), // 0x65
  new Letters("jyebs"), // 0x66
  new Letters("jyes"), // 0x67
  new Letters("jyess"), // 0x68
  new Letters("jyeng"), // 0x69
  new Letters("jyej"), // 0x6a
  new Letters("jyec"), // 0x6b
  new Letters("jyek"), // 0x6c
  new Letters("jyet"), // 0x6d
  new Letters("jyep"), // 0x6e
  new Letters("jyeh"), // 0x6f
  LO_JO, // 0x70
  new Letters("jog"), // 0x71
  new Letters("jogg"), // 0x72
  new Letters("jogs"), // 0x73
  new Letters("jon"), // 0x74
  new Letters("jonj"), // 0x75
  new Letters("jonh"), // 0x76
  new Letters("jod"), // 0x77
  new Letters("jol"), // 0x78
  new Letters("jolg"), // 0x79
  new Letters("jolm"), // 0x7a
  new Letters("jolb"), // 0x7b
  new Letters("jols"), // 0x7c
  new Letters("jolt"), // 0x7d
  new Letters("jolp"), // 0x7e
  new Letters("jolh"), // 0x7f
  new Letters("jom"), // 0x80
  new Letters("job"), // 0x81
  new Letters("jobs"), // 0x82
  new Letters("jos"), // 0x83
  new Letters("joss"), // 0x84
  new Letters("jong"), // 0x85
  new Letters("joj"), // 0x86
  new Letters("joc"), // 0x87
  new Letters("jok"), // 0x88
  new Letters("jot"), // 0x89
  new Letters("jop"), // 0x8a
  new Letters("joh"), // 0x8b
  new Letters("jwa"), // 0x8c
  new Letters("jwag"), // 0x8d
  new Letters("jwagg"), // 0x8e
  new Letters("jwags"), // 0x8f
  new Letters("jwan"), // 0x90
  new Letters("jwanj"), // 0x91
  new Letters("jwanh"), // 0x92
  new Letters("jwad"), // 0x93
  new Letters("jwal"), // 0x94
  new Letters("jwalg"), // 0x95
  new Letters("jwalm"), // 0x96
  new Letters("jwalb"), // 0x97
  new Letters("jwals"), // 0x98
  new Letters("jwalt"), // 0x99
  new Letters("jwalp"), // 0x9a
  new Letters("jwalh"), // 0x9b
  new Letters("jwam"), // 0x9c
  new Letters("jwab"), // 0x9d
  new Letters("jwabs"), // 0x9e
  new Letters("jwas"), // 0x9f
  new Letters("jwass"), // 0xa0
  new Letters("jwang"), // 0xa1
  new Letters("jwaj"), // 0xa2
  new Letters("jwac"), // 0xa3
  new Letters("jwak"), // 0xa4
  new Letters("jwat"), // 0xa5
  new Letters("jwap"), // 0xa6
  new Letters("jwah"), // 0xa7
  new Letters("jwae"), // 0xa8
  new Letters("jwaeg"), // 0xa9
  new Letters("jwaegg"), // 0xaa
  new Letters("jwaegs"), // 0xab
  new Letters("jwaen"), // 0xac
  new Letters("jwaenj"), // 0xad
  new Letters("jwaenh"), // 0xae
  new Letters("jwaed"), // 0xaf
  new Letters("jwael"), // 0xb0
  new Letters("jwaelg"), // 0xb1
  new Letters("jwaelm"), // 0xb2
  new Letters("jwaelb"), // 0xb3
  new Letters("jwaels"), // 0xb4
  new Letters("jwaelt"), // 0xb5
  new Letters("jwaelp"), // 0xb6
  new Letters("jwaelh"), // 0xb7
  new Letters("jwaem"), // 0xb8
  new Letters("jwaeb"), // 0xb9
  new Letters("jwaebs"), // 0xba
  new Letters("jwaes"), // 0xbb
  new Letters("jwaess"), // 0xbc
  new Letters("jwaeng"), // 0xbd
  new Letters("jwaej"), // 0xbe
  new Letters("jwaec"), // 0xbf
  new Letters("jwaek"), // 0xc0
  new Letters("jwaet"), // 0xc1
  new Letters("jwaep"), // 0xc2
  new Letters("jwaeh"), // 0xc3
  new Letters("joe"), // 0xc4
  new Letters("joeg"), // 0xc5
  new Letters("joegg"), // 0xc6
  new Letters("joegs"), // 0xc7
  new Letters("joen"), // 0xc8
  new Letters("joenj"), // 0xc9
  new Letters("joenh"), // 0xca
  new Letters("joed"), // 0xcb
  new Letters("joel"), // 0xcc
  new Letters("joelg"), // 0xcd
  new Letters("joelm"), // 0xce
  new Letters("joelb"), // 0xcf
  new Letters("joels"), // 0xd0
  new Letters("joelt"), // 0xd1
  new Letters("joelp"), // 0xd2
  new Letters("joelh"), // 0xd3
  new Letters("joem"), // 0xd4
  new Letters("joeb"), // 0xd5
  new Letters("joebs"), // 0xd6
  new Letters("joes"), // 0xd7
  new Letters("joess"), // 0xd8
  new Letters("joeng"), // 0xd9
  new Letters("joej"), // 0xda
  new Letters("joec"), // 0xdb
  new Letters("joek"), // 0xdc
  new Letters("joet"), // 0xdd
  new Letters("joep"), // 0xde
  new Letters("joeh"), // 0xdf
  new Letters("jyo"), // 0xe0
  new Letters("jyog"), // 0xe1
  new Letters("jyogg"), // 0xe2
  new Letters("jyogs"), // 0xe3
  new Letters("jyon"), // 0xe4
  new Letters("jyonj"), // 0xe5
  new Letters("jyonh"), // 0xe6
  new Letters("jyod"), // 0xe7
  new Letters("jyol"), // 0xe8
  new Letters("jyolg"), // 0xe9
  new Letters("jyolm"), // 0xea
  new Letters("jyolb"), // 0xeb
  new Letters("jyols"), // 0xec
  new Letters("jyolt"), // 0xed
  new Letters("jyolp"), // 0xee
  new Letters("jyolh"), // 0xef
  new Letters("jyom"), // 0xf0
  new Letters("jyob"), // 0xf1
  new Letters("jyobs"), // 0xf2
  new Letters("jyos"), // 0xf3
  new Letters("jyoss"), // 0xf4
  new Letters("jyong"), // 0xf5
  new Letters("jyoj"), // 0xf6
  new Letters("jyoc"), // 0xf7
  new Letters("jyok"), // 0xf8
  new Letters("jyot"), // 0xf9
  new Letters("jyop"), // 0xfa
  new Letters("jyoh"), // 0xfb
  LO_JU, // 0xfc
  new Letters("jug"), // 0xfd
  new Letters("jugg"), // 0xfe
  new Letters("jugs") // 0xff
  };
}