/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+C9xx (Hangul Syllables for Korean).
 */
final class Xc9 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("jun"), // 0x00
  new Letters("junj"), // 0x01
  new Letters("junh"), // 0x02
  new Letters("jud"), // 0x03
  new Letters("jul"), // 0x04
  new Letters("julg"), // 0x05
  new Letters("julm"), // 0x06
  new Letters("julb"), // 0x07
  new Letters("juls"), // 0x08
  new Letters("jult"), // 0x09
  new Letters("julp"), // 0x0a
  new Letters("julh"), // 0x0b
  new Letters("jum"), // 0x0c
  new Letters("jub"), // 0x0d
  new Letters("jubs"), // 0x0e
  new Letters("jus"), // 0x0f
  new Letters("juss"), // 0x10
  new Letters("jung"), // 0x11
  new Letters("juj"), // 0x12
  new Letters("juc"), // 0x13
  new Letters("juk"), // 0x14
  new Letters("jut"), // 0x15
  new Letters("jup"), // 0x16
  new Letters("juh"), // 0x17
  new Letters("jweo"), // 0x18
  new Letters("jweog"), // 0x19
  new Letters("jweogg"), // 0x1a
  new Letters("jweogs"), // 0x1b
  new Letters("jweon"), // 0x1c
  new Letters("jweonj"), // 0x1d
  new Letters("jweonh"), // 0x1e
  new Letters("jweod"), // 0x1f
  new Letters("jweol"), // 0x20
  new Letters("jweolg"), // 0x21
  new Letters("jweolm"), // 0x22
  new Letters("jweolb"), // 0x23
  new Letters("jweols"), // 0x24
  new Letters("jweolt"), // 0x25
  new Letters("jweolp"), // 0x26
  new Letters("jweolh"), // 0x27
  new Letters("jweom"), // 0x28
  new Letters("jweob"), // 0x29
  new Letters("jweobs"), // 0x2a
  new Letters("jweos"), // 0x2b
  new Letters("jweoss"), // 0x2c
  new Letters("jweong"), // 0x2d
  new Letters("jweoj"), // 0x2e
  new Letters("jweoc"), // 0x2f
  new Letters("jweok"), // 0x30
  new Letters("jweot"), // 0x31
  new Letters("jweop"), // 0x32
  new Letters("jweoh"), // 0x33
  new Letters("jwe"), // 0x34
  new Letters("jweg"), // 0x35
  new Letters("jwegg"), // 0x36
  new Letters("jwegs"), // 0x37
  new Letters("jwen"), // 0x38
  new Letters("jwenj"), // 0x39
  new Letters("jwenh"), // 0x3a
  new Letters("jwed"), // 0x3b
  new Letters("jwel"), // 0x3c
  new Letters("jwelg"), // 0x3d
  new Letters("jwelm"), // 0x3e
  new Letters("jwelb"), // 0x3f
  new Letters("jwels"), // 0x40
  new Letters("jwelt"), // 0x41
  new Letters("jwelp"), // 0x42
  new Letters("jwelh"), // 0x43
  new Letters("jwem"), // 0x44
  new Letters("jweb"), // 0x45
  new Letters("jwebs"), // 0x46
  new Letters("jwes"), // 0x47
  new Letters("jwess"), // 0x48
  new Letters("jweng"), // 0x49
  new Letters("jwej"), // 0x4a
  new Letters("jwec"), // 0x4b
  new Letters("jwek"), // 0x4c
  new Letters("jwet"), // 0x4d
  new Letters("jwep"), // 0x4e
  new Letters("jweh"), // 0x4f
  new Letters("jwi"), // 0x50
  new Letters("jwig"), // 0x51
  new Letters("jwigg"), // 0x52
  new Letters("jwigs"), // 0x53
  new Letters("jwin"), // 0x54
  new Letters("jwinj"), // 0x55
  new Letters("jwinh"), // 0x56
  new Letters("jwid"), // 0x57
  new Letters("jwil"), // 0x58
  new Letters("jwilg"), // 0x59
  new Letters("jwilm"), // 0x5a
  new Letters("jwilb"), // 0x5b
  new Letters("jwils"), // 0x5c
  new Letters("jwilt"), // 0x5d
  new Letters("jwilp"), // 0x5e
  new Letters("jwilh"), // 0x5f
  new Letters("jwim"), // 0x60
  new Letters("jwib"), // 0x61
  new Letters("jwibs"), // 0x62
  new Letters("jwis"), // 0x63
  new Letters("jwiss"), // 0x64
  new Letters("jwing"), // 0x65
  new Letters("jwij"), // 0x66
  new Letters("jwic"), // 0x67
  new Letters("jwik"), // 0x68
  new Letters("jwit"), // 0x69
  new Letters("jwip"), // 0x6a
  new Letters("jwih"), // 0x6b
  new Letters("jyu"), // 0x6c
  new Letters("jyug"), // 0x6d
  new Letters("jyugg"), // 0x6e
  new Letters("jyugs"), // 0x6f
  new Letters("jyun"), // 0x70
  new Letters("jyunj"), // 0x71
  new Letters("jyunh"), // 0x72
  new Letters("jyud"), // 0x73
  new Letters("jyul"), // 0x74
  new Letters("jyulg"), // 0x75
  new Letters("jyulm"), // 0x76
  new Letters("jyulb"), // 0x77
  new Letters("jyuls"), // 0x78
  new Letters("jyult"), // 0x79
  new Letters("jyulp"), // 0x7a
  new Letters("jyulh"), // 0x7b
  new Letters("jyum"), // 0x7c
  new Letters("jyub"), // 0x7d
  new Letters("jyubs"), // 0x7e
  new Letters("jyus"), // 0x7f
  new Letters("jyuss"), // 0x80
  new Letters("jyung"), // 0x81
  new Letters("jyuj"), // 0x82
  new Letters("jyuc"), // 0x83
  new Letters("jyuk"), // 0x84
  new Letters("jyut"), // 0x85
  new Letters("jyup"), // 0x86
  new Letters("jyuh"), // 0x87
  new Letters("jeu"), // 0x88
  new Letters("jeug"), // 0x89
  new Letters("jeugg"), // 0x8a
  new Letters("jeugs"), // 0x8b
  new Letters("jeun"), // 0x8c
  new Letters("jeunj"), // 0x8d
  new Letters("jeunh"), // 0x8e
  new Letters("jeud"), // 0x8f
  new Letters("jeul"), // 0x90
  new Letters("jeulg"), // 0x91
  new Letters("jeulm"), // 0x92
  new Letters("jeulb"), // 0x93
  new Letters("jeuls"), // 0x94
  new Letters("jeult"), // 0x95
  new Letters("jeulp"), // 0x96
  new Letters("jeulh"), // 0x97
  new Letters("jeum"), // 0x98
  new Letters("jeub"), // 0x99
  new Letters("jeubs"), // 0x9a
  new Letters("jeus"), // 0x9b
  new Letters("jeuss"), // 0x9c
  new Letters("jeung"), // 0x9d
  new Letters("jeuj"), // 0x9e
  new Letters("jeuc"), // 0x9f
  new Letters("jeuk"), // 0xa0
  new Letters("jeut"), // 0xa1
  new Letters("jeup"), // 0xa2
  new Letters("jeuh"), // 0xa3
  new Letters("jyi"), // 0xa4
  new Letters("jyig"), // 0xa5
  new Letters("jyigg"), // 0xa6
  new Letters("jyigs"), // 0xa7
  new Letters("jyin"), // 0xa8
  new Letters("jyinj"), // 0xa9
  new Letters("jyinh"), // 0xaa
  new Letters("jyid"), // 0xab
  new Letters("jyil"), // 0xac
  new Letters("jyilg"), // 0xad
  new Letters("jyilm"), // 0xae
  new Letters("jyilb"), // 0xaf
  new Letters("jyils"), // 0xb0
  new Letters("jyilt"), // 0xb1
  new Letters("jyilp"), // 0xb2
  new Letters("jyilh"), // 0xb3
  new Letters("jyim"), // 0xb4
  new Letters("jyib"), // 0xb5
  new Letters("jyibs"), // 0xb6
  new Letters("jyis"), // 0xb7
  new Letters("jyiss"), // 0xb8
  new Letters("jying"), // 0xb9
  new Letters("jyij"), // 0xba
  new Letters("jyic"), // 0xbb
  new Letters("jyik"), // 0xbc
  new Letters("jyit"), // 0xbd
  new Letters("jyip"), // 0xbe
  new Letters("jyih"), // 0xbf
  new Letters("ji"), // 0xc0
  new Letters("jig"), // 0xc1
  new Letters("jigg"), // 0xc2
  new Letters("jigs"), // 0xc3
  new Letters("jin"), // 0xc4
  new Letters("jinj"), // 0xc5
  new Letters("jinh"), // 0xc6
  new Letters("jid"), // 0xc7
  new Letters("jil"), // 0xc8
  new Letters("jilg"), // 0xc9
  new Letters("jilm"), // 0xca
  new Letters("jilb"), // 0xcb
  new Letters("jils"), // 0xcc
  new Letters("jilt"), // 0xcd
  new Letters("jilp"), // 0xce
  new Letters("jilh"), // 0xcf
  new Letters("jim"), // 0xd0
  new Letters("jib"), // 0xd1
  new Letters("jibs"), // 0xd2
  new Letters("jis"), // 0xd3
  new Letters("jiss"), // 0xd4
  new Letters("jing"), // 0xd5
  new Letters("jij"), // 0xd6
  new Letters("jic"), // 0xd7
  new Letters("jik"), // 0xd8
  new Letters("jit"), // 0xd9
  new Letters("jip"), // 0xda
  new Letters("jih"), // 0xdb
  new Letters("jja"), // 0xdc
  new Letters("jjag"), // 0xdd
  new Letters("jjagg"), // 0xde
  new Letters("jjags"), // 0xdf
  new Letters("jjan"), // 0xe0
  new Letters("jjanj"), // 0xe1
  new Letters("jjanh"), // 0xe2
  new Letters("jjad"), // 0xe3
  new Letters("jjal"), // 0xe4
  new Letters("jjalg"), // 0xe5
  new Letters("jjalm"), // 0xe6
  new Letters("jjalb"), // 0xe7
  new Letters("jjals"), // 0xe8
  new Letters("jjalt"), // 0xe9
  new Letters("jjalp"), // 0xea
  new Letters("jjalh"), // 0xeb
  new Letters("jjam"), // 0xec
  new Letters("jjab"), // 0xed
  new Letters("jjabs"), // 0xee
  new Letters("jjas"), // 0xef
  new Letters("jjass"), // 0xf0
  new Letters("jjang"), // 0xf1
  new Letters("jjaj"), // 0xf2
  new Letters("jjac"), // 0xf3
  new Letters("jjak"), // 0xf4
  new Letters("jjat"), // 0xf5
  new Letters("jjap"), // 0xf6
  new Letters("jjah"), // 0xf7
  new Letters("jjae"), // 0xf8
  new Letters("jjaeg"), // 0xf9
  new Letters("jjaegg"), // 0xfa
  new Letters("jjaegs"), // 0xfb
  new Letters("jjaen"), // 0xfc
  new Letters("jjaenj"), // 0xfd
  new Letters("jjaenh"), // 0xfe
  new Letters("jjaed") // 0xff
  };
}