/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+CAxx (Hangul Syllables for Korean).
 */
final class Xca extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("jjael"), // 0x00
  new Letters("jjaelg"), // 0x01
  new Letters("jjaelm"), // 0x02
  new Letters("jjaelb"), // 0x03
  new Letters("jjaels"), // 0x04
  new Letters("jjaelt"), // 0x05
  new Letters("jjaelp"), // 0x06
  new Letters("jjaelh"), // 0x07
  new Letters("jjaem"), // 0x08
  new Letters("jjaeb"), // 0x09
  new Letters("jjaebs"), // 0x0a
  new Letters("jjaes"), // 0x0b
  new Letters("jjaess"), // 0x0c
  new Letters("jjaeng"), // 0x0d
  new Letters("jjaej"), // 0x0e
  new Letters("jjaec"), // 0x0f
  new Letters("jjaek"), // 0x10
  new Letters("jjaet"), // 0x11
  new Letters("jjaep"), // 0x12
  new Letters("jjaeh"), // 0x13
  new Letters("jjya"), // 0x14
  new Letters("jjyag"), // 0x15
  new Letters("jjyagg"), // 0x16
  new Letters("jjyags"), // 0x17
  new Letters("jjyan"), // 0x18
  new Letters("jjyanj"), // 0x19
  new Letters("jjyanh"), // 0x1a
  new Letters("jjyad"), // 0x1b
  new Letters("jjyal"), // 0x1c
  new Letters("jjyalg"), // 0x1d
  new Letters("jjyalm"), // 0x1e
  new Letters("jjyalb"), // 0x1f
  new Letters("jjyals"), // 0x20
  new Letters("jjyalt"), // 0x21
  new Letters("jjyalp"), // 0x22
  new Letters("jjyalh"), // 0x23
  new Letters("jjyam"), // 0x24
  new Letters("jjyab"), // 0x25
  new Letters("jjyabs"), // 0x26
  new Letters("jjyas"), // 0x27
  new Letters("jjyass"), // 0x28
  new Letters("jjyang"), // 0x29
  new Letters("jjyaj"), // 0x2a
  new Letters("jjyac"), // 0x2b
  new Letters("jjyak"), // 0x2c
  new Letters("jjyat"), // 0x2d
  new Letters("jjyap"), // 0x2e
  new Letters("jjyah"), // 0x2f
  new Letters("jjyae"), // 0x30
  new Letters("jjyaeg"), // 0x31
  new Letters("jjyaegg"), // 0x32
  new Letters("jjyaegs"), // 0x33
  new Letters("jjyaen"), // 0x34
  new Letters("jjyaenj"), // 0x35
  new Letters("jjyaenh"), // 0x36
  new Letters("jjyaed"), // 0x37
  new Letters("jjyael"), // 0x38
  new Letters("jjyaelg"), // 0x39
  new Letters("jjyaelm"), // 0x3a
  new Letters("jjyaelb"), // 0x3b
  new Letters("jjyaels"), // 0x3c
  new Letters("jjyaelt"), // 0x3d
  new Letters("jjyaelp"), // 0x3e
  new Letters("jjyaelh"), // 0x3f
  new Letters("jjyaem"), // 0x40
  new Letters("jjyaeb"), // 0x41
  new Letters("jjyaebs"), // 0x42
  new Letters("jjyaes"), // 0x43
  new Letters("jjyaess"), // 0x44
  new Letters("jjyaeng"), // 0x45
  new Letters("jjyaej"), // 0x46
  new Letters("jjyaec"), // 0x47
  new Letters("jjyaek"), // 0x48
  new Letters("jjyaet"), // 0x49
  new Letters("jjyaep"), // 0x4a
  new Letters("jjyaeh"), // 0x4b
  new Letters("jjeo"), // 0x4c
  new Letters("jjeog"), // 0x4d
  new Letters("jjeogg"), // 0x4e
  new Letters("jjeogs"), // 0x4f
  new Letters("jjeon"), // 0x50
  new Letters("jjeonj"), // 0x51
  new Letters("jjeonh"), // 0x52
  new Letters("jjeod"), // 0x53
  new Letters("jjeol"), // 0x54
  new Letters("jjeolg"), // 0x55
  new Letters("jjeolm"), // 0x56
  new Letters("jjeolb"), // 0x57
  new Letters("jjeols"), // 0x58
  new Letters("jjeolt"), // 0x59
  new Letters("jjeolp"), // 0x5a
  new Letters("jjeolh"), // 0x5b
  new Letters("jjeom"), // 0x5c
  new Letters("jjeob"), // 0x5d
  new Letters("jjeobs"), // 0x5e
  new Letters("jjeos"), // 0x5f
  new Letters("jjeoss"), // 0x60
  new Letters("jjeong"), // 0x61
  new Letters("jjeoj"), // 0x62
  new Letters("jjeoc"), // 0x63
  new Letters("jjeok"), // 0x64
  new Letters("jjeot"), // 0x65
  new Letters("jjeop"), // 0x66
  new Letters("jjeoh"), // 0x67
  new Letters("jje"), // 0x68
  new Letters("jjeg"), // 0x69
  new Letters("jjegg"), // 0x6a
  new Letters("jjegs"), // 0x6b
  new Letters("jjen"), // 0x6c
  new Letters("jjenj"), // 0x6d
  new Letters("jjenh"), // 0x6e
  new Letters("jjed"), // 0x6f
  new Letters("jjel"), // 0x70
  new Letters("jjelg"), // 0x71
  new Letters("jjelm"), // 0x72
  new Letters("jjelb"), // 0x73
  new Letters("jjels"), // 0x74
  new Letters("jjelt"), // 0x75
  new Letters("jjelp"), // 0x76
  new Letters("jjelh"), // 0x77
  new Letters("jjem"), // 0x78
  new Letters("jjeb"), // 0x79
  new Letters("jjebs"), // 0x7a
  new Letters("jjes"), // 0x7b
  new Letters("jjess"), // 0x7c
  new Letters("jjeng"), // 0x7d
  new Letters("jjej"), // 0x7e
  new Letters("jjec"), // 0x7f
  new Letters("jjek"), // 0x80
  new Letters("jjet"), // 0x81
  new Letters("jjep"), // 0x82
  new Letters("jjeh"), // 0x83
  new Letters("jjyeo"), // 0x84
  new Letters("jjyeog"), // 0x85
  new Letters("jjyeogg"), // 0x86
  new Letters("jjyeogs"), // 0x87
  new Letters("jjyeon"), // 0x88
  new Letters("jjyeonj"), // 0x89
  new Letters("jjyeonh"), // 0x8a
  new Letters("jjyeod"), // 0x8b
  new Letters("jjyeol"), // 0x8c
  new Letters("jjyeolg"), // 0x8d
  new Letters("jjyeolm"), // 0x8e
  new Letters("jjyeolb"), // 0x8f
  new Letters("jjyeols"), // 0x90
  new Letters("jjyeolt"), // 0x91
  new Letters("jjyeolp"), // 0x92
  new Letters("jjyeolh"), // 0x93
  new Letters("jjyeom"), // 0x94
  new Letters("jjyeob"), // 0x95
  new Letters("jjyeobs"), // 0x96
  new Letters("jjyeos"), // 0x97
  new Letters("jjyeoss"), // 0x98
  new Letters("jjyeong"), // 0x99
  new Letters("jjyeoj"), // 0x9a
  new Letters("jjyeoc"), // 0x9b
  new Letters("jjyeok"), // 0x9c
  new Letters("jjyeot"), // 0x9d
  new Letters("jjyeop"), // 0x9e
  new Letters("jjyeoh"), // 0x9f
  new Letters("jjye"), // 0xa0
  new Letters("jjyeg"), // 0xa1
  new Letters("jjyegg"), // 0xa2
  new Letters("jjyegs"), // 0xa3
  new Letters("jjyen"), // 0xa4
  new Letters("jjyenj"), // 0xa5
  new Letters("jjyenh"), // 0xa6
  new Letters("jjyed"), // 0xa7
  new Letters("jjyel"), // 0xa8
  new Letters("jjyelg"), // 0xa9
  new Letters("jjyelm"), // 0xaa
  new Letters("jjyelb"), // 0xab
  new Letters("jjyels"), // 0xac
  new Letters("jjyelt"), // 0xad
  new Letters("jjyelp"), // 0xae
  new Letters("jjyelh"), // 0xaf
  new Letters("jjyem"), // 0xb0
  new Letters("jjyeb"), // 0xb1
  new Letters("jjyebs"), // 0xb2
  new Letters("jjyes"), // 0xb3
  new Letters("jjyess"), // 0xb4
  new Letters("jjyeng"), // 0xb5
  new Letters("jjyej"), // 0xb6
  new Letters("jjyec"), // 0xb7
  new Letters("jjyek"), // 0xb8
  new Letters("jjyet"), // 0xb9
  new Letters("jjyep"), // 0xba
  new Letters("jjyeh"), // 0xbb
  new Letters("jjo"), // 0xbc
  new Letters("jjog"), // 0xbd
  new Letters("jjogg"), // 0xbe
  new Letters("jjogs"), // 0xbf
  new Letters("jjon"), // 0xc0
  new Letters("jjonj"), // 0xc1
  new Letters("jjonh"), // 0xc2
  new Letters("jjod"), // 0xc3
  new Letters("jjol"), // 0xc4
  new Letters("jjolg"), // 0xc5
  new Letters("jjolm"), // 0xc6
  new Letters("jjolb"), // 0xc7
  new Letters("jjols"), // 0xc8
  new Letters("jjolt"), // 0xc9
  new Letters("jjolp"), // 0xca
  new Letters("jjolh"), // 0xcb
  new Letters("jjom"), // 0xcc
  new Letters("jjob"), // 0xcd
  new Letters("jjobs"), // 0xce
  new Letters("jjos"), // 0xcf
  new Letters("jjoss"), // 0xd0
  new Letters("jjong"), // 0xd1
  new Letters("jjoj"), // 0xd2
  new Letters("jjoc"), // 0xd3
  new Letters("jjok"), // 0xd4
  new Letters("jjot"), // 0xd5
  new Letters("jjop"), // 0xd6
  new Letters("jjoh"), // 0xd7
  new Letters("jjwa"), // 0xd8
  new Letters("jjwag"), // 0xd9
  new Letters("jjwagg"), // 0xda
  new Letters("jjwags"), // 0xdb
  new Letters("jjwan"), // 0xdc
  new Letters("jjwanj"), // 0xdd
  new Letters("jjwanh"), // 0xde
  new Letters("jjwad"), // 0xdf
  new Letters("jjwal"), // 0xe0
  new Letters("jjwalg"), // 0xe1
  new Letters("jjwalm"), // 0xe2
  new Letters("jjwalb"), // 0xe3
  new Letters("jjwals"), // 0xe4
  new Letters("jjwalt"), // 0xe5
  new Letters("jjwalp"), // 0xe6
  new Letters("jjwalh"), // 0xe7
  new Letters("jjwam"), // 0xe8
  new Letters("jjwab"), // 0xe9
  new Letters("jjwabs"), // 0xea
  new Letters("jjwas"), // 0xeb
  new Letters("jjwass"), // 0xec
  new Letters("jjwang"), // 0xed
  new Letters("jjwaj"), // 0xee
  new Letters("jjwac"), // 0xef
  new Letters("jjwak"), // 0xf0
  new Letters("jjwat"), // 0xf1
  new Letters("jjwap"), // 0xf2
  new Letters("jjwah"), // 0xf3
  new Letters("jjwae"), // 0xf4
  new Letters("jjwaeg"), // 0xf5
  new Letters("jjwaegg"), // 0xf6
  new Letters("jjwaegs"), // 0xf7
  new Letters("jjwaen"), // 0xf8
  new Letters("jjwaenj"), // 0xf9
  new Letters("jjwaenh"), // 0xfa
  new Letters("jjwaed"), // 0xfb
  new Letters("jjwael"), // 0xfc
  new Letters("jjwaelg"), // 0xfd
  new Letters("jjwaelm"), // 0xfe
  new Letters("jjwaelb") // 0xff
  };
}