/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+CBxx (Hangul Syllables for Korean).
 */
final class Xcb extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("jjwaels"), // 0x00
  new Letters("jjwaelt"), // 0x01
  new Letters("jjwaelp"), // 0x02
  new Letters("jjwaelh"), // 0x03
  new Letters("jjwaem"), // 0x04
  new Letters("jjwaeb"), // 0x05
  new Letters("jjwaebs"), // 0x06
  new Letters("jjwaes"), // 0x07
  new Letters("jjwaess"), // 0x08
  new Letters("jjwaeng"), // 0x09
  new Letters("jjwaej"), // 0x0a
  new Letters("jjwaec"), // 0x0b
  new Letters("jjwaek"), // 0x0c
  new Letters("jjwaet"), // 0x0d
  new Letters("jjwaep"), // 0x0e
  new Letters("jjwaeh"), // 0x0f
  new Letters("jjoe"), // 0x10
  new Letters("jjoeg"), // 0x11
  new Letters("jjoegg"), // 0x12
  new Letters("jjoegs"), // 0x13
  new Letters("jjoen"), // 0x14
  new Letters("jjoenj"), // 0x15
  new Letters("jjoenh"), // 0x16
  new Letters("jjoed"), // 0x17
  new Letters("jjoel"), // 0x18
  new Letters("jjoelg"), // 0x19
  new Letters("jjoelm"), // 0x1a
  new Letters("jjoelb"), // 0x1b
  new Letters("jjoels"), // 0x1c
  new Letters("jjoelt"), // 0x1d
  new Letters("jjoelp"), // 0x1e
  new Letters("jjoelh"), // 0x1f
  new Letters("jjoem"), // 0x20
  new Letters("jjoeb"), // 0x21
  new Letters("jjoebs"), // 0x22
  new Letters("jjoes"), // 0x23
  new Letters("jjoess"), // 0x24
  new Letters("jjoeng"), // 0x25
  new Letters("jjoej"), // 0x26
  new Letters("jjoec"), // 0x27
  new Letters("jjoek"), // 0x28
  new Letters("jjoet"), // 0x29
  new Letters("jjoep"), // 0x2a
  new Letters("jjoeh"), // 0x2b
  new Letters("jjyo"), // 0x2c
  new Letters("jjyog"), // 0x2d
  new Letters("jjyogg"), // 0x2e
  new Letters("jjyogs"), // 0x2f
  new Letters("jjyon"), // 0x30
  new Letters("jjyonj"), // 0x31
  new Letters("jjyonh"), // 0x32
  new Letters("jjyod"), // 0x33
  new Letters("jjyol"), // 0x34
  new Letters("jjyolg"), // 0x35
  new Letters("jjyolm"), // 0x36
  new Letters("jjyolb"), // 0x37
  new Letters("jjyols"), // 0x38
  new Letters("jjyolt"), // 0x39
  new Letters("jjyolp"), // 0x3a
  new Letters("jjyolh"), // 0x3b
  new Letters("jjyom"), // 0x3c
  new Letters("jjyob"), // 0x3d
  new Letters("jjyobs"), // 0x3e
  new Letters("jjyos"), // 0x3f
  new Letters("jjyoss"), // 0x40
  new Letters("jjyong"), // 0x41
  new Letters("jjyoj"), // 0x42
  new Letters("jjyoc"), // 0x43
  new Letters("jjyok"), // 0x44
  new Letters("jjyot"), // 0x45
  new Letters("jjyop"), // 0x46
  new Letters("jjyoh"), // 0x47
  new Letters("jju"), // 0x48
  new Letters("jjug"), // 0x49
  new Letters("jjugg"), // 0x4a
  new Letters("jjugs"), // 0x4b
  new Letters("jjun"), // 0x4c
  new Letters("jjunj"), // 0x4d
  new Letters("jjunh"), // 0x4e
  new Letters("jjud"), // 0x4f
  new Letters("jjul"), // 0x50
  new Letters("jjulg"), // 0x51
  new Letters("jjulm"), // 0x52
  new Letters("jjulb"), // 0x53
  new Letters("jjuls"), // 0x54
  new Letters("jjult"), // 0x55
  new Letters("jjulp"), // 0x56
  new Letters("jjulh"), // 0x57
  new Letters("jjum"), // 0x58
  new Letters("jjub"), // 0x59
  new Letters("jjubs"), // 0x5a
  new Letters("jjus"), // 0x5b
  new Letters("jjuss"), // 0x5c
  new Letters("jjung"), // 0x5d
  new Letters("jjuj"), // 0x5e
  new Letters("jjuc"), // 0x5f
  new Letters("jjuk"), // 0x60
  new Letters("jjut"), // 0x61
  new Letters("jjup"), // 0x62
  new Letters("jjuh"), // 0x63
  new Letters("jjweo"), // 0x64
  new Letters("jjweog"), // 0x65
  new Letters("jjweogg"), // 0x66
  new Letters("jjweogs"), // 0x67
  new Letters("jjweon"), // 0x68
  new Letters("jjweonj"), // 0x69
  new Letters("jjweonh"), // 0x6a
  new Letters("jjweod"), // 0x6b
  new Letters("jjweol"), // 0x6c
  new Letters("jjweolg"), // 0x6d
  new Letters("jjweolm"), // 0x6e
  new Letters("jjweolb"), // 0x6f
  new Letters("jjweols"), // 0x70
  new Letters("jjweolt"), // 0x71
  new Letters("jjweolp"), // 0x72
  new Letters("jjweolh"), // 0x73
  new Letters("jjweom"), // 0x74
  new Letters("jjweob"), // 0x75
  new Letters("jjweobs"), // 0x76
  new Letters("jjweos"), // 0x77
  new Letters("jjweoss"), // 0x78
  new Letters("jjweong"), // 0x79
  new Letters("jjweoj"), // 0x7a
  new Letters("jjweoc"), // 0x7b
  new Letters("jjweok"), // 0x7c
  new Letters("jjweot"), // 0x7d
  new Letters("jjweop"), // 0x7e
  new Letters("jjweoh"), // 0x7f
  new Letters("jjwe"), // 0x80
  new Letters("jjweg"), // 0x81
  new Letters("jjwegg"), // 0x82
  new Letters("jjwegs"), // 0x83
  new Letters("jjwen"), // 0x84
  new Letters("jjwenj"), // 0x85
  new Letters("jjwenh"), // 0x86
  new Letters("jjwed"), // 0x87
  new Letters("jjwel"), // 0x88
  new Letters("jjwelg"), // 0x89
  new Letters("jjwelm"), // 0x8a
  new Letters("jjwelb"), // 0x8b
  new Letters("jjwels"), // 0x8c
  new Letters("jjwelt"), // 0x8d
  new Letters("jjwelp"), // 0x8e
  new Letters("jjwelh"), // 0x8f
  new Letters("jjwem"), // 0x90
  new Letters("jjweb"), // 0x91
  new Letters("jjwebs"), // 0x92
  new Letters("jjwes"), // 0x93
  new Letters("jjwess"), // 0x94
  new Letters("jjweng"), // 0x95
  new Letters("jjwej"), // 0x96
  new Letters("jjwec"), // 0x97
  new Letters("jjwek"), // 0x98
  new Letters("jjwet"), // 0x99
  new Letters("jjwep"), // 0x9a
  new Letters("jjweh"), // 0x9b
  new Letters("jjwi"), // 0x9c
  new Letters("jjwig"), // 0x9d
  new Letters("jjwigg"), // 0x9e
  new Letters("jjwigs"), // 0x9f
  new Letters("jjwin"), // 0xa0
  new Letters("jjwinj"), // 0xa1
  new Letters("jjwinh"), // 0xa2
  new Letters("jjwid"), // 0xa3
  new Letters("jjwil"), // 0xa4
  new Letters("jjwilg"), // 0xa5
  new Letters("jjwilm"), // 0xa6
  new Letters("jjwilb"), // 0xa7
  new Letters("jjwils"), // 0xa8
  new Letters("jjwilt"), // 0xa9
  new Letters("jjwilp"), // 0xaa
  new Letters("jjwilh"), // 0xab
  new Letters("jjwim"), // 0xac
  new Letters("jjwib"), // 0xad
  new Letters("jjwibs"), // 0xae
  new Letters("jjwis"), // 0xaf
  new Letters("jjwiss"), // 0xb0
  new Letters("jjwing"), // 0xb1
  new Letters("jjwij"), // 0xb2
  new Letters("jjwic"), // 0xb3
  new Letters("jjwik"), // 0xb4
  new Letters("jjwit"), // 0xb5
  new Letters("jjwip"), // 0xb6
  new Letters("jjwih"), // 0xb7
  new Letters("jjyu"), // 0xb8
  new Letters("jjyug"), // 0xb9
  new Letters("jjyugg"), // 0xba
  new Letters("jjyugs"), // 0xbb
  new Letters("jjyun"), // 0xbc
  new Letters("jjyunj"), // 0xbd
  new Letters("jjyunh"), // 0xbe
  new Letters("jjyud"), // 0xbf
  new Letters("jjyul"), // 0xc0
  new Letters("jjyulg"), // 0xc1
  new Letters("jjyulm"), // 0xc2
  new Letters("jjyulb"), // 0xc3
  new Letters("jjyuls"), // 0xc4
  new Letters("jjyult"), // 0xc5
  new Letters("jjyulp"), // 0xc6
  new Letters("jjyulh"), // 0xc7
  new Letters("jjyum"), // 0xc8
  new Letters("jjyub"), // 0xc9
  new Letters("jjyubs"), // 0xca
  new Letters("jjyus"), // 0xcb
  new Letters("jjyuss"), // 0xcc
  new Letters("jjyung"), // 0xcd
  new Letters("jjyuj"), // 0xce
  new Letters("jjyuc"), // 0xcf
  new Letters("jjyuk"), // 0xd0
  new Letters("jjyut"), // 0xd1
  new Letters("jjyup"), // 0xd2
  new Letters("jjyuh"), // 0xd3
  new Letters("jjeu"), // 0xd4
  new Letters("jjeug"), // 0xd5
  new Letters("jjeugg"), // 0xd6
  new Letters("jjeugs"), // 0xd7
  new Letters("jjeun"), // 0xd8
  new Letters("jjeunj"), // 0xd9
  new Letters("jjeunh"), // 0xda
  new Letters("jjeud"), // 0xdb
  new Letters("jjeul"), // 0xdc
  new Letters("jjeulg"), // 0xdd
  new Letters("jjeulm"), // 0xde
  new Letters("jjeulb"), // 0xdf
  new Letters("jjeuls"), // 0xe0
  new Letters("jjeult"), // 0xe1
  new Letters("jjeulp"), // 0xe2
  new Letters("jjeulh"), // 0xe3
  new Letters("jjeum"), // 0xe4
  new Letters("jjeub"), // 0xe5
  new Letters("jjeubs"), // 0xe6
  new Letters("jjeus"), // 0xe7
  new Letters("jjeuss"), // 0xe8
  new Letters("jjeung"), // 0xe9
  new Letters("jjeuj"), // 0xea
  new Letters("jjeuc"), // 0xeb
  new Letters("jjeuk"), // 0xec
  new Letters("jjeut"), // 0xed
  new Letters("jjeup"), // 0xee
  new Letters("jjeuh"), // 0xef
  new Letters("jjyi"), // 0xf0
  new Letters("jjyig"), // 0xf1
  new Letters("jjyigg"), // 0xf2
  new Letters("jjyigs"), // 0xf3
  new Letters("jjyin"), // 0xf4
  new Letters("jjyinj"), // 0xf5
  new Letters("jjyinh"), // 0xf6
  new Letters("jjyid"), // 0xf7
  new Letters("jjyil"), // 0xf8
  new Letters("jjyilg"), // 0xf9
  new Letters("jjyilm"), // 0xfa
  new Letters("jjyilb"), // 0xfb
  new Letters("jjyils"), // 0xfc
  new Letters("jjyilt"), // 0xfd
  new Letters("jjyilp"), // 0xfe
  new Letters("jjyilh") // 0xff
  };
}