/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+CCxx (Hangul Syllables for Korean).
 */
final class Xcc extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("jjyim"), // 0x00
  new Letters("jjyib"), // 0x01
  new Letters("jjyibs"), // 0x02
  new Letters("jjyis"), // 0x03
  new Letters("jjyiss"), // 0x04
  new Letters("jjying"), // 0x05
  new Letters("jjyij"), // 0x06
  new Letters("jjyic"), // 0x07
  new Letters("jjyik"), // 0x08
  new Letters("jjyit"), // 0x09
  new Letters("jjyip"), // 0x0a
  new Letters("jjyih"), // 0x0b
  new Letters("jji"), // 0x0c
  new Letters("jjig"), // 0x0d
  new Letters("jjigg"), // 0x0e
  new Letters("jjigs"), // 0x0f
  new Letters("jjin"), // 0x10
  new Letters("jjinj"), // 0x11
  new Letters("jjinh"), // 0x12
  new Letters("jjid"), // 0x13
  new Letters("jjil"), // 0x14
  new Letters("jjilg"), // 0x15
  new Letters("jjilm"), // 0x16
  new Letters("jjilb"), // 0x17
  new Letters("jjils"), // 0x18
  new Letters("jjilt"), // 0x19
  new Letters("jjilp"), // 0x1a
  new Letters("jjilh"), // 0x1b
  new Letters("jjim"), // 0x1c
  new Letters("jjib"), // 0x1d
  new Letters("jjibs"), // 0x1e
  new Letters("jjis"), // 0x1f
  new Letters("jjiss"), // 0x20
  new Letters("jjing"), // 0x21
  new Letters("jjij"), // 0x22
  new Letters("jjic"), // 0x23
  new Letters("jjik"), // 0x24
  new Letters("jjit"), // 0x25
  new Letters("jjip"), // 0x26
  new Letters("jjih"), // 0x27
  LO_CA, // 0x28
  new Letters("cag"), // 0x29
  new Letters("cagg"), // 0x2a
  new Letters("cags"), // 0x2b
  new Letters("can"), // 0x2c
  new Letters("canj"), // 0x2d
  new Letters("canh"), // 0x2e
  new Letters("cad"), // 0x2f
  new Letters("cal"), // 0x30
  new Letters("calg"), // 0x31
  new Letters("calm"), // 0x32
  new Letters("calb"), // 0x33
  new Letters("cals"), // 0x34
  new Letters("calt"), // 0x35
  new Letters("calp"), // 0x36
  new Letters("calh"), // 0x37
  new Letters("cam"), // 0x38
  new Letters("cab"), // 0x39
  new Letters("cabs"), // 0x3a
  new Letters("cas"), // 0x3b
  new Letters("cass"), // 0x3c
  new Letters("cang"), // 0x3d
  new Letters("caj"), // 0x3e
  new Letters("cac"), // 0x3f
  new Letters("cak"), // 0x40
  new Letters("cat"), // 0x41
  new Letters("cap"), // 0x42
  new Letters("cah"), // 0x43
  new Letters("cae"), // 0x44
  new Letters("caeg"), // 0x45
  new Letters("caegg"), // 0x46
  new Letters("caegs"), // 0x47
  new Letters("caen"), // 0x48
  new Letters("caenj"), // 0x49
  new Letters("caenh"), // 0x4a
  new Letters("caed"), // 0x4b
  new Letters("cael"), // 0x4c
  new Letters("caelg"), // 0x4d
  new Letters("caelm"), // 0x4e
  new Letters("caelb"), // 0x4f
  new Letters("caels"), // 0x50
  new Letters("caelt"), // 0x51
  new Letters("caelp"), // 0x52
  new Letters("caelh"), // 0x53
  new Letters("caem"), // 0x54
  new Letters("caeb"), // 0x55
  new Letters("caebs"), // 0x56
  new Letters("caes"), // 0x57
  new Letters("caess"), // 0x58
  new Letters("caeng"), // 0x59
  new Letters("caej"), // 0x5a
  new Letters("caec"), // 0x5b
  new Letters("caek"), // 0x5c
  new Letters("caet"), // 0x5d
  new Letters("caep"), // 0x5e
  new Letters("caeh"), // 0x5f
  new Letters("cya"), // 0x60
  new Letters("cyag"), // 0x61
  new Letters("cyagg"), // 0x62
  new Letters("cyags"), // 0x63
  new Letters("cyan"), // 0x64
  new Letters("cyanj"), // 0x65
  new Letters("cyanh"), // 0x66
  new Letters("cyad"), // 0x67
  new Letters("cyal"), // 0x68
  new Letters("cyalg"), // 0x69
  new Letters("cyalm"), // 0x6a
  new Letters("cyalb"), // 0x6b
  new Letters("cyals"), // 0x6c
  new Letters("cyalt"), // 0x6d
  new Letters("cyalp"), // 0x6e
  new Letters("cyalh"), // 0x6f
  new Letters("cyam"), // 0x70
  new Letters("cyab"), // 0x71
  new Letters("cyabs"), // 0x72
  new Letters("cyas"), // 0x73
  new Letters("cyass"), // 0x74
  new Letters("cyang"), // 0x75
  new Letters("cyaj"), // 0x76
  new Letters("cyac"), // 0x77
  new Letters("cyak"), // 0x78
  new Letters("cyat"), // 0x79
  new Letters("cyap"), // 0x7a
  new Letters("cyah"), // 0x7b
  new Letters("cyae"), // 0x7c
  new Letters("cyaeg"), // 0x7d
  new Letters("cyaegg"), // 0x7e
  new Letters("cyaegs"), // 0x7f
  new Letters("cyaen"), // 0x80
  new Letters("cyaenj"), // 0x81
  new Letters("cyaenh"), // 0x82
  new Letters("cyaed"), // 0x83
  new Letters("cyael"), // 0x84
  new Letters("cyaelg"), // 0x85
  new Letters("cyaelm"), // 0x86
  new Letters("cyaelb"), // 0x87
  new Letters("cyaels"), // 0x88
  new Letters("cyaelt"), // 0x89
  new Letters("cyaelp"), // 0x8a
  new Letters("cyaelh"), // 0x8b
  new Letters("cyaem"), // 0x8c
  new Letters("cyaeb"), // 0x8d
  new Letters("cyaebs"), // 0x8e
  new Letters("cyaes"), // 0x8f
  new Letters("cyaess"), // 0x90
  new Letters("cyaeng"), // 0x91
  new Letters("cyaej"), // 0x92
  new Letters("cyaec"), // 0x93
  new Letters("cyaek"), // 0x94
  new Letters("cyaet"), // 0x95
  new Letters("cyaep"), // 0x96
  new Letters("cyaeh"), // 0x97
  new Letters("ceo"), // 0x98
  new Letters("ceog"), // 0x99
  new Letters("ceogg"), // 0x9a
  new Letters("ceogs"), // 0x9b
  new Letters("ceon"), // 0x9c
  new Letters("ceonj"), // 0x9d
  new Letters("ceonh"), // 0x9e
  new Letters("ceod"), // 0x9f
  new Letters("ceol"), // 0xa0
  new Letters("ceolg"), // 0xa1
  new Letters("ceolm"), // 0xa2
  new Letters("ceolb"), // 0xa3
  new Letters("ceols"), // 0xa4
  new Letters("ceolt"), // 0xa5
  new Letters("ceolp"), // 0xa6
  new Letters("ceolh"), // 0xa7
  new Letters("ceom"), // 0xa8
  new Letters("ceob"), // 0xa9
  new Letters("ceobs"), // 0xaa
  new Letters("ceos"), // 0xab
  new Letters("ceoss"), // 0xac
  new Letters("ceong"), // 0xad
  new Letters("ceoj"), // 0xae
  new Letters("ceoc"), // 0xaf
  new Letters("ceok"), // 0xb0
  new Letters("ceot"), // 0xb1
  new Letters("ceop"), // 0xb2
  new Letters("ceoh"), // 0xb3
  LO_CE, // 0xb4
  new Letters("ceg"), // 0xb5
  new Letters("cegg"), // 0xb6
  new Letters("cegs"), // 0xb7
  new Letters("cen"), // 0xb8
  new Letters("cenj"), // 0xb9
  new Letters("cenh"), // 0xba
  new Letters("ced"), // 0xbb
  new Letters("cel"), // 0xbc
  new Letters("celg"), // 0xbd
  new Letters("celm"), // 0xbe
  new Letters("celb"), // 0xbf
  new Letters("cels"), // 0xc0
  new Letters("celt"), // 0xc1
  new Letters("celp"), // 0xc2
  new Letters("celh"), // 0xc3
  new Letters("cem"), // 0xc4
  new Letters("ceb"), // 0xc5
  new Letters("cebs"), // 0xc6
  new Letters("ces"), // 0xc7
  new Letters("cess"), // 0xc8
  new Letters("ceng"), // 0xc9
  new Letters("cej"), // 0xca
  new Letters("cec"), // 0xcb
  new Letters("cek"), // 0xcc
  new Letters("cet"), // 0xcd
  new Letters("cep"), // 0xce
  new Letters("ceh"), // 0xcf
  new Letters("cyeo"), // 0xd0
  new Letters("cyeog"), // 0xd1
  new Letters("cyeogg"), // 0xd2
  new Letters("cyeogs"), // 0xd3
  new Letters("cyeon"), // 0xd4
  new Letters("cyeonj"), // 0xd5
  new Letters("cyeonh"), // 0xd6
  new Letters("cyeod"), // 0xd7
  new Letters("cyeol"), // 0xd8
  new Letters("cyeolg"), // 0xd9
  new Letters("cyeolm"), // 0xda
  new Letters("cyeolb"), // 0xdb
  new Letters("cyeols"), // 0xdc
  new Letters("cyeolt"), // 0xdd
  new Letters("cyeolp"), // 0xde
  new Letters("cyeolh"), // 0xdf
  new Letters("cyeom"), // 0xe0
  new Letters("cyeob"), // 0xe1
  new Letters("cyeobs"), // 0xe2
  new Letters("cyeos"), // 0xe3
  new Letters("cyeoss"), // 0xe4
  new Letters("cyeong"), // 0xe5
  new Letters("cyeoj"), // 0xe6
  new Letters("cyeoc"), // 0xe7
  new Letters("cyeok"), // 0xe8
  new Letters("cyeot"), // 0xe9
  new Letters("cyeop"), // 0xea
  new Letters("cyeoh"), // 0xeb
  new Letters("cye"), // 0xec
  new Letters("cyeg"), // 0xed
  new Letters("cyegg"), // 0xee
  new Letters("cyegs"), // 0xef
  new Letters("cyen"), // 0xf0
  new Letters("cyenj"), // 0xf1
  new Letters("cyenh"), // 0xf2
  new Letters("cyed"), // 0xf3
  new Letters("cyel"), // 0xf4
  new Letters("cyelg"), // 0xf5
  new Letters("cyelm"), // 0xf6
  new Letters("cyelb"), // 0xf7
  new Letters("cyels"), // 0xf8
  new Letters("cyelt"), // 0xf9
  new Letters("cyelp"), // 0xfa
  new Letters("cyelh"), // 0xfb
  new Letters("cyem"), // 0xfc
  new Letters("cyeb"), // 0xfd
  new Letters("cyebs"), // 0xfe
  new Letters("cyes") // 0xff
  };
}