/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+CDxx (Hangul Syllables for Korean).
 */
final class Xcd extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("cyess"), // 0x00
  new Letters("cyeng"), // 0x01
  new Letters("cyej"), // 0x02
  new Letters("cyec"), // 0x03
  new Letters("cyek"), // 0x04
  new Letters("cyet"), // 0x05
  new Letters("cyep"), // 0x06
  new Letters("cyeh"), // 0x07
  new Letters("co"), // 0x08
  new Letters("cog"), // 0x09
  new Letters("cogg"), // 0x0a
  new Letters("cogs"), // 0x0b
  new Letters("con"), // 0x0c
  new Letters("conj"), // 0x0d
  new Letters("conh"), // 0x0e
  new Letters("cod"), // 0x0f
  new Letters("col"), // 0x10
  new Letters("colg"), // 0x11
  new Letters("colm"), // 0x12
  new Letters("colb"), // 0x13
  new Letters("cols"), // 0x14
  new Letters("colt"), // 0x15
  new Letters("colp"), // 0x16
  new Letters("colh"), // 0x17
  new Letters("com"), // 0x18
  new Letters("cob"), // 0x19
  new Letters("cobs"), // 0x1a
  new Letters("cos"), // 0x1b
  new Letters("coss"), // 0x1c
  new Letters("cong"), // 0x1d
  new Letters("coj"), // 0x1e
  new Letters("coc"), // 0x1f
  new Letters("cok"), // 0x20
  new Letters("cot"), // 0x21
  new Letters("cop"), // 0x22
  new Letters("coh"), // 0x23
  new Letters("cwa"), // 0x24
  new Letters("cwag"), // 0x25
  new Letters("cwagg"), // 0x26
  new Letters("cwags"), // 0x27
  new Letters("cwan"), // 0x28
  new Letters("cwanj"), // 0x29
  new Letters("cwanh"), // 0x2a
  new Letters("cwad"), // 0x2b
  new Letters("cwal"), // 0x2c
  new Letters("cwalg"), // 0x2d
  new Letters("cwalm"), // 0x2e
  new Letters("cwalb"), // 0x2f
  new Letters("cwals"), // 0x30
  new Letters("cwalt"), // 0x31
  new Letters("cwalp"), // 0x32
  new Letters("cwalh"), // 0x33
  new Letters("cwam"), // 0x34
  new Letters("cwab"), // 0x35
  new Letters("cwabs"), // 0x36
  new Letters("cwas"), // 0x37
  new Letters("cwass"), // 0x38
  new Letters("cwang"), // 0x39
  new Letters("cwaj"), // 0x3a
  new Letters("cwac"), // 0x3b
  new Letters("cwak"), // 0x3c
  new Letters("cwat"), // 0x3d
  new Letters("cwap"), // 0x3e
  new Letters("cwah"), // 0x3f
  new Letters("cwae"), // 0x40
  new Letters("cwaeg"), // 0x41
  new Letters("cwaegg"), // 0x42
  new Letters("cwaegs"), // 0x43
  new Letters("cwaen"), // 0x44
  new Letters("cwaenj"), // 0x45
  new Letters("cwaenh"), // 0x46
  new Letters("cwaed"), // 0x47
  new Letters("cwael"), // 0x48
  new Letters("cwaelg"), // 0x49
  new Letters("cwaelm"), // 0x4a
  new Letters("cwaelb"), // 0x4b
  new Letters("cwaels"), // 0x4c
  new Letters("cwaelt"), // 0x4d
  new Letters("cwaelp"), // 0x4e
  new Letters("cwaelh"), // 0x4f
  new Letters("cwaem"), // 0x50
  new Letters("cwaeb"), // 0x51
  new Letters("cwaebs"), // 0x52
  new Letters("cwaes"), // 0x53
  new Letters("cwaess"), // 0x54
  new Letters("cwaeng"), // 0x55
  new Letters("cwaej"), // 0x56
  new Letters("cwaec"), // 0x57
  new Letters("cwaek"), // 0x58
  new Letters("cwaet"), // 0x59
  new Letters("cwaep"), // 0x5a
  new Letters("cwaeh"), // 0x5b
  new Letters("coe"), // 0x5c
  new Letters("coeg"), // 0x5d
  new Letters("coegg"), // 0x5e
  new Letters("coegs"), // 0x5f
  new Letters("coen"), // 0x60
  new Letters("coenj"), // 0x61
  new Letters("coenh"), // 0x62
  new Letters("coed"), // 0x63
  new Letters("coel"), // 0x64
  new Letters("coelg"), // 0x65
  new Letters("coelm"), // 0x66
  new Letters("coelb"), // 0x67
  new Letters("coels"), // 0x68
  new Letters("coelt"), // 0x69
  new Letters("coelp"), // 0x6a
  new Letters("coelh"), // 0x6b
  new Letters("coem"), // 0x6c
  new Letters("coeb"), // 0x6d
  new Letters("coebs"), // 0x6e
  new Letters("coes"), // 0x6f
  new Letters("coess"), // 0x70
  new Letters("coeng"), // 0x71
  new Letters("coej"), // 0x72
  new Letters("coec"), // 0x73
  new Letters("coek"), // 0x74
  new Letters("coet"), // 0x75
  new Letters("coep"), // 0x76
  new Letters("coeh"), // 0x77
  new Letters("cyo"), // 0x78
  new Letters("cyog"), // 0x79
  new Letters("cyogg"), // 0x7a
  new Letters("cyogs"), // 0x7b
  new Letters("cyon"), // 0x7c
  new Letters("cyonj"), // 0x7d
  new Letters("cyonh"), // 0x7e
  new Letters("cyod"), // 0x7f
  new Letters("cyol"), // 0x80
  new Letters("cyolg"), // 0x81
  new Letters("cyolm"), // 0x82
  new Letters("cyolb"), // 0x83
  new Letters("cyols"), // 0x84
  new Letters("cyolt"), // 0x85
  new Letters("cyolp"), // 0x86
  new Letters("cyolh"), // 0x87
  new Letters("cyom"), // 0x88
  new Letters("cyob"), // 0x89
  new Letters("cyobs"), // 0x8a
  new Letters("cyos"), // 0x8b
  new Letters("cyoss"), // 0x8c
  new Letters("cyong"), // 0x8d
  new Letters("cyoj"), // 0x8e
  new Letters("cyoc"), // 0x8f
  new Letters("cyok"), // 0x90
  new Letters("cyot"), // 0x91
  new Letters("cyop"), // 0x92
  new Letters("cyoh"), // 0x93
  new Letters("cu"), // 0x94
  new Letters("cug"), // 0x95
  new Letters("cugg"), // 0x96
  new Letters("cugs"), // 0x97
  new Letters("cun"), // 0x98
  new Letters("cunj"), // 0x99
  new Letters("cunh"), // 0x9a
  new Letters("cud"), // 0x9b
  new Letters("cul"), // 0x9c
  new Letters("culg"), // 0x9d
  new Letters("culm"), // 0x9e
  new Letters("culb"), // 0x9f
  new Letters("culs"), // 0xa0
  new Letters("cult"), // 0xa1
  new Letters("culp"), // 0xa2
  new Letters("culh"), // 0xa3
  new Letters("cum"), // 0xa4
  new Letters("cub"), // 0xa5
  new Letters("cubs"), // 0xa6
  new Letters("cus"), // 0xa7
  new Letters("cuss"), // 0xa8
  new Letters("cung"), // 0xa9
  new Letters("cuj"), // 0xaa
  new Letters("cuc"), // 0xab
  new Letters("cuk"), // 0xac
  new Letters("cut"), // 0xad
  new Letters("cup"), // 0xae
  new Letters("cuh"), // 0xaf
  new Letters("cweo"), // 0xb0
  new Letters("cweog"), // 0xb1
  new Letters("cweogg"), // 0xb2
  new Letters("cweogs"), // 0xb3
  new Letters("cweon"), // 0xb4
  new Letters("cweonj"), // 0xb5
  new Letters("cweonh"), // 0xb6
  new Letters("cweod"), // 0xb7
  new Letters("cweol"), // 0xb8
  new Letters("cweolg"), // 0xb9
  new Letters("cweolm"), // 0xba
  new Letters("cweolb"), // 0xbb
  new Letters("cweols"), // 0xbc
  new Letters("cweolt"), // 0xbd
  new Letters("cweolp"), // 0xbe
  new Letters("cweolh"), // 0xbf
  new Letters("cweom"), // 0xc0
  new Letters("cweob"), // 0xc1
  new Letters("cweobs"), // 0xc2
  new Letters("cweos"), // 0xc3
  new Letters("cweoss"), // 0xc4
  new Letters("cweong"), // 0xc5
  new Letters("cweoj"), // 0xc6
  new Letters("cweoc"), // 0xc7
  new Letters("cweok"), // 0xc8
  new Letters("cweot"), // 0xc9
  new Letters("cweop"), // 0xca
  new Letters("cweoh"), // 0xcb
  new Letters("cwe"), // 0xcc
  new Letters("cweg"), // 0xcd
  new Letters("cwegg"), // 0xce
  new Letters("cwegs"), // 0xcf
  new Letters("cwen"), // 0xd0
  new Letters("cwenj"), // 0xd1
  new Letters("cwenh"), // 0xd2
  new Letters("cwed"), // 0xd3
  new Letters("cwel"), // 0xd4
  new Letters("cwelg"), // 0xd5
  new Letters("cwelm"), // 0xd6
  new Letters("cwelb"), // 0xd7
  new Letters("cwels"), // 0xd8
  new Letters("cwelt"), // 0xd9
  new Letters("cwelp"), // 0xda
  new Letters("cwelh"), // 0xdb
  new Letters("cwem"), // 0xdc
  new Letters("cweb"), // 0xdd
  new Letters("cwebs"), // 0xde
  new Letters("cwes"), // 0xdf
  new Letters("cwess"), // 0xe0
  new Letters("cweng"), // 0xe1
  new Letters("cwej"), // 0xe2
  new Letters("cwec"), // 0xe3
  new Letters("cwek"), // 0xe4
  new Letters("cwet"), // 0xe5
  new Letters("cwep"), // 0xe6
  new Letters("cweh"), // 0xe7
  new Letters("cwi"), // 0xe8
  new Letters("cwig"), // 0xe9
  new Letters("cwigg"), // 0xea
  new Letters("cwigs"), // 0xeb
  new Letters("cwin"), // 0xec
  new Letters("cwinj"), // 0xed
  new Letters("cwinh"), // 0xee
  new Letters("cwid"), // 0xef
  new Letters("cwil"), // 0xf0
  new Letters("cwilg"), // 0xf1
  new Letters("cwilm"), // 0xf2
  new Letters("cwilb"), // 0xf3
  new Letters("cwils"), // 0xf4
  new Letters("cwilt"), // 0xf5
  new Letters("cwilp"), // 0xf6
  new Letters("cwilh"), // 0xf7
  new Letters("cwim"), // 0xf8
  new Letters("cwib"), // 0xf9
  new Letters("cwibs"), // 0xfa
  new Letters("cwis"), // 0xfb
  new Letters("cwiss"), // 0xfc
  new Letters("cwing"), // 0xfd
  new Letters("cwij"), // 0xfe
  new Letters("cwic") // 0xff
  };
}