/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+CExx (Hangul Syllables for Korean).
 */
final class Xce extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("cwik"), // 0x00
  new Letters("cwit"), // 0x01
  new Letters("cwip"), // 0x02
  new Letters("cwih"), // 0x03
  new Letters("cyu"), // 0x04
  new Letters("cyug"), // 0x05
  new Letters("cyugg"), // 0x06
  new Letters("cyugs"), // 0x07
  new Letters("cyun"), // 0x08
  new Letters("cyunj"), // 0x09
  new Letters("cyunh"), // 0x0a
  new Letters("cyud"), // 0x0b
  new Letters("cyul"), // 0x0c
  new Letters("cyulg"), // 0x0d
  new Letters("cyulm"), // 0x0e
  new Letters("cyulb"), // 0x0f
  new Letters("cyuls"), // 0x10
  new Letters("cyult"), // 0x11
  new Letters("cyulp"), // 0x12
  new Letters("cyulh"), // 0x13
  new Letters("cyum"), // 0x14
  new Letters("cyub"), // 0x15
  new Letters("cyubs"), // 0x16
  new Letters("cyus"), // 0x17
  new Letters("cyuss"), // 0x18
  new Letters("cyung"), // 0x19
  new Letters("cyuj"), // 0x1a
  new Letters("cyuc"), // 0x1b
  new Letters("cyuk"), // 0x1c
  new Letters("cyut"), // 0x1d
  new Letters("cyup"), // 0x1e
  new Letters("cyuh"), // 0x1f
  new Letters("ceu"), // 0x20
  new Letters("ceug"), // 0x21
  new Letters("ceugg"), // 0x22
  new Letters("ceugs"), // 0x23
  new Letters("ceun"), // 0x24
  new Letters("ceunj"), // 0x25
  new Letters("ceunh"), // 0x26
  new Letters("ceud"), // 0x27
  new Letters("ceul"), // 0x28
  new Letters("ceulg"), // 0x29
  new Letters("ceulm"), // 0x2a
  new Letters("ceulb"), // 0x2b
  new Letters("ceuls"), // 0x2c
  new Letters("ceult"), // 0x2d
  new Letters("ceulp"), // 0x2e
  new Letters("ceulh"), // 0x2f
  new Letters("ceum"), // 0x30
  new Letters("ceub"), // 0x31
  new Letters("ceubs"), // 0x32
  new Letters("ceus"), // 0x33
  new Letters("ceuss"), // 0x34
  new Letters("ceung"), // 0x35
  new Letters("ceuj"), // 0x36
  new Letters("ceuc"), // 0x37
  new Letters("ceuk"), // 0x38
  new Letters("ceut"), // 0x39
  new Letters("ceup"), // 0x3a
  new Letters("ceuh"), // 0x3b
  new Letters("cyi"), // 0x3c
  new Letters("cyig"), // 0x3d
  new Letters("cyigg"), // 0x3e
  new Letters("cyigs"), // 0x3f
  new Letters("cyin"), // 0x40
  new Letters("cyinj"), // 0x41
  new Letters("cyinh"), // 0x42
  new Letters("cyid"), // 0x43
  new Letters("cyil"), // 0x44
  new Letters("cyilg"), // 0x45
  new Letters("cyilm"), // 0x46
  new Letters("cyilb"), // 0x47
  new Letters("cyils"), // 0x48
  new Letters("cyilt"), // 0x49
  new Letters("cyilp"), // 0x4a
  new Letters("cyilh"), // 0x4b
  new Letters("cyim"), // 0x4c
  new Letters("cyib"), // 0x4d
  new Letters("cyibs"), // 0x4e
  new Letters("cyis"), // 0x4f
  new Letters("cyiss"), // 0x50
  new Letters("cying"), // 0x51
  new Letters("cyij"), // 0x52
  new Letters("cyic"), // 0x53
  new Letters("cyik"), // 0x54
  new Letters("cyit"), // 0x55
  new Letters("cyip"), // 0x56
  new Letters("cyih"), // 0x57
  new Letters("ci"), // 0x58
  new Letters("cig"), // 0x59
  new Letters("cigg"), // 0x5a
  new Letters("cigs"), // 0x5b
  new Letters("cin"), // 0x5c
  new Letters("cinj"), // 0x5d
  new Letters("cinh"), // 0x5e
  new Letters("cid"), // 0x5f
  new Letters("cil"), // 0x60
  new Letters("cilg"), // 0x61
  new Letters("cilm"), // 0x62
  new Letters("cilb"), // 0x63
  new Letters("cils"), // 0x64
  new Letters("cilt"), // 0x65
  new Letters("cilp"), // 0x66
  new Letters("cilh"), // 0x67
  new Letters("cim"), // 0x68
  new Letters("cib"), // 0x69
  new Letters("cibs"), // 0x6a
  new Letters("cis"), // 0x6b
  new Letters("ciss"), // 0x6c
  new Letters("cing"), // 0x6d
  new Letters("cij"), // 0x6e
  new Letters("cic"), // 0x6f
  new Letters("cik"), // 0x70
  new Letters("cit"), // 0x71
  new Letters("cip"), // 0x72
  new Letters("cih"), // 0x73
  LO_KA, // 0x74
  new Letters("kag"), // 0x75
  new Letters("kagg"), // 0x76
  new Letters("kags"), // 0x77
  new Letters("kan"), // 0x78
  new Letters("kanj"), // 0x79
  new Letters("kanh"), // 0x7a
  new Letters("kad"), // 0x7b
  new Letters("kal"), // 0x7c
  new Letters("kalg"), // 0x7d
  new Letters("kalm"), // 0x7e
  new Letters("kalb"), // 0x7f
  new Letters("kals"), // 0x80
  new Letters("kalt"), // 0x81
  new Letters("kalp"), // 0x82
  new Letters("kalh"), // 0x83
  new Letters("kam"), // 0x84
  new Letters("kab"), // 0x85
  new Letters("kabs"), // 0x86
  new Letters("kas"), // 0x87
  new Letters("kass"), // 0x88
  new Letters("kang"), // 0x89
  new Letters("kaj"), // 0x8a
  new Letters("kac"), // 0x8b
  new Letters("kak"), // 0x8c
  new Letters("kat"), // 0x8d
  new Letters("kap"), // 0x8e
  new Letters("kah"), // 0x8f
  new Letters("kae"), // 0x90
  new Letters("kaeg"), // 0x91
  new Letters("kaegg"), // 0x92
  new Letters("kaegs"), // 0x93
  new Letters("kaen"), // 0x94
  new Letters("kaenj"), // 0x95
  new Letters("kaenh"), // 0x96
  new Letters("kaed"), // 0x97
  new Letters("kael"), // 0x98
  new Letters("kaelg"), // 0x99
  new Letters("kaelm"), // 0x9a
  new Letters("kaelb"), // 0x9b
  new Letters("kaels"), // 0x9c
  new Letters("kaelt"), // 0x9d
  new Letters("kaelp"), // 0x9e
  new Letters("kaelh"), // 0x9f
  new Letters("kaem"), // 0xa0
  new Letters("kaeb"), // 0xa1
  new Letters("kaebs"), // 0xa2
  new Letters("kaes"), // 0xa3
  new Letters("kaess"), // 0xa4
  new Letters("kaeng"), // 0xa5
  new Letters("kaej"), // 0xa6
  new Letters("kaec"), // 0xa7
  new Letters("kaek"), // 0xa8
  new Letters("kaet"), // 0xa9
  new Letters("kaep"), // 0xaa
  new Letters("kaeh"), // 0xab
  new Letters("kya"), // 0xac
  new Letters("kyag"), // 0xad
  new Letters("kyagg"), // 0xae
  new Letters("kyags"), // 0xaf
  new Letters("kyan"), // 0xb0
  new Letters("kyanj"), // 0xb1
  new Letters("kyanh"), // 0xb2
  new Letters("kyad"), // 0xb3
  new Letters("kyal"), // 0xb4
  new Letters("kyalg"), // 0xb5
  new Letters("kyalm"), // 0xb6
  new Letters("kyalb"), // 0xb7
  new Letters("kyals"), // 0xb8
  new Letters("kyalt"), // 0xb9
  new Letters("kyalp"), // 0xba
  new Letters("kyalh"), // 0xbb
  new Letters("kyam"), // 0xbc
  new Letters("kyab"), // 0xbd
  new Letters("kyabs"), // 0xbe
  new Letters("kyas"), // 0xbf
  new Letters("kyass"), // 0xc0
  new Letters("kyang"), // 0xc1
  new Letters("kyaj"), // 0xc2
  new Letters("kyac"), // 0xc3
  new Letters("kyak"), // 0xc4
  new Letters("kyat"), // 0xc5
  new Letters("kyap"), // 0xc6
  new Letters("kyah"), // 0xc7
  new Letters("kyae"), // 0xc8
  new Letters("kyaeg"), // 0xc9
  new Letters("kyaegg"), // 0xca
  new Letters("kyaegs"), // 0xcb
  new Letters("kyaen"), // 0xcc
  new Letters("kyaenj"), // 0xcd
  new Letters("kyaenh"), // 0xce
  new Letters("kyaed"), // 0xcf
  new Letters("kyael"), // 0xd0
  new Letters("kyaelg"), // 0xd1
  new Letters("kyaelm"), // 0xd2
  new Letters("kyaelb"), // 0xd3
  new Letters("kyaels"), // 0xd4
  new Letters("kyaelt"), // 0xd5
  new Letters("kyaelp"), // 0xd6
  new Letters("kyaelh"), // 0xd7
  new Letters("kyaem"), // 0xd8
  new Letters("kyaeb"), // 0xd9
  new Letters("kyaebs"), // 0xda
  new Letters("kyaes"), // 0xdb
  new Letters("kyaess"), // 0xdc
  new Letters("kyaeng"), // 0xdd
  new Letters("kyaej"), // 0xde
  new Letters("kyaec"), // 0xdf
  new Letters("kyaek"), // 0xe0
  new Letters("kyaet"), // 0xe1
  new Letters("kyaep"), // 0xe2
  new Letters("kyaeh"), // 0xe3
  new Letters("keo"), // 0xe4
  new Letters("keog"), // 0xe5
  new Letters("keogg"), // 0xe6
  new Letters("keogs"), // 0xe7
  new Letters("keon"), // 0xe8
  new Letters("keonj"), // 0xe9
  new Letters("keonh"), // 0xea
  new Letters("keod"), // 0xeb
  new Letters("keol"), // 0xec
  new Letters("keolg"), // 0xed
  new Letters("keolm"), // 0xee
  new Letters("keolb"), // 0xef
  new Letters("keols"), // 0xf0
  new Letters("keolt"), // 0xf1
  new Letters("keolp"), // 0xf2
  new Letters("keolh"), // 0xf3
  new Letters("keom"), // 0xf4
  new Letters("keob"), // 0xf5
  new Letters("keobs"), // 0xf6
  new Letters("keos"), // 0xf7
  new Letters("keoss"), // 0xf8
  new Letters("keong"), // 0xf9
  new Letters("keoj"), // 0xfa
  new Letters("keoc"), // 0xfb
  new Letters("keok"), // 0xfc
  new Letters("keot"), // 0xfd
  new Letters("keop"), // 0xfe
  new Letters("keoh") // 0xff
  };
}