/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+D0xx (Hangul Syllables for Korean).
 */
final class Xd0 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("kweon"), // 0x00
  new Letters("kweonj"), // 0x01
  new Letters("kweonh"), // 0x02
  new Letters("kweod"), // 0x03
  new Letters("kweol"), // 0x04
  new Letters("kweolg"), // 0x05
  new Letters("kweolm"), // 0x06
  new Letters("kweolb"), // 0x07
  new Letters("kweols"), // 0x08
  new Letters("kweolt"), // 0x09
  new Letters("kweolp"), // 0x0a
  new Letters("kweolh"), // 0x0b
  new Letters("kweom"), // 0x0c
  new Letters("kweob"), // 0x0d
  new Letters("kweobs"), // 0x0e
  new Letters("kweos"), // 0x0f
  new Letters("kweoss"), // 0x10
  new Letters("kweong"), // 0x11
  new Letters("kweoj"), // 0x12
  new Letters("kweoc"), // 0x13
  new Letters("kweok"), // 0x14
  new Letters("kweot"), // 0x15
  new Letters("kweop"), // 0x16
  new Letters("kweoh"), // 0x17
  new Letters("kwe"), // 0x18
  new Letters("kweg"), // 0x19
  new Letters("kwegg"), // 0x1a
  new Letters("kwegs"), // 0x1b
  new Letters("kwen"), // 0x1c
  new Letters("kwenj"), // 0x1d
  new Letters("kwenh"), // 0x1e
  new Letters("kwed"), // 0x1f
  new Letters("kwel"), // 0x20
  new Letters("kwelg"), // 0x21
  new Letters("kwelm"), // 0x22
  new Letters("kwelb"), // 0x23
  new Letters("kwels"), // 0x24
  new Letters("kwelt"), // 0x25
  new Letters("kwelp"), // 0x26
  new Letters("kwelh"), // 0x27
  new Letters("kwem"), // 0x28
  new Letters("kweb"), // 0x29
  new Letters("kwebs"), // 0x2a
  new Letters("kwes"), // 0x2b
  new Letters("kwess"), // 0x2c
  new Letters("kweng"), // 0x2d
  new Letters("kwej"), // 0x2e
  new Letters("kwec"), // 0x2f
  new Letters("kwek"), // 0x30
  new Letters("kwet"), // 0x31
  new Letters("kwep"), // 0x32
  new Letters("kweh"), // 0x33
  new Letters("kwi"), // 0x34
  new Letters("kwig"), // 0x35
  new Letters("kwigg"), // 0x36
  new Letters("kwigs"), // 0x37
  new Letters("kwin"), // 0x38
  new Letters("kwinj"), // 0x39
  new Letters("kwinh"), // 0x3a
  new Letters("kwid"), // 0x3b
  new Letters("kwil"), // 0x3c
  new Letters("kwilg"), // 0x3d
  new Letters("kwilm"), // 0x3e
  new Letters("kwilb"), // 0x3f
  new Letters("kwils"), // 0x40
  new Letters("kwilt"), // 0x41
  new Letters("kwilp"), // 0x42
  new Letters("kwilh"), // 0x43
  new Letters("kwim"), // 0x44
  new Letters("kwib"), // 0x45
  new Letters("kwibs"), // 0x46
  new Letters("kwis"), // 0x47
  new Letters("kwiss"), // 0x48
  new Letters("kwing"), // 0x49
  new Letters("kwij"), // 0x4a
  new Letters("kwic"), // 0x4b
  new Letters("kwik"), // 0x4c
  new Letters("kwit"), // 0x4d
  new Letters("kwip"), // 0x4e
  new Letters("kwih"), // 0x4f
  new Letters("kyu"), // 0x50
  new Letters("kyug"), // 0x51
  new Letters("kyugg"), // 0x52
  new Letters("kyugs"), // 0x53
  new Letters("kyun"), // 0x54
  new Letters("kyunj"), // 0x55
  new Letters("kyunh"), // 0x56
  new Letters("kyud"), // 0x57
  new Letters("kyul"), // 0x58
  new Letters("kyulg"), // 0x59
  new Letters("kyulm"), // 0x5a
  new Letters("kyulb"), // 0x5b
  new Letters("kyuls"), // 0x5c
  new Letters("kyult"), // 0x5d
  new Letters("kyulp"), // 0x5e
  new Letters("kyulh"), // 0x5f
  new Letters("kyum"), // 0x60
  new Letters("kyub"), // 0x61
  new Letters("kyubs"), // 0x62
  new Letters("kyus"), // 0x63
  new Letters("kyuss"), // 0x64
  new Letters("kyung"), // 0x65
  new Letters("kyuj"), // 0x66
  new Letters("kyuc"), // 0x67
  new Letters("kyuk"), // 0x68
  new Letters("kyut"), // 0x69
  new Letters("kyup"), // 0x6a
  new Letters("kyuh"), // 0x6b
  new Letters("keu"), // 0x6c
  new Letters("keug"), // 0x6d
  new Letters("keugg"), // 0x6e
  new Letters("keugs"), // 0x6f
  new Letters("keun"), // 0x70
  new Letters("keunj"), // 0x71
  new Letters("keunh"), // 0x72
  new Letters("keud"), // 0x73
  new Letters("keul"), // 0x74
  new Letters("keulg"), // 0x75
  new Letters("keulm"), // 0x76
  new Letters("keulb"), // 0x77
  new Letters("keuls"), // 0x78
  new Letters("keult"), // 0x79
  new Letters("keulp"), // 0x7a
  new Letters("keulh"), // 0x7b
  new Letters("keum"), // 0x7c
  new Letters("keub"), // 0x7d
  new Letters("keubs"), // 0x7e
  new Letters("keus"), // 0x7f
  new Letters("keuss"), // 0x80
  new Letters("keung"), // 0x81
  new Letters("keuj"), // 0x82
  new Letters("keuc"), // 0x83
  new Letters("keuk"), // 0x84
  new Letters("keut"), // 0x85
  new Letters("keup"), // 0x86
  new Letters("keuh"), // 0x87
  new Letters("kyi"), // 0x88
  new Letters("kyig"), // 0x89
  new Letters("kyigg"), // 0x8a
  new Letters("kyigs"), // 0x8b
  new Letters("kyin"), // 0x8c
  new Letters("kyinj"), // 0x8d
  new Letters("kyinh"), // 0x8e
  new Letters("kyid"), // 0x8f
  new Letters("kyil"), // 0x90
  new Letters("kyilg"), // 0x91
  new Letters("kyilm"), // 0x92
  new Letters("kyilb"), // 0x93
  new Letters("kyils"), // 0x94
  new Letters("kyilt"), // 0x95
  new Letters("kyilp"), // 0x96
  new Letters("kyilh"), // 0x97
  new Letters("kyim"), // 0x98
  new Letters("kyib"), // 0x99
  new Letters("kyibs"), // 0x9a
  new Letters("kyis"), // 0x9b
  new Letters("kyiss"), // 0x9c
  new Letters("kying"), // 0x9d
  new Letters("kyij"), // 0x9e
  new Letters("kyic"), // 0x9f
  new Letters("kyik"), // 0xa0
  new Letters("kyit"), // 0xa1
  new Letters("kyip"), // 0xa2
  new Letters("kyih"), // 0xa3
  LO_KI, // 0xa4
  new Letters("kig"), // 0xa5
  new Letters("kigg"), // 0xa6
  new Letters("kigs"), // 0xa7
  new Letters("kin"), // 0xa8
  new Letters("kinj"), // 0xa9
  new Letters("kinh"), // 0xaa
  new Letters("kid"), // 0xab
  new Letters("kil"), // 0xac
  new Letters("kilg"), // 0xad
  new Letters("kilm"), // 0xae
  new Letters("kilb"), // 0xaf
  new Letters("kils"), // 0xb0
  new Letters("kilt"), // 0xb1
  new Letters("kilp"), // 0xb2
  new Letters("kilh"), // 0xb3
  new Letters("kim"), // 0xb4
  new Letters("kib"), // 0xb5
  new Letters("kibs"), // 0xb6
  new Letters("kis"), // 0xb7
  new Letters("kiss"), // 0xb8
  new Letters("king"), // 0xb9
  new Letters("kij"), // 0xba
  new Letters("kic"), // 0xbb
  new Letters("kik"), // 0xbc
  new Letters("kit"), // 0xbd
  new Letters("kip"), // 0xbe
  new Letters("kih"), // 0xbf
  LO_TA, // 0xc0
  new Letters("tag"), // 0xc1
  new Letters("tagg"), // 0xc2
  new Letters("tags"), // 0xc3
  new Letters("tan"), // 0xc4
  new Letters("tanj"), // 0xc5
  new Letters("tanh"), // 0xc6
  new Letters("tad"), // 0xc7
  new Letters("tal"), // 0xc8
  new Letters("talg"), // 0xc9
  new Letters("talm"), // 0xca
  new Letters("talb"), // 0xcb
  new Letters("tals"), // 0xcc
  new Letters("talt"), // 0xcd
  new Letters("talp"), // 0xce
  new Letters("talh"), // 0xcf
  new Letters("tam"), // 0xd0
  new Letters("tab"), // 0xd1
  new Letters("tabs"), // 0xd2
  new Letters("tas"), // 0xd3
  new Letters("tass"), // 0xd4
  new Letters("tang"), // 0xd5
  new Letters("taj"), // 0xd6
  new Letters("tac"), // 0xd7
  new Letters("tak"), // 0xd8
  new Letters("tat"), // 0xd9
  new Letters("tap"), // 0xda
  new Letters("tah"), // 0xdb
  new Letters("tae"), // 0xdc
  new Letters("taeg"), // 0xdd
  new Letters("taegg"), // 0xde
  new Letters("taegs"), // 0xdf
  new Letters("taen"), // 0xe0
  new Letters("taenj"), // 0xe1
  new Letters("taenh"), // 0xe2
  new Letters("taed"), // 0xe3
  new Letters("tael"), // 0xe4
  new Letters("taelg"), // 0xe5
  new Letters("taelm"), // 0xe6
  new Letters("taelb"), // 0xe7
  new Letters("taels"), // 0xe8
  new Letters("taelt"), // 0xe9
  new Letters("taelp"), // 0xea
  new Letters("taelh"), // 0xeb
  new Letters("taem"), // 0xec
  new Letters("taeb"), // 0xed
  new Letters("taebs"), // 0xee
  new Letters("taes"), // 0xef
  new Letters("taess"), // 0xf0
  new Letters("taeng"), // 0xf1
  new Letters("taej"), // 0xf2
  new Letters("taec"), // 0xf3
  new Letters("taek"), // 0xf4
  new Letters("taet"), // 0xf5
  new Letters("taep"), // 0xf6
  new Letters("taeh"), // 0xf7
  new Letters("tya"), // 0xf8
  new Letters("tyag"), // 0xf9
  new Letters("tyagg"), // 0xfa
  new Letters("tyags"), // 0xfb
  new Letters("tyan"), // 0xfc
  new Letters("tyanj"), // 0xfd
  new Letters("tyanh"), // 0xfe
  new Letters("tyad") // 0xff
  };
}