/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+D1xx (Hangul Syllables for Korean).
 */
final class Xd1 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("tyal"), // 0x00
  new Letters("tyalg"), // 0x01
  new Letters("tyalm"), // 0x02
  new Letters("tyalb"), // 0x03
  new Letters("tyals"), // 0x04
  new Letters("tyalt"), // 0x05
  new Letters("tyalp"), // 0x06
  new Letters("tyalh"), // 0x07
  new Letters("tyam"), // 0x08
  new Letters("tyab"), // 0x09
  new Letters("tyabs"), // 0x0a
  new Letters("tyas"), // 0x0b
  new Letters("tyass"), // 0x0c
  new Letters("tyang"), // 0x0d
  new Letters("tyaj"), // 0x0e
  new Letters("tyac"), // 0x0f
  new Letters("tyak"), // 0x10
  new Letters("tyat"), // 0x11
  new Letters("tyap"), // 0x12
  new Letters("tyah"), // 0x13
  new Letters("tyae"), // 0x14
  new Letters("tyaeg"), // 0x15
  new Letters("tyaegg"), // 0x16
  new Letters("tyaegs"), // 0x17
  new Letters("tyaen"), // 0x18
  new Letters("tyaenj"), // 0x19
  new Letters("tyaenh"), // 0x1a
  new Letters("tyaed"), // 0x1b
  new Letters("tyael"), // 0x1c
  new Letters("tyaelg"), // 0x1d
  new Letters("tyaelm"), // 0x1e
  new Letters("tyaelb"), // 0x1f
  new Letters("tyaels"), // 0x20
  new Letters("tyaelt"), // 0x21
  new Letters("tyaelp"), // 0x22
  new Letters("tyaelh"), // 0x23
  new Letters("tyaem"), // 0x24
  new Letters("tyaeb"), // 0x25
  new Letters("tyaebs"), // 0x26
  new Letters("tyaes"), // 0x27
  new Letters("tyaess"), // 0x28
  new Letters("tyaeng"), // 0x29
  new Letters("tyaej"), // 0x2a
  new Letters("tyaec"), // 0x2b
  new Letters("tyaek"), // 0x2c
  new Letters("tyaet"), // 0x2d
  new Letters("tyaep"), // 0x2e
  new Letters("tyaeh"), // 0x2f
  new Letters("teo"), // 0x30
  new Letters("teog"), // 0x31
  new Letters("teogg"), // 0x32
  new Letters("teogs"), // 0x33
  new Letters("teon"), // 0x34
  new Letters("teonj"), // 0x35
  new Letters("teonh"), // 0x36
  new Letters("teod"), // 0x37
  new Letters("teol"), // 0x38
  new Letters("teolg"), // 0x39
  new Letters("teolm"), // 0x3a
  new Letters("teolb"), // 0x3b
  new Letters("teols"), // 0x3c
  new Letters("teolt"), // 0x3d
  new Letters("teolp"), // 0x3e
  new Letters("teolh"), // 0x3f
  new Letters("teom"), // 0x40
  new Letters("teob"), // 0x41
  new Letters("teobs"), // 0x42
  new Letters("teos"), // 0x43
  new Letters("teoss"), // 0x44
  new Letters("teong"), // 0x45
  new Letters("teoj"), // 0x46
  new Letters("teoc"), // 0x47
  new Letters("teok"), // 0x48
  new Letters("teot"), // 0x49
  new Letters("teop"), // 0x4a
  new Letters("teoh"), // 0x4b
  LO_TE, // 0x4c
  new Letters("teg"), // 0x4d
  new Letters("tegg"), // 0x4e
  new Letters("tegs"), // 0x4f
  new Letters("ten"), // 0x50
  new Letters("tenj"), // 0x51
  new Letters("tenh"), // 0x52
  new Letters("ted"), // 0x53
  new Letters("tel"), // 0x54
  new Letters("telg"), // 0x55
  new Letters("telm"), // 0x56
  new Letters("telb"), // 0x57
  new Letters("tels"), // 0x58
  new Letters("telt"), // 0x59
  new Letters("telp"), // 0x5a
  new Letters("telh"), // 0x5b
  new Letters("tem"), // 0x5c
  new Letters("teb"), // 0x5d
  new Letters("tebs"), // 0x5e
  new Letters("tes"), // 0x5f
  new Letters("tess"), // 0x60
  new Letters("teng"), // 0x61
  new Letters("tej"), // 0x62
  new Letters("tec"), // 0x63
  new Letters("tek"), // 0x64
  new Letters("tet"), // 0x65
  new Letters("tep"), // 0x66
  new Letters("teh"), // 0x67
  new Letters("tyeo"), // 0x68
  new Letters("tyeog"), // 0x69
  new Letters("tyeogg"), // 0x6a
  new Letters("tyeogs"), // 0x6b
  new Letters("tyeon"), // 0x6c
  new Letters("tyeonj"), // 0x6d
  new Letters("tyeonh"), // 0x6e
  new Letters("tyeod"), // 0x6f
  new Letters("tyeol"), // 0x70
  new Letters("tyeolg"), // 0x71
  new Letters("tyeolm"), // 0x72
  new Letters("tyeolb"), // 0x73
  new Letters("tyeols"), // 0x74
  new Letters("tyeolt"), // 0x75
  new Letters("tyeolp"), // 0x76
  new Letters("tyeolh"), // 0x77
  new Letters("tyeom"), // 0x78
  new Letters("tyeob"), // 0x79
  new Letters("tyeobs"), // 0x7a
  new Letters("tyeos"), // 0x7b
  new Letters("tyeoss"), // 0x7c
  new Letters("tyeong"), // 0x7d
  new Letters("tyeoj"), // 0x7e
  new Letters("tyeoc"), // 0x7f
  new Letters("tyeok"), // 0x80
  new Letters("tyeot"), // 0x81
  new Letters("tyeop"), // 0x82
  new Letters("tyeoh"), // 0x83
  new Letters("tye"), // 0x84
  new Letters("tyeg"), // 0x85
  new Letters("tyegg"), // 0x86
  new Letters("tyegs"), // 0x87
  new Letters("tyen"), // 0x88
  new Letters("tyenj"), // 0x89
  new Letters("tyenh"), // 0x8a
  new Letters("tyed"), // 0x8b
  new Letters("tyel"), // 0x8c
  new Letters("tyelg"), // 0x8d
  new Letters("tyelm"), // 0x8e
  new Letters("tyelb"), // 0x8f
  new Letters("tyels"), // 0x90
  new Letters("tyelt"), // 0x91
  new Letters("tyelp"), // 0x92
  new Letters("tyelh"), // 0x93
  new Letters("tyem"), // 0x94
  new Letters("tyeb"), // 0x95
  new Letters("tyebs"), // 0x96
  new Letters("tyes"), // 0x97
  new Letters("tyess"), // 0x98
  new Letters("tyeng"), // 0x99
  new Letters("tyej"), // 0x9a
  new Letters("tyec"), // 0x9b
  new Letters("tyek"), // 0x9c
  new Letters("tyet"), // 0x9d
  new Letters("tyep"), // 0x9e
  new Letters("tyeh"), // 0x9f
  LO_TO, // 0xa0
  new Letters("tog"), // 0xa1
  new Letters("togg"), // 0xa2
  new Letters("togs"), // 0xa3
  new Letters("ton"), // 0xa4
  new Letters("tonj"), // 0xa5
  new Letters("tonh"), // 0xa6
  new Letters("tod"), // 0xa7
  new Letters("tol"), // 0xa8
  new Letters("tolg"), // 0xa9
  new Letters("tolm"), // 0xaa
  new Letters("tolb"), // 0xab
  new Letters("tols"), // 0xac
  new Letters("tolt"), // 0xad
  new Letters("tolp"), // 0xae
  new Letters("tolh"), // 0xaf
  new Letters("tom"), // 0xb0
  new Letters("tob"), // 0xb1
  new Letters("tobs"), // 0xb2
  new Letters("tos"), // 0xb3
  new Letters("toss"), // 0xb4
  new Letters("tong"), // 0xb5
  new Letters("toj"), // 0xb6
  new Letters("toc"), // 0xb7
  new Letters("tok"), // 0xb8
  new Letters("tot"), // 0xb9
  new Letters("top"), // 0xba
  new Letters("toh"), // 0xbb
  new Letters("twa"), // 0xbc
  new Letters("twag"), // 0xbd
  new Letters("twagg"), // 0xbe
  new Letters("twags"), // 0xbf
  new Letters("twan"), // 0xc0
  new Letters("twanj"), // 0xc1
  new Letters("twanh"), // 0xc2
  new Letters("twad"), // 0xc3
  new Letters("twal"), // 0xc4
  new Letters("twalg"), // 0xc5
  new Letters("twalm"), // 0xc6
  new Letters("twalb"), // 0xc7
  new Letters("twals"), // 0xc8
  new Letters("twalt"), // 0xc9
  new Letters("twalp"), // 0xca
  new Letters("twalh"), // 0xcb
  new Letters("twam"), // 0xcc
  new Letters("twab"), // 0xcd
  new Letters("twabs"), // 0xce
  new Letters("twas"), // 0xcf
  new Letters("twass"), // 0xd0
  new Letters("twang"), // 0xd1
  new Letters("twaj"), // 0xd2
  new Letters("twac"), // 0xd3
  new Letters("twak"), // 0xd4
  new Letters("twat"), // 0xd5
  new Letters("twap"), // 0xd6
  new Letters("twah"), // 0xd7
  new Letters("twae"), // 0xd8
  new Letters("twaeg"), // 0xd9
  new Letters("twaegg"), // 0xda
  new Letters("twaegs"), // 0xdb
  new Letters("twaen"), // 0xdc
  new Letters("twaenj"), // 0xdd
  new Letters("twaenh"), // 0xde
  new Letters("twaed"), // 0xdf
  new Letters("twael"), // 0xe0
  new Letters("twaelg"), // 0xe1
  new Letters("twaelm"), // 0xe2
  new Letters("twaelb"), // 0xe3
  new Letters("twaels"), // 0xe4
  new Letters("twaelt"), // 0xe5
  new Letters("twaelp"), // 0xe6
  new Letters("twaelh"), // 0xe7
  new Letters("twaem"), // 0xe8
  new Letters("twaeb"), // 0xe9
  new Letters("twaebs"), // 0xea
  new Letters("twaes"), // 0xeb
  new Letters("twaess"), // 0xec
  new Letters("twaeng"), // 0xed
  new Letters("twaej"), // 0xee
  new Letters("twaec"), // 0xef
  new Letters("twaek"), // 0xf0
  new Letters("twaet"), // 0xf1
  new Letters("twaep"), // 0xf2
  new Letters("twaeh"), // 0xf3
  new Letters("toe"), // 0xf4
  new Letters("toeg"), // 0xf5
  new Letters("toegg"), // 0xf6
  new Letters("toegs"), // 0xf7
  new Letters("toen"), // 0xf8
  new Letters("toenj"), // 0xf9
  new Letters("toenh"), // 0xfa
  new Letters("toed"), // 0xfb
  new Letters("toel"), // 0xfc
  new Letters("toelg"), // 0xfd
  new Letters("toelm"), // 0xfe
  new Letters("toelb") // 0xff
  };
}