/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+D3xx (Hangul Syllables for Korean).
 */
final class Xd3 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("tim"), // 0x00
  new Letters("tib"), // 0x01
  new Letters("tibs"), // 0x02
  new Letters("tis"), // 0x03
  new Letters("tiss"), // 0x04
  new Letters("ting"), // 0x05
  new Letters("tij"), // 0x06
  new Letters("tic"), // 0x07
  new Letters("tik"), // 0x08
  new Letters("tit"), // 0x09
  new Letters("tip"), // 0x0a
  new Letters("tih"), // 0x0b
  LO_PA, // 0x0c
  new Letters("pag"), // 0x0d
  new Letters("pagg"), // 0x0e
  new Letters("pags"), // 0x0f
  new Letters("pan"), // 0x10
  new Letters("panj"), // 0x11
  new Letters("panh"), // 0x12
  new Letters("pad"), // 0x13
  new Letters("pal"), // 0x14
  new Letters("palg"), // 0x15
  new Letters("palm"), // 0x16
  new Letters("palb"), // 0x17
  new Letters("pals"), // 0x18
  new Letters("palt"), // 0x19
  new Letters("palp"), // 0x1a
  new Letters("palh"), // 0x1b
  new Letters("pam"), // 0x1c
  new Letters("pab"), // 0x1d
  new Letters("pabs"), // 0x1e
  new Letters("pas"), // 0x1f
  new Letters("pass"), // 0x20
  new Letters("pang"), // 0x21
  new Letters("paj"), // 0x22
  new Letters("pac"), // 0x23
  new Letters("pak"), // 0x24
  new Letters("pat"), // 0x25
  new Letters("pap"), // 0x26
  new Letters("pah"), // 0x27
  new Letters("pae"), // 0x28
  new Letters("paeg"), // 0x29
  new Letters("paegg"), // 0x2a
  new Letters("paegs"), // 0x2b
  new Letters("paen"), // 0x2c
  new Letters("paenj"), // 0x2d
  new Letters("paenh"), // 0x2e
  new Letters("paed"), // 0x2f
  new Letters("pael"), // 0x30
  new Letters("paelg"), // 0x31
  new Letters("paelm"), // 0x32
  new Letters("paelb"), // 0x33
  new Letters("paels"), // 0x34
  new Letters("paelt"), // 0x35
  new Letters("paelp"), // 0x36
  new Letters("paelh"), // 0x37
  new Letters("paem"), // 0x38
  new Letters("paeb"), // 0x39
  new Letters("paebs"), // 0x3a
  new Letters("paes"), // 0x3b
  new Letters("paess"), // 0x3c
  new Letters("paeng"), // 0x3d
  new Letters("paej"), // 0x3e
  new Letters("paec"), // 0x3f
  new Letters("paek"), // 0x40
  new Letters("paet"), // 0x41
  new Letters("paep"), // 0x42
  new Letters("paeh"), // 0x43
  new Letters("pya"), // 0x44
  new Letters("pyag"), // 0x45
  new Letters("pyagg"), // 0x46
  new Letters("pyags"), // 0x47
  new Letters("pyan"), // 0x48
  new Letters("pyanj"), // 0x49
  new Letters("pyanh"), // 0x4a
  new Letters("pyad"), // 0x4b
  new Letters("pyal"), // 0x4c
  new Letters("pyalg"), // 0x4d
  new Letters("pyalm"), // 0x4e
  new Letters("pyalb"), // 0x4f
  new Letters("pyals"), // 0x50
  new Letters("pyalt"), // 0x51
  new Letters("pyalp"), // 0x52
  new Letters("pyalh"), // 0x53
  new Letters("pyam"), // 0x54
  new Letters("pyab"), // 0x55
  new Letters("pyabs"), // 0x56
  new Letters("pyas"), // 0x57
  new Letters("pyass"), // 0x58
  new Letters("pyang"), // 0x59
  new Letters("pyaj"), // 0x5a
  new Letters("pyac"), // 0x5b
  new Letters("pyak"), // 0x5c
  new Letters("pyat"), // 0x5d
  new Letters("pyap"), // 0x5e
  new Letters("pyah"), // 0x5f
  new Letters("pyae"), // 0x60
  new Letters("pyaeg"), // 0x61
  new Letters("pyaegg"), // 0x62
  new Letters("pyaegs"), // 0x63
  new Letters("pyaen"), // 0x64
  new Letters("pyaenj"), // 0x65
  new Letters("pyaenh"), // 0x66
  new Letters("pyaed"), // 0x67
  new Letters("pyael"), // 0x68
  new Letters("pyaelg"), // 0x69
  new Letters("pyaelm"), // 0x6a
  new Letters("pyaelb"), // 0x6b
  new Letters("pyaels"), // 0x6c
  new Letters("pyaelt"), // 0x6d
  new Letters("pyaelp"), // 0x6e
  new Letters("pyaelh"), // 0x6f
  new Letters("pyaem"), // 0x70
  new Letters("pyaeb"), // 0x71
  new Letters("pyaebs"), // 0x72
  new Letters("pyaes"), // 0x73
  new Letters("pyaess"), // 0x74
  new Letters("pyaeng"), // 0x75
  new Letters("pyaej"), // 0x76
  new Letters("pyaec"), // 0x77
  new Letters("pyaek"), // 0x78
  new Letters("pyaet"), // 0x79
  new Letters("pyaep"), // 0x7a
  new Letters("pyaeh"), // 0x7b
  new Letters("peo"), // 0x7c
  new Letters("peog"), // 0x7d
  new Letters("peogg"), // 0x7e
  new Letters("peogs"), // 0x7f
  new Letters("peon"), // 0x80
  new Letters("peonj"), // 0x81
  new Letters("peonh"), // 0x82
  new Letters("peod"), // 0x83
  new Letters("peol"), // 0x84
  new Letters("peolg"), // 0x85
  new Letters("peolm"), // 0x86
  new Letters("peolb"), // 0x87
  new Letters("peols"), // 0x88
  new Letters("peolt"), // 0x89
  new Letters("peolp"), // 0x8a
  new Letters("peolh"), // 0x8b
  new Letters("peom"), // 0x8c
  new Letters("peob"), // 0x8d
  new Letters("peobs"), // 0x8e
  new Letters("peos"), // 0x8f
  new Letters("peoss"), // 0x90
  new Letters("peong"), // 0x91
  new Letters("peoj"), // 0x92
  new Letters("peoc"), // 0x93
  new Letters("peok"), // 0x94
  new Letters("peot"), // 0x95
  new Letters("peop"), // 0x96
  new Letters("peoh"), // 0x97
  LO_PE, // 0x98
  new Letters("peg"), // 0x99
  new Letters("pegg"), // 0x9a
  new Letters("pegs"), // 0x9b
  new Letters("pen"), // 0x9c
  new Letters("penj"), // 0x9d
  new Letters("penh"), // 0x9e
  new Letters("ped"), // 0x9f
  new Letters("pel"), // 0xa0
  new Letters("pelg"), // 0xa1
  new Letters("pelm"), // 0xa2
  new Letters("pelb"), // 0xa3
  new Letters("pels"), // 0xa4
  new Letters("pelt"), // 0xa5
  new Letters("pelp"), // 0xa6
  new Letters("pelh"), // 0xa7
  new Letters("pem"), // 0xa8
  new Letters("peb"), // 0xa9
  new Letters("pebs"), // 0xaa
  new Letters("pes"), // 0xab
  new Letters("pess"), // 0xac
  new Letters("peng"), // 0xad
  new Letters("pej"), // 0xae
  new Letters("pec"), // 0xaf
  new Letters("pek"), // 0xb0
  new Letters("pet"), // 0xb1
  new Letters("pep"), // 0xb2
  new Letters("peh"), // 0xb3
  new Letters("pyeo"), // 0xb4
  new Letters("pyeog"), // 0xb5
  new Letters("pyeogg"), // 0xb6
  new Letters("pyeogs"), // 0xb7
  new Letters("pyeon"), // 0xb8
  new Letters("pyeonj"), // 0xb9
  new Letters("pyeonh"), // 0xba
  new Letters("pyeod"), // 0xbb
  new Letters("pyeol"), // 0xbc
  new Letters("pyeolg"), // 0xbd
  new Letters("pyeolm"), // 0xbe
  new Letters("pyeolb"), // 0xbf
  new Letters("pyeols"), // 0xc0
  new Letters("pyeolt"), // 0xc1
  new Letters("pyeolp"), // 0xc2
  new Letters("pyeolh"), // 0xc3
  new Letters("pyeom"), // 0xc4
  new Letters("pyeob"), // 0xc5
  new Letters("pyeobs"), // 0xc6
  new Letters("pyeos"), // 0xc7
  new Letters("pyeoss"), // 0xc8
  new Letters("pyeong"), // 0xc9
  new Letters("pyeoj"), // 0xca
  new Letters("pyeoc"), // 0xcb
  new Letters("pyeok"), // 0xcc
  new Letters("pyeot"), // 0xcd
  new Letters("pyeop"), // 0xce
  new Letters("pyeoh"), // 0xcf
  new Letters("pye"), // 0xd0
  new Letters("pyeg"), // 0xd1
  new Letters("pyegg"), // 0xd2
  new Letters("pyegs"), // 0xd3
  new Letters("pyen"), // 0xd4
  new Letters("pyenj"), // 0xd5
  new Letters("pyenh"), // 0xd6
  new Letters("pyed"), // 0xd7
  new Letters("pyel"), // 0xd8
  new Letters("pyelg"), // 0xd9
  new Letters("pyelm"), // 0xda
  new Letters("pyelb"), // 0xdb
  new Letters("pyels"), // 0xdc
  new Letters("pyelt"), // 0xdd
  new Letters("pyelp"), // 0xde
  new Letters("pyelh"), // 0xdf
  new Letters("pyem"), // 0xe0
  new Letters("pyeb"), // 0xe1
  new Letters("pyebs"), // 0xe2
  new Letters("pyes"), // 0xe3
  new Letters("pyess"), // 0xe4
  new Letters("pyeng"), // 0xe5
  new Letters("pyej"), // 0xe6
  new Letters("pyec"), // 0xe7
  new Letters("pyek"), // 0xe8
  new Letters("pyet"), // 0xe9
  new Letters("pyep"), // 0xea
  new Letters("pyeh"), // 0xeb
  LO_PO, // 0xec
  new Letters("pog"), // 0xed
  new Letters("pogg"), // 0xee
  new Letters("pogs"), // 0xef
  new Letters("pon"), // 0xf0
  new Letters("ponj"), // 0xf1
  new Letters("ponh"), // 0xf2
  new Letters("pod"), // 0xf3
  new Letters("pol"), // 0xf4
  new Letters("polg"), // 0xf5
  new Letters("polm"), // 0xf6
  new Letters("polb"), // 0xf7
  new Letters("pols"), // 0xf8
  new Letters("polt"), // 0xf9
  new Letters("polp"), // 0xfa
  new Letters("polh"), // 0xfb
  new Letters("pom"), // 0xfc
  new Letters("pob"), // 0xfd
  new Letters("pobs"), // 0xfe
  new Letters("pos") // 0xff
  };
}