/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+D4xx (Hangul Syllables for Korean).
 */
final class Xd4 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("poss"), // 0x00
  new Letters("pong"), // 0x01
  new Letters("poj"), // 0x02
  new Letters("poc"), // 0x03
  new Letters("pok"), // 0x04
  new Letters("pot"), // 0x05
  new Letters("pop"), // 0x06
  new Letters("poh"), // 0x07
  new Letters("pwa"), // 0x08
  new Letters("pwag"), // 0x09
  new Letters("pwagg"), // 0x0a
  new Letters("pwags"), // 0x0b
  new Letters("pwan"), // 0x0c
  new Letters("pwanj"), // 0x0d
  new Letters("pwanh"), // 0x0e
  new Letters("pwad"), // 0x0f
  new Letters("pwal"), // 0x10
  new Letters("pwalg"), // 0x11
  new Letters("pwalm"), // 0x12
  new Letters("pwalb"), // 0x13
  new Letters("pwals"), // 0x14
  new Letters("pwalt"), // 0x15
  new Letters("pwalp"), // 0x16
  new Letters("pwalh"), // 0x17
  new Letters("pwam"), // 0x18
  new Letters("pwab"), // 0x19
  new Letters("pwabs"), // 0x1a
  new Letters("pwas"), // 0x1b
  new Letters("pwass"), // 0x1c
  new Letters("pwang"), // 0x1d
  new Letters("pwaj"), // 0x1e
  new Letters("pwac"), // 0x1f
  new Letters("pwak"), // 0x20
  new Letters("pwat"), // 0x21
  new Letters("pwap"), // 0x22
  new Letters("pwah"), // 0x23
  new Letters("pwae"), // 0x24
  new Letters("pwaeg"), // 0x25
  new Letters("pwaegg"), // 0x26
  new Letters("pwaegs"), // 0x27
  new Letters("pwaen"), // 0x28
  new Letters("pwaenj"), // 0x29
  new Letters("pwaenh"), // 0x2a
  new Letters("pwaed"), // 0x2b
  new Letters("pwael"), // 0x2c
  new Letters("pwaelg"), // 0x2d
  new Letters("pwaelm"), // 0x2e
  new Letters("pwaelb"), // 0x2f
  new Letters("pwaels"), // 0x30
  new Letters("pwaelt"), // 0x31
  new Letters("pwaelp"), // 0x32
  new Letters("pwaelh"), // 0x33
  new Letters("pwaem"), // 0x34
  new Letters("pwaeb"), // 0x35
  new Letters("pwaebs"), // 0x36
  new Letters("pwaes"), // 0x37
  new Letters("pwaess"), // 0x38
  new Letters("pwaeng"), // 0x39
  new Letters("pwaej"), // 0x3a
  new Letters("pwaec"), // 0x3b
  new Letters("pwaek"), // 0x3c
  new Letters("pwaet"), // 0x3d
  new Letters("pwaep"), // 0x3e
  new Letters("pwaeh"), // 0x3f
  new Letters("poe"), // 0x40
  new Letters("poeg"), // 0x41
  new Letters("poegg"), // 0x42
  new Letters("poegs"), // 0x43
  new Letters("poen"), // 0x44
  new Letters("poenj"), // 0x45
  new Letters("poenh"), // 0x46
  new Letters("poed"), // 0x47
  new Letters("poel"), // 0x48
  new Letters("poelg"), // 0x49
  new Letters("poelm"), // 0x4a
  new Letters("poelb"), // 0x4b
  new Letters("poels"), // 0x4c
  new Letters("poelt"), // 0x4d
  new Letters("poelp"), // 0x4e
  new Letters("poelh"), // 0x4f
  new Letters("poem"), // 0x50
  new Letters("poeb"), // 0x51
  new Letters("poebs"), // 0x52
  new Letters("poes"), // 0x53
  new Letters("poess"), // 0x54
  new Letters("poeng"), // 0x55
  new Letters("poej"), // 0x56
  new Letters("poec"), // 0x57
  new Letters("poek"), // 0x58
  new Letters("poet"), // 0x59
  new Letters("poep"), // 0x5a
  new Letters("poeh"), // 0x5b
  new Letters("pyo"), // 0x5c
  new Letters("pyog"), // 0x5d
  new Letters("pyogg"), // 0x5e
  new Letters("pyogs"), // 0x5f
  new Letters("pyon"), // 0x60
  new Letters("pyonj"), // 0x61
  new Letters("pyonh"), // 0x62
  new Letters("pyod"), // 0x63
  new Letters("pyol"), // 0x64
  new Letters("pyolg"), // 0x65
  new Letters("pyolm"), // 0x66
  new Letters("pyolb"), // 0x67
  new Letters("pyols"), // 0x68
  new Letters("pyolt"), // 0x69
  new Letters("pyolp"), // 0x6a
  new Letters("pyolh"), // 0x6b
  new Letters("pyom"), // 0x6c
  new Letters("pyob"), // 0x6d
  new Letters("pyobs"), // 0x6e
  new Letters("pyos"), // 0x6f
  new Letters("pyoss"), // 0x70
  new Letters("pyong"), // 0x71
  new Letters("pyoj"), // 0x72
  new Letters("pyoc"), // 0x73
  new Letters("pyok"), // 0x74
  new Letters("pyot"), // 0x75
  new Letters("pyop"), // 0x76
  new Letters("pyoh"), // 0x77
  LO_PU, // 0x78
  new Letters("pug"), // 0x79
  new Letters("pugg"), // 0x7a
  new Letters("pugs"), // 0x7b
  new Letters("pun"), // 0x7c
  new Letters("punj"), // 0x7d
  new Letters("punh"), // 0x7e
  new Letters("pud"), // 0x7f
  new Letters("pul"), // 0x80
  new Letters("pulg"), // 0x81
  new Letters("pulm"), // 0x82
  new Letters("pulb"), // 0x83
  new Letters("puls"), // 0x84
  new Letters("pult"), // 0x85
  new Letters("pulp"), // 0x86
  new Letters("pulh"), // 0x87
  new Letters("pum"), // 0x88
  new Letters("pub"), // 0x89
  new Letters("pubs"), // 0x8a
  new Letters("pus"), // 0x8b
  new Letters("puss"), // 0x8c
  new Letters("pung"), // 0x8d
  new Letters("puj"), // 0x8e
  new Letters("puc"), // 0x8f
  new Letters("puk"), // 0x90
  new Letters("put"), // 0x91
  new Letters("pup"), // 0x92
  new Letters("puh"), // 0x93
  new Letters("pweo"), // 0x94
  new Letters("pweog"), // 0x95
  new Letters("pweogg"), // 0x96
  new Letters("pweogs"), // 0x97
  new Letters("pweon"), // 0x98
  new Letters("pweonj"), // 0x99
  new Letters("pweonh"), // 0x9a
  new Letters("pweod"), // 0x9b
  new Letters("pweol"), // 0x9c
  new Letters("pweolg"), // 0x9d
  new Letters("pweolm"), // 0x9e
  new Letters("pweolb"), // 0x9f
  new Letters("pweols"), // 0xa0
  new Letters("pweolt"), // 0xa1
  new Letters("pweolp"), // 0xa2
  new Letters("pweolh"), // 0xa3
  new Letters("pweom"), // 0xa4
  new Letters("pweob"), // 0xa5
  new Letters("pweobs"), // 0xa6
  new Letters("pweos"), // 0xa7
  new Letters("pweoss"), // 0xa8
  new Letters("pweong"), // 0xa9
  new Letters("pweoj"), // 0xaa
  new Letters("pweoc"), // 0xab
  new Letters("pweok"), // 0xac
  new Letters("pweot"), // 0xad
  new Letters("pweop"), // 0xae
  new Letters("pweoh"), // 0xaf
  new Letters("pwe"), // 0xb0
  new Letters("pweg"), // 0xb1
  new Letters("pwegg"), // 0xb2
  new Letters("pwegs"), // 0xb3
  new Letters("pwen"), // 0xb4
  new Letters("pwenj"), // 0xb5
  new Letters("pwenh"), // 0xb6
  new Letters("pwed"), // 0xb7
  new Letters("pwel"), // 0xb8
  new Letters("pwelg"), // 0xb9
  new Letters("pwelm"), // 0xba
  new Letters("pwelb"), // 0xbb
  new Letters("pwels"), // 0xbc
  new Letters("pwelt"), // 0xbd
  new Letters("pwelp"), // 0xbe
  new Letters("pwelh"), // 0xbf
  new Letters("pwem"), // 0xc0
  new Letters("pweb"), // 0xc1
  new Letters("pwebs"), // 0xc2
  new Letters("pwes"), // 0xc3
  new Letters("pwess"), // 0xc4
  new Letters("pweng"), // 0xc5
  new Letters("pwej"), // 0xc6
  new Letters("pwec"), // 0xc7
  new Letters("pwek"), // 0xc8
  new Letters("pwet"), // 0xc9
  new Letters("pwep"), // 0xca
  new Letters("pweh"), // 0xcb
  new Letters("pwi"), // 0xcc
  new Letters("pwig"), // 0xcd
  new Letters("pwigg"), // 0xce
  new Letters("pwigs"), // 0xcf
  new Letters("pwin"), // 0xd0
  new Letters("pwinj"), // 0xd1
  new Letters("pwinh"), // 0xd2
  new Letters("pwid"), // 0xd3
  new Letters("pwil"), // 0xd4
  new Letters("pwilg"), // 0xd5
  new Letters("pwilm"), // 0xd6
  new Letters("pwilb"), // 0xd7
  new Letters("pwils"), // 0xd8
  new Letters("pwilt"), // 0xd9
  new Letters("pwilp"), // 0xda
  new Letters("pwilh"), // 0xdb
  new Letters("pwim"), // 0xdc
  new Letters("pwib"), // 0xdd
  new Letters("pwibs"), // 0xde
  new Letters("pwis"), // 0xdf
  new Letters("pwiss"), // 0xe0
  new Letters("pwing"), // 0xe1
  new Letters("pwij"), // 0xe2
  new Letters("pwic"), // 0xe3
  new Letters("pwik"), // 0xe4
  new Letters("pwit"), // 0xe5
  new Letters("pwip"), // 0xe6
  new Letters("pwih"), // 0xe7
  new Letters("pyu"), // 0xe8
  new Letters("pyug"), // 0xe9
  new Letters("pyugg"), // 0xea
  new Letters("pyugs"), // 0xeb
  new Letters("pyun"), // 0xec
  new Letters("pyunj"), // 0xed
  new Letters("pyunh"), // 0xee
  new Letters("pyud"), // 0xef
  new Letters("pyul"), // 0xf0
  new Letters("pyulg"), // 0xf1
  new Letters("pyulm"), // 0xf2
  new Letters("pyulb"), // 0xf3
  new Letters("pyuls"), // 0xf4
  new Letters("pyult"), // 0xf5
  new Letters("pyulp"), // 0xf6
  new Letters("pyulh"), // 0xf7
  new Letters("pyum"), // 0xf8
  new Letters("pyub"), // 0xf9
  new Letters("pyubs"), // 0xfa
  new Letters("pyus"), // 0xfb
  new Letters("pyuss"), // 0xfc
  new Letters("pyung"), // 0xfd
  new Letters("pyuj"), // 0xfe
  new Letters("pyuc") // 0xff
  };
}