/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+D5xx (Hangul Syllables for Korean).
 */
final class Xd5 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("pyuk"), // 0x00
  new Letters("pyut"), // 0x01
  new Letters("pyup"), // 0x02
  new Letters("pyuh"), // 0x03
  new Letters("peu"), // 0x04
  new Letters("peug"), // 0x05
  new Letters("peugg"), // 0x06
  new Letters("peugs"), // 0x07
  new Letters("peun"), // 0x08
  new Letters("peunj"), // 0x09
  new Letters("peunh"), // 0x0a
  new Letters("peud"), // 0x0b
  new Letters("peul"), // 0x0c
  new Letters("peulg"), // 0x0d
  new Letters("peulm"), // 0x0e
  new Letters("peulb"), // 0x0f
  new Letters("peuls"), // 0x10
  new Letters("peult"), // 0x11
  new Letters("peulp"), // 0x12
  new Letters("peulh"), // 0x13
  new Letters("peum"), // 0x14
  new Letters("peub"), // 0x15
  new Letters("peubs"), // 0x16
  new Letters("peus"), // 0x17
  new Letters("peuss"), // 0x18
  new Letters("peung"), // 0x19
  new Letters("peuj"), // 0x1a
  new Letters("peuc"), // 0x1b
  new Letters("peuk"), // 0x1c
  new Letters("peut"), // 0x1d
  new Letters("peup"), // 0x1e
  new Letters("peuh"), // 0x1f
  new Letters("pyi"), // 0x20
  new Letters("pyig"), // 0x21
  new Letters("pyigg"), // 0x22
  new Letters("pyigs"), // 0x23
  new Letters("pyin"), // 0x24
  new Letters("pyinj"), // 0x25
  new Letters("pyinh"), // 0x26
  new Letters("pyid"), // 0x27
  new Letters("pyil"), // 0x28
  new Letters("pyilg"), // 0x29
  new Letters("pyilm"), // 0x2a
  new Letters("pyilb"), // 0x2b
  new Letters("pyils"), // 0x2c
  new Letters("pyilt"), // 0x2d
  new Letters("pyilp"), // 0x2e
  new Letters("pyilh"), // 0x2f
  new Letters("pyim"), // 0x30
  new Letters("pyib"), // 0x31
  new Letters("pyibs"), // 0x32
  new Letters("pyis"), // 0x33
  new Letters("pyiss"), // 0x34
  new Letters("pying"), // 0x35
  new Letters("pyij"), // 0x36
  new Letters("pyic"), // 0x37
  new Letters("pyik"), // 0x38
  new Letters("pyit"), // 0x39
  new Letters("pyip"), // 0x3a
  new Letters("pyih"), // 0x3b
  LO_PI, // 0x3c
  new Letters("pig"), // 0x3d
  new Letters("pigg"), // 0x3e
  new Letters("pigs"), // 0x3f
  new Letters("pin"), // 0x40
  new Letters("pinj"), // 0x41
  new Letters("pinh"), // 0x42
  new Letters("pid"), // 0x43
  new Letters("pil"), // 0x44
  new Letters("pilg"), // 0x45
  new Letters("pilm"), // 0x46
  new Letters("pilb"), // 0x47
  new Letters("pils"), // 0x48
  new Letters("pilt"), // 0x49
  new Letters("pilp"), // 0x4a
  new Letters("pilh"), // 0x4b
  new Letters("pim"), // 0x4c
  new Letters("pib"), // 0x4d
  new Letters("pibs"), // 0x4e
  new Letters("pis"), // 0x4f
  new Letters("piss"), // 0x50
  new Letters("ping"), // 0x51
  new Letters("pij"), // 0x52
  new Letters("pic"), // 0x53
  new Letters("pik"), // 0x54
  new Letters("pit"), // 0x55
  new Letters("pip"), // 0x56
  new Letters("pih"), // 0x57
  LO_HA, // 0x58
  new Letters("hag"), // 0x59
  new Letters("hagg"), // 0x5a
  new Letters("hags"), // 0x5b
  new Letters("han"), // 0x5c
  new Letters("hanj"), // 0x5d
  new Letters("hanh"), // 0x5e
  new Letters("had"), // 0x5f
  new Letters("hal"), // 0x60
  new Letters("halg"), // 0x61
  new Letters("halm"), // 0x62
  new Letters("halb"), // 0x63
  new Letters("hals"), // 0x64
  new Letters("halt"), // 0x65
  new Letters("halp"), // 0x66
  new Letters("halh"), // 0x67
  new Letters("ham"), // 0x68
  new Letters("hab"), // 0x69
  new Letters("habs"), // 0x6a
  new Letters("has"), // 0x6b
  new Letters("hass"), // 0x6c
  new Letters("hang"), // 0x6d
  new Letters("haj"), // 0x6e
  new Letters("hac"), // 0x6f
  new Letters("hak"), // 0x70
  new Letters("hat"), // 0x71
  new Letters("hap"), // 0x72
  new Letters("hah"), // 0x73
  new Letters("hae"), // 0x74
  new Letters("haeg"), // 0x75
  new Letters("haegg"), // 0x76
  new Letters("haegs"), // 0x77
  new Letters("haen"), // 0x78
  new Letters("haenj"), // 0x79
  new Letters("haenh"), // 0x7a
  new Letters("haed"), // 0x7b
  new Letters("hael"), // 0x7c
  new Letters("haelg"), // 0x7d
  new Letters("haelm"), // 0x7e
  new Letters("haelb"), // 0x7f
  new Letters("haels"), // 0x80
  new Letters("haelt"), // 0x81
  new Letters("haelp"), // 0x82
  new Letters("haelh"), // 0x83
  new Letters("haem"), // 0x84
  new Letters("haeb"), // 0x85
  new Letters("haebs"), // 0x86
  new Letters("haes"), // 0x87
  new Letters("haess"), // 0x88
  new Letters("haeng"), // 0x89
  new Letters("haej"), // 0x8a
  new Letters("haec"), // 0x8b
  new Letters("haek"), // 0x8c
  new Letters("haet"), // 0x8d
  new Letters("haep"), // 0x8e
  new Letters("haeh"), // 0x8f
  new Letters("hya"), // 0x90
  new Letters("hyag"), // 0x91
  new Letters("hyagg"), // 0x92
  new Letters("hyags"), // 0x93
  new Letters("hyan"), // 0x94
  new Letters("hyanj"), // 0x95
  new Letters("hyanh"), // 0x96
  new Letters("hyad"), // 0x97
  new Letters("hyal"), // 0x98
  new Letters("hyalg"), // 0x99
  new Letters("hyalm"), // 0x9a
  new Letters("hyalb"), // 0x9b
  new Letters("hyals"), // 0x9c
  new Letters("hyalt"), // 0x9d
  new Letters("hyalp"), // 0x9e
  new Letters("hyalh"), // 0x9f
  new Letters("hyam"), // 0xa0
  new Letters("hyab"), // 0xa1
  new Letters("hyabs"), // 0xa2
  new Letters("hyas"), // 0xa3
  new Letters("hyass"), // 0xa4
  new Letters("hyang"), // 0xa5
  new Letters("hyaj"), // 0xa6
  new Letters("hyac"), // 0xa7
  new Letters("hyak"), // 0xa8
  new Letters("hyat"), // 0xa9
  new Letters("hyap"), // 0xaa
  new Letters("hyah"), // 0xab
  new Letters("hyae"), // 0xac
  new Letters("hyaeg"), // 0xad
  new Letters("hyaegg"), // 0xae
  new Letters("hyaegs"), // 0xaf
  new Letters("hyaen"), // 0xb0
  new Letters("hyaenj"), // 0xb1
  new Letters("hyaenh"), // 0xb2
  new Letters("hyaed"), // 0xb3
  new Letters("hyael"), // 0xb4
  new Letters("hyaelg"), // 0xb5
  new Letters("hyaelm"), // 0xb6
  new Letters("hyaelb"), // 0xb7
  new Letters("hyaels"), // 0xb8
  new Letters("hyaelt"), // 0xb9
  new Letters("hyaelp"), // 0xba
  new Letters("hyaelh"), // 0xbb
  new Letters("hyaem"), // 0xbc
  new Letters("hyaeb"), // 0xbd
  new Letters("hyaebs"), // 0xbe
  new Letters("hyaes"), // 0xbf
  new Letters("hyaess"), // 0xc0
  new Letters("hyaeng"), // 0xc1
  new Letters("hyaej"), // 0xc2
  new Letters("hyaec"), // 0xc3
  new Letters("hyaek"), // 0xc4
  new Letters("hyaet"), // 0xc5
  new Letters("hyaep"), // 0xc6
  new Letters("hyaeh"), // 0xc7
  new Letters("heo"), // 0xc8
  new Letters("heog"), // 0xc9
  new Letters("heogg"), // 0xca
  new Letters("heogs"), // 0xcb
  new Letters("heon"), // 0xcc
  new Letters("heonj"), // 0xcd
  new Letters("heonh"), // 0xce
  new Letters("heod"), // 0xcf
  new Letters("heol"), // 0xd0
  new Letters("heolg"), // 0xd1
  new Letters("heolm"), // 0xd2
  new Letters("heolb"), // 0xd3
  new Letters("heols"), // 0xd4
  new Letters("heolt"), // 0xd5
  new Letters("heolp"), // 0xd6
  new Letters("heolh"), // 0xd7
  new Letters("heom"), // 0xd8
  new Letters("heob"), // 0xd9
  new Letters("heobs"), // 0xda
  new Letters("heos"), // 0xdb
  new Letters("heoss"), // 0xdc
  new Letters("heong"), // 0xdd
  new Letters("heoj"), // 0xde
  new Letters("heoc"), // 0xdf
  new Letters("heok"), // 0xe0
  new Letters("heot"), // 0xe1
  new Letters("heop"), // 0xe2
  new Letters("heoh"), // 0xe3
  LO_HE, // 0xe4
  new Letters("heg"), // 0xe5
  new Letters("hegg"), // 0xe6
  new Letters("hegs"), // 0xe7
  new Letters("hen"), // 0xe8
  new Letters("henj"), // 0xe9
  new Letters("henh"), // 0xea
  new Letters("hed"), // 0xeb
  new Letters("hel"), // 0xec
  new Letters("helg"), // 0xed
  new Letters("helm"), // 0xee
  new Letters("helb"), // 0xef
  new Letters("hels"), // 0xf0
  new Letters("helt"), // 0xf1
  new Letters("help"), // 0xf2
  new Letters("helh"), // 0xf3
  new Letters("hem"), // 0xf4
  new Letters("heb"), // 0xf5
  new Letters("hebs"), // 0xf6
  new Letters("hes"), // 0xf7
  new Letters("hess"), // 0xf8
  new Letters("heng"), // 0xf9
  new Letters("hej"), // 0xfa
  new Letters("hec"), // 0xfb
  new Letters("hek"), // 0xfc
  new Letters("het"), // 0xfd
  new Letters("hep"), // 0xfe
  new Letters("heh") // 0xff
  };
}