/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+D6xx (Hangul Syllables for Korean).
 */
final class Xd6 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Letters("hyeo"), // 0x00
  new Letters("hyeog"), // 0x01
  new Letters("hyeogg"), // 0x02
  new Letters("hyeogs"), // 0x03
  new Letters("hyeon"), // 0x04
  new Letters("hyeonj"), // 0x05
  new Letters("hyeonh"), // 0x06
  new Letters("hyeod"), // 0x07
  new Letters("hyeol"), // 0x08
  new Letters("hyeolg"), // 0x09
  new Letters("hyeolm"), // 0x0a
  new Letters("hyeolb"), // 0x0b
  new Letters("hyeols"), // 0x0c
  new Letters("hyeolt"), // 0x0d
  new Letters("hyeolp"), // 0x0e
  new Letters("hyeolh"), // 0x0f
  new Letters("hyeom"), // 0x10
  new Letters("hyeob"), // 0x11
  new Letters("hyeobs"), // 0x12
  new Letters("hyeos"), // 0x13
  new Letters("hyeoss"), // 0x14
  new Letters("hyeong"), // 0x15
  new Letters("hyeoj"), // 0x16
  new Letters("hyeoc"), // 0x17
  new Letters("hyeok"), // 0x18
  new Letters("hyeot"), // 0x19
  new Letters("hyeop"), // 0x1a
  new Letters("hyeoh"), // 0x1b
  new Letters("hye"), // 0x1c
  new Letters("hyeg"), // 0x1d
  new Letters("hyegg"), // 0x1e
  new Letters("hyegs"), // 0x1f
  new Letters("hyen"), // 0x20
  new Letters("hyenj"), // 0x21
  new Letters("hyenh"), // 0x22
  new Letters("hyed"), // 0x23
  new Letters("hyel"), // 0x24
  new Letters("hyelg"), // 0x25
  new Letters("hyelm"), // 0x26
  new Letters("hyelb"), // 0x27
  new Letters("hyels"), // 0x28
  new Letters("hyelt"), // 0x29
  new Letters("hyelp"), // 0x2a
  new Letters("hyelh"), // 0x2b
  new Letters("hyem"), // 0x2c
  new Letters("hyeb"), // 0x2d
  new Letters("hyebs"), // 0x2e
  new Letters("hyes"), // 0x2f
  new Letters("hyess"), // 0x30
  new Letters("hyeng"), // 0x31
  new Letters("hyej"), // 0x32
  new Letters("hyec"), // 0x33
  new Letters("hyek"), // 0x34
  new Letters("hyet"), // 0x35
  new Letters("hyep"), // 0x36
  new Letters("hyeh"), // 0x37
  LO_HO, // 0x38
  new Letters("hog"), // 0x39
  new Letters("hogg"), // 0x3a
  new Letters("hogs"), // 0x3b
  new Letters("hon"), // 0x3c
  new Letters("honj"), // 0x3d
  new Letters("honh"), // 0x3e
  new Letters("hod"), // 0x3f
  new Letters("hol"), // 0x40
  new Letters("holg"), // 0x41
  new Letters("holm"), // 0x42
  new Letters("holb"), // 0x43
  new Letters("hols"), // 0x44
  new Letters("holt"), // 0x45
  new Letters("holp"), // 0x46
  new Letters("holh"), // 0x47
  new Letters("hom"), // 0x48
  new Letters("hob"), // 0x49
  new Letters("hobs"), // 0x4a
  new Letters("hos"), // 0x4b
  new Letters("hoss"), // 0x4c
  new Letters("hong"), // 0x4d
  new Letters("hoj"), // 0x4e
  new Letters("hoc"), // 0x4f
  new Letters("hok"), // 0x50
  new Letters("hot"), // 0x51
  new Letters("hop"), // 0x52
  new Letters("hoh"), // 0x53
  new Letters("hwa"), // 0x54
  new Letters("hwag"), // 0x55
  new Letters("hwagg"), // 0x56
  new Letters("hwags"), // 0x57
  new Letters("hwan"), // 0x58
  new Letters("hwanj"), // 0x59
  new Letters("hwanh"), // 0x5a
  new Letters("hwad"), // 0x5b
  new Letters("hwal"), // 0x5c
  new Letters("hwalg"), // 0x5d
  new Letters("hwalm"), // 0x5e
  new Letters("hwalb"), // 0x5f
  new Letters("hwals"), // 0x60
  new Letters("hwalt"), // 0x61
  new Letters("hwalp"), // 0x62
  new Letters("hwalh"), // 0x63
  new Letters("hwam"), // 0x64
  new Letters("hwab"), // 0x65
  new Letters("hwabs"), // 0x66
  new Letters("hwas"), // 0x67
  new Letters("hwass"), // 0x68
  new Letters("hwang"), // 0x69
  new Letters("hwaj"), // 0x6a
  new Letters("hwac"), // 0x6b
  new Letters("hwak"), // 0x6c
  new Letters("hwat"), // 0x6d
  new Letters("hwap"), // 0x6e
  new Letters("hwah"), // 0x6f
  new Letters("hwae"), // 0x70
  new Letters("hwaeg"), // 0x71
  new Letters("hwaegg"), // 0x72
  new Letters("hwaegs"), // 0x73
  new Letters("hwaen"), // 0x74
  new Letters("hwaenj"), // 0x75
  new Letters("hwaenh"), // 0x76
  new Letters("hwaed"), // 0x77
  new Letters("hwael"), // 0x78
  new Letters("hwaelg"), // 0x79
  new Letters("hwaelm"), // 0x7a
  new Letters("hwaelb"), // 0x7b
  new Letters("hwaels"), // 0x7c
  new Letters("hwaelt"), // 0x7d
  new Letters("hwaelp"), // 0x7e
  new Letters("hwaelh"), // 0x7f
  new Letters("hwaem"), // 0x80
  new Letters("hwaeb"), // 0x81
  new Letters("hwaebs"), // 0x82
  new Letters("hwaes"), // 0x83
  new Letters("hwaess"), // 0x84
  new Letters("hwaeng"), // 0x85
  new Letters("hwaej"), // 0x86
  new Letters("hwaec"), // 0x87
  new Letters("hwaek"), // 0x88
  new Letters("hwaet"), // 0x89
  new Letters("hwaep"), // 0x8a
  new Letters("hwaeh"), // 0x8b
  new Letters("hoe"), // 0x8c
  new Letters("hoeg"), // 0x8d
  new Letters("hoegg"), // 0x8e
  new Letters("hoegs"), // 0x8f
  new Letters("hoen"), // 0x90
  new Letters("hoenj"), // 0x91
  new Letters("hoenh"), // 0x92
  new Letters("hoed"), // 0x93
  new Letters("hoel"), // 0x94
  new Letters("hoelg"), // 0x95
  new Letters("hoelm"), // 0x96
  new Letters("hoelb"), // 0x97
  new Letters("hoels"), // 0x98
  new Letters("hoelt"), // 0x99
  new Letters("hoelp"), // 0x9a
  new Letters("hoelh"), // 0x9b
  new Letters("hoem"), // 0x9c
  new Letters("hoeb"), // 0x9d
  new Letters("hoebs"), // 0x9e
  new Letters("hoes"), // 0x9f
  new Letters("hoess"), // 0xa0
  new Letters("hoeng"), // 0xa1
  new Letters("hoej"), // 0xa2
  new Letters("hoec"), // 0xa3
  new Letters("hoek"), // 0xa4
  new Letters("hoet"), // 0xa5
  new Letters("hoep"), // 0xa6
  new Letters("hoeh"), // 0xa7
  new Letters("hyo"), // 0xa8
  new Letters("hyog"), // 0xa9
  new Letters("hyogg"), // 0xaa
  new Letters("hyogs"), // 0xab
  new Letters("hyon"), // 0xac
  new Letters("hyonj"), // 0xad
  new Letters("hyonh"), // 0xae
  new Letters("hyod"), // 0xaf
  new Letters("hyol"), // 0xb0
  new Letters("hyolg"), // 0xb1
  new Letters("hyolm"), // 0xb2
  new Letters("hyolb"), // 0xb3
  new Letters("hyols"), // 0xb4
  new Letters("hyolt"), // 0xb5
  new Letters("hyolp"), // 0xb6
  new Letters("hyolh"), // 0xb7
  new Letters("hyom"), // 0xb8
  new Letters("hyob"), // 0xb9
  new Letters("hyobs"), // 0xba
  new Letters("hyos"), // 0xbb
  new Letters("hyoss"), // 0xbc
  new Letters("hyong"), // 0xbd
  new Letters("hyoj"), // 0xbe
  new Letters("hyoc"), // 0xbf
  new Letters("hyok"), // 0xc0
  new Letters("hyot"), // 0xc1
  new Letters("hyop"), // 0xc2
  new Letters("hyoh"), // 0xc3
  LO_HU, // 0xc4
  new Letters("hug"), // 0xc5
  new Letters("hugg"), // 0xc6
  new Letters("hugs"), // 0xc7
  new Letters("hun"), // 0xc8
  new Letters("hunj"), // 0xc9
  new Letters("hunh"), // 0xca
  new Letters("hud"), // 0xcb
  new Letters("hul"), // 0xcc
  new Letters("hulg"), // 0xcd
  new Letters("hulm"), // 0xce
  new Letters("hulb"), // 0xcf
  new Letters("huls"), // 0xd0
  new Letters("hult"), // 0xd1
  new Letters("hulp"), // 0xd2
  new Letters("hulh"), // 0xd3
  new Letters("hum"), // 0xd4
  new Letters("hub"), // 0xd5
  new Letters("hubs"), // 0xd6
  new Letters("hus"), // 0xd7
  new Letters("huss"), // 0xd8
  new Letters("hung"), // 0xd9
  new Letters("huj"), // 0xda
  new Letters("huc"), // 0xdb
  new Letters("huk"), // 0xdc
  new Letters("hut"), // 0xdd
  new Letters("hup"), // 0xde
  new Letters("huh"), // 0xdf
  new Letters("hweo"), // 0xe0
  new Letters("hweog"), // 0xe1
  new Letters("hweogg"), // 0xe2
  new Letters("hweogs"), // 0xe3
  new Letters("hweon"), // 0xe4
  new Letters("hweonj"), // 0xe5
  new Letters("hweonh"), // 0xe6
  new Letters("hweod"), // 0xe7
  new Letters("hweol"), // 0xe8
  new Letters("hweolg"), // 0xe9
  new Letters("hweolm"), // 0xea
  new Letters("hweolb"), // 0xeb
  new Letters("hweols"), // 0xec
  new Letters("hweolt"), // 0xed
  new Letters("hweolp"), // 0xee
  new Letters("hweolh"), // 0xef
  new Letters("hweom"), // 0xf0
  new Letters("hweob"), // 0xf1
  new Letters("hweobs"), // 0xf2
  new Letters("hweos"), // 0xf3
  new Letters("hweoss"), // 0xf4
  new Letters("hweong"), // 0xf5
  new Letters("hweoj"), // 0xf6
  new Letters("hweoc"), // 0xf7
  new Letters("hweok"), // 0xf8
  new Letters("hweot"), // 0xf9
  new Letters("hweop"), // 0xfa
  new Letters("hweoh"), // 0xfb
  new Letters("hwe"), // 0xfc
  new Letters("hweg"), // 0xfd
  new Letters("hwegg"), // 0xfe
  new Letters("hwegs") // 0xff
  };
}