/* Copyright c The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.text.ascii.impl;

/**
 * {@Yxx} for codepoint U+F9xx (CJK Compatibility Ideographs).
 */
final class Xf9 extends Xxx {

  public static final CodePointMapping[] MAP = new CodePointMapping[] { //
  new Word("Kay"), // 0x00
  new Word("Kayng"), // 0x01
  new Word("Ke"), // 0x02
  new Word("Ko"), // 0x03
  new Word("Kol"), // 0x04
  new Word("Koc"), // 0x05
  new Word("Kwi"), // 0x06
  new Word("Kwi"), // 0x07
  new Word("Kyun"), // 0x08
  new Word("Kul"), // 0x09
  new Word("Kum"), // 0x0a
  new Word("Na"), // 0x0b
  new Word("Na"), // 0x0c
  new Word("Na"), // 0x0d
  new Word("La"), // 0x0e
  new Word("Na"), // 0x0f
  new Word("Na"), // 0x10
  new Word("Na"), // 0x11
  new Word("Na"), // 0x12
  new Word("Na"), // 0x13
  new Word("Nak"), // 0x14
  new Word("Nak"), // 0x15
  new Word("Nak"), // 0x16
  new Word("Nak"), // 0x17
  new Word("Nak"), // 0x18
  new Word("Nak"), // 0x19
  new Word("Nak"), // 0x1a
  new Word("Nan"), // 0x1b
  new Word("Nan"), // 0x1c
  new Word("Nan"), // 0x1d
  new Word("Nan"), // 0x1e
  new Word("Nan"), // 0x1f
  new Word("Nan"), // 0x20
  new Word("Nam"), // 0x21
  new Word("Nam"), // 0x22
  new Word("Nam"), // 0x23
  new Word("Nam"), // 0x24
  new Word("Nap"), // 0x25
  new Word("Nap"), // 0x26
  new Word("Nap"), // 0x27
  new Word("Nang"), // 0x28
  new Word("Nang"), // 0x29
  new Word("Nang"), // 0x2a
  new Word("Nang"), // 0x2b
  new Word("Nang"), // 0x2c
  new Word("Nay"), // 0x2d
  new Word("Nayng"), // 0x2e
  new Word("No"), // 0x2f
  new Word("No"), // 0x30
  new Word("No"), // 0x31
  new Word("No"), // 0x32
  new Word("No"), // 0x33
  new Word("No"), // 0x34
  new Word("No"), // 0x35
  new Word("No"), // 0x36
  new Word("No"), // 0x37
  new Word("No"), // 0x38
  new Word("No"), // 0x39
  new Word("No"), // 0x3a
  new Word("Nok"), // 0x3b
  new Word("Nok"), // 0x3c
  new Word("Nok"), // 0x3d
  new Word("Nok"), // 0x3e
  new Word("Nok"), // 0x3f
  new Word("Nok"), // 0x40
  new Word("Non"), // 0x41
  new Word("Nong"), // 0x42
  new Word("Nong"), // 0x43
  new Word("Nong"), // 0x44
  new Word("Nong"), // 0x45
  new Word("Noy"), // 0x46
  new Word("Noy"), // 0x47
  new Word("Noy"), // 0x48
  new Word("Noy"), // 0x49
  new Word("Nwu"), // 0x4a
  new Word("Nwu"), // 0x4b
  new Word("Nwu"), // 0x4c
  new Word("Nwu"), // 0x4d
  new Word("Nwu"), // 0x4e
  new Word("Nwu"), // 0x4f
  new Word("Nwu"), // 0x50
  new Word("Nwu"), // 0x51
  new Word("Nuk"), // 0x52
  new Word("Nuk"), // 0x53
  new Word("Num"), // 0x54
  new Word("Nung"), // 0x55
  new Word("Nung"), // 0x56
  new Word("Nung"), // 0x57
  new Word("Nung"), // 0x58
  new Word("Nung"), // 0x59
  new Word("Twu"), // 0x5a
  new Word("La"), // 0x5b
  new Word("Lak"), // 0x5c
  new Word("Lak"), // 0x5d
  new Word("Lan"), // 0x5e
  new Word("Lyeng"), // 0x5f
  new Word("Lo"), // 0x60
  new Word("Lyul"), // 0x61
  new Word("Li"), // 0x62
  new Word("Pey"), // 0x63
  new Word("Pen"), // 0x64
  new Word("Pyen"), // 0x65
  new Word("Pwu"), // 0x66
  new Word("Pwul"), // 0x67
  new Word("Pi"), // 0x68
  new Word("Sak"), // 0x69
  new Word("Sak"), // 0x6a
  new Word("Sam"), // 0x6b
  new Word("Sayk"), // 0x6c
  new Word("Sayng"), // 0x6d
  new Word("Sep"), // 0x6e
  new Word("Sey"), // 0x6f
  new Word("Sway"), // 0x70
  new Word("Sin"), // 0x71
  new Word("Sim"), // 0x72
  new Word("Sip"), // 0x73
  new Word("Ya"), // 0x74
  new Word("Yak"), // 0x75
  new Word("Yak"), // 0x76
  new Word("Yang"), // 0x77
  new Word("Yang"), // 0x78
  new Word("Yang"), // 0x79
  new Word("Yang"), // 0x7a
  new Word("Yang"), // 0x7b
  new Word("Yang"), // 0x7c
  new Word("Yang"), // 0x7d
  new Word("Yang"), // 0x7e
  new Word("Ye"), // 0x7f
  new Word("Ye"), // 0x80
  new Word("Ye"), // 0x81
  new Word("Ye"), // 0x82
  new Word("Ye"), // 0x83
  new Word("Ye"), // 0x84
  new Word("Ye"), // 0x85
  new Word("Ye"), // 0x86
  new Word("Ye"), // 0x87
  new Word("Ye"), // 0x88
  new Word("Ye"), // 0x89
  new Word("Yek"), // 0x8a
  new Word("Yek"), // 0x8b
  new Word("Yek"), // 0x8c
  new Word("Yek"), // 0x8d
  new Word("Yen"), // 0x8e
  new Word("Yen"), // 0x8f
  new Word("Yen"), // 0x90
  new Word("Yen"), // 0x91
  new Word("Yen"), // 0x92
  new Word("Yen"), // 0x93
  new Word("Yen"), // 0x94
  new Word("Yen"), // 0x95
  new Word("Yen"), // 0x96
  new Word("Yen"), // 0x97
  new Word("Yen"), // 0x98
  new Word("Yen"), // 0x99
  new Word("Yen"), // 0x9a
  new Word("Yen"), // 0x9b
  new Word("Yel"), // 0x9c
  new Word("Yel"), // 0x9d
  new Word("Yel"), // 0x9e
  new Word("Yel"), // 0x9f
  new Word("Yel"), // 0xa0
  new Word("Yel"), // 0xa1
  new Word("Yem"), // 0xa2
  new Word("Yem"), // 0xa3
  new Word("Yem"), // 0xa4
  new Word("Yem"), // 0xa5
  new Word("Yem"), // 0xa6
  new Word("Yep"), // 0xa7
  new Word("Yeng"), // 0xa8
  new Word("Yeng"), // 0xa9
  new Word("Yeng"), // 0xaa
  new Word("Yeng"), // 0xab
  new Word("Yeng"), // 0xac
  new Word("Yeng"), // 0xad
  new Word("Yeng"), // 0xae
  new Word("Yeng"), // 0xaf
  new Word("Yeng"), // 0xb0
  new Word("Yeng"), // 0xb1
  new Word("Yeng"), // 0xb2
  new Word("Yeng"), // 0xb3
  new Word("Yeng"), // 0xb4
  new Word("Yey"), // 0xb5
  new Word("Yey"), // 0xb6
  new Word("Yey"), // 0xb7
  new Word("Yey"), // 0xb8
  new Word("O"), // 0xb9
  new Word("Yo"), // 0xba
  new Word("Yo"), // 0xbb
  new Word("Yo"), // 0xbc
  new Word("Yo"), // 0xbd
  new Word("Yo"), // 0xbe
  new Word("Yo"), // 0xbf
  new Word("Yo"), // 0xc0
  new Word("Yo"), // 0xc1
  new Word("Yo"), // 0xc2
  new Word("Yo"), // 0xc3
  new Word("Yong"), // 0xc4
  new Word("Wun"), // 0xc5
  new Word("Wen"), // 0xc6
  new Word("Yu"), // 0xc7
  new Word("Yu"), // 0xc8
  new Word("Yu"), // 0xc9
  new Word("Yu"), // 0xca
  new Word("Yu"), // 0xcb
  new Word("Yu"), // 0xcc
  new Word("Yu"), // 0xcd
  new Word("Yu"), // 0xce
  new Word("Yu"), // 0xcf
  new Word("Yu"), // 0xd0
  new Word("Yuk"), // 0xd1
  new Word("Yuk"), // 0xd2
  new Word("Yuk"), // 0xd3
  new Word("Yun"), // 0xd4
  new Word("Yun"), // 0xd5
  new Word("Yun"), // 0xd6
  new Word("Yun"), // 0xd7
  new Word("Yul"), // 0xd8
  new Word("Yul"), // 0xd9
  new Word("Yul"), // 0xda
  new Word("Yul"), // 0xdb
  new Word("Yung"), // 0xdc
  new Word("I"), // 0xdd
  new Word("I"), // 0xde
  new Word("I"), // 0xdf
  new Word("I"), // 0xe0
  new Word("I"), // 0xe1
  new Word("I"), // 0xe2
  new Word("I"), // 0xe3
  new Word("I"), // 0xe4
  new Word("I"), // 0xe5
  new Word("I"), // 0xe6
  new Word("I"), // 0xe7
  new Word("I"), // 0xe8
  new Word("I"), // 0xe9
  new Word("I"), // 0xea
  new Word("Ik"), // 0xeb
  new Word("Ik"), // 0xec
  new Word("In"), // 0xed
  new Word("In"), // 0xee
  new Word("In"), // 0xef
  new Word("In"), // 0xf0
  new Word("In"), // 0xf1
  new Word("In"), // 0xf2
  new Word("In"), // 0xf3
  new Word("Im"), // 0xf4
  new Word("Im"), // 0xf5
  new Word("Im"), // 0xf6
  new Word("Ip"), // 0xf7
  new Word("Ip"), // 0xf8
  new Word("Ip"), // 0xf9
  new Word("Cang"), // 0xfa
  new Word("Cek"), // 0xfb
  new Word("Ci"), // 0xfc
  new Word("Cip"), // 0xfd
  new Word("Cha"), // 0xfe
  new Word("Chek") // 0xff
  };
}